From PolynomialFormulas Require Import
  Basic Cubic CubicComplex Quartic AbelRuffini AbelRuffiniRootwise
  LowDegreeRadicals
  QuinticRadicalDecidability SexticRecursiveCore SexticFactorCompleteness
  QuinticRecursiveFactor SexticFactorSelector
  QuinticF20Data QuinticSolvableCriterion QuinticThetaOrbit
  QuinticThetaValues QuinticGaloisAction QuinticGaloisCriterion
  QuinticThetaGaloisBridge
  SexticSparsePolynomials SexticSparseResolvents SexticSparseSymmetricSearch
  SexticPowerSumSymmetric SexticNewtonPowerSums SexticResolventSymmetry
  SexticComputedResolvents SexticRationalRootSearch
  SexticComputedResolventBridge
  SexticSeparatingSearch
  SexticSeparatingExistence
  SexticSeparatingSelector
  SexticTotalSeparatingSelector
  SexticDescriptorAction
  SexticGaloisAction
  SexticVietaBridge
  SexticDescriptorGaloisCriterion
  SexticReducibleSemantics
  ReducibleRadicalSemantics
  SexticRadicalDecidability.

(** Kernel-assumption audit for the degree-one-through-four solver theorems
    and the Abel--Ruffini obstruction above degree four. *)

Import LeanProofs.PolynomialFormulas.
Import LeanProofs.PolynomialFormulasCubic.
Import LeanProofs.PolynomialFormulasQuartic.
Import LeanProofs.PolynomialFormulasAbelRuffini.
Import PolynomialFormulasAbelRuffiniRootwise.
Import PolynomialFormulasLowDegreeRadicals.
Import PolynomialFormulasQuinticRadicalDecidability.
Import PolynomialFormulasSexticRecursiveCore.
Import PolynomialFormulasSexticFactorCompleteness.
Import PolynomialFormulasQuinticRecursiveFactor.
Import PolynomialFormulasSexticFactorSelector.
Import PolynomialFormulasQuinticF20Data.
Import PolynomialFormulasQuinticSolvableCriterion.
Import PolynomialFormulasQuinticThetaOrbit.
Import PolynomialFormulasQuinticThetaValues.
Import PolynomialFormulasQuinticGaloisAction.
Import PolynomialFormulasQuinticGaloisCriterion.
Import PolynomialFormulasQuinticThetaGaloisBridge.
Import PolynomialFormulasSexticSparsePolynomials.
Import PolynomialFormulasSexticSparseResolvents.
Import PolynomialFormulasSexticSparseSymmetricSearch.
Import PolynomialFormulasSexticPowerSumSymmetric.
Import PolynomialFormulasSexticNewtonPowerSums.
Import PolynomialFormulasSexticResolventSymmetry.
Import PolynomialFormulasSexticComputedResolvents.
Import PolynomialFormulasSexticRationalRootSearch.
Import PolynomialFormulasSexticComputedResolventBridge.
Import PolynomialFormulasSexticSeparatingSearch.
Import PolynomialFormulasSexticSeparatingExistence.
Import PolynomialFormulasSexticSeparatingSelector.
Import PolynomialFormulasSexticTotalSeparatingSelector.
Import PolynomialFormulasSexticDescriptorAction.
Import PolynomialFormulasSexticGaloisAction.
Import PolynomialFormulasSexticVietaBridge.
Import PolynomialFormulasSexticDescriptorGaloisCriterion.
Import PolynomialFormulasSexticReducibleSemantics.
Import PolynomialFormulasReducibleRadicalSemantics.
Import PolynomialFormulasSexticRadicalDecidability.

Check solve_linear_correct.
Check solve_quadratic_correct.
Check cardano_formula.
Check solve_cubic_correct.
Check ferrari_parameters_of_resolvent.
Check solve_quartic_correct.
Check LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_correct.
Check LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_exhaustive.
Check LeanProofs.PolynomialFormulasCubicComplex.cubic_eq_zero_iff.
Check solve_quartic_exhaustive.
Check quartic_eq_zero_iff.
Check quintic_no_radical_formula.
Check algterm_eval_aut.
Check quintic_roots_conjugate.
Check quintic_root_has_no_radical_expression.
Check quintic_every_root_has_no_radical_expression.
Check padded_no_radical_formula.
Check padded_not_solvable_by_radicals.
Check monic_padded_counterexample.
Check degree_gt_four_counterexample.
Check not_every_degree_gt_four_solvable_by_radicals.
Check no_radical_formula_degree_gt_four.
Check low_degree_radical_formula.
Check galois_solvableP.
Check every_root_has_radical_expressionP.
Check quintic_every_root_has_radical_expressionP.
Check integer_radical_decisionP.
Check quintic_radical_decision_codeK.
Check quintic_radical_decision_codeP.
Check has_bounded_proper_factorP.
Check selected_sextic_linear_factorization_quintic.
Check theta_stabilizerE.
Check solvable_transitive_S5_criterion.
Check theta_table_orbit_exhaustive_exists.
Check quintic_scalar_resolvent_permute.
Check quintic_scalar_resolvent_rootP.
Check quintic_root_tuple_injective.
Check quintic_galois_image_transitive.
Check quintic_galois_image_solvableE.
Check quintic_galois_solvable_F20b.
Check contained_in_conjugate_F20b_theta_orbitE.
Check quintic_galois_solvable_iff_stable_theta_orbit.
Check sparse_equivalentbP.
Check sparse_equivalentb_eval.
Check size_pair_sparse_resolvent.
Check size_triple_sparse_resolvent.
Check coefficient_list_eval_pair_resolvent.
Check coefficient_list_eval_triple_resolvent.
Check elementary_certificate_eval.
Check elementary_certificate_eventually.
Check injective_assignment_sum_power_formula.
Check newton_sparse_power_correct.
Check newton_symmetrize_invariant_correct.
Check pair_sparse_resolvent_coefficient_invariant.
Check triple_sparse_resolvent_coefficient_invariant.
Check pair_scaled_resolvent_coefficient_correct_unconditional.
Check triple_scaled_resolvent_coefficient_correct_unconditional.
Check denq_dvd_leading_coefficient.
Check numq_dvd_constant_coefficient.
Check has_bounded_rational_root_of_rational.
Check rational_rootP.
Check pair_scaled_rational_rootP.
Check triple_scaled_rational_rootP.
Check pair_scaled_resolvent_poly_correct.
Check triple_scaled_resolvent_poly_correct.
Check pair_scaled_semantic_rational_rootP.
Check triple_scaled_semantic_rational_rootP.
Check pair_semantic_root_iff_rational_descriptor.
Check triple_semantic_root_iff_rational_descriptor.
Check pair_scaled_rational_descriptorP.
Check triple_scaled_rational_descriptorP.
Check collision_product_neq0_iff.
Check pair_sparse_collision_invariant.
Check triple_sparse_collision_invariant.
Check pair_scaled_collision_value_correct.
Check triple_scaled_collision_value_correct.
Check pair_separatesP.
Check triple_separatesP.
Check pair_separating_search_eventually.
Check triple_separating_search_eventually.
Check exists_nat_horner_ne_zero.
Check exists_nat_bipoly_eval_ne_zero.
Check pair_descriptor_bipolynomial_injective.
Check triple_descriptor_bipolynomial_injective.
Check exists_pair_descriptor_injective.
Check exists_triple_descriptor_injective.
Check pair_separating_search_terminates.
Check triple_separating_search_terminates.
Check first_true_indexP.
Check first_true_index_minimal.
Check first_true_index_proof_irrelevant.
Check pair_separating_parameter_from_roots_injective.
Check triple_separating_parameter_from_roots_injective.
Check proper_rational_divisor_has_small_factor.
Check no_bounded_proper_factor_irreducible.
Check pair_total_separates_eventually_of_roots.
Check triple_total_separates_eventually_of_roots.
Check pair_descriptor_perm.
Check triple_descriptor_perm.
Check pair_partition_action_fixedP.
Check triple_partition_action_fixedP.
Check sextic_galois_image_transitive.
Check sextic_galois_image_solvableE.
Check fixed_iff_rational.
Check quintic_theta_value_gal.
Check quintic_theta_value_fixed_iff_stable.
Check exists_rational_quintic_theta_value_iff_galois_solvable.
Check quintic_scalar_resolvent_has_rational_root_iff_galois_solvable.
Check prod_XsubC_sixE.
Check monic_sextic_vieta.
Check pair_descriptor_rational_iff_stabilizer.
Check triple_descriptor_rational_iff_stabilizer.
Check sextic_galois_solvable_iff_rational_descriptors.
Check sextic_scaled_resolvent_solvableP.
Check radical_formula_solves_mul.
Check radical_formula_solves_scale.
Check all_roots_radical_int_mul.
Check all_roots_radical_int_scale.
Check reducible_quintic_radical_formula.
Check bounded_linear_factor_radical_formula.
Check bounded_nonlinear_factor_radical_formula.
Check all_roots_radical_sextic_int_semantic_decidable.
Check sextic_radical_semantic_codeP.

Print Assumptions solve_linear_correct.
Print Assumptions solve_quadratic_correct.
Print Assumptions cardano_formula.
Print Assumptions solve_cubic_correct.
Print Assumptions ferrari_parameters_of_resolvent.
Print Assumptions solve_quartic_correct.
Print Assumptions LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_correct.
Print Assumptions LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_exhaustive.
Print Assumptions LeanProofs.PolynomialFormulasCubicComplex.cubic_eq_zero_iff.
Print Assumptions solve_quartic_exhaustive.
Print Assumptions quartic_eq_zero_iff.
Print Assumptions quintic_no_radical_formula.
Print Assumptions algterm_eval_aut.
Print Assumptions quintic_roots_conjugate.
Print Assumptions quintic_root_has_no_radical_expression.
Print Assumptions quintic_every_root_has_no_radical_expression.
Print Assumptions padded_no_radical_formula.
Print Assumptions padded_not_solvable_by_radicals.
Print Assumptions monic_padded_counterexample.
Print Assumptions degree_gt_four_counterexample.
Print Assumptions not_every_degree_gt_four_solvable_by_radicals.
Print Assumptions no_radical_formula_degree_gt_four.
Print Assumptions low_degree_radical_formula.
Print Assumptions galois_solvableP.
Print Assumptions every_root_has_radical_expressionP.
Print Assumptions quintic_every_root_has_radical_expressionP.
Print Assumptions integer_radical_decisionP.
Print Assumptions quintic_radical_decision_codeK.
Print Assumptions quintic_radical_decision_codeP.
Print Assumptions has_bounded_proper_factorP.
Print Assumptions selected_sextic_linear_factorization_quintic.
Print Assumptions theta_stabilizerE.
Print Assumptions solvable_transitive_S5_criterion.
Print Assumptions theta_table_orbit_exhaustive_exists.
Print Assumptions quintic_scalar_resolvent_permute.
Print Assumptions quintic_scalar_resolvent_rootP.
Print Assumptions quintic_root_tuple_injective.
Print Assumptions quintic_galois_image_transitive.
Print Assumptions quintic_galois_image_solvableE.
Print Assumptions quintic_galois_solvable_F20b.
Print Assumptions contained_in_conjugate_F20b_theta_orbitE.
Print Assumptions quintic_galois_solvable_iff_stable_theta_orbit.
Print Assumptions sparse_equivalentbP.
Print Assumptions sparse_equivalentb_eval.
Print Assumptions size_pair_sparse_resolvent.
Print Assumptions size_triple_sparse_resolvent.
Print Assumptions coefficient_list_eval_pair_resolvent.
Print Assumptions coefficient_list_eval_triple_resolvent.
Print Assumptions elementary_certificate_eval.
Print Assumptions elementary_certificate_eventually.
Print Assumptions injective_assignment_sum_power_formula.
Print Assumptions newton_sparse_power_correct.
Print Assumptions newton_symmetrize_invariant_correct.
Print Assumptions pair_sparse_resolvent_coefficient_invariant.
Print Assumptions triple_sparse_resolvent_coefficient_invariant.
Print Assumptions pair_scaled_resolvent_coefficient_correct_unconditional.
Print Assumptions triple_scaled_resolvent_coefficient_correct_unconditional.
Print Assumptions denq_dvd_leading_coefficient.
Print Assumptions numq_dvd_constant_coefficient.
Print Assumptions has_bounded_rational_root_of_rational.
Print Assumptions rational_rootP.
Print Assumptions pair_scaled_rational_rootP.
Print Assumptions triple_scaled_rational_rootP.
Print Assumptions pair_scaled_resolvent_poly_correct.
Print Assumptions triple_scaled_resolvent_poly_correct.
Print Assumptions pair_scaled_semantic_rational_rootP.
Print Assumptions triple_scaled_semantic_rational_rootP.
Print Assumptions pair_semantic_root_iff_rational_descriptor.
Print Assumptions triple_semantic_root_iff_rational_descriptor.
Print Assumptions pair_scaled_rational_descriptorP.
Print Assumptions triple_scaled_rational_descriptorP.
Print Assumptions collision_product_neq0_iff.
Print Assumptions pair_sparse_collision_invariant.
Print Assumptions triple_sparse_collision_invariant.
Print Assumptions pair_scaled_collision_value_correct.
Print Assumptions triple_scaled_collision_value_correct.
Print Assumptions pair_separatesP.
Print Assumptions triple_separatesP.
Print Assumptions pair_separating_search_eventually.
Print Assumptions triple_separating_search_eventually.
Print Assumptions exists_nat_horner_ne_zero.
Print Assumptions exists_nat_bipoly_eval_ne_zero.
Print Assumptions pair_descriptor_bipolynomial_injective.
Print Assumptions triple_descriptor_bipolynomial_injective.
Print Assumptions exists_pair_descriptor_injective.
Print Assumptions exists_triple_descriptor_injective.
Print Assumptions pair_separating_search_terminates.
Print Assumptions triple_separating_search_terminates.
Print Assumptions first_true_indexP.
Print Assumptions first_true_index_minimal.
Print Assumptions first_true_index_proof_irrelevant.
Print Assumptions pair_separating_parameter_from_roots_injective.
Print Assumptions triple_separating_parameter_from_roots_injective.
Print Assumptions proper_rational_divisor_has_small_factor.
Print Assumptions no_bounded_proper_factor_irreducible.
Print Assumptions pair_total_separates_eventually_of_roots.
Print Assumptions triple_total_separates_eventually_of_roots.
Print Assumptions pair_descriptor_perm.
Print Assumptions triple_descriptor_perm.
Print Assumptions pair_partition_action_fixedP.
Print Assumptions triple_partition_action_fixedP.
Print Assumptions sextic_galois_image_transitive.
Print Assumptions sextic_galois_image_solvableE.
Print Assumptions fixed_iff_rational.
Print Assumptions quintic_theta_value_gal.
Print Assumptions quintic_theta_value_fixed_iff_stable.
Print Assumptions exists_rational_quintic_theta_value_iff_galois_solvable.
Print Assumptions quintic_scalar_resolvent_has_rational_root_iff_galois_solvable.
Print Assumptions prod_XsubC_sixE.
Print Assumptions monic_sextic_vieta.
Print Assumptions pair_descriptor_rational_iff_stabilizer.
Print Assumptions triple_descriptor_rational_iff_stabilizer.
Print Assumptions sextic_galois_solvable_iff_rational_descriptors.
Print Assumptions sextic_scaled_resolvent_solvableP.
Print Assumptions radical_formula_solves_mul.
Print Assumptions radical_formula_solves_scale.
Print Assumptions all_roots_radical_int_mul.
Print Assumptions all_roots_radical_int_scale.
Print Assumptions reducible_quintic_radical_formula.
Print Assumptions bounded_linear_factor_radical_formula.
Print Assumptions bounded_nonlinear_factor_radical_formula.
Print Assumptions all_roots_radical_sextic_int_semantic_decidable.
Print Assumptions sextic_radical_semantic_codeP.
