From PolynomialFormulas Require Import
  Basic Cubic CubicComplex Quartic AbelRuffini AbelRuffiniRootwise
  QuinticRadicalDecidability SexticRecursiveCore SexticFactorCompleteness
  SexticSparsePolynomials SexticSparseResolvents SexticSparseSymmetricSearch
  SexticPowerSumSymmetric SexticNewtonPowerSums SexticResolventSymmetry
  SexticComputedResolvents SexticRationalRootSearch
  SexticComputedResolventBridge
  SexticSeparatingSearch
  SexticRadicalDecidability.

(** Kernel-assumption audit for the degree-one-through-four solver theorems
    and the Abel--Ruffini obstruction above degree four. *)

Import LeanProofs.PolynomialFormulas.
Import LeanProofs.PolynomialFormulasCubic.
Import LeanProofs.PolynomialFormulasQuartic.
Import LeanProofs.PolynomialFormulasAbelRuffini.
Import PolynomialFormulasAbelRuffiniRootwise.
Import PolynomialFormulasQuinticRadicalDecidability.
Import PolynomialFormulasSexticRecursiveCore.
Import PolynomialFormulasSexticFactorCompleteness.
Import PolynomialFormulasSexticSparsePolynomials.
Import PolynomialFormulasSexticSparseResolvents.
Import PolynomialFormulasSexticSparseSymmetricSearch.
Import PolynomialFormulasSexticPowerSumSymmetric.
Import PolynomialFormulasSexticNewtonPowerSums.
Import PolynomialFormulasSexticResolventSymmetry.
Import PolynomialFormulasSexticComputedResolvents.
Import PolynomialFormulasSexticRationalRootSearch.
Import PolynomialFormulasSexticComputedResolventBridge.
Import PolynomialFormulasSexticSeparatingSearch.
Import PolynomialFormulasSexticRadicalDecidability.

Check solve_linear_correct.
Check solve_quadratic_correct.
Check cardano_formula.
Check solve_cubic_correct.
Check ferrari_parameters_of_resolvent.
Check solve_quartic_correct.
Check LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_correct.
Check LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_exhaustive.
Check LeanProofs.PolynomialFormulasCubicComplex.cubic_eq_zero_iff.
Check solve_quartic_exhaustive.
Check quartic_eq_zero_iff.
Check quintic_no_radical_formula.
Check algterm_eval_aut.
Check quintic_roots_conjugate.
Check quintic_root_has_no_radical_expression.
Check quintic_every_root_has_no_radical_expression.
Check padded_no_radical_formula.
Check padded_not_solvable_by_radicals.
Check monic_padded_counterexample.
Check degree_gt_four_counterexample.
Check not_every_degree_gt_four_solvable_by_radicals.
Check no_radical_formula_degree_gt_four.
Check galois_solvableP.
Check every_root_has_radical_expressionP.
Check quintic_every_root_has_radical_expressionP.
Check integer_radical_decisionP.
Check quintic_radical_decision_codeK.
Check quintic_radical_decision_codeP.
Check has_bounded_proper_factorP.
Check sparse_equivalentbP.
Check sparse_equivalentb_eval.
Check size_pair_sparse_resolvent.
Check size_triple_sparse_resolvent.
Check coefficient_list_eval_pair_resolvent.
Check coefficient_list_eval_triple_resolvent.
Check elementary_certificate_eval.
Check elementary_certificate_eventually.
Check injective_assignment_sum_power_formula.
Check newton_sparse_power_correct.
Check newton_symmetrize_invariant_correct.
Check pair_sparse_resolvent_coefficient_invariant.
Check triple_sparse_resolvent_coefficient_invariant.
Check pair_scaled_resolvent_coefficient_correct_unconditional.
Check triple_scaled_resolvent_coefficient_correct_unconditional.
Check denq_dvd_leading_coefficient.
Check numq_dvd_constant_coefficient.
Check has_bounded_rational_root_of_rational.
Check rational_rootP.
Check pair_scaled_rational_rootP.
Check triple_scaled_rational_rootP.
Check pair_scaled_resolvent_poly_correct.
Check triple_scaled_resolvent_poly_correct.
Check pair_scaled_semantic_rational_rootP.
Check triple_scaled_semantic_rational_rootP.
Check collision_product_neq0_iff.
Check pair_sparse_collision_invariant.
Check triple_sparse_collision_invariant.
Check pair_scaled_collision_value_correct.
Check triple_scaled_collision_value_correct.
Check pair_separatesP.
Check triple_separatesP.
Check pair_separating_search_eventually.
Check triple_separating_search_eventually.
Check all_roots_radical_sextic_int_semantic_decidable.
Check sextic_radical_semantic_codeP.

Print Assumptions solve_linear_correct.
Print Assumptions solve_quadratic_correct.
Print Assumptions cardano_formula.
Print Assumptions solve_cubic_correct.
Print Assumptions ferrari_parameters_of_resolvent.
Print Assumptions solve_quartic_correct.
Print Assumptions LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_correct.
Print Assumptions LeanProofs.PolynomialFormulasCubicComplex.solve_cubic_exhaustive.
Print Assumptions LeanProofs.PolynomialFormulasCubicComplex.cubic_eq_zero_iff.
Print Assumptions solve_quartic_exhaustive.
Print Assumptions quartic_eq_zero_iff.
Print Assumptions quintic_no_radical_formula.
Print Assumptions algterm_eval_aut.
Print Assumptions quintic_roots_conjugate.
Print Assumptions quintic_root_has_no_radical_expression.
Print Assumptions quintic_every_root_has_no_radical_expression.
Print Assumptions padded_no_radical_formula.
Print Assumptions padded_not_solvable_by_radicals.
Print Assumptions monic_padded_counterexample.
Print Assumptions degree_gt_four_counterexample.
Print Assumptions not_every_degree_gt_four_solvable_by_radicals.
Print Assumptions no_radical_formula_degree_gt_four.
Print Assumptions galois_solvableP.
Print Assumptions every_root_has_radical_expressionP.
Print Assumptions quintic_every_root_has_radical_expressionP.
Print Assumptions integer_radical_decisionP.
Print Assumptions quintic_radical_decision_codeK.
Print Assumptions quintic_radical_decision_codeP.
Print Assumptions has_bounded_proper_factorP.
Print Assumptions sparse_equivalentbP.
Print Assumptions sparse_equivalentb_eval.
Print Assumptions size_pair_sparse_resolvent.
Print Assumptions size_triple_sparse_resolvent.
Print Assumptions coefficient_list_eval_pair_resolvent.
Print Assumptions coefficient_list_eval_triple_resolvent.
Print Assumptions elementary_certificate_eval.
Print Assumptions elementary_certificate_eventually.
Print Assumptions injective_assignment_sum_power_formula.
Print Assumptions newton_sparse_power_correct.
Print Assumptions newton_symmetrize_invariant_correct.
Print Assumptions pair_sparse_resolvent_coefficient_invariant.
Print Assumptions triple_sparse_resolvent_coefficient_invariant.
Print Assumptions pair_scaled_resolvent_coefficient_correct_unconditional.
Print Assumptions triple_scaled_resolvent_coefficient_correct_unconditional.
Print Assumptions denq_dvd_leading_coefficient.
Print Assumptions numq_dvd_constant_coefficient.
Print Assumptions has_bounded_rational_root_of_rational.
Print Assumptions rational_rootP.
Print Assumptions pair_scaled_rational_rootP.
Print Assumptions triple_scaled_rational_rootP.
Print Assumptions pair_scaled_resolvent_poly_correct.
Print Assumptions triple_scaled_resolvent_poly_correct.
Print Assumptions pair_scaled_semantic_rational_rootP.
Print Assumptions triple_scaled_semantic_rational_rootP.
Print Assumptions collision_product_neq0_iff.
Print Assumptions pair_sparse_collision_invariant.
Print Assumptions triple_sparse_collision_invariant.
Print Assumptions pair_scaled_collision_value_correct.
Print Assumptions triple_scaled_collision_value_correct.
Print Assumptions pair_separatesP.
Print Assumptions triple_separatesP.
Print Assumptions pair_separating_search_eventually.
Print Assumptions triple_separating_search_eventually.
Print Assumptions all_roots_radical_sextic_int_semantic_decidable.
Print Assumptions sextic_radical_semantic_codeP.
