From PolynomialFormulas Require Import
  LazardQuinticSectionFiveCombinedAction.

(** Focused kernel-assumption audit for the corrected Section 5 action. *)

Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_phi_psi_commute.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_primitive_fifth_root_cases.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_T_phi_eq_neg_printed_U.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_printed_U_phi_eq_T.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_fourier_s_o0_eq_zero.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_cyclic_S_five_cycle_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_x0_recovery.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_fourier_orbit_phi_psi_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_fourier_s_phi_psi_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_cyclic_S_phi_psi_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_quadratic_triple_phi_psi_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_fourier_fifth_orbit_phi_psi_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_omega_squared_independent_of_phi_invariant.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_all_primitive_fifth_roots_independent.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_printed_section_five_forward_source_eq_phi_iterates.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_eq_printed_I1_I2_I3_neg_I4.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_phi_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_phi_psi_fixed.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_squared.
Check
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_all_primitive.

Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_phi_psi_commute.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_primitive_fifth_root_cases.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_T_phi_eq_neg_printed_U.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_printed_U_phi_eq_T.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_fourier_s_o0_eq_zero.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_cyclic_S_five_cycle_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_x0_recovery.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_fourier_orbit_phi_psi_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_fourier_s_phi_psi_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_section_five_cyclic_S_phi_psi_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_quadratic_triple_phi_psi_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_fourier_fifth_orbit_phi_psi_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_omega_squared_independent_of_phi_invariant.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_all_primitive_fifth_roots_independent.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_printed_section_five_forward_source_eq_phi_iterates.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_eq_printed_I1_I2_I3_neg_I4.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_phi_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_phi_psi_fixed.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_squared.
Print Assumptions
  PolynomialFormulasLazardQuinticSectionFiveCombinedAction.lazard_root_formula_convention_projection_values_all_primitive.
