(** Public surface and kernel-assumption audit for the generic Foundation port. *)

From Foundation.Syntax.Predicate Require Import Language Term Quantifier.
From Foundation.FirstOrder.Basic.Syntax Require Import Formula.
From Foundation.Syntax.Predicate Require Import Rew.
From Foundation.FirstOrder.Basic Require Import Operator.
From Foundation.FirstOrder.Basic.Semantics Require Import Semantics.
From Foundation.FirstOrder.Basic.Semantics Require Import OperatorSemantics.
From Foundation.FirstOrder.Basic.Semantics Require Import ModelTheory.
From Foundation.Syntax.Predicate Require Import Relational.

Check language.
Check language_relational.
Check language_is_constant.
Check empty_language.
Check graph_language.
Check binary_language.
Check equality_language.
Check oring_language.
Check constant_language.
Check language_add.
Check language_sigma.
Check language_oring.
Check oring_language_structure.
Check language_hom.
Check language_hom_id.
Check language_hom_comp.
Check language_hom_add_left.
Check language_hom_add_right.
Check language_hom_sigma.
Check language_hom_add_left_func.
Check language_hom_add_left_rel.
Check language_hom_add_right_func.
Check language_hom_add_right_rel.
Check language_hom_sigma_func.
Check language_hom_sigma_rel.
Check language_hom_ext.
Check language_hom_comp_id_left.
Check language_hom_comp_id_right.
Check language_hom_comp_assoc.
Check oring_embedding.
Check language_decidable_eq.
Check equality_language_decidable_eq.
Check oring_language_decidable_eq.
Check encoding.
Check equality_language_encodable.
Check oring_language_encodable.
Check finite_cover.
Check language_finite.
Check oring_language_finite.

Check semiterm.
Check term.
Check closed_semiterm.
Check syntactic_term.
Check semiterm_from_free_default.
Check semiterm_from_constant.
Check fin_pointwise_eq_dec.
Check fin_function_eq_dec.
Check fin_function_pointwise_eq_dec.
Check semiterm_eq_dec.
Check semiterm_complexity.
Check semiterm_complexity_func_lt.
Check semiterm_bound_occurs.
Check semiterm_positive.
Check semiterm_positive_func.
Check semiterm_no_bound_occurs_of_positive_one.
Check semiterm_free_occurs.
Check semiterm_language_map.
Check semiterm_language_map_positive.
Check semiterm_language_map_free_occurs.
Check semiterm_language_map_id.
Check semiterm_language_map_comp.
Check semiterm_free_variable_list.
Check semiterm_free_variable_list_spec.
Check semiterm_index_of_free_variable.
Check semiterm_enumerate_free_variable.
Check semiterm_enumerate_index_of_free_variable.

Check polarity_alt_involutive.
Check sigma_pi_delta_alt_involutive.
Check sigma_pi_delta_alt_polarity.
Check first_universal_quantifier.
Check first_existential_quantifier.
Check first_quantifiers.
Check first_connectives_with_quantifiers.
Check first_all_closure.
Check first_all_iter.
Check first_exists_closure.
Check first_exists_iter.
Check first_bounded_all.
Check first_bounded_exists.
Check second_universal_quantifier.
Check second_existential_quantifier.
Check second_quantifiers.
Check second_connectives_with_quantifiers.
Check second_all_closure.
Check second_all_iter.
Check second_exists_closure.
Check second_exists_iter.
Check second_bounded_all.
Check second_bounded_exists.

Check semiformula.
Check semiformula_connectives.
Check semiformula_lcwq.
Check semiformula_neg_involutive.
Check semiformula_neg_all_closure.
Check semiformula_neg_exists_closure.
Check semiformula_neg_bounded_all.
Check semiformula_all_closure_injective.
Check semiformula_all_iter_injective.
Check semiformula_complexity.
Check semiformula_quantifier_rank.
Check semiformula_open.
Check semiformula_eq_dec.
Check semiformula_free_occurs.
Check semiformula_free_variable_list_spec.
Check semiformula_fv_sup_fresh.
Check semiformula_language_map.
Check semiformula_language_connective_hom.
Check semiformula_language_map_free_occurs.
Check semiformula_language_map_id.
Check semiformula_language_map_comp.
Check semiformula_language_map_all_iter.
Check semiformula_language_map_free_variable_list.
Check semiformula_enumerate_index_of_free_variable.
Check theory_language_map.

Check rew.
Check rew_equiv.
Check rew_id.
Check rew_comp.
Check rew_comp_assoc.
Check rew_bind.
Check rew_eta.
Check rew_equiv_of_variables.
Check rew_rewrite.
Check rew_rewrite_map.
Check rew_map.
Check rew_subst.
Check rew_emb.
Check rew_emb_substs.
Check rew_cast.
Check fin_cast_refl.
Check fin_cast_L_zero.
Check fin_cast_le.
Check fin_cast_le_refl.
Check rew_cast_le.
Check rew_cast_refl.
Check rew_cast_le_refl.
Check rew_subst_comp_subst.
Check rew_subst_comp_emb_substs.
Check rew_comp_emb_substs.
Check rew_emb_substs_variables.
Check rew_emb_substs_variables_empty.
Check rew_rewrite_comp_rewrite.
Check rew_bshift.
Check rew_bshift_add.
Check rew_bshift_add_zero_cast.
Check rew_bshift_comp_subst.
Check rew_shift_comp_subst.
Check rew_rewrite_comp_emb.
Check rew_shift_comp_emb.
Check rew_comp_emb_empty.
Check rew_subst_bound_occurs.
Check rew_subst_positive.
Check rew_emb_substs_bound_occurs.
Check rew_emb_substs_positive.
Check rew_q.
Check rew_q_bshift_apply.
Check rew_q_comp_apply.
Check rew_q_respects_equiv.
Check rew_qpow.
Check rew_shift.
Check rew_free.
Check rew_fix.
Check rew_shift_injective.
Check rew_free_comp_fix.
Check rew_fix_comp_free.
Check rew_free_bshift_eq_shift.
Check rew_bshift_positive.
Check rew_bshift_free_occurs.
Check rew_free_occurs_sources.
Check semiterm_language_map_rew_bind.
Check semiterm_language_map_rew_bshift.
Check semiterm_language_map_rew_shift.
Check semiterm_language_map_rew_free.
Check semiterm_language_map_rew_fix.
Check rew_q_shift.
Check rew_fix_iter.
Check rew_fix_iter_zero.
Check rew_fix_iter_succ.
Check rew_fix_iter_bvar.
Check rew_fix_iter_fvar_ge.
Check rew_fix_iter_fvar_lt.
Check semiterm_to_closed.
Check semiterm_emb_to_closed.
Check semiterm_emb_no_free_occurs.
Check semiterm_to_closed_emb.
Check semiformula_rewrite.
Check semiformula_rewrite_connective_hom.
Check semiformula_rewrite_all.
Check semiformula_rewrite_ext.
Check semiformula_rewrite_id.
Check semiformula_rewrite_comp.
Check semiformula_rewrite_all_iter.
Check semiformula_rewrite_exists_iter.
Check semiformula_rewrite_bounded_all.
Check semiformula_rewrite_complexity.
Check semiformula_rewrite_quantifier_rank.
Check semiformula_rewrite_open.
Check semiformula_rewrite_free_occurs_sources.
Check semiformula_substitute.
Check semiformula_substitute_id.
Check semiformula_substitute_comp.
Check semiformula_shift_injective.
Check semiformula_free_fix.
Check semiformula_fix_free.
Check rew_q_emb.
Check semiformula_to_closed.
Check semiformula_emb_to_closed.
Check semiformula_emb_no_free_occurs.
Check semiformula_free_bound.
Check semiformula_fix_all_free.
Check semiformula_fix_all_free_no_free.
Check semiformula_universal_closure_open.
Check semiformula_universal_closure_open_no_free.
Check semiformula_universal_closure.
Check semiformula_emb_universal_closure.
Check semiformula_universal_closure_open_id.

Check semiterm_operator.
Check semiterm_operator_fn.
Check semiterm_operator_apply.
Check semiterm_operator_const_apply.
Check semiterm_operator_fn_apply.
Check rew_semiterm_operator_apply.
Check semiterm_operator_comp.
Check semiterm_operator_comp_apply.
Check semiterm_operator_bvar.
Check semiterm_operator_bvar_apply.
Check semiterm_operator_comp_bvar_left.
Check semiterm_operator_comp_bvar_right.
Check semiterm_operator_comp_assoc.
Check semiterm_operator_apply_bound_occurs.
Check semiterm_operator_apply_positive.
Check semiterm_const_operator_positive.
Check semiterm_operator_foldr.
Check semiterm_operator_foldr_cons_apply.
Check fin_to_list.
Check semiterm_operator_iterr.
Check semiterm_operator_iterr_zero.
Check semiterm_operator_iterr_succ.
Check semiterm_has_zero_operator.
Check semiterm_has_one_operator.
Check semiterm_has_add_operator.
Check semiterm_has_mul_operator.
Check semiterm_has_exp_operator.
Check semiterm_has_sub_operator.
Check semiterm_has_div_operator.
Check semiterm_has_star_operator.
Check semiterm_godel_number_operator.
Check semiterm_zero_operator_of_language.
Check semiterm_one_operator_of_language.
Check semiterm_add_operator_of_language.
Check semiterm_mul_operator_of_language.
Check semiterm_exp_operator_of_language.
Check semiterm_star_operator_of_language.
Check semiterm_add_operator_positive.
Check semiterm_mul_operator_positive.
Check semiterm_exp_operator_positive.
Check semiterm_operator_numeral.
Check semiterm_operator_numeral_zero.
Check semiterm_operator_numeral_one.
Check semiterm_operator_numeral_succ_nonzero.
Check semiterm_operator_numeral_succ_succ.
Check semiterm_godel_number_of_encoding.
Check semiterm_operator_npow.
Check semiterm_operator_npow_zero.
Check semiterm_operator_npow_succ.
Check semiterm_operator_npow_positive.
Check fin_max_two.
Check semiterm_zero_operator_complexity.
Check semiterm_one_operator_complexity.
Check semiterm_add_operator_complexity.
Check semiterm_mul_operator_complexity.
Check semiformula_operator.
Check semiformula_operator_apply.
Check rew_semiformula_operator_apply.
Check semiformula_operator_comp.
Check semiformula_operator_comp_apply.
Check semiformula_operator_comp_bvar_right.
Check semiformula_operator_comp_assoc.
Check semiformula_operator_and.
Check semiformula_operator_or.
Check semiformula_operator_and_apply.
Check semiformula_operator_or_apply.
Check semiformula_has_eq_operator.
Check semiformula_has_lt_operator.
Check semiformula_has_le_operator.
Check semiformula_has_mem_operator.
Check semiformula_eq_operator_of_language.
Check semiformula_lt_operator_of_language.
Check semiformula_mem_operator_of_language.
Check semiformula_le_operator_of_eq_lt.
Check semiformula_le_operator_of_language.
Check semiformula_eq_operator_apply.
Check semiformula_lt_operator_apply.
Check semiformula_mem_operator_apply.
Check semiformula_le_operator_apply.
Check semiformula_rel_arity_injective.
Check semiformula_rewrite_binary_relation_preimage.
Check semiformula_rewrite_eq_operator_preimage.
Check semiformula_rewrite_lt_operator_preimage.
Check semiformula_rewrite_mem_operator_preimage.
Check semiformula_binary_relation_injective.
Check semiformula_eq_operator_injective.
Check semiformula_lt_operator_injective.
Check semiformula_mem_operator_injective.
Check semiformula_le_operator_injective.
Check semiformula_eq_operator_open.
Check semiformula_lt_operator_open.
Check semiformula_mem_operator_open.
Check semiformula_le_operator_open.
Check semiformula_ball_lt.
Check semiformula_bex_lt.
Check semiformula_ball_le.
Check semiformula_bex_le.
Check semiformula_ball_mem.
Check semiformula_bex_mem.

Check first_order_structure.
Check unit_first_order_structure.
Check first_order_structure_language_map.
Check carrier_equiv.
Check first_order_structure_transport.
Check fin_env_cons.
Check carrier_equiv_from_fin_env_cons.
Check semiterm_val.
Check closed_semiterm_val.
Check semiterm_val_rewrite.
Check semiterm_val_rewrite_free.
Check semiterm_val_rewrite_map.
Check semiterm_val_substitute.
Check semiterm_val_map.
Check semiterm_val_bshift.
Check semiterm_val_emb_substs.
Check semiterm_val_language_map.
Check semiterm_val_transport.
Check semiterm_val_free_ext.
Check semiformula_eval.
Check formula_eval.
Check sentence_realize.
Check semiformula_eval_neg.
Check semiformula_eval_imp.
Check semiformula_eval_bounded_all.
Check semiformula_eval_bounded_exists.
Check semiterm_val_rew_q_bvars.
Check semiterm_val_rew_q_fvars.
Check semiformula_eval_rewrite.
Check semiformula_eval_map.
Check semiformula_eval_substitute.
Check semiformula_eval_bshift.
Check semiformula_eval_emb_substs.
Check semiformula_eval_free_ext.
Check semiformula_eval_language_map.
Check semiformula_eval_transport.
Check semiterm_operator_val.
Check semiterm_val_operator_apply.
Check semiterm_operator_val_comp.
Check semiterm_operator_val_bvar.
Check semiterm_operator_val_fn.
Check semiterm_operator_val_transport.
Check semiformula_operator_eval.
Check semiformula_eval_operator_apply.
Check semiformula_operator_eval_comp.
Check semiformula_operator_eval_and.
Check semiformula_operator_eval_or.
Check semiformula_operator_eval_transport.
Check semiformula_eq_operator_eval_of_language.
Check semiformula_lt_operator_eval_of_language.
Check semiformula_mem_operator_eval_of_language.
Check structure_interprets_zero.
Check structure_interprets_one.
Check structure_interprets_add.
Check structure_interprets_mul.
Check structure_interprets_exp.
Check structure_interprets_eq.
Check structure_interprets_relation.
Check structure_interprets_lt.
Check structure_interprets_le.
Check structure_interprets_mem.
Check structure_interprets_le_of_eq_lt.
Check structure_interprets_le_of_eq_lt_spec.
Check semiterm_val_binary_bound.
Check semiformula_eval_bounded_operator_all.
Check semiformula_eval_bounded_operator_exists.
Check semiformula_eval_ball_lt.
Check semiformula_eval_bex_lt.
Check semiformula_eval_ball_le.
Check semiformula_eval_bex_le.
Check semiformula_eval_ball_mem.
Check semiformula_eval_bex_mem.
Check semiformula_eval_ball_relation.
Check semiformula_eval_bex_relation.
Check first_order_model.
Check first_order_model_of_structure.
Check first_order_model_realize.
Check first_order_semantics.
Check sentence_connectives.
Check first_order_tarski.
Check first_order_models_theory.
Check first_order_valid.
Check first_order_satisfiable.
Check first_order_consequence.
Check first_order_models_theory_iff.
Check first_order_models_of_member.
Check first_order_models_of_subset.
Check first_order_models_union_iff.
Check first_order_valid_iff.
Check first_order_satisfiable_iff.
Check first_order_unsatisfiable_iff.
Check first_order_satisfiable_intro.
Check first_order_consequence_iff.
Check first_order_consequence_iff_unsatisfiable.
Check first_order_consequence_weakening.
Check first_order_consequence_of_member.
Check first_order_model_theory.
Check first_order_model_theory_spec.
Check first_order_model_models_own_theory.
Check first_order_model_theory_satisfiable.
Check first_order_theory_subset_model_theory_iff.
Check first_order_model_language_pullback.
Check first_order_model_realize_language_map.
Check first_order_consequence_language_map.

Check semiterm_bvar_or_fvar_relational.
Check term_fvar_relational.
Check fin_cons.
Check semiterm_relational_val.
Check semiterm_relational_val_bvar.
Check semiterm_relational_val_fvar.
Check semiterm_relational_val_rew.
Check semiterm_relational_val_bshift.

Print Assumptions language_hom_ext.
Print Assumptions language_hom_comp_assoc.
Print Assumptions oring_function_symbols_complete.
Print Assumptions oring_language_finite.
Print Assumptions fin_function_pointwise_eq_dec.
Print Assumptions semiterm_eq_dec.
Print Assumptions semiterm_complexity_func_lt.
Print Assumptions semiterm_language_map_positive.
Print Assumptions semiterm_language_map_comp.
Print Assumptions semiterm_free_variable_list_spec.
Print Assumptions semiterm_enumerate_index_of_free_variable.
Print Assumptions semiterm_language_map_free_variable_list.
Print Assumptions polarity_alt_involutive.
Print Assumptions first_all_iter_succ.
Print Assumptions first_exists_iter_succ.
Print Assumptions second_all_iter_succ.
Print Assumptions second_exists_iter_succ.
Print Assumptions semiformula_neg_involutive.
Print Assumptions semiformula_neg_all_closure.
Print Assumptions semiformula_all_iter_injective.
Print Assumptions semiformula_eq_dec.
Print Assumptions semiformula_fv_sup_fresh.
Print Assumptions semiformula_language_connective_hom.
Print Assumptions semiformula_language_map_free_occurs.
Print Assumptions semiformula_language_map_id.
Print Assumptions semiformula_language_map_comp.
Print Assumptions semiformula_enumerate_index_of_free_variable.
Print Assumptions rew_comp_assoc.
Print Assumptions rew_eta.
Print Assumptions rew_equiv_of_variables.
Print Assumptions rew_subst_comp_subst.
Print Assumptions rew_subst_comp_emb_substs.
Print Assumptions rew_comp_emb_substs.
Print Assumptions rew_emb_substs_variables.
Print Assumptions rew_emb_substs_variables_empty.
Print Assumptions rew_cast_refl.
Print Assumptions rew_cast_le_refl.
Print Assumptions rew_bshift_add_zero_cast.
Print Assumptions rew_bshift_comp_subst.
Print Assumptions rew_shift_comp_subst.
Print Assumptions rew_rewrite_comp_emb.
Print Assumptions rew_comp_emb_empty.
Print Assumptions rew_subst_bound_occurs.
Print Assumptions rew_subst_positive.
Print Assumptions rew_emb_substs_bound_occurs.
Print Assumptions rew_emb_substs_positive.
Print Assumptions rew_q_bshift_apply.
Print Assumptions rew_q_comp_apply.
Print Assumptions rew_fix_iter_zero.
Print Assumptions rew_fix_iter_bvar.
Print Assumptions rew_fix_iter_fvar_ge.
Print Assumptions rew_fix_iter_fvar_lt.
Print Assumptions semiterm_emb_to_closed.
Print Assumptions semiterm_emb_no_free_occurs.
Print Assumptions semiterm_to_closed_emb.
Print Assumptions rew_shift_injective.
Print Assumptions rew_free_comp_fix.
Print Assumptions rew_fix_comp_free.
Print Assumptions rew_bshift_positive.
Print Assumptions rew_free_occurs_sources.
Print Assumptions semiterm_language_map_rew_bind.
Print Assumptions semiformula_rewrite_connective_hom.
Print Assumptions semiformula_rewrite_ext.
Print Assumptions semiformula_rewrite_id.
Print Assumptions semiformula_rewrite_comp.
Print Assumptions semiformula_rewrite_all_iter.
Print Assumptions semiformula_rewrite_complexity.
Print Assumptions semiformula_rewrite_quantifier_rank.
Print Assumptions semiformula_rewrite_open.
Print Assumptions semiformula_rewrite_free_occurs_sources.
Print Assumptions semiformula_substitute_comp.
Print Assumptions semiformula_shift_injective.
Print Assumptions semiformula_free_fix.
Print Assumptions semiformula_fix_free.
Print Assumptions rew_q_emb.
Print Assumptions semiformula_emb_to_closed.
Print Assumptions semiformula_emb_no_free_occurs.
Print Assumptions semiformula_fix_all_free_no_free.
Print Assumptions semiformula_universal_closure_open_no_free.
Print Assumptions semiformula_emb_universal_closure.
Print Assumptions semiformula_universal_closure_open_id.
Print Assumptions rew_semiterm_operator_apply.
Print Assumptions semiterm_operator_comp_assoc.
Print Assumptions semiterm_operator_apply_bound_occurs.
Print Assumptions semiterm_operator_apply_positive.
Print Assumptions semiterm_const_operator_positive.
Print Assumptions semiterm_operator_foldr_cons_apply.
Print Assumptions semiterm_add_operator_positive.
Print Assumptions semiterm_mul_operator_positive.
Print Assumptions semiterm_exp_operator_positive.
Print Assumptions semiterm_operator_numeral_succ_nonzero.
Print Assumptions semiterm_operator_iterr_succ.
Print Assumptions semiterm_operator_npow_positive.
Print Assumptions semiterm_add_operator_complexity.
Print Assumptions rew_semiformula_operator_apply.
Print Assumptions semiformula_operator_comp_assoc.
Print Assumptions semiformula_rewrite_binary_relation_preimage.
Print Assumptions semiformula_rewrite_eq_operator_preimage.
Print Assumptions semiformula_binary_relation_injective.
Print Assumptions semiformula_eq_operator_injective.
Print Assumptions semiformula_le_operator_injective.
Print Assumptions semiterm_val_rewrite.
Print Assumptions semiterm_val_language_map.
Print Assumptions semiterm_val_transport.
Print Assumptions semiterm_val_free_ext.
Print Assumptions semiformula_eval_neg.
Print Assumptions semiformula_eval_bounded_all.
Print Assumptions semiformula_eval_rewrite.
Print Assumptions semiformula_eval_free_ext.
Print Assumptions semiformula_eval_language_map.
Print Assumptions semiformula_eval_transport.
Print Assumptions semiterm_val_operator_apply.
Print Assumptions semiterm_operator_val_comp.
Print Assumptions semiterm_operator_val_transport.
Print Assumptions semiformula_eval_operator_apply.
Print Assumptions semiformula_operator_eval_comp.
Print Assumptions semiformula_operator_eval_transport.
Print Assumptions structure_interprets_le_of_eq_lt.
Print Assumptions structure_interprets_le_of_eq_lt_spec.
Print Assumptions semiformula_eval_bounded_operator_all.
Print Assumptions semiformula_eval_bounded_operator_exists.
Print Assumptions semiformula_eval_ball_relation.
Print Assumptions semiformula_eval_bex_relation.
Print Assumptions first_order_tarski.
Print Assumptions first_order_models_theory_iff.
Print Assumptions first_order_satisfiable_iff.
Print Assumptions first_order_unsatisfiable_iff.
Print Assumptions first_order_consequence_iff.
Print Assumptions first_order_consequence_iff_unsatisfiable.
Print Assumptions first_order_consequence_weakening.
Print Assumptions first_order_model_theory_satisfiable.
Print Assumptions first_order_model_realize_language_map.
Print Assumptions first_order_consequence_language_map.
Print Assumptions semiterm_bvar_or_fvar_relational.
Print Assumptions term_fvar_relational.
Print Assumptions semiterm_relational_val_rew.
Print Assumptions semiterm_relational_val_bshift.
