name = "Cardinals"
defaultTargets = ["Cardinals"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "ProveIt"
path = "../ProveIt"

[[lean_lib]]
name = "Cardinals"
