import Surreal.Surcomplex.FiniteTrigonometry
import Mathlib.Algebra.Star.Unitary
import Mathlib.Analysis.Complex.Circle
import Mathlib.GroupTheory.QuotientGroup.Basic

/-!
# The actual unit circle and finite-angle quotient

The group clauses of `trigonometry:thm:polar` use Mathlib's unitary group
and its first isomorphism theorem. The kernel consists of exactly the
ordinary integer multiples of `2*pi`; infinite angles are not introduced.
-/

universe u

namespace Surreal.Surcomplex

open Foundations

noncomputable section

/-- The actual surcomplex unit circle, with Mathlib's native unitary group structure. -/
abbrev UnitCircle := unitary Surcomplex.{u}

/-- The algebraic unitary condition is exactly actual modulus one. -/
theorem mem_unitCircle_iff (z : Surcomplex.{u}) : z ∈ unitary Surcomplex.{u} ↔ modulus z = 1 := by
  have he : z * star z = ofReal (modulus z ^ 2) := by
    change z * conj z = _
    rw [mul_conj, modulus_sq]
  rw [Unitary.mem_iff, mul_comm (star z) z, and_self, he]
  constructor
  · intro h
    have hs : modulus z ^ 2 = 1 := ofReal.injective (h.trans (map_one ofReal).symm)
    nlinarith [modulus_nonneg z]
  · intro h
    simp only [h, one_pow, map_one]

@[simp] theorem modulus_unitCircle (z : UnitCircle.{u}) : modulus z.val = 1 :=
  (mem_unitCircle_iff z.val).mp z.property

/-- Every direction has finite actual coordinates. -/
theorem isFinite_unitCircle (z : UnitCircle.{u}) : IsFinite z.val := by
  apply (isFinite_iff_modulus z.val).mpr
  rw [modulus_unitCircle]
  exact SignSequence.finite_one

/-- Phase as a homomorphism from the additive finite real angles onto the full circle. -/
def finitePhaseHom : Multiplicative SignSequence.FiniteElement.{u} →* UnitCircle.{u} where
  toFun θ := ⟨finitePhase θ.toAdd, (mem_unitCircle_iff _).mpr (modulus_finitePhase _)⟩
  map_one' := by apply Subtype.ext; exact finitePhase_zero
  map_mul' θ φ := by apply Subtype.ext; exact finitePhase_add θ.toAdd φ.toAdd

@[simp] theorem coe_finitePhaseHom (θ : Multiplicative SignSequence.FiniteElement.{u}) :
    (finitePhaseHom θ).val = finitePhase θ.toAdd := rfl

/-- Finite actual angles cover every direction. -/
theorem finitePhaseHom_surjective : Function.Surjective finitePhaseHom.{u} := by
  intro z
  obtain ⟨θ, hθ⟩ := exists_finitePhase_eq_of_modulus_eq_one z.val (modulus_unitCircle z)
  exact ⟨Multiplicative.ofAdd θ, Subtype.ext hθ⟩

/-- The kernel has precisely the ordinary integral periods. -/
theorem mem_finitePhaseHom_ker_iff (θ : Multiplicative SignSequence.FiniteElement.{u}) :
    θ ∈ finitePhaseHom.ker ↔ ∃ n : ℤ,
      θ.toAdd.val = SignSequence.ofReal ((n : ℝ) * (2 * Real.pi)) := by
  change finitePhaseHom θ = 1 ↔ _
  rw [Subtype.ext_iff]
  change finitePhase θ.toAdd = 1 ↔ _
  rw [← finitePhase_zero, finitePhase_eq_iff]
  simp only [ArchimedeanClass.FiniteElement.val_zero, sub_zero]

/-- The subgroup of ordinary periods, in multiplicative notation for finite angle addition. -/
def anglePeriods : Subgroup (Multiplicative SignSequence.FiniteElement.{u}) :=
  Subgroup.zpowers (Multiplicative.ofAdd (SignSequence.finiteOfReal (2 * Real.pi)))

/-- The phase kernel is literally the subgroup generated by the ordinary full turn. -/
theorem finitePhaseHom_ker_eq_anglePeriods : finitePhaseHom.ker = anglePeriods.{u} := by
  ext θ
  rw [mem_finitePhaseHom_ker_iff, anglePeriods, Subgroup.mem_zpowers_iff]
  constructor
  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    change n • SignSequence.finiteOfReal (2 * Real.pi) = θ.toAdd
    rw [← map_zsmul, zsmul_eq_mul]
    exact ArchimedeanClass.FiniteElement.ext hn.symm
  · rintro ⟨n, hn⟩
    change n • SignSequence.finiteOfReal (2 * Real.pi) = θ.toAdd at hn
    rw [← map_zsmul, zsmul_eq_mul] at hn
    exact ⟨n, congrArg (fun x : SignSequence.FiniteElement.{u} => x.val) hn.symm⟩

/-- Finite real angles modulo ordinary full turns are exactly the actual unit circle. -/
def angleQuotientEquiv :
    (Multiplicative SignSequence.FiniteElement.{u} ⧸ anglePeriods) ≃* UnitCircle.{u} :=
  (QuotientGroup.quotientMulEquivOfEq finitePhaseHom_ker_eq_anglePeriods.symm).trans
    (QuotientGroup.quotientKerEquivOfSurjective finitePhaseHom finitePhaseHom_surjective)

/-- The quotient isomorphism sends each angle class to its original phase. -/
@[simp] theorem angleQuotientEquiv_mk (θ : Multiplicative SignSequence.FiniteElement.{u}) :
    angleQuotientEquiv (QuotientGroup.mk θ) = finitePhaseHom θ := rfl

/-- Standard part of a unit direction is an ordinary complex unit direction. -/
def circleStandardPart : UnitCircle.{u} →* Circle where
  toFun z := ⟨standardPart z.val, by
    apply mem_sphere_zero_iff_norm.mpr
    have h := standardPart_modulus (isFinite_unitCircle z)
    rw [modulus_unitCircle, SignSequence.standardPart_one] at h
    exact h.symm⟩
  map_one' := by apply Circle.ext; exact standardPartHom.map_one
  map_mul' z w := by apply Circle.ext; exact standardPart_mul (isFinite_unitCircle z) (isFinite_unitCircle w)

@[simp] theorem coe_circleStandardPart (z : UnitCircle.{u}) :
    (circleStandardPart z : ℂ) = standardPart z.val := rfl

/-- Ordinary complex unit directions embed in the actual unit circle. -/
def circleOfComplex : Circle →* UnitCircle.{u} where
  toFun z := ⟨ofComplex z, (mem_unitCircle_iff _).mpr (by
    rw [modulus_ofComplex, Circle.norm_coe, map_one])⟩
  map_one' := by apply Subtype.ext; exact map_one ofComplex
  map_mul' z w := by apply Subtype.ext; exact map_mul ofComplex (z : ℂ) (w : ℂ)

@[simp] theorem coe_circleOfComplex (z : Circle) :
    (circleOfComplex z : Surcomplex.{u}) = ofComplex z := rfl

@[simp] theorem circleStandardPart_ofComplex (z : Circle) :
    circleStandardPart (circleOfComplex z : UnitCircle.{u}) = z := by
  apply Circle.ext
  exact standardPart_ofComplex z

end
end Surreal.Surcomplex
