(**
  The finite-model-property failure of KTMk.

  This module ports the proved surface of the pinned Foundation file
  [Modal/Kripke/Logic/KTMk.lean].  KTMk is the normal logic generated by T
  and Makinson's two-variable axiom Mk.  Its intended frames are reflexive
  frames satisfying [frame_makinson].

  The central result is deliberately stated for a fixed model, just as in
  Foundation: every finite model in which all KTMk theorems hold validates
  every instance of Four.  Starting from a failure of Four, Mk produces a
  world at the next box depth.  T makes worlds at distinct depths distinct,
  so an arbitrarily long list of such worlds contradicts an explicit finite
  cover.  This avoids Foundation's more elaborate list-chain construction.

  The pinned proof of canonicality for Mk, in [Modal/Kripke/AxiomMk.lean],
  is literally [sorry].  Consequently no canonical-completeness theorem is
  asserted here.  Soundness, consistency, the fixed-model finite theorem,
  the recession counterframe, failure of the finite model property, and the
  two strict hierarchy results are all proved without admissions.
*)

From Stdlib Require Import
  Lists.List Arith.PeanoNat Lia
  Logic.Classical_Prop Logic.ClassicalChoice.
From FoundationModal Require Import
  Syntax Axioms Kripke Correspondence CorrespondenceExtensions Filtration
  NormalHilbert CanonicalExtensions.

Import ListNotations.

Set Implicit Arguments.
Unset Strict Implicit.
Set Universe Polymorphism.

(** * Syntax, calculus, and frames *)

Definition Mk_axiom_schema : modal_axiom_schema :=
  fun AtomType p =>
    exists q r : formula AtomType, p = Mk q r.

Definition KTMk_schema : modal_axiom_schema :=
  schema_union schema_T Mk_axiom_schema.

Definition KTMk_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves KTMk_schema AtomType.

Lemma Mk_axiom_schema_substitution_closed :
  schema_substitution_closed Mk_axiom_schema.
Proof.
  intros A B sigma p [q [r ->]].
  exists (substitute sigma q), (substitute sigma r). reflexivity.
Qed.

Lemma KTMk_schema_substitution_closed :
  schema_substitution_closed KTMk_schema.
Proof.
  apply schema_union_substitution_closed.
  - exact schema_T_substitution_closed.
  - exact Mk_axiom_schema_substitution_closed.
Qed.

Definition KTMk_frame_class (F : frame) : Prop :=
  frame_reflexive F /\ frame_makinson F.

Definition KTMk_finite_frame_class (F : frame) : Prop :=
  finite_frame F /\ KTMk_frame_class F.

(** * Soundness and consistency *)

Lemma Mk_axiom_schema_valid_on_makinson :
  forall F,
    frame_makinson F -> schema_valid_on_frame Mk_axiom_schema F.
Proof.
  intros F HM AtomType p [q [r ->]].
  now apply valid_Mk_of_makinson.
Qed.

Theorem KTMk_proves_sound_on_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_reflexive F -> frame_makinson F ->
    KTMk_proves p -> valid F p.
Proof.
  intros AtomType F p HR HM Hp.
  eapply normal_proves_sound_on_frame; [| exact Hp].
  apply schema_union_valid_on_frame.
  - now apply schema_T_valid_on_reflexive.
  - now apply Mk_axiom_schema_valid_on_makinson.
Qed.

Corollary KTMk_proves_sound_on_class :
  forall (AtomType : Type) (p : formula AtomType),
    KTMk_proves p ->
    forall F, KTMk_frame_class F -> valid F p.
Proof.
  intros AtomType p Hp F [HR HM].
  now apply KTMk_proves_sound_on_frame.
Qed.

Lemma reflexive_singleton_makinson :
  frame_makinson reflexive_singleton_frame.
Proof.
  intros []. exists tt. repeat split; try constructor.
Qed.

Theorem KTMk_is_consistent :
  forall AtomType, ~ @KTMk_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := KTMk_schema) (F := reflexive_singleton_frame)).
  - now exists tt.
  - apply schema_union_valid_on_frame.
    + apply schema_T_valid_on_reflexive.
      exact reflexive_singleton_reflexive.
    + apply Mk_axiom_schema_valid_on_makinson.
      exact reflexive_singleton_makinson.
Qed.

(** * Fixed-model semantics *)

Definition KTMk_model {AtomType} (F : frame)
    (V : valuation AtomType F) : Prop :=
  forall p : formula AtomType,
    KTMk_proves p -> @model_valid AtomType F V p.

Arguments KTMk_model {AtomType} F V.

Lemma KTMk_model_valid_T :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    KTMk_model F V ->
    forall p : formula AtomType, @model_valid AtomType F V (T p).
Proof.
  intros AtomType F V HM p.
  apply HM. apply Np_extra. left. exists p. reflexivity.
Qed.

Lemma KTMk_model_valid_Mk :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    KTMk_model F V ->
    forall p q : formula AtomType, @model_valid AtomType F V (Mk p q).
Proof.
  intros AtomType F V HM p q.
  apply HM. apply Np_extra. right. exists p, q. reflexivity.
Qed.

(** T lowers a box iterate at every world of a KTMk model. *)
Lemma KTMk_model_box_iter_down_one :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    KTMk_model F V ->
    forall (p : formula AtomType) n w,
      satisfies F V w (box_iter (S n) p) ->
      satisfies F V w (box_iter n p).
Proof.
  intros AtomType F V HM p n w Hbox.
  exact (@KTMk_model_valid_T AtomType F V HM
    (box_iter n p) w Hbox).
Qed.

Lemma KTMk_model_box_iter_down :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    KTMk_model F V ->
    forall (p : formula AtomType) i j w,
      i <= j ->
      satisfies F V w (box_iter j p) ->
      satisfies F V w (box_iter i p).
Proof.
  intros AtomType F V HM p i j w Hij.
  induction Hij as [|j Hij IH].
  - trivial.
  - intro Hbox. apply IH.
    now apply (KTMk_model_box_iter_down_one HM).
Qed.

Definition KTMk_box_level {AtomType} (F : frame)
    (V : valuation AtomType F) (p : formula AtomType)
    (n : nat) (w : World F) : Prop :=
  satisfies F V w (box_iter (S n) p) /\
  ~ satisfies F V w (box_iter (S (S n)) p).

Arguments KTMk_box_level {AtomType} F V p n w.

(** Mk advances a failed box level by one accessible step. *)
Lemma KTMk_model_box_level_step :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    KTMk_model F V ->
    forall (p : formula AtomType) n w,
      KTMk_box_level F V p n w ->
      exists u, Rel F w u /\ KTMk_box_level F V p (S n) u.
Proof.
  intros AtomType F V HM p n w [Hbox Hnotbox].
  pose (a := box_iter n p).
  pose (q := Neg (Box (Box a))).
  assert (Hante : satisfies F V w (And (Box a) q)).
  {
    apply (proj2 (@satisfies_and AtomType F V w (Box a) q)).
    split; [exact Hbox | exact Hnotbox].
  }
  pose proof (@KTMk_model_valid_Mk AtomType F V HM a q w Hante)
    as Hmk.
  destruct (@satisfies_dia_elim AtomType F V w
    (And (Box (Box a)) (Dia q)) Hmk)
    as [u [Rwu Hu]].
  destruct (proj1 (@satisfies_and AtomType F V u
    (Box (Box a)) (Dia q)) Hu) as [Hnext Hdia].
  exists u. split; [exact Rwu |].
  split; [exact Hnext |].
  intro Htoo_far.
  destruct (@satisfies_dia_elim AtomType F V u q Hdia)
    as [z [Ruz Hzq]].
  apply Hzq. exact (Htoo_far z Ruz).
Qed.

(** Distinct levels cannot occur at the same world: the larger positive
    box iterate lowers, by T, to the smaller level's forbidden iterate. *)
Lemma KTMk_box_levels_distinct :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    KTMk_model F V ->
    forall (p : formula AtomType) i j x y,
      i < j ->
      KTMk_box_level F V p i x ->
      KTMk_box_level F V p j y ->
      x <> y.
Proof.
  intros AtomType F V HM p i j x y Hij
    [Hi Hnoti] [Hj Hnotj] Heq.
  subst y. apply Hnoti.
  eapply KTMk_model_box_iter_down; [exact HM | | exact Hj].
  lia.
Qed.

Lemma NoDup_map_of_injective :
  forall (A B : Type) (f : A -> B) (l : list A),
    (forall x y, f x = f y -> x = y) ->
    NoDup l -> NoDup (map f l).
Proof.
  intros A B f l Hinj Hnodup.
  induction Hnodup as [|x xs Hnotin Hnodup IH]; simpl.
  - constructor.
  - constructor.
    + intro Hin. apply in_map_iff in Hin.
      destruct Hin as [y [Hfy Hy]].
      assert (Hyx : y = x) by now apply Hinj.
      subst y. now apply Hnotin.
    + exact IH.
Qed.

(** * Finite KTMk models validate Four *)

Theorem KTMk_validate_Four_of_finite_model :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    finite_frame F -> KTMk_model F V ->
    forall p : formula AtomType, @model_valid AtomType F V (Four p).
Proof.
  intros AtomType F V [cover Hcover] HM p.
  apply NNPP. intro Hnotvalid.
  apply not_all_ex_not in Hnotvalid.
  destruct Hnotvalid as [w Hbad].
  assert (Hlevel0 : KTMk_box_level F V p 0 w).
  {
    unfold KTMk_box_level. simpl in *. tauto.
  }
  assert (Hlevels : forall n, exists x, KTMk_box_level F V p n x).
  {
    intro n. induction n as [|n [x Hx]].
    - now exists w.
    - destruct (KTMk_model_box_level_step HM Hx) as [y [_ Hy]].
      now exists y.
  }
  destruct (choice (fun n x => KTMk_box_level F V p n x) Hlevels)
    as [f Hf].
  assert (Hinjective : forall i j, f i = f j -> i = j).
  {
    intros i j Heq.
    destruct (Nat.lt_trichotomy i j) as [Hij | [Hij | Hij]].
    - exfalso. exact (KTMk_box_levels_distinct HM Hij (Hf i) (Hf j) Heq).
    - exact Hij.
    - exfalso. apply (KTMk_box_levels_distinct HM Hij (Hf j) (Hf i)).
      now symmetry.
  }
  pose (worlds := map f (seq 0 (S (length cover)))).
  assert (Hnodup : NoDup worlds).
  {
    unfold worlds. apply NoDup_map_of_injective.
    - exact Hinjective.
    - apply seq_NoDup.
  }
  assert (Hincl : incl worlds cover).
  {
    intros x Hx. apply Hcover.
  }
  pose proof (NoDup_incl_length Hnodup Hincl) as Hlength.
  unfold worlds in Hlength. rewrite length_map, length_seq in Hlength.
  lia.
Qed.

(** At the frame level the fixed-model theorem says that every finite
    reflexive Makinson frame is already transitive. *)
Corollary KTMk_finite_frame_valid_Four :
  forall (AtomType : Type) (F : frame),
    finite_frame F -> KTMk_frame_class F ->
    forall p : formula AtomType, valid F (Four p).
Proof.
  intros AtomType F Hfinite [HR HM] p V.
  apply (@KTMk_validate_Four_of_finite_model
    AtomType F V Hfinite).
  intros q Hq w.
  exact (@KTMk_proves_sound_on_frame AtomType F q HR HM Hq V w).
Qed.

Corollary KTMk_finite_frame_transitive :
  forall F : frame,
    finite_frame F -> KTMk_frame_class F -> frame_transitive F.
Proof.
  intros F Hfinite HKTMk.
  apply (proj1 (valid_Four_iff_transitive F)).
  exact (@KTMk_finite_frame_valid_Four nat F Hfinite HKTMk (Atom 0)).
Qed.

Corollary KTMk_model_infinite_of_not_Four :
  forall (AtomType : Type) (F : frame) (V : valuation AtomType F),
    KTMk_model F V ->
    (exists p : formula AtomType, ~ @model_valid AtomType F V (Four p)) ->
    ~ finite_frame F.
Proof.
  intros AtomType F V HM [p Hbad] Hfinite.
  apply Hbad.
  exact (@KTMk_validate_Four_of_finite_model
    AtomType F V Hfinite HM p).
Qed.

(** * The recession frame *)

Definition recession_frame : frame :=
  {| World := nat;
     Rel := fun i j => i <= S j |}.

Lemma recession_frame_reflexive :
  frame_reflexive recession_frame.
Proof. intro i. simpl. lia. Qed.

Lemma recession_frame_makinson :
  frame_makinson recession_frame.
Proof.
  intro i. exists (S i). repeat split; simpl; try lia.
  intros z Htwo. simpl in Htwo.
  destruct Htwo as [u [Hiu [v [Huv ->]]]]. simpl in *. lia.
Qed.

Lemma recession_frame_is_KTMk :
  KTMk_frame_class recession_frame.
Proof. split; [apply recession_frame_reflexive | apply recession_frame_makinson]. Qed.

Lemma recession_frame_not_transitive :
  ~ frame_transitive recession_frame.
Proof.
  intro HT. specialize (HT 2 1 0). simpl in HT.
  assert (H21 : 2 <= S 1) by lia.
  assert (H10 : 1 <= S 0) by lia.
  specialize (HT H21 H10). lia.
Qed.

Lemma recession_frame_not_valid_Four_atom :
  ~ valid recession_frame (Four (Atom 0)).
Proof.
  intro Hvalid. apply recession_frame_not_transitive.
  now apply (proj1 (valid_Four_iff_transitive recession_frame)).
Qed.

Theorem KTMk_exists_unprovable_Four :
  exists p : formula nat, ~ KTMk_proves (Four p).
Proof.
  exists (Atom 0). intro Hproof.
  apply recession_frame_not_valid_Four_atom.
  eapply KTMk_proves_sound_on_frame.
  - exact recession_frame_reflexive.
  - exact recession_frame_makinson.
  - exact Hproof.
Qed.

(** * Failure of the finite model property *)

Definition normal_finite_model_property
    (P : formula nat -> Prop) : Prop :=
  forall p : formula nat,
    ~ P p ->
    exists (F : frame) (V : valuation nat F) (w : World F),
      finite_frame F /\
      (forall q, P q -> @model_valid nat F V q) /\
      ~ satisfies F V w p.

Theorem KTMk_no_finite_model_property :
  ~ normal_finite_model_property (@KTMk_proves nat).
Proof.
  intro HFMP.
  destruct KTMk_exists_unprovable_Four as [p Hnotproof].
  destruct (HFMP (Four p) Hnotproof)
    as [F [V [w [Hfinite [HM Hbad]]]]].
  apply Hbad.
  exact (@KTMk_validate_Four_of_finite_model
    nat F V Hfinite HM p w).
Qed.

Corollary KTMk_non_theorem_valid_in_every_finite_model :
  exists p : formula nat,
    ~ KTMk_proves p /\
    forall (F : frame) (V : valuation nat F),
      finite_frame F -> KTMk_model F V -> @model_valid nat F V p.
Proof.
  destruct KTMk_exists_unprovable_Four as [p Hnot].
  exists (Four p). split; [exact Hnot |].
  intros F V Hfinite HM.
  exact (@KTMk_validate_Four_of_finite_model
    nat F V Hfinite HM p).
Qed.

(** * Strict hierarchy KT < KTMk < S4 *)

Lemma KT_weaker_than_KTMk :
  forall p : formula nat, KT_proves p -> KTMk_proves p.
Proof.
  intros p Hp. eapply normal_proves_weaken; [| exact Hp].
  intros AtomType q Hq. now left.
Qed.

Definition ktmk_separating_valuation : valuation nat reflexive_three_chain_frame :=
  fun a w =>
    match a with
    | 0 => w <> W2
    | 1 => w = W0
    | _ => True
    end.

Lemma reflexive_three_chain_not_valid_Mk :
  ~ valid reflexive_three_chain_frame (Mk (Atom 0) (Atom 1)).
Proof.
  intro Hvalid.
  specialize (Hvalid ktmk_separating_valuation W0).
  assert (Hante : satisfies reflexive_three_chain_frame
    ktmk_separating_valuation W0 (And (Box (Atom 0)) (Atom 1))).
  {
    apply (proj2 (@satisfies_and nat reflexive_three_chain_frame
      ktmk_separating_valuation W0 (Box (Atom 0)) (Atom 1))).
    split.
    - intros y Hy. destruct y; simpl in *; try discriminate.
      unfold three_chain_relation in Hy. intuition discriminate.
    - reflexivity.
  }
  pose proof (Hvalid Hante) as Hdia.
  destruct (@satisfies_dia_elim nat reflexive_three_chain_frame
    ktmk_separating_valuation W0
    (And (Box (Box (Atom 0))) (Dia (Atom 1))) Hdia)
    as [y [H0y Hy]].
  destruct (proj1 (@satisfies_and nat reflexive_three_chain_frame
    ktmk_separating_valuation y (Box (Box (Atom 0)))
    (Dia (Atom 1))) Hy) as [Hboxbox Hdiaone].
  destruct y.
  - specialize (Hboxbox W1).
    assert (H01 : Rel reflexive_three_chain_frame W0 W1).
    { right. left. auto. }
    specialize (Hboxbox H01 W2).
    assert (H12 : Rel reflexive_three_chain_frame W1 W2).
    { right. right. auto. }
    specialize (Hboxbox H12). exact (Hboxbox eq_refl).
  - specialize (Hboxbox W1).
    assert (H11 : Rel reflexive_three_chain_frame W1 W1) by now left.
    specialize (Hboxbox H11 W2).
    assert (H12 : Rel reflexive_three_chain_frame W1 W2).
    { right. right. auto. }
    specialize (Hboxbox H12). exact (Hboxbox eq_refl).
  - simpl in H0y. unfold three_chain_relation in H0y.
    intuition discriminate.
Qed.

Theorem KT_strictly_weaker_KTMk :
  normal_strictly_weaker (@KT_proves nat) (@KTMk_proves nat).
Proof.
  split.
  - exact KT_weaker_than_KTMk.
  - exists (Mk (Atom 0) (Atom 1)). split.
    + apply Np_extra. right. exists (Atom 0), (Atom 1). reflexivity.
    + intro HKT.
      apply reflexive_three_chain_not_valid_Mk.
      eapply KT_proves_sound_on_reflexive_frame.
      * exact reflexive_three_chain_reflexive.
      * exact HKT.
Qed.

Lemma preorder_makinson :
  forall F : frame,
    frame_reflexive F -> frame_transitive F -> frame_makinson F.
Proof.
  intros F HR HT x. exists x. repeat split.
  - apply HR.
  - apply HR.
  - intros z Htwo. simpl in Htwo.
    destruct Htwo as [y [Rxy [u [Ryu ->]]]].
    now apply (HT x y z).
Qed.

Lemma KTMk_weaker_than_S4 :
  forall p : formula nat, KTMk_proves p -> S4_proves p.
Proof.
  intros p Hp. apply S4_complete.
  intros F [HR HT].
  apply KTMk_proves_sound_on_frame.
  - exact HR.
  - now apply preorder_makinson.
  - exact Hp.
Qed.

Theorem KTMk_strictly_weaker_S4 :
  normal_strictly_weaker (@KTMk_proves nat) (@S4_proves nat).
Proof.
  split.
  - exact KTMk_weaker_than_S4.
  - destruct KTMk_exists_unprovable_Four as [p Hnot].
    exists (Four p). split.
    + apply Np_extra. right. exists p. reflexivity.
    + exact Hnot.
Qed.
