(**
  Normal Hilbert systems generated by additional modal axiom schemata.

  Foundation presents named systems such as KT, K4, S4, K5, S5, GL, and
  Grz as extensions of one common normal Hilbert calculus.  This module gives
  that abstraction directly in Coq.  An axiom schema is polymorphic in the
  atom type, so substitution closure can be stated once and inherited by
  every named system below.

  The module establishes the structural metatheory, embeds the concrete
  calculus [K_proves], and proves framewise soundness and consistency for the
  principal named systems.  Canonical completeness for extensions is kept
  separate: unlike soundness, it requires a Lindenbaum construction indexed
  by the chosen schema and proofs that its canonical frame has the desired
  relational properties.
*)

From FoundationModal Require Import
  Syntax Axioms HilbertK Kripke HilbertKSoundness Correspondence Loeb
  CorrespondenceExtensions.

Set Implicit Arguments.
Unset Strict Implicit.
Set Universe Polymorphism.

(** * Generic normal systems *)

Definition modal_axiom_schema : Type :=
  forall AtomType : Type, formula AtomType -> Prop.

Definition empty_schema : modal_axiom_schema :=
  fun _ _ => False.

Definition schema_union (Ax Ay : modal_axiom_schema) : modal_axiom_schema :=
  fun AtomType p => Ax AtomType p \/ Ay AtomType p.

Definition schema_included (Ax Ay : modal_axiom_schema) : Prop :=
  forall AtomType p, Ax AtomType p -> Ay AtomType p.

Definition schema_substitution_closed (Ax : modal_axiom_schema) : Prop :=
  forall (A B : Type) (sigma : A -> formula B) p,
    Ax A p -> Ax B (substitute sigma p).

Inductive normal_proves (Ax : modal_axiom_schema) {AtomType : Type}
    : formula AtomType -> Prop :=
| Np_imply_K : forall p q,
    normal_proves Ax (Hilbert_imply_K p q)
| Np_imply_S : forall p q r,
    normal_proves Ax (Hilbert_imply_S p q r)
| Np_elim_contra : forall p q,
    normal_proves Ax (Hilbert_elim_contra p q)
| Np_modal_K : forall p q,
    normal_proves Ax (K p q)
| Np_extra : forall p,
    Ax AtomType p -> normal_proves Ax p
| Np_mp : forall p q,
    normal_proves Ax (Imp p q) ->
    normal_proves Ax p ->
    normal_proves Ax q
| Np_nec : forall p,
    normal_proves Ax p -> normal_proves Ax (Box p).

Arguments Np_imply_K {Ax AtomType} p q.
Arguments Np_imply_S {Ax AtomType} p q r.
Arguments Np_elim_contra {Ax AtomType} p q.
Arguments Np_modal_K {Ax AtomType} p q.
Arguments Np_extra {Ax AtomType p} _.
Arguments Np_mp {Ax AtomType p q} _ _.
Arguments Np_nec {Ax AtomType p} _.

Lemma normal_proves_weaken :
  forall Ax Ay (Hinc : schema_included Ax Ay)
         (AtomType : Type) (p : formula AtomType),
    normal_proves Ax p -> normal_proves Ay p.
Proof.
  intros Ax Ay Hinc AtomType p Hp; induction Hp.
  - apply Np_imply_K.
  - apply Np_imply_S.
  - apply Np_elim_contra.
  - apply Np_modal_K.
  - apply Np_extra. now apply Hinc.
  - eapply Np_mp; eauto.
  - now apply Np_nec.
Qed.

Lemma normal_proves_substitute :
  forall Ax,
    schema_substitution_closed Ax ->
    forall (A B : Type) (sigma : A -> formula B) p,
      normal_proves Ax p ->
      normal_proves Ax (substitute sigma p).
Proof.
  intros Ax Hclosed A B sigma p Hp; induction Hp; simpl.
  - apply Np_imply_K.
  - apply Np_imply_S.
  - apply Np_elim_contra.
  - apply Np_modal_K.
  - apply Np_extra. now apply Hclosed.
  - eapply Np_mp; eauto.
  - now apply Np_nec.
Qed.

Lemma K_proves_normal :
  forall Ax (AtomType : Type) (p : formula AtomType),
    K_proves p -> normal_proves Ax p.
Proof.
  intros Ax AtomType p Hp; induction Hp.
  - apply Np_imply_K.
  - apply Np_imply_S.
  - apply Np_elim_contra.
  - apply Np_modal_K.
  - eapply Np_mp; eauto.
  - now apply Np_nec.
Qed.

Theorem empty_normal_proves_iff_K :
  forall (AtomType : Type) (p : formula AtomType),
    normal_proves empty_schema p <-> K_proves p.
Proof.
  intros AtomType p; split.
  - intro Hp; induction Hp.
    + apply Kp_imply_K.
    + apply Kp_imply_S.
    + apply Kp_elim_contra.
    + apply Kp_modal_K.
    + contradiction.
    + eapply Kp_mp; eauto.
    + now apply Kp_nec.
  - apply K_proves_normal.
Qed.

Lemma empty_schema_substitution_closed :
  schema_substitution_closed empty_schema.
Proof. intros A B sigma p H; contradiction. Qed.

Lemma schema_union_substitution_closed :
  forall Ax Ay,
    schema_substitution_closed Ax ->
    schema_substitution_closed Ay ->
    schema_substitution_closed (schema_union Ax Ay).
Proof.
  intros Ax Ay HAx HAy A B sigma p [Hp | Hp].
  - left. now apply HAx.
  - right. now apply HAy.
Qed.

(** * Named axiom schemata *)

Definition schema_T : modal_axiom_schema :=
  fun AtomType p => exists q : formula AtomType, p = T q.

Definition schema_D : modal_axiom_schema :=
  fun AtomType p => exists q : formula AtomType, p = D q.

Definition schema_B : modal_axiom_schema :=
  fun AtomType p => exists q : formula AtomType, p = B q.

Definition schema_Four : modal_axiom_schema :=
  fun AtomType p => exists q : formula AtomType, p = Four q.

Definition schema_Five : modal_axiom_schema :=
  fun AtomType p => exists q : formula AtomType, p = Five q.

Definition schema_L : modal_axiom_schema :=
  fun AtomType p => exists q : formula AtomType, p = L q.

Definition schema_Grz : modal_axiom_schema :=
  fun AtomType p => exists q : formula AtomType, p = Grz q.

Lemma schema_T_substitution_closed : schema_substitution_closed schema_T.
Proof. intros A B sigma p [q ->]. exists (substitute sigma q). reflexivity. Qed.

Lemma schema_D_substitution_closed : schema_substitution_closed schema_D.
Proof. intros A B sigma p [q ->]. exists (substitute sigma q). reflexivity. Qed.

Lemma schema_B_substitution_closed : schema_substitution_closed schema_B.
Proof. intros A B sigma p [q ->]. exists (substitute sigma q). reflexivity. Qed.

Lemma schema_Four_substitution_closed :
  schema_substitution_closed schema_Four.
Proof. intros A B sigma p [q ->]. exists (substitute sigma q). reflexivity. Qed.

Lemma schema_Five_substitution_closed :
  schema_substitution_closed schema_Five.
Proof. intros A B sigma p [q ->]. exists (substitute sigma q). reflexivity. Qed.

Lemma schema_L_substitution_closed : schema_substitution_closed schema_L.
Proof. intros A B sigma p [q ->]. exists (substitute sigma q). reflexivity. Qed.

Lemma schema_Grz_substitution_closed :
  schema_substitution_closed schema_Grz.
Proof. intros A B sigma p [q ->]. exists (substitute sigma q). reflexivity. Qed.

Definition K_normal_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves empty_schema AtomType.
Definition KT_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves schema_T AtomType.
Definition KD_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves schema_D AtomType.
Definition KB_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves schema_B AtomType.
Definition K4_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves schema_Four AtomType.
Definition K5_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves schema_Five AtomType.
Definition S4_schema := schema_union schema_T schema_Four.
Definition S4_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves S4_schema AtomType.
Definition S5_schema := schema_union schema_T schema_Five.
Definition S5_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves S5_schema AtomType.
Definition GL_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves schema_L AtomType.
Definition Grz_proves {AtomType} : formula AtomType -> Prop :=
  @normal_proves schema_Grz AtomType.

Lemma K_weaker_than_normal :
  forall Ax (AtomType : Type) (p : formula AtomType),
    K_normal_proves p -> normal_proves Ax p.
Proof.
  intros Ax AtomType p Hp.
  apply K_proves_normal.
  now apply (proj1 (empty_normal_proves_iff_K p)).
Qed.

Lemma KT_weaker_than_S4 :
  forall (AtomType : Type) (p : formula AtomType),
    KT_proves p -> S4_proves p.
Proof.
  intros AtomType p.
  apply normal_proves_weaken.
  intros A q Hq. now left.
Qed.

Lemma K4_weaker_than_S4 :
  forall (AtomType : Type) (p : formula AtomType),
    K4_proves p -> S4_proves p.
Proof.
  intros AtomType p.
  apply normal_proves_weaken.
  intros A q Hq. now right.
Qed.

Lemma KT_weaker_than_S5 :
  forall (AtomType : Type) (p : formula AtomType),
    KT_proves p -> S5_proves p.
Proof.
  intros AtomType p.
  apply normal_proves_weaken.
  intros A q Hq. now left.
Qed.

Lemma K5_weaker_than_S5 :
  forall (AtomType : Type) (p : formula AtomType),
    K5_proves p -> S5_proves p.
Proof.
  intros AtomType p.
  apply normal_proves_weaken.
  intros A q Hq. now right.
Qed.

(** * Generic and named soundness *)

Definition schema_valid_on_frame (Ax : modal_axiom_schema) (F : frame) : Prop :=
  forall (AtomType : Type) (p : formula AtomType), Ax AtomType p -> valid F p.

Theorem normal_proves_sound_on_frame :
  forall Ax (AtomType : Type) (F : frame) (p : formula AtomType),
    schema_valid_on_frame Ax F ->
    normal_proves Ax p -> valid F p.
Proof.
  intros Ax AtomType F p HAx Hp; induction Hp.
  - apply valid_Hilbert_imply_K.
  - apply valid_Hilbert_imply_S.
  - apply valid_Hilbert_elim_contra.
  - apply valid_K.
  - now apply HAx.
  - eapply valid_mp; eauto.
  - now apply valid_nec.
Qed.

Lemma schema_union_valid_on_frame :
  forall Ax Ay F,
    schema_valid_on_frame Ax F ->
    schema_valid_on_frame Ay F ->
    schema_valid_on_frame (schema_union Ax Ay) F.
Proof.
  intros Ax Ay F HAx HAy A p [Hp | Hp].
  - now apply HAx.
  - now apply HAy.
Qed.

Lemma schema_T_valid_on_reflexive :
  forall F, frame_reflexive F -> schema_valid_on_frame schema_T F.
Proof. intros F HF A p [q ->]. now apply valid_T_of_reflexive. Qed.

Lemma schema_D_valid_on_serial :
  forall F, frame_serial F -> schema_valid_on_frame schema_D F.
Proof. intros F HF A p [q ->]. now apply valid_D_of_serial. Qed.

Lemma schema_B_valid_on_symmetric :
  forall F, frame_symmetric F -> schema_valid_on_frame schema_B F.
Proof. intros F HF A p [q ->]. now apply valid_B_of_symmetric. Qed.

Lemma schema_Four_valid_on_transitive :
  forall F, frame_transitive F -> schema_valid_on_frame schema_Four F.
Proof. intros F HF A p [q ->]. now apply valid_Four_of_transitive. Qed.

Lemma schema_Five_valid_on_right_euclidean :
  forall F,
    frame_right_euclidean F -> schema_valid_on_frame schema_Five F.
Proof. intros F HF A p [q ->]. now apply valid_Five_of_right_euclidean. Qed.

Lemma schema_L_valid_on_GL_frame :
  forall F,
    frame_transitive F -> frame_converse_well_founded F ->
    schema_valid_on_frame schema_L F.
Proof. intros F HT HC A p [q ->]. now apply valid_Loeb_of_transitive_cwf. Qed.

Lemma schema_Grz_valid_on_Grz_frame :
  forall F,
    frame_reflexive F -> frame_transitive F ->
    frame_weak_converse_well_founded F ->
    schema_valid_on_frame schema_Grz F.
Proof.
  intros F HR HT HW A p [q ->].
  now apply valid_Grz_of_reflexive_transitive_weak_cwf.
Qed.

Theorem KT_proves_sound_on_reflexive_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_reflexive F -> KT_proves p -> valid F p.
Proof.
  intros AtomType F p HF Hp.
  eapply normal_proves_sound_on_frame; [now apply schema_T_valid_on_reflexive | exact Hp].
Qed.

Theorem KD_proves_sound_on_serial_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_serial F -> KD_proves p -> valid F p.
Proof.
  intros AtomType F p HF Hp.
  eapply normal_proves_sound_on_frame; [now apply schema_D_valid_on_serial | exact Hp].
Qed.

Theorem KB_proves_sound_on_symmetric_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_symmetric F -> KB_proves p -> valid F p.
Proof.
  intros AtomType F p HF Hp.
  eapply normal_proves_sound_on_frame; [now apply schema_B_valid_on_symmetric | exact Hp].
Qed.

Theorem K4_proves_sound_on_transitive_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_transitive F -> K4_proves p -> valid F p.
Proof.
  intros AtomType F p HF Hp.
  eapply normal_proves_sound_on_frame; [now apply schema_Four_valid_on_transitive | exact Hp].
Qed.

Theorem K5_proves_sound_on_right_euclidean_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_right_euclidean F -> K5_proves p -> valid F p.
Proof.
  intros AtomType F p HF Hp.
  eapply normal_proves_sound_on_frame;
    [now apply schema_Five_valid_on_right_euclidean | exact Hp].
Qed.

Theorem S4_proves_sound_on_preorder_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_reflexive F -> frame_transitive F -> S4_proves p -> valid F p.
Proof.
  intros AtomType F p HR HT Hp.
  eapply normal_proves_sound_on_frame; [|exact Hp].
  apply schema_union_valid_on_frame.
  - now apply schema_T_valid_on_reflexive.
  - now apply schema_Four_valid_on_transitive.
Qed.

Theorem S5_proves_sound_on_reflexive_euclidean_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_reflexive F -> frame_right_euclidean F ->
    S5_proves p -> valid F p.
Proof.
  intros AtomType F p HR HE Hp.
  eapply normal_proves_sound_on_frame; [|exact Hp].
  apply schema_union_valid_on_frame.
  - now apply schema_T_valid_on_reflexive.
  - now apply schema_Five_valid_on_right_euclidean.
Qed.

Theorem GL_proves_sound_on_transitive_cwf_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_transitive F -> frame_converse_well_founded F ->
    GL_proves p -> valid F p.
Proof.
  intros AtomType F p HT HC Hp.
  eapply normal_proves_sound_on_frame;
    [now apply schema_L_valid_on_GL_frame | exact Hp].
Qed.

Theorem Grz_proves_sound_on_reflexive_transitive_weak_cwf_frame :
  forall (AtomType : Type) (F : frame) (p : formula AtomType),
    frame_reflexive F -> frame_transitive F ->
    frame_weak_converse_well_founded F ->
    Grz_proves p -> valid F p.
Proof.
  intros AtomType F p HR HT HW Hp.
  eapply normal_proves_sound_on_frame;
    [now apply schema_Grz_valid_on_Grz_frame | exact Hp].
Qed.

(** * Concrete consistency witnesses *)

Definition reflexive_singleton_frame : frame :=
  {| World := unit;
     Rel := fun _ _ => True |}.

Lemma reflexive_singleton_reflexive :
  frame_reflexive reflexive_singleton_frame.
Proof. intros []; constructor. Qed.

Lemma reflexive_singleton_serial :
  frame_serial reflexive_singleton_frame.
Proof. intros []; exists tt; constructor. Qed.

Lemma reflexive_singleton_symmetric :
  frame_symmetric reflexive_singleton_frame.
Proof. intros [] [] _; constructor. Qed.

Lemma reflexive_singleton_transitive :
  frame_transitive reflexive_singleton_frame.
Proof. intros [] [] [] _ _; constructor. Qed.

Lemma reflexive_singleton_right_euclidean :
  frame_right_euclidean reflexive_singleton_frame.
Proof. intros [] [] [] _ _; constructor. Qed.

Lemma reflexive_singleton_weak_cwf :
  frame_weak_converse_well_founded reflexive_singleton_frame.
Proof.
  intros X [x Hx]. exists x; split; [exact Hx |].
  intros y _ _. now destruct x, y.
Qed.

Lemma irreflexive_singleton_transitive :
  frame_transitive irreflexive_singleton_frame.
Proof. intros [] [] [] H; contradiction. Qed.

Lemma irreflexive_singleton_cwf :
  frame_converse_well_founded irreflexive_singleton_frame.
Proof.
  intros X [x Hx]. exists x; split; [exact Hx |].
  intros y _ Hxy. exact Hxy.
Qed.

Theorem normal_consistent_of_sound_inhabited_frame :
  forall Ax (F : frame),
    (exists w : World F, True) ->
    schema_valid_on_frame Ax F ->
    forall AtomType : Type,
      ~ normal_proves Ax (@Bottom AtomType).
Proof.
  intros Ax F [w _] HAx AtomType Hbottom.
  pose proof
    (@normal_proves_sound_on_frame Ax AtomType F Bottom HAx Hbottom)
    as Hvalid.
  exact (Hvalid (fun _ _ => False) w).
Qed.

Theorem KT_is_consistent : forall AtomType, ~ @KT_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := schema_T) (F := reflexive_singleton_frame)).
  - now exists tt.
  - apply schema_T_valid_on_reflexive.
    exact reflexive_singleton_reflexive.
Qed.

Theorem KD_is_consistent : forall AtomType, ~ @KD_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := schema_D) (F := reflexive_singleton_frame)).
  - now exists tt.
  - apply schema_D_valid_on_serial.
    exact reflexive_singleton_serial.
Qed.

Theorem KB_is_consistent : forall AtomType, ~ @KB_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := schema_B) (F := reflexive_singleton_frame)).
  - now exists tt.
  - apply schema_B_valid_on_symmetric.
    exact reflexive_singleton_symmetric.
Qed.

Theorem K4_is_consistent : forall AtomType, ~ @K4_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := schema_Four) (F := irreflexive_singleton_frame)).
  - now exists tt.
  - apply schema_Four_valid_on_transitive.
    exact irreflexive_singleton_transitive.
Qed.

Theorem K5_is_consistent : forall AtomType, ~ @K5_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := schema_Five) (F := irreflexive_singleton_frame)).
  - now exists tt.
  - apply schema_Five_valid_on_right_euclidean.
    intros [] [] [] H; contradiction.
Qed.

Theorem S4_is_consistent : forall AtomType, ~ @S4_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := S4_schema) (F := reflexive_singleton_frame)).
  - now exists tt.
  - apply schema_union_valid_on_frame.
    + apply schema_T_valid_on_reflexive.
      exact reflexive_singleton_reflexive.
    + apply schema_Four_valid_on_transitive.
      exact reflexive_singleton_transitive.
Qed.

Theorem S5_is_consistent : forall AtomType, ~ @S5_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := S5_schema) (F := reflexive_singleton_frame)).
  - now exists tt.
  - apply schema_union_valid_on_frame.
    + apply schema_T_valid_on_reflexive.
      exact reflexive_singleton_reflexive.
    + apply schema_Five_valid_on_right_euclidean.
      exact reflexive_singleton_right_euclidean.
Qed.

Theorem GL_is_consistent : forall AtomType, ~ @GL_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := schema_L) (F := irreflexive_singleton_frame)).
  - now exists tt.
  - apply schema_L_valid_on_GL_frame.
    + exact irreflexive_singleton_transitive.
    + exact irreflexive_singleton_cwf.
Qed.

Theorem Grz_is_consistent : forall AtomType, ~ @Grz_proves AtomType Bottom.
Proof.
  apply (normal_consistent_of_sound_inhabited_frame
    (Ax := schema_Grz) (F := reflexive_singleton_frame)).
  - now exists tt.
  - apply schema_Grz_valid_on_Grz_frame.
    + exact reflexive_singleton_reflexive.
    + exact reflexive_singleton_transitive.
    + exact reflexive_singleton_weak_cwf.
Qed.
