(** Classical propositional logic over intuitionistic Kripke frames.

    This ports Foundation's [Propositional/Kripke/AxiomLEM] and
    [Propositional/Kripke/Hilbert/Cl] modules.  Because the ambient frames are
    preorders, symmetry and right Euclideanness coincide.  Excluded middle
    defines either condition exactly.

    The finite completeness proof is deliberately shorter than the source
    filtration argument.  Every relevant frame class contains the reflexive
    singleton, and forcing there is exactly Boolean evaluation.  A reusable
    singleton bridge therefore reduces all such completeness statements to
    the existing Boolean completeness theorem. *)

From Stdlib Require Import Logic.Classical_Prop Lists.List.
From FoundationModal Require Import
  PropositionalFormula PropositionalHilbert PropositionalBoolean
  PropositionalBooleanHilbert PropositionalKripke
  PropositionalKripkeCanonical PropositionalKripkeFinite.

Set Implicit Arguments.
Unset Strict Implicit.
Set Universe Polymorphism.

(** * Exact frame correspondence for excluded middle *)

Definition pkripke_frame_symmetric (F : pkripke_frame) : Prop :=
  forall x y, pkripke_access F x y -> pkripke_access F y x.

Definition pkripke_frame_euclidean (F : pkripke_frame) : Prop :=
  forall x y z,
    pkripke_access F x y -> pkripke_access F x z ->
    pkripke_access F y z.

Lemma pkripke_symmetric_of_euclidean :
  forall F, pkripke_frame_euclidean F -> pkripke_frame_symmetric F.
Proof.
  intros F HE x y Rxy.
  exact (HE x y x Rxy (pkripke_access_refl F x)).
Qed.

Lemma pkripke_euclidean_of_symmetric :
  forall F, pkripke_frame_symmetric F -> pkripke_frame_euclidean F.
Proof.
  intros F HS x y z Rxy Rxz.
  exact (pkripke_access_trans F y x z (HS x y Rxy) Rxz).
Qed.

Theorem pkripke_symmetric_iff_euclidean :
  forall F,
    pkripke_frame_symmetric F <-> pkripke_frame_euclidean F.
Proof.
  intro F; split.
  - apply pkripke_euclidean_of_symmetric.
  - apply pkripke_symmetric_of_euclidean.
Qed.

Theorem pkripke_LEM_valid_of_symmetric :
  forall (Atom : Type) (F : pkripke_frame),
    pkripke_frame_symmetric F ->
    forall p : pformula Atom,
      pkripke_frame_valid F (ph_axiom_lem p).
Proof.
  intros Atom F HS p V x.
  cbn [ph_axiom_lem pneg].
  destruct (classic (pkripke_forces
      {| pkripke_model_frame := F; pkripke_model_valuation := V |}
      x p)) as [Hp | Hnp].
  - now left.
  - right. intros y Rxy Hyp. apply Hnp.
    eapply pkripke_forces_persistent.
    + exact (HS x y Rxy).
    + exact Hyp.
Qed.

Corollary pkripke_LEM_valid_of_euclidean :
  forall (Atom : Type) (F : pkripke_frame),
    pkripke_frame_euclidean F ->
    forall p : pformula Atom,
      pkripke_frame_valid F (ph_axiom_lem p).
Proof.
  intros Atom F HE p.
  now apply pkripke_LEM_valid_of_symmetric,
    pkripke_symmetric_of_euclidean.
Qed.

(** One atom suffices for the converse.  Its upward-closed valuation is the
    principal upset generated by the first successor. *)
Theorem pkripke_euclidean_of_LEM_valid :
  forall F,
    pkripke_frame_valid F (ph_axiom_lem (PAtom 0)) ->
    pkripke_frame_euclidean F.
Proof.
  intros F Hvalid x y z Rxy Rxz.
  pose (V :=
    {| pkripke_atom_value := fun _ v => pkripke_access F y v;
       pkripke_atom_persistent := fun _ u v Ruv Ryu =>
         pkripke_access_trans F y u v Ryu Ruv |} :
      pkripke_valuation nat F).
  specialize (Hvalid V x).
  cbn [ph_axiom_lem pneg] in Hvalid.
  destruct Hvalid as [Ryx | Hneg].
  - exact (pkripke_access_trans F y x z Ryx Rxz).
  - exfalso. apply (Hneg y Rxy), pkripke_access_refl.
Qed.

Theorem pkripke_LEM_valid_iff_euclidean :
  forall F,
    pkripke_frame_valid F (ph_axiom_lem (PAtom 0)) <->
    pkripke_frame_euclidean F.
Proof.
  intro F; split.
  - apply pkripke_euclidean_of_LEM_valid.
  - intro HE. exact (pkripke_LEM_valid_of_euclidean HE (PAtom 0)).
Qed.

(** * Canonicality *)

Definition pki_has_lem (H : ph_hilbert nat) : Prop :=
  forall p, ph_hilbert_provable H (ph_axiom_lem p).

Theorem pki_canonical_frame_euclidean :
  forall H, pki_has_lem H ->
    pkripke_frame_euclidean (pki_canonical_frame H).
Proof.
  intros H HLEM T U V HTU HTV p HpU.
  apply NNPP. intro HnpV.
  assert (HlemT : pki_prime_mem T (ph_axiom_lem p)).
  { apply pki_prime_contains_theorems, HLEM. }
  destruct (proj1 (pki_prime_or_iff T p (pneg p)) HlemT)
    as [HpT | HnpT].
  - apply HnpV. exact (HTV p HpT).
  - apply (@pki_prime_proper H U).
    eapply pki_prime_mdp.
    + exact (HTU (pneg p) HnpT).
    + exact HpU.
Qed.

Definition pki_cl_has_efq : pki_has_efq (ph_hilbert_cl nat) :=
  fun p => inhabits (ph_hilbert_cl_efq p).

Definition pki_cl_has_lem : pki_has_lem (ph_hilbert_cl nat) :=
  fun p => inhabits (ph_hilbert_cl_lem p).

(** * Singleton/Boolean completeness bridge *)

Definition pkripke_singleton_boolean_valuation {Atom : Type}
    (v : pvaluation Atom) :
    pkripke_valuation Atom pkripke_singleton_frame :=
  {| pkripke_atom_value := fun a _ => v a;
     pkripke_atom_persistent := fun _ _ _ _ Ha => Ha |}.

Definition pkripke_singleton_boolean_model {Atom : Type}
    (v : pvaluation Atom) : pkripke_model Atom :=
  {| pkripke_model_frame := pkripke_singleton_frame;
     pkripke_model_valuation := pkripke_singleton_boolean_valuation v |}.

Theorem pkripke_singleton_forces_iff_boolean :
  forall (Atom : Type) (v : pvaluation Atom) (p : pformula Atom)
      (w : pkripke_world pkripke_singleton_frame),
    pkripke_forces (pkripke_singleton_boolean_model v) w p <->
    pboolean_eval v p.
Proof.
  intros Atom v p; induction p as
      [a| |p IHp q IHq|p IHp q IHq|p IHp q IHq]; intros []; cbn.
  - reflexivity.
  - tauto.
  - now rewrite IHp, IHq.
  - now rewrite IHp, IHq.
  - split.
    + intros H Hp. apply (proj1 (IHq tt)).
      apply (H tt I), (proj2 (IHp tt)), Hp.
    + intros H [] _ Hp. apply (proj2 (IHq tt)), H.
      now apply (proj1 (IHp tt)).
Qed.

(** Any frame class containing the singleton is already complete for Cl.
    This strictly generalizes both finite completeness statements below. *)
Theorem ph_hilbert_cl_pkripke_complete_of_singleton :
  forall (Atom : Type) (K : pformula_atom_codec Atom)
      (C : pkripke_frame -> Prop),
    C pkripke_singleton_frame ->
    pkripke_complete (ph_hilbert_cl Atom) C.
Proof.
  intros Atom K C Hsingle p Hvalid.
  apply (@ph_cl_provable_complete Atom K p).
  intro v.
  apply (proj1 (pkripke_singleton_forces_iff_boolean v p tt)).
  exact (Hvalid pkripke_singleton_frame Hsingle
    (pkripke_singleton_boolean_valuation v) tt).
Qed.

(** * Classical Hilbert soundness, completeness, and consistency *)

Theorem ph_hilbert_cl_pkripke_sound :
  forall (Atom : Type) p,
    ph_hilbert_provable (ph_hilbert_cl Atom) p ->
    pkripke_frame_class_valid pkripke_frame_euclidean p.
Proof.
  intros Atom p Hp.
  eapply ph_hilbert_pkripke_sound; [| exact Hp].
  intros q Hq; destruct Hq; intros F HF.
  - intros V. apply pkripke_model_valid_efq.
  - now apply pkripke_LEM_valid_of_euclidean.
Qed.

Theorem ph_hilbert_cl_pkripke_complete :
  pkripke_complete (ph_hilbert_cl nat) pkripke_frame_euclidean.
Proof.
  apply ph_hilbert_pkripke_complete_of_canonical.
  - exact pki_cl_has_efq.
  - exact (pki_canonical_frame_euclidean pki_cl_has_lem).
Qed.

Theorem ph_hilbert_cl_pkripke_sound_complete :
  forall p : pformula nat,
    ph_hilbert_provable (ph_hilbert_cl nat) p <->
    pkripke_frame_class_valid pkripke_frame_euclidean p.
Proof.
  intro p; split.
  - apply ph_hilbert_cl_pkripke_sound.
  - apply ph_hilbert_cl_pkripke_complete.
Qed.

Theorem ph_hilbert_cl_pkripke_symmetric_complete :
  pkripke_complete (ph_hilbert_cl nat) pkripke_frame_symmetric.
Proof.
  intros p Hvalid. apply ph_hilbert_cl_pkripke_complete.
  intros F HE. apply Hvalid, pkripke_symmetric_of_euclidean, HE.
Qed.

Theorem ph_hilbert_cl_pkripke_symmetric_sound_complete :
  forall p : pformula nat,
    ph_hilbert_provable (ph_hilbert_cl nat) p <->
    pkripke_frame_class_valid pkripke_frame_symmetric p.
Proof.
  intro p; split.
  - intros Hp F HS.
    apply (ph_hilbert_cl_pkripke_sound Hp).
    exact (pkripke_euclidean_of_symmetric HS).
  - apply ph_hilbert_cl_pkripke_symmetric_complete.
Qed.

Lemma pkripke_singleton_symmetric :
  pkripke_frame_symmetric pkripke_singleton_frame.
Proof. intros [] [] _. exact I. Qed.

Lemma pkripke_singleton_euclidean :
  pkripke_frame_euclidean pkripke_singleton_frame.
Proof. intros [] [] [] _ _. exact I. Qed.

Lemma pkripke_singleton_finite :
  pkripke_frame_finite pkripke_singleton_frame.
Proof. exists (tt :: nil). intros []. now left. Qed.

Definition pkripke_finite_symmetric (F : pkripke_frame) : Prop :=
  pkripke_frame_finite F /\ pkripke_frame_symmetric F.

Definition pkripke_finite_euclidean (F : pkripke_frame) : Prop :=
  pkripke_frame_finite F /\ pkripke_frame_euclidean F.

Theorem ph_hilbert_cl_pkripke_finite_symmetric_complete :
  forall (Atom : Type) (K : pformula_atom_codec Atom),
    pkripke_complete (ph_hilbert_cl Atom) pkripke_finite_symmetric.
Proof.
  intros Atom K.
  apply (@ph_hilbert_cl_pkripke_complete_of_singleton Atom K).
  split.
  - exact pkripke_singleton_finite.
  - exact pkripke_singleton_symmetric.
Qed.

Theorem ph_hilbert_cl_pkripke_finite_euclidean_complete :
  forall (Atom : Type) (K : pformula_atom_codec Atom),
    pkripke_complete (ph_hilbert_cl Atom) pkripke_finite_euclidean.
Proof.
  intros Atom K.
  apply (@ph_hilbert_cl_pkripke_complete_of_singleton Atom K).
  split.
  - exact pkripke_singleton_finite.
  - exact pkripke_singleton_euclidean.
Qed.

Theorem ph_hilbert_cl_consistent_via_pkripke :
  forall Atom : Type,
    ~ ph_hilbert_provable (ph_hilbert_cl Atom) PFalsum.
Proof.
  intro Atom.
  eapply ph_hilbert_consistent_of_nonempty_pkripke_class.
  - exact (@ph_hilbert_cl_pkripke_sound Atom).
  - exists pkripke_singleton_frame. split.
    + exact pkripke_singleton_euclidean.
    + constructor. exact tt.
Qed.

(** * Strictness over LC *)

Lemma ph_hilbert_lc_included_cl :
  forall Atom : Type,
    ph_hilbert_logic_included
      (ph_hilbert_lc Atom) (ph_hilbert_cl Atom).
Proof.
  intros Atom p Hp.
  eapply ph_hilbert_provable_of_provable_schema; [| exact Hp].
  intros q Hq. destruct Hq.
  - constructor. apply ph_hilbert_cl_efq.
  - constructor. apply ph_hilbert_cl_dummett.
Qed.

Inductive pkripke_two_chain_world : Type :=
| PK2_root | PK2_top.

Definition pkripke_two_chain_access
    (x y : pkripke_two_chain_world) : Prop :=
  match x, y with
  | PK2_top, PK2_root => False
  | _, _ => True
  end.

Lemma pkripke_two_chain_access_refl :
  forall x, pkripke_two_chain_access x x.
Proof. intros []; exact I. Qed.

Lemma pkripke_two_chain_access_trans :
  forall x y z,
    pkripke_two_chain_access x y ->
    pkripke_two_chain_access y z ->
    pkripke_two_chain_access x z.
Proof.
  intros [] [] [] Hxy Hyz; exact I || contradiction.
Qed.

Definition pkripke_two_chain_frame : pkripke_frame :=
  {| pkripke_world := pkripke_two_chain_world;
     pkripke_access := pkripke_two_chain_access;
     pkripke_access_refl := pkripke_two_chain_access_refl;
     pkripke_access_trans := pkripke_two_chain_access_trans |}.

Lemma pkripke_two_chain_strongly_connected :
  pkripke_frame_strongly_connected pkripke_two_chain_frame.
Proof.
  intros x [] [] _ _; [left | left | right | left]; exact I.
Qed.

Lemma pkripke_two_chain_not_euclidean :
  ~ pkripke_frame_euclidean pkripke_two_chain_frame.
Proof.
  intro HE.
  specialize (HE PK2_root PK2_top PK2_root I I).
  cbn [pkripke_two_chain_frame pkripke_two_chain_access] in HE.
  exact HE.
Qed.

Theorem ph_hilbert_lc_strictly_included_cl :
  ph_hilbert_logic_strictly_included
    (ph_hilbert_lc nat) (ph_hilbert_cl nat).
Proof.
  split.
  - apply ph_hilbert_lc_included_cl.
  - exists (ph_axiom_lem (PAtom 0)). split.
    + constructor. exact (ph_hilbert_cl_lem (PAtom 0)).
    + intro HLC. apply pkripke_two_chain_not_euclidean.
      apply pkripke_euclidean_of_LEM_valid.
      exact (ph_hilbert_lc_pkripke_sound HLC
        pkripke_two_chain_strongly_connected).
Qed.
