// Independent a=3 audit: no producer source or canonicalizer is imported.
// Quotients: ALL upper-triangular relations, transitivity, ALL vertex permutations.
// Supports: ternary roles and Hall inequalities, not matching enumeration.
#include <bits/stdc++.h>
using namespace std; using U=unsigned; using Key=array<U,8>; using ll=long long;
int pc(U x){return __builtin_popcount(x);} int lo(U x){return __builtin_ctz(x);}
bool preorder(vector<U> r){int n=r.size();for(int i=0;i<n;i++)r[i]|=1u<<i;auto x=r;for(int k=0;k<n;k++)for(int i=0;i<n;i++)if(x[i]>>k&1)x[i]|=x[k];return x==r;}
vector<U> extension(const vector<U>&r,array<int,3>A,int signs,const vector<int>&ts){auto x=r;x.resize(6+ts.size());for(int j=0;j<(int)ts.size();j++)for(int a=0;a<3;a++)if(ts[j]>>a&1){int tail=(signs>>a&1)?A[a]:6+j;int head=(signs>>a&1)?6+j:A[a];x[tail]|=1u<<head;}return x;}
Key marked_key(const vector<U>&r,array<int,3>A,int signs,int legal){vector<int>B;for(int i=0;i<6;i++)if(find(A.begin(),A.end(),i)==A.end())B.push_back(i);sort(A.begin(),A.end()); // caller always supplies sorted A
 // Direction/type coordinates refer to this sorted A.
 Key best;best.fill(UINT_MAX);array<int,3>p={0,1,2};
 do{sort(B.begin(),B.end());do{array<int,6>ord={A[p[0]],A[p[1]],A[p[2]],B[0],B[1],B[2]};for(int rev=0;rev<2;rev++){Key k={};for(int i=0;i<6;i++)for(int j=0;j<6;j++)if(rev?(r[ord[j]]>>ord[i]&1):(r[ord[i]]>>ord[j]&1))k[i]|=1u<<j;for(int a=0;a<3;a++)if(((signs>>p[a])&1)^rev)k[6]|=1u<<a;for(int t=1;t<8;t++)if(legal>>t&1){int z=0;for(int a=0;a<3;a++)if(t>>p[a]&1)z|=1<<a;k[7]|=1u<<z;}best=min(best,k);}}while(next_permutation(B.begin(),B.end()));}while(next_permutation(p.begin(),p.end()));return best;}
int rank_core(const vector<U>&r,U mask){int dp[64]={};U und[6]={};for(int i=0;i<6;i++)for(int j=0;j<6;j++)if((r[i]>>j&1)||(r[j]>>i&1))und[i]|=1u<<j;for(U s=1;s<64;s++){int i=lo(s);U rem=s&(s-1);dp[s]=dp[rem];for(U z=rem&und[i];z;z&=z-1)dp[s]=max(dp[s],1+dp[rem^(z&-z)]);}return dp[mask];}
bool retain(const vector<U>&core,array<int,3>A,int signs,const vector<int>&ts){auto r=extension(core,A,signs,ts);int n=r.size();vector<U>adj(n);for(int i=0;i<n;i++)for(int j=0;j<n;j++)if((r[i]>>j&1)||(r[j]>>i&1))adj[i]|=1u<<j;U unvisited=(1u<<n)-1;bool needed=false;while(unvisited){U comp=unvisited&-unvisited,old=0;while(old!=comp){old=comp;for(U z=old;z;z&=z-1)comp|=adj[lo(z)];}unvisited&=~comp;int color[32];fill(color,color+32,-1);vector<int>q={lo(comp)};color[q[0]]=0;bool bip=true;for(int a=0;a<(int)q.size();a++){int v=q[a];for(U z=adj[v];z;z&=z-1){int w=lo(z);if(color[w]<0){color[w]=1-color[v];q.push_back(w);}else if(color[w]==color[v])bip=false;}}
 U active=0;for(int j=0;j<(int)ts.size();j++)if(comp>>(6+j)&1)for(int a=0;a<3;a++)if(ts[j]>>a&1)active|=1u<<A[a];int rank=pc(active)+rank_core(core,(comp&63)&~active);assert(rank<=4);if(!bip&&rank==4)needed=true;}return needed;}
uint64_t quotient_key(const vector<U>&r){int n=r.size();vector<int>p(n);iota(p.begin(),p.end(),0);uint64_t best=~uint64_t(0);do{uint64_t k=0;for(int i=0;i<n;i++)for(int j=0;j<n;j++)if(r[p[i]]>>p[j]&1)k|=uint64_t(1)<<(n*i+j);best=min(best,k);}while(next_permutation(p.begin(),p.end()));return best;}
ll cores=0,specs=0,reduced=0,retained=0;set<Key>obtained,expected;
void check_core(const vector<U>&q,const vector<int>&sizes){cores++;vector<int>cls;for(int i=0;i<(int)q.size();i++)for(int j=0;j<sizes[i];j++)cls.push_back(i);assert(cls.size()==6);vector<U>r(6);for(int i=0;i<6;i++)for(int j=0;j<6;j++)if(i!=j&&(cls[i]==cls[j]||(q[cls[i]]>>cls[j]&1)))r[i]|=1u<<j;assert(preorder(r));for(int a=0;a<6;a++)for(int b=a+1;b<6;b++)for(int c=b+1;c<6;c++)for(int sign=0;sign<8;sign++){array<int,3>A={a,b,c};int legal=0;vector<int>ts;for(int t=1;t<8;t++){bool once=preorder(extension(r,A,sign,{t}));bool twice=preorder(extension(r,A,sign,{t,t}));assert(once==twice);if(twice){legal|=1<<t;ts.push_back(t);}}if(ts.empty())continue;assert(preorder(extension(r,A,sign,ts)));specs++;if(!retain(r,A,sign,ts)){reduced++;continue;}retained++;obtained.insert(marked_key(r,A,sign,legal));}}
struct Sup{U a,b;int k;};vector<Sup>support[4];vector<U>sub[512];int pops[512];
void roles(int extra,int pos,U a,U b){int n=6+extra;if(pos==n){if(pc(a)==pc(b)&&pc(a)<=4)support[extra].push_back({a,b,pc(a)});return;}if(pos<6)roles(extra,pos+1,a,b);roles(extra,pos+1,a|(1u<<pos),b);roles(extra,pos+1,a,b|(1u<<pos));}
array<ll,5>hall_gamma(const vector<U>&r,int extra){U nb[512]={};int n=r.size();for(U a=1;a<(1u<<n);a++)nb[a]=nb[a&(a-1)]|r[lo(a)];array<ll,5>g={};for(auto p:support[extra]){bool yes=true;for(U s:sub[p.a])if(pops[nb[s]&p.b]<pops[s]){yes=false;break;}if(yes)g[p.k]++;}return g;}
int main(int argc,char**argv){assert(argc==2);for(int a=0;a<512;a++){pops[a]=pc(a);for(U s=a;s;s=(s-1)&a)sub[a].push_back(s);sort(sub[a].begin(),sub[a].end(),[](U a,U b){return pc(a)>pc(b);});}for(int e=0;e<4;e++){roles(e,0,0,0);cout<<"mandatory_extra="<<e<<" support_candidates="<<support[e].size()<<endl;}
 ifstream in(argv[1]);int id;ll checked=0,quota=0,scalar=0;while(in>>id){assert(id==checked);vector<U>r(6);for(auto&x:r)in>>x;int signs,L,d,nq;in>>signs>>L>>d>>nq;assert(in&&preorder(r));vector<int>ts;for(int t=1;t<8;t++)if(L>>t&1)ts.push_back(t);assert((int)ts.size()==d);int computedL=0;for(int t=1;t<8;t++)if(preorder(extension(r,{0,1,2},signs,{t,t})))computedL|=1<<t;assert(computedL==L);assert(preorder(extension(r,{0,1,2},signs,ts)));assert(retain(r,{0,1,2},signs,ts));Key key;copy(r.begin(),r.end(),key.begin());key[6]=signs;key[7]=L;assert(key==marked_key(r,{0,1,2},signs,L));assert(expected.insert(key).second);
 for(int j=0;j<nq;j++){vector<int>ext;for(int a=0;a<d;a++){int count;in>>count;assert(count>=0);for(int z=0;z<count;z++)ext.push_back(ts[a]);}assert(ext.size()<=3);array<ll,5>want;for(auto&x:want)in>>x;assert(in);auto rr=extension(r,{0,1,2},signs,ext);assert(preorder(rr));auto got=hall_gamma(rr,ext.size());if(want!=got){cerr<<"POLYNOMIAL MISMATCH template="<<id<<" quota="<<j<<endl;return 1;}quota++;scalar+=5;}checked++;if(checked%500==0)cout<<"representatives="<<checked<<" quota_vectors="<<quota<<endl;}
 assert(checked==6213&&quota==188715);cout<<"HALL COMPLETE representatives="<<checked<<" quotas="<<quota<<" scalar_coefficients="<<scalar<<endl;
 for(int n=1;n<=6;n++){vector<pair<int,int>>edges;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)edges.push_back({i,j});set<uint64_t>Qs;ll natural=0;for(U mask=0;mask<(1u<<edges.size());mask++){vector<U>r(n);for(int e=0;e<(int)edges.size();e++)if(mask>>e&1)r[edges[e].first]|=1u<<edges[e].second;if(!preorder(r))continue;natural++;Qs.insert(quotient_key(r));}for(auto key:Qs){vector<U>q(n);for(int i=0;i<n;i++)q[i]=(key>>(n*i))&((1u<<n)-1);for(U sep=0;sep<32;sep++)if(pc(sep)==n-1){vector<int>sizes;int run=1;for(int i=0;i<5;i++){if(sep>>i&1){sizes.push_back(run);run=1;}else run++;}sizes.push_back(run);check_core(q,sizes);}}cout<<"quotient_n="<<n<<" natural_posets="<<natural<<" unlabeled_posets="<<Qs.size()<<" cores="<<cores<<" specs="<<specs<<" reduced="<<reduced<<" retained="<<retained<<" templates="<<obtained.size()<<endl;}
 assert(cores==854&&specs==90042&&reduced==68704&&retained==21338&&obtained.size()==6213);if(obtained!=expected){cerr<<"COVERAGE SET MISMATCH"<<endl;return 1;}cout<<"PASS exact complete marked-template set, Hall coefficients, legality, pruning, canonical representatives"<<endl;
}
