// Independent a4 coverage, Hall kernel, and subset-union Newton-gap recount.
#include <bits/stdc++.h>
using namespace std;using U=unsigned;using ll=long long;using Code=uint64_t;using Key=array<U,6>;using Poly=map<Code,ll>;
int pc(U x){return __builtin_popcount(x);}int lo(U x){return __builtin_ctz(x);}
bool preorder(vector<U>r){for(int i=0;i<(int)r.size();i++)r[i]|=1u<<i;auto c=r;for(int k=0;k<(int)r.size();k++)for(int i=0;i<(int)r.size();i++)if(c[i]>>k&1)c[i]|=c[k];return c==r;}
vector<U>ext(const vector<U>&r,int signs,const vector<int>&ts){auto x=r;x.resize(4+ts.size());for(int j=0;j<(int)ts.size();j++)for(int a=0;a<4;a++)if(ts[j]>>a&1){int u=(signs>>a&1)?a:4+j,v=(signs>>a&1)?4+j:a;x[u]|=1u<<v;}return x;}
U pack(const vector<U>&r){U key=0;for(int i=0;i<(int)r.size();i++)key|=r[i]<<(4*i);return key;}
vector<U>permute(const vector<U>&r,const vector<int>&p,bool rev=false){int n=p.size();vector<U>x(n);for(int i=0;i<n;i++)for(int j=0;j<n;j++)if(rev?(r[p[j]]>>p[i]&1):(r[p[i]]>>p[j]&1))x[i]|=1u<<j;return x;}
Key canonical(const vector<U>&r,int s,int L){vector<int>p={0,1,2,3};Key best;best.fill(UINT_MAX);do{for(int rev=0;rev<2;rev++){auto x=permute(r,p,rev);Key k={};copy(x.begin(),x.end(),k.begin());for(int i=0;i<4;i++)if(((s>>p[i])&1)^rev)k[4]|=1<<i;for(int t=1;t<16;t++)if(L>>t&1){int nt=0;for(int i=0;i<4;i++)if(t>>p[i]&1)nt|=1<<i;k[5]|=1<<nt;}best=min(best,k);}}while(next_permutation(p.begin(),p.end()));return best;}
int rank4(const vector<U>&r,U mask){int dp[16]={};for(U a=1;a<16;a++){U rest=a&(a-1);int v=lo(a);dp[a]=dp[rest];for(U z=rest;z;z&=z-1){int w=lo(z);if((r[v]>>w&1)||(r[w]>>v&1))dp[a]=max(dp[a],1+dp[rest^(1u<<w)]);}}return dp[mask];}
bool retain(const vector<U>&core,int s,const vector<int>&ts){auto r=ext(core,s,ts);int n=r.size();vector<U>adj(n);for(int i=0;i<n;i++)for(int j=0;j<n;j++)if((r[i]>>j&1)||(r[j]>>i&1))adj[i]|=1u<<j;U remain=(1u<<n)-1;bool wanted=false;while(remain){U comp=remain&-remain,old=0;while(comp!=old){old=comp;for(U z=old;z;z&=z-1)comp|=adj[lo(z)];}remain&=~comp;U active=0;for(int i=0;i<(int)ts.size();i++)if(comp>>(4+i)&1)active|=ts[i];int rank=pc(active)+rank4(core,(comp&15)&~active);assert(rank<=4&&(rank==4)==(active==15));int colors[32];fill(colors,colors+32,-1);vector<int>todo={lo(comp)};colors[todo[0]]=0;bool bip=true;for(int h=0;h<(int)todo.size();h++){int v=todo[h];for(U z=adj[v];z;z&=z-1){int w=lo(z);if(colors[w]<0){colors[w]=1-colors[v];todo.push_back(w);}else if(colors[w]==colors[v])bip=false;}}if(!bip&&rank==4)wanted=true;}return wanted;}
struct Support{U a,b;int k;};vector<Support>supports[5];vector<U>subsets[256];int pops[256];
void roles(int e,int i,U a,U b){if(i==4+e){if(pc(a)==pc(b)&&pc(a)<=4)supports[e].push_back({a,b,pc(a)});return;}if(i<4)roles(e,i+1,a,b);roles(e,i+1,a|(1u<<i),b);roles(e,i+1,a,b|(1u<<i));}
array<ll,5>hall(const vector<U>&r,int e){U N[256]={};for(U a=1;a<(1u<<r.size());a++)N[a]=N[a&(a-1)]|r[lo(a)];array<ll,5>g={};for(auto p:supports[e]){bool ok=true;for(U a:subsets[p.a])if(pops[N[a]&p.b]<pops[a]){ok=false;break;}if(ok)g[p.k]++;}return g;}
// Weight[a][b][t] is enumerated from all ordered subset pairs of a t-set
// having sizes a,b and union the whole t-set. No factorial formula is used.
ll weight[5][5][9]={};
void product_into(const Poly&A,const Poly&B,Poly&C,ll scalar,int d){for(auto [x,u]:A)for(auto [y,v]:B){vector<tuple<int,int,int>>shared;Code fixed=0;for(int i=0;i<d;i++){int a=(x>>(3*i))&7,b=(y>>(3*i))&7;assert(a<=4&&b<=4&&a+b<=6);if(a&&b)shared.push_back({i,a,b});else fixed|=Code(a+b)<<(3*i);}function<void(int,Code,ll)>go=[&](int j,Code z,ll w){if(j==(int)shared.size()){C[z]+=w;return;}auto[i,a,b]=shared[j];for(int t=max(a,b);t<=a+b;t++)if(weight[a][b][t])go(j+1,z|(Code(t)<<(3*i)),w*weight[a][b][t]);};go(0,fixed,scalar*u*v);}}
void clean(Poly&p){for(auto it=p.begin();it!=p.end();)if(!it->second)it=p.erase(it);else++it;}
int main(int argc,char**argv){assert(argc==2);for(int a=0;a<256;a++){pops[a]=pc(a);for(U z=a;z;z=(z-1)&a)subsets[a].push_back(z);sort(subsets[a].begin(),subsets[a].end(),[](U a,U b){return pc(a)>pc(b);});}for(int e=0;e<5;e++){roles(e,0,0,0);cout<<"mandatory_extra="<<e<<" Hall_candidates="<<supports[e].size()<<endl;}
 for(int t=0;t<=6;t++)for(U a=0;a<(1u<<t);a++)for(U b=0;b<(1u<<t);b++)if((a|b)==(1u<<t)-1&&pc(a)<=4&&pc(b)<=4)weight[pc(a)][pc(b)][t]++;
 ifstream in(argv[1]);int id;ll templates=0,quota=0,terms=0;set<Key>expected;map<int,int>dimensions;
 while(in>>id){assert(id==templates);vector<U>r(4);for(auto&x:r)in>>x;int s,L,d,nq;in>>s>>L>>d>>nq;assert(in&&preorder(r));vector<int>ts;int legal=0;for(int t=1;t<16;t++)if(preorder(ext(r,s,{t,t}))){legal|=1<<t;ts.push_back(t);}assert(legal==L&&(int)ts.size()==d&&preorder(ext(r,s,ts))&&retain(r,s,ts));Key key;copy(r.begin(),r.end(),key.begin());key[4]=s;key[5]=L;assert(key==canonical(r,s,L)&&expected.insert(key).second);dimensions[d]++;
 array<Poly,5>G;for(int j=0;j<nq;j++){vector<int>ex;Code code=0;for(int i=0;i<d;i++){int q;in>>q;assert(0<=q&&q<=4);code|=Code(q)<<(3*i);for(int z=0;z<q;z++)ex.push_back(ts[i]);}assert(ex.size()<=4);array<ll,5>want;for(auto&v:want)in>>v;assert(in);auto rr=ext(r,s,ex);assert(preorder(rr));auto got=hall(rr,ex.size());if(got!=want){cerr<<"HALL MISMATCH id="<<id<<" quota="<<j<<endl;return 1;}for(int k=0;k<5;k++)if(got[k])G[k][code]=got[k];quota++;}
 for(int k=2;k<=3;k++){int nt;in>>nt;Poly wanted;for(int j=0;j<nt;j++){Code e;ll c;in>>e>>c;assert(in&&c&&wanted.emplace(e,c).second);}Poly got;product_into(G[k],G[k],got,k==2?4:3,d);product_into(G[k-1],G[k+1],got,k==2?-9:-8,d);clean(got);if(got!=wanted){cerr<<"GAP MISMATCH id="<<id<<" gap="<<k<<endl;return 1;}terms+=nt;}
 templates++;if(templates%10==0)cout<<"templates="<<templates<<" quotas="<<quota<<" Newton_terms="<<terms<<endl;}
 assert(templates==76&&quota==32516&&terms==258153);cout<<"HALL AND NEWTON COMPLETE templates="<<templates<<" quotas="<<quota<<" scalar_coefficients="<<5*quota<<" gap_terms="<<terms<<endl;
 // Independent coverage: weighted unlabeled quotient posets and all relabelings.
 set<U>all_preorders;ll weighted=0;for(int n=1;n<=4;n++){vector<pair<int,int>>edges;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)edges.push_back({i,j});set<U>quotients;for(U mask=0;mask<(1u<<edges.size());mask++){vector<U>q(n);for(int j=0;j<(int)edges.size();j++)if(mask>>j&1)q[edges[j].first]|=1u<<edges[j].second;if(!preorder(q))continue;vector<int>p(n);iota(p.begin(),p.end(),0);U best=UINT_MAX;do{best=min(best,pack(permute(q,p)));}while(next_permutation(p.begin(),p.end()));quotients.insert(best);}for(U z:quotients){vector<U>q(n);for(int i=0;i<n;i++)q[i]=(z>>(4*i))&15;for(U sep=0;sep<8;sep++)if(pc(sep)==n-1){vector<int>cls;int c=0;for(int i=0;i<4;i++){cls.push_back(c);if(i<3&&(sep>>i&1))c++;}assert(c==n-1);weighted++;vector<U>r(4);for(int i=0;i<4;i++)for(int j=0;j<4;j++)if(i!=j&&(cls[i]==cls[j]||(q[cls[i]]>>cls[j]&1)))r[i]|=1u<<j;vector<int>p={0,1,2,3};do{all_preorders.insert(pack(permute(r,p)));}while(next_permutation(p.begin(),p.end()));}}cout<<"quotient_size="<<n<<" quotient_count="<<quotients.size()<<" weighted_cores="<<weighted<<" labeled_preorders="<<all_preorders.size()<<endl;}
 assert(weighted==38&&all_preorders.size()==355);ll specs=0,reduced=0,retained=0;set<Key>obtained;for(U z:all_preorders){vector<U>r(4);for(int i=0;i<4;i++)r[i]=(z>>(4*i))&15;assert(preorder(r));for(int s=0;s<16;s++){int L=0;vector<int>ts;for(int t=1;t<16;t++){bool one=preorder(ext(r,s,{t})),two=preorder(ext(r,s,{t,t}));assert(one==two);if(two){L|=1<<t;ts.push_back(t);}}if(ts.empty())continue;assert(preorder(ext(r,s,ts)));specs++;if(!retain(r,s,ts)){reduced++;continue;}retained++;obtained.insert(canonical(r,s,L));}}
 assert(specs==4882&&reduced==2874&&retained==2008&&obtained.size()==76&&obtained==expected);cout<<"COVERAGE COMPLETE labeled_preorders=355 specifications="<<specs<<" reduced="<<reduced<<" retained="<<retained<<" templates="<<obtained.size()<<endl;cout<<"type_counts=";for(auto[d,n]:dimensions)cout<<d<<":"<<n<<",";cout<<endl<<"PASS complete coverage, pruning, legal types, canonical templates, Hall coefficients, exact binomial Newton gaps"<<endl;
}
