// Independent Hall-support/decomposition audit over every type multiset of size<=4.
#include <bits/stdc++.h>
using namespace std; using U=unsigned; using ll=long long;
int pc(U a){return __builtin_popcount(a);}int lo(U a){return __builtin_ctz(a);}int pops[256];
vector<U>subs[256];struct S{U a,b;int k;};vector<S>support[9];
void roles(int n,int i,U a,U b){if(i==n){if(pc(a)==pc(b)&&pc(a)<=4)support[n].push_back({a,b,pc(a)});return;}roles(n,i+1,a,b);roles(n,i+1,a|(1u<<i),b);roles(n,i+1,a,b|(1u<<i));}
array<ll,5>gamma(const vector<int>&types,bool core){int e=types.size(),n=4+e;U rows[8]={};if(core){rows[2]=3;rows[3]=3;}for(int j=0;j<e;j++)for(int a=0;a<4;a++)if(types[j]>>a&1){if(a>=2)rows[a]|=1u<<(4+j);else rows[4+j]|=1u<<a;}U N[256]={};for(U s=1;s<(1u<<n);s++)N[s]=N[s&(s-1)]|rows[lo(s)];array<ll,5>g={};for(auto p:support[n]){bool ok=true;for(U a:subs[p.a])if(pops[N[a]&p.b]<pops[a]){ok=false;break;}if(ok)g[p.k]++;}return g;}
int side_weight(const vector<int>&ts,U chosen,int shift){int result=0;for(U centers=0;centers<4;centers++)if(pc(centers)==pc(chosen)){bool ok=true;for(U a=chosen;a;a=(a-1)&chosen){U N=0;for(U b=a;b;b&=b-1)N|=(ts[lo(b)]>>shift)&3;if(pc(N&centers)<pc(a)){ok=false;break;}}result+=ok;}return result;}
ll cases=0,positive=0;set<array<ll,5>>polys;vector<int>types;
void check_case(){int e=types.size();auto g=gamma(types,true),f=gamma(types,false);array<ll,5>convolution={};U all=(1u<<e)-1;for(U H=0;H<=all;H++){int a=side_weight(types,H,2);if(!a)continue;U available=all^H;for(U T=available;;T=(T-1)&available){int b=side_weight(types,T,0);if(b)convolution[pc(H)+pc(T)]+=a*b;if(!T)break;}}assert(f==convolution);int m=0,n=0,r=0;for(int t:types){m+=bool(t&12);n+=bool(t&3);r+=bool(t&12)&&bool(t&3);}int u=2*(m+n),v=m*n-r;auto predicted=f;predicted[1]+=4;predicted[2]+=u+1;predicted[3]+=v;assert(g==predicted);if(f[4]){positive++;assert(m>=2&&n>=2&&m+n-r>=4);assert(3*f[3]*f[3]>=8*f[2]*f[4]);assert(v*v>=4*f[4]);assert(3*m*n*f[3]>=10*(m+n)*f[4]);assert(6*f[3]*v+3*v*v>8*(u+1)*f[4]);assert(3*g[3]*g[3]>8*g[2]*g[4]);}polys.insert(f);cases++;}
void choose(int remaining,int minimum){check_case();if(!remaining)return;for(int t=minimum;t<=15;t++){types.push_back(t);choose(remaining-1,t);types.pop_back();}}
int main(){for(int i=0;i<256;i++){pops[i]=pc(i);for(U a=i;a;a=(a-1)&i)subs[i].push_back(a);}for(int n=4;n<=8;n++)roles(n,0,0,0);choose(4,1);assert(cases==3876);cout<<"PASS multisets="<<cases<<" degree_four="<<positive<<" distinct_F="<<polys.size()<<endl;ofstream out("F_polynomials.txt");for(auto p:polys){for(auto c:p)out<<c<<" ";out<<"\n";}}
