// Full a=3 bounded-core enumeration, with known-component structural reductions.
#include<bits/stdc++.h>
using namespace std;using ll=long long;
#include "canonical.inc"
unsigned rows[9];int m;vector<unsigned>qrows;vector<int>blocks;ll cores=0,specs=0,retained=0,reduced=0;
using Spec=array<unsigned,8>;set<Spec>templates;
bool transitive(vector<unsigned>r){int n=r.size();for(int i=0;i<n;i++)r[i]|=1u<<i;for(int i=0;i<n;i++)for(int j=0;j<n;j++)if((r[i]>>j&1)&&(r[j]&~r[i]))return 0;return 1;}
vector<unsigned> expand(vector<unsigned>core,array<int,3>A,int s,vector<int>ts){core.resize(6+ts.size());for(int j=0;j<(int)ts.size();j++)for(int a=0;a<3;a++)if(ts[j]>>a&1){if(s>>a&1)core[A[a]]|=1u<<(6+j);else core[6+j]|=1u<<A[a];}return core;}
int nu(vector<unsigned>&rr,unsigned mask){if(!mask)return 0;int v=__builtin_ctz(mask);unsigned tail=mask^(1u<<v);int best=nu(rr,tail);for(unsigned t=tail;t;t&=t-1){int w=__builtin_ctz(t);if((rr[v]>>w&1)||(rr[w]>>v&1))best=max(best,1+nu(rr,tail^(1u<<w)));}return best;}
bool needs_certificate(vector<unsigned>core,array<int,3>A,int s,vector<int>ts){auto r=expand(core,A,s,ts);int n=r.size();vector<int>color(n,-1);for(int root=0;root<n;root++)if(color[root]<0){vector<int>todo={root};color[root]=0;bool bip=true;unsigned coremask=0,active=0;for(int h=0;h<(int)todo.size();h++){int v=todo[h];if(v<6)coremask|=1u<<v;else for(int a=0;a<3;a++)if(ts[v-6]>>a&1)active|=1u<<A[a];for(int w=0;w<n;w++)if((r[v]>>w&1)||(r[w]>>v&1)){if(color[w]<0){color[w]=color[v]^1;todo.push_back(w);}else if(color[w]==color[v])bip=false;}}
 // At population3 every active attachment can be matched to a distinct exterior clone.
 // The exact component rank is |active attachments|+nu(core minus those attachments).
 int rank=__builtin_popcount(active)+nu(core,coremask&~active);if(rank>4)throw runtime_error("rank bound failed");if(!bip&&rank==4)return true;}
 return false;}
Spec canon_spec(vector<unsigned>r,array<int,3>A,int s,int legal){vector<int>rest;for(int i=0;i<6;i++)if(find(A.begin(),A.end(),i)==A.end())rest.push_back(i);array<int,3>ap={0,1,2};Spec best;best.fill(UINT_MAX);do{sort(rest.begin(),rest.end());do{vector<int>ord={A[ap[0]],A[ap[1]],A[ap[2]],rest[0],rest[1],rest[2]};for(int dual=0;dual<2;dual++){Spec key={};for(int i=0;i<6;i++)for(int j=0;j<6;j++)if(dual?(r[ord[j]]>>ord[i]&1):(r[ord[i]]>>ord[j]&1))key[i]|=1u<<j;for(int a=0;a<3;a++)if(((s>>ap[a])&1)^dual)key[6]|=1u<<a;for(int t=1;t<8;t++)if(legal>>t&1){int nt=0;for(int a=0;a<3;a++)if(t>>ap[a]&1)nt|=1u<<a;key[7]|=1u<<nt;}best=min(best,key);}}while(next_permutation(rest.begin(),rest.end()));}while(next_permutation(ap.begin(),ap.end()));return best;}
void eval(){cores++;vector<int>cls;for(int i=0;i<m;i++)for(int j=0;j<blocks[i];j++)cls.push_back(i);vector<unsigned>r(6);for(int i=0;i<6;i++)for(int j=0;j<6;j++)if(i!=j&&(cls[i]==cls[j]||(qrows[cls[i]]>>cls[j]&1)))r[i]|=1u<<j;
 for(int a=0;a<6;a++)for(int b=a+1;b<6;b++)for(int c=b+1;c<6;c++)for(int s=0;s<8;s++){array<int,3>A={a,b,c};vector<int>ts;int legal=0;for(int t=1;t<8;t++)if(transitive(expand(r,A,s,{t,t}))){ts.push_back(t);legal|=1u<<t;}if(ts.empty())continue;if(!transitive(expand(r,A,s,ts)))throw runtime_error("incompatible types");specs++;if(!needs_certificate(r,A,s,ts)){reduced++;continue;}retained++;templates.insert(canon_spec(r,A,s,legal));}}
void compose(int idx,int left){if(idx==m-1){blocks[idx]=left;eval();return;}for(int x=1;x<=left-(m-idx-1);x++){blocks[idx]=x;compose(idx+1,left-x);}}
struct Support{unsigned a,b;int k;};vector<Support>supports[4];
bool match(unsigned a,unsigned b){if(!a)return true;unsigned opts=rows[__builtin_ctz(a)]&b;a&=a-1;while(opts){unsigned bit=opts&-opts;opts-=bit;if(match(a,b^bit))return true;}return false;}
int main(int argc,char**argv){string out=argc>1?argv[1]:"a3_polynomials.jsonl";vector<vector<unsigned>>last(1);for(m=1;m<=6;m++){set<Key>keys;for(auto&r:last){int z=r.size();for(unsigned pred=0;pred<(1u<<z);pred++){bool ideal=true;for(int i=0;i<z;i++)if(!(pred>>i&1)&&(r[i]&pred)){ideal=false;break;}if(!ideal)continue;auto nr=r;for(int i=0;i<z;i++)if(pred>>i&1)nr[i]|=1u<<z;nr.push_back(0);keys.insert(canonical(nr));}}vector<vector<unsigned>>current;for(auto key:keys){auto r=decode(key,m);current.push_back(r);qrows=r;blocks.assign(m,0);compose(0,6);}last=move(current);cout<<"m="<<m<<" cores="<<cores<<" specifications="<<specs<<" structurally_reduced="<<reduced<<" retained="<<retained<<" canonical_templates="<<templates.size()<<endl;}
 for(int extra=0;extra<=3;extra++){int N=6+extra;unsigned mandatory=((1u<<extra)-1)<<6;for(unsigned a=0;a<(1u<<N);a++){int k=__builtin_popcount(a);if(k>4)continue;unsigned comp=((1u<<N)-1)^a;for(unsigned b=comp;;b=(b-1)&comp){if(__builtin_popcount(b)==k&&((a|b)&mandatory)==mandatory)supports[extra].push_back({a,b,k});if(!b)break;}}}
 ofstream f(out);ll id=0;for(auto spec:templates){vector<unsigned>core(spec.begin(),spec.begin()+6);vector<int>ts;for(int t=1;t<8;t++)if(spec[7]>>t&1)ts.push_back(t);int d=ts.size();vector<vector<int>>Q;vector<array<ll,5>>G;vector<int>q(d);function<void(int,int)>go=[&](int i,int left){if(i<d){for(int k=0;k<=left;k++){q[i]=k;go(i+1,left-k);}return;}vector<int>ext;for(int j=0;j<d;j++)for(int k=0;k<q[j];k++)ext.push_back(ts[j]);auto r=expand(core,{0,1,2},spec[6],ext);copy(r.begin(),r.end(),rows);array<ll,5>g={};for(auto p:supports[ext.size()])if(match(p.a,p.b))g[p.k]++;Q.push_back(q);G.push_back(g);};go(0,3);
 f<<"{\"id\":"<<id<<",\"core_rows\":[";for(int i=0;i<6;i++){if(i)f<<",";f<<core[i];}f<<"],\"orientation_mask\":"<<spec[6]<<",\"types\":[";for(int i=0;i<d;i++){if(i)f<<",";f<<ts[i];}f<<"],\"quota\":[";for(int i=0;i<(int)Q.size();i++){if(i)f<<",";f<<"[";for(int j=0;j<d;j++){if(j)f<<",";f<<Q[i][j];}f<<"]";}f<<"],\"gamma\":[";for(int k=0;k<5;k++){if(k)f<<",";f<<"[";for(int j=0;j<(int)G.size();j++){if(j)f<<",";f<<G[j][k];}f<<"]";}f<<"]}\n";id++;if(id%100==0)cout<<"polynomials="<<id<<endl;}
 cout<<"COMPLETE templates="<<templates.size()<<endl;
}
