import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicSixExponentials

/-!
# Generic algebraic-base spectrum

This module packages membership in the divisible hull of two positive real bases as a
positive-power relation with nonnegative exponents.  It then uses the algebraic Six
Exponentials theorem to classify the positive algebraic bases whose `x`-th real powers are
algebraic.
-/

namespace LeanProofs.AlgebraicBaseSpectrum

open Set

noncomputable section

/-- Nonnegative monomials in `a,b` are unique.  For positive bases this is the usual
multiplicative-independence condition. -/
def PairMonomialIndependent (a b : ℝ) : Prop :=
  Function.Injective (fun u : ℕ × ℕ ↦ a ^ u.1 * b ^ u.2)

/-- A denominator-free presentation of membership of `c` in the divisible hull of the group
generated by `a,b`: after multiplying by an `a,b` monomial, a positive power of `c` is
another `a,b` monomial. -/
def HasPositivePairPowerRelation (a b c : ℝ) : Prop :=
  ∃ n : ℕ, 0 < n ∧ ∃ i j k l : ℕ,
    a ^ k * b ^ l * c ^ n = a ^ i * b ^ j

private def tripleMonomial (a b c : ℝ) (u : ℕ × ℕ × ℕ) : ℝ :=
  a ^ u.1 * b ^ u.2.1 * c ^ u.2.2

private theorem collision_of_positivePairPowerRelation
    {a b c : ℝ} (hrel : HasPositivePairPowerRelation a b c) :
    ¬ Function.Injective (tripleMonomial a b c) := by
  rintro hinj
  obtain ⟨n, hn, i, j, k, l, hrel⟩ := hrel
  have htuple := hinj
    (a₁ := ((k, l, n) : ℕ × ℕ × ℕ))
    (a₂ := ((i, j, 0) : ℕ × ℕ × ℕ)) (by
      simpa [tripleMonomial] using hrel)
  have : n = 0 := congrArg (fun u : ℕ × ℕ × ℕ ↦ u.2.2) htuple
  omega

private theorem positivePairPowerRelation_of_collision_lt
    {a b c : ℝ} (hc : 0 < c)
    {i j k i' j' k' : ℕ} (hkk' : k < k')
    (hcollision :
      tripleMonomial a b c (i, j, k) = tripleMonomial a b c (i', j', k')) :
    HasPositivePairPowerRelation a b c := by
  let n : ℕ := k' - k
  have hn : 0 < n := Nat.sub_pos_of_lt hkk'
  have hk' : k' = k + n := by
    dsimp only [n]
    omega
  have hcancel : a ^ i * b ^ j = (a ^ i' * b ^ j') * c ^ n := by
    apply mul_right_cancel₀ (pow_ne_zero k hc.ne')
    calc
      (a ^ i * b ^ j) * c ^ k = tripleMonomial a b c (i, j, k) := by
        simp [tripleMonomial]
      _ = tripleMonomial a b c (i', j', k') := hcollision
      _ = (a ^ i' * b ^ j') * c ^ (k + n) := by
        rw [hk']
        simp [tripleMonomial]
      _ = ((a ^ i' * b ^ j') * c ^ n) * c ^ k := by
        rw [pow_add]
        ring
  exact ⟨n, hn, i, j, i', j', hcancel.symm⟩

/-- With an independent pair `a,b`, adjoining `c` preserves uniqueness of nonnegative
monomials exactly when `c` has no positive pair-power relation. -/
theorem tripleMonomial_injective_iff
    {a b c : ℝ} (hc : 0 < c) (hab : PairMonomialIndependent a b) :
    Function.Injective (tripleMonomial a b c) ↔
      ¬ HasPositivePairPowerRelation a b c := by
  constructor
  · intro hinj hrel
    exact collision_of_positivePairPowerRelation hrel hinj
  · intro hno
    rintro ⟨i, j, k⟩ ⟨i', j', k'⟩ hcollision
    by_cases hkk' : k = k'
    · subst k'
      have hbase : a ^ i * b ^ j = a ^ i' * b ^ j' := by
        apply mul_right_cancel₀ (pow_ne_zero k hc.ne')
        simpa [tripleMonomial] using hcollision
      have hij : (i, j) = (i', j') := hab hbase
      cases hij
      rfl
    · rcases lt_or_gt_of_ne hkk' with hlt | hgt
      · exact (hno (positivePairPowerRelation_of_collision_lt hc hlt hcollision)).elim
      · exact (hno (positivePairPowerRelation_of_collision_lt hc hgt hcollision.symm)).elim

private theorem natPow_rpow (a : ℝ) (ha : 0 < a) (n : ℕ) (x : ℝ) :
    (a ^ n) ^ x = (a ^ x) ^ n := by
  calc
    (a ^ n) ^ x = (a ^ (n : ℝ)) ^ x := by rw [Real.rpow_natCast]
    _ = a ^ ((n : ℝ) * x) := by rw [← Real.rpow_mul ha.le]
    _ = a ^ (x * (n : ℝ)) := by rw [mul_comm]
    _ = (a ^ x) ^ n := Real.rpow_mul_natCast ha.le x n

private theorem isAlgebraic_rpow_of_positivePairPowerRelation
    {a b c x : ℝ} (ha : 0 < a) (hb : 0 < b) (hc : 0 < c)
    (haPowAlg : IsAlgebraic ℚ (a ^ x))
    (hbPowAlg : IsAlgebraic ℚ (b ^ x))
    (hrel : HasPositivePairPowerRelation a b c) :
    IsAlgebraic ℚ (c ^ x) := by
  obtain ⟨n, hn, i, j, k, l, hrel⟩ := hrel
  apply IsAlgebraic.of_pow hn
  have hden : a ^ k * b ^ l ≠ 0 := by positivity
  have hcn : c ^ n = (a ^ i * b ^ j) / (a ^ k * b ^ l) := by
    apply (eq_div_iff hden).2
    simpa [mul_comm, mul_left_comm, mul_assoc] using hrel
  rw [Real.rpow_pow_comm hc.le x n, hcn,
    Real.div_rpow (by positivity) (by positivity),
    Real.mul_rpow (by positivity) (by positivity),
    Real.mul_rpow (by positivity) (by positivity),
    natPow_rpow a ha i x, natPow_rpow b hb j x,
    natPow_rpow a ha k x, natPow_rpow b hb l x,
    div_eq_mul_inv]
  exact ((haPowAlg.pow i).mul (hbPowAlg.pow j)).mul
    (((haPowAlg.pow k).mul (hbPowAlg.pow l)).inv)

/-- Generic exact algebraic-base spectrum.  For an irrational exponent with algebraic outputs
at an independent positive algebraic pair `a,b`, the output at a third positive algebraic
base `c` is algebraic exactly when `c` belongs to the divisible hull of `a,b`. -/
theorem real_rpow_isAlgebraic_iff_hasPositivePairPowerRelation
    {a b c x : ℝ}
    (ha : 0 < a) (hb : 0 < b) (hc : 0 < c)
    (haAlg : IsAlgebraic ℚ a) (hbAlg : IsAlgebraic ℚ b)
    (hcAlg : IsAlgebraic ℚ c)
    (hab : PairMonomialIndependent a b)
    (hx : x ∉ Set.range ((↑) : ℚ → ℝ))
    (haPowAlg : IsAlgebraic ℚ (a ^ x))
    (hbPowAlg : IsAlgebraic ℚ (b ^ x)) :
    IsAlgebraic ℚ (c ^ x) ↔ HasPositivePairPowerRelation a b c := by
  constructor
  · intro hcPowAlg
    by_contra hno
    apply hx
    exact LeanProofs.AlgebraicSixExponentials.rational_of_three_real_rpows_isAlgebraic_of_monomial_injective
        ha hb hc haAlg hbAlg hcAlg
        ((tripleMonomial_injective_iff hc hab).2 hno)
        haPowAlg hbPowAlg hcPowAlg
  · exact isAlgebraic_rpow_of_positivePairPowerRelation
      ha hb hc haPowAlg hbPowAlg

end

end LeanProofs.AlgebraicBaseSpectrum
