import ExponentialIdentities.TwoBaseIntegerExponent.CandidateLattice
import ExponentialIdentities.TwoBaseIntegerExponent.KernelDichotomy
import ExponentialIdentities.TwoBaseIntegerExponent.SecondIterateKernel
import ExponentialIdentities.TwoBaseIntegerExponent.TowerRigidity
import ExponentialIdentities.TwoBaseIntegerExponent.SymmetricTowerConstants
import ExponentialIdentities.TwoBaseIntegerExponent.PrimeLogSpaceOperator
import ExponentialIdentities.TwoBaseIntegerExponent.ArbitraryNodeRepulsion
import ExponentialIdentities.TwoBaseIntegerExponent.ClearedDividedDifference
import ExponentialIdentities.TwoBaseIntegerExponent.SuperfactorialDeterminant
import ExponentialIdentities.TwoBaseIntegerExponent.SemigroupGapBound
import ExponentialIdentities.TwoBaseIntegerExponent.OrderedChamberPositivity
import ExponentialIdentities.TwoBaseIntegerExponent.ExternalRankClassification
import ExponentialIdentities.TwoBaseIntegerExponent.PerfectPowerContent
import ExponentialIdentities.TwoBaseIntegerExponent.RootSaturation
import ExponentialIdentities.TwoBaseIntegerExponent.ValuationLattice
import ExponentialIdentities.TwoBaseIntegerExponent.RationalFunctionRigidity
import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicTowerTransition
import ExponentialIdentities.TwoBaseIntegerExponent.CrossBaseTowerTransition
import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicExponentLocus
import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicOutputLocus
import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicBaseSpectrum
import ExponentialIdentities.TwoBaseIntegerExponent.CanonicalRadicalMixedOutput
import ExponentialIdentities.TwoBaseIntegerExponent.SimultaneousRadicalDegrees
import ExponentialIdentities.TwoBaseIntegerExponent.RationalFunctionAlgebraicLocus
import ExponentialIdentities.TwoBaseIntegerExponent.MinPlusCeiling
import ExponentialIdentities.TwoBaseIntegerExponent.TropicalInitialForm
import ExponentialIdentities.TwoBaseIntegerExponent.BlockFiberFactorization
import ExponentialIdentities.TwoBaseIntegerExponent.BlockVandermondeValuationBudget
import ExponentialIdentities.TwoBaseIntegerExponent.AllLayerUnitBasis
import ExponentialIdentities.TwoBaseIntegerExponent.FinitePlaceShortRelationCore
import ExponentialIdentities.TwoBaseIntegerExponent.UnitOrderingGain
import ExponentialIdentities.TwoBaseIntegerExponent.TropicalBlockApplication
import ExponentialIdentities.TwoBaseIntegerExponent.BeattyTropicalFiber
import ExponentialIdentities.TwoBaseIntegerExponent.RowBlockLaplaceExpansion
import ExponentialIdentities.TwoBaseIntegerExponent.AssignmentExcessGeometry
import ExponentialIdentities.TwoBaseIntegerExponent.RowBlockUnitDivisibility
import ExponentialIdentities.TwoBaseIntegerExponent.MixedDeterminantUnitBridge
import ExponentialIdentities.TwoBaseIntegerExponent.GlobalMixedPrefixCascade
import ExponentialIdentities.TwoBaseIntegerExponent.ComplexSolutions
import ExponentialIdentities.TwoBaseIntegerExponent.SparsePowerCurve
import ExponentialIdentities.TwoBaseIntegerExponent.RationalOrbitGrid
import ExponentialIdentities.TwoBaseIntegerExponent.RationalContactRigidity
import ExponentialIdentities.TwoBaseIntegerExponent.RestrictedMatrixCoefficient
import ExponentialIdentities.TwoBaseIntegerExponent.IntegralPowerMatrix
import ExponentialIdentities.TwoBaseIntegerExponent.JordanFirstJet
import ExponentialIdentities.TwoBaseIntegerExponent.CandidateAlternant
import ExponentialIdentities.TwoBaseIntegerExponent.SynchronizedSumDecoder
import ExponentialIdentities.TwoBaseIntegerExponent.RationalSumDecoder
import ExponentialIdentities.TwoBaseIntegerExponent.FormalPrimeDeterminant
import ExponentialIdentities.TwoBaseIntegerExponent.FermatQuotientDeterminant
import ExponentialIdentities.TwoBaseIntegerExponent.BoundaryDilationDefect
import ExponentialIdentities.TwoBaseIntegerExponent.DilationDifferenceQuotient
import ExponentialIdentities.TwoBaseIntegerExponent.CrossResidualScaling
import ExponentialIdentities.TwoBaseIntegerExponent.ResultantScaling
import ExponentialIdentities.TwoBaseIntegerExponent.NodeDivisorScaling
import ExponentialIdentities.TwoBaseIntegerExponent.CrossResultantBridge
import ExponentialIdentities.TwoBaseIntegerExponent.DenominatorCancellationCounterexample
import ExponentialIdentities.TwoBaseIntegerExponent.GridTransformNoGo
import ExponentialIdentities.TwoBaseIntegerExponent.CompoundEndpointRate
import ExponentialIdentities.TwoBaseIntegerExponent.BoundaryDisplacement
import ExponentialIdentities.TwoBaseIntegerExponent.FejerKernelCertificate
import ExponentialIdentities.TwoBaseIntegerExponent.SignedProgressionDeterminant
import ExponentialIdentities.TwoBaseIntegerExponent.GeometricVandermondeSmith
import ExponentialIdentities.TwoBaseIntegerExponent.SmithProfileCore
import ExponentialIdentities.TwoBaseIntegerExponent.ContentNormalizedProfileFinite
import ExponentialIdentities.TwoBaseIntegerExponent.DeepSubresultantCost
import ExponentialIdentities.TwoBaseIntegerExponent.MomentArithmetic
import ExponentialIdentities.TwoBaseIntegerExponent.RankGeometry
import ExponentialIdentities.TwoBaseIntegerExponent.UnimodularGapCollision
import ExponentialIdentities.TwoBaseIntegerExponent.OrbitHeightEntropy
import ExponentialIdentities.TwoBaseIntegerExponent.ProjectiveDefect
import ExponentialIdentities.TwoBaseIntegerExponent.CarryPath
import ExponentialIdentities.TwoBaseIntegerExponent.DfiniteExponentCore
import ExponentialIdentities.TwoBaseIntegerExponent.LambertCocycleFinite
import ExponentialIdentities.TwoBaseIntegerExponent.PositiveCoefficientClosure
import ExponentialIdentities.TwoBaseIntegerExponent.FiniteDilationAlternation
import ExponentialIdentities.TwoBaseIntegerExponent.NewtonCollisionCore
import ExponentialIdentities.TwoBaseIntegerExponent.RankOneNewtonKummer
import ExponentialIdentities.TwoBaseIntegerExponent.SignedOrbitNormFinite
import ExponentialIdentities.TwoBaseIntegerExponent.MixedGapKummerFinite
import ExponentialIdentities.TwoBaseIntegerExponent.DyadicPrivateSupport
import ExponentialIdentities.TwoBaseIntegerExponent.CatalanTangentCore
import ExponentialIdentities.TwoBaseIntegerExponent.MixedRadixCarryFinite
import ExponentialIdentities.TwoBaseIntegerExponent.CaptureMultiplier
import ExponentialIdentities.TwoBaseIntegerExponent.RadixShadow
import ExponentialIdentities.TwoBaseIntegerExponent.BorrowBlockCore
import ExponentialIdentities.TwoBaseIntegerExponent.ValuationSlopeEnergy
import ExponentialIdentities.TwoBaseIntegerExponent.GeometricNewtonInterpolation
import ExponentialIdentities.TwoBaseIntegerExponent.QNewtonEndpointDefect
import ExponentialIdentities.TwoBaseIntegerExponent.QNewtonOffAxisTransfer
import ExponentialIdentities.TwoBaseIntegerExponent.AdelicDrift
import ExponentialIdentities.TwoBaseIntegerExponent.SturmianProbability
import ExponentialIdentities.TwoBaseIntegerExponent.SturmianGeneratingSeries
import ExponentialIdentities.TwoBaseIntegerExponent.MatchedGapAmplification
import ExponentialIdentities.TwoBaseIntegerExponent.PolynomialApproximationTax
import ExponentialIdentities.TwoBaseIntegerExponent.ConsecutiveLogMeanBounds
import ExponentialIdentities.TwoBaseIntegerExponent.MixedMahlerFinite
import ExponentialIdentities.TwoBaseIntegerExponent.TwoScaleSupportFinite
import ExponentialIdentities.TwoBaseIntegerExponent.KummerCompatibilityFinite
import ExponentialIdentities.TwoBaseIntegerExponent.PrimePowerKummerCoherence
import ExponentialIdentities.TwoBaseIntegerExponent.ReciprocalHalfContact
import ExponentialIdentities.TwoBaseIntegerExponent.ReciprocalMomentLatticeFinite
import ExponentialIdentities.TwoBaseIntegerExponent.TwoStarContent
import ExponentialIdentities.TwoBaseIntegerExponent.CenteredTrace
import ExponentialIdentities.TwoBaseIntegerExponent.PrimeTopIsolation
import ExponentialIdentities.TwoBaseIntegerExponent.ExponentLatticeMask
import ExponentialIdentities.TwoBaseIntegerExponent.FactorialCocycle
import ExponentialIdentities.TwoBaseIntegerExponent.SparseCoaction
import ExponentialIdentities.TwoBaseIntegerExponent.RestrictedDenominatorDirichlet
import ExponentialIdentities.TwoBaseIntegerExponent.TerminalFactorialIndependence
import ExponentialIdentities.TwoBaseIntegerExponent.RationalHankelTriple
import ExponentialIdentities.TwoBaseIntegerExponent.SmoothSemigroupCore
import ExponentialIdentities.TwoBaseIntegerExponent.ExternalPrimeNewtonWall
import ExponentialIdentities.TwoBaseIntegerExponent.CriticalWindowContraction
import ExponentialIdentities.TwoBaseIntegerExponent.CompactChartArea
import ExponentialIdentities.TwoBaseIntegerExponent.ToricMonomialRigidity
import ExponentialIdentities.TwoBaseIntegerExponent.FiniteCheck8192
import ExponentialIdentities.TwoBaseIntegerExponent.FiniteCheck16384

/-!
# Assumption audit for the newly formalized modules

Each `#print axioms` below must report only the three standard Lean foundations
`propext`, `Classical.choice`, `Quot.sound`.  Anything else — in particular
`sorryAx` — is a trust breach and must fail review.

The two explicit analytic inputs of this round, `RpowDividedDifferenceMeanValue`
and `NewtonFactorization`, are *hypotheses of theorems*, not axioms, so they do
not and cannot appear here; they are visible instead in the statements of
`le_vandermondeProduct_of_dividedDiffMeanValue`, `packing_of_dividedDiffMeanValue`
and `card_le_ten_thousand_log_sq`.
-/

namespace LeanProofs.TwoBaseIntegerExponent

-- LCM-cleared barycentric integer functional and its cubic specialization
#print axioms ClearedDividedDifference.signedDenominator_dvd_lcm
#print axioms ClearedDividedDifference.denominatorLCM_dvd
#print axioms ClearedDividedDifference.clearedCoefficient_mul_denominator
#print axioms ClearedDividedDifference.cleared_moment_eq_zero
#print axioms ClearedDividedDifference.cast_clearedFunctional_eq_lcm_mul_dividedDiff
#print axioms ClearedDividedDifference.lcm_mul_dividedDiff_mem_intCast
#print axioms ClearedDividedDifference.fourNodes_coefficients
#print axioms ClearedDividedDifference.fourNodes_certificate
#print axioms ClearedDividedDifference.fourNodes_moment_eq_zero

-- Generic arbitrary-pair algebraic-base spectrum (report 16)
#print axioms LeanProofs.AlgebraicBaseSpectrum.tripleMonomial_injective_iff
#print axioms LeanProofs.AlgebraicBaseSpectrum.real_rpow_isAlgebraic_iff_hasPositivePairPowerRelation

-- Exact finite algebra behind the mixed Mahler equation (report 16)
#print axioms mixedMahlerTrunc_succ_succ

-- Exact finite algebra behind the ordinary two-scale support equation (report 18)
#print axioms twoScaleSupportTrunc_succ_succ

-- Exact Smith form of the geometric Vandermonde (report 17)
#print axioms qPascal_mul_qFactorProduct
#print axioms qSmithFactor_report_formula
#print axioms qSmithFactor_dvd_succ
#print axioms qSmithFactor_pos
#print axioms geometricVandermonde_isUnimodularEquivalent_qSmithDiagonal

-- Exact finite q-Newton interpolation and extrapolation (report 19)
#print axioms qNewtonExpansion_eq_pow
#print axioms qNewtonTruncValue_eq_pow_of_le
#print axioms qNewtonTruncValue_remainder
#print axioms qNewtonTruncValue_first_omitted

-- Finite q-Newton basis dilation and exact endpoint defect
#print axioms QNewtonEndpointDefect.dilate_geometricNodeBasis_succ
#print axioms QNewtonEndpointDefect.geometricNodeDenominator_succ
#print axioms QNewtonEndpointDefect.qNewtonCoefficient_succ
#print axioms QNewtonEndpointDefect.qNewtonPolynomial_endpoint_dilation_defect

-- Finite off-axis q-Newton transfer recurrence and exact closed solution
#print axioms QNewtonOffAxisTransfer.transferDenominator_succ
#print axioms QNewtonOffAxisTransfer.transferForcing_succ
#print axioms QNewtonOffAxisTransfer.transported_recurrence
#print axioms QNewtonOffAxisTransfer.transfer_solution
#print axioms QNewtonOffAxisTransfer.transfer_solution_sum

-- Rational first-jet arithmetic and the base-two Jordan closing criterion (report 20)
#print axioms rational_of_rpow_and_firstJet
#print axioms firstJet_rational_of_jordanFirstJet_rational
#print axioms integer_of_two_rpow_integer_of_jordanFirstJet_rational

-- Candidate lattice
#print axioms twoBaseNaturalCandidate_gcd
#print axioms twoBaseNaturalCandidate_lcm
#print axioms exists_fixed_odd_core_of_not_alaogluErdosConjecture

-- Kernel dichotomy
#print axioms multiplicativelyDependentOutputs_iff_secondIterateKernelRelation
#print axioms twoBaseNonintegerSolution_kernel_dichotomy

-- Second-iterate kernel
#print axioms kernelPairs_det_eq_zero
#print axioms kernelPairs_prop_dim
#print axioms saturatedKernel_invariant

-- Tower rigidity
#print axioms alaogluErdosConjecture_iff_two_rpow_square_cube_isAlgebraic
#print axioms TwoBaseNonintegerSolution.base_two_tower_dichotomy

-- Symmetric tower constants
#print axioms TwoBaseNonintegerSolution.hasPositiveRationalPower_symmetricTowerThree
#print axioms TwoBaseNonintegerSolution.hasPositiveRationalPower_symmetricTowerTwo

-- Prime-log-space operator
#print axioms primeLogSpanThetaPullbackRankOne_iff_rationalOutput
#print axioms alaogluErdosConjecture_of_primeLogSpanThetaPullbackRankOne

-- Arbitrary-node repulsion
#print axioms det_nodeMatrix_eq_vandermondeProduct_mul_dividedDiff
#print axioms le_vandermondeProduct_of_dividedDiffMeanValue
#print axioms packing_of_dividedDiffMeanValue

-- Universal superfactorial content and strengthened arbitrary-node repulsion
#print axioms interpolationSuperfactorial_dvd_nodeIntMatrix_det
#print axioms det_nodeIntMatrix_consecutive_lastOrdinate
#print axioms interpolationSuperfactorial_le_abs_det_nodeMatrix
#print axioms interpolationSuperfactorial_mul_inv_le_vandermondeProduct_of_dividedDifference
#print axioms superfactorial_mul_le_vandermondeProduct_of_dividedDiffMeanValue
#print axioms superfactorial_packing_of_dividedDiffMeanValue

-- Semigroup gap bound
#print axioms abs_det_le_of_abs_entry_le
#print axioms det_semigroupMatrix_ne_zero
#print axioms card_le_ten_thousand_log_sq

-- Ordered-chamber positivity
#print axioms det_rpowVandermonde_pos
#print axioms det_semigroupMatrix_pos
#print axioms one_le_det_semigroupMatrix_of_strictMono

-- External-rank classification
#print axioms existsUnique_hasExternalRankType
#print axioms TwoBaseNonintegerSolution.externalRankClassification
#print axioms hasExternalRankType_independent_iff_not_multiplicativelyDependentOutputs

-- Perfect-power content
#print axioms isCommonOutputPower_iff_twoBaseIntegralSolution_div

-- Root saturation
#print axioms exists_canonicalConeData_of_not_alaogluErdosConjecture

-- Valuation lattice
#print axioms finite_quotient_ratOutputLattice
#print axioms closure_quotient_pair_eq_top

-- Rational-function rigidity
#print axioms twoBaseIntegralSolution_mul_iff
#print axioms alaogluErdosConjecture_iff_solutions_closed_under_mul
#print axioms alaogluErdosConjecture_iff_solutions_closed_under_sq
#print axioms rationalFunction_rigidity_at_generator

-- Algebraic exponent/output loci and simultaneous radicals
#print axioms hasPositiveTwoThreeUnitPower_two_rpow_iff_affine_logRatio
#print axioms TwoBaseNonintegerSolution.twoRpowAlgebraicTransition_iff_affine_logRatio
#print axioms TwoBaseNonintegerSolution.not_two_distinct_algebraic_tower_transitions
#print axioms TwoBaseNonintegerSolution.card_algebraicTowerTransitionDepths_le_one
#print axioms alaogluErdosConjecture_iff_two_distinct_tower_transitions_algebraic
#print axioms TwoBaseNonintegerSolution.threeRpowAlgebraicTransition_iff_scaled_affine_logRatio
#print axioms TwoBaseNonintegerSolution.not_baseTwo_and_baseThree_tower_transitions
#print axioms TwoBaseNonintegerSolution.not_two_distinct_baseThree_tower_transitions
#print axioms TwoBaseNonintegerSolution.eq_of_twoOrThree_tower_transitions
#print axioms TwoBaseNonintegerSolution.not_higher_unitDirectionTowerTransition_of_depth_one
#print axioms TwoBaseNonintegerSolution.not_higher_unitDirectionTowerTransition_of_kernelRelation
#print axioms TwoBaseNonintegerSolution.not_higher_unitDirectionTowerTransition_of_dependentOutputs
#print axioms TwoBaseNonintegerSolution.twoThreeRpowAlgebraic_iff_affine
#print axioms TwoBaseNonintegerSolution.algebraic_two_three_squared_monomial_locus_trichotomy
#print axioms alaogluErdosConjecture_iff_no_squaredTwoThreeMonomial_coordinateFace
#print axioms TwoBaseNonintegerSolution.transcendental_mixed_canonical_radical_output
#print axioms TwoBaseNonintegerSolution.algebraic_mixed_canonical_radical_output_imp_coordinate_face
#print axioms threeFreeCoreRpow_exact_radical_degree_of_simultaneous_normalization
#print axioms mixed_coreRpow_exact_radical_degree_of_zero_baseDepths

-- Rational-function algebraic-output detectors
#print axioms TwoBaseNonintegerSolution.twoThreeRpowAlgebraic_rationalFunction_iff
#print axioms twoThreeRpowAlgebraic_rationalFunction_iff_integer_or_affine
#print axioms alaogluErdosConjecture_iff_twoThreeRpowAlgebraic_rationalFunction
#print axioms twoThreeRpowAlgebraic_polynomial_iff_integer_of_two_le_natDegree
#print axioms alaogluErdosConjecture_iff_twoThreeRpowAlgebraic_polynomial_of_two_le_natDegree
#print axioms exists_generator_with_exact_rationalFunction_algebraic_and_integral_loci

-- Min-plus ceiling
#print axioms minPlusContent_le_of_le
#print axioms minPlusContent_le_of_natAbs_le
#print axioms primeContent_le_log
#print axioms det_dvd_and_not_dvd_of_unique_min

-- Tied tropical initial forms
#print axioms det_pow_add_dvd_iff_signedLeibnizQuotientSum_dvd
#print axioms det_pow_succ_dvd_iff_signedLeibnizQuotientSum_eq_zero
#print axioms det_pow_succ_dvd_iff_tiedFiberSum_eq_zero
#print axioms det_pow_succ_dvd_iff_initialFiberSum_eq_zero

-- Tied-fiber block and Vandermonde factorizations
#print axioms sum_blockPreserving_eq_prod_blockDet
#print axioms sum_basePerm_mul_blockPreserving_eq_sign_mul_prod_blockDet
#print axioms sum_blockPreserving_eq_prod_vandermonde_of_reindex
#print axioms sum_blockPreserving_consecutivePowers_eq_prod_vandermonde
#print axioms det_pow_succ_dvd_iff_prod_blockDet_eq_zero
#print axioms det_pow_succ_dvd_iff_prod_vandermonde_eq_zero

-- Exact collision energy and elementary finite block-valuation budgets
#print axioms padicValNat_natVandermondeProduct_eq_sum_collisionCount
#print axioms padicValNat_natAbs_pow_sub_pow_le
#print axioms padicValNat_blockVandermondeNatProduct
#print axioms padicValNat_blockVandermondeNatProduct_le_cubeBudget
#print axioms padicValNat_blockVandermondeNatProduct_le_powDifferenceCubeBudget

-- Cascade-independent all-layer divisibility from unit-adapted monic bases
#print axioms prod_columnDivisor_dvd_det
#print axioms pow_sum_columnWeight_dvd_det
#print axioms pow_sum_columnWeight_dvd_det_of_unimodular_mul
#print axioms pow_sum_rowWeight_dvd_det
#print axioms pow_mul_card_dvd_det_of_rows_divisible
#print axioms pow_mul_card_dvd_det_of_eliminatedRows
#print axioms pow_sum_dvd_det_vandermonde_of_monicBasis
#print axioms two_pow_sum_degree_dvd_det_vandermonde_of_odd
#print axioms three_pow_sum_halfDegree_dvd_det_vandermonde_of_unit
#print axioms two_pow_sum_degree_add_factorialVal_dvd_det_vandermonde
#print axioms three_pow_sum_halfDegree_add_factorialVal_dvd_det_vandermonde

-- Exact block sums and finite cubic bounds for the unit-ordering gains
#print axioms twoUnitOrderingWeight_eq_two_mul_sub_digitSum
#print axioms two_mul_threeUnitOrderingWeight_eq_three_mul_sub_digitSum
#print axioms twoUnitBlockGain_eq
#print axioms threeUnitBlockGain_eq
#print axioms twoUnitBlockGain_le_square
#print axioms two_mul_threeUnitBlockGain_le_square
#print axioms sum_twoUnitBlockGain_le_cube
#print axioms two_mul_sum_threeUnitBlockGain_le_cube

-- Concrete Beatty minimizing fiber, gap, and determinant expansion
#print axioms rankOneAssignmentCost_eq_iff_blockPreserving
#print axioms beattyAssignmentCost_eq_iff_blockPreserving
#print axioms beattyAssignmentCost_add_floor_le_of_not_blockPreserving
#print axioms beattyPower_pow_floor_dvd_quotient_of_not_blockPreserving
#print axioms det_beattyPowerMatrix_pow_succ_dvd_iff_prod_blockDet_eq_zero
#print axioms det_beattyPowerMatrix_eq_pow_mul_blockDet_add_pow_floor_mul

-- Exact all-layer grouping by ordered row partitions
#print axioms sum_permutationRowBlockAssignmentFiber_eq_sign_mul_prod_blockDet
#print axioms det_eq_sum_rowBlockAssignment_minorProducts
#print axioms det_rankOnePowerMatrix_eq_sum_rowBlockAssignment_minorProducts
#print axioms det_rankOnePowerMatrix_eq_minPow_mul_sum_assignmentExcess
#print axioms det_rankOnePowerMatrix_eq_minPow_mul_truncatedAssignmentSum
#print axioms beattyRowBlockAssignment_excess_ge_floor

-- Prefix-crossing geometry and finite cascade-support counts
#print axioms finPrefixSum_canonical_le_assignment
#print axioms rowBlockCrossingEnergy_eq_reverseFinRank_excess
#print axioms rankOneAssignmentCost_add_mul_reverseExcess_le_of_gapDecomposition
#print axioms beattyFloor_mul_rowBlockCrossingEnergy_le_excess
#print axioms card_rowBlockAssignment_crossingEnergy_lt_choose
#print axioms card_rowBlockAssignment_excess_lt_choose_of_crossing_lower_bound
#print axioms card_beattyRowBlockAssignment_excess_lt
#print axioms rowBlockPrefixSurplus_last_eq_zero
#print axioms card_rowBlockAssignment_crossingEnergy_lt_choose_of_pos
#print axioms card_rowBlockAssignment_excess_lt_choose_of_crossing_lower_bound_of_pos
#print axioms card_beattyRowBlockAssignment_excess_lt_of_pos

-- Uniform unit-ordering divisors throughout the row-assignment cascade
#print axioms rowBlockOrderingExponent_two_eq_sum_blockGain
#print axioms rowBlockOrderingExponent_three_eq_sum_blockGain
#print axioms det_fiberMonicBasisChange_eq_one
#print axioms pow_dvd_weighted_rowBlockAssignmentSum
#print axioms fiberScaledConsecutivePowerMatrix_mul_fiberMonicBasisChange
#print axioms two_pow_rowBlockOrderingExponent_dvd_minorProduct_fiberScaledConsecutivePowers
#print axioms three_pow_rowBlockOrderingExponent_dvd_minorProduct_fiberScaledConsecutivePowers
#print axioms pow_sum_dvd_det_fiberScaledConsecutivePowerMatrix_of_monicBasis
#print axioms two_pow_rowBlockOrderingExponent_dvd_det_fiberScaledConsecutivePowers
#print axioms three_pow_rowBlockOrderingExponent_dvd_det_fiberScaledConsecutivePowers
#print axioms pow_minCost_add_commonMinorExponent_dvd_det_rankOnePowerMatrix
#print axioms two_pow_minCost_add_rowBlockOrderingExponent_dvd_det_rankOnePowerMatrix
#print axioms three_pow_minCost_add_rowBlockOrderingExponent_dvd_det_rankOnePowerMatrix

-- Bridge from mixed integer matrices to the row-block unit divisors
#print axioms sortedMixedExponentBoxPair_weight_strictMono
#print axioms sortedMixedExponentBoxPrefix_weight_strictMono
#print axioms submatrix_mixedIntegerPowerMatrix_eq_two_rankOnePowerMatrix
#print axioms submatrix_mixedIntegerPowerMatrix_eq_three_rankOnePowerMatrix
#print axioms dvd_det_of_dvd_det_columnPermute
#print axioms two_pow_minCost_add_rowBlockOrderingExponent_dvd_det_mixedIntegerPowerMatrix
#print axioms three_pow_minCost_add_rowBlockOrderingExponent_dvd_det_mixedIntegerPowerMatrix

-- Concrete global mixed-prefix cascade and unit-divisor specialization
#print axioms sortedMixedExponentBoxPrefix_weight_lt_of_not_mem
#print axioms lexMixedPrefixFiberEquiv_degree
#print axioms colexMixedPrefixFiberEquiv_degree
#print axioms sign_mul_det_globalMixedPrefix_two_eq_minPow_mul_truncatedAssignmentSum
#print axioms sign_mul_det_globalMixedPrefix_three_eq_minPow_mul_truncatedAssignmentSum
#print axioms two_pow_globalMixedPrefix_minCost_add_unit_dvd_det
#print axioms three_pow_globalMixedPrefix_minCost_add_unit_dvd_det
#print axioms two_pow_globalMixedPrefix_structuralOutput_dvd_det
#print axioms three_pow_globalMixedPrefix_structuralOutput_dvd_det

-- Complex exponents
#print axioms im_eq_zero_of_complexTwoBaseIntegralSolution
#print axioms twoBaseIntegralSolution_re_of_complex

-- Restricted matrix-coefficient reformulation
#print axioms restrictedLogDet_eq_zero_iff_exists_commonExponent
#print axioms restrictedLogMatrix_eq_rankOne
#print axioms restrictedMatrixCoefficient_ne_zero_of_not_integer
#print axioms alaogluErdosConjecture_iff_restrictedMatrixCoefficientPrinciple

-- A fixed split integral matrix and its exact integral-time reformulation
#print axioms splitTwoThreeRealPowerMatrix_hasIntegralEntries_iff
#print axioms alaogluErdosConjecture_iff_splitTwoThreeRealPowerMatrix

-- Exact candidate alternant from a rational approximation
#print axioms det_affineExponentVandermonde
#print axioms rpowAffineExponentMatrix_eq_affineExponentVandermonde
#print axioms candidateClusterExponent_eq_semigroupCombination
#print axioms det_candidateApproximationAlternant
#print axioms det_candidateApproximationAlternant_ne_zero

-- Exact synchronized ordinary/power-sum decoder (report 15)
#print axioms strictAntiOn_fixedSumRpow
#print axioms eq_of_ordered_sum_eq_rpow_sum_eq
#print axioms eq_or_swap_of_sum_eq_rpow_sum_eq

-- Rational synchronized-sum decoder degree bound (report 15)
#print axioms rational_sum_decoder_card_le

-- Formal prime-symbol determinant and sparse Structural Rank reformulation
#print axioms primeFactorLinearForm_eval₂_log
#print axioms formalPrimeDeterminant_eval₂_log
#print axioms formalPrimeDeterminant_eq_zero_iff
#print axioms alaogluErdosConjecture_iff_sparsePrimeLogStructuralRankPrinciple

-- Exact sparse interpolation on irrational power curves
#print axioms powerCurveFrequency_injective
#print axioms sparsePowerCurve_coeff_eq_zero_of_zeros
#print axioms card_le_of_sparsePowerCurve_eq_zero
#print axioms det_sparsePowerCurveMatrix_ne_zero
#print axioms det_natPowerCurveEvaluationMatrix_ne_zero
#print axioms positiveNodeInterpolant_support_card
#print axioms positiveNodeInterpolant_eval

-- Exact rational-grid collisions and the sharp one-monomial certificate
#print axioms newRowWeight_mem_previous_iff
#print axioms card_previous_inter_newRow
#print axioms card_rationalOrbitWeights
#print axioms card_irrationalOrbitParameters
#print axioms squareGrid_le_of_sparsePowerCurve_eq_zero
#print axioms rationalOrbitNodePolynomial_support_card
#print axioms rationalOrbitNodePolynomial_support_card_eq
#print axioms rationalOrbitNodePolynomial_eval_eq_zero
#print axioms exists_rational_squareGrid_certificate

-- Rational contact rigidity for an irrational power direction
#print axioms ratPolynomial_eval₂_ne_zero_of_transcendental
#print axioms homogeneousContactPolynomial_ne_zero
#print axioms homogeneousContactCoefficient_ne_zero
#print axioms rationalPade_firstContactCoefficient_ne_zero
#print axioms rationalPadeResidual_deriv_ne_zero

-- Rectangular interpolation-grid boundary compression
#print axioms rectangularNodePolynomial_dilate_vertical
#print axioms rectangularNodePolynomial_dilate_horizontal
#print axioms rectangularNodePolynomial_dvd_horizontalDefect
#print axioms rectangularNodePolynomial_dvd_verticalDefect
#print axioms existsUnique_squareGridResiduals
#print axioms squareBoundaryExpressions_natDegree_le
#print axioms boundaryDilation_commutator

-- Integral dilation-difference quotient and dyadic derivative reduction (structural-residual analysis)
#print axioms dilation_sub_eq_C_mul_X_mul_integralDilationQuotient
#print axioms dyadic_dilation_sub_factorization
#print axioms integralDilationQuotient_three_map_zmod_two

-- Cross-residual scaling, exact structural-prime resultant orders, and Smith-minor core
#print axioms crossResidualScaling_of_prime_scaled_defect
#print axioms exists_crossResidualNormalization_of_prime_scaled_defect
#print axioms Polynomial.resultant_eq_pow_mul_of_cross_normalizations
#print axioms Polynomial.resultant_eq_pow_mul_of_cross_normalizations_right
#print axioms Polynomial.exists_residue_unit_quotient_of_cross_normalization
#print axioms Polynomial.two_three_triangular_cross_residuals_dvd_resultant
#print axioms report14TriadicDefectDivisor_comp_two_pow
#print axioms report14DyadicDefectDivisor_comp_three_pow
#print axioms report14TriadicDivisorDyadicNormalization_constantCoeff_odd
#print axioms report14DyadicDivisorTriadicNormalization_constantCoeff_not_three_dvd
#print axioms report14_actual_divisors_cross_normalizations
#print axioms report14_simultaneous_favorable_cross_resultant
#print axioms actual_divisors_favorable_cross_resultant
#print axioms DenominatorCancellationExample.cross_resultant_eq
#print axioms DenominatorCancellationExample.delta_coprime_cross_resultant
#print axioms DenominatorCancellationExample.Q_coeff_three_den
#print axioms DenominatorCancellationExample.sixty_mul_Q_eq_P
#print axioms DenominatorCancellationExample.dyadic_defect_factorization
#print axioms DenominatorCancellationExample.triadic_defect_factorization
#print axioms DenominatorCancellationExample.rational_residual_resultant_eq
#print axioms simultaneous_cross_support_iff
#print axioms twiceSmithMu_le_sum_twiceTriangular
#print axioms twiceSmithMu_lt_sum_twiceTriangular_of_ne
#print axioms smithMu_le_matchingChooseCost
#print axioms pow_smithMu_dvd_weightedLowerToeplitz_minor
#print axioms ContentNormalizedProfileFinite.tri2_lt_psi2
#print axioms ContentNormalizedProfileFinite.direct_floor_doubled
#print axioms ContentNormalizedProfileFinite.compressed_permutation_profileCost2_lower
#print axioms twiceSmithMu_le_direct_shallow_cost
#print axioms twiceSmithMu_lt_direct_shallow_cost_of_direct
#print axioms direct_shallow_cost_eq_iff
#print axioms compoundEndpointRate_le_neg_l₂
#print axioms crossCompoundEndpointRate_le_neg_log_two

-- Reports 21--23: moment arithmetic, rank geometry, and unimodular gap collisions
#print axioms MomentArithmetic.rational_twoAtom_reproduction
#print axioms MomentArithmetic.firstHankel_commonDenominator
#print axioms MomentArithmetic.defect017_commonDenominator
#print axioms MomentArithmetic.defect127_commonDenominator
#print axioms MomentArithmetic.defect027_commonDenominator
#print axioms MomentArithmetic.firstHankel_numerator_localUnits
#print axioms MomentArithmetic.defect017_numerator_localUnits
#print axioms MomentArithmetic.defect127_numerator_localUnits
#print axioms MomentArithmetic.defect027_numerator_localUnits
#print axioms RankGeometry.dotProduct_hyperbolicGram_mulVec
#print axioms RankGeometry.rankThreeConicMatrix_det
#print axioms RankGeometry.symmetrizingMatrix_det
#print axioms RankGeometry.right_mul_symmetrizingMatrix_isSymm
#print axioms RankGeometry.exists_isUnit_rightMultiplier_isSymm
#print axioms RankGeometry.symmetric_outerProduct_normalForm
#print axioms UnimodularGapCollision.pow_eq_one_of_det_forward
#print axioms UnimodularGapCollision.pow_eq_one_of_det_reverse
#print axioms UnimodularGapCollision.eq_one_of_det_forward_one
#print axioms UnimodularGapCollision.eq_one_of_det_reverse_one
#print axioms UnimodularGapCollision.modEq_pow_one_of_det_forward
#print axioms UnimodularGapCollision.modEq_pow_one_of_det_reverse
#print axioms UnimodularGapCollision.modEq_one_of_det_forward_one
#print axioms UnimodularGapCollision.modEq_one_of_det_reverse_one
#print axioms OrbitHeightEntropy.integral_slope_floor_identity
#print axioms OrbitHeightEntropy.denominator_exponent_eq_floor_logb
#print axioms OrbitHeightEntropy.rotationDenominatorExponent_eq_floor_integralSlope
#print axioms OrbitHeightEntropy.rotationDenominatorExponent_eq_floor_logb
#print axioms OrbitHeightEntropy.exists_index_card_sub_one_le
#print axioms OrbitHeightEntropy.exists_simultaneous_exponential_denominator_lower_bound
#print axioms OrbitHeightEntropy.exists_report24_denominator_lower_bound
#print axioms ProjectiveDefect.piecewise_projective_bound
#print axioms ProjectiveDefect.padeDefect_le_projective
#print axioms ProjectiveDefect.depth_and_efficiency_threshold
#print axioms CarryPath.carryRepresentation_sum
#print axioms CarryPath.carryRepresentation_length
#print axioms CarryPath.carryConstruction_correct
#print axioms CarryPath.endpoint_tail_degree_lt
#print axioms CarryPath.word_eq_of_endpoint_eq_of_suffixVertices_eq
#print axioms DfiniteExponentCore.coeff_exponentRelationPolynomial_order
#print axioms DfiniteExponentCore.exponentRelationPolynomial_ne_zero

-- Universal formal Lambert cocycle (post-report-27 closure audit)
#print axioms lambertCoeff_native_dilation
#print axioms mixedDoubleDilation_lambertCoeff_universal
#print axioms lambertRationalCocycle_eq
#print axioms seriesDilationDifference_formalLambertSeries
#print axioms secondDilation_lambertRationalCocycle_commute
#print axioms secondDilation_lambertRationalCocycle_eq
#print axioms mixedDoubleDilation_formalLambertSeries_universal
#print axioms mixedDoubleDilation_two_three_universal

-- Finite positive-coefficient covariance closure (post-report closure audit)
#print axioms PositiveCoefficientClosure.two_mul_covariance_identity
#print axioms PositiveCoefficientClosure.pow_two_three_pair_nonneg
#print axioms PositiveCoefficientClosure.pow_two_three_pair_pos
#print axioms PositiveCoefficientClosure.finite_nonnegative_rankOne_atMostOne
#print axioms PositiveCoefficientClosure.finite_nonnegative_rankOne_eq_single

-- Finite positive/signed dilation filters preserve strict coefficient alternation
#print axioms FiniteDilationAlternation.dilationMultiplier_pos_of_nonnegative
#print axioms FiniteDilationAlternation.eventually_strictAlternating_positiveDilation
#print axioms FiniteDilationAlternation.not_eventually_nonnegative_of_strictAlternating
#print axioms FiniteDilationAlternation.dilationMultiplier_normalized_tendsto
#print axioms FiniteDilationAlternation.eventually_dilationMultiplier_sameSign_of_uniqueMax
#print axioms FiniteDilationAlternation.eventually_strictAlternating_finiteDilation_uniqueMax
#print axioms FiniteDilationAlternation.not_eventually_nonnegative_finiteDilation_uniqueMax

-- Newton append, collision, and translated-table algebra
#print axioms NewtonCollisionCore.appendPolynomial_eval_new
#print axioms NewtonCollisionCore.appendPolynomial_eval_old
#print axioms NewtonCollisionCore.residual_ne_zero_of_node_collision
#print axioms NewtonCollisionCore.value_eq_of_node_collision_of_residual_eq_zero
#print axioms NewtonCollisionCore.barycentricTop_scale

-- Higher Newton--Kummer product and integral-exponent calibration
#print axioms RankOneNewtonKummer.newtonCocycle_one
#print axioms RankOneNewtonKummer.newtonProduct_natPower_eq_zero
#print axioms RankOneNewtonKummer.newtonCocycle_natPower_eq_zero_of_lt
#print axioms RankOneNewtonKummer.newtonCocycle_endpoint_eq_zero
#print axioms RankOneNewtonKummer.newtonCocycle_natPower_eq_zero
#print axioms RankOneNewtonKummer.calibration_two
#print axioms RankOneNewtonKummer.calibration_three

-- Finite signed-orbit augmentation and axis-separable difference-grid identities
#print axioms SignedOrbitNormFinite.signedOrbit_fullProduct_eq_augmentation
#print axioms SignedOrbitNormFinite.mixedDifference_eq_zero
#print axioms SignedOrbitNormFinite.differenceGrid_twoMinor

-- Finite mixed-gap Kummer determinant and denominator retention
#print axioms MixedGapKummerFinite.mixedGap_determinant_identity
#print axioms MixedGapKummerFinite.sameResidue_obstruction
#print axioms MixedGapKummerFinite.denominatorRetention_of_one_numerator_uncancelled

-- Private odd-prime order and level separation for dyadic cyclotomic factors
#print axioms DyadicPrivateSupport.orderOf_eq_two_pow_succ
#print axioms DyadicPrivateSupport.oddPrime_divisor_has_private_order
#print axioms DyadicPrivateSupport.oddPrime_divisor_congruent_one
#print axioms DyadicPrivateSupport.oddPrime_divisor_private

-- Exact adjacent-smooth tangent and finite-residue identities
#print axioms CatalanTangentCore.first_tangent_defect_identity
#print axioms CatalanTangentCore.second_tangent_defect_identity
#print axioms CatalanTangentCore.balanceVector_parametrization
#print axioms CatalanTangentCore.tangentLattice_parametrization
#print axioms CatalanTangentCore.fourResidues_first_relation
#print axioms CatalanTangentCore.fourResidues_second_relation
#print axioms CatalanTangentCore.balancedResidual_cross_identity

-- Finite mixed-radix carry and cleaned-gap capture cores
#print axioms MixedRadixCarryFinite.lowerHorizontalDigit_lt
#print axioms MixedRadixCarryFinite.leftVerticalDigit_lt
#print axioms MixedRadixCarryFinite.upperHorizontalDigit_lt
#print axioms MixedRadixCarryFinite.rightVerticalDigit_lt
#print axioms MixedRadixCarryFinite.mixedRadixPlaquette
#print axioms CaptureMultiplier.capture_multiplier_iff_dvd

-- Exact binary-to-ternary radix-shadow congruence and valuation bridge
#print axioms RadixShadow.phi_injective
#print axioms RadixShadow.phi_modEq_pow_iff
#print axioms RadixShadow.three_pow_dvd_phi_sub_iff_two_pow_dvd_sub
#print axioms RadixShadow.padicValInt_phi_sub_eq

-- Finite borrow-block rigidity for binary/ternary digit differences
#print axioms BorrowBlockCore.shiftedCoefficient_eq_zero_of_lt
#print axioms BorrowBlockCore.borrowShift_eq_zero_iff
#print axioms BorrowBlockCore.digitPair_eq_zero_one_of_evaluation_lt
#print axioms BorrowBlockCore.leadingTwoEvaluation_not_lt

-- Zero-safe diagonal energy and total-variation comparison
#print axioms ValuationSlopeEnergy.sum_max_eq_one_add_totalVariation
#print axioms ValuationSlopeEnergy.four_mul_totalVariation_sq_div_one_add_le_diagonalEnergy
#print axioms ValuationSlopeEnergy.diagonalEnergy_le_two_mul_totalVariation
#print axioms ValuationSlopeEnergy.wedge_pos_of_opposite_signs
#print axioms ValuationSlopeEnergy.wedge_le_totalVariation_of_opposite_signs
#print axioms ValuationSlopeEnergy.totalVariation_and_diagonalEnergy_lower_of_wedge

-- Exact rank-K boundary displacement for rectangular evaluation matrices
#print axioms firstGridShiftMatrix_mul
#print axioms secondGridShiftMatrix_mul
#print axioms rank_firstGridBoundaryProjector
#print axioms rank_secondGridBoundaryProjector
#print axioms first_gridEvaluation_displacement
#print axioms second_gridEvaluation_displacement
#print axioms rank_first_gridEvaluation_matrix_displacement
#print axioms rank_second_gridEvaluation_matrix_displacement

-- Signed-progression geometric factorization and exact denominator tax
#print axioms det_geometricVandermondeMatrix_factored
#print axioms progressionDifference_coprime_left
#print axioms progressionInvariantQuotient_coprime_left
#print axioms progressionInvariantQuotient_coprime_right
#print axioms cast_progressionInvariantQuotient_eq_taxProduct
#print axioms progressionEtaWeight_eq_choose
#print axioms progressionBaseWeight_eq_choose
#print axioms log_progressionTaxProduct
#print axioms progressionTaxLog_eq_choose
#print axioms progressionLogRemainder_nonneg_le_choose
#print axioms progressionTaxLog_lower_bound
#print axioms log_cast_progressionInvariantQuotient_eq
#print axioms log_cast_progressionInvariantQuotient_lower_bound

-- Finite positive-kernel bridge and exact Fejer score identity
#print axioms normSq_geometricPhaseSum_eq_fejerFourierNumerator
#print axioms normalizedFejerKernel_nonneg
#print axioms normalizedFejerKernel_one
#print axioms exactPhaseHitCount_le_fejerScore
#print axioms fejerScore_eq_fourier
#print axioms fejerScore_eq_card_div_add_weightedFrequencies
#print axioms circlePhase_pow
#print axioms phaseExponentialSum_circlePhase
#print axioms circlePhase_eq_one_iff
#print axioms exactIntegerPhaseCount_le_fejerScore

-- Exact denominator drift and p-adic escape
#print axioms orbitDenominatorExponent_cast
#print axioms orbitDenominatorExponent_centered
#print axioms orbitDenominatorExponent_common_defect
#print axioms orbitDenominatorExponent_sub
#print axioms orbitDenominatorNat_tendsto_atTop
#print axioms padicNorm_normalizedRationalOrbit
#print axioms twoThree_padic_escape_of_normalized_outputs

-- Exact mechanical-word probability laws and covariance kernel
#print axioms floor_add_sub_floor_eq_carryBit
#print axioms sum_bit_eq_floor_difference
#print axioms sum_bit_eq_floor_add_carry
#print axioms sum_bit_two_values
#print axioms carryBit_sub_eq_coboundary
#print axioms prefixCount_mean
#print axioms prefixCount_variance
#print axioms jointCarrySet_eq_union
#print axioms jointCarrySet_measureReal
#print axioms jointCarry_integral
#print axioms carryCovariance_eq

-- Exact polynomial denominator clearing, finite-difference floor, and normalization tax
#print axioms pow_mul_denseIntegerPolynomialEval_div
#print axioms normalizedPolynomialResidual_clearing
#print axioms normalizedPolynomialResidual_eq_zero_of_abs_scaled_lt_one
#print axioms polynomialApproximationFloor_le_of_pointwise
#print axioms one_lt_normalizationTax_logThreeDivLogTwo
#print axioms normalized_mem_Ico_one_two_of_mem_dyadicBlock
#print axioms normalizationTax_obstruction

-- Exact rational enclosure for the consecutive logarithmic mean
#print axioms consecutiveLogMean_bounds

-- Exact carry/floor and denominator formal-series identities
#print axioms rotationCarry_eq_zero_or_one
#print axioms sum_rotationCarry
#print axioms X_mul_rotationCarrySeries
#print axioms one_sub_X_sq_mul_linearIndexSeries
#print axioms rotationDenominatorSeries_eq
#print axioms one_sub_X_sq_mul_denominator_defect
#print axioms rotationDenominatorSeries_sub

-- Strict one-gap dyadic--triadic amplification and its finite-product form
#print axioms strictMonoOn_unitRpowGap
#print axioms unitRpowGap_two_lt
#print axioms two_mul_rpow_lt_one_add_rpow_sub_one
#print axioms matched_one_gap_bound
#print axioms phi_gt_logb_three_two
#print axioms prod_matched_gap_bound
#print axioms prod_matched_one_gap_bound

-- Exact first Fermat-quotient determinant layer
#print axioms prime_dvd_pow_sub_one
#print axioms pow_eq_one_add_mul_fermatQuotientNat
#print axioms fermatQuotientResidue_pow
#print axioms firstLogDeterminant_eq_fermatQuotientDeterminant
#print axioms fermatQuotientDeterminant_two_three_powers

-- Exact finite compatibility and transverse-hyperplane counts
#print axioms KummerCompatibilityFinite.card_compatible
#print axioms KummerCompatibilityFinite.card_transverse_compatible
#print axioms KummerCompatibilityFinite.card_compatible_zmod
#print axioms KummerCompatibilityFinite.card_transverse_compatible_zmod

-- Exact prime-power Kummer coherence counts over ZMod(q^e)
#print axioms PrimePowerKummerCoherence.scalarCompatibleEquiv
#print axioms PrimePowerKummerCoherence.card_compatible_shell_sum
#print axioms PrimePowerKummerCoherence.card_scalarCompatible_primePower
#print axioms PrimePowerKummerCoherence.card_dominantBase_shell_sum
#print axioms PrimePowerKummerCoherence.coefficientEquiv
#print axioms PrimePowerKummerCoherence.card_transverseNormalForm_primePower

-- Exact coefficient content of the primitive two-star determinant
#print axioms formalPrimeDeterminant_content_eq_simultaneousCoordinateGCD
#print axioms IsLeastTwoBaseNonintegerSolution.formalPrimeDeterminant_content_eq_one
#print axioms map_ne_zero_of_integerCoefficientContent_eq_one
#print axioms IsLeastTwoBaseNonintegerSolution.formalPrimeDeterminant_map_ne_zero

-- Reciprocal coefficient symmetry and its exact half-contact ceiling
#print axioms ReciprocalHalfContact.reverseIndex_reverseIndex
#print axioms ReciprocalHalfContact.two_mul_contact_le_degree
#print axioms ReciprocalHalfContact.two_mul_contact_eq_degree_iff_single_middle
#print axioms ReciprocalHalfContact.even_degree_of_sharp_contact
#print axioms ReciprocalHalfContact.coeff_eq_two_middle_of_odd_floor_contact

-- One-Vandermonde reciprocal-moment clearing and integral Hankel lattice floor
#print axioms ReciprocalMomentLatticeFinite.cofactorWeight_mul_signedDenominator
#print axioms ReciprocalMomentLatticeFinite.cast_clearedMoment_eq_delta_mul_rationalBarycentricMoment
#print axioms ReciprocalMomentLatticeFinite.denominatorLCM_dvd_vandermondeDelta
#print axioms ReciprocalMomentLatticeFinite.nodeCofactorContent_mul_lcmClearedMoment
#print axioms ReciprocalMomentLatticeFinite.nodeCofactorContent_dvd_clearedMoment
#print axioms ReciprocalMomentLatticeFinite.quadraticValue_eq_doubleSum
#print axioms ReciprocalMomentLatticeFinite.commonDivisor_dvd_quadraticValue
#print axioms ReciprocalMomentLatticeFinite.commonDivisor_pow_dvd_momentHankel_det
#print axioms ReciprocalMomentLatticeFinite.commonDivisor_le_quadraticValue
#print axioms ReciprocalMomentLatticeFinite.nodeCofactorContent_le_quadraticValue
#print axioms ReciprocalMomentLatticeFinite.one_le_quadraticValue
#print axioms ReciprocalMomentLatticeFinite.one_le_momentHankel_det
#print axioms ReciprocalMomentLatticeFinite.commonDivisor_pow_le_momentHankel_det
#print axioms ReciprocalMomentLatticeFinite.one_div_clearedMoment_zero_le_normalizedQuadraticValue
#print axioms ReciprocalMomentLatticeFinite.commonDivisor_div_clearedMoment_zero_le_normalizedQuadraticValue
#print axioms ReciprocalMomentLatticeFinite.nodeCofactorContent_div_clearedMoment_zero_le_normalizedQuadraticValue

#print axioms CenteredTrace.homGeomSum_sub_eq_defectSum
#print axioms CenteredTrace.sq_sub_dvd_homGeomSum_sub
#print axioms CenteredTrace.three_dvd_cubicNumerator_iff
#print axioms CenteredTrace.prime_dvd_cubic_gcd
#print axioms CenteredTrace.padicValInt_sq_div_three
#print axioms CenteredTrace.eq_five_of_dvd_both_channels
#print axioms CenteredTrace.fifth_trace_two_channel
#print axioms PrimeTopIsolation.orderOf_eq_two_mul_of_dvd_homCyclotomic
#print axioms PrimeTopIsolation.two_mul_dvd_sub_one_of_dvd_homCyclotomic
#print axioms PrimeTopIsolation.not_dvd_pow_sub_pow_of_lt
#print axioms PrimeTopIsolation.padicValRat_sum_eq_top
#print axioms PrimeTopIsolation.coefficient_tax
#print axioms ExponentLatticeMask.gap_pow_dvd_clearedEval
#print axioms ExponentLatticeMask.abs_clearedEval_ge
#print axioms ExponentLatticeMask.transport_zpow
#print axioms ExponentLatticeMask.det_eq_zero_of_orthogonal
#print axioms FactorialCocycle.log_two_div_log_three_gt_half
#print axioms FactorialCocycle.log_two_div_log_three_lt_two_thirds
#print axioms FactorialCocycle.pair_mode_gt_one
#print axioms FactorialCocycle.triple_mode_lt_one
#print axioms FactorialCocycle.shiftEval_mul_geom
#print axioms FactorialCocycle.annihilator_kills_growing_modes
#print axioms FactorialCocycle.padicValNat_choose_le_of_pow_dvd
#print axioms external_derivative_ne_zero
#print axioms abs_external_derivative_ge
#print axioms alaogluErdosConjecture_of_sparseCoactionSeparation
#print axioms sparseCoactionSeparation_iff_alaogluErdosConjecture
#print axioms RestrictedDirichlet.covolume_conservation
#print axioms TerminalFactorial.padicValNat_termFall_eq_one
#print axioms TerminalFactorial.not_dvd_termFall_of_lt
#print axioms TerminalFactorial.termFall_multiplicative_independent
#print axioms RationalHankel.exists_common_base_of_recurrences
#print axioms RationalHankel.sq_eq_mul_parametrization
#print axioms RationalHankel.hankel_ray
#print axioms RationalHankel.coeff_identities_of_transcendental
#print axioms SmoothSemigroup.modulus_lt_of_card_image_lt
#print axioms SmoothSemigroup.smooth_box_cutoff
#print axioms SmoothSemigroup.consecutive_threeSmooth_triples
#print axioms SmoothSemigroup.pow_two_eq_pow_three_add_one
#print axioms SmoothSemigroup.pow_three_eq_pow_two_add_one
#print axioms SmoothSemigroup.consecutive_threeSmooth_pairs
#print axioms NewtonWall.eq_one_of_tendsto_pow
#print axioms NewtonWall.edge_spectrum
#print axioms NewtonWall.eq_zero_of_edge_law
#print axioms NewtonWall.edge_pairs_empty_spectrum
#print axioms NewtonWall.no_formal_edge_realization
#print axioms CriticalWindow.mass_balance
#print axioms CriticalWindow.contraction_mul
#print axioms CriticalWindow.kappa_mul_lt
#print axioms CriticalWindow.no_balanced_transport
#print axioms CriticalWindow.exponent_gap_dvd
#print axioms CompactChart.area_eq_div
#print axioms CompactChart.abs_area_ge
#print axioms CompactChart.coord_diff
#print axioms CompactChart.codimension_lock
#print axioms ToricRigidity.eigenvalue_eq_of_ne_zero
#print axioms ToricRigidity.toric_eigen_support_unique
#print axioms integer_of_two_three_rpow_integer_of_two_rpow_lt_8192
#print axioms thirteen_le_of_not_integer_of_two_three_rpow_integer
#print axioms integer_of_two_three_rpow_integer_of_two_rpow_lt_16384
#print axioms fourteen_le_of_not_integer_of_two_three_rpow_integer

end LeanProofs.TwoBaseIntegerExponent
