import ExponentialIdentities.TwoBaseIntegerExponent.CandidateLattice
import ExponentialIdentities.TwoBaseIntegerExponent.KernelDichotomy
import ExponentialIdentities.TwoBaseIntegerExponent.SecondIterateKernel
import ExponentialIdentities.TwoBaseIntegerExponent.TowerRigidity
import ExponentialIdentities.TwoBaseIntegerExponent.SymmetricTowerConstants
import ExponentialIdentities.TwoBaseIntegerExponent.PrimeLogSpaceOperator
import ExponentialIdentities.TwoBaseIntegerExponent.ArbitraryNodeRepulsion
import ExponentialIdentities.TwoBaseIntegerExponent.SuperfactorialDeterminant
import ExponentialIdentities.TwoBaseIntegerExponent.SemigroupGapBound
import ExponentialIdentities.TwoBaseIntegerExponent.OrderedChamberPositivity
import ExponentialIdentities.TwoBaseIntegerExponent.ExternalRankClassification
import ExponentialIdentities.TwoBaseIntegerExponent.PerfectPowerContent
import ExponentialIdentities.TwoBaseIntegerExponent.RootSaturation
import ExponentialIdentities.TwoBaseIntegerExponent.ValuationLattice
import ExponentialIdentities.TwoBaseIntegerExponent.RationalFunctionRigidity
import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicTowerTransition
import ExponentialIdentities.TwoBaseIntegerExponent.CrossBaseTowerTransition
import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicExponentLocus
import ExponentialIdentities.TwoBaseIntegerExponent.AlgebraicOutputLocus
import ExponentialIdentities.TwoBaseIntegerExponent.CanonicalRadicalMixedOutput
import ExponentialIdentities.TwoBaseIntegerExponent.SimultaneousRadicalDegrees
import ExponentialIdentities.TwoBaseIntegerExponent.RationalFunctionAlgebraicLocus
import ExponentialIdentities.TwoBaseIntegerExponent.MinPlusCeiling
import ExponentialIdentities.TwoBaseIntegerExponent.TropicalInitialForm
import ExponentialIdentities.TwoBaseIntegerExponent.BlockFiberFactorization
import ExponentialIdentities.TwoBaseIntegerExponent.BlockVandermondeValuationBudget
import ExponentialIdentities.TwoBaseIntegerExponent.AllLayerUnitBasis
import ExponentialIdentities.TwoBaseIntegerExponent.UnitOrderingGain
import ExponentialIdentities.TwoBaseIntegerExponent.TropicalBlockApplication
import ExponentialIdentities.TwoBaseIntegerExponent.BeattyTropicalFiber
import ExponentialIdentities.TwoBaseIntegerExponent.RowBlockLaplaceExpansion
import ExponentialIdentities.TwoBaseIntegerExponent.AssignmentExcessGeometry
import ExponentialIdentities.TwoBaseIntegerExponent.RowBlockUnitDivisibility
import ExponentialIdentities.TwoBaseIntegerExponent.MixedDeterminantUnitBridge
import ExponentialIdentities.TwoBaseIntegerExponent.ComplexSolutions
import ExponentialIdentities.TwoBaseIntegerExponent.SparsePowerCurve
import ExponentialIdentities.TwoBaseIntegerExponent.RationalOrbitGrid
import ExponentialIdentities.TwoBaseIntegerExponent.RestrictedMatrixCoefficient
import ExponentialIdentities.TwoBaseIntegerExponent.FormalPrimeDeterminant
import ExponentialIdentities.TwoBaseIntegerExponent.BoundaryDilationDefect
import ExponentialIdentities.TwoBaseIntegerExponent.FejerKernelCertificate
import ExponentialIdentities.TwoBaseIntegerExponent.SignedProgressionDeterminant

/-!
# Assumption audit for the newly formalized modules

Each `#print axioms` below must report only the three standard Lean foundations
`propext`, `Classical.choice`, `Quot.sound`.  Anything else — in particular
`sorryAx` — is a trust breach and must fail review.

The two explicit analytic inputs of this round, `RpowDividedDifferenceMeanValue`
and `NewtonFactorization`, are *hypotheses of theorems*, not axioms, so they do
not and cannot appear here; they are visible instead in the statements of
`le_vandermondeProduct_of_dividedDiffMeanValue`, `packing_of_dividedDiffMeanValue`
and `card_le_ten_thousand_log_sq`.
-/

namespace LeanProofs.TwoBaseIntegerExponent

-- Candidate lattice
#print axioms twoBaseNaturalCandidate_gcd
#print axioms twoBaseNaturalCandidate_lcm
#print axioms exists_fixed_odd_core_of_not_alaogluErdosConjecture

-- Kernel dichotomy
#print axioms multiplicativelyDependentOutputs_iff_secondIterateKernelRelation
#print axioms twoBaseNonintegerSolution_kernel_dichotomy

-- Second-iterate kernel
#print axioms kernelPairs_det_eq_zero
#print axioms kernelPairs_prop_dim
#print axioms saturatedKernel_invariant

-- Tower rigidity
#print axioms alaogluErdosConjecture_iff_two_rpow_square_cube_isAlgebraic
#print axioms TwoBaseNonintegerSolution.base_two_tower_dichotomy

-- Symmetric tower constants
#print axioms TwoBaseNonintegerSolution.hasPositiveRationalPower_symmetricTowerThree
#print axioms TwoBaseNonintegerSolution.hasPositiveRationalPower_symmetricTowerTwo

-- Prime-log-space operator
#print axioms primeLogSpanThetaPullbackRankOne_iff_rationalOutput
#print axioms alaogluErdosConjecture_of_primeLogSpanThetaPullbackRankOne

-- Arbitrary-node repulsion
#print axioms det_nodeMatrix_eq_vandermondeProduct_mul_dividedDiff
#print axioms le_vandermondeProduct_of_dividedDiffMeanValue
#print axioms packing_of_dividedDiffMeanValue

-- Universal superfactorial content and strengthened arbitrary-node repulsion
#print axioms interpolationSuperfactorial_dvd_nodeIntMatrix_det
#print axioms det_nodeIntMatrix_consecutive_lastOrdinate
#print axioms interpolationSuperfactorial_le_abs_det_nodeMatrix
#print axioms interpolationSuperfactorial_mul_inv_le_vandermondeProduct_of_dividedDifference
#print axioms superfactorial_mul_le_vandermondeProduct_of_dividedDiffMeanValue
#print axioms superfactorial_packing_of_dividedDiffMeanValue

-- Semigroup gap bound
#print axioms abs_det_le_of_abs_entry_le
#print axioms det_semigroupMatrix_ne_zero
#print axioms card_le_ten_thousand_log_sq

-- Ordered-chamber positivity
#print axioms det_rpowVandermonde_pos
#print axioms det_semigroupMatrix_pos
#print axioms one_le_det_semigroupMatrix_of_strictMono

-- External-rank classification
#print axioms existsUnique_hasExternalRankType
#print axioms TwoBaseNonintegerSolution.externalRankClassification
#print axioms hasExternalRankType_independent_iff_not_multiplicativelyDependentOutputs

-- Perfect-power content
#print axioms isCommonOutputPower_iff_twoBaseIntegralSolution_div

-- Root saturation
#print axioms exists_canonicalConeData_of_not_alaogluErdosConjecture

-- Valuation lattice
#print axioms finite_quotient_ratOutputLattice
#print axioms closure_quotient_pair_eq_top

-- Rational-function rigidity
#print axioms twoBaseIntegralSolution_mul_iff
#print axioms alaogluErdosConjecture_iff_solutions_closed_under_mul
#print axioms alaogluErdosConjecture_iff_solutions_closed_under_sq
#print axioms rationalFunction_rigidity_at_generator

-- Algebraic exponent/output loci and simultaneous radicals
#print axioms hasPositiveTwoThreeUnitPower_two_rpow_iff_affine_logRatio
#print axioms TwoBaseNonintegerSolution.twoRpowAlgebraicTransition_iff_affine_logRatio
#print axioms TwoBaseNonintegerSolution.not_two_distinct_algebraic_tower_transitions
#print axioms TwoBaseNonintegerSolution.card_algebraicTowerTransitionDepths_le_one
#print axioms alaogluErdosConjecture_iff_two_distinct_tower_transitions_algebraic
#print axioms TwoBaseNonintegerSolution.threeRpowAlgebraicTransition_iff_scaled_affine_logRatio
#print axioms TwoBaseNonintegerSolution.not_baseTwo_and_baseThree_tower_transitions
#print axioms TwoBaseNonintegerSolution.not_two_distinct_baseThree_tower_transitions
#print axioms TwoBaseNonintegerSolution.eq_of_twoOrThree_tower_transitions
#print axioms TwoBaseNonintegerSolution.not_higher_unitDirectionTowerTransition_of_depth_one
#print axioms TwoBaseNonintegerSolution.not_higher_unitDirectionTowerTransition_of_kernelRelation
#print axioms TwoBaseNonintegerSolution.not_higher_unitDirectionTowerTransition_of_dependentOutputs
#print axioms TwoBaseNonintegerSolution.twoThreeRpowAlgebraic_iff_affine
#print axioms TwoBaseNonintegerSolution.algebraic_two_three_squared_monomial_locus_trichotomy
#print axioms alaogluErdosConjecture_iff_no_squaredTwoThreeMonomial_coordinateFace
#print axioms TwoBaseNonintegerSolution.transcendental_mixed_canonical_radical_output
#print axioms TwoBaseNonintegerSolution.algebraic_mixed_canonical_radical_output_imp_coordinate_face
#print axioms threeFreeCoreRpow_exact_radical_degree_of_simultaneous_normalization
#print axioms mixed_coreRpow_exact_radical_degree_of_zero_baseDepths

-- Rational-function algebraic-output detectors
#print axioms TwoBaseNonintegerSolution.twoThreeRpowAlgebraic_rationalFunction_iff
#print axioms twoThreeRpowAlgebraic_rationalFunction_iff_integer_or_affine
#print axioms alaogluErdosConjecture_iff_twoThreeRpowAlgebraic_rationalFunction
#print axioms twoThreeRpowAlgebraic_polynomial_iff_integer_of_two_le_natDegree
#print axioms alaogluErdosConjecture_iff_twoThreeRpowAlgebraic_polynomial_of_two_le_natDegree
#print axioms exists_generator_with_exact_rationalFunction_algebraic_and_integral_loci

-- Min-plus ceiling
#print axioms minPlusContent_le_of_le
#print axioms minPlusContent_le_of_natAbs_le
#print axioms primeContent_le_log
#print axioms det_dvd_and_not_dvd_of_unique_min

-- Tied tropical initial forms
#print axioms det_pow_add_dvd_iff_signedLeibnizQuotientSum_dvd
#print axioms det_pow_succ_dvd_iff_signedLeibnizQuotientSum_eq_zero
#print axioms det_pow_succ_dvd_iff_tiedFiberSum_eq_zero
#print axioms det_pow_succ_dvd_iff_initialFiberSum_eq_zero

-- Tied-fiber block and Vandermonde factorizations
#print axioms sum_blockPreserving_eq_prod_blockDet
#print axioms sum_basePerm_mul_blockPreserving_eq_sign_mul_prod_blockDet
#print axioms sum_blockPreserving_eq_prod_vandermonde_of_reindex
#print axioms sum_blockPreserving_consecutivePowers_eq_prod_vandermonde
#print axioms det_pow_succ_dvd_iff_prod_blockDet_eq_zero
#print axioms det_pow_succ_dvd_iff_prod_vandermonde_eq_zero

-- Exact collision energy and elementary finite block-valuation budgets
#print axioms padicValNat_natVandermondeProduct_eq_sum_collisionCount
#print axioms padicValNat_natAbs_pow_sub_pow_le
#print axioms padicValNat_blockVandermondeNatProduct
#print axioms padicValNat_blockVandermondeNatProduct_le_cubeBudget
#print axioms padicValNat_blockVandermondeNatProduct_le_powDifferenceCubeBudget

-- Cascade-independent all-layer divisibility from unit-adapted monic bases
#print axioms prod_columnDivisor_dvd_det
#print axioms pow_sum_columnWeight_dvd_det
#print axioms pow_sum_columnWeight_dvd_det_of_unimodular_mul
#print axioms pow_sum_dvd_det_vandermonde_of_monicBasis
#print axioms two_pow_sum_degree_dvd_det_vandermonde_of_odd
#print axioms three_pow_sum_halfDegree_dvd_det_vandermonde_of_unit
#print axioms two_pow_sum_degree_add_factorialVal_dvd_det_vandermonde
#print axioms three_pow_sum_halfDegree_add_factorialVal_dvd_det_vandermonde

-- Exact block sums and finite cubic bounds for the unit-ordering gains
#print axioms twoUnitOrderingWeight_eq_two_mul_sub_digitSum
#print axioms two_mul_threeUnitOrderingWeight_eq_three_mul_sub_digitSum
#print axioms twoUnitBlockGain_eq
#print axioms threeUnitBlockGain_eq
#print axioms twoUnitBlockGain_le_square
#print axioms two_mul_threeUnitBlockGain_le_square
#print axioms sum_twoUnitBlockGain_le_cube
#print axioms two_mul_sum_threeUnitBlockGain_le_cube

-- Concrete Beatty minimizing fiber, gap, and determinant expansion
#print axioms rankOneAssignmentCost_eq_iff_blockPreserving
#print axioms beattyAssignmentCost_eq_iff_blockPreserving
#print axioms beattyAssignmentCost_add_floor_le_of_not_blockPreserving
#print axioms beattyPower_pow_floor_dvd_quotient_of_not_blockPreserving
#print axioms det_beattyPowerMatrix_pow_succ_dvd_iff_prod_blockDet_eq_zero
#print axioms det_beattyPowerMatrix_eq_pow_mul_blockDet_add_pow_floor_mul

-- Exact all-layer grouping by ordered row partitions
#print axioms sum_permutationRowBlockAssignmentFiber_eq_sign_mul_prod_blockDet
#print axioms det_eq_sum_rowBlockAssignment_minorProducts
#print axioms det_rankOnePowerMatrix_eq_sum_rowBlockAssignment_minorProducts
#print axioms det_rankOnePowerMatrix_eq_minPow_mul_sum_assignmentExcess
#print axioms det_rankOnePowerMatrix_eq_minPow_mul_truncatedAssignmentSum
#print axioms beattyRowBlockAssignment_excess_ge_floor

-- Prefix-crossing geometry and finite cascade-support counts
#print axioms finPrefixSum_canonical_le_assignment
#print axioms rowBlockCrossingEnergy_eq_reverseFinRank_excess
#print axioms rankOneAssignmentCost_add_mul_reverseExcess_le_of_gapDecomposition
#print axioms beattyFloor_mul_rowBlockCrossingEnergy_le_excess
#print axioms card_rowBlockAssignment_crossingEnergy_lt_choose
#print axioms card_rowBlockAssignment_excess_lt_choose_of_crossing_lower_bound
#print axioms card_beattyRowBlockAssignment_excess_lt
#print axioms rowBlockPrefixSurplus_last_eq_zero
#print axioms card_rowBlockAssignment_crossingEnergy_lt_choose_of_pos
#print axioms card_rowBlockAssignment_excess_lt_choose_of_crossing_lower_bound_of_pos
#print axioms card_beattyRowBlockAssignment_excess_lt_of_pos

-- Uniform unit-ordering divisors throughout the row-assignment cascade
#print axioms rowBlockOrderingExponent_two_eq_sum_blockGain
#print axioms rowBlockOrderingExponent_three_eq_sum_blockGain
#print axioms det_fiberMonicBasisChange_eq_one
#print axioms pow_dvd_weighted_rowBlockAssignmentSum
#print axioms fiberScaledConsecutivePowerMatrix_mul_fiberMonicBasisChange
#print axioms two_pow_rowBlockOrderingExponent_dvd_minorProduct_fiberScaledConsecutivePowers
#print axioms three_pow_rowBlockOrderingExponent_dvd_minorProduct_fiberScaledConsecutivePowers
#print axioms pow_sum_dvd_det_fiberScaledConsecutivePowerMatrix_of_monicBasis
#print axioms two_pow_rowBlockOrderingExponent_dvd_det_fiberScaledConsecutivePowers
#print axioms three_pow_rowBlockOrderingExponent_dvd_det_fiberScaledConsecutivePowers
#print axioms pow_minCost_add_commonMinorExponent_dvd_det_rankOnePowerMatrix
#print axioms two_pow_minCost_add_rowBlockOrderingExponent_dvd_det_rankOnePowerMatrix
#print axioms three_pow_minCost_add_rowBlockOrderingExponent_dvd_det_rankOnePowerMatrix

-- Bridge from mixed integer matrices to the row-block unit divisors
#print axioms sortedMixedExponentBoxPair_weight_strictMono
#print axioms sortedMixedExponentBoxPrefix_weight_strictMono
#print axioms submatrix_mixedIntegerPowerMatrix_eq_two_rankOnePowerMatrix
#print axioms submatrix_mixedIntegerPowerMatrix_eq_three_rankOnePowerMatrix
#print axioms dvd_det_of_dvd_det_columnPermute
#print axioms two_pow_minCost_add_rowBlockOrderingExponent_dvd_det_mixedIntegerPowerMatrix
#print axioms three_pow_minCost_add_rowBlockOrderingExponent_dvd_det_mixedIntegerPowerMatrix

-- Complex exponents
#print axioms im_eq_zero_of_complexTwoBaseIntegralSolution
#print axioms twoBaseIntegralSolution_re_of_complex

-- Restricted matrix-coefficient reformulation
#print axioms restrictedLogDet_eq_zero_iff_exists_commonExponent
#print axioms restrictedLogMatrix_eq_rankOne
#print axioms restrictedMatrixCoefficient_ne_zero_of_not_integer
#print axioms alaogluErdosConjecture_iff_restrictedMatrixCoefficientPrinciple

-- Formal prime-symbol determinant and sparse Structural Rank reformulation
#print axioms primeFactorLinearForm_eval₂_log
#print axioms formalPrimeDeterminant_eval₂_log
#print axioms formalPrimeDeterminant_eq_zero_iff
#print axioms alaogluErdosConjecture_iff_sparsePrimeLogStructuralRankPrinciple

-- Exact sparse interpolation on irrational power curves
#print axioms powerCurveFrequency_injective
#print axioms sparsePowerCurve_coeff_eq_zero_of_zeros
#print axioms card_le_of_sparsePowerCurve_eq_zero
#print axioms det_sparsePowerCurveMatrix_ne_zero
#print axioms det_natPowerCurveEvaluationMatrix_ne_zero
#print axioms positiveNodeInterpolant_support_card
#print axioms positiveNodeInterpolant_eval

-- Exact rational-grid collisions and the sharp one-monomial certificate
#print axioms newRowWeight_mem_previous_iff
#print axioms card_previous_inter_newRow
#print axioms card_rationalOrbitWeights
#print axioms card_irrationalOrbitParameters
#print axioms squareGrid_le_of_sparsePowerCurve_eq_zero
#print axioms rationalOrbitNodePolynomial_support_card
#print axioms rationalOrbitNodePolynomial_support_card_eq
#print axioms rationalOrbitNodePolynomial_eval_eq_zero
#print axioms exists_rational_squareGrid_certificate

-- Rectangular interpolation-grid boundary compression
#print axioms rectangularNodePolynomial_dilate_vertical
#print axioms rectangularNodePolynomial_dilate_horizontal
#print axioms rectangularNodePolynomial_dvd_horizontalDefect
#print axioms rectangularNodePolynomial_dvd_verticalDefect
#print axioms existsUnique_squareGridResiduals
#print axioms squareBoundaryExpressions_natDegree_le
#print axioms boundaryDilation_commutator

-- Signed-progression geometric factorization and exact denominator tax
#print axioms det_geometricVandermondeMatrix_factored
#print axioms progressionDifference_coprime_left
#print axioms progressionInvariantQuotient_coprime_left
#print axioms progressionInvariantQuotient_coprime_right
#print axioms cast_progressionInvariantQuotient_eq_taxProduct
#print axioms progressionEtaWeight_eq_choose
#print axioms progressionBaseWeight_eq_choose
#print axioms log_progressionTaxProduct
#print axioms progressionTaxLog_eq_choose
#print axioms progressionLogRemainder_nonneg_le_choose
#print axioms progressionTaxLog_lower_bound
#print axioms log_cast_progressionInvariantQuotient_eq
#print axioms log_cast_progressionInvariantQuotient_lower_bound

-- Finite positive-kernel bridge and exact Fejer score identity
#print axioms normSq_geometricPhaseSum_eq_fejerFourierNumerator
#print axioms normalizedFejerKernel_nonneg
#print axioms normalizedFejerKernel_one
#print axioms exactPhaseHitCount_le_fejerScore
#print axioms fejerScore_eq_fourier
#print axioms fejerScore_eq_card_div_add_weightedFrequencies
#print axioms circlePhase_pow
#print axioms phaseExponentialSum_circlePhase
#print axioms circlePhase_eq_one_iff
#print axioms exactIntegerPhaseCount_le_fejerScore

end LeanProofs.TwoBaseIntegerExponent
