import ExponentialIdentities.TwoBaseIntegerExponent.SecondIterateKernel
import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.NumberTheory.Padics.PadicVal.Basic
import Mathlib.SetTheory.Cardinal.Finite

/-!
# The rational-output lattice of an output pair

This file formalizes the arithmetic content of the section *Rational and integral outputs
inside the spectrum* of the unified Alaoglu--Erdős report: the rational-output lattice
`Λ_x` attached to a hypothetical nonintegral solution `x` with integral outputs
`M = 2 ^ x` and `A = 3 ^ x`.

## The report's object

The report forms the prime-valuation matrix `V_x = (𝐦 𝐚) ∈ M_{P×2}(ℤ)`, whose rows are
indexed by the union `P` of the prime supports of `M` and `A`, and sets
\[
  Λ_x=\{q∈ℚ^2 : V_xq∈ℤ^{P}\},
\]
so that for `q = (r, s)` the auxiliary base `α(q) = 2^r 3^s` has `α(q)^x = M^r A^s ∈ ℚ_{>0}`
exactly when `q ∈ Λ_x`.  The report then proves `ℤ² ⊆ Λ_x` with finite index and classifies
the quotient by Smith normal form.

## What is carried here, and why

Two adjustments make the object available to a machine-checked development without building
`V_x` and unique factorization of rational-exponent products.

*The prime matrix is bypassed.*  Membership `V_x q ∈ ℤ^P` is replaced by its meaning,
`M ^ r * A ^ s ∈ ℚ_{>0}`.  That equivalence is the report's Proposition *Exact rational and
integral auxiliary-output spectrum*; it is the one place where `V_x` is genuinely used, and it
is **not** proved here (see the honesty note below).

*Rational exponents are cleared.*  A rational pair `q = (a/N, b/N)` is carried by its
numerator pair `(a, b) : ℤ × ℤ` together with the fixed denominator `N`.  Under this
identification `M ^ (a/N) * A ^ (b/N)` is rational exactly when some positive rational `q`
satisfies `q ^ N = M ^ a * A ^ b`, and that is the definition of `ratOutputPairs M A N` below.
The scaling is not cosmetic: at `N = 1` the lattice is all of `ℤ × ℤ`
(`ratOutputPairs_one`), which is precisely the report's containment `ℤ² ⊆ Λ_x`, so every
non-trivial phenomenon lives in the denominators.

Under the same scaling the report's copy of `ℤ²` inside `Λ_x` becomes `twoThreeUnitPairs N`,
the pairs both of whose coordinates are divisible by `N`, and the report's defect group
`Λ_x/ℤ²` becomes `ratOutputDefect`, the image of the lattice in `(ℤ × ℤ) ⧸ twoThreeUnitPairs N`.

## Relation to `SecondIterateKernel`

This lattice is **not** the kernel of `SecondIterateKernel`, and the two must not be conflated.
`kernelPairs M A` asks that `M ^ a * A ^ b` lie in the divisible `2,3`-hull `Γ^{sat}`, whereas
`ratOutputPairs` asks that a root of `M ^ a * A ^ b` be *rational*.  At integral exponents the
two conditions are genuinely different: `ratOutputPairs M A 1 = Set.univ` while `kernelPairs`
is generally a proper subgroup of rank at most one.  The kernel is a statement about the
outer, solution-independent spectrum; the lattice is a statement about the inner, per-solution
rational locus.

## Results

* `ratOutputLattice` --- the lattice as an `AddSubgroup (ℤ × ℤ)`.
* `ratOutputPairs_one` and `twoThreeUnitPairs_le_ratOutputLattice` --- the report's
  containment `ℤ² ⊆ Λ_x`, unscaled and scaled.
* `finite_quotient_of_twoThreeUnitPairs_le`, `card_quotient_le_of_twoThreeUnitPairs_le` --- the
  finite-index statement, with the explicit bound `N ^ 2` on the order of the quotient.
* `closure_quotient_pair_eq_top` --- every such quotient is generated by the images of
  `(1, 0)` and `(0, 1)`; it is a quotient of `ℤ × ℤ`, so at most two generators suffice.
* `rat_root_iff_mem_ratOutputPairs` and `two_three_rpow_output_rat_iff` --- the bridge from the
  lattice to the analytic object: for `α > 0` with `α ^ N = 2 ^ a * 3 ^ b`, the output `α ^ x`
  is rational exactly when `(a, b)` lies in the lattice of the output pair of `x`.
* `ratOutputPairs_inter_translate` and `two_three_rpow_rat_at_consecutive_iff` --- the report's
  Proposition *Translation intersection*, `Λ_x ∩ Λ_{x+1} = ℤ²`, in scaled form: a base whose
  outputs at two consecutive solutions are both rational is a rational `2,3`-unit.
* `HasSmithClassification` --- the Smith classification as an explicit predicate, with the
  consequences the report draws from it (`HasSmithClassification.card`,
  `HasSmithClassification.card_eq_one_iff`, `ratOutputDefect_eq_bot_of_smith_one`).

## Honesty note

Two ingredients of the report's section are **not** proved here and are not assumed silently.

1. The identification of `Λ_x` with `{q : V_x q ∈ ℤ^P}` --- equivalently, that a positive
   rational-exponent monomial in the primes is rational only when all exponents are integers.
   The definition used here is the *meaning* of that condition, so nothing is lost downstream;
   what is missing is the prime-matrix picture, hence also the determinantal divisors
   `δ₁(V_x)`, `δ₂(V_x)`.
2. The existence of the Smith normal form itself.  `HasSmithClassification` is a hypothesis,
   never discharged in this file.  Everything stated about invariant factors is conditional on
   it, and the report's `|Λ_x/ℤ²| = δ₂(V_x)` is therefore available here only as
   `HasSmithClassification.card`.

The integral spectrum `Λ_x^{+}` and its Gordan finiteness are not touched at all.
-/

namespace LeanProofs.TwoBaseIntegerExponent

open Set

/-! ### The lattice and its group structure -/

/-- The **rational-output lattice** of the output pair `(M, A)` at denominator `N`.

A pair `(a, b)` belongs to it when the auxiliary base `2 ^ (a/N) * 3 ^ (b/N)` has a rational
output, that is, when some positive rational `q` satisfies `q ^ N = M ^ a * A ^ b`.  This is
the report's `Λ_x` in `N`-scaled integral coordinates. -/
def ratOutputPairs (M A N : ℕ) : Set (ℤ × ℤ) :=
  {p | ∃ q : ℚ, 0 < q ∧ (q : ℝ) ^ N = (M : ℝ) ^ p.1 * (A : ℝ) ^ p.2}

/-- Unfolded membership in the rational-output lattice. -/
theorem mem_ratOutputPairs_iff {M A N : ℕ} {a b : ℤ} :
    (a, b) ∈ ratOutputPairs M A N ↔
      ∃ q : ℚ, 0 < q ∧ (q : ℝ) ^ N = (M : ℝ) ^ a * (A : ℝ) ^ b :=
  Iff.rfl

/-- The defining relation of the lattice, transported to `ℚ`.  Both sides are equalities
between rational numbers, so nothing is lost by descending. -/
theorem mem_ratOutputPairs_iff_rat {M A N : ℕ} {a b : ℤ} :
    (a, b) ∈ ratOutputPairs M A N ↔
      ∃ q : ℚ, 0 < q ∧ q ^ N = (M : ℚ) ^ a * (A : ℚ) ^ b := by
  rw [mem_ratOutputPairs_iff]
  refine exists_congr fun q => and_congr_right fun _ => ?_
  constructor
  · intro h
    have hcast : ((q ^ N : ℚ) : ℝ) = ((((M : ℚ) ^ a * (A : ℚ) ^ b) : ℚ) : ℝ) := by
      push_cast
      exact h
    exact_mod_cast hcast
  · intro h
    have hcast := congrArg (fun t : ℚ => (t : ℝ)) h
    push_cast at hcast
    exact hcast

/-- A natural power of a two-factor integral-exponent monomial. -/
private theorem zpow_mul_pow (y z : ℝ) (u v : ℤ) (N : ℕ) :
    (y ^ u * z ^ v) ^ N = y ^ ((N : ℤ) * u) * z ^ ((N : ℤ) * v) := by
  rw [mul_pow, ← zpow_natCast (y ^ u) N, ← zpow_natCast (z ^ v) N, ← zpow_mul, ← zpow_mul,
    mul_comm u (N : ℤ), mul_comm v (N : ℤ)]

/-- The zero vector lies in the lattice. -/
theorem zero_mem_ratOutputPairs (M A N : ℕ) : ((0 : ℤ), (0 : ℤ)) ∈ ratOutputPairs M A N :=
  mem_ratOutputPairs_iff.mpr ⟨1, one_pos, by simp⟩

/-- The lattice is closed under negation. -/
theorem neg_mem_ratOutputPairs {M A N : ℕ} {a b : ℤ} (h : (a, b) ∈ ratOutputPairs M A N) :
    (-a, -b) ∈ ratOutputPairs M A N := by
  obtain ⟨q, hqpos, hq⟩ := mem_ratOutputPairs_iff.mp h
  refine mem_ratOutputPairs_iff.mpr ⟨q⁻¹, inv_pos.mpr hqpos, ?_⟩
  rw [Rat.cast_inv, inv_pow, hq, zpow_neg, zpow_neg, mul_inv]

/-- The lattice is closed under addition. -/
theorem add_mem_ratOutputPairs {M A N : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) {a b a' b' : ℤ}
    (h : (a, b) ∈ ratOutputPairs M A N) (h' : (a', b') ∈ ratOutputPairs M A N) :
    (a + a', b + b') ∈ ratOutputPairs M A N := by
  obtain ⟨q, hqpos, hq⟩ := mem_ratOutputPairs_iff.mp h
  obtain ⟨q', hq'pos, hq'⟩ := mem_ratOutputPairs_iff.mp h'
  have hMR : (M : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hM
  have hAR : (A : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hA
  refine mem_ratOutputPairs_iff.mpr ⟨q * q', mul_pos hqpos hq'pos, ?_⟩
  rw [Rat.cast_mul, mul_pow, hq, hq', zpow_add₀ hMR, zpow_add₀ hAR]
  ring

/-- **The rational-output lattice is an additive subgroup of `ℤ × ℤ`.** -/
def ratOutputLattice {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) (N : ℕ) : AddSubgroup (ℤ × ℤ) where
  carrier := ratOutputPairs M A N
  add_mem' := by
    rintro ⟨a, b⟩ ⟨a', b'⟩ h h'
    show (a + a', b + b') ∈ ratOutputPairs M A N
    exact add_mem_ratOutputPairs hM hA h h'
  zero_mem' := by
    show ((0 : ℤ), (0 : ℤ)) ∈ ratOutputPairs M A N
    exact zero_mem_ratOutputPairs M A N
  neg_mem' := by
    rintro ⟨a, b⟩ h
    show (-a, -b) ∈ ratOutputPairs M A N
    exact neg_mem_ratOutputPairs h

/-- Membership in the lattice, as a subgroup, is membership in the underlying set. -/
theorem mem_ratOutputLattice_iff {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) {N : ℕ} {p : ℤ × ℤ} :
    p ∈ ratOutputLattice hM hA N ↔ p ∈ ratOutputPairs M A N :=
  Iff.rfl

/-! ### The copy of `ℤ²` and the containment `ℤ² ⊆ Λ_x` -/

/-- The **rational `2,3`-unit pairs** at denominator `N`: the pairs whose two coordinates are
divisible by `N`.  Under the scaling `(a, b) ↦ (a/N, b/N)` these are exactly the bases
`2 ^ u * 3 ^ v` with `u, v : ℤ`, that is, the report's copy of `ℤ²` inside `Λ_x`. -/
def twoThreeUnitPairs (N : ℕ) : AddSubgroup (ℤ × ℤ) where
  carrier := {p | (N : ℤ) ∣ p.1 ∧ (N : ℤ) ∣ p.2}
  add_mem' := by
    rintro ⟨a, b⟩ ⟨a', b'⟩ hp hp'
    obtain ⟨h₁, h₂⟩ := hp
    obtain ⟨h₁', h₂'⟩ := hp'
    show (N : ℤ) ∣ a + a' ∧ (N : ℤ) ∣ b + b'
    exact ⟨dvd_add h₁ h₁', dvd_add h₂ h₂'⟩
  zero_mem' := by
    show (N : ℤ) ∣ (0 : ℤ) ∧ (N : ℤ) ∣ (0 : ℤ)
    exact ⟨dvd_zero _, dvd_zero _⟩
  neg_mem' := by
    rintro ⟨a, b⟩ hp
    obtain ⟨h₁, h₂⟩ := hp
    show (N : ℤ) ∣ -a ∧ (N : ℤ) ∣ -b
    exact ⟨dvd_neg.mpr h₁, dvd_neg.mpr h₂⟩

/-- Unfolded membership in the rational `2,3`-unit pairs. -/
theorem mem_twoThreeUnitPairs {N : ℕ} {p : ℤ × ℤ} :
    p ∈ twoThreeUnitPairs N ↔ (N : ℤ) ∣ p.1 ∧ (N : ℤ) ∣ p.2 :=
  Iff.rfl

/-- **A rational `2,3`-unit base has a rational output.**  This is the easy inclusion of the
report's Proposition on the rational locus: `ℤ² ⊆ Λ_x`. -/
theorem mem_ratOutputPairs_of_dvd {M A N : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) {a b : ℤ}
    (ha : (N : ℤ) ∣ a) (hb : (N : ℤ) ∣ b) : (a, b) ∈ ratOutputPairs M A N := by
  obtain ⟨u, rfl⟩ := ha
  obtain ⟨v, rfl⟩ := hb
  have hMQ : (0 : ℚ) < (M : ℚ) := by exact_mod_cast Nat.pos_of_ne_zero hM
  have hAQ : (0 : ℚ) < (A : ℚ) := by exact_mod_cast Nat.pos_of_ne_zero hA
  refine mem_ratOutputPairs_iff.mpr ⟨(M : ℚ) ^ u * (A : ℚ) ^ v,
    mul_pos (zpow_pos hMQ u) (zpow_pos hAQ v), ?_⟩
  have hcast : (((M : ℚ) ^ u * (A : ℚ) ^ v : ℚ) : ℝ) = (M : ℝ) ^ u * (A : ℝ) ^ v := by
    push_cast <;> ring
  rw [hcast, zpow_mul_pow]

/-- **The containment `ℤ² ⊆ Λ_x`, in scaled form.** -/
theorem twoThreeUnitPairs_le_ratOutputLattice {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) (N : ℕ) :
    twoThreeUnitPairs N ≤ ratOutputLattice hM hA N := by
  rintro ⟨a, b⟩ hmem
  obtain ⟨ha, hb⟩ := mem_twoThreeUnitPairs.mp hmem
  exact mem_ratOutputPairs_of_dvd hM hA ha hb

/-- **At denominator one the lattice is everything.**  This is the unscaled form of the
report's containment `ℤ² ⊆ Λ_x`, and it explains why the whole content of the section lives in
the denominators: integral exponents always give a rational output. -/
theorem ratOutputPairs_one {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) :
    ratOutputPairs M A 1 = Set.univ := by
  ext ⟨a, b⟩
  simp only [Set.mem_univ, iff_true]
  exact mem_ratOutputPairs_of_dvd hM hA (by simp) (by simp)

/-! ### Finiteness of the defect -/

/-- Every class of `(ℤ × ℤ) ⧸ K` is represented by a pair of remainders modulo `N`, as soon as
`K` contains the `N`-scaled integer pairs. -/
private theorem quotient_mk_surjective_of_twoThreeUnitPairs_le {N : ℕ} (hN : 0 < N)
    {K : AddSubgroup (ℤ × ℤ)} (hK : twoThreeUnitPairs N ≤ K) :
    Function.Surjective (fun ij : Fin N × Fin N =>
      QuotientAddGroup.mk' K (((ij.1 : ℕ) : ℤ), ((ij.2 : ℕ) : ℤ))) := by
  intro z
  obtain ⟨⟨a, b⟩, rfl⟩ := QuotientAddGroup.mk'_surjective K z
  have hNz : ((N : ℤ)) ≠ 0 := by exact_mod_cast hN.ne'
  have hNpos : (0 : ℤ) < (N : ℤ) := by exact_mod_cast hN
  have ha0 : 0 ≤ a % (N : ℤ) := Int.emod_nonneg a hNz
  have hb0 : 0 ≤ b % (N : ℤ) := Int.emod_nonneg b hNz
  have haN : a % (N : ℤ) < (N : ℤ) := Int.emod_lt_of_pos a hNpos
  have hbN : b % (N : ℤ) < (N : ℤ) := Int.emod_lt_of_pos b hNpos
  have hia : (a % (N : ℤ)).toNat < N := by
    have h : (((a % (N : ℤ)).toNat : ℕ) : ℤ) < (N : ℤ) := by
      rw [Int.toNat_of_nonneg ha0]
      exact haN
    exact_mod_cast h
  have hib : (b % (N : ℤ)).toNat < N := by
    have h : (((b % (N : ℤ)).toNat : ℕ) : ℤ) < (N : ℤ) := by
      rw [Int.toNat_of_nonneg hb0]
      exact hbN
    exact_mod_cast h
  refine ⟨(⟨(a % (N : ℤ)).toNat, hia⟩, ⟨(b % (N : ℤ)).toNat, hib⟩), ?_⟩
  have hsub : ((a % (N : ℤ), b % (N : ℤ)) - (a, b) : ℤ × ℤ) ∈ twoThreeUnitPairs N := by
    refine mem_twoThreeUnitPairs.mpr ⟨⟨-(a / (N : ℤ)), ?_⟩, ⟨-(b / (N : ℤ)), ?_⟩⟩
    · show a % (N : ℤ) - a = (N : ℤ) * -(a / (N : ℤ))
      linear_combination Int.emod_add_ediv_mul a (N : ℤ)
    · show b % (N : ℤ) - b = (N : ℤ) * -(b / (N : ℤ))
      linear_combination Int.emod_add_ediv_mul b (N : ℤ)
  show QuotientAddGroup.mk' K ((((a % (N : ℤ)).toNat : ℕ) : ℤ),
      (((b % (N : ℤ)).toNat : ℕ) : ℤ)) = QuotientAddGroup.mk' K (a, b)
  rw [Int.toNat_of_nonneg ha0, Int.toNat_of_nonneg hb0]
  have h0 : QuotientAddGroup.mk' K ((a % (N : ℤ), b % (N : ℤ)) : ℤ × ℤ) -
      QuotientAddGroup.mk' K ((a, b) : ℤ × ℤ) = 0 := by
    rw [← map_sub, QuotientAddGroup.mk'_apply]
    exact (QuotientAddGroup.eq_zero_iff _).mpr (hK hsub)
  exact sub_eq_zero.mp h0

/-- **Finite index.**  A subgroup of `ℤ × ℤ` containing the `N`-scaled integer pairs has finite
quotient.  Applied to the rational-output lattice this is the report's assertion that `Λ_x`
contains `ℤ²` with finite index. -/
theorem finite_quotient_of_twoThreeUnitPairs_le {N : ℕ} (hN : 0 < N)
    {K : AddSubgroup (ℤ × ℤ)} (hK : twoThreeUnitPairs N ≤ K) : Finite ((ℤ × ℤ) ⧸ K) :=
  Finite.of_surjective _ (quotient_mk_surjective_of_twoThreeUnitPairs_le hN hK)

/-- The quantitative form of `finite_quotient_of_twoThreeUnitPairs_le`: the quotient has at most
`N ^ 2` elements. -/
theorem card_quotient_le_of_twoThreeUnitPairs_le {N : ℕ} (hN : 0 < N)
    {K : AddSubgroup (ℤ × ℤ)} (hK : twoThreeUnitPairs N ≤ K) :
    Nat.card ((ℤ × ℤ) ⧸ K) ≤ N * N := by
  have h := Nat.card_le_card_of_surjective _
    (quotient_mk_surjective_of_twoThreeUnitPairs_le hN hK)
  rwa [Nat.card_prod, Nat.card_fin] at h

/-- The quotient of `ℤ × ℤ` by the rational-output lattice is finite. -/
theorem finite_quotient_ratOutputLattice {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) {N : ℕ}
    (hN : 0 < N) : Finite ((ℤ × ℤ) ⧸ ratOutputLattice hM hA N) :=
  finite_quotient_of_twoThreeUnitPairs_le hN (twoThreeUnitPairs_le_ratOutputLattice hM hA N)

/-! ### The defect group `Λ_x/ℤ²` -/

/-- The **rational-output defect group**, the report's `Λ_x/ℤ²`: the image of the
rational-output lattice in `(ℤ × ℤ) ⧸ twoThreeUnitPairs N`.  Because the unit pairs are
contained in the lattice, this image is canonically the quotient of the lattice by them. -/
def ratOutputDefect {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) (N : ℕ) :
    AddSubgroup ((ℤ × ℤ) ⧸ twoThreeUnitPairs N) :=
  (ratOutputLattice hM hA N).map (QuotientAddGroup.mk' (twoThreeUnitPairs N))

/-- **The rational-output defect is finite.** -/
theorem finite_ratOutputDefect {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) {N : ℕ} (hN : 0 < N) :
    Finite (ratOutputDefect hM hA N) := by
  haveI : Finite ((ℤ × ℤ) ⧸ twoThreeUnitPairs N) :=
    finite_quotient_of_twoThreeUnitPairs_le hN le_rfl
  infer_instance

/-- **The defect vanishes exactly when no extra base has a rational output.**  This is the
report's remark that the rational-output defect equals `1` exactly when no auxiliary base
outside `{2 ^ u * 3 ^ v : u, v ∈ ℤ}` produces a rational output at `x`. -/
theorem ratOutputDefect_eq_bot_iff {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) (N : ℕ) :
    ratOutputDefect hM hA N = ⊥ ↔ ratOutputLattice hM hA N = twoThreeUnitPairs N := by
  constructor
  · intro h
    refine le_antisymm ?_ (twoThreeUnitPairs_le_ratOutputLattice hM hA N)
    intro p hp
    have hmem : QuotientAddGroup.mk' (twoThreeUnitPairs N) p ∈ ratOutputDefect hM hA N :=
      AddSubgroup.mem_map_of_mem _ hp
    rw [h, AddSubgroup.mem_bot, QuotientAddGroup.mk'_apply] at hmem
    exact (QuotientAddGroup.eq_zero_iff p).mp hmem
  · intro h
    refine le_antisymm ?_ bot_le
    rintro y ⟨p, hp, rfl⟩
    rw [h] at hp
    rw [AddSubgroup.mem_bot, QuotientAddGroup.mk'_apply]
    exact (QuotientAddGroup.eq_zero_iff p).mpr hp

/-! ### Two generators for the ambient quotient -/

/-- Every integer pair lies in the subgroup generated by `(1, 0)` and `(0, 1)`. -/
private theorem mem_closure_int_pair (a b : ℤ) :
    ((a, b) : ℤ × ℤ) ∈
      AddSubgroup.closure ({((1 : ℤ), (0 : ℤ)), ((0 : ℤ), (1 : ℤ))} : Set (ℤ × ℤ)) := by
  have he₁ : ((1 : ℤ), (0 : ℤ)) ∈
      AddSubgroup.closure ({((1 : ℤ), (0 : ℤ)), ((0 : ℤ), (1 : ℤ))} : Set (ℤ × ℤ)) :=
    AddSubgroup.subset_closure (by simp)
  have he₂ : ((0 : ℤ), (1 : ℤ)) ∈
      AddSubgroup.closure ({((1 : ℤ), (0 : ℤ)), ((0 : ℤ), (1 : ℤ))} : Set (ℤ × ℤ)) :=
    AddSubgroup.subset_closure (by simp)
  have hfst : ∀ c : ℤ, ((c, (0 : ℤ)) : ℤ × ℤ) ∈
      AddSubgroup.closure ({((1 : ℤ), (0 : ℤ)), ((0 : ℤ), (1 : ℤ))} : Set (ℤ × ℤ)) := by
    intro c
    induction c using Int.induction_on with
    | zero => exact AddSubgroup.zero_mem _
    | succ k ih => simpa using AddSubgroup.add_mem _ ih he₁
    | pred k ih => simpa using AddSubgroup.sub_mem _ ih he₁
  have hsnd : ∀ c : ℤ, (((0 : ℤ), c) : ℤ × ℤ) ∈
      AddSubgroup.closure ({((1 : ℤ), (0 : ℤ)), ((0 : ℤ), (1 : ℤ))} : Set (ℤ × ℤ)) := by
    intro c
    induction c using Int.induction_on with
    | zero => exact AddSubgroup.zero_mem _
    | succ k ih => simpa using AddSubgroup.add_mem _ ih he₂
    | pred k ih => simpa using AddSubgroup.sub_mem _ ih he₂
  simpa using AddSubgroup.add_mem _ (hfst a) (hsnd b)

/-- The pairs `(1, 0)` and `(0, 1)` generate `ℤ × ℤ`. -/
private theorem closure_int_pair_eq_top :
    AddSubgroup.closure ({((1 : ℤ), (0 : ℤ)), ((0 : ℤ), (1 : ℤ))} : Set (ℤ × ℤ)) = ⊤ := by
  refine eq_top_iff.mpr ?_
  rintro ⟨a, b⟩ -
  exact mem_closure_int_pair a b

/-- **Two generators.**  Every quotient of `ℤ × ℤ` is generated by the images of `(1, 0)` and
`(0, 1)`; in particular the finite defect groups of this file need at most two generators,
being quotients of a rank-two lattice.

This is the unconditional half of the report's Smith classification.  The classification itself
sharpens it to a *direct sum* of two cyclic groups with `d₁ ∣ d₂`, and that refinement is not
proved here --- see `HasSmithClassification`. -/
theorem closure_quotient_pair_eq_top (K : AddSubgroup (ℤ × ℤ)) :
    AddSubgroup.closure
        ({QuotientAddGroup.mk' K ((1 : ℤ), (0 : ℤ)),
          QuotientAddGroup.mk' K ((0 : ℤ), (1 : ℤ))} : Set ((ℤ × ℤ) ⧸ K)) = ⊤ := by
  have h := AddMonoidHom.map_closure (QuotientAddGroup.mk' K)
    ({((1 : ℤ), (0 : ℤ)), ((0 : ℤ), (1 : ℤ))} : Set (ℤ × ℤ))
  rw [closure_int_pair_eq_top,
    AddSubgroup.map_top_of_surjective _ (QuotientAddGroup.mk'_surjective K),
    Set.image_pair] at h
  exact h.symm

/-! ### The bridge to actual outputs -/

/-- The `x`-th power of `2 ^ r * 3 ^ s` is the corresponding monomial in the outputs. -/
private theorem two_three_zpow_rpow {x : ℝ} {M A : ℕ}
    (hM : (M : ℝ) = (2 : ℝ) ^ x) (hA : (A : ℝ) = (3 : ℝ) ^ x) (r s : ℤ) :
    ((2 : ℝ) ^ r * (3 : ℝ) ^ s) ^ x = (M : ℝ) ^ r * (A : ℝ) ^ s := by
  have h2 : (0 : ℝ) ≤ (2 : ℝ) ^ r := by positivity
  have h3 : (0 : ℝ) ≤ (3 : ℝ) ^ s := by positivity
  rw [Real.mul_rpow h2 h3, hM, hA]
  congr 1
  · rw [← Real.rpow_intCast_mul (by norm_num : (0 : ℝ) ≤ 2) r x,
      ← Real.rpow_mul_intCast (by norm_num : (0 : ℝ) ≤ 2) x r, mul_comm ((r : ℤ) : ℝ) x]
  · rw [← Real.rpow_intCast_mul (by norm_num : (0 : ℝ) ≤ 3) s x,
      ← Real.rpow_mul_intCast (by norm_num : (0 : ℝ) ≤ 3) x s, mul_comm ((s : ℤ) : ℝ) x]

/-- **The lattice detects rational roots.**  A positive real `N`-th root of the output monomial
`M ^ a * A ^ b` is rational exactly when `(a, b)` lies in the lattice. -/
theorem rat_root_iff_mem_ratOutputPairs {M A N : ℕ} (hN : 0 < N) {a b : ℤ} {β : ℝ}
    (hβ : 0 < β) (hβN : β ^ N = (M : ℝ) ^ a * (A : ℝ) ^ b) :
    β ∈ Set.range ((↑) : ℚ → ℝ) ↔ (a, b) ∈ ratOutputPairs M A N := by
  constructor
  · rintro ⟨q, rfl⟩
    have hq : 0 < q := by exact_mod_cast hβ
    exact mem_ratOutputPairs_iff.mpr ⟨q, hq, hβN⟩
  · intro hmem
    obtain ⟨q, hqpos, hq⟩ := mem_ratOutputPairs_iff.mp hmem
    refine ⟨q, ?_⟩
    have hqR : (0 : ℝ) ≤ (q : ℝ) := by exact_mod_cast hqpos.le
    have hpow : ((q : ℝ)) ^ N = β ^ N := by rw [hq, hβN]
    exact (pow_left_inj₀ hqR hβ.le hN.ne').mp hpow

/-- **The rational-output spectrum.**  For a two-base solution `x` with integral outputs
`M = 2 ^ x` and `A = 3 ^ x`, and an auxiliary base `α > 0` presented by `α ^ N = 2 ^ a * 3 ^ b`,
the output `α ^ x` is rational exactly when `(a, b)` lies in the rational-output lattice of the
output pair.  This is the report's Proposition *Exact rational auxiliary-output spectrum*,
carried in scaled integral coordinates. -/
theorem two_three_rpow_output_rat_iff {x : ℝ} {M A : ℕ}
    (hM : (M : ℝ) = (2 : ℝ) ^ x) (hA : (A : ℝ) = (3 : ℝ) ^ x)
    {N : ℕ} (hN : 0 < N) {a b : ℤ} {α : ℝ} (hα : 0 < α)
    (hαN : α ^ N = (2 : ℝ) ^ a * (3 : ℝ) ^ b) :
    α ^ x ∈ Set.range ((↑) : ℚ → ℝ) ↔ (a, b) ∈ ratOutputPairs M A N := by
  have hpow : (α ^ x) ^ N = (M : ℝ) ^ a * (A : ℝ) ^ b := by
    rw [← Real.rpow_natCast (α ^ x) N, ← Real.rpow_mul hα.le, mul_comm x (N : ℝ),
      Real.rpow_mul hα.le, Real.rpow_natCast, hαN, two_three_zpow_rpow hM hA a b]
  exact rat_root_iff_mem_ratOutputPairs hN (Real.rpow_pos_of_pos hα x) hpow

/-! ### The translation intersection -/

private theorem padicValRat_self_two : padicValRat 2 (2 : ℚ) = 1 := by
  simpa using padicValRat.self (p := 2) (by norm_num)

private theorem padicValRat_self_three : padicValRat 3 (3 : ℚ) = 1 := by
  simpa using padicValRat.self (p := 3) (by norm_num)

private theorem padicValRat_two_three : padicValRat 2 (3 : ℚ) = 0 := by
  have hnd : ¬ (2 : ℕ) ∣ 3 := by decide
  have h : padicValRat 2 ((3 : ℕ) : ℚ) = (padicValNat 2 3 : ℤ) := padicValRat.of_nat
  rw [padicValNat.eq_zero_of_not_dvd hnd] at h
  simpa using h

private theorem padicValRat_three_two : padicValRat 3 (2 : ℚ) = 0 := by
  have hnd : ¬ (3 : ℕ) ∣ 2 := by decide
  have h : padicValRat 3 ((2 : ℕ) : ℚ) = (padicValNat 3 2 : ℤ) := padicValRat.of_nat
  rw [padicValNat.eq_zero_of_not_dvd hnd] at h
  simpa using h

/-- **A rational `N`-th root of `2 ^ a * 3 ^ b` forces `N ∣ a` and `N ∣ b`.**  This is the
arithmetic step behind the report's translation intersection: a positive rational of the form
`2 ^ r * 3 ^ s` with `r, s ∈ ℚ` has `r, s ∈ ℤ`.  The proof compares the `2`-adic and `3`-adic
valuations of the two sides. -/
theorem dvd_of_rat_pow_eq_two_three_zpow {q : ℚ} (hq : q ≠ 0) {N : ℕ} {a b : ℤ}
    (h : q ^ N = (2 : ℚ) ^ a * (3 : ℚ) ^ b) : (N : ℤ) ∣ a ∧ (N : ℤ) ∣ b := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  have h2a : ((2 : ℚ) ^ a) ≠ 0 := zpow_ne_zero _ (by norm_num)
  have h3b : ((3 : ℚ) ^ b) ≠ 0 := zpow_ne_zero _ (by norm_num)
  have e2 : (N : ℤ) * padicValRat 2 q = a := by
    have hv := congrArg (padicValRat 2) h
    rw [padicValRat.pow (p := 2), padicValRat.mul (p := 2) h2a h3b,
      padicValRat.zpow (p := 2), padicValRat.zpow (p := 2),
      padicValRat_self_two, padicValRat_two_three] at hv
    linear_combination hv
  have e3 : (N : ℤ) * padicValRat 3 q = b := by
    have hv := congrArg (padicValRat 3) h
    rw [padicValRat.pow (p := 3), padicValRat.mul (p := 3) h2a h3b,
      padicValRat.zpow (p := 3), padicValRat.zpow (p := 3),
      padicValRat_three_two, padicValRat_self_three] at hv
    linear_combination hv
  exact ⟨⟨padicValRat 2 q, e2.symm⟩, ⟨padicValRat 3 q, e3.symm⟩⟩

/-- **Translation intersection.**  The report's Proposition `Λ_x ∩ Λ_{x+1} = ℤ²`, in scaled
integral coordinates.  The output pair of `x + 1` is `(2 * M, 3 * A)`, and a pair lying in both
lattices is a rational `2,3`-unit pair.  No transcendence input is used: the argument divides
the two relations and compares `2`-adic and `3`-adic valuations. -/
theorem ratOutputPairs_inter_translate {M A N : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) :
    ratOutputPairs M A N ∩ ratOutputPairs (2 * M) (3 * A) N =
      {p : ℤ × ℤ | (N : ℤ) ∣ p.1 ∧ (N : ℤ) ∣ p.2} := by
  have hM2 : 2 * M ≠ 0 := Nat.mul_ne_zero (by norm_num) hM
  have hA3 : 3 * A ≠ 0 := Nat.mul_ne_zero (by norm_num) hA
  ext ⟨a, b⟩
  constructor
  · rintro ⟨hmem, hmem'⟩
    obtain ⟨q, hqpos, hq⟩ := mem_ratOutputPairs_iff_rat.mp hmem
    obtain ⟨q', hq'pos, hq'⟩ := mem_ratOutputPairs_iff_rat.mp hmem'
    have hqne : q ≠ 0 := hqpos.ne'
    have hsplit : ((2 * M : ℕ) : ℚ) ^ a * ((3 * A : ℕ) : ℚ) ^ b =
        ((2 : ℚ) ^ a * (3 : ℚ) ^ b) * ((M : ℚ) ^ a * (A : ℚ) ^ b) := by
      push_cast
      rw [mul_zpow, mul_zpow]
      ring
    rw [hsplit, ← hq] at hq'
    have hqN : q ^ N ≠ 0 := pow_ne_zero _ hqne
    have hratEq : (q' / q) ^ N = (2 : ℚ) ^ a * (3 : ℚ) ^ b := by
      rw [div_pow, hq', mul_div_assoc, div_self hqN, mul_one]
    exact dvd_of_rat_pow_eq_two_three_zpow (div_ne_zero hq'pos.ne' hqne) hratEq
  · rintro ⟨ha, hb⟩
    exact ⟨mem_ratOutputPairs_of_dvd hM hA ha hb,
      mem_ratOutputPairs_of_dvd hM2 hA3 ha hb⟩

/-- **A base rational at two consecutive solutions is a rational `2,3`-unit.**  This is the
report's Proposition *Translation intersection* in its analytic phrasing: if the auxiliary base
`α`, presented by `α ^ N = 2 ^ a * 3 ^ b`, has rational outputs at both `x` and `x + 1`, then
`N ∣ a` and `N ∣ b`, that is `α = 2 ^ u * 3 ^ v` with `u, v : ℤ`.  The converse is immediate. -/
theorem two_three_rpow_rat_at_consecutive_iff {x : ℝ} {M A : ℕ}
    (hM : (M : ℝ) = (2 : ℝ) ^ x) (hA : (A : ℝ) = (3 : ℝ) ^ x)
    {N : ℕ} (hN : 0 < N) {a b : ℤ} {α : ℝ} (hα : 0 < α)
    (hαN : α ^ N = (2 : ℝ) ^ a * (3 : ℝ) ^ b) :
    (α ^ x ∈ Set.range ((↑) : ℚ → ℝ) ∧ α ^ (x + 1) ∈ Set.range ((↑) : ℚ → ℝ)) ↔
      ((N : ℤ) ∣ a ∧ (N : ℤ) ∣ b) := by
  have hMpos : (0 : ℝ) < (M : ℝ) := by
    rw [hM]
    exact Real.rpow_pos_of_pos (by norm_num) x
  have hApos : (0 : ℝ) < (A : ℝ) := by
    rw [hA]
    exact Real.rpow_pos_of_pos (by norm_num) x
  have hMne : M ≠ 0 := by exact_mod_cast hMpos.ne'
  have hAne : A ≠ 0 := by exact_mod_cast hApos.ne'
  have hM' : ((2 * M : ℕ) : ℝ) = (2 : ℝ) ^ (x + 1) := by
    rw [Real.rpow_add_one (by norm_num : (2 : ℝ) ≠ 0), ← hM]
    push_cast <;> ring
  have hA' : ((3 * A : ℕ) : ℝ) = (3 : ℝ) ^ (x + 1) := by
    rw [Real.rpow_add_one (by norm_num : (3 : ℝ) ≠ 0), ← hA]
    push_cast <;> ring
  rw [two_three_rpow_output_rat_iff hM hA hN hα hαN,
    two_three_rpow_output_rat_iff hM' hA' hN hα hαN]
  constructor
  · intro h
    have hmem : (a, b) ∈ ratOutputPairs M A N ∩ ratOutputPairs (2 * M) (3 * A) N := h
    rw [ratOutputPairs_inter_translate hMne hAne] at hmem
    exact hmem
  · rintro ⟨ha, hb⟩
    have hmem : (a, b) ∈ ratOutputPairs M A N ∩ ratOutputPairs (2 * M) (3 * A) N := by
      rw [ratOutputPairs_inter_translate hMne hAne]
      exact ⟨ha, hb⟩
    exact hmem

/-! ### The Smith classification, as an explicit hypothesis -/

/-- The **Smith classification** of a finite abelian group by two invariant factors: the report's
`Λ_x/ℤ² ≅ ℤ/d₁ℤ ⊕ ℤ/d₂ℤ` with `d₁ ∣ d₂`.

This is a *predicate*, not a theorem.  Producing it for `ratOutputDefect` requires the Smith
normal form of the prime-valuation matrix over `ℤ`, which is not developed in this file.
Everything below is therefore conditional on it, and says exactly what the report derives from
the classification once it is available. -/
def HasSmithClassification (G : Type*) [AddCommGroup G] (d₁ d₂ : ℕ) : Prop :=
  0 < d₁ ∧ 0 < d₂ ∧ d₁ ∣ d₂ ∧ Nonempty (G ≃+ ZMod d₁ × ZMod d₂)

/-- A group with a Smith classification is finite. -/
theorem HasSmithClassification.finite {G : Type*} [AddCommGroup G] {d₁ d₂ : ℕ}
    (h : HasSmithClassification G d₁ d₂) : Finite G := by
  obtain ⟨h₁, h₂, -, ⟨e⟩⟩ := h
  haveI : NeZero d₁ := ⟨h₁.ne'⟩
  haveI : NeZero d₂ := ⟨h₂.ne'⟩
  exact Finite.of_equiv _ e.symm.toEquiv

/-- **The order of the defect is the product of the invariant factors.**  This is the report's
`|Λ_x/ℤ²| = δ₂(V_x)`, with `δ₂ = d₁ d₂`. -/
theorem HasSmithClassification.card {G : Type*} [AddCommGroup G] {d₁ d₂ : ℕ}
    (h : HasSmithClassification G d₁ d₂) : Nat.card G = d₁ * d₂ := by
  obtain ⟨-, -, -, ⟨e⟩⟩ := h
  rw [Nat.card_congr e.toEquiv, Nat.card_prod, Nat.card_zmod, Nat.card_zmod]

/-- **The defect is trivial exactly when both invariant factors are one.** -/
theorem HasSmithClassification.card_eq_one_iff {G : Type*} [AddCommGroup G] {d₁ d₂ : ℕ}
    (h : HasSmithClassification G d₁ d₂) : Nat.card G = 1 ↔ d₁ = 1 ∧ d₂ = 1 := by
  have hcard := h.card
  obtain ⟨h₁, h₂, -, -⟩ := h
  rw [hcard]
  constructor
  · intro hc
    have hle₁ : d₁ ≤ 1 := Nat.le_of_dvd one_pos ⟨d₂, hc.symm⟩
    have hle₂ : d₂ ≤ 1 := Nat.le_of_dvd one_pos ⟨d₁, by rw [← hc]; ring⟩
    omega
  · rintro ⟨rfl, rfl⟩
    norm_num

/-- **The rational-output defect under the Smith classification.**  Conditional on the Smith
classification of the defect group, its order is `d₁ d₂` --- the report's rational-output
defect `δ₂(V_x)`. -/
theorem card_ratOutputDefect_of_smith {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) {N d₁ d₂ : ℕ}
    (h : HasSmithClassification (ratOutputDefect hM hA N) d₁ d₂) :
    Nat.card (ratOutputDefect hM hA N) = d₁ * d₂ :=
  h.card

/-- **Defect one means no extra rational base.**  Conditional on the Smith classification with
both invariant factors equal to one, the rational-output lattice is exactly the lattice of
rational `2,3`-unit bases: no auxiliary base outside `{2 ^ u * 3 ^ v : u, v ∈ ℤ}` has a
rational output. -/
theorem ratOutputDefect_eq_bot_of_smith_one {M A : ℕ} (hM : M ≠ 0) (hA : A ≠ 0) {N : ℕ}
    (h : HasSmithClassification (ratOutputDefect hM hA N) 1 1) :
    ratOutputLattice hM hA N = twoThreeUnitPairs N := by
  rw [← ratOutputDefect_eq_bot_iff]
  exact AddSubgroup.card_eq_one.mp (by simpa using h.card)

end LeanProofs.TwoBaseIntegerExponent
