"""Exact rational H^1 of the simplicial complex generated by tetrahedra.

A spanning-forest gauge removes coboundaries. A rational nullspace basis is
scaled to primitive integer cocycles. These span H^1 over Q; they are NOT
advertised as a Z-lattice basis. No manifold recognition is performed here.
"""
from __future__ import annotations

from fractions import Fraction
from itertools import combinations
from math import gcd
from typing import Sequence


def rational_cohomology_basis(tetrahedra: Sequence[Sequence[int]]
                              ) -> list[dict[tuple[int, int], int]]:
    tetrahedra = [tuple(t) for t in tetrahedra]
    if any(len(t) != 4 or any(type(v) is not int or v < 0 for v in t)
           or len(set(t)) != 4 for t in tetrahedra):
        raise ValueError("tetrahedra need four distinct nonnegative integer vertices")
    if len({tuple(sorted(t)) for t in tetrahedra}) != len(tetrahedra):
        raise ValueError("duplicate tetrahedron")
    edges = sorted({tuple(sorted(e)) for t in tetrahedra for e in combinations(t, 2)})
    faces = sorted({tuple(sorted(f)) for t in tetrahedra for f in combinations(t, 3)})
    parent = {v: v for t in tetrahedra for v in t}

    def find(v):
        while parent[v] != v:
            parent[v] = parent[parent[v]]
            v = parent[v]
        return v

    chords = []
    for u, v in edges:
        a, b = find(u), find(v)
        if a != b:
            parent[a] = b
        else:
            chords.append((u, v))
    index = {edge: i for i, edge in enumerate(chords)}
    n = len(chords)
    matrix = []
    for u, v, w in faces:
        row = [Fraction(0)] * n
        for edge, sign in [((u, v), 1), ((v, w), 1), ((u, w), -1)]:
            if edge in index:
                row[index[edge]] += sign
        if any(row):
            matrix.append(row)
    pivots = []
    at = 0
    for col in range(n):
        p = next((r for r in range(at, len(matrix)) if matrix[r][col]), None)
        if p is None:
            continue
        matrix[at], matrix[p] = matrix[p], matrix[at]
        pivot = matrix[at][col]
        matrix[at] = [x / pivot for x in matrix[at]]
        for r in range(len(matrix)):
            if r != at and matrix[r][col]:
                factor = matrix[r][col]
                matrix[r] = [x - factor * y for x, y in zip(matrix[r], matrix[at])]
        pivots.append(col)
        at += 1
        if at == len(matrix):
            break
    result = []
    for free in sorted(set(range(n)) - set(pivots)):
        vector = [Fraction(0)] * n
        vector[free] = Fraction(1)
        for r, pivot in enumerate(pivots):
            vector[pivot] = -matrix[r][free]
        denominator = 1
        for x in vector:
            denominator = denominator * x.denominator // gcd(denominator, x.denominator)
        integers = [x.numerator * (denominator // x.denominator) for x in vector]
        common = 0
        for x in integers:
            common = gcd(common, x)
        result.append({edge: integers[i] // common for i, edge in enumerate(chords)
                       if integers[i]})
    return result
