/-
Added for ProveIt (not an upstream file; distributed under Apache-2.0).
Incremental axiom audit of the first 300 modules listed in
quantitative-port-manifest.json, plus the added compatibility declarations.
This does not import or certify Results.Conclusions. Extend this checkpoint
as the remaining quantitative dependency port compiles.
-/
import OAI.Combinatorics.Progressions.Model
import OAI.Combinatorics.Progressions.Results.Basic
import OAI.Combinatorics.Progressions.Estimates.ComplexFiniteMeans
import OAI.Combinatorics.Progressions.Estimates.WeightedSummandCorrelation
import OAI.Combinatorics.Progressions.Estimates.BufferedSiteExpansion
import OAI.Combinatorics.Progressions.Lattices.RectangularLatticeCells
import OAI.Combinatorics.Progressions.Geometry.CompactBoxIntegral
import OAI.Combinatorics.Progressions.Probability.FiniteProbabilityLipschitz
import OAI.Combinatorics.Progressions.Sampling.ModelScoreComparison
import OAI.Combinatorics.Progressions.Estimates.CorrelationDerivative
import OAI.Combinatorics.Progressions.Estimates.CyclicShortShiftSet
import OAI.Combinatorics.Progressions.Estimates.UnitExpansionCorrelation
import OAI.Combinatorics.Progressions.Polynomial.PolynomialDensityBudget
import OAI.Combinatorics.Progressions.Geometry.BoxDetectionExponents
import OAI.Combinatorics.Progressions.Estimates.FixedPartnerPower
import OAI.Combinatorics.Progressions.Linear.BalancedDualBounds
import OAI.Combinatorics.Progressions.Estimates.ShiftTestingGowers
import OAI.Combinatorics.Progressions.Estimates.FiniteFiberTest
import OAI.Combinatorics.Progressions.Probability.FiniteConditionedMass
import OAI.Combinatorics.Progressions.Estimates.DenseCorrelationPairs
import OAI.Combinatorics.Progressions.Estimates.BooleanCubeProduct
import OAI.Combinatorics.Progressions.Fourier.FiniteSpectrumCutoff
import OAI.Combinatorics.Progressions.Fourier.FiniteFourierSmoothing
import OAI.Combinatorics.Progressions.Estimates.FiniteConvolution
import OAI.Combinatorics.Progressions.Fourier.GowersFourierMultiplier
import OAI.Combinatorics.Progressions.Lattices.IntegerAbsInterval
import OAI.Combinatorics.Progressions.Estimates.CyclicCutNeighborhood
import OAI.Combinatorics.Progressions.Estimates.LinearCutoff
import OAI.Combinatorics.Progressions.Fourier.RectangularGridCharacter
import OAI.Combinatorics.Progressions.Estimates.InteriorIntervalCutoff
import OAI.Combinatorics.Progressions.Fourier.CRTConfigurationTorus
import OAI.Combinatorics.Progressions.Estimates.FiniteImageCover
import OAI.Combinatorics.Progressions.Lattices.IntegerLiftOffset
import OAI.Combinatorics.Progressions.Fourier.RationalLiftCharacterTwist
import OAI.Combinatorics.Progressions.Estimates.DependentPatchValue
import OAI.Combinatorics.Progressions.Sampling.FrozenPartitionScore
import OAI.Combinatorics.Progressions.Estimates.ProgressionPartitionComposition
import OAI.Combinatorics.Progressions.Estimates.SimultaneousDirichlet
import OAI.Combinatorics.Progressions.Fourier.AffineTorusDensityIncrement
import OAI.Combinatorics.Progressions.Dynamics.FlatPatchReset
import OAI.Combinatorics.Progressions.Estimates.NormalizedCutoffs
import OAI.Combinatorics.Progressions.Linear.PeriodicKernelPartition
import OAI.Combinatorics.Progressions.Lattices.AffineLowestLayer
import OAI.Combinatorics.Progressions.Polynomial.VectorPolynomialReconstruction
import OAI.Combinatorics.Progressions.Polynomial.MixedWeightedPolynomialRename
import OAI.Combinatorics.Progressions.Polynomial.PolynomialPatchProductBudget
import OAI.Combinatorics.Progressions.Estimates.WeightedPatchReparam
import OAI.Combinatorics.Progressions.Linear.WeightedParameterPatchRankPadding
import OAI.Combinatorics.Progressions.Sampling.PositivePartitionScore
import OAI.Combinatorics.Progressions.Fourier.TorusCellBudget
import OAI.Combinatorics.Progressions.Lattices.CRTProgressionVanishing
import OAI.Combinatorics.Progressions.Estimates.AlgebraicMajorUniformExponent
import OAI.Combinatorics.Progressions.Estimates.SymmetricIntervalDilation
import OAI.Combinatorics.Progressions.Lattices.IntegerFiberCount
import OAI.Combinatorics.Progressions.Lattices.ShortIntegerDifference
import OAI.Combinatorics.Progressions.Estimates.CommonDenominatorMultiples
import OAI.Combinatorics.Progressions.Estimates.GowersWeightedDerivative
import OAI.Combinatorics.Progressions.Geometry.SupportedCubeEquivTransport
import OAI.Combinatorics.Progressions.Estimates.CubeTranslation
import OAI.Combinatorics.Progressions.Lattices.ResidueSliceCountingCost
import OAI.Combinatorics.Progressions.Estimates.PhysicalSliceCost
import OAI.Combinatorics.Progressions.Estimates.WeightedOverlapCorrelation
import OAI.Combinatorics.Progressions.Probability.NormalizedDensityL1
import OAI.Combinatorics.Progressions.Estimates.EmbeddedFiniteConditioning
import OAI.Combinatorics.Progressions.Estimates.FiniteReciprocalTenthTail
import OAI.Combinatorics.Progressions.Probability.ComplexPartitionMixture
import OAI.Combinatorics.Progressions.Lattices.BoxResiduePartition
import OAI.Combinatorics.Progressions.Geometry.BoxBlockBudget
import OAI.Combinatorics.Progressions.Sampling.NormalizedRealBoxHalfGrid
import OAI.Combinatorics.Progressions.Lattices.ResidueSliceNormalizedCell
import OAI.Combinatorics.Progressions.Lattices.PhysicalSubboxResidueSlice
import OAI.Combinatorics.Progressions.Polynomial.AffinePhaseBias
import OAI.Combinatorics.Progressions.Lattices.NearIntegerMultiples
import OAI.Combinatorics.Progressions.Dynamics.DenseProductPowerBudget
import OAI.Combinatorics.Progressions.Estimates.DenseProductApproximation
import OAI.Combinatorics.Progressions.Probability.DenseProductDensity
import OAI.Combinatorics.Progressions.Geometry.IntervalBoxDifference
import OAI.Combinatorics.Progressions.Estimates.ProductDifferenceBias
import OAI.Combinatorics.Progressions.Dynamics.MultiaffineBiasBudget
import OAI.Combinatorics.Progressions.Polynomial.PhasePreservingCauchySchwarz
import OAI.Combinatorics.Progressions.Probability.FiniteMassErrorSelection
import OAI.Combinatorics.Progressions.Geometry.BoxDifferenceHom
import OAI.Combinatorics.Progressions.Estimates.MultiaffineExpansion
import OAI.Combinatorics.Progressions.Fourier.BoxDifferenceCharacter
import OAI.Combinatorics.Progressions.Polynomial.MultiaffinePhaseDifference
import OAI.Combinatorics.Progressions.Estimates.MultiaffineBias
import OAI.Combinatorics.Progressions.Estimates.BlockSubsetCount
import OAI.Combinatorics.Progressions.Estimates.SquarefreeExponents
import OAI.Combinatorics.Progressions.Estimates.SquarefreeCoefficients
import OAI.Combinatorics.Progressions.Estimates.FormalExpLog
import OAI.Combinatorics.Progressions.Estimates.RationalHeight
import OAI.Combinatorics.Progressions.Estimates.TruncatedSeries
import OAI.Combinatorics.Progressions.Estimates.TensorContraction
import OAI.Combinatorics.Progressions.Estimates.DynkinTrees
import OAI.Combinatorics.Progressions.Linear.DynkinProjection
import OAI.Combinatorics.Progressions.Estimates.FreePrimitiveCriterion
import OAI.Combinatorics.Progressions.Linear.LieWordProjection
import OAI.Combinatorics.Progressions.Estimates.FreeLieTreeCoefficientBounds
import OAI.Combinatorics.Progressions.Nilpotent.NilpotentBilinearExponential
import OAI.Combinatorics.Progressions.Nilpotent.LieBCHContinuity
import OAI.Combinatorics.Progressions.Estimates.TruncatedSeriesFiltration
import OAI.Combinatorics.Progressions.Estimates.UniformProductAccuracy
import OAI.Combinatorics.Progressions.Linear.FiniteSpanRounding
import OAI.Combinatorics.Progressions.Dynamics.CandidateFrontSourceLossBudget
import OAI.Combinatorics.Progressions.Fourier.PrimePowerCharacterScaling
import OAI.Combinatorics.Progressions.Lattices.ResidueRefinedPeriod
import OAI.Combinatorics.Progressions.Lattices.IntegerCokernelExponent
import OAI.Combinatorics.Progressions.Fourier.CokernelCharacterWitness
import OAI.Combinatorics.Progressions.Fourier.CharacterCoordinateScale
import OAI.Combinatorics.Progressions.Fourier.IndependentCharacterEvents
import OAI.Combinatorics.Progressions.Probability.LargeCokernelProbability
import OAI.Combinatorics.Progressions.Lattices.IntegerColumnMinor
import OAI.Combinatorics.Progressions.Estimates.RationalRowReduction
import OAI.Combinatorics.Progressions.Dynamics.RationalHeightBudget
import OAI.Combinatorics.Progressions.Geometry.LinearMapCoordinateHeight
import OAI.Combinatorics.Progressions.Linear.SpanKernelGenerators
import OAI.Combinatorics.Progressions.Estimates.RationalSubspaces
import OAI.Combinatorics.Progressions.Linear.RationalKernelBudget
import OAI.Combinatorics.Progressions.Estimates.RationalImageIntersections
import OAI.Combinatorics.Progressions.Sampling.RationalSpanGrid
import OAI.Combinatorics.Progressions.Sampling.RealGridSeparation
import OAI.Combinatorics.Progressions.Linear.RationalMatrixSeparation
import OAI.Combinatorics.Progressions.Polynomial.IntegerPolynomialCongruence
import OAI.Combinatorics.Progressions.Polynomial.PolynomialTermCount
import OAI.Combinatorics.Progressions.Polynomial.PolynomialIntegerInputs
import OAI.Combinatorics.Progressions.Polynomial.LieCoordinatePolynomials
import OAI.Combinatorics.Progressions.Geometry.LieCoordinateHeight
import OAI.Combinatorics.Progressions.Polynomial.RationalPolynomialGrid
import OAI.Combinatorics.Progressions.Sampling.ConjugationGridBudget
import OAI.Combinatorics.Progressions.Nilpotent.BCHDenominatorBudget
import OAI.Combinatorics.Progressions.Geometry.LieCoordinateScalarExtension
import OAI.Combinatorics.Progressions.Nilpotent.BCHNonlinearRemainder
import OAI.Combinatorics.Progressions.Estimates.ProductPMFMap
import OAI.Combinatorics.Progressions.Estimates.RealWeightPMF
import OAI.Combinatorics.Progressions.Geometry.IndependentProductTransport
import OAI.Combinatorics.Progressions.Estimates.BooleanCubeModeWitness
import OAI.Combinatorics.Progressions.Linear.BooleanCubeCoordinateFrame
import OAI.Combinatorics.Progressions.Polynomial.BoundedRealPolynomialBasis
import OAI.Combinatorics.Progressions.Polynomial.IntegerPolynomialResidues
import OAI.Combinatorics.Progressions.Polynomial.RealPolynomialEvaluationMass
import OAI.Combinatorics.Progressions.Lattices.IntegerAffineResidues
import OAI.Combinatorics.Progressions.Estimates.RealBooleanInterpolation
import OAI.Combinatorics.Progressions.Linear.MatrixSupInverse
import OAI.Combinatorics.Progressions.Linear.RealKernelJetInverse
import OAI.Combinatorics.Progressions.Lattices.NormalizedIntegerDual
import OAI.Combinatorics.Progressions.Lattices.IntegralAffineModeRemoval
import OAI.Combinatorics.Progressions.Estimates.NormalizedIntervalWindow
import OAI.Combinatorics.Progressions.Linear.KernelMixtureControl
import OAI.Combinatorics.Progressions.Estimates.BoundedProductDifference
import OAI.Combinatorics.Progressions.Estimates.CompactIntervalIntegral
import OAI.Combinatorics.Progressions.Geometry.FiniteSupportTranslation
import OAI.Combinatorics.Progressions.Estimates.LocalAverageAmplitude
import OAI.Combinatorics.Progressions.Estimates.PartialComplexScaledQuadrature
import OAI.Combinatorics.Progressions.Lattices.CompactLatticeApproximation
import OAI.Combinatorics.Progressions.Estimates.NormalizedSampledHistogram
import OAI.Combinatorics.Progressions.Probability.BinaryDensity
import OAI.Combinatorics.Progressions.Probability.SampledWeightCellLaw
import OAI.Combinatorics.Progressions.Geometry.BoxWindowAveraging
import OAI.Combinatorics.Progressions.Lattices.AffineBoxTest
import OAI.Combinatorics.Progressions.Geometry.BoxTestSmoothing
import OAI.Combinatorics.Progressions.Estimates.SmoothedImageTest
import OAI.Combinatorics.Progressions.Geometry.BoxImageComparison
import OAI.Combinatorics.Progressions.Geometry.ProductEuclideanCoordinates
import OAI.Combinatorics.Progressions.Estimates.ProperSubspaceCount
import OAI.Combinatorics.Progressions.Lattices.DenseIntegerSpan
import OAI.Combinatorics.Progressions.Estimates.EuclideanBisectorNull
import OAI.Combinatorics.Progressions.Linear.SpanSubsetBasis
import OAI.Combinatorics.Progressions.Linear.ZSpanRounding
import OAI.Combinatorics.Progressions.Lattices.LatticeVoronoiPacking
import OAI.Combinatorics.Progressions.Linear.ShortVectorProjection
import OAI.Combinatorics.Progressions.Sampling.DerivativeGridPoints
import OAI.Combinatorics.Progressions.Lattices.EuclideanDerivativeLattice
import OAI.Combinatorics.Progressions.Probability.DiagonalDensityTransport
import OAI.Combinatorics.Progressions.Geometry.TwoBoxSmoothingComplex
import OAI.Combinatorics.Progressions.Estimates.InverseSqrtMoment
import OAI.Combinatorics.Progressions.Geometry.UnitBoxAmplitude
import OAI.Combinatorics.Progressions.Probability.PairedProductDensity
import OAI.Combinatorics.Progressions.Probability.DiagonalImageDensity
import OAI.Combinatorics.Progressions.Estimates.CutoffImageTest
import OAI.Combinatorics.Progressions.Dynamics.ProductCutoffBudget
import OAI.Combinatorics.Progressions.Estimates.SmoothSublevelCutoff
import OAI.Combinatorics.Progressions.Geometry.ChartCutoff
import OAI.Combinatorics.Progressions.Geometry.BoxChartCutoff
import OAI.Combinatorics.Progressions.Geometry.SigmaAxisCoordinates
import OAI.Combinatorics.Progressions.Geometry.PivotCoordinateChange
import OAI.Combinatorics.Progressions.Probability.TranslatedMixtureL1
import OAI.Combinatorics.Progressions.Estimates.PivotJacobianBound
import OAI.Combinatorics.Progressions.Dynamics.PivotDeterminantBudget
import OAI.Combinatorics.Progressions.Linear.PivotNormalizedMatrix
import OAI.Combinatorics.Progressions.Sampling.PivotGridErrorTransfer
import OAI.Combinatorics.Progressions.Lattices.IntegerFiberUniformBound
import OAI.Combinatorics.Progressions.Probability.SmoothProbabilityProfile
import OAI.Combinatorics.Progressions.Estimates.SplitSmoothProductProfile
import OAI.Combinatorics.Progressions.Geometry.NormalizedRestrictionTransport
import OAI.Combinatorics.Progressions.Geometry.ProgressionCoordinateResampling
import OAI.Combinatorics.Progressions.Estimates.PaddedBooleanFeatures
import OAI.Combinatorics.Progressions.Geometry.OperatorCoordinateBound
import OAI.Combinatorics.Progressions.Polynomial.PolynomialAnalyticDerivative
import OAI.Combinatorics.Progressions.Polynomial.PolynomialDeterminantDerivativeBound
import OAI.Combinatorics.Progressions.Sampling.BooleanProductSampler
import OAI.Combinatorics.Progressions.Polynomial.BooleanBlockCoefficientPhase
import OAI.Combinatorics.Progressions.Estimates.RectangularCellGeometry
import OAI.Combinatorics.Progressions.Estimates.SublevelThresholdBalance
import OAI.Combinatorics.Progressions.Estimates.FiniteFiberVolumeBound
import OAI.Combinatorics.Progressions.Estimates.SeparatedInterpolationBound
import OAI.Combinatorics.Progressions.Estimates.SeparatedRealSamples
import OAI.Combinatorics.Progressions.Polynomial.UnivariatePolynomialSublevel
import OAI.Combinatorics.Progressions.Estimates.SymmetricScalarSublevel
import OAI.Combinatorics.Progressions.Polynomial.PolynomialCoordinateSlice
import OAI.Combinatorics.Progressions.Probability.SymmetricCubeMeasure
import OAI.Combinatorics.Progressions.Estimates.SymmetricCubeSublevel
import OAI.Combinatorics.Progressions.Estimates.SymmetricCubeVolume
import OAI.Combinatorics.Progressions.Polynomial.PolynomialDeterminantDegree
import OAI.Combinatorics.Progressions.Geometry.CoordinateDeterminant
import OAI.Combinatorics.Progressions.Polynomial.PolynomialDilation
import OAI.Combinatorics.Progressions.Polynomial.PolynomialValueCoefficient
import OAI.Combinatorics.Progressions.Polynomial.EmbeddedMatrixDeterminantPolynomial
import OAI.Combinatorics.Progressions.Estimates.BooleanMinorDimension
import OAI.Combinatorics.Progressions.Estimates.SmoothHalfspaceCutoff
import OAI.Combinatorics.Progressions.Estimates.ScalarCubeDomain
import OAI.Combinatorics.Progressions.Probability.ScalarCubeDomainDensity
import OAI.Combinatorics.Progressions.Estimates.ScalarCubeBoundaryCost
import OAI.Combinatorics.Progressions.Geometry.ScalarCubeCoordinates
import OAI.Combinatorics.Progressions.Estimates.ScalarCubeBoundaryVolume
import OAI.Combinatorics.Progressions.Probability.ScalarCubeBoundaryMass
import OAI.Combinatorics.Progressions.Estimates.ScalarCubeFaceSlab
import OAI.Combinatorics.Progressions.Probability.ScaledCubeProductMeasure
import OAI.Combinatorics.Progressions.Estimates.ProductCutoffLipschitz
import OAI.Combinatorics.Progressions.Estimates.ResidualErrorAllocation
import OAI.Combinatorics.Progressions.Lattices.ScalarCubeLatticeGeometry
import OAI.Combinatorics.Progressions.Probability.ScalarCubeDensityBudget
import OAI.Combinatorics.Progressions.Dynamics.ScalarCubeBoundaryLogBudget
import OAI.Combinatorics.Progressions.Estimates.FiniteInversePerturbation
import OAI.Combinatorics.Progressions.Geometry.CutoffBoxImageComparison
import OAI.Combinatorics.Progressions.Geometry.DivergenceSupport
import OAI.Combinatorics.Progressions.Estimates.CompactSmoothApproximation
import OAI.Combinatorics.Progressions.Estimates.UnitTestClipping
import OAI.Combinatorics.Progressions.Probability.BoundedSmoothTestDensity
import OAI.Combinatorics.Progressions.Estimates.WeightedImageDerivative
import OAI.Combinatorics.Progressions.Geometry.ImageCoordinateDerivative
import OAI.Combinatorics.Progressions.Estimates.LocalProductContinuity
import OAI.Combinatorics.Progressions.Geometry.LocalCoordinateDivergence
import OAI.Combinatorics.Progressions.Geometry.CoordinateInjection
import OAI.Combinatorics.Progressions.Linear.SelectedCoordinateMatrix
import OAI.Combinatorics.Progressions.Lattices.AffineSliceC2Difference
import OAI.Combinatorics.Progressions.Polynomial.PolynomialParameterContinuity
import OAI.Combinatorics.Progressions.Estimates.BooleanSelectedDerivativeBound
import OAI.Combinatorics.Progressions.Estimates.LocalImageComparison
import OAI.Combinatorics.Progressions.Estimates.BoundedInequalityGoodCutoff
import OAI.Combinatorics.Progressions.Estimates.PrincipalCoefficientSource
import OAI.Combinatorics.Progressions.Geometry.BlockCubeCoordinates
import OAI.Combinatorics.Progressions.Estimates.SigmaAxisOperator
import OAI.Combinatorics.Progressions.Polynomial.BooleanPolynomialBudget
import OAI.Combinatorics.Progressions.Lattices.BooleanAffineInput
import OAI.Combinatorics.Progressions.Estimates.CoefficientNormalization
import OAI.Combinatorics.Progressions.Polynomial.MonomialArrayJet
import OAI.Combinatorics.Progressions.Sampling.CanonicalSamplerTuple
import OAI.Combinatorics.Progressions.Estimates.JointBooleanGoodWeight
import OAI.Combinatorics.Progressions.Probability.FiniteArrayMeasure
import OAI.Combinatorics.Progressions.Probability.DensityMixtureAELaw
import OAI.Combinatorics.Progressions.Probability.RestrictedComplexChartDensityComparison
import OAI.Combinatorics.Progressions.Geometry.UnitBoxInteriorCutoff
import OAI.Combinatorics.Progressions.Probability.SigmaProductMeasure
import OAI.Combinatorics.Progressions.Estimates.SlicedPairAmplitude
import OAI.Combinatorics.Progressions.Probability.PairedProductLaw
import OAI.Combinatorics.Progressions.Estimates.FourProductSmoothing
import OAI.Combinatorics.Progressions.Lattices.RandomAffinePair
import OAI.Combinatorics.Progressions.Probability.SlicedPairDensity
import OAI.Combinatorics.Progressions.Estimates.FourSlicedProductSmoothing
import OAI.Combinatorics.Progressions.Dynamics.SlicedProductBudget
import OAI.Combinatorics.Progressions.Probability.SpatialProductDensity
import OAI.Combinatorics.Progressions.Probability.SlicedRemainderDensityFamily
import OAI.Combinatorics.Progressions.Estimates.FactoredC2Difference
import OAI.Combinatorics.Progressions.Polynomial.JointBooleanPolynomialPerturbation
import OAI.Combinatorics.Progressions.Probability.BooleanJetMassBudget
import OAI.Combinatorics.Progressions.Estimates.CoefficientTailScaling
import OAI.Combinatorics.Progressions.Sampling.BooleanSamplerMeasurability
import OAI.Combinatorics.Progressions.Estimates.RawProductArrayNormalization
import OAI.Combinatorics.Progressions.Sampling.CanonicalRawSampler
import OAI.Combinatorics.Progressions.Estimates.ScaledJointFrozenSource
import OAI.Combinatorics.Progressions.Polynomial.RawCanonicalNormalizedPolynomial
import OAI.Combinatorics.Progressions.Estimates.PrincipalBlockExponent
import OAI.Combinatorics.Progressions.Polynomial.PrincipalMonomialScale
import OAI.Combinatorics.Progressions.Estimates.PrincipalCoefficientMarginal
import OAI.Combinatorics.Progressions.Polynomial.PolynomialKernelValues
import OAI.Combinatorics.Progressions.Polynomial.ExtendedPolynomialValues
import OAI.Combinatorics.Progressions.Polynomial.SquarefreePolynomialQuotient
import OAI.Combinatorics.Progressions.Nilpotent.SquarefreeBracketCoefficients
import OAI.Combinatorics.Progressions.Polynomial.SquarefreeBlockDegree
import OAI.Combinatorics.Progressions.Estimates.SquarefreeSplitCount
import OAI.Combinatorics.Progressions.Lattices.MultilinearAffineExpansion
import OAI.Combinatorics.Progressions.Polynomial.MultilinearSlicePolynomial
import OAI.Combinatorics.Progressions.Estimates.MultiaffineOptionExpansion
import OAI.Combinatorics.Progressions.Polynomial.MultiaffinePolynomialBias
import OAI.Combinatorics.Progressions.Estimates.StrideProductBounds
import OAI.Combinatorics.Progressions.Estimates.FiniteBiasedSlice
import OAI.Combinatorics.Progressions.Linear.MatrixCoordinateSlice
import OAI.Combinatorics.Progressions.Geometry.MultilinearBoxInverse
import OAI.Combinatorics.Progressions.Geometry.BoxDifferenceSubstitution
import OAI.Combinatorics.Progressions.Geometry.BoxCornerMean
import OAI.Compat.Set
import OAI.Compat.Isometry
import OAI.Compat.FinsetInj
import OAI.Compat.MatrixInjective
import OAI.Compat.ExteriorPower
import OAI.Compat.ContinuousLinearMap
import Lean.Util.CollectAxioms

set_option maxHeartbeats 0
open Lean Elab Command in
run_cmd do
  let env ← getEnv
  let allowed : Array Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let mut checked : Nat := 0
  for (name, info) in env.constants do
    if (`OAI).isPrefixOf name && info.isTheorem then
      for axiomName in (← collectAxioms name) do
        unless allowed.contains axiomName do
          throwError "{name} depends on unapproved axiom {axiomName}"
      checked := checked + 1
  for name in #[``Set.mem_ofPred_eq, ``Isometry.lipschitzWith, ``Finset.sum_le_sum_of_injOn, ``Matrix.mulVec_injective_of_det_ne_zero, ``Matrix.gram_eq_one_iff_orthonormal, ``exteriorPower.inner_ιMulti_ιMulti, ``exteriorPower.inner_ιMulti_self, ``OrthonormalBasis.exteriorPower, ``OrthonormalBasis.toBasis_exteriorPower, ``ContinuousLinearMap.lipschitzWith] do
    for axiomName in (← collectAxioms name) do
      unless allowed.contains axiomName do
        throwError "{name} depends on unapproved axiom {axiomName}"
  if checked == 0 then throwError "No OAI theorems found"
  logInfo m!"Audited {checked} public OAI theorems: only propext, Classical.choice, Quot.sound."
#print axioms Set.mem_ofPred_eq
#print axioms Isometry.lipschitzWith
#print axioms Finset.sum_le_sum_of_injOn
#print axioms Matrix.mulVec_injective_of_det_ne_zero
#print axioms Matrix.gram_eq_one_iff_orthonormal
#print axioms exteriorPower.inner_ιMulti_ιMulti
#print axioms exteriorPower.inner_ιMulti_self
#print axioms OrthonormalBasis.exteriorPower
#print axioms OrthonormalBasis.toBasis_exteriorPower
#print axioms ContinuousLinearMap.lipschitzWith
