import FabiusFunction.IntervalParseval
import FabiusFunction.IntSumFolding
import FabiusFunction.PascalTailIdentity
import FabiusFunction.PeriodicOrbitGelfondBound
import FabiusFunction.PascalParityPeriodic
import FabiusFunction.RvachevHalfIntegerEnergy
import FabiusFunction.LambertWElementaryBounds
import FabiusFunction.CompleteHomogeneous
import FabiusFunction.CompleteHomogeneousGenerating
import FabiusFunction.CompleteHomogeneousBell
import FabiusFunction.CompleteHomogeneousAsymptotics
import FabiusFunction.SymmetricFunctionOrthogonality
import FabiusFunction.FiniteTriangularTransform
import FabiusFunction.TriangularKernelInverse
import FabiusFunction.BinomialInversion
import FabiusFunction.StirlingBasisChange
import FabiusFunction.LahNumbers
import FabiusFunction.BellStirling
import FabiusFunction.StirlingGeneratingFunctions
import FabiusFunction.EulerianNumbers
import FabiusFunction.PartialBellPolynomials
import FabiusFunction.BellGeneratingFunctions
import FabiusFunction.BellComposition
import FabiusFunction.BernoulliStirling
import FabiusFunction.BellHomogeneity
import FabiusFunction.StirlingOrdinaryGF
import FabiusFunction.EulerianGeneratingFunctions
import FabiusFunction.ExponentialRiordan
import FabiusFunction.ExponentialFormula
import FabiusFunction.OrderedBell
import FabiusFunction.OrdinaryPartialBell
import FabiusFunction.EulerianStirling
import FabiusFunction.NewtonExpansion
import FabiusFunction.ComplementaryBell
import FabiusFunction.StirlingTriangularExplicit
import FabiusFunction.BellShiftEGF
import FabiusFunction.OrdinaryBellComposition
import FabiusFunction.EulerianEGF
import FabiusFunction.BernoulliAppell
import FabiusFunction.StirlingShiftedEvaluations
import FabiusFunction.StirlingTransformEGF
import FabiusFunction.StirlingSummations
import FabiusFunction.StirlingNormalOrder
import FabiusFunction.BinomialType
import FabiusFunction.BellLeadingZeros
import FabiusFunction.GenocchiNumbers
import FabiusFunction.EulerianAlternating
import FabiusFunction.EulerPolynomials
import FabiusFunction.EulerReflection
import FabiusFunction.FaulhaberOffset
import FabiusFunction.RaabeMultiplication
import FabiusFunction.TouchardCongruence
import FabiusFunction.TouchardShiftEGF
import FabiusFunction.TouchardPolyCongruence
import FabiusFunction.TypeBEulerian
import FabiusFunction.SecondOrderEulerian
import FabiusFunction.ShiftOperatorCharP
import FabiusFunction.BellUmbra
import FabiusFunction.StirlingParity
import FabiusFunction.CatalanGeneratingFunction
import FabiusFunction.StirlingFirstReverse
import FabiusFunction.BernoulliNewtonBasis
import FabiusFunction.NorlundPolynomials
import FabiusFunction.BellDerivative
import FabiusFunction.AssociatedStirling
import FabiusFunction.RStirling
import FabiusFunction.FallingFactorialSeries
import FabiusFunction.CauchyPolynomials
import FabiusFunction.CoefficientRules
import FabiusFunction.IteratedLeibniz
import FabiusFunction.NorlundDiagonal
import FabiusFunction.NarayanaNumbers
import FabiusFunction.StirlingFirstModH
import FabiusFunction.LagrangeInversion
import FabiusFunction.LambertWSeries
import FabiusFunction.FussCatalanSeries
import FabiusFunction.InverseBellCoefficients
import FabiusFunction.StirlingFirstDiagonal
import FabiusFunction.DiamondPower
import FabiusFunction.OrdinaryBellBivariate
import FabiusFunction.BinomialInversionEGF
import FabiusFunction.EulerianPolynomialRecurrence
import FabiusFunction.BellFactorialRowSum
import FabiusFunction.BellInversionTwo
import FabiusFunction.StirlingSecondReverseColumn
import FabiusFunction.ElementarySymmetricBell
import FabiusFunction.ExpLog
import FabiusFunction.CumulantBellFormula
import FabiusFunction.NewtonPowerSumBell
import FabiusFunction.ExpAddLog
import FabiusFunction.SquareRootSeries
import FabiusFunction.PowerSumOrdinaryBell
import FabiusFunction.StirlingParityBitwise
import FabiusFunction.StirlingSecondReverseRow
import FabiusFunction.SymmetricFunctionTransform
import FabiusFunction.SymmetricFunctionGenerating
import FabiusFunction.FiniteQBinomialCore
import FabiusFunction.QBinomialReciprocity
import FabiusFunction.QBinomialInversion
import FabiusFunction.QPochhammerElementaryIdentities
import FabiusFunction.QDifferenceAnnihilation
import FabiusFunction.QBinomialTransform
import FabiusFunction.QBinomialVandermonde
import FabiusFunction.QBinomialCauchy
import FabiusFunction.GaussianBinomialAtOne
import FabiusFunction.GaussianBinomialAtNegOne
import FabiusFunction.GaussianBinomialAtNegOneDerivative
import FabiusFunction.GeometricCompleteHomogeneous
import FabiusFunction.GeometricLagrange
import FabiusFunction.LagrangeResidualMoments
import FabiusFunction.GeometricResidualMoments
import FabiusFunction.FinitePowerSeriesFilter
import FabiusFunction.GeometricPowerSeriesFilter
import FabiusFunction.AnalyticSeriesFilter
import FabiusFunction.RvachevQBinomialFilter
import FabiusFunction.GeometricQBinomialLagrange
import FabiusFunction.QBinomialInversionSpecializations
import FabiusFunction.GeometricRichardson
import FabiusFunction.GeometricLagrangeWeights
import FabiusFunction.GeometricLagrangeQBinomial
import FabiusFunction.GeometricLagrangeQMoments
import FabiusFunction.GeometricLagrangeCompleteHomogeneous
import FabiusFunction.GeometricRichardsonGenerating
import FabiusFunction.LambertPhaseLockedRichardson
import FabiusFunction.LambertPhaseLockedBell
import FabiusFunction.LambertReciprocalAsymptotics
import FabiusFunction.FabiusLambertPhaseLockedPullback
import FabiusFunction.FabiusLambertPhaseExtraction
import FabiusFunction.FabiusLambertPhaseExtractionBell
import FabiusFunction.PrincipalLambertW
import FabiusFunction.PrincipalLambertWAtTop
import FabiusFunction.ProuhetBaseTwoBridge
import FabiusFunction.AutonomousIteratedDeriv
import FabiusFunction.LambertWHigherDerivatives
import FabiusFunction.LambertWAntiderivative
import FabiusFunction.LambertWLogBounds
import FabiusFunction.LambertWNegativeBounds
import FabiusFunction.LambertWAdditionIdentity
import FabiusFunction.LambertWBranchPairing
import FabiusFunction.LambertWGapBijection
import FabiusFunction.LambertWBranchGapBernoulli
import FabiusFunction.LambertWBranchSymmetry
import FabiusFunction.LowerLambertW
import FabiusFunction.GeneralizedLambertCoordinate
import FabiusFunction.LambertBranchDichotomy
import FabiusFunction.LambertWCurvature
import FabiusFunction.LambertWBranchPointGeometry
import FabiusFunction.LambertWBranchPointAsymptotics
import FabiusFunction.PowerExponentialLambert
import FabiusFunction.PowerExponentialLambertCalculus
import FabiusFunction.PowerExponentialLambertCurvature
import FabiusFunction.PowerExponentialLambertInverse
import FabiusFunction.PowerExponentialLambertAsymptotics
import FabiusFunction.PowerExponentialLambertFabius
import FabiusFunction.PowerExponentialLambertFabiusCurvature
import FabiusFunction.WeightedUniformSeries
import FabiusFunction.WeightedUniformDistribution
import FabiusFunction.WeightedUniformSupport
import FabiusFunction.ContinuousCDF
import FabiusFunction.AffineIndependentCopy
import FabiusFunction.GeometricUniformLaw
import FabiusFunction.GeometricUniformMultisection
import FabiusFunction.GeometricUniformUniqueness
import FabiusFunction.GeometricUniformCDF
import FabiusFunction.GeometricUniformRealization
import FabiusFunction.GeometricUniformMomentPolynomial
import FabiusFunction.GeometricUniformMomentPolynomialBridge
import FabiusFunction.GeometricUniformComplexMomentProduct
import FabiusFunction.GeometricUniformExteriorComplexMomentGerm
import FabiusFunction.GeometricUniformMomentReciprocity
import FabiusFunction.GeometricUniformMomentRatFunc
import FabiusFunction.GeometricUniformMomentPolynomialDegree
import FabiusFunction.Paper05442
import FabiusFunction.Paper06487
import FabiusFunction.PaperFabiusAsymptotic
import FabiusFunction.FinitePolynomialFilterExactness
import FabiusFunction.FiniteAffineCombinationBounds
import FabiusFunction.FabiusDiscreteLimitRates
import FabiusFunction.EndpointTransferPolynomials
import FabiusFunction.PerturbedLowerLambert
import FabiusFunction.PaperKFoldThueMorse
import FabiusFunction.FinitePolynomialFunctional
import FabiusFunction.PolynomialMomentFunctional
import FabiusFunction.FiniteMomentGram
import FabiusFunction.GramStieltjes
import FabiusFunction.FiniteMomentJacobi
import FabiusFunction.GramStieltjesNaturality
import FabiusFunction.PolynomialMomentGramDeterminant
import FabiusFunction.LegendrePolynomialRational
import FabiusFunction.WeightedScaleMultiplicity
import FabiusFunction.BaseDigitMultiplicity
import FabiusFunction.PartitionDefect
import FabiusFunction.SpectralZetaWeighted
import FabiusFunction.ShiftDifferenceWeights
import FabiusFunction.NewtonMultiplicityAssembly
import FabiusFunction.NewtonBasisGeneratingFunction
import FabiusFunction.NewtonSpectralZeta
import FabiusFunction.NewtonCoefficientUniqueness
import FabiusFunction.BellPolynomialInversion
import FabiusFunction.AppellSequence
import FabiusFunction.MomentCumulantAlgebra
import FabiusFunction.SaddleLogProductAlgebra
import FabiusFunction.SaddleLogExpansionPowerSeries
import FabiusFunction.CenteredMomentCumulants
import FabiusFunction.CenteredMomentParity
import FabiusFunction.SinhDivBernoulliLog
import FabiusFunction.HyperbolicActivation
import FabiusFunction.ActivationSeries
import FabiusFunction.ActivationAsymptotics
import FabiusFunction.ActivationTaylor
import FabiusFunction.ActivationSeriesAsymptotics
import FabiusFunction.GeometricActivationDimension
import FabiusFunction.GeometricActivationAsymptotics
import FabiusFunction.ReciprocalExponentialGenerating
import FabiusFunction.RvachevMomentAppell
import FabiusFunction.FinitePrefixAppellRecovery
import FabiusFunction.ImplicitPowerSeries
import FabiusFunction.QuadraticCompositionalInverse
import FabiusFunction.PolynomialExpectationCumulant
import FabiusFunction.ThueMorseBasicLemmas
import FabiusFunction.ThueMorseBitSupport
import FabiusFunction.AffineDifferenceOrbit
import FabiusFunction.ThueMorseBooleanCube
import FabiusFunction.ThueMorseComplexExponential
import FabiusFunction.BitPositionGenerating
import FabiusFunction.ParityCharacter
import FabiusFunction.ParityCharacterKernel
import FabiusFunction.DigitCharacterCongruence
import FabiusFunction.BinaryDigitFloor
import FabiusFunction.RademacherSine
import FabiusFunction.BaseDigitProduct
import FabiusFunction.SignedRowSum
import FabiusFunction.BaseDigitProuhet
import FabiusFunction.RulerLogDerivative
import FabiusFunction.RulerLogSeries
import FabiusFunction.BaseBProduct
import FabiusFunction.ThueMorseCubature
import FabiusFunction.ThueMorseAutocorrelationLimit
import FabiusFunction.BellPolynomialMoments
import FabiusFunction.GeneralizedProuhetBlock
import FabiusFunction.ProuhetBlockZeroOrder
import FabiusFunction.BitPositionQBinomial
import FabiusFunction.BinaryPartitionGreenInverse
import FabiusFunction.DigitDefectCounting
import FabiusFunction.DigitDefectBitForm
import FabiusFunction.ThueMorseValuation
import FabiusFunction.DyadicZeroMultiplicity
import FabiusFunction.PascalDyadicMultiplicity
import FabiusFunction.CentralBinomialValuation
import FabiusFunction.PrimePowerBinomialValuation
import FabiusFunction.ThueMorseDigits
import FabiusFunction.ThueMorseEnumerators
import FabiusFunction.ThueMorseRarefied
import FabiusFunction.ThueMorseAperiodicity
import FabiusFunction.ThueMorseSparseProuhet
import FabiusFunction.ThueMorseBlockAlgebra
import FabiusFunction.ThueMorseProductIdentity
import FabiusFunction.ApproximationLadder
import FabiusFunction.ThueMorseMoments
import FabiusFunction.FinitePrefixThueMorseCollapse
import FabiusFunction.ThueMorseArtinSchreier
import FabiusFunction.ThueMorseEulerTransform
import FabiusFunction.ThueMorseLucasSupport
import FabiusFunction.DigitalDensity
import FabiusFunction.SubmaskDensityAsymptotic
import FabiusFunction.ThueMorseWalsh
import FabiusFunction.ThueMorseComplexProductBridge
import FabiusFunction.ThueMorseSparseMoments
import FabiusFunction.ThueMorseMixedDifference
import FabiusFunction.ThueMorseSymmetricDifference
import FabiusFunction.ThueMorseCornerIntegral
import FabiusFunction.ThueMorseAutocorrelation
import FabiusFunction.ThueMorseOverlapFree
import FabiusFunction.ThueMorseRecurrence
import FabiusFunction.ThueMorseRecurrenceGap
import FabiusFunction.ThueMorseSparseBinomial
import FabiusFunction.ThueMorseMahler
import FabiusFunction.ThueMorseBooleanMobius
import FabiusFunction.ThueMorseMultinomial
import FabiusFunction.ThueMorseFourier
import FabiusFunction.ThueMorseSineProduct
import FabiusFunction.ThueMorseFourierInversion
import FabiusFunction.HalfIntegerOddDFT
import FabiusFunction.SummableCyclicAlias
import FabiusFunction.HalfIntegerAliasIdentity
import FabiusFunction.DyadicBoundaryIdentity
import FabiusFunction.AliasDyadicBridge
import FabiusFunction.AliasQBinomialBridge
import FabiusFunction.MeanValueBracket
import FabiusFunction.TransseriesHeight
import FabiusFunction.TransseriesScale
import FabiusFunction.TransseriesWellBased
import FabiusFunction.WrightOmega
import FabiusFunction.LambertShiftInverse
import FabiusFunction.LambertInverseCoefficients
import FabiusFunction.CyclicCharacterSums
import FabiusFunction.AliasErrorBound
import FabiusFunction.DyadicDerivativeFiltration
import FabiusFunction.ThueMorseParseval
import FabiusFunction.ThueMorseComplexity
import FabiusFunction.ThueMorseArithmeticFilter
import FabiusFunction.RealZPowProduct
import FabiusFunction.ToeplitzHessenberg
import FabiusFunction.ThueMorseHessenberg
import FabiusFunction.ExponentialPartition
import FabiusFunction.ThueMorsePartition
import FabiusFunction.ExponentialBell
import FabiusFunction.UnitSeriesBellCoefficients
import FabiusFunction.ThueMorseIntegerLift
import FabiusFunction.ThueMorseBoundaryFlatness
import FabiusFunction.ThueMorseDirichlet
import FabiusFunction.ThueMorseCatalanSeries
import FabiusFunction.ThueMorseCatalanConvolution
import FabiusFunction.ThueMorseIntegerLiftEquation
import FabiusFunction.ThueMorseIntegerLiftRecurrence
import FabiusFunction.ThueMorseLacunaryQuotient
import FabiusFunction.ThueMorseInfiniteProduct
import FabiusFunction.ThueMorseMellin
import FabiusFunction.ThueMorseWoodsRobbins
import FabiusFunction.ThueMorseMasterProduct
import FabiusFunction.ThueMorseBlockProducts
import FabiusFunction.ThueMorseEntireContinuation
import FabiusFunction.FrullaniIntegral
import FabiusFunction.ReciprocalGammaJets
import FabiusFunction.ThueMorseGDirichlet
import FabiusFunction.ThueMorseGammaTower
import FabiusFunction.ThueMorseGammaTowerDifferential
import FabiusFunction.ThueMorseQuarterProduct
import FabiusFunction.ThueMorseDiscSeries
import FabiusFunction.ThueMorseNaturalBoundary
import FabiusFunction.ThueMorseComputability
import FabiusFunction.WordComplexity
import FabiusFunction.ThueMorseNewman
import FabiusFunction.ThueMorseNewmanQuantitative
import FabiusFunction.ThueMorseNewmanResidues
import FabiusFunction.ThueMorseNewmanSelfSimilarity
import FabiusFunction.ThueMorseGelfond
import FabiusFunction.ThueMorseGelfondSharpness
import FabiusFunction.PeriodDoublingHankel
import FabiusFunction.ThueMorseHankel
import FabiusFunction.LacunaryRieszIntegral
import FabiusFunction.RieszSharpness
import FabiusFunction.GelfondLogisticBound
import FabiusFunction.GeometricScaleProducts
import FabiusFunction.GeneralizedRvachevProduct
import FabiusFunction.WeightLinearityProducts
import FabiusFunction.WeierstrassProductBound
import FabiusFunction.SincLowerBound
import FabiusFunction.SincProductPositive
import FabiusFunction.RelativeHarmonicDominance
import FabiusFunction.PlateauLocalization
import FabiusFunction.PlateauDegree
import FabiusFunction.PlateauConstant
import FabiusFunction.UniformSplineStrictMono
import FabiusFunction.QuarterCellEvaluation
import FabiusFunction.PlateauLimit
import FabiusFunction.QuarterQuantile
import FabiusFunction.StieltjesInversion
import FabiusFunction.PoissonApproximateIdentity
import FabiusFunction.PoissonMassSwap
import FabiusFunction.StieltjesPerron
import FabiusFunction.GeneralQConditionNumber
import FabiusFunction.GeometricToeplitzBridge
import FabiusFunction.LimitConditionNumber
import FabiusFunction.CumulantGridConstant
import FabiusFunction.MultipleAngleBounds
import FabiusFunction.TentMoment
import FabiusFunction.FaberSchauderDefect
import FabiusFunction.GeometricConvolutionTails
import FabiusFunction.SmoothingOperatorInversion
import FabiusFunction.SmoothingOperatorExponential
import FabiusFunction.AlgebraicInverseGerm
import FabiusFunction.AlgebraicInverseGermAnalytic
import FabiusFunction.AlgebraicInverseGermBinomial
import FabiusFunction.FabiusInverseQuarterJet
import FabiusFunction.GeometricCgfTails
import FabiusFunction.GeometricTailDictionary
import FabiusFunction.GeometricUniformDictionary
import FabiusFunction.GeometricSincFactorization
import FabiusFunction.DyadicCombTrapezoid
import FabiusFunction.IncompleteBetaMaster
import FabiusFunction.MeasureCauchyTransform
import FabiusFunction.MeasureCauchyMomentLaurent
import FabiusFunction.MomentHankelMatrix
import FabiusFunction.MomentHankelValues
import FabiusFunction.StieltjesMomentLaurent
import FabiusFunction.StieltjesCauchyTransform
import FabiusFunction.StieltjesHerglotz
import FabiusFunction.RefinementConditioning
import FabiusFunction.EntireKernelCalculus
import FabiusFunction.StieltjesLogFixedPoint
import FabiusFunction.StieltjesResolventHierarchy
import FabiusFunction.StieltjesGeneralizedOrder
import FabiusFunction.OrthogonalPolynomialConstruction
import FabiusFunction.OrthogonalPolynomialGramBridge
import FabiusFunction.RvachevRationalJacobi
import FabiusFunction.FabiusLegendreHankelDeterminant
import FabiusFunction.FabiusLegendreRationalGram
import FabiusFunction.FabiusLegendreRationalGramValues
import FabiusFunction.OrthogonalPolynomialValues
import FabiusFunction.OrthogonalPolynomialParity
import FabiusFunction.OrthogonalPolynomialRecurrence
import FabiusFunction.OrthogonalPolynomialJacobi
import FabiusFunction.CompositeMeshExactness
import FabiusFunction.RvachevPolynomialSynthesis
import FabiusFunction.LagrangeRvachevSynthesis
import FabiusFunction.RvachevAppellHasse
import FabiusFunction.RvachevLagrangeNodesOnly
import FabiusFunction.LagrangeRvachevMatrix
import FabiusFunction.CombFirstDefect
import FabiusFunction.CompositeMeshSharpness
import FabiusFunction.CombDefectSeries
import FabiusFunction.RvachevSuperconvergentSynthesis
import FabiusFunction.CauchySurvival
import FabiusFunction.CauchyHigherPowers
import FabiusFunction.MonomialCombFourier
import FabiusFunction.MonomialCombDerivatives
import FabiusFunction.MonomialCombAlias
import FabiusFunction.MonomialCombExactness
import FabiusFunction.PolynomialCombExactness
import FabiusFunction.SincProductShells
import FabiusFunction.RvachevFixedMantissaRay
import FabiusFunction.SharpGelfondBound
import FabiusFunction.CyclicSineProductBound
import FabiusFunction.SincProductPeakRay
import FabiusFunction.DoublingCocycleIdentities
import FabiusFunction.DiscreteLacunaryParseval
import FabiusFunction.SineProductRootsUnity
import FabiusFunction.SincMeanBracket
import FabiusFunction.PeakRayEnvelope
import FabiusFunction.DoublingTransferAdjoint
import FabiusFunction.GeometricCesaro
import FabiusFunction.LogSineMeanZero
import FabiusFunction.LogTanMeanZero
import FabiusFunction.SquareLogIntegrable
import FabiusFunction.MartingaleOrthogonality
import FabiusFunction.CocycleCovarianceHalving
import FabiusFunction.DirichletKernelCotangent
import FabiusFunction.LogSineFourierCoefficient
import FabiusFunction.CocycleParseval
import FabiusFunction.LogCosineFourier
import FabiusFunction.GordinParseval
import FabiusFunction.ClausenCorollaries
import FabiusFunction.DoublingMapTransfer
import FabiusFunction.CovarianceLadder
import FabiusFunction.DistanceCounting
import FabiusFunction.BirkhoffVariance
import FabiusFunction.BirkhoffProductBridge
import FabiusFunction.BirkhoffMoments
import FabiusFunction.ShellLinearity
import FabiusFunction.BoundaryLayerMax
import FabiusFunction.VarianceBookkeeping
import FabiusFunction.SharpGelfondEquality
import FabiusFunction.CesaroProfileSkeleton
import FabiusFunction.LogMeanSkeleton
import FabiusFunction.SincEulerProduct
import FabiusFunction.SincCanonicalProduct
import FabiusFunction.RvachevPochhammerFactorization
import FabiusFunction.QPochhammerEntire
import FabiusFunction.GeometricPochhammerNormalConvergence
import FabiusFunction.GeneralizedCanonicalForm
import FabiusFunction.LobeSignLaw
import FabiusFunction.CanonicalIntegerPoint
import FabiusFunction.LobeSignNegative
import FabiusFunction.GeneralizedRvachevEntire
import FabiusFunction.AlternatingNewtonFamily
import FabiusFunction.AlternatingNewtonZeta
import FabiusFunction.GeneralizedZeroDivisor
import FabiusFunction.GeneralizedRvachevIdentifiability
import FabiusFunction.LobeSignComplete
import FabiusFunction.GeneralizedRealBound
import FabiusFunction.GeneralizedExponentialType
import FabiusFunction.ClassicalGrowth
import FabiusFunction.RMSTransferEigenfunctions
import FabiusFunction.LogFactorConcavity
import FabiusFunction.CentralLobeConcavity
import FabiusFunction.LobeDerivativeFormulas
import FabiusFunction.CentralLobeOnePeak
import FabiusFunction.CentralLobePeakAtZero
import FabiusFunction.LobeLogFactorization
import FabiusFunction.SideLobeConcavity
import FabiusFunction.OnePeakPerLobe
import FabiusFunction.RvachevProductContinuity
import FabiusFunction.KappaZeroInMeasure
import FabiusFunction.LogProductMoments
import FabiusFunction.BaselineDecay
import FabiusFunction.FluctuationTightness
import FabiusFunction.LatticeFiber
import FabiusFunction.ZeroOrderTail
import FabiusFunction.PhiZeroOrder
import FabiusFunction.PhiRealSign
import FabiusFunction.LobeSignCount
import FabiusFunction.ValleyZeroOrders
import FabiusFunction.ThueMorseLobeSign
import FabiusFunction.LobeSignSelfSimilarity
import FabiusFunction.RenormalizationIdentity
import FabiusFunction.FourierLaplaceRotation
import FabiusFunction.IntegerZeroLocalFactorization
import FabiusFunction.LeadingJet
import FabiusFunction.IntegerZeroAnalyticOrder
import FabiusFunction.RvachevLaurentLeading
import FabiusFunction.ScaledInfiniteProducts
import FabiusFunction.GeometricReciprocalGamma
import FabiusFunction.GeometricSincCharacteristicFunction
import FabiusFunction.DyadicGammaOrder
import FabiusFunction.ReciprocalIntegerGammaZeros
import FabiusFunction.SincPrefixBound
import FabiusFunction.GlobalDecayEnvelope
import FabiusFunction.LacunaryMeanSharp
import FabiusFunction.KappaDictionary
import FabiusFunction.DyadicReflection
import FabiusFunction.CollatzWielandt
import FabiusFunction.LacunaryProductToSum
import FabiusFunction.LacunaryProductToSumCosine
import FabiusFunction.CenteredRvachevThueMorseFourier
import FabiusFunction.LogSeriesMultiplicative
import FabiusFunction.BaseLayerRegrouping
import FabiusFunction.ShellEnvelopeExplicit
import FabiusFunction.ThueMorseSinhProduct
import FabiusFunction.RvachevFourierDecay
import FabiusFunction.BoundednessSkeleton
import FabiusFunction.TransferOperatorStep
import FabiusFunction.TransseriesBlockAntiderivative
import FabiusFunction.TransseriesDifferentialBlock
import FabiusFunction.TransseriesHarmonicIncrement
import FabiusFunction.TransseriesScaleDominance
import FabiusFunction.TransseriesPolyLogScale
import FabiusFunction.TransseriesFlat
import FabiusFunction.TriangularPowerProduct
import FabiusFunction.LasotaYorkeIteration
import FabiusFunction.TransferPositivity
import FabiusFunction.PerronRootExistence
import FabiusFunction.PerronEigenvalueUnique
import FabiusFunction.DiagonalSelection
import FabiusFunction.MeasureEqualization
import FabiusFunction.NegativeLaplace
import FabiusFunction.SubgraphFubini
import FabiusFunction.SurvivalLayerCake
import FabiusFunction.CDFLayerCake
import FabiusFunction.ProbabilityLaplaceMoments
import FabiusFunction.UnitLaplaceMomentBounds
import FabiusFunction.PeriodicCorrection
import FabiusFunction.MellinBose
import FabiusFunction.MellinFinitePart
import FabiusFunction.BoseFinitePartIntegral
import FabiusFunction.PeriodicMean
import FabiusFunction.PeriodicRegularity
import FabiusFunction.LaplacePeriodicSecondOrder
import FabiusFunction.EndpointLogDerivativeExpansion
import FabiusFunction.LaplaceMomentBoundsSharp
import FabiusFunction.FabiusTranslatedLegendreSeries
import FabiusFunction.FabiusLegendreLeastSquares
import FabiusFunction.LegendreGaunt
import FabiusFunction.LegendreGauntClosedForm
import FabiusFunction.FabiusLegendreEnergy
import FabiusFunction.FabiusLegendreRationalEnergy
import FabiusFunction.FabiusLegendreGaunt
import FabiusFunction.FabiusLegendreGauntClosedForm
import FabiusFunction.FabiusSquareEnergyFourier
import FabiusFunction.FabiusLegendreTranslateBlocks
import FabiusFunction.RvachevLegendreBiorthogonality
import FabiusFunction.RvachevLegendreCentralSum
import FabiusFunction.FabiusLegendreTranslateSeries
import FabiusFunction.FabiusBinaryReductionSeries
import FabiusFunction.FabiusComputability
import FabiusFunction.Monotonicity
import FabiusFunction.Regularity
import FabiusFunction.Convexity
import FabiusFunction.EffectiveFlatness
import FabiusFunction.SharpFlatness
import FabiusFunction.FabiusInverse
import FabiusFunction.InverseModulus
import FabiusFunction.FabiusInverseEffectiveContinuity
import FabiusFunction.FabiusInverseLogarithmicModulus
import FabiusFunction.FabiusInverseExactDyadicModulus
import FabiusFunction.MidpointEndpointTransfer
import FabiusFunction.InverseMidpointDefect
import FabiusFunction.InverseLayerCake
import FabiusFunction.InversePairIntegral
import FabiusFunction.QuantileTransport
import FabiusFunction.InverseQuarterAnchor
import FabiusFunction.QuarterCatalanGerm
import FabiusFunction.QuarterCatalanRichardson
import FabiusFunction.QuarterSplineLocalPolynomial
import FabiusFunction.QuarterSplineTwoSided
import FabiusFunction.GlobalBounds
import FabiusFunction.NormalizedVolterra
import FabiusFunction.FractionalVolterra
import FabiusFunction.FractionalVolterraCalculus
import FabiusFunction.FractionalVolterraSemigroup
import FabiusFunction.FractionalCDFLayerCake
import FabiusFunction.FabiusFractionalIntegral
import FabiusFunction.FabiusFractionalVolterra
import FabiusFunction.FabiusAntiderivatives
import FabiusFunction.RvachevDerivativeDistribution
import FabiusFunction.BoundedDerivatives
import FabiusFunction.NowhereAnalytic
import FabiusFunction.AlgebraicBranch
import FabiusFunction.ElementaryFunction
import FabiusFunction.NotElementary
import FabiusFunction.InverseBranch
import FabiusFunction.InverseNotElementary
import FabiusFunction.FabiusComputableSpline
import FabiusFunction.EffectiveMonotoneInverse
import FabiusFunction.PrimrecNatPow
import FabiusFunction.EffectiveGapInverse
import FabiusFunction.FabiusGapInversion
import FabiusFunction.FabiusInverseComputable
import FabiusFunction.FabiusSaddleJetClosedForm
import FabiusFunction.FabiusSaddleExponentClosedForm
import FabiusFunction.FabiusSaddleJetStirling
import FabiusFunction.FabiusSaddleLeadingCoefficient
import FabiusFunction.FabiusSecondSaddleCorrection
import FabiusFunction.FabiusSecondSaddleExpansion
import FabiusFunction.EulerLogTransform
import FabiusFunction.WeightedEulerTransform
import FabiusFunction.EvenZetaSeries
import FabiusFunction.EvenZetaValues
import FabiusFunction.SincZetaSeries
import FabiusFunction.SincZetaDyadic
import FabiusFunction.GeometricSincZeta
import FabiusFunction.LaplaceEndpointAllOrders
import FabiusFunction.GeneralizedSincZeta
import FabiusFunction.AlternatingNewtonCumulantKernel
import FabiusFunction.ExponentialDiskMaximality
import FabiusFunction.SincZetaRemainder
import FabiusFunction.BernsteinPositivity
import FabiusFunction.PerronRootEnclosure
import FabiusFunction.KappaOneEnclosure
import FabiusFunction.KappaConstantEnclosures
import FabiusFunction.MeasureRefinement
import FabiusFunction.UniformDigitThueMorseBridge
import FabiusFunction.RandomSeriesLaw
import FabiusFunction.GeometricUniformCauchy
import FabiusFunction.CauchyTransform
import FabiusFunction.CauchyCDF
import FabiusFunction.CauchyRenormalization
import FabiusFunction.UniformSplineWeakConvergence
import FabiusFunction.DyadicSpecializations
import FabiusFunction.EvaluatorPopcount
import FabiusFunction.PrefixKernelCounting
import FabiusFunction.ThueMorseFormalProduct
import FabiusFunction.GlobalBlockFold
import FabiusFunction.NormalizationDictionary
import FabiusFunction.QPochhammerDissection
import FabiusFunction.QPochhammerInfinite
import FabiusFunction.QBinomialTheoremInfinite
import FabiusFunction.GaussianBinomialFixedColumnRate
import FabiusFunction.GaussianBinomialGreaterOneAsymptotics
import FabiusFunction.JacobiTripleProduct
import FabiusFunction.QPascalSummation
import FabiusFunction.GaussianBinomialContinuity
import FabiusFunction.QuantumBinomial
import FabiusFunction.RogersSzegoPolynomial
import FabiusFunction.PolynomialQDerivative
import FabiusFunction.PolynomialQLeibniz
import FabiusFunction.QGamma
import FabiusFunction.LambertSeriesLog
import FabiusFunction.QPochhammerDerivative
import FabiusFunction.HalfQBinomialRootSimplicity
import FabiusFunction.ClassicalPochhammerLimit
import FabiusFunction.QPochhammerIntegerIndex
import FabiusFunction.QPartialFractions
import FabiusFunction.PolynomialQTaylor
import FabiusFunction.GaussianBinomialUniversal
import FabiusFunction.GaussianBinomialPolynomialStructure
import FabiusFunction.QPochhammerInfiniteBounds
import FabiusFunction.HeineTransformation
import FabiusFunction.QGaussSummation
import FabiusFunction.QPochhammerComplexOrder
import FabiusFunction.BasicHypergeometricSeries
import FabiusFunction.QMultinomial
import FabiusFunction.QExponential
import FabiusFunction.JacksonIntegral
import FabiusFunction.QPochhammerLogDerivative
import FabiusFunction.QPochhammerLambertForm
import FabiusFunction.QPochhammerOrderDerivative
import FabiusFunction.JacobiCubic
import FabiusFunction.CyclotomicFactorization
import FabiusFunction.CentralQBinomialReduction
import FabiusFunction.CentralQVandermondeInfinite
import FabiusFunction.PrimitiveRootBlock
import FabiusFunction.QLucas
import FabiusFunction.CyclotomicDivisibility
import FabiusFunction.QCatalan
import FabiusFunction.QBetaIntegral
import FabiusFunction.NewtonInterpolation
import FabiusFunction.GaussianBinomialInteger
import FabiusFunction.GaussianBinomialComplexOrder
import FabiusFunction.QPfaffSaalschutz
import FabiusFunction.QuantumMultinomial
import FabiusFunction.GaussianBinomialBounds
import FabiusFunction.BinaryWordInversions
import FabiusFunction.BinaryWeightTotals
import FabiusFunction.BoxPartitions
import FabiusFunction.TelescopingCertificate
import FabiusFunction.VandermondeAlternant
import FabiusFunction.CyclotomicFactorList
import FabiusFunction.QGammaMultiplication
import FabiusFunction.ComplexGaussianBinomial
import FabiusFunction.BilateralSeriesConvergence
import FabiusFunction.QGammaLogDerivative
import FabiusFunction.PowerSeriesUniqueness
import FabiusFunction.DivisorSumLambert
import FabiusFunction.ReciprocalQBinomialAnalytic
import FabiusFunction.TwoPhiOneReversal
import FabiusFunction.QGammaLogConvex
import FabiusFunction.QChuVandermonde
import FabiusFunction.GeometricFilterBound
import FabiusFunction.GaussianBinomialCumulants
import FabiusFunction.GeometricSimplexSum
import FabiusFunction.IntegerParameterTranslation
import FabiusFunction.MultisetInversions
import FabiusFunction.GeometricSimplexReindex
import FabiusFunction.RatioExpansion
import FabiusFunction.ThetaHeatEquation
import FabiusFunction.QPochhammerModularAsymptotic
import FabiusFunction.FormalQBinomial
import FabiusFunction.BorweinReciprocity
import FabiusFunction.GaussianUnimodality
import FabiusFunction.TwoSquareTheorem
import FabiusFunction.JacobiTwoSquareCount
import FabiusFunction.FourSquareTheorem
import FabiusFunction.JacksonVeryWellPoised
import FabiusFunction.QSeriesTruncation
import FabiusFunction.RogersRamanujanPartitions
import FabiusFunction.GLOrderProduct
import FabiusFunction.SchroeterFormula
import FabiusFunction.SubspaceMobius
import FabiusFunction.BasicBernoulliLog
import FabiusFunction.GaussianFourierTheta
import FabiusFunction.JacksonRationalCertificate
import FabiusFunction.JacobiImaginaryTransform
import FabiusFunction.ThetaProductIdentities
import FabiusFunction.CyclicSievingSubsets
import FabiusFunction.SchurPrincipalSpecialization
import FabiusFunction.RankMatrixCount
import FabiusFunction.QExponentialFactorization
import FabiusFunction.LambertTailLimit
import FabiusFunction.SubspaceCount
import FabiusFunction.AndrewsGordonFreeIndices
import FabiusFunction.ClassicalHypergeometricLimit
import FabiusFunction.QGammaClassicalLimit
import FabiusFunction.ComplexGaussianClassical
import FabiusFunction.QuintupleProduct
import FabiusFunction.QBabbage
import FabiusFunction.ThetaSimpleZeros
import FabiusFunction.LambertSeriesLocallyUniform
import FabiusFunction.QGaussFullDomain
import FabiusFunction.RamanujanOnePsiOne
import FabiusFunction.QGammaMeromorphic
import FabiusFunction.RegularCentralQBinomialSum
import FabiusFunction.BasicHypergeometricDivergence
import FabiusFunction.GaussianIntegerPrimes
import FabiusFunction.HessenbergDeterminant
import FabiusFunction.JacksonFundamentalExtension
import FabiusFunction.SumsOfSquaresGeneratingFunction
import FabiusFunction.JacobiTripleProductUniform
import FabiusFunction.RogersContinuant
import FabiusFunction.RogersSeries
import FabiusFunction.BaileyLemmaFull
import FabiusFunction.BaileyChainBounds
import FabiusFunction.AndrewsGordon
import FabiusFunction.AndrewsGordonOne
import FabiusFunction.BaileyLowering
import FabiusFunction.BaileyChain
import FabiusFunction.BaileyInversion
import FabiusFunction.BaileyAux
import FabiusFunction.BaileyPairs
import FabiusFunction.BaileyUnitPairs
import FabiusFunction.BaileyLimitInfinite
import FabiusFunction.RogersRamanujan
import FabiusFunction.QBinomialLocallyUniform
import FabiusFunction.EulerPartitionRecurrence
import FabiusFunction.PartitionStabilization
import FabiusFunction.DurfeeAll
import FabiusFunction.PartitionDistinctOdd
import FabiusFunction.PartitionGeneratingFunction
import FabiusFunction.PartitionBoundedParts
import FabiusFunction.QBohrMollerup
import FabiusFunction.PartitionMultiplicity
import FabiusFunction.EulerTelescoping
import FabiusFunction.GaussianBinomialPalindromic
import FabiusFunction.ThetaQuasiPeriodicity
import FabiusFunction.FabiusDyadicGaussianForm
import FabiusFunction.FabiusGeneralLinearDenominator
import FabiusFunction.ThueMorseComplexHalfAngle
import FabiusFunction.ThueMorseQPochhammer
import FabiusFunction.QPochhammerMultiplicativeDissection
import FabiusFunction.ThueMorseEulerFunction
import FabiusFunction.ThueMorseQPochhammerInfinite
import FabiusFunction.ThueMorsePentagonal
import FabiusFunction.LambertWAnalytic
import FabiusFunction.MixedDifferenceForwardDiff
import FabiusFunction.GeometricProuhetBlock
import FabiusFunction.GeneralLinearThueMorseSum
import FabiusFunction.QuadraticCoreCatalan
import FabiusFunction.DerangementNearestInteger
import FabiusFunction.PowerLogCoreInversion
import FabiusFunction.LinLogCoreInversion
import FabiusFunction.StaircaseInversion
import FabiusFunction.RemainderTransport

set_option autoImplicit false

/-!
# Fabius function

Public import surface for the bounded Fabius function, its signed global
extension, exact dyadic arithmetic, and the complete proved formalizations of
arXiv:1702.05442 and arXiv:1702.06487v3.  It also exposes claim-level audits
of the two local TeX drafts on Fabius asymptotics and K-fold Thue--Morse
summation, including corrected results and formal counterexamples to their
false claims.  The public surface also includes the exact negative-Laplace
product, its Gamma--zeta periodic correction, and the unconditional corrected
sharp small-argument asymptotic.  Its probability interface also exposes
measure-generic midpoint log-convexity and positive-shift factorial bounds for
unit-interval Laplace moments, with bounded-Fabius specializations.
Its foundational algebra includes finite weighted-moment coefficient
extraction across arbitrary semiring homomorphisms and field-generic Lagrange
evaluation on geometric grids, culminating in module-valued Richardson
exactness at an arbitrary starting index.  Arbitrary finite-node rescale
filters are diagonalized coefficientwise on formal power series, with exact
Gaussian residual multipliers for geometric rows; the recursive Gaussian
coefficients themselves have functorial, symmetric, denominator-free ring
laws.
The geometric Richardson generating-function layer is the exact 3+7 public
surface `geometricRichardsonKernel`, `qPochhammerNormalizedDataSeries`,
`geometricRichardsonTransform`,
`coeff_rescale_qPochhammerSeries_eq_geometricRichardsonKernel`,
`coeff_qPochhammerNormalizedDataSeries`,
`geometricRichardsonTransform_generating`,
`geometricRichardsonTransform_eq_sum_lagrange`,
`geometricLagrangeRichardson_generating`,
`hasSum_geometricRichardsonTransform_mul_pow`, and
`hasSum_geometricLagrangeRichardson_mul_pow`.  The formal convolution and
factorization hold over every commutative ring using total `Ring.inverse`,
without topology or q-regularity.  The canonical Lagrange-row identification,
which makes the comb-interpolation claim `gq:thm:richardson-generating` Exact,
holds over fields for `q ≠ 0`; roots of unity are allowed algebraically, but
colliding nodes do not acquire interpolation exactness, and the repeated-node
case `q = 0`, `n ≥ 2` is excluded.  The analytic `HasSum` pair assumes a
complete normed field, `‖q‖ < 1`, and norm-summability of the normalized data,
with `q ≠ 0` additionally required only for the Lagrange form.
It also exposes the exact Fourier--Legendre expansion of Rvachev's up
function, with absolute uniform convergence on `[-1,1]`, and its translated
monomial representation of the signed global Fabius function on `[0,2]`.
Every finite even Legendre partial sum is also proved to be the unique
least-squares best polynomial approximation in its degree class.
The inverse-dyadic recurrence also has a finite nonrecursive solution as an
explicit weighted sum over ordered compositions.

The reusable integration layer exposes normalized Volterra operators on
arbitrary real normed spaces and, under completeness where required, their
literal-iteration semigroup, strict FTC calculus, and Taylor reconstruction;
the exact polynomial commutators retain the weaker normed-space generality.
Its Fabius specialization gives the complete signed primitive ladder on all
of `ℝ`, the bounded ladder on the maximal range `x ≤ 1`, and finite formulas
for every natural monomial weight.  A separate absolutely-continuous
inverse-pair theorem derives monotonicity and measurable clamped extensions
of both clocks from their strict order equivalence, then packages the full
two-function compact-rectangle identity and its Fabius specialization.

The probability interface also exposes a support-free inverse-CDF transport
principle from an almost-everywhere sublevel identity.  Its compact Fabius
specialization identifies uniform measure transported by the total inverse
with the binary weighted-sum law, and therefore supplies Banach-valued quantile
substitution without repeating a change-of-variables argument for each
statistic.

The regularity layer adds the sharp global shape of the two functions: the
single differential equation `F'(x) = 2 up(2x - 1)` valid on all of `ℝ`, the
optimal Lipschitz constant `2` for both `F` and `up`, strict monotonicity of
`F` on `[0,1]` together with the resulting bijection of `[0,1]` onto itself,
the exact support `(-1,1)` of `up` and its strict unimodality, convexity of
`F` on `(-∞,1/2]` and concavity on `[1/2,∞)`, the effective flatness bound
`F(x) ≤ 2^C(n+1,2) x^n` on `2^n x ≤ 1`, the sharp uniform derivative bounds
`|F^(k)| ≤ 2^C(k+1,2)` with the value attained, and the exact real-analytic
locus: `F` is analytic at `x` if and only if `x ∉ [0,1]`.

The regularity layer also inverts the bijection `F : [0,1] → [0,1]`.  The
inverse is continuous and monotone on all of `ℝ` once totalized by the
endpoint values, and the flatness bounds transport through it into lower
bounds `y ≤ 2^C(n+1,2) · F⁻¹(y)^n`: the inverse is steeper than every root at
the origin, with `F⁻¹(y)/y → ∞` as `y → 0⁺`.

The derivative-distribution layer resolves the exact dyadic cell structure
behind those sharp bounds.  It gives every signed cell profile and midpoint,
the all-order Thue--Morse finite-mixture law for Banach-valued continuous
tests, and every signed natural-power moment in one Boolean-cube formula.  Its
even specialization holds at every derivative order, while positive-order odd
moments vanish.  At every positive derivative order,
`intervalIntegral_comp_normalized_iteratedDeriv_rvachev` gives the symmetric
half-mixture of `up` and `-up` for continuous tests valued in any real Banach
space, and `map_normalized_iteratedDeriv_rvachev_restrict_Icc` upgrades it to
an equality of Borel pushforwards of restricted Lebesgue measure on `[-1,1]`.
At order zero the normalized signed law is instead the unsymmetrized `up` law.
Equality of the Borel pushforwards of the normalized absolute derivative and
`up` on `[-1,1]` separately yields all nonnegative real `rpow` absolute moments
with exact scale `2^(p * C(n+1,2))`, including order and moment zero.  This
layer does not package an `eLpNorm` or general rearrangement-invariant norm
ladder, inverse-Fabius level sets, beta specialization, or spectral theorem.

The small-argument asymptotic layer is completed by closed forms for the
objects that previously existed only as recursions.  The differential
recurrence for the periodic saddle jets is solved: the `n`-th jet is a
harmonic-number constant plus a sum of the first `n+1` derivatives of the
centered periodic correction, weighted by the coefficients of
`∏ k ∈ Finset.Icc 1 n, (X - k)`, that is, by signed Stirling numbers of the
first kind.  The saddle exponent coefficients likewise collapse to one power
of `I` multiplying a jet term and a universal jet-free tail.  Together these
make every coefficient of the all-orders expansion an explicit finite
expression with rational coefficients in `1 / log 2` and the derivatives of
the periodic correction, rather than the output of a recursion.  The
coefficient of `lambda⁻²` is computed in closed form and substituted into
the expansion, so the public surface now carries
`log F(x) = fabiusSharpLambertMain x + A₁(lambda)/lambda +
A₂(lambda)/lambda² + O(lambda⁻³)` with both corrections written out.  See
Part “Small-Argument Asymptotics Research Frontiers” of
`docs/semi-formalized-research-frontiers/semi-formalized-research-frontiers.tex`.

Finally, the canonical bounded Fabius function is proved computable in the
Grzegorczyk sense: a primitive-recursive centered-spline evaluator preserves
computable dyadic names, and the explicit recursive modulus `d(n)=2n` gives
effective uniform continuity.  The same centered splines converge uniformly
on all of `ℝ` to the signed extension with error at most `2⁻ᵖ`, while the
finite binary-reduction telescope through scale `N ≥ 1` converges uniformly
with error at most `2^(1-N)`.

The inverse now has the same full computable-real interface.  A generic
tolerant-bisection layer proves that every computably dyadically approximable
strict monotone bijection of `[0,1]` has a sequentially computable inverse once
a computable positive reciprocal inverse modulus is supplied.  Its certified
three-way comparisons never decide equality: a large signed difference safely
shrinks the bracket, while an inconclusive result already meets the requested
inverse tolerance.  Specializing the construction to `fabiusReal`, clamping
input names to `[0,1]`, and combining it with the logarithmic Delta modulus
proves `fabiusInv_isComputableRealFunction` for every bounded Fabius witness.
This is a computability certificate for the total inverse, not an input-bit
running-time theorem or an exact least endpoint-mass denominator.

The adjacent exact endpoint-mass layer closes that last denominator clause.
`FabiusInverseExactDyadicModulus` has two definitions and ten theorems: its
fixed-order ceiling is least among positive strict integer moduli for the
target `2⁻ʳ`, and both that denominator and its logarithmic composition are
primitive recursive.  The reciprocal `1/n` conclusion remains witness-only,
the value at zero is a totalization convention, and no input-bit running-time
bound is asserted.

The adjacent `EffectiveGapInverse` module has four definitions and four
theorems.  It derives the required inverse modulus, sequential computability,
and effective uniform continuity from computable positive rational lower
bounds for every dyadic forward gap, and proves total computability exactly for
the unit-clamped extension.  Together with `EffectiveMonotoneInverse` (2+6)
and `FabiusInverseComputable` (0+1), this effective-inverse union contains
three modules and seventeen public declarations.

The real Lambert branch layer packages the positive gap between the principal
and lower branches as an explicit bijective coordinate on the open two-branch
interval.  Its finite pairing, inverse-gap, and symmetry modules expose four
definitions and thirty-two theorems: both branch reconstructions (including
the `t = exp gap` coordinate), the inverse bijection, exact ratio, sum, and
product formulas, and the sharp strict sum and product bounds.  The companion
`LambertWBranchGapBernoulli` leaf adds exactly five theorems: absolute
summability of the real Bernoulli exponential generating series on
`|z| < 2 * pi`; the exact complex convergence locus `‖z‖ < 2 * pi`, hence
divergence on and outside its boundary circle; its actual real sum
`z / (exp z - 1)` for `z != 0`; its complex sum as
`(complexExpm1Div z)⁻¹` exactly on that disk, including value `1` at the
removable origin; and the two printed branch-gap series when the positive gap
is below `2 * pi`.  Together the four Lambert gap modules expose four
definitions and thirty-seven theorems, forty-one declarations.  Guide label
`eq:bernoulli-gen` is Exact only under this canonical removable-origin
representation, not as Lean's literal totalized quotient at zero, and no
holomorphy theorem is asserted.  The branch point and zero endpoint are
excluded from the branch series, and no remainder or higher Puiseux claim is
made.

The geometric-uniform moment-polynomial algebra leaf has the exhaustive public
surface of one definition and eight theorems:
`geometricUniformMomentPolynomial`,
`geometricUniformMomentPolynomial_zero`,
`geometricUniformMomentPolynomial_succ`,
`geometricUniformMomentPolynomial_natDegree_le`,
`geometricUniformMomentPolynomial_eval_zero`,
`geometricUniformMomentPolynomial_one`,
`geometricUniformMomentPolynomial_two`,
`geometricUniformMomentPolynomial_three`, and
`geometricUniformMomentPolynomial_four`.  It proves the division-free
residual-product recursion over `ℚ[X]`, the bound `natDegree P_n ≤ n.choose 2`,
the specialization `P_n(0) = 1/(n+1)!`, and the displayed values through
`P_4`.

The companion geometric-uniform moment-polynomial bridge leaf has the
exhaustive public surface of zero definitions and one theorem,
`geometricUniformMomentPolynomial_eval₂_eq_mgf_taylorCoefficient`.  For every
real `q` with `|q| < 1` and every index, it identifies evaluation of the
recursive polynomial by the exact formula
`P_n(q) = ((q;q)_n / (1-q)^n) * (iteratedDeriv n M_q 0 / n!)`, where `M_q` is the genuine
geometric-uniform MGF.  The range includes `q = 0` and negative contractions.

The complex-product companion has the exhaustive public surface of one
definition and three theorems: `geometricUniformComplexMomentProduct`,
`hasProdLocallyUniformly_geometricUniformComplexMomentProduct`,
`differentiable_geometricUniformComplexMomentProduct`, and
`geometricUniformMomentPolynomial_eval₂_eq_complexMomentProduct_taylorCoefficient`.
For every complex `q` with `‖q‖ < 1`, including `q = 0` and negative real
contractions, it constructs the genuine product
`A_q(z) = ∏' j, complexExpm1Div ((1-q) * q^j * z)`, proves locally uniform
convergence on the whole complex plane, proves that the resulting function is
entire, and proves
`P_n(q) = ((q;q)_n / (1-q)^n) * (iteratedDeriv n A_q 0 / n!)`.
For nonreal `q`, this analytic product is not described as a probability MGF.

The exterior reciprocal-germ companion also has the exhaustive public surface
of one definition and two theorems:
`geometricUniformExteriorComplexMomentGerm`,
`analyticAt_geometricUniformExteriorComplexMomentGerm`, and
`geometricUniformMomentPolynomial_eval₂_eq_exteriorComplexMomentGerm_taylorCoefficient`.
For every complex `q` with `1 < ‖q‖`, it defines the actual manuscript germ
`M_q(z) = (A_{q⁻¹}(-z))⁻¹`, proves analyticity at zero, and proves
`P_n(q) = ((q;q)_n / (1-q)^n) * (iteratedDeriv n M_q 0 / n!)`.
The inverse is total in Lean, but only the germ at zero is asserted analytic;
no boundary or global pole statement is included.

The reciprocity companion has the exhaustive public surface of one definition
and five theorems: `geometricUniformComplexMomentGerm`,
`geometricUniformComplexMomentGerm_of_norm_lt_one`,
`geometricUniformComplexMomentGerm_of_one_lt_norm`,
`analyticAt_geometricUniformComplexMomentGerm`,
`geometricUniformComplexMomentGerm_reciprocity`, and
`geometricUniformComplexMomentGerm_moment_convolution`.  It joins the inner
product and exterior reciprocal into the canonical two-regime germ, proves
analyticity at zero away from the unit circle, and for `q ≠ 0`, `‖q‖ ≠ 1`
proves both `M_q(z) M_{q⁻¹}(-z) = 1` as an `EventuallyEq` germ identity and
the exact all-order binomial convolution of its Taylor moments.  The local
statement is essential: the inner product can have zeros away from the
origin, and no unit-circle continuation is asserted.  This makes canonical
label `thm:qF-reciprocity` Exact.

The rational-coefficient companion has the exhaustive public surface of one
definition and four theorems:
`geometricUniformMomentRatFunc`,
`qFactorial_mul_geometricUniformMomentRatFunc`,
`eval_geometricUniformMomentRatFunc_eq_complexMomentProduct_taylorCoefficient`,
`eval_geometricUniformMomentRatFunc_eq_exteriorComplexMomentGerm_taylorCoefficient`,
and `eval_geometricUniformMomentRatFunc_one`.  It packages the common
coefficient as the single `RatFunc ℚ` given by `P_n / [n]_X!`, proves the
global pole-clearing identity `[n]_X! * a_n = P_n`, identifies safe evaluation
of that same rational function with the inner product for `‖q‖ < 1` and the
exterior reciprocal germ for `1 < ‖q‖`, and proves the removable specialization
at `q = 1`, where `[n]_1! = n!`.  It assigns no value at a genuine pole and
asserts no exact pole divisor, unit-circle analytic continuation, or global
holomorphy of the exterior inverse.

The sharp-degree companion has the exhaustive public surface of zero
definitions and three theorems:
`coeff_geometricUniformMomentPolynomial_choose_two`,
`coeff_geometricUniformMomentPolynomial_choose_two_sub_one`, and
`geometricUniformMomentPolynomial_natDegree_eq`.  It identifies the
coefficient at the triangular degree bound with `bernoulli' n / n!`, proves
the displayed subleading coefficient for `2 ≤ n`, and determines the exact
degree: the triangular bound is attained for `n = 1` and even `n`, while odd
`n ≥ 3` misses it by exactly one.  The statements include the `n = 0` and
`n = 1` edge cases and are purely algebraic.

These leaves make the real probability-law normalization and both the inner
complex-disc and exterior complex-germ Taylor normalizations exact.  Together
with the sharp coefficient and degree theorem they make frontier label
`p7:thm:Pn` Exact.  The global rational-function definition, pole-clearing
identity, two regime specializations, and safe value at `q = 1` also make
monograph label `thm:qF-moment-polynomial` Exact by assembly with the
algebraic polynomial leaf.  This is a polynomial continuation statement, not
an analytic continuation of either product through `‖q‖ = 1`.
Label `thm:geometric-uniform-mgf` remains Partial: although coefficient
rationality is now packaged, no public theorem packages the product's
dilation/Mahler law, normalization, formal uniqueness, exact
root-of-unity pole data, or its direct identification with the real MGF or
characteristic function.  The
leading/subleading coefficient and exact-degree claims of
`prop:qF-P-degree-sharp` are exactly the sharp-degree companion's three
theorems, so that label is Exact.

The post-RatFunc union adds exactly two public theorems to
`ProbabilityLaplaceMoments`:
`weightedSumDistribution_real_Ici_eq_rvachevUp_of_nonneg` identifies the
closed survival tail with `rvachevUp` on the whole nonnegative ray, using
atomlessness to pass from the strict tail, and
`integral_pow_weightedSumDistribution_eq_mul_intervalIntegral_rvachevUp`
gives the full-law raw-moment layer-cake formula for every `1 ≤ n`.  Together
with the existing global up/Fabius identifications these make monograph labels
`prop:up-tail` and `cor:up-moments` Exact; no degree-zero instance is inferred
from the positive-degree moment theorem.

The exhaustive public surface of `RvachevLegendreBiorthogonality` is one
definition, `rvachevLegendreAnalysisKernel`, and one theorem,
`rvachevLegendreBiorthogonality`.  For `F : BoundedFabius` satisfying
`IsFabius`, a nonzero natural mesh `M`, and `l ≤ padicValNat 2 M`, the theorem
gives the exact finite Kronecker pairing on the open block `|k| < 2M`.  Thus
`thm:leg-biorthogonality` is Exact.  The broader `thm:leg-Lambda` and
`cor:leg-biorthogonal-matrices` remain incomplete: this leaf supplies neither
the kernel's support, smoothness, parity, origin, Fourier--Bessel, or dyadic
rationality clauses nor the bundled projector and reverse-closure results.

The parity-selected Rvachev synthesis layer exports exactly one definition and
eight theorems.  `IsRvachevSuperconvergentPhase` selects the endpoint phases
`0, 1/2` when `v₂(M)+1` is odd and the quarter phases `1/4, 3/4` when it is
even; `isRvachevSuperconvergentPhase_two_pow_iff` specializes this to endpoint
phases for even dyadic level and quarter phases for odd dyadic level.  The two
quarter-phase monomial theorems, the unified monomial and polynomial theorems,
the physical-coordinate quadrature theorem, and the deconvolved-polynomial and
Appell specializations prove exactness through degree `v₂(M)+1` for every
nonzero natural mesh.  This is stronger than the manuscript's dyadic-only
form.  The predicate names exact real representatives, not all translates
modulo integers, and the API asserts neither uniqueness of the selected phases
nor maximality, positivity, or rationality of the resulting quadrature.

The q-calculus surface further includes finite-prefix infinite-product bounds,
the Heine transformation and q-Gauss summation, a ratio-defined complex-order
q-Pochhammer symbol, general basic-hypergeometric terms with their convergence
criteria, and a division-free recursive q-multinomial coefficient.  These six
modules expose exactly six definitions and thirty theorems; their explicit
strict-contraction, nonvanishing, and denominator hypotheses are retained.

Four companion modules add exactly five definitions and thirty-three theorems.
They prove the degree, monicity, palindromicity, endpoint coefficients, and
division-free mean identity for Gaussian polynomials; define the q-derivative
and both q-exponentials with their product and eigenfunction laws; prove both
directions of Jackson's fundamental theorem and integration by parts; and give
the bilateral-theta product, quasi-periodicity, and exact zero criterion.  The
analytic declarations retain their stated strict-contraction, nonzero-variable,
convergence, and nonvanishing hypotheses.

The next four q-series leaves add twenty theorems and no definitions.  They
give the exact degree, monicity, constant coefficient, and palindromicity of
the universal Gaussian polynomial over `ℕ`; Jacobi's cubic identity in
`HasSum` form; the q-Pochhammer logarithmic derivative and its Lambert-series
form on the unit disc; and differentiation of the complex-order q-Pochhammer
symbol under its explicit strict-contraction and nonzero-nome hypotheses.

Two further division-free algebra leaves add thirteen theorems and no
definitions.  `CyclotomicFactorization` factors `(X;X)_n` and the universal
Gaussian coefficient into cyclotomic polynomials over the stated commutative
ring or integral-domain contexts.  `CentralQBinomialReduction` proves the
sign-pairing and even--odd dissection identities and reduces `[2k,k]_(q²)` to
finite q-Pochhammer products, with the quotient form retaining both explicit
nonvanishing-denominator hypotheses.

Four root-of-unity and q-Catalan companions add one definition and twenty-four
theorems: `CyclotomicDivisibility` 0+3, `PrimitiveRootBlock` 0+3,
`QCatalan` 1+11, and `QLucas` 0+7.  They prove the cyclotomic carry criterion,
complete primitive-root blocks, the q-Lucas theorem over integral domains, and
MacMahon's integral q-Catalan polynomial with its degree and value at one.
QLucas's `two_mul_choose_two` helper is private; the public theorem of that
name belongs to `QChuVandermonde`.

`TwoPhiOneReversal` (1+6) and `QChuVandermonde` (0+5) prove the reflected
finite-product identity, terminating two-phi-one reversal, denominator-cleared
first q-Chu sum, both quotient evaluations, and the second evaluation by
reversal.  Their generic-field nonvanishing assumptions remain explicit;
rational-extension removal of auxiliary hypotheses is not a separate theorem.
`JacobiTwoSquareCount` (0+4) then closes the nonzero two-square count and
instantiates both Lambert kernels from `TwoSquareTheorem`; its product form
retains the even-valuation hypothesis, while both analytic identities hold in
every complete normed field under `‖q‖ < 1`.
The zeta–Lambert tail calculus of the Thue–Morse frontier results is
formalized end to end.  The engine is the Euler log transform: for any
absolutely summable family with all norms below one, over any index type,
`∑ log(1-aᵢ) = -∑_{r≥1} (∑ aᵢʳ)/r`, with branch-free exponential product
forms and the Lambert-series logarithm of the infinite `q`-Pochhammer
product as its geometric instance.  Feeding the Euler product of the sinc
through it gives `lem:logsinc` — `sinc(πx) = exp(-∑ ζ(2r)x^{2r}/r)` on the
unit disk, with the literal logarithmic form for real arguments — and over
the pair index it gives the all-orders expansion of the whole dyadic
product: `Φ(z) = exp(-∑ ζ(2r)4ʳz^{2r}/(r(4ʳ-1)))` on `‖z‖ < 1`, the exact
prefix factorization on `‖z‖ < 2^m`, the certified tail remainder
`(4ζ(2)/3)·x^{2N+2}/((N+1)(1-x²))`, and the exact three-factor
prefix–corrections–tail form of `Φ`.  The even zeta values enter as
elementary series with positivity, antitonicity, the closed evaluations
`ζ(2) = π²/6` and `ζ(4) = π⁴/90`, the Bernoulli form, and agreement with
`riemannZeta`.

The prime-power valuation leaf has no definitions and six theorems.  Besides
the additive and subtraction formulas for row `p ^ m`, it proves that every
entry of row `p ^ m - 1` is a `p`-adic unit and, for exactly
`0 < j < p ^ m`, that
`vₚ ((p ^ m - 2).choose (j - 1)) = vₚ(j)`.  The two dyadic wrappers give the
ordinary comb-weight formula and this endpoint-flat companion.  The strict
upper bound is essential: at `j = p ^ m` the companion binomial coefficient
is outside its row and hence zero.

The spectral q-Pochhammer layer now also exposes a zero-definition,
three-theorem locally uniform outer-product API.  For every complex `q` with
`‖q‖ < 1`, including `q = 0`, the functions
`z ↦ complexQPochhammerInf (z ^ 2 / (k + 1) ^ 2) (q ^ 2)` have a locally
uniform product on all of `ℂ` equal to `geometricSincProduct q`; the other two
theorems are its dyadic Rvachev-product and bounded-Fabius specializations.
This closes the outer normal-convergence clause only.  It does not package the
centered characteristic-function/MGF form, an outside-disk reciprocal
formula, a pole divisor, or the zero--pole exchange of the compound spectral
theorem.

The generalized-product layer also carries every finite natural-linear
identity between admissible exponent sequences to an exact product identity.
For an admissible natural weight `a`, every natural depth `m`, and every
complex `z`, dilation by `2^m` exposes precisely the first `m` sinc layers and
leaves the product for the shifted weight `h ↦ a(h+m)`.  This all-depth
shift--refinement theorem has no frequency restriction; at `m=0` its prefix
is empty and the statement is reflexive.  Natural coefficients are the exact
boundary of this API: it does not promote signed finite differences to an
analytic-germ or pole-cancellation theorem.

The companion `GeneralizedRvachevIdentifiability` module has no public
definitions and exactly six public theorems:
`weightSequence_eq_of_weightedScaleMultiplicity_base_pow_eq`,
`analyticOrderAt_generalizedRvachevProduct_two_pow`,
`exponent_zero_eq_toNat_analyticOrderAt_generalizedRvachevProduct`,
`exponent_succ_eq_toNat_analyticOrderAt_generalizedRvachevProduct`,
`exponentSequence_eq_of_analyticOrderAt_two_pow_eq`, and
`generalizedRvachevProduct_eq_iff`.  The first recovers a cancellative-monoid
weight sequence from its weighted multiplicities at every power of any base
greater than one.  Under the generalized product's exact summability
hypothesis, the remaining results identify the analytic order at `2^n` with
the inclusive exponent prefix, give head and consecutive-difference decoders,
recover the full exponent sequence from all dyadic orders, and make equality
of the entire products equivalent to equality of their exponent sequences.
This is identifiability from the multiplicity/order divisor, not from a bare
zero set or merely the product values at its zero points; those data cannot
distinguish a sequence from its double.  Spectral-zeta, cumulant-sample, and
generalized probability-law identifiability remain outside the facade's
proved surface.

The Perron root `ρ₁` of the arithmetic-mean transfer operator is enclosed by
kernel-checked arithmetic: `0.66126798 ≤ ρ₁ ≤ 0.66134921`, by carrying the
audits' optimized cubic test function through the Collatz–Wielandt bracket
with the two positivity checks discharged by 32-piece subdivided Bernstein
certificates — integer coefficients verified by `ring` normalization, no
Sturm sequences — on a general piecewise-positivity engine for `[0,1]`.

The Newton-interpolation and Jackson-q-beta tail contributes three definitions
and twenty-one theorems.  `NewtonInterpolation` has two definitions and
thirteen theorems: triangular Newton coefficients and polynomials,
interpolation and uniqueness, the divided-difference formula, and its explicit
geometric-grid specialization.  `QBetaIntegral` has one definition and eight
theorems: for `0 < q < 1` and positive arguments it evaluates the Jackson
q-beta integral in infinite-product and q-gamma forms and derives symmetry,
positivity, and both successor recurrences.  The hypotheses are retained
explicitly; no endpoint or `q → 1` limiting theorem is asserted.

Three further q-series modules contribute two definitions and eighteen
theorems.  `GaussianBinomialInteger` (1+10) defines Gaussian coefficients with
integer upper index, proves both q-Pascal recurrences and negative-index
reflection, and derives the reciprocal finite q-binomial series.
`GaussianBinomialComplexOrder` (1+5) uses principal complex powers to extend
the upper index and packages the generalized reciprocal and finite q-binomial
series.  `QPfaffSaalschutz` (0+3) proves the terminating balanced `₃φ₂`
summation algebraically over a field.  The nonzero nome and parameters,
strict-contraction bounds, and finite-product nonvanishing assumptions remain
explicit; no boundary or limiting extension is asserted.

The terminating basic-hypergeometric pair contributes two definitions and
twenty-two theorems.  `TwoPhiOneReversal` (2+12) defines `twoPhiOneFinite` and
`twoPhiOneReflection`; its exhaustive theorem inventory is
`choose_two_add_succ_choose_two`, `finiteQPochhammerIn_sub_eq`,
`finiteQPochhammerIn_reversal_ne_zero`,
`finiteQPochhammerIn_inv_pow_self`, `twoPhiOneReflection_involutive`,
`twoPhiOneFinite_reversal`, `twoPhiOneFinite_reversal_twice`,
`twoPhiOneFinite_eq_sum_twoPhiOneTerm`,
`twoPhiOne_eq_twoPhiOneFinite_inv_pow`, `twoPhiOne_reversal`,
`twoPhiOne_reversal_twice`, and `twoPhiOne_one_eq_twoPhiOneFinite_zero`.
The actual-tsum statement, finite-support bridge, involutive parameter
reflection, and double application make the monograph's
`lem:2phi1-reversal` coverage Exact.  The reversal retains `q,a,c,z ≠ 0` and
nonvanishing of `(q;q)_n`, `(c;q)_n`, and `(q^{1-n}/a;q)_n`; the separate
`n=0` bridge includes `q=0`.

`QChuVandermonde` (0+10) has the exhaustive theorem inventory
`two_mul_choose_two`, `mul_sub_one_eq_mul_sub_add`,
`finiteQPochhammerIn_div_eq_sum_chu`, `q_chu_vandermonde_first`,
`finiteQPochhammerIn_div_eq_sum_chu_second`,
`twoPhiOneFinite_mul_finiteQPochhammerIn_eq_chu_second`,
`q_chu_vandermonde_second`, `q_chu_vandermonde_second_by_reversal`,
`twoPhiOne_q_chu_vandermonde_first`, and
`twoPhiOne_q_chu_vandermonde_second`.  The two actual-tsum wrappers make
`cor:q-chu` Exact on the full displayed rational domain `q ≠ 0`, `A ≠ 0`,
`(q;q)_n ≠ 0`, `(C;q)_n ≠ 0`; the second formula needs neither `C ≠ 0` nor
`(A;q)_n ≠ 0`.  The audit status of `prop:qchu2-by-reversal` is Partial:
the named reversal proof additionally assumes `C ≠ 0` and `(A;q)_n ≠ 0`,
whereas the stronger full-domain finite theorem and actual-tsum wrapper use a
direct denominator-cleared q-Cauchy argument.  Rational continuation and the
cleared commutative-ring extension remain outside the formal API.

`QuantumMultinomial` adds no definitions and exactly five theorems.  It
decomposes tuple antidiagonals, transports Gaussian symmetry to every
semiring, proves q-multinomial coefficients commute with every element that
the nome does, and derives the ordered noncommutative q-multinomial expansion
when `q` commutes with each variable and `x_j * x_i = q * (x_i * x_j)` for
`i < j`.  The result is finite and division-free and requires no ambient
commutativity or analytic convergence premise.

`GaussianBinomialBounds` adds no definitions and exactly six theorems.  It
evaluates Gaussian reciprocity over fields, proves the constant-term lower
bound for nonnegative nomes and the infinite-q-Pochhammer upper bound for real
strict contractions, and transfers these to dimension-dominant two-sided
bounds at every real `Q > 1`.  The index premise `k ≤ n` and the displayed
nonzero, order, and strict-contraction hypotheses remain explicit.

`GaussianBinomialCumulants` has exactly two definitions, `meanAtOne` and
`varAtOne`, and twenty-four theorems.  Its exhaustive theorem inventory is
`meanAtOne_one`, `varAtOne_one`, `meanAtOne_mul`, `varAtOne_mul`,
`meanAtOne_prod`, `varAtOne_prod`, `eval_one_derivative_X_pow`,
`eval_one_derivative_derivative_X_pow`, `eval_one_qInt_X`,
`eval_one_derivative_qInt_X`, `eval_one_derivative_derivative_qInt_X`,
`meanAtOne_qInt_X`, `varAtOne_qInt_X`, `one_sub_X_pow_succ_eq`,
`gaussianBinomial_X_mul_prod_qInt`, `eval_one_gaussianBinomial_X`,
`sum_mean_diff`, `sum_var_diff`, `meanAtOne_gaussianBinomial_X`,
`varAtOne_gaussianBinomial_X`, `eval_one_derivative_gaussianBinomial_X`,
`eval_one_derivative_derivative_gaussianBinomial_X`,
`twelve_mul_secondMoment_gaussianBinomial_eval_one`, and
`twelve_mul_varianceNumerator_gaussianBinomial_eval_one`.  The last three add
the explicit second derivative at one and division-free raw-second-moment and
variance-numerator identities.  The two functionals are total field-valued
definitions, while their product laws assume nonvanishing at one.  The
q-integer and Gaussian closed forms use a characteristic-zero field, and the
Gaussian formulas assume `k ≤ n`; the two cleared identities are total for all
natural `n,k` over every commutative semiring, including above-row zero
extension.  Probability language describes the normalized coefficient
generating polynomial; these declarations prove its algebraic moment
identities and do not construct a separate random variable.

`FinitePrefixThueMorseCollapse` is an exhaustive zero-definition/eight-theorem
leaf.  Its public surface is `Appell.sum_thueMorseSign_mul_eval_poly`,
`sum_thueMorseSign_mul_uncenteredDyadicPrefixAppellPolynomialRat`,
`sum_thueMorseSign_mul_uncenteredDyadicPrefixAppellPolynomialRat_of_lt`,
`sum_thueMorseSign_mul_uncenteredDyadicPrefixAppellPolynomialRat_self`,
`sum_thueMorseSign_mul_centeredDyadicPrefixAppellPolynomialRat`,
`sum_thueMorseSign_mul_centeredDyadicPrefixAppellPolynomialRat_succ`,
`sum_thueMorseSign_mul_centeredDyadicPrefixAppellPolynomialRat_of_lt`, and
`sum_thueMorseSign_mul_centeredDyadicPrefixAppellPolynomialRat_self`.  These
are finite rational coefficient identities, total at depth zero; they add no
analytic generating-function or convergence claim.

`DyadicBoundaryIdentity` is an exhaustive zero-definition/two-theorem leaf.
`prod_complexSinc_prefix_mul_rvachevFourierProduct` clears the finite sinc
prefix against the rescaled product, and
`rvachevFourierProduct_dyadic_boundary` composes that result with the
integer-zero factorization to give the entire denominator-cleared boundary
identity for every natural shell and complex displacement.  No nonvanishing
hypothesis is needed until one passes to a quotient formulation.  These two
upstream API descriptions do not change any source-coverage status.

The probabilistic layer is closed at the level of measures.  The up-measure
`μ_up = up·Leb` satisfies the refinement equation
`μ_up = Uniform[-½,½] ∗ (μ_up ∘ (·/2)⁻¹)` and its iterate, the
measure-level random-tail law, proved by characteristic functions from the
dyadic renormalization of the Fourier product.  The bridge to the random
series `X = ∑ U_k 2^{-k-1}` of the product-probability representation is the
affine identity `μ_up = law(X) ∘ (2·-1)⁻¹` — the fundamental theorem of
calculus for the folded derivative `F' = 2·up(2·-1)`, which exhibits
`y ↦ F((y+1)/2)` as the CDF of `μ_up`.  Through the bridge the refinement
equation becomes the equality-in-law splitting `X ≗ (U + X')/2` of the
random series, and the characteristic function of `X` takes the closed form
`E[e^{itX}] = e^{it/2}·Û(t/(4π))` in the Rvachev Fourier transform.
The finite spline laws — the laws of the first `p` weighted uniform
coordinates, translated by the midpoint correction `2^{-p-1}` and with
CDFs the midpoint-corrected finite CDFs — converge weakly to the
random-series law, by Lévy's continuity theorem with the pointwise
characteristic-function convergence supplied by dominated convergence;
the companion quantitative statement is the all-real uniform CDF bound
`|C_p - F| ≤ 2^{-p}` of the computability module.
-/
