(** Public surface and assumption audit for compact uniform provability. *)

From BoundedPAConsistency Require Import CompactPAUniformProvability.

Import PABoundedCompactPAUniformProvability.

Check compactSelectorPackageFormula.
Check RawCompactSelectorPackageAt.
Check raw_sat_compactSelectorPackageFormula_iff.
Check raw_compactSelectorPackage_zero.
Check raw_compactSelectorPackage_standard.
Check RawRestrictedPAConsistencyProofSuccessor.
Check RawRestrictedPAConsistencyProofSuccessorInAllModels.
Check RawRestrictedPAConsistencyCertificateSuccessor.
Check RawRestrictedPAConsistencyCertificateSuccessorInAllModels.
Check raw_restrictedPAConsistencyProofSuccessor_of_certificate.
Check raw_restrictedPAConsistencyCertificateSuccessor_of_proof.
Check raw_restrictedPAConsistencySuccessor_interfaces_equivalent.
Check raw_codedPAProofOf_standardRestrictedPAConsistencyTarget.
Check raw_restrictedPAConsistencyCertificateSuccessor_standard.
Check raw_compactSelectorPackage_successor.
Check raw_compactSelectorPackages_all.
Check compactUniformRestrictedPAConsistencyProvabilityBodyFormula.
Check compactUniformRestrictedPAConsistencyProvabilityFormula.
Check
  raw_sat_compactUniformRestrictedPAConsistencyProvabilityBodyFormula_iff.
Check raw_sat_compactUniformRestrictedPAConsistencyProvabilityFormula_iff.
Check compactUniformRestrictedPAConsistencyProvabilityFormula_sentence.
Check compactUniformRestrictedPAConsistencyProvabilityFormula_raw_valid.
Check PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_certificate_successor.

Print Assumptions raw_sat_compactSelectorPackageFormula_iff.
Print Assumptions raw_compactSelectorPackage_zero.
Print Assumptions raw_compactSelectorPackage_standard.
Print Assumptions raw_compactSelectorPackages_all.
Print Assumptions
  raw_restrictedPAConsistencySuccessor_interfaces_equivalent.
Print Assumptions raw_codedPAProofOf_standardRestrictedPAConsistencyTarget.
Print Assumptions
  raw_restrictedPAConsistencyCertificateSuccessor_standard.
Print Assumptions
  raw_sat_compactUniformRestrictedPAConsistencyProvabilityFormula_iff.
Print Assumptions
  compactUniformRestrictedPAConsistencyProvabilityFormula_raw_valid.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_certificate_successor.
