(** Audit the simultaneous cross-level, substitution, and V2-final cuts. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedBoundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedBoundary.

Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedKernelCompilers_of_crossLevel_v2_carried.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevelSubstitution_v2_carried_kernel_compilers.
Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedKernelCompilersInAllModels_of_crossLevel_v2_carried.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevelSubstitution_v2_carried_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevelSubstitution_v2_carried_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedKernelCompilers_of_crossLevel_v2_carried.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevelSubstitution_v2_carried_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelSubstitutionV2CarriedKernelCompilersInAllModels_of_crossLevel_v2_carried.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevelSubstitution_v2_carried_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevelSubstitution_v2_carried_kernel_compilers.
