(** Assumption audit for exact native/direct synchronized-row identification. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsIdentification.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsIdentification.

Check RawCoqRestrictedPANativeAxiomRowsSynchronizedLinkAt.
Check
  raw_coqRestrictedPANativeAxiomRowsSynchronizedLink_exists_of_trace_and_inputs.
Check
  raw_coqRestrictedPANativeAxiomRowsSynchronizedLink_exists_of_coherent_inputs.
Check
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_rows_synchronized_link_exists.
Check coqRestrictedPANativeAxiomRowsSigmaDomainTemplate_open.
Check coqRestrictedPANativeAxiomRowsPiDomainTemplate_open.
Check raw_coqRestrictedPANativeAxiomRows_lower_term_code.
Check raw_coqRestrictedPANativeAxiomRows_domain_code.
Check raw_coqRestrictedPANativeAxiomRows_sigma_leaf_code.
Check raw_coqRestrictedPANativeAxiomRows_field_identification.
Check raw_coqRestrictedPANativeAxiomRows_target_identification.
Check coqRestrictedPANativeAxiomRowsFieldTemplate_scoped.
Check coqRestrictedPANativeAxiomRowsFieldTemplate_shift_closed.
Check raw_coqRestrictedPANativeAxiomRows_field_shift_identity.
Check
  raw_coqRestrictedPANativeAxiomRowsGrowingIdentificationOn_of_synchronized_link.

Print Assumptions
  raw_coqRestrictedPANativeAxiomRowsSynchronizedLink_exists_of_trace_and_inputs.
Print Assumptions
  raw_coqRestrictedPANativeAxiomRowsSynchronizedLink_exists_of_coherent_inputs.
Print Assumptions
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_rows_synchronized_link_exists.
Print Assumptions raw_coqRestrictedPANativeAxiomRows_field_identification.
Print Assumptions raw_coqRestrictedPANativeAxiomRows_target_identification.
Print Assumptions raw_coqRestrictedPANativeAxiomRows_field_shift_identity.
Print Assumptions
  raw_coqRestrictedPANativeAxiomRowsGrowingIdentificationOn_of_synchronized_link.
