(** Kernel-facing audit for the complete aligned Imp-I ready-child decision. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeAlignedImpIntroductionReadyChildDecisionCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeAlignedImpIntroductionReadyChildDecisionCompilation.

Check coqRestrictedPADirectImpIntroductionReadyChildAtomic_aligned_view.
Check coqRestrictedPADirectImpIntroductionReadyChildDomain_aligned_view.
Check coqDynamicTruthNativeAlignedImpIntroductionReadyDecisionTemplate.
Check
  raw_dynamicTruthNativeAligned_impIntroduction_readyEvidenceDecision_rebased_of_atomic_and_domain_roots.
Check
  raw_dynamicTruthNativeAligned_impIntroduction_readyChild_evidenceDecision_nested.
Check
  raw_dynamicTruthNativeAligned_impIntroduction_readyChild_evidenceDecision.

Print Assumptions
  coqRestrictedPADirectImpIntroductionReadyChildAtomic_aligned_view.
Print Assumptions
  coqRestrictedPADirectImpIntroductionReadyChildDomain_aligned_view.
Print Assumptions
  raw_dynamicTruthNativeAligned_impIntroduction_readyEvidenceDecision_rebased_of_atomic_and_domain_roots.
Print Assumptions
  raw_dynamicTruthNativeAligned_impIntroduction_readyChild_evidenceDecision_nested.
Print Assumptions
  raw_dynamicTruthNativeAligned_impIntroduction_readyChild_evidenceDecision.
