(** Assumption audit for adequacy-preserving paired code orbits. *)

From BoundedPAConsistency Require Import
  RawCodedCarrierIndexedPairedAdequateCodeOrbitGraph.

Import PABoundedRawCodedCarrierIndexedPairedAdequateCodeOrbitGraph.

Check RawCarrierIndexedPairedAdequateCodeOrbitBaseTotal.
Check RawCarrierIndexedPairedAdequateCodeOrbitSuccessorTotal.
Check RawCarrierIndexedPairedAdequateCodeOrbitAt.
Check carrierIndexedPairedAdequateCodeOrbitExistsFormula.
Check raw_sat_carrierIndexedPairedAdequateCodeOrbitExistsFormula_iff.
Check raw_carrierIndexedPairedAdequateCodeOrbitExists_zero.
Check raw_carrierIndexedPairedAdequateCodeOrbitExists_succ.
Check raw_carrierIndexedPairedAdequateCodeOrbitExists_all.
Check RawCarrierIndexedPairedAdequateCodeOrbitGraphTotal.
Check raw_carrierIndexedPairedAdequateCodeOrbitGraph_total.

Print Assumptions
  raw_sat_carrierIndexedPairedAdequateCodeOrbitExistsFormula_iff.
Print Assumptions raw_carrierIndexedPairedAdequateCodeOrbitExists_all.
Print Assumptions raw_carrierIndexedPairedAdequateCodeOrbitGraph_total.
