(** Assumption audit for eliminating the eight table-extension witnesses. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendExistentialElimination.

Import PABoundedRawCodedFourStateTableAppendExistentialElimination.

Check coqFourStateTableAppendWitnessContext.
Check coqFourStateTableAppendExtensionBodyTemplate.
Check coqFourStateTableAppendModeLookupTemplate.
Check coqFourStateTableAppendFormulaLookupTemplate.
Check coqFourStateTableAppendAssignmentCodeLookupTemplate.
Check coqFourStateTableAppendAssignmentStepLookupTemplate.
Check coqFourStateTableAppendRootBoundTemplate.
Check coqFourStateTableAppendModeDefinedTemplate.
Check coqFourStateTableAppendFormulaDefinedTemplate.
Check coqFourStateTableAppendAssignmentCodeDefinedTemplate.
Check coqFourStateTableAppendAssignmentStepDefinedTemplate.
Check coqFourStateTableAppendNewStateDefinedTemplate.
Check coqFourStateTableAppendNewStateLookupTemplate.
Check coqFourStateTableAppendWitnessTail.
Check coqFourStateTableAppendWitnessContext_success.
Check coqFourStateTableAppendWitnessContext_shape.
Check coqFourStateTableAppendExtensionBodyTemplate_components.
Check coqFourStateTableAppendExtensionComponent_shapes.
Check coqFourStateTableAppendExtensionLookupBound_shapes.
Check coqFourStateTableAppendExtensionDefined_shapes.
Check raw_codedPALocalProofOf_four_state_table_append_extension_assumption.
Check raw_codedPALocalProofOf_four_state_table_append_extension_components.
Check raw_codedPALocalProofOf_four_state_table_append_lookup_components.
Check raw_codedPALocalProofOf_four_state_table_append_defined_components.
Check raw_codedPALocalProofOf_four_state_table_append_new_state_defined.
Check raw_codedPALocalProofOf_four_state_table_append_root_bound.
Check raw_codedPALocalProofOf_four_state_table_append_new_state_lookup.
Check raw_codedPALocalProofOf_four_state_table_append_ex8_elimination.

Print Assumptions coqFourStateTableAppendWitnessContext_success.
Print Assumptions coqFourStateTableAppendWitnessContext_shape.
Print Assumptions coqFourStateTableAppendExtensionBodyTemplate_components.
Print Assumptions coqFourStateTableAppendExtensionComponent_shapes.
Print Assumptions coqFourStateTableAppendExtensionLookupBound_shapes.
Print Assumptions coqFourStateTableAppendExtensionDefined_shapes.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_extension_assumption.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_extension_components.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_lookup_components.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_defined_components.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_new_state_defined.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_root_bound.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_new_state_lookup.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_ex8_elimination.
