(** Assumption and API audit for the direct assumption-rule root. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectAssumptionCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAssumptionCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAssumptionCase.

Check coqRestrictedPADirectAssumptionNaturalStepContext.
Check coqRestrictedPADirectAssumptionEndpointTail.
Check coqRestrictedPADirectAssumption_endpoint_permutation.
Check raw_coqTemplateNestedExContext_inherited.
Check coqRestrictedPADirectAssumptionDeepContext.

Check coqRestrictedPADirectAssumptionCaseTemplate.
Check coqRestrictedPADirectAssumption_case_shape.
Check coqRestrictedPADirectAssumptionContextEqualityTemplate.
Check coqRestrictedPADirectAssumptionConclusionEqualityTemplate.
Check coqRestrictedPADirectAssumptionMembershipTemplate.
Check coqRestrictedPADirectAssumptionOuterContextTruthTemplate.
Check coqRestrictedPADirectAssumptionWitnessContextTruthTemplate.
Check coqRestrictedPADirectAssumptionWitnessFormulaTruthTemplate.
Check coqRestrictedPADirectAssumptionOuterConclusionTruthTemplate.

Check coqRestrictedPADirectAssumptionMembershipTruthLawTemplate.
Check RawCoqRestrictedPADirectAssumptionMembershipTruthLawRoot.
Check coqRestrictedPADirectAssumptionWitnessContextTruthRoot_valid.
Check coqRestrictedPADirectAssumptionConclusionTransportRoot_valid.
Check raw_codedPALocalProofOf_coqRestrictedPADirectAssumptionCase.
Check raw_coqRestrictedPADirectDeepEndpointAssumptionCaseRoot.

Check coqRestrictedPADirectAssumptionDeepAdmissibleTemplate.
Check coqRestrictedPADirectAssumption_strong_step_remaining_shape.
Check coqRestrictedPADirectStrongStepAssumptionDeepEndpointContext.
Check coqRestrictedPADirectStrongStepAssumptionCaseContext.
Check coqRestrictedPADirectStrongStepAssumptionAdmissibleContext.
Check coqRestrictedPADirectStrongStepAssumptionReadyContext.
Check RawCoqRestrictedPADirectAssumptionMembershipTruthLawRootAt.
Check
  RawCoqRestrictedPADirectStrongStepAssumptionMembershipTruthLawRoot.
Check coqRestrictedPADirectAssumptionWitnessContextTruthRootAt_valid.
Check coqRestrictedPADirectAssumptionConclusionTransportRootAt_valid.
Check raw_codedPALocalProofOf_coqRestrictedPADirectAssumptionConclusionAt.
Check raw_coqRestrictedPADirectStrongStepAssumptionCaseImplicationRoot.

Print Assumptions
  coqRestrictedPADirectAssumption_endpoint_permutation.
Print Assumptions raw_coqTemplateNestedExContext_inherited.
Print Assumptions
  coqRestrictedPADirectAssumptionWitnessContextTruthRoot_valid.
Print Assumptions
  coqRestrictedPADirectAssumptionConclusionTransportRoot_valid.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectAssumptionCase.
Print Assumptions
  raw_coqRestrictedPADirectDeepEndpointAssumptionCaseRoot.
Print Assumptions
  coqRestrictedPADirectAssumption_strong_step_remaining_shape.
Print Assumptions
  coqRestrictedPADirectAssumptionWitnessContextTruthRootAt_valid.
Print Assumptions
  coqRestrictedPADirectAssumptionConclusionTransportRootAt_valid.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectAssumptionConclusionAt.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepAssumptionCaseImplicationRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAssumptionCaseAudit.
