(** Strict assumption audit for the exact three-root Eq-E compiler. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationSemanticRootsCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationSemanticRootsCompilation.

Check
  RawCoqRestrictedPADirectEqualityEliminationOpenedCoverageCompilerLawRoot.
Check
  RawCoqRestrictedPADirectEqualityEliminationPairedChildInterfaceRootAt.
Check
  raw_equalityEliminationPairedChildInterfaceRoot_of_openedCoverageCompiler.
Check
  raw_equalityEliminationPairedChildInterface_standardTailCompiler.

Check
  RawCoqRestrictedPADirectEqualityEliminationChildInterfaceRootsAtWitnesses.
Check
  RawCoqRestrictedPADirectEqualityEliminationChildInterfaceRootsStandardTailCompiler.
Check raw_equalityEliminationChildInterfaceRoots_standardTailCompiler.
Check
  raw_equalityEliminationChildInterfaceRootsAtWitnesses_append_stable.

Check RawCoqRestrictedPADirectEqualityEliminationSemanticRootsAtWitnesses.
Check
  RawCoqRestrictedPADirectEqualityEliminationSemanticRootsStandardTailCompiler.
Check raw_equalityEliminationSemanticRootsAtWitnesses_append_stable.
Check
  raw_equalityEliminationSemanticRoots_standardTailCompiler_of_aligned_append_concrete_row.

Print Assumptions
  raw_equalityEliminationPairedChildInterface_standardTailCompiler.
Print Assumptions
  raw_equalityEliminationChildInterfaceRoots_standardTailCompiler.
Print Assumptions
  raw_equalityEliminationSemanticRootsAtWitnesses_append_stable.
Print Assumptions
  raw_equalityEliminationSemanticRoots_standardTailCompiler_of_aligned_append_concrete_row.
