(** Audit for the transport-complete compact native endpoint. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeMasterEndpointWithTransport.

Import
  PABoundedRawCodedDynamicTruthNativeMasterEndpointWithTransport.

Check RawDynamicTruthNativePositiveProofTotalsInAllModels.
Check RawDynamicTruthNativePositiveLocalProofTotalsInAllModels.
Check RawDynamicTruthNativeLocalRootCompilersInAllModels.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels_of_proof_totals.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels_of_local_proof_totals.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels_of_local_root_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_proof_totals.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_local_proof_totals.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_local_root_compilers.

Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels_of_proof_totals.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels_of_local_root_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_proof_totals.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_local_root_compilers.
