(** Audit surface for the exact-Bottom V2 dispatcher integration. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectBottomAdmissibilityAwareDispatcherIntegration.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectBottomAdmissibilityAwareDispatcherIntegration.

Check RawCoqRestrictedPADirectStrongStepBottomCaseImplicationRoot.
Check coqRestrictedPADirectBottomDeepContext_app_witnesses.
Check raw_bottomStrongStepCaseImplicationRoot_of_compact.
Check raw_bottomStrongStepCaseImplicationRoot_surround_witnessed_tail.

Check RawCoqRestrictedPADirectRuleCaseSemanticRootsV2.
Check rawCoqRestrictedPADirectRuleCasesV2_assumption.
Check rawCoqRestrictedPADirectRuleCasesV2_impIntroductionRecursive.
Check rawCoqRestrictedPADirectRuleCasesV2_impIntroductionTruth.
Check rawCoqRestrictedPADirectRuleCasesV2_impElimination.
Check rawCoqRestrictedPADirectRuleCasesV2_bottomElimination.
Check rawCoqRestrictedPADirectRuleCasesV2_orIntroductionLeftRecursive.
Check rawCoqRestrictedPADirectRuleCasesV2_orIntroductionLeftTruth.
Check rawCoqRestrictedPADirectRuleCasesV2_afterBottomElimination.
Check
  raw_coqRestrictedPADirectStrongStepRuleCaseImplicationRoots_of_semantic_roots_v2.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectStrongStep_of_rule_case_semantic_roots_v2.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_rule_case_implication_roots_on_witnessed_tail.

Check RawCoqRestrictedPADirectRuleCaseSemanticRootsV2AfterImpElimination.
Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsV2AfterImpIntroductionTruth.
Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsV2AfterImpIntroductionRecursive.
Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsV2AfterOrIntroductionLeftTruth.
Check RawCoqRestrictedPADirectRuleCaseSemanticRootsV2AfterAssumption.
Check RawCoqRestrictedPADirectRuleCaseSemanticRootsV2AfterOrIntroductionLeft.

Check
  RawCoqRestrictedPADirectRemainingV2AfterImpEliminationStandardTailCompiler.
Check
  RawCoqRestrictedPADirectRemainingV2AfterImpIntroductionTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectRemainingV2AfterImpIntroductionRecursiveStandardTailCompiler.
Check
  RawCoqRestrictedPADirectRemainingV2AfterOrIntroductionLeftTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectRemainingV2AfterAssumptionStandardTailCompiler.
Check RawCoqRestrictedPADirectRemainingRuleCasesV2StandardTailCompiler.

Check
  raw_remainingV2AfterImpEliminationCompiler_of_admissibilityAwareBottom.
Check raw_remainingV2AfterImpIntroductionTruthCompiler_of_selectedImpECore.
Check
  raw_remainingV2AfterImpIntroductionRecursiveCompiler_of_selectedImpIntroductionTruth.
Check
  raw_remainingV2AfterImpIntroductionRecursiveCompiler_of_fixedRowSplit.
Check
  raw_remainingV2AfterOrIntroductionLeftTruthCompiler_of_selectedImpIntroductionRecursive.
Check
  raw_remainingV2AfterAssumptionCompiler_of_selectedOrIntroductionLeftTruth.
Check raw_remainingRuleCasesV2Compiler_of_selectedAssumption.
Check raw_remainingRuleCasesV2Compiler_of_selected_prefix_and_bottom.
Check raw_remainingRuleCasesV2Compiler_of_fixedRowSplit_and_bottom.
Check raw_ruleCaseSemanticRootsV2_on_selected_witnessed_tail_of_remaining.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_remaining_v2_after_orIntroductionLeft.

Print Assumptions
  raw_bottomStrongStepCaseImplicationRoot_surround_witnessed_tail.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepRuleCaseImplicationRoots_of_semantic_roots_v2.
Print Assumptions
  raw_remainingV2AfterImpEliminationCompiler_of_admissibilityAwareBottom.
Print Assumptions
  raw_ruleCaseSemanticRootsV2_on_selected_witnessed_tail_of_remaining.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_remaining_v2_after_orIntroductionLeft.
