(** Audit surface for completed witnessed-context merge transport. *)

From BoundedPAConsistency Require Import
  RawCodedPALocalProofWitnessedContextMergeTransportComplete.

Import PABoundedRawCodedPALocalProofWitnessedContextMergeTransportComplete.

Check RawContextUnitShiftSuffixState.
Check contextUnitShiftSuffixStateTermAt.
Check raw_sat_contextUnitShiftSuffixStateTermAt_iff.
Check raw_contextUnitShiftSuffixState_zero.
Check raw_contextUnitShiftSuffixState_succ.
Check raw_contextUnitShiftSuffixState_all.
Check raw_contextShift_exists_of_all_atomically_adequate.
Check raw_contextShift_target_all_atomically_adequate.

Check RawContextBinderReady.
Check contextBinderReadyTermAt.
Check raw_sat_contextBinderReadyTermAt_iff.
Check raw_contextBinderReady_of_target_all_atomically_adequate.
Check raw_contextBinderReady_cons.
Check raw_contextBinderReady_witnessed_target.

Check RawCodedPALocalProofBinderWeakeningAt.
Check codedPALocalProofBinderWeakeningAtTermAt.
Check raw_sat_codedPALocalProofBinderWeakeningAtTermAt_iff.
Check RawCodedPALocalProofBinderWeakeningBelow.
Check codedPALocalProofBinderWeakeningBelowTermAt.
Check raw_sat_codedPALocalProofBinderWeakeningBelowTermAt_iff.
Check raw_codedPALocalProofBinderWeakening_rootStep.
Check raw_codedPALocalProofBinderWeakeningBelow_all.
Check raw_codedPALocalProofBinderWeakeningAt_all.

Check raw_codedPALocalProof_contextInclusionWeakening_of_binderReady.
Check raw_codedPALocalProofWitnessedContextInclusionWeakening_complete.
Check
  raw_codedPALocalProof_twoWitnessedContexts_commonContext_with_inclusions_complete.
Check raw_codedPALocalProof_twoWitnessedContexts_commonContext_complete.
Check raw_sixFieldMasterOrdinaryProofsCommonContextLift_complete.

Print Assumptions raw_contextShift_exists_of_all_atomically_adequate.
Print Assumptions raw_contextBinderReady_cons.
Print Assumptions raw_codedPALocalProofBinderWeakening_rootStep.
Print Assumptions raw_codedPALocalProofBinderWeakeningBelow_all.
Print Assumptions
  raw_codedPALocalProofWitnessedContextInclusionWeakening_complete.
Print Assumptions
  raw_codedPALocalProof_twoWitnessedContexts_commonContext_with_inclusions_complete.
Print Assumptions
  raw_codedPALocalProof_twoWitnessedContexts_commonContext_complete.
Print Assumptions raw_sixFieldMasterOrdinaryProofsCommonContextLift_complete.
