(** Assumption audit for successor-bound splitting in an appended row. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendRowLtSuccCases.

Import PABoundedRawCodedFourStateTableAppendRowLtSuccCases.

Check raw_templateContextCode_embedPAAxiomWitnesses.
Check raw_fourStateTableAppendRowContext_witnessed_tail_code.
Check raw_fourStateTableAppendRow_combined_witnessed_tail.
Check raw_fourStateTableAppendRowContext_combined_tail_code.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases_eliminate.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_branch_lookup.

Print Assumptions raw_templateContextCode_embedPAAxiomWitnesses.
Print Assumptions raw_fourStateTableAppendRowContext_witnessed_tail_code.
Print Assumptions raw_fourStateTableAppendRow_combined_witnessed_tail.
Print Assumptions raw_fourStateTableAppendRowContext_combined_tail_code.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases_eliminate.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_branch_lookup.
