From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionTransferInstance.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionTransferInstance.

Check coqRestrictedPADirectAssumptionTransferSourceTemplate.
Check coqRestrictedPADirectAssumptionTransferReplacements.
Check coqRestrictedPADirectAssumptionTransferInstanceTemplate.
Check coqRestrictedPADirectAssumptionLeftTraversalTemplate.
Check coqRestrictedPADirectAssumptionRightTraversalTemplate.
Check coqRestrictedPADirectAssumptionRightMembershipWithTablesTemplate.
Check coqRestrictedPADirectAssumptionLeftMembershipWithTablesTemplate.
Check coqRestrictedPADirectAssumptionTransferReplacements_ready.
Check coqRestrictedPADirectAssumptionTransferInstance_shape.

Print Assumptions
  coqRestrictedPADirectAssumptionTransferReplacements_ready.
Print Assumptions coqRestrictedPADirectAssumptionTransferInstance_shape.
