(** API and assumption audit for the full Pi-domain projection transform. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPiDomainProjectionTransformGraph.

Import PABoundedRawCodedDynamicTruthPiDomainProjectionTransformGraph.

Check dynamicTruthPiDomainProjectionFormulaAllCodeTerm.
Check dynamicTruthPiDomainProjectionRepeatedAllCodeTerm.
Check dynamicTruthPiDomainProjectionCodeTerm.
Check dynamicTruthPiDomainProjectionFieldCodeTerm.
Check raw_eval_dynamicTruthPiDomainProjectionFormulaAllCodeTerm.
Check raw_eval_dynamicTruthPiDomainProjectionRepeatedAllCodeTerm.
Check raw_eval_dynamicTruthPiDomainProjectionCodeTerm.
Check raw_eval_dynamicTruthPiDomainProjectionFieldCodeTerm.
Check dynamicTruthPiDomainProjectionFieldCodeTermAt.
Check raw_sat_dynamicTruthPiDomainProjectionFieldCodeTermAt_iff.

Check dynamicTruthPiDomainProjectionFieldTransformGraph.
Check RawDynamicTruthPiDomainProjectionFieldTransformAt.
Check raw_sat_dynamicTruthPiDomainProjectionFieldTransformGraph_iff.
Check RawDynamicTruthPiDomainProjectionFieldTransformTotal.
Check dynamicTruthPiDomainProjectionFieldTransformGraph_raw_total.
Check RawDynamicTruthPiDomainProjectionDirectCompilerTotal.
Check dynamicTruthPiDomainProjectionFieldTransformGraph_raw_proof_total.

Check dynamicTruthPiDomainProjectionPositiveFieldGraph.
Check RawDynamicTruthPiDomainProjectionPositiveFieldAt.
Check raw_sat_dynamicTruthPiDomainProjectionPositiveFieldGraph_iff.
Check RawDynamicTruthPiDomainProjectionPositiveFieldTotal.
Check dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total.
Check RawDynamicTruthPiDomainProjectionOrbitDirectCompilerTotal.
Check
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_adequate_proof_total.
Check
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total_of_orbit_direct_compiler.
Check
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total_of_orbit_interchange.

Print Assumptions raw_eval_dynamicTruthPiDomainProjectionFieldCodeTerm.
Print Assumptions
  raw_sat_dynamicTruthPiDomainProjectionFieldTransformGraph_iff.
Print Assumptions
  dynamicTruthPiDomainProjectionFieldTransformGraph_raw_total.
Print Assumptions
  dynamicTruthPiDomainProjectionFieldTransformGraph_raw_proof_total.
Print Assumptions
  raw_sat_dynamicTruthPiDomainProjectionPositiveFieldGraph_iff.
Print Assumptions
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total.
Print Assumptions
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_adequate_proof_total.
Print Assumptions
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total_of_orbit_interchange.
