(**
  Interface and trust audit for successor-row branch-disjunction compilation.

  The checks below keep visible all three seams: the finite template proof,
  identification with the literal native codes, and compilation over a
  realizable context that is stable under one-place shift.
*)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSuccessorRowBranchDisjunctionCompilation.

Import
  PABoundedRawCodedDynamicTruthSuccessorRowBranchDisjunctionCompilation.

Check templateRightDisjunctionPreserveWitnessFrom.
Check templateRightDisjunctionPreserveWitnessFrom_derives.
Check templateRepeatedExistsDisjunctionFrom.
Check templateRepeatedExistsDisjunctionFrom_derives.
Check templateRepeatedExistsBranchDisjunctionFrom.
Check templateRepeatedExistsBranchDisjunctionFrom_derives.
Check templateRepeatedExistsBranchDisjunctionProof_derives.

Check coqDynamicTruthSigmaSuccessorRowBranchDisjunctionTarget.
Check coqDynamicTruthPiSuccessorRowBranchDisjunctionTarget.
Check coqDynamicTruthSigmaSuccessorRowBranchDisjunctionProof_derives.
Check coqDynamicTruthPiSuccessorRowBranchDisjunctionProof_derives.

Check rawDirect_coqDynamicTruthSigmaBranchDisjunctionTarget_identified.
Check rawDirect_coqDynamicTruthPiBranchDisjunctionTarget_identified.
Check rawDirect_coqDynamicTruthSigmaBranchDisjunctionFormula_identified.
Check rawDirect_coqDynamicTruthPiBranchDisjunctionFormula_identified.

Check RawDynamicTruthSigmaSuccessorRowBranchDisjunctionCompilationInputs.
Check rawDynamicTruthSigmaBranchDisjunction_contextRealizable.
Check rawDynamicTruthSigmaBranchDisjunction_contextSelfShift.
Check rawDynamicTruthSigmaBranchDisjunction_directInputs.
Check rawDynamicTruthSigmaBranchDisjunction_identification.

Check RawDynamicTruthPiSuccessorRowBranchDisjunctionCompilationInputs.
Check rawDynamicTruthPiBranchDisjunction_contextRealizable.
Check rawDynamicTruthPiBranchDisjunction_contextSelfShift.
Check rawDynamicTruthPiBranchDisjunction_directInputs.
Check rawDynamicTruthPiBranchDisjunction_identification.

Check rawDynamicTruthSigmaSuccessorRowBranchDisjunctionImpRoot.
Check rawDynamicTruthPiSuccessorRowBranchDisjunctionImpRoot.
Check raw_codedPALocalProofOf_dynamicTruthSigmaSuccessorRowBranchDisjunctionImp.
Check raw_codedPALocalProofOf_dynamicTruthPiSuccessorRowBranchDisjunctionImp.
Check rawDynamicTruthSigmaSuccessorRowBranchDisjunctionRoot.
Check rawDynamicTruthPiSuccessorRowBranchDisjunctionRoot.
Check raw_codedPALocalProofOf_dynamicTruthSigmaSuccessorRowBranchDisjunction.
Check raw_codedPALocalProofOf_dynamicTruthPiSuccessorRowBranchDisjunction.

Print Assumptions templateRepeatedExistsBranchDisjunctionProof_derives.
Print Assumptions
  coqDynamicTruthSigmaSuccessorRowBranchDisjunctionProof_derives.
Print Assumptions
  coqDynamicTruthPiSuccessorRowBranchDisjunctionProof_derives.
Print Assumptions
  rawDirect_coqDynamicTruthSigmaBranchDisjunctionFormula_identified.
Print Assumptions
  rawDirect_coqDynamicTruthPiBranchDisjunctionFormula_identified.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthSigmaSuccessorRowBranchDisjunctionImp.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthPiSuccessorRowBranchDisjunctionImp.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthSigmaSuccessorRowBranchDisjunction.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthPiSuccessorRowBranchDisjunction.
