(** Kernel-facing audit for the positive guarded-constructor reduction. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativePositiveGuardedConstructorBranchReduction.

Import
  PABoundedRawCodedDynamicTruthNativePositiveGuardedConstructorBranchReduction.

Check
  RawDynamicTruthGuardedConstructorBranchRootsOnWitnessedExtensionsUnderCallerPrefixAt.
Check
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_of_constructor_branch_roots_on_witnessed_extensions.
Check
  RawDynamicTruthNativeAlignedLogicalRootsToGuardedConstructorBranchRootsContinuationUnderCallerPrefix.
Check
  raw_dynamicTruthNativeAlignedLogicalRootsToGuardedCollisionContinuationUnderCallerPrefix_of_constructor_branch_roots.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingPositivePermutedAppendInputConstructorBranchSplitGrowingKernelCompilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingPositivePermutedAppendInputResourceSplitGrowingKernelCompilers_of_constructor_branch_split.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_constructor_branch_split.

Print Assumptions
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_of_constructor_branch_roots_on_witnessed_extensions.
Print Assumptions
  raw_dynamicTruthNativeAlignedLogicalRootsToGuardedCollisionContinuationUnderCallerPrefix_of_constructor_branch_roots.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingPositivePermutedAppendInputResourceSplitGrowingKernelCompilers_of_constructor_branch_split.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_constructor_branch_split.
