(** Assumption audit for cross-trace operation and application functionality. *)

From BoundedPAConsistency Require Import
  RawCodedTermOperationCrossTraceFunctionality
  RawCodedFormulaOperationCrossTraceFunctionality
  RawCodedTemplateTernaryApplicationFunctionality.

Import PABoundedRawCodedTermOperationCrossTraceFunctionality.
Import PABoundedRawCodedFormulaOperationCrossTraceFunctionality.
Import PABoundedRawCodedTemplateTernaryApplicationFunctionality.

Check raw_shiftedIndex_functional.
Check raw_codedTermShiftVariableRow_functional.
Check RawCodedTermShiftIndexFunctionalBelow.
Check raw_codedTermShiftIndexFunctionalBelow_all.
Check raw_codedTermShift_functional.
Check raw_codedTermOpeningVariableRow_functional.
Check RawCodedTermOpeningIndexFunctionalBelow.
Check raw_codedTermOpeningIndexFunctionalBelow_all.
Check raw_codedTermOpening_functional.
Check RawCodedFormulaOperationAtomFunctional.
Check raw_codedFormulaShiftAtom_functional.
Check raw_codedFormulaSubstitutionAtom_functional.

Check RawCodedFormulaOperationIndexFunctionalBelow.
Check raw_codedFormulaOperationIndexFunctionalBelow_all.
Check raw_codedFormulaOperation_functional.
Check raw_codedFormulaShift_functional.
Check raw_codedFormulaSubstitution_functional.
Check raw_codedFormulaSingleSubstitution_functional.

Check raw_codedTernaryApplication_functional.
Check rawTernaryApplicationOutput_unique.
Check rawTernaryApplicationSelectors_agree_on_syntax.
Check RawCodedTernaryApplicationShiftInterchange.
Check RawCodedTernaryApplicationOpeningInterchange.
Check RawCodedFormulaOperationSingleSubstitutionInterchange.
Check RawCodedFormulaOperationProtectiveShiftStable.
Check raw_codedTernaryApplication_operation_interchange.
Check raw_codedTernaryApplication_shift_interchange_on_syntax_of_laws.
Check raw_codedTernaryApplication_opening_interchange_on_syntax_of_laws.
Check rawTernaryApplicationSelector_unit_shift_on_syntax_of_laws.
Check rawTernaryApplicationSelector_single_opening_on_syntax_of_laws.
Check RawCodedTernaryApplicationShiftCommutingOnSyntax.
Check RawCodedTernaryApplicationOpeningCommutingOnSyntax.
Check rawTernaryApplicationSelector_shift_commuting_on_syntax.
Check rawTernaryApplicationSelector_opening_commuting_on_syntax.

Print Assumptions raw_codedTermShift_functional.
Print Assumptions raw_codedTermOpening_functional.
Print Assumptions raw_codedFormulaShiftAtom_functional.
Print Assumptions raw_codedFormulaSubstitutionAtom_functional.
Print Assumptions raw_codedFormulaOperation_functional.
Print Assumptions raw_codedFormulaShift_functional.
Print Assumptions raw_codedFormulaSubstitution_functional.
Print Assumptions raw_codedFormulaSingleSubstitution_functional.
Print Assumptions raw_codedTernaryApplication_functional.
Print Assumptions rawTernaryApplicationOutput_unique.
Print Assumptions raw_codedTernaryApplication_operation_interchange.
Print Assumptions raw_codedTernaryApplication_shift_interchange_on_syntax_of_laws.
Print Assumptions raw_codedTernaryApplication_opening_interchange_on_syntax_of_laws.
Print Assumptions rawTernaryApplicationSelector_unit_shift_on_syntax_of_laws.
Print Assumptions rawTernaryApplicationSelector_single_opening_on_syntax_of_laws.
