(** Audit for opaque-row global traversal reconstruction after append. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendTemplateGlobalTraversalAssembly.

Import
  PABoundedRawCodedFourStateTableAppendTemplateGlobalTraversalAssembly.

Check coqFourStateTableAppendOpenedTemplateGlobalFormula.
Check coqFourStateTableAppendOpenedTemplateGlobalFormula_success.
Check coqFourStateTableAppendOpenedTemplateGlobalRows.
Check coqFourStateTableAppendOpenedTemplateGlobalRowBody.
Check coqFourStateTableAppendOpenedTemplateGlobalRowProduction.
Check coqFourStateTableAppendOpenedTemplateGlobalRows_success.
Check coqFourStateTableAppendOpenedTemplateGlobalRows_shape.
Check coqFourStateTableAppendOpenedTemplateGlobalRowProduction_local_shape.
Check coqFourStateTableAppendOpenedTemplateGlobalFormula_embed.
Check coqFourStateTableAppendOpenedTemplateGlobalFormula_and7_shape.
Check coqFourStateTableAppendOpenedTemplateGlobalFormula_field_shapes.
Check coqFourStateTableAppendOpenedTemplateGlobalFormula_shape.
Check templateTermSubst_template_scoped_fixed.
Check templateTermsSubst_template_scoped_fixed.
Check templateFormulaSubst_template_scoped_fixed.
Check templateTermScopedBool.
Check templateTermsScopedBool.
Check templateFormulaScopedBool.
Check templateTermScopedBool_iff.
Check templateTermsScopedBool_iff.
Check templateFormulaScopedBool_iff.
Check
  coqFourStateTableAppendOpenedLocalRowTemplate_template_scoped_identity.
Check coqFourStateTableAppendTemplateClosedRowProduction_eq_opened.
Check
  raw_codedPAGrowingTemplateLocalProofAt_opened_template_global_rows_of_concrete_row.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_template_global_of_append_rows.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_template_global_of_append_concrete_row.

Print Assumptions coqFourStateTableAppendOpenedTemplateGlobalFormula_embed.
Print Assumptions coqFourStateTableAppendOpenedTemplateGlobalFormula_shape.
Print Assumptions templateFormulaSubst_template_scoped_fixed.
Print Assumptions templateFormulaScopedBool_iff.
Print Assumptions
  coqFourStateTableAppendOpenedLocalRowTemplate_template_scoped_identity.
Print Assumptions coqFourStateTableAppendTemplateClosedRowProduction_eq_opened.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_opened_template_global_rows_of_concrete_row.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_template_global_of_append_rows.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_template_global_of_append_concrete_row.
