From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessQuantifierUnaryChildInterfaceOpenedCoverageSource
  RawCodedRestrictedPADerivationSoundnessQuantifierUnaryChildInterfaceOpenedCoverageCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessQuantifierUnaryChildInterfaceOpenedCoverageSource.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessQuantifierUnaryChildInterfaceOpenedCoverageCompilation.

Check coqRestrictedPAQuantifierUnary_child_interface_agreement.
Check raw_universalElimination_child_interface.
Check raw_existentialIntroduction_child_interface.
Check raw_quantifierUnary_openedCoverageLaw_valid.
Check PA_proves_coqRestrictedPAQuantifierUnaryOpenedCoverageSource.
Check rawDirect_quantifierUnaryOpenedCoverageSource_substitution.

Check raw_quantifierUnaryChildInterfaceRoot_of_openedCoverageCompiler.
Check
  raw_codedPALocalProof_quantifierUnaryOpenedCoverageLaw_on_witnessed_base.
Check RawCoqRestrictedPAQuantifierUnaryChildInterfaceStandardTailCompiler.
Check raw_quantifierUnaryChildInterface_standardTailCompiler.

Check
  RawCoqRestrictedPADirectUniversalEliminationRecursiveChildStandardTailCompiler.
Check raw_universalEliminationRecursiveChild_standardTailCompiler.
Check raw_universalEliminationRecursiveChildAtWitnesses_append_stable.

Check
  RawCoqRestrictedPADirectExistentialIntroductionChildInterfaceLawStandardTailCompiler.
Check raw_existentialIntroductionChildInterfaceLaw_standardTailCompiler.
Check
  raw_existentialIntroductionChildInterfaceLawAtWitnesses_append_stable.
Check RawCoqRestrictedPAQuantifierUnaryChildRootsAtWitnesses.
Check RawCoqRestrictedPAQuantifierUnaryChildRootsStandardTailCompiler.
Check raw_quantifierUnaryChildRootsAtWitnesses_append_stable.
Check raw_quantifierUnaryChildRoots_standardTailCompiler.

Print Assumptions raw_universalElimination_child_interface.
Print Assumptions raw_existentialIntroduction_child_interface.
Print Assumptions raw_quantifierUnary_openedCoverageLaw_valid.
Print Assumptions PA_proves_coqRestrictedPAQuantifierUnaryOpenedCoverageSource.
Print Assumptions rawDirect_quantifierUnaryOpenedCoverageSource_substitution.
Print Assumptions raw_quantifierUnaryChildInterfaceRoot_of_openedCoverageCompiler.
Print Assumptions raw_quantifierUnaryChildInterface_standardTailCompiler.
Print Assumptions raw_universalEliminationRecursiveChild_standardTailCompiler.
Print Assumptions raw_universalEliminationRecursiveChildAtWitnesses_append_stable.
Print Assumptions
  raw_existentialIntroductionChildInterfaceLaw_standardTailCompiler.
Print Assumptions
  raw_existentialIntroductionChildInterfaceLawAtWitnesses_append_stable.
Print Assumptions raw_quantifierUnaryChildRootsAtWitnesses_append_stable.
Print Assumptions raw_quantifierUnaryChildRoots_standardTailCompiler.
