From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionTenWitnessComposition.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionTenWitnessComposition.

Check coqRestrictedPADirectAssumptionNativeMembershipTruthLawTemplate.
Check coqRestrictedPADirectAssumptionFinalWitnessContext.
Check coqRestrictedPADirectAssumptionTenWitnessRoot.
Check coqRestrictedPADirectAssumptionNativeTruth_rename_five_twice.
Check coqRestrictedPADirectAssumption_shifted_context_truth_in.
Check coqRestrictedPADirectAssumption_final_context_body_in.
Check coqRestrictedPADirectAssumption_final_membership_body_in.
Check coqRestrictedPADirectAssumption_final_transfer_source_in.
Check coqRestrictedPADirectAssumptionTenWitnessRoot_derives.

Print Assumptions
  coqRestrictedPADirectAssumptionTenWitnessRoot_derives.
