From BoundedPAConsistency Require Import
  RawCodedRestrictedPASelectedSigmaBottomArbitraryAssignmentRefutation.

Import
  PABoundedRawCodedRestrictedPASelectedSigmaBottomArbitraryAssignmentRefutation.

Check coqRestrictedPASelectedSigmaBottomAssignmentSourceAt.
Check coqRestrictedPASelectedSigmaBottomAssignmentRootRowReplacementsAt.
Check coqRestrictedPASelectedSigmaBottomAssignmentOpenedSigmaBranchAt.
Check
  coqRestrictedPASelectedSigmaBottomAssignmentPrincipalRefutationPA_raw_valid.
Check
  PA_proves_coqRestrictedPASelectedSigmaBottomAssignmentPrincipalRefutation.
Check
  raw_codedPALocalProofOf_selectedSigmaBottomAssignment_refutation_compiled_growing.
Check
  raw_codedPALocalProofOf_selectedSigmaBottomAssignment_template_refutation_compiled_growing.
Check
  raw_codedPALocalProofOf_selectedSigmaBottomCurrentAssignment_refutation_compiled_growing.
Check
  raw_codedPALocalProofOf_selectedSigmaBottomCurrentAssignment_template_refutation_compiled_growing.
Check coqRestrictedPASelectedSigmaBottomCurrentAssignmentSource_shape.
Check
  coqRestrictedPASelectedSigmaBottomCurrentAssignmentAlignedTruth_shape.
Check raw_selectedSigmaBottomCurrentAssignmentSource_aligned_reroot.

Print Assumptions
  coqRestrictedPASelectedSigmaBottomAssignmentPrincipalRefutationPA_raw_valid.
Print Assumptions
  PA_proves_coqRestrictedPASelectedSigmaBottomAssignmentPrincipalRefutation.
Print Assumptions
  raw_codedPALocalProofOf_selectedSigmaBottomAssignment_refutation_compiled_growing.
Print Assumptions
  raw_codedPALocalProofOf_selectedSigmaBottomAssignment_template_refutation_compiled_growing.
Print Assumptions
  raw_codedPALocalProofOf_selectedSigmaBottomCurrentAssignment_refutation_compiled_growing.
Print Assumptions
  raw_codedPALocalProofOf_selectedSigmaBottomCurrentAssignment_template_refutation_compiled_growing.
Print Assumptions raw_selectedSigmaBottomCurrentAssignmentSource_aligned_reroot.
