From BoundedPAConsistency Require Import
  RawCodedDynamicTruthImpGuardedBranchExclusivity.

Import PABoundedRawCodedDynamicTruthImpGuardedBranchExclusivity.

Check dynamicTruthImpGuardedPredecessorStateExclusivityFormula.
Check RawDynamicTruthImpGuardedPredecessorStateExclusiveAt.
Check
  raw_sat_dynamicTruthImpGuardedPredecessorStateExclusivityFormula_iff.
Check dynamicTruthImpFalseLeftGuardedConditionalCellFormula.
Check dynamicTruthImpTrueRightGuardedConditionalCellFormula.
Check raw_sat_dynamicTruthImpFalseLeftGuardedConditionalCellFormula_iff.
Check raw_sat_dynamicTruthImpTrueRightGuardedConditionalCellFormula_iff.
Check dynamicTruthImpFalseLeftGuardedConditionalCellFormula_raw_valid.
Check dynamicTruthImpTrueRightGuardedConditionalCellFormula_raw_valid.
Check PA_proves_dynamicTruthImpFalseLeftGuardedConditionalCellFormula.
Check PA_proves_dynamicTruthImpTrueRightGuardedConditionalCellFormula.
Check rawDynamicTruthImpGuardedPredecessorStateExclusivityCode.
Check rawDynamicTruthImpFalseLeftGuardedConditionalCellCode.
Check rawDynamicTruthImpTrueRightGuardedConditionalCellCode.
Check rawDynamicTruthImpFalseLeftGuardedConditionalCellCode_eq_quoted.
Check rawDynamicTruthImpTrueRightGuardedConditionalCellCode_eq_quoted.
Check
  raw_codedPAProofOf_dynamicTruthImpFalseLeftGuardedConditionalCell.
Check
  raw_codedPAProofOf_dynamicTruthImpTrueRightGuardedConditionalCell.

Print Assumptions
  dynamicTruthImpFalseLeftGuardedConditionalCellFormula_raw_valid.
Print Assumptions
  dynamicTruthImpTrueRightGuardedConditionalCellFormula_raw_valid.
Print Assumptions
  PA_proves_dynamicTruthImpFalseLeftGuardedConditionalCellFormula.
Print Assumptions
  PA_proves_dynamicTruthImpTrueRightGuardedConditionalCellFormula.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthImpFalseLeftGuardedConditionalCell.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthImpTrueRightGuardedConditionalCell.
