From BoundedPAConsistency Require Import
  RawCodedDynamicTruthImpDirectChildAdmissibilityProofCompilation.

Import
  PABoundedRawCodedDynamicTruthImpDirectChildAdmissibilityProofCompilation.

Check RawDynamicTruthImpDirectChildAdmissibilityCoreAt.
Check raw_dynamicTruthImpDirectChild_admissibility_core.
Check dynamicTruthImpDirectChildAdmissibilityCoreFormula.
Check raw_sat_dynamicTruthImpDirectChildAdmissibilityCoreFormula_iff.
Check dynamicTruthImpDirectChildAdmissibilityCoreFormula_sentence.
Check dynamicTruthImpDirectChildAdmissibilityCoreFormula_raw_valid.
Check PA_proves_dynamicTruthImpDirectChildAdmissibilityCoreFormula.
Check coqDynamicTruthImpDirectChildAdmissibilityCoreInstanceTemplate_open.
Check
  coqDynamicTruthImpDirectChildAdmissibilityCoreInstanceTemplate_imp4_shape.
Check
  raw_codedPALocalProofOf_dynamicTruthImpDirectChildAdmissibilityCore_instance_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_dynamicTruthImpDirectChildAdmissibilityCore_instance_on_witnessed_tail_under_prefix.

Print Assumptions raw_dynamicTruthImpDirectChild_admissibility_core.
Print Assumptions dynamicTruthImpDirectChildAdmissibilityCoreFormula_raw_valid.
Print Assumptions PA_proves_dynamicTruthImpDirectChildAdmissibilityCoreFormula.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthImpDirectChildAdmissibilityCore_instance_on_witnessed_tail_under_prefix.
