From BoundedPAConsistency Require Import RawCodedPALocalProofConjunction.

Import PABoundedRawCodedPALocalProofConjunction.

Check raw_codedPALocalProofOf_andE.
Check raw_codedPALocalProofOf_andE1.
Check raw_codedPALocalProofOf_andE2.
Check raw_codedPALocalProofOf_andE11.
Check raw_codedPALocalProofOf_andE12.
Check raw_codedPALocalProofOf_andE21.
Check raw_codedPALocalProofOf_andE22.
Check raw_codedPALocalProofOf_andE121.

Print Assumptions raw_codedPALocalProofOf_andE.
Print Assumptions raw_codedPALocalProofOf_andE1.
Print Assumptions raw_codedPALocalProofOf_andE2.
Print Assumptions raw_codedPALocalProofOf_andE11.
Print Assumptions raw_codedPALocalProofOf_andE12.
Print Assumptions raw_codedPALocalProofOf_andE21.
Print Assumptions raw_codedPALocalProofOf_andE22.
Print Assumptions raw_codedPALocalProofOf_andE121.
