From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaOrGuardedCanonicalThreeRootCompilation.

Module
  PABoundedRawCodedDynamicTruthSigmaOrGuardedCanonicalThreeRootCompilationAudit.

Import
  PABoundedRawCodedDynamicTruthSigmaOrGuardedCanonicalThreeRootCompilation.

Check RawCodedPAStandardWitnessGrowingTemplateFormulaCompilerAt.
Check
  RawCodedPAStandardWitnessGrowingTemplateFormulaOrRefutationCompilerAt.
Check
  raw_codedPAStandardWitnessGrowingTemplateFormulaCompilerAt_of_or_refutation.

Check coqDynamicTruthSigmaOrGuardedCanonicalDomainRootTemplate.
Check coqDynamicTruthSigmaOrGuardedCanonicalCodeRootTemplate.
Check coqDynamicTruthSigmaOrGuardedCanonicalLeftStateRootTemplate.

Check
  RawDynamicTruthSigmaOrGuardedCanonicalIndependentGrowingThreeRootCompilersUnderPrefixAt.
Check
  RawDynamicTruthSigmaOrGuardedCanonicalIndependentGrowingThreeRootOrRefutationCompilersUnderPrefixAt.
Check
  raw_dynamicTruthSigmaOrGuardedCanonical_independentGrowingThreeRootCompilersUnderPrefixAt_of_or_refutation.
Check
  raw_dynamicTruthSigmaOrGuardedCanonical_growingThreeRootCompilerUnderPrefixAt_of_independent.
Check
  raw_dynamicTruthSigmaOrGuardedCanonical_growingFixedProductionCompilerUnderPrefixAt_of_independent_three_roots_or_refutations.

Print Assumptions
  raw_codedPAStandardWitnessGrowingTemplateFormulaCompilerAt_of_or_refutation.
Print Assumptions
  raw_dynamicTruthSigmaOrGuardedCanonical_growingThreeRootCompilerUnderPrefixAt_of_independent.
Print Assumptions
  raw_dynamicTruthSigmaOrGuardedCanonical_growingFixedProductionCompilerUnderPrefixAt_of_independent_three_roots_or_refutations.

End
  PABoundedRawCodedDynamicTruthSigmaOrGuardedCanonicalThreeRootCompilationAudit.
