(** Public surface and assumption audit for the synchronized Or-E source. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageDefinitions
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSource.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageDefinitions.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSource.

Check CoqRestrictedPAOrEliminationChild.
Check coqRestrictedPADirectOrEliminationChildInterfaceTemplate.
Check coqRestrictedPADirectOrEliminationChildInterfacesTemplate.
Check coqRestrictedPADirectOrEliminationOpenedCoverageLawTemplate.
Check RawCoqRestrictedPAOrEliminationChildInterface.
Check raw_orElimination_child_interface_renamed_sat_iff.
Check raw_orElimination_openedCoverageLaw_valid.
Check coqRestrictedPADirectOrEliminationOpenedCoverageSource_reifies.
Check PA_proves_coqRestrictedPADirectOrEliminationOpenedCoverageSource.
Check rawDirect_orEliminationOpenedCoverageSource_substitution.

Print Assumptions raw_orElimination_openedCoverageLaw_valid.
Print Assumptions
  PA_proves_coqRestrictedPADirectOrEliminationOpenedCoverageSource.
Print Assumptions rawDirect_orEliminationOpenedCoverageSource_substitution.
