(** Exact-interface and assumption audit for append traversal assembly. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendGlobalTraversalAssembly.

Import PABoundedRawCodedFourStateTableAppendGlobalTraversalAssembly.

Check raw_codedTemplateFormula_atomically_adequate.
Check raw_codedTemplatePrefix_atomically_adequate.
Check coqFourStateTableAppendWitnessContext_affine.
Check raw_fourStateTableAppendWitnessContext_witnessed_tail_code.
Check
  raw_fourStateTableAppendWitnessContext_witnessed_tail_code_under_prefix.
Check
  raw_fourStateTableAppendRowContext_witnessed_tail_code_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_of_local_on_append_row_context_under_prefix.
Check coqFourStateTableAppendTraversalBodyTemplate.
Check coqFourStateTableAppendGlobalTraversalWitnesses.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_success.
Check templateAnd7First.
Check templateAnd7Second.
Check templateAnd7Third.
Check templateAnd7Fourth.
Check templateAnd7Fifth.
Check templateAnd7Sixth.
Check templateAnd7Seventh.
Check templateUniversalBodyMany.
Check coqFourStateTableAppendOpenedGlobalRowsTemplate.
Check coqFourStateTableAppendOpenedGlobalRowBodyTemplate.
Check coqFourStateTableAppendOpenedGlobalRowProductionTemplate.
Check coqFourStateTableAppendOpenedGlobalRowsTemplate_success.
Check coqFourStateTableAppendOpenedGlobalRowsTemplate_shape.
Check templateTermReplaceParameterAt_embedPATerm.
Check templateFormulaReplaceParameterAt_embedPAFormula.
Check templateTermSubst_embedPATerm_scoped_fixed.
Check templateFormulaSubst_embedPAFormula_scoped_fixed.
Check templateFormulaReplaceParametersDirect_embedPAFormula.
Check
  coqFourStateTableAppendConcreteClosedRowProductionTemplate_embedded_shape.
Check templateFormulaExMany.
Check coqFourStateTableAppendOpenedLocalRowTemplate.
Check
  coqFourStateTableAppendOpenedGlobalRowProductionTemplate_local_shape.
Check coqFourStateTableAppendOpenedLocalRowTemplate_scoped_identity.
Check
  coqFourStateTableAppendConcreteClosedRowProductionTemplate_embedded_eq_opened.
Check templateOpeningSubstAt_rename_succ_at_depth.
Check templateTermReplaceParameterAt_rename_succ.
Check templateFormulaReplaceParameterAt_rename_succ.
Check templateFormulaReplaceParameter_rename_succ.
Check templateParameterBindingsRename.
Check templateFormulaReplaceParametersDirect_rename_succ.
Check templateContextReplaceParametersDirect.
Check templateContextReplaceParametersDirect_shift.
Check templateParameterBindingsShiftMany.
Check templateContextReplaceParametersDirect_shift_many.
Check coqFourStateTableAppendRootFieldBindings.
Check
  coqFourStateTableAppendConcreteGlobalModeLookup_matches_beta_first.
Check
  coqFourStateTableAppendConcreteRootModeLookup_matches_beta_first.
Check
  coqFourStateTableAppendNamedRowModeLookup_matches_concrete_beta_second.
Check coqFourStateTableAppendConcreteGlobalLookup_and4_shape.
Check coqFourStateTableAppendConcreteRootLookup_and4_shape.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_mode_equality.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_root_mode_equality.
Check coqFourStateTableAppendEmbeddedModeProductionMotive.
Check coqFourStateTableAppendEmbeddedModeProductionMotive_open.
Check coqFourStateTableAppendEmbeddedModeProductionMotive_open_row.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_production_of_mode_equality.
Check
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_concrete_global_equality_production.
Check
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_concrete_root_equality_production.
Check RawFourStateTableAppendConcreteGlobalEqualityInputsAt.
Check RawFourStateTableAppendConcreteRootEqualityInputsAt.
Check raw_fourStateTableAppendConcreteRootEqualityInputsAt_of_global.
Check raw_fourStateTableAppendConcreteGlobalEqualityInputsAt_transport.
Check raw_fourStateTableAppendConcreteRootEqualityInputsAt_transport.
Check
  raw_fourStateTableAppendConcreteGlobalEqualityInputsAt_on_witnessed_row_context_under_prefix_of_local_roots.
Check
  raw_fourStateTableAppendConcreteGlobalEqualityInputsAt_on_literal_row_context_under_suffix_and_prefix_of_local_roots.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_of_inherited_local_roots_and_equality_inputs.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_of_inherited_local_roots_under_prefix.
Check raw_codedPAGrowingTemplateLocalProofAt_impI_two.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_implications_on_witnessed_row_context.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_implications_on_literal_row_context_under_suffix.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_implications.
Check rawTemplateContextCodeOnTail_Forall2_eq.
Check raw_codedPAGrowingTemplateLocalProofAt_prefix_code_eq.
Check
  raw_codedPAGrowingTemplateLocalProofAt_prefix_and_conclusion_code_eq.
Check
  raw_codedPAGrowingTemplateLocalProofAt_opened_global_rows_of_concrete_row.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_and7_shape.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_field_shapes.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_shape.
Check
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_traversal_body_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_traversal_body.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_rows.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_concrete_row.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_scoped_concrete_row.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_concrete_global_row_inputs.
Check RawFourStateTableAppendConcreteGlobalRowInputsAt.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_concrete_global_row_input_package.
Check
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_global_sigma_pi_of_append_concrete_global_row_input_packages.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_code_equivalent_row_prefix.

Print Assumptions coqFourStateTableAppendWitnessContext_affine.
Print Assumptions raw_codedTemplateFormula_atomically_adequate.
Print Assumptions raw_codedTemplatePrefix_atomically_adequate.
Print Assumptions raw_fourStateTableAppendWitnessContext_witnessed_tail_code.
Print Assumptions
  raw_fourStateTableAppendWitnessContext_witnessed_tail_code_under_prefix.
Print Assumptions
  raw_fourStateTableAppendRowContext_witnessed_tail_code_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_of_local_on_append_row_context_under_prefix.
Print Assumptions
  coqFourStateTableAppendOpenedGlobalFormulaTemplate_and7_shape.
Print Assumptions
  coqFourStateTableAppendOpenedGlobalFormulaTemplate_field_shapes.
Print Assumptions coqFourStateTableAppendOpenedGlobalRowsTemplate_success.
Print Assumptions coqFourStateTableAppendOpenedGlobalRowsTemplate_shape.
Print Assumptions templateTermReplaceParameterAt_embedPATerm.
Print Assumptions templateFormulaReplaceParameterAt_embedPAFormula.
Print Assumptions templateTermSubst_embedPATerm_scoped_fixed.
Print Assumptions templateFormulaSubst_embedPAFormula_scoped_fixed.
Print Assumptions templateFormulaReplaceParametersDirect_embedPAFormula.
Print Assumptions
  coqFourStateTableAppendConcreteClosedRowProductionTemplate_embedded_shape.
Print Assumptions
  coqFourStateTableAppendOpenedGlobalRowProductionTemplate_local_shape.
Print Assumptions
  coqFourStateTableAppendOpenedLocalRowTemplate_scoped_identity.
Print Assumptions
  coqFourStateTableAppendConcreteClosedRowProductionTemplate_embedded_eq_opened.
Print Assumptions templateOpeningSubstAt_rename_succ_at_depth.
Print Assumptions templateTermReplaceParameterAt_rename_succ.
Print Assumptions templateFormulaReplaceParameterAt_rename_succ.
Print Assumptions templateFormulaReplaceParameter_rename_succ.
Print Assumptions templateFormulaReplaceParametersDirect_rename_succ.
Print Assumptions templateContextReplaceParametersDirect_shift.
Print Assumptions templateContextReplaceParametersDirect_shift_many.
Print Assumptions
  coqFourStateTableAppendConcreteGlobalModeLookup_matches_beta_first.
Print Assumptions
  coqFourStateTableAppendConcreteRootModeLookup_matches_beta_first.
Print Assumptions
  coqFourStateTableAppendNamedRowModeLookup_matches_concrete_beta_second.
Print Assumptions coqFourStateTableAppendConcreteGlobalLookup_and4_shape.
Print Assumptions coqFourStateTableAppendConcreteRootLookup_and4_shape.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_mode_equality.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_root_mode_equality.
Print Assumptions coqFourStateTableAppendEmbeddedModeProductionMotive_open.
Print Assumptions coqFourStateTableAppendEmbeddedModeProductionMotive_open_row.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_production_of_mode_equality.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_concrete_global_equality_production.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_concrete_root_equality_production.
Print Assumptions RawFourStateTableAppendConcreteRootEqualityInputsAt.
Print Assumptions raw_fourStateTableAppendConcreteRootEqualityInputsAt_of_global.
Print Assumptions
  raw_fourStateTableAppendConcreteGlobalEqualityInputsAt_transport.
Print Assumptions
  raw_fourStateTableAppendConcreteRootEqualityInputsAt_transport.
Print Assumptions
  raw_fourStateTableAppendConcreteGlobalEqualityInputsAt_on_witnessed_row_context_under_prefix_of_local_roots.
Print Assumptions
  raw_fourStateTableAppendConcreteGlobalEqualityInputsAt_on_literal_row_context_under_suffix_and_prefix_of_local_roots.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_of_inherited_local_roots_and_equality_inputs.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_of_inherited_local_roots_under_prefix.
Print Assumptions raw_codedPAGrowingTemplateLocalProofAt_impI_two.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_implications_on_witnessed_row_context.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_implications_on_literal_row_context_under_suffix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_global_closed_row_implications.
Print Assumptions rawTemplateContextCodeOnTail_Forall2_eq.
Print Assumptions raw_codedPAGrowingTemplateLocalProofAt_prefix_code_eq.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_prefix_and_conclusion_code_eq.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_opened_global_rows_of_concrete_row.
Print Assumptions coqFourStateTableAppendOpenedGlobalFormulaTemplate_shape.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_traversal_body_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_traversal_body.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_rows.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_concrete_row.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_scoped_concrete_row.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_concrete_global_row_inputs.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_concrete_global_row_input_package.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_global_sigma_pi_of_append_concrete_global_row_input_packages.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_code_equivalent_row_prefix.
