(** Assumption audit for eliminating the eight table-extension witnesses. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendExistentialElimination.

Import PABoundedRawCodedFourStateTableAppendExistentialElimination.

Check coqFourStateTableAppendWitnessContext.
Check coqFourStateTableAppendExtensionBodyTemplate.
Check coqFourStateTableAppendModeLookupTemplate.
Check coqFourStateTableAppendFormulaLookupTemplate.
Check coqFourStateTableAppendAssignmentCodeLookupTemplate.
Check coqFourStateTableAppendAssignmentStepLookupTemplate.
Check coqFourStateTableAppendRootBoundTemplate.
Check coqFourStateTableAppendModeDefinedTemplate.
Check coqFourStateTableAppendFormulaDefinedTemplate.
Check coqFourStateTableAppendAssignmentCodeDefinedTemplate.
Check coqFourStateTableAppendAssignmentStepDefinedTemplate.
Check coqFourStateTableAppendModePreservationTemplate.
Check coqFourStateTableAppendFormulaPreservationTemplate.
Check coqFourStateTableAppendAssignmentCodePreservationTemplate.
Check coqFourStateTableAppendAssignmentStepPreservationTemplate.
Check coqFourStateTableAppendPreservationAtTemplate.
Check coqFourStateTableAppendRowPreservationAtTemplate.
Check coqFourStateTableAppendPreservationCurrentBoundTemplate.
Check coqFourStateTableAppendPreservationOldBoundTemplate.
Check coqFourStateTableAppendPreservationOldLookupTemplate.
Check coqFourStateTableAppendPreservationNewLookupTemplate.
Check coqFourStateTableAppendNewStateDefinedTemplate.
Check coqFourStateTableAppendNewStateLookupTemplate.
Check coqFourStateTableAppendWitnessTail.
Check coqFourStateTableAppendWitnessContext_success.
Check coqFourStateTableAppendWitnessContext_shape.
Check templateContextShiftMany_cons.
Check templateContextShift_app.
Check templateContextShiftMany_app.
Check coqFourStateTableAppendRowPrefix.
Check coqFourStateTableAppendRowContext_affine.
Check templateContextShift_embedPAAxiomWitnesses_fixed.
Check templateContextShiftMany_embedPAAxiomWitnesses_fixed.
Check coqFourStateTableAppendRowContext_witnessed_tail.
Check templateFormulaShiftMany_and.
Check templateFormulaProjection_shift_many.
Check templateAndFirst_shift_many.
Check templateAndSecond_shift_many.
Check templateAnd4First_shift_many.
Check templateAnd4Second_shift_many.
Check templateAnd4Third_shift_many.
Check templateAnd4Fourth_shift_many.
Check templateFormulaShiftMany_and4_shape.
Check coqFourStateTableAppendWitnessContext_shift_many_shape.
Check
  raw_codedPALocalProofOf_four_state_table_append_extension_assumption_shift_many.
Check
  raw_codedPALocalProofOf_four_state_table_append_extension_components_shift_many.
Check coqFourStateTableAppendExtensionBodyTemplate_components.
Check coqFourStateTableAppendExtensionComponent_shapes.
Check coqFourStateTableAppendExtensionLookupBound_shapes.
Check coqFourStateTableAppendExtensionDefined_shapes.
Check coqFourStateTableAppendExtensionPreservation_shapes.
Check coqFourStateTableAppendPreservationAt_successes.
Check coqFourStateTableAppendRowPreservationAt_successes.
Check coqFourStateTableAppendPreservationAt_shapes.
Check templateImp3SecondPremise.
Check templateImp3ThirdPremise.
Check templateImp3Conclusion.
Check templateFormulaMapAnd4.
Check templateFormulaMapAnd4_shape.
Check raw_codedPALocalProofOf_templateImpE3_shared_first_second_and4.
Check
  raw_codedPALocalProofOf_templateImpE3_shared_first_second_and4_under_adequate_head.
Check coqFourStateTableAppendModePreservationAtTemplate.
Check coqFourStateTableAppendFormulaPreservationAtTemplate.
Check coqFourStateTableAppendAssignmentCodePreservationAtTemplate.
Check coqFourStateTableAppendAssignmentStepPreservationAtTemplate.
Check coqFourStateTableAppendRowModePreservationAtTemplate.
Check coqFourStateTableAppendRowFormulaPreservationAtTemplate.
Check coqFourStateTableAppendRowAssignmentCodePreservationAtTemplate.
Check coqFourStateTableAppendRowAssignmentStepPreservationAtTemplate.
Check coqFourStateTableAppendRowPredecessorCurrentBoundTemplate.
Check coqFourStateTableAppendRowPredecessorOldBoundTemplate.
Check coqFourStateTableAppendRowPredecessorOldStateLookupTemplate.
Check coqFourStateTableAppendRowPredecessorNewStateLookupTemplate.
Check coqFourStateTableAppendRowPreservationAt_shapes.
Check coqFourStateTableAppendPredecessorCurrentBoundTemplate.
Check coqFourStateTableAppendPredecessorOldBoundTemplate.
Check coqFourStateTableAppendPredecessorOldStateLookupTemplate.
Check coqFourStateTableAppendPredecessorNewStateLookupTemplate.
Check raw_codedPALocalProofOf_four_state_table_append_extension_assumption.
Check raw_codedPALocalProofOf_four_state_table_append_extension_components.
Check raw_codedPALocalProofOf_four_state_table_append_lookup_components.
Check
  raw_codedPALocalProofOf_four_state_table_append_lookup_components_shift_many.
Check raw_codedPALocalProofOf_four_state_table_append_defined_components.
Check raw_codedPALocalProofOf_four_state_table_append_preservation_components.
Check
  raw_codedPALocalProofOf_four_state_table_append_preservation_components_shift_many.
Check raw_codedPALocalProofOf_four_state_table_append_row_preservation_at.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_state_lookup.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_state_lookup_under_adequate_head.
Check raw_codedPALocalProofOf_four_state_table_append_preservation_at.
Check
  raw_codedPALocalProofOf_four_state_table_append_predecessor_state_lookup.
Check raw_codedPALocalProofOf_four_state_table_append_new_state_defined.
Check raw_codedPALocalProofOf_four_state_table_append_root_bound.
Check raw_codedPALocalProofOf_four_state_table_append_new_state_lookup.
Check
  raw_codedPALocalProofOf_four_state_table_append_new_state_lookup_shift_many.
Check raw_codedPALocalProofOf_four_state_table_append_ex8_elimination.

Print Assumptions coqFourStateTableAppendWitnessContext_success.
Print Assumptions coqFourStateTableAppendWitnessContext_shape.
Print Assumptions templateContextShiftMany_cons.
Print Assumptions templateContextShiftMany_app.
Print Assumptions coqFourStateTableAppendRowContext_affine.
Print Assumptions
  templateContextShiftMany_embedPAAxiomWitnesses_fixed.
Print Assumptions coqFourStateTableAppendRowContext_witnessed_tail.
Print Assumptions templateFormulaShiftMany_and.
Print Assumptions templateFormulaProjection_shift_many.
Print Assumptions templateFormulaShiftMany_and4_shape.
Print Assumptions coqFourStateTableAppendWitnessContext_shift_many_shape.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_extension_assumption_shift_many.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_extension_components_shift_many.
Print Assumptions coqFourStateTableAppendExtensionBodyTemplate_components.
Print Assumptions coqFourStateTableAppendExtensionComponent_shapes.
Print Assumptions coqFourStateTableAppendExtensionLookupBound_shapes.
Print Assumptions coqFourStateTableAppendExtensionDefined_shapes.
Print Assumptions coqFourStateTableAppendExtensionPreservation_shapes.
Print Assumptions coqFourStateTableAppendPreservationAt_successes.
Print Assumptions coqFourStateTableAppendRowPreservationAt_successes.
Print Assumptions coqFourStateTableAppendPreservationAt_shapes.
Print Assumptions templateFormulaMapAnd4_shape.
Print Assumptions
  raw_codedPALocalProofOf_templateImpE3_shared_first_second_and4.
Print Assumptions
  raw_codedPALocalProofOf_templateImpE3_shared_first_second_and4_under_adequate_head.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_extension_assumption.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_extension_components.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_lookup_components.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_lookup_components_shift_many.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_defined_components.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_preservation_components.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_preservation_components_shift_many.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_preservation_at.
Print Assumptions coqFourStateTableAppendRowPreservationAt_shapes.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_state_lookup.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_state_lookup_under_adequate_head.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_preservation_at.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_predecessor_state_lookup.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_new_state_defined.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_root_bound.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_new_state_lookup.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_new_state_lookup_shift_many.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_ex8_elimination.
