(** Audit for ordinary deep closure of the direct strong-prefix body. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectOrdinaryClosure.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrdinaryClosureAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrdinaryClosure.

Check raw_formulaBotCode_deep_closed_from.
Check raw_coqRestrictedPADirectTemplateFormula_deep_closed_from_scope.
Check
  raw_coqRestrictedPAOpaqueDeepClosedFromTemplateScopes_of_ternary_leaf_equations.
Check
  coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyTemplate_scoped.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirect_deep_closed_of_opaque_deep.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirect_substitution_identity_of_opaque_deep.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirect_substitution_identity_of_ternary_leaf_equations.

Print Assumptions
  raw_coqRestrictedPADirectTemplateFormula_deep_closed_from_scope.
Print Assumptions
  raw_coqRestrictedPAOpaqueDeepClosedFromTemplateScopes_of_ternary_leaf_equations.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirect_deep_closed_of_opaque_deep.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirect_substitution_identity_of_ternary_leaf_equations.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrdinaryClosureAudit.
