From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyContinuationCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyContinuationCompilation.

Check raw_threeFieldEqualityEliminationChildren_standardTailCompiler.
Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_eleven_rows_and_equalityChildren.
Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_eleven_rows.
Check
  raw_remainingRuleCasesV2Compiler_of_aligned_thirteen_rows_equalityChildren_and_frontier.
Check
  raw_remainingRuleCasesV2Compiler_of_aligned_thirteen_rows_and_frontier.

Print Assumptions
  raw_threeFieldEqualityEliminationChildren_standardTailCompiler.
Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_eleven_rows_and_equalityChildren.
Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_eleven_rows.
Print Assumptions
  raw_remainingRuleCasesV2Compiler_of_aligned_thirteen_rows_equalityChildren_and_frontier.
Print Assumptions
  raw_remainingRuleCasesV2Compiler_of_aligned_thirteen_rows_and_frontier.
