(** Audit the simultaneous cross-level and V2-final premise reduction. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelV2CarriedBoundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelV2CarriedBoundary.

Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelV2CarriedKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilers_of_v2_carried_resources.
Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelV2CarriedKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilersInAllModels_of_v2_carried_resources.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevel_v2_carried_resources.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilers_of_v2_carried_resources.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilersInAllModels_of_v2_carried_resources.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevel_v2_carried_resources.
