(** Assumption audit for the direct strong-prefix induction shell. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixDirectInductionShell.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixDirectInductionShell.

Check rawCoqRestrictedPADerivationSoundnessPredicateDirectCode.
Check rawCoqRestrictedPADerivationSoundnessUniversalDirectCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixDirectCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongStepDirectCode.
Check
  RawCoqRestrictedPADerivationSoundnessStrongPrefixDirectClosureRemainder.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixDirectClosureInductionData.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessStrongPrefixAllDirect_of_cases.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_strongPrefix_cases_and_finalizer.

Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixDirectClosureInductionData.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_strongPrefix_cases_and_finalizer.
