(** Kernel-facing audit for the native Pi source template. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPiUniversalLeafSourceTemplate.

Import PABoundedRawCodedDynamicTruthPiUniversalLeafSourceTemplate.

Check coqDynamicTruthLowerSigmaAtomTemplate.
Check raw_dynamicTruthPiCoqLowerApplication_iff_sigma.
Check coqDynamicTruthPiDomainLeafTemplate.
Check coqDynamicTruthPiExistentialLeafTemplate.
Check coqDynamicTruthPiBranchesTemplate.
Check coqDynamicTruthPiSuccessorRowTemplate.
Check rawStructural_coqDynamicTruthLowerSigmaAtomTemplate.
Check rawStructural_coqDynamicTruthPiExistentialLeafTemplate.
Check rawStructural_coqDynamicTruthPiBranchesTemplate.
Check rawStructural_coqDynamicTruthPiSuccessorRowTemplate.
Check rawCoqDynamicTruthPiSuccessorRowTemplateCode_eq_native.
Check RawCoqDynamicTruthPiTemplateIdentification.
Check rawStructural_coqDynamicTruthPiSuccessorRowTemplate_identified.
Check coqDynamicTruthPiRestrictedExistentialProjectionFormula.
Check coqDynamicTruthPiRestrictedExistentialProjectionProof.
Check coqDynamicTruthPiRestrictedExistentialProjectionProof_derives.
Check rawStructural_coqDynamicTruthPiRestrictedProjection_identified.
Check coqDynamicTruthPiClosedRestrictedProjectionFormula.
Check coqDynamicTruthPiClosedRestrictedProjectionProof.
Check coqDynamicTruthPiClosedRestrictedProjectionProof_derives.

Print Assumptions rawStructural_coqDynamicTruthPiSuccessorRowTemplate.
Print Assumptions raw_dynamicTruthPiCoqLowerApplication_iff_sigma.
Print Assumptions rawCoqDynamicTruthPiSuccessorRowTemplateCode_eq_native.
Print Assumptions
  coqDynamicTruthPiRestrictedExistentialProjectionProof_derives.
Print Assumptions
  rawStructural_coqDynamicTruthPiRestrictedProjection_identified.
Print Assumptions
  coqDynamicTruthPiClosedRestrictedProjectionProof_derives.
