(** Kernel-facing audit of the native five-field endpoint specialization. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeMasterEndpoint.

Module PABoundedRawCodedDynamicTruthNativeMasterEndpointAudit.

Import PABoundedRawCodedDynamicTruthNativeMasterEndpoint.

Check dynamicTruthNativeSplicedLocalFieldGraph.
Check dynamicTruthNativeSplicedCrossLevelFieldGraph.
Check dynamicTruthNativeSplicedShiftFieldGraph.
Check dynamicTruthNativeSplicedSubstitutionFieldGraph.
Check dynamicTruthNativeSplicedAxiomSoundnessFieldGraph.
Check dynamicTruthNativeSplicedMasterGraph.
Check raw_dynamicTruthNativeSplicedMasterPackageBase.
Check RawDynamicTruthNativeSplicedMasterPositiveComponentSuccessor.
Check RawDynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels.
Check raw_dynamicTruthNativeSplicedMasterPackageSuccessor_of_compiler.
Check raw_dynamicTruthNativeSplicedMasterComponents_of_compiler.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_native_compiler.

Print Assumptions raw_dynamicTruthNativeSplicedMasterPackageBase.
Print Assumptions raw_dynamicTruthNativeSplicedMasterPackageSuccessor_of_compiler.
Print Assumptions raw_dynamicTruthNativeSplicedMasterComponents_of_compiler.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_native_compiler.

End PABoundedRawCodedDynamicTruthNativeMasterEndpointAudit.
