(** Assumption audit for guarded rank-zero callback normalization. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroGuardedCallbackNormalization.

Module
  PABoundedRawCodedDynamicTruthNativeZeroGuardedCallbackNormalizationAudit.

Import
  PABoundedRawCodedDynamicTruthNativeZeroGuardedCallbackNormalization.

Check dynamicTruthImpGuardedPredecessorStateExclusivityFormula_neq_legacy.
Check
  RawDynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnCurrentGuardedHelperContext.
Check
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnCurrentGuardedHelperContext_of_normalized_resources.
Check
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnCurrentGuardedHelperContext_of_branch_roots.

Print Assumptions
  dynamicTruthImpGuardedPredecessorStateExclusivityFormula_neq_legacy.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnCurrentGuardedHelperContext_of_normalized_resources.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnCurrentGuardedHelperContext_of_branch_roots.

End
  PABoundedRawCodedDynamicTruthNativeZeroGuardedCallbackNormalizationAudit.
