(** Audit surface for the context-flexible dependency endpoint. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedTraceProofBoundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedTraceProofBoundary.

Check RawDynamicTruthNativeDependencyOrderedTraceProofKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_trace_proof_kernel_compilers.

Check
  RawDynamicTruthNativeDependencyOrderedDirectBridgeFamilyKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedTraceProofKernelCompilers_of_direct_bridge_family.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_direct_bridge_family.

Check
  RawDynamicTruthNativeDependencyOrderedTraceProofKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedDirectBridgeFamilyKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_trace_proof_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_direct_bridge_family.

Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_trace_proof_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_direct_bridge_family.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_trace_proof_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedTraceProofKernelCompilers_of_direct_bridge_family.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_direct_bridge_family.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_trace_proof_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_direct_bridge_family.
