From BoundedPAConsistency Require Import
  RawCodedRestrictedPATemplateTernaryApplicationCompilation.

Import
  PABoundedRawCodedRestrictedPATemplateTernaryApplicationCompilation.

Check coqRestrictedPATemplateTernaryFirstLifted.
Check coqRestrictedPATemplateTernarySecondLifted.
Check coqRestrictedPATemplateTernaryFirstResult.
Check coqRestrictedPATemplateTernarySecondResult.
Check coqRestrictedPATemplateTernaryApplication.
Check raw_coqRestrictedPATemplateTernary_first_shift.
Check raw_coqRestrictedPATemplateTernary_second_shift.
Check raw_coqRestrictedPATemplateTernaryApplication_trace.
Check raw_coqRestrictedPATemplateTernaryApplication_output.

Print Assumptions raw_coqRestrictedPATemplateTernary_first_shift.
Print Assumptions raw_coqRestrictedPATemplateTernary_second_shift.
Print Assumptions raw_coqRestrictedPATemplateTernaryApplication_trace.
Print Assumptions raw_coqRestrictedPATemplateTernaryApplication_output.
