(** Assumption audit for exact canonical rank-zero global applications. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroCanonicalTraceExactification.

Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalTraceExactification.

Check dynamicTruthZeroInputGlobalSigmaFormula_scoped.
Check dynamicTruthZeroInputGlobalPiFormula_scoped.
Check raw_dynamicTruthZeroInputGlobalSigma_root_closed.
Check raw_dynamicTruthZeroInputGlobalPi_root_closed.
Check dynamicTruthZeroInputGlobalSigmaApplicationFormula.
Check dynamicTruthZeroInputGlobalPiApplicationFormula.
Check dynamicTruthZeroInputGlobalSigmaApplicationFormula_scoped.
Check dynamicTruthZeroInputGlobalPiApplicationFormula_scoped.
Check raw_dynamicTruthZeroInputGlobalSigma_application_standard.
Check raw_dynamicTruthZeroInputGlobalPi_application_standard.
Check raw_dynamicTruthZeroInputGlobal_applications_exact.
Check raw_dynamicTruthZeroInputGlobalSigmaApplication_atomically_adequate.
Check raw_dynamicTruthZeroInputGlobalPiApplication_atomically_adequate.

Print Assumptions dynamicTruthZeroInputGlobalSigmaFormula_scoped.
Print Assumptions dynamicTruthZeroInputGlobalPiFormula_scoped.
Print Assumptions raw_dynamicTruthZeroInputGlobalSigma_root_closed.
Print Assumptions raw_dynamicTruthZeroInputGlobalPi_root_closed.
Print Assumptions dynamicTruthZeroInputGlobalSigmaApplicationFormula_scoped.
Print Assumptions dynamicTruthZeroInputGlobalPiApplicationFormula_scoped.
Print Assumptions raw_dynamicTruthZeroInputGlobalSigma_application_standard.
Print Assumptions raw_dynamicTruthZeroInputGlobalPi_application_standard.
Print Assumptions raw_dynamicTruthZeroInputGlobal_applications_exact.
Print Assumptions
  raw_dynamicTruthZeroInputGlobalSigmaApplication_atomically_adequate.
Print Assumptions
  raw_dynamicTruthZeroInputGlobalPiApplication_atomically_adequate.
