From BoundedPAConsistency Require Import
  RawCodedUniversalClosureAllCarrierTotality.

Import PABoundedRawCodedUniversalClosureAllCarrierTotality.

Check universalClosureOrbitBaseGraph.
Check universalClosureOrbitSuccessorGraph.
Check raw_universalClosureOrbitBase_total.
Check raw_universalClosureOrbitSuccessor_total.
Check raw_carrierIndexedCodeOrbitAt_to_codedUniversalClosure.
Check raw_codedUniversalClosure_exists_all.
Check raw_codedUniversalClosure_exists_unique_all.

Check raw_codedFormulaOperationTraversalRow_source_syntax.
Check raw_codedFormulaOperation_source_well_formed.
Check raw_codedFormulaShift_source_well_formed.
Check rawDirectTemplateFormula_well_formed.

Check
  raw_coqRestrictedPADerivationSoundnessStrongPrefixDirectClosureRemainder_exists.

Print Assumptions raw_codedUniversalClosure_exists_all.
Print Assumptions raw_codedUniversalClosure_exists_unique_all.
Print Assumptions raw_codedFormulaOperation_source_well_formed.
Print Assumptions rawDirectTemplateFormula_well_formed.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessStrongPrefixDirectClosureRemainder_exists.
