(** Audit the five-coordinate call-site dependency boundary. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2Boundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2Boundary.

Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2KernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2KernelCompilers_of_without_axiom_cut.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevelShiftSubstitutionAxiom_canonical_v2_kernel_compilers.
Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2KernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2KernelCompilersInAllModels_of_without_axiom_cut.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevelShiftSubstitutionAxiom_canonical_v2_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevelShiftSubstitutionAxiom_canonical_v2_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2KernelCompilers_of_without_axiom_cut.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevelShiftSubstitutionAxiom_canonical_v2_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionAxiomCanonicalV2KernelCompilersInAllModels_of_without_axiom_cut.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevelShiftSubstitutionAxiom_canonical_v2_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevelShiftSubstitutionAxiom_canonical_v2_kernel_compilers.
