(** Audit for the six-upstream-plus-dynamic-soundness boundary. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedKernelCompilersFromDynamicSoundnessProducer
  RawCodedRestrictedPADynamicSoundnessProducer.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedKernelCompilersFromDynamicSoundnessProducer.
Import PABoundedRawCodedRestrictedPADynamicSoundnessProducer.

Check RawDynamicTruthNativeDependencyOrderedKernelCompilersWithoutFinalSource.
Check RawDynamicTruthNativeDependencyOrderedKernelCompilersWithoutFinalSourceInAllModels.
Check raw_dynamicTruthNativeDependencyOrderedKernelCompilers_of_dynamicSoundnessProducer.
Check raw_dynamicTruthNativeDependencyOrderedKernelCompilersInAllModels_of_dynamicSoundnessProducer.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_kernel_compilers_and_dynamicSoundnessProducer.

Print Assumptions raw_dynamicTruthNativeDependencyOrderedKernelCompilers_of_dynamicSoundnessProducer.
Print Assumptions raw_dynamicTruthNativeDependencyOrderedKernelCompilersInAllModels_of_dynamicSoundnessProducer.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_kernel_compilers_and_dynamicSoundnessProducer.
