(** Assumption audit for guarded rank-zero predecessor compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroGuardedPredecessorCompilation.

Module
  PABoundedRawCodedDynamicTruthNativeZeroGuardedPredecessorCompilationAudit.

Import
  PABoundedRawCodedDynamicTruthNativeZeroGuardedPredecessorCompilation.

Check coqDynamicTruthImpGuardedParentAtomicTemplate_eq_endpoint_shift5.
Check coqDynamicTruthImpGuardedParentDomainTemplate_view.
Check
  coqStrongStepProofEndpointQuantifierBoundedConclusion_shift5_view.
Check raw_coqDynamicTruthImpGuardedParentDomain_eq_endpoint_shift5.
Check coqDynamicTruthImpGuardedFixedDeepPrefix.
Check coqDynamicTruthImpGuardedDeepPrefix_split.
Check rawTemplateContextCodeOnTail_app_finite.
Check
  raw_dynamicTruthImpGuardedParentEndpointRoots_of_template_assumptions.
Check RawDynamicTruthImpGuardedParentBranchRootsAt.
Check RawDynamicTruthImpGuardedSelectedEvidenceTraversalAt.
Check RawDynamicTruthImpGuardedEvidenceRootsAt.
Check RawDynamicTruthImpGuardedGrowingSelectedEvidenceTraversalAt.
Check raw_dynamicTruthImpGuardedParentBranchRoots_transport.
Check
  raw_dynamicTruthImpGuardedEvidenceRoots_on_witnessed_extension_of_traversal.
Check
  raw_dynamicTruthImpGuardedBranchRoots_on_witnessed_extension_of_parent_and_traversal.
Check
  raw_dynamicTruthImpGuardedBranchRoots_on_witnessed_extension_of_parent_and_growing_traversal.
Check RawDynamicTruthImpGuardedBranchRootsAt.
Check
  raw_dynamicTruthImpGuardedPredecessorRoot_on_witnessed_extension_of_branch_roots.
Check raw_dynamicTruthImpGuardedBranchSource_of_zero_normalized.
Check
  raw_dynamicTruthImpGuardedBranchSource_exists_of_zero_normalized.
Check
  raw_dynamicTruthImpGuardedParentBranchRoots_exists_of_zero_normalized_and_template_assumptions.
Check
  RawDynamicTruthNativeLocalZeroGrowingGuardedBranchRootsCompilerOnNormalizedResources.
Check
  RawDynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnNormalizedResources.
Check
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnNormalizedResources_of_branch_roots.

Print Assumptions
  raw_coqDynamicTruthImpGuardedParentDomain_eq_endpoint_shift5.
Print Assumptions
  raw_dynamicTruthImpGuardedParentEndpointRoots_of_template_assumptions.
Print Assumptions
  raw_dynamicTruthImpGuardedParentBranchRoots_exists_of_zero_normalized_and_template_assumptions.
Print Assumptions
  raw_dynamicTruthImpGuardedBranchRoots_on_witnessed_extension_of_parent_and_traversal.
Print Assumptions
  raw_dynamicTruthImpGuardedPredecessorRoot_on_witnessed_extension_of_branch_roots.
Print Assumptions raw_dynamicTruthImpGuardedBranchSource_of_zero_normalized.
Print Assumptions
  raw_dynamicTruthImpGuardedBranchSource_exists_of_zero_normalized.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnNormalizedResources_of_branch_roots.

End
  PABoundedRawCodedDynamicTruthNativeZeroGuardedPredecessorCompilationAudit.
