(** Assumption and exact-slot audit for direct universal elimination. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectUniversalEliminationCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalEliminationCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalEliminationCase.

Check coqRestrictedPADirectUniversalEliminationCaseTemplate.
Check coqRestrictedPADirectUniversalElimination_case_shape.
Check coqRestrictedPADirectUniversalEliminationCodeEqualityTemplate.
Check coqRestrictedPADirectUniversalEliminationSubstitutionTemplate.
Check coqRestrictedPADirectUniversalEliminationFormulaCodeTemplate.
Check coqRestrictedPADirectUniversalEliminationChildEndpointTemplate.
Check coqRestrictedPADirectUniversalEliminationFormulaTerm.
Check coqRestrictedPADirectUniversalEliminationFormulaTruthTemplate.
Check coqRestrictedPADirectUniversalElimination_formula_truth_shape.
Check coqRestrictedPADirectUniversalEliminationResultTruthTemplate.
Check
  coqRestrictedPADirectUniversalEliminationConclusionTransportRootAt_valid.

Check coqRestrictedPADirectUniversalEliminationRecursiveChildLawTemplate.
Check coqRestrictedPADirectUniversalEliminationDynamicTruthLawTemplate.
Check rawTemplateFormula_universalEliminationRecursiveChildLaw_view.
Check rawTemplateFormula_universalEliminationDynamicTruthLaw_view.
Check RawCoqRestrictedPADirectUniversalEliminationRecursiveChildLawRoot.
Check RawCoqRestrictedPADirectUniversalEliminationDynamicTruthLawRoot.

Check coqRestrictedPADirectUniversalEliminationCodeEqualityRootAt_valid.
Check coqRestrictedPADirectUniversalEliminationSubstitutionRootAt_valid.
Check coqRestrictedPADirectUniversalEliminationFormulaCodeRootAt_valid.
Check coqRestrictedPADirectUniversalEliminationChildEndpointRootAt_valid.
Check coqRestrictedPADirectUniversalEliminationTerminalTruthRootAt_valid.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectUniversalEliminationConclusion.
Check raw_coqRestrictedPADirectStrongStepUniversalEliminationCaseRoot.

Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectUniversalEliminationConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepUniversalEliminationCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalEliminationCaseAudit.
