(** Assumption audit for the V2 carried trace-proof compiler. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeFinalV2CarriedTraceProofCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeFinalV2CarriedTraceProofCompilation.

Check RawDynamicTruthNativeFinalV2CarriedTraceResourcesAt.
Check RawDynamicTruthNativeFinalV2CarriedTraceResourcesCompiler.
Check
  raw_dynamicTruthNativeFinalStagedTraceProofCompiler_of_v2_carried_resources.
Check RawDynamicTruthNativeDependencyOrderedV2CarriedKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedTraceProofKernelCompilers_of_v2_carried_resources.
Check
  RawDynamicTruthNativeDependencyOrderedV2CarriedKernelCompilersInAllModels.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_v2_carried_resources.

Print Assumptions
  raw_dynamicTruthNativeFinalStagedTraceProofCompiler_of_v2_carried_resources.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedTraceProofKernelCompilers_of_v2_carried_resources.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_v2_carried_resources.
