From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalGuardedRemainderBridge.

Import
  PABoundedRawCodedDynamicTruthNativeLocalGuardedRemainderBridge.

Check
  raw_dynamicTruthNativeLocalNonConditionalReducedKernelInputsAt_of_current_kernel_tail.
Check
  raw_dynamicTruthNativeLocalNonConditionalReducedKernelInputsAt_of_reduced_staged_without_predecessor.
Check
  raw_dynamicTruthNativeLocalGuardedReducedStagedRootsAt_of_reduced_staged_without_predecessor_and_boolean_and_guarded_predecessor.

Print Assumptions
  raw_dynamicTruthNativeLocalNonConditionalReducedKernelInputsAt_of_current_kernel_tail.
Print Assumptions
  raw_dynamicTruthNativeLocalNonConditionalReducedKernelInputsAt_of_reduced_staged_without_predecessor.
Print Assumptions
  raw_dynamicTruthNativeLocalGuardedReducedStagedRootsAt_of_reduced_staged_without_predecessor_and_boolean_and_guarded_predecessor.
