(** Audit surface for aligned native strong-step logical-root compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeAlignedStrongStepLogicalRootsCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeAlignedStrongStepLogicalRootsCompilation.

Check RawDynamicTruthNativeAlignedStrongStepResourcesCompilerWithPA.
Check rawCoqDynamicTruthAlignedEvidenceDirectSelector.
Check RawDynamicTruthNativeAlignedStrongStepStructuralInputsAt.
Check raw_dynamicTruthNativeAlignedStrongStepStructuralInputs_exists.
Check
  RawDynamicTruthNativeAlignedStrongStepProofResourcesCompilerWithPA.
Check
  RawDynamicTruthNativeAlignedStrongStepGrowingProofResourcesCompilerWithPA.
Check
  RawDynamicTruthNativeAlignedStrongStepAppendProofResourcesCompilerWithPA.
Check
  raw_dynamicTruthNativeAlignedStrongStepResourcesCompilerWithPA_of_proof_resources.
Check
  raw_dynamicTruthNativeAlignedStrongStepGrowingProofResourcesCompilerWithPA_of_append_proof_resources.
Check
  raw_dynamicTruthNativeLocalAlignedGrowingLogicalRootsCompilerOnWitnessedBase_of_strong_step_resources.
Check
  raw_dynamicTruthNativeLocalAlignedGrowingLogicalRootsCompilerOnWitnessedBase_of_growing_proof_resources.

Print Assumptions
  raw_dynamicTruthNativeAlignedStrongStepStructuralInputs_exists.
Print Assumptions
  raw_dynamicTruthNativeAlignedStrongStepResourcesCompilerWithPA_of_proof_resources.
Print Assumptions
  raw_dynamicTruthNativeAlignedStrongStepGrowingProofResourcesCompilerWithPA_of_append_proof_resources.
Print Assumptions
  raw_dynamicTruthNativeLocalAlignedGrowingLogicalRootsCompilerOnWitnessedBase_of_strong_step_resources.
Print Assumptions
  raw_dynamicTruthNativeLocalAlignedGrowingLogicalRootsCompilerOnWitnessedBase_of_growing_proof_resources.
