(** Kernel-facing audit for the native positive axiom-soundness field. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeAxiomSoundnessPositiveGraph.

Import PABoundedRawCodedDynamicTruthNativeAxiomSoundnessPositiveGraph.

(** Exact carrier sentence and its standard fixed-level alignment. *)
Check dynamicTruthNativeAxiomLowerAdmissibleFormula.
Check dynamicTruthNativeAxiomSoundnessCarrierBodyFormula.
Check dynamicTruthNativeAxiomSoundnessCarrierFormula.
Check dynamicTruthNativeAxiomSigmaDomainTemplate.
Check dynamicTruthNativeAxiomPiDomainTemplate.
Check raw_dynamicTruthNativeAxiomSigmaDomain_standard.
Check raw_dynamicTruthNativeAxiomPiDomain_standard.
Check dynamicTruthNativeAxiomSoundnessFixedLevelBodyFormula.
Check dynamicTruthNativeAxiomSoundnessFixedLevelFormula.
Check dynamicTruthNativeAxiomSoundnessCarrierFormula_fixedLevel.
Check dynamicTruthNativeAxiomSoundnessFixedLevelFormula_zero.
Check RawDynamicTruthNativeAxiomSoundnessCarrierAt.
Check raw_sat_dynamicTruthNativeAxiomSoundnessCarrierFormula_iff.
Check RawDynamicTruthNativeAxiomSoundnessFixedLevelAt.
Check raw_sat_dynamicTruthNativeAxiomSoundnessFixedLevelFormula_iff.

(** Genuine standard PA proof and represented proof object. *)
Check raw_dynamicTruthNativeAxiomSoundnessFixedLevel_all.
Check dynamicTruthNativeAxiomSoundnessFixedLevelFormula_raw_valid.
Check PA_proves_dynamicTruthNativeAxiomSoundnessFixedLevelFormula.
Check raw_dynamicTruthNativeAxiomSoundnessFixedLevel_quoted_proof.

(** The represented next-Sigma application is literally [(axiom,0,0)]. *)
Check dynamicTruthNativeAxiomApplicationFirstReplacement.
Check dynamicTruthNativeAxiomApplicationSecondReplacement.
Check dynamicTruthNativeAxiomApplicationThirdReplacement.
Check dynamicTruthNativeAxiomApplicationTermAt.
Check RawDynamicTruthNativeAxiomApplication.
Check raw_sat_dynamicTruthNativeAxiomApplicationTermAt_iff.
Check raw_dynamicTruthNativeAxiomApplication_exists_adequate.
Check standardDynamicTruthNativeAxiomApplication.
Check standardDynamicTruthNativeAxiomApplication_correct_order.
Check raw_dynamicTruthNativeAxiomApplication_standard.
Check raw_dynamicTruthNativeAxiomApplication_fixedLevelSigma_standard.

(** Transparent field-code polynomial and its standard proof. *)
Check dynamicTruthNativeAxiomLowerAdmissibleCodeTerm.
Check dynamicTruthNativeAxiomSoundnessFieldCodeTerm.
Check rawDynamicTruthNativeAxiomLowerAdmissibleCode.
Check rawDynamicTruthNativeAxiomSoundnessFieldCode.
Check raw_eval_dynamicTruthNativeAxiomLowerAdmissibleCodeTerm.
Check raw_eval_dynamicTruthNativeAxiomSoundnessFieldCodeTerm.
Check dynamicTruthNativeAxiomSoundnessFieldCodeTermAt.
Check raw_sat_dynamicTruthNativeAxiomSoundnessFieldCodeTermAt_iff.
Check rawDynamicTruthNativeAxiomSoundnessFieldCode_quoted.
Check rawDynamicTruthNativeAxiomSoundnessFieldCode_quoted_successor_level.
Check rawDynamicTruthNativeAxiomSoundnessFieldCode_standard_proof.

(** Genuine [S p] orbit, native paired successor, and transform trace. *)
Check dynamicTruthNativeAxiomSoundnessInputOrbitGraph.
Check RawDynamicTruthNativeAxiomSoundnessInputOrbitAt.
Check raw_sat_dynamicTruthNativeAxiomSoundnessInputOrbitGraph_iff.
Check raw_sat_dynamicTruthNativeAxiomSoundnessInputOrbitGraph_standard_iff.
Check dynamicTruthNativeAxiomSoundnessSuccessorBodyGraph.
Check raw_sat_dynamicTruthNativeAxiomSoundnessSuccessorBodyGraph_iff.
Check dynamicTruthNativeAxiomSoundnessFieldTransformGraph.
Check RawDynamicTruthNativeAxiomSoundnessFieldTransformAt.
Check raw_sat_dynamicTruthNativeAxiomSoundnessFieldTransformGraph_iff.
Check raw_dynamicTruthNativeAxiomSoundnessFieldTransformAt_exposes_rows.
Check rawDynamicTruthNativeAxiomSoundnessFieldCode_atomically_adequate.
Check RawDynamicTruthNativeAxiomSoundnessFieldTransformTotalOnAdequate.
Check dynamicTruthNativeAxiomSoundnessFieldTransformGraph_raw_total_on_adequate.

(** Output-first positive graph and the exact nonstandard compiler seam. *)
Check dynamicTruthNativeAxiomSoundnessPositiveGraph.
Check RawDynamicTruthNativeAxiomSoundnessPositiveAt.
Check raw_sat_dynamicTruthNativeAxiomSoundnessPositiveGraph_iff.
Check RawDynamicTruthNativeAxiomSoundnessPositiveAdequateTotal.
Check dynamicTruthNativeAxiomSoundnessPositiveGraph_raw_adequate_total.
Check RawDynamicTruthNativeAxiomSoundnessPositiveTotal.
Check dynamicTruthNativeAxiomSoundnessPositiveGraph_raw_total.
Check RawDynamicTruthNativeAxiomSoundnessProofCompiler.
Check RawDynamicTruthNativeAxiomSoundnessPositiveProofTotal.
Check dynamicTruthNativeAxiomSoundnessPositiveGraph_raw_proof_total_of_compiler.

(** Assumption reports make the standard proof/nonstandard seam explicit. *)
Print Assumptions raw_dynamicTruthNativeAxiomSigmaDomain_standard.
Print Assumptions raw_dynamicTruthNativeAxiomApplication_fixedLevelSigma_standard.
Print Assumptions raw_sat_dynamicTruthNativeAxiomSoundnessCarrierFormula_iff.
Print Assumptions PA_proves_dynamicTruthNativeAxiomSoundnessFixedLevelFormula.
Print Assumptions raw_dynamicTruthNativeAxiomSoundnessFixedLevel_quoted_proof.
Print Assumptions rawDynamicTruthNativeAxiomSoundnessFieldCode_standard_proof.
Print Assumptions raw_sat_dynamicTruthNativeAxiomSoundnessFieldTransformGraph_iff.
Print Assumptions raw_dynamicTruthNativeAxiomSoundnessFieldTransformAt_exposes_rows.
Print Assumptions dynamicTruthNativeAxiomSoundnessPositiveGraph_raw_adequate_total.
Print Assumptions dynamicTruthNativeAxiomSoundnessPositiveGraph_raw_proof_total_of_compiler.
