(** Assumption and interface audit for dynamic coded-context truth. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicContextTruthSelector.

Import PABoundedRawCodedDynamicContextTruthSelector.

Check RawDynamicContextAllSigmaWithTables.
Check dynamicContextAllSigmaWithTablesTermAt.
Check RawDynamicTernaryFormulaSemantics.
Check raw_sat_dynamicContextAllSigmaWithTablesTermAt_iff.

Check RawDynamicContextAllSigma.
Check dynamicContextAllSigmaTermAt.
Check dynamicContextAllSigmaFormula.
Check raw_sat_dynamicContextAllSigmaTermAt_iff.
Check raw_sat_dynamicContextAllSigmaFormula_iff.

Check dynamicContextTruthTraversalBody.
Check dynamicContextTruthLiveIndexBody.
Check dynamicContextTruthHeadLookupBody.
Check rawDynamicContextSigmaApplicationCode.
Check rawDynamicContextAllSigmaWithTablesCode.
Check rawDynamicContextFormulaEx5Code.
Check rawDynamicContextAllSigmaCode.

Check raw_dynamicContext_quotedTerm_syntax.
Check raw_dynamicContextSigmaApplication_trace.
Check raw_dynamicContextSigmaApplication_atomically_adequate.
Check raw_dynamicContextSigmaApplication_deep_closed_from_nine.
Check raw_dynamicContextTraversalBody_deep_closed_from_eight.
Check raw_dynamicContextLiveIndexBody_deep_closed_from_eight.
Check raw_dynamicContextHeadLookupBody_deep_closed_from_nine.
Check raw_dynamicContextAllSigmaWithTablesCode_deep_closed_from_seven.
Check raw_dynamicContextAllSigmaCode_deep_closed.
Check raw_dynamicContextAllSigmaCode_atomically_adequate.
Check raw_dynamicContextAllSigmaApplicationSelector_exists.

Print Assumptions raw_sat_dynamicContextAllSigmaTermAt_iff.
Print Assumptions raw_sat_dynamicContextAllSigmaFormula_iff.
Print Assumptions raw_dynamicContextSigmaApplication_deep_closed_from_nine.
Print Assumptions raw_dynamicContextAllSigmaCode_deep_closed.
Print Assumptions raw_dynamicContextAllSigmaApplicationSelector_exists.
