(** Kernel-facing audit for unconditional synchronized carried consistency. *)

From PAFiniteBasisReduction Require Import
  HierarchyReduction CanonicalSelectorPA FiniteBetaCoding.
From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeFinalUnifiedSynchronizedCarriedConsistency.

Module
  PABoundedRawCodedDynamicTruthNativeFinalUnifiedSynchronizedCarriedConsistencyAudit.

Import PAHierarchyReduction.
Import PACanonicalSelectorPA.
Import PAFiniteBetaCoding.
Import
  PABoundedRawCodedDynamicTruthNativeFinalUnifiedSynchronizedCarriedConsistency.

Check
  raw_dynamicTruthNativeFinalDirectBottomGrowth_of_unified_synchronized_compiled.
Check RawDynamicTruthNativeFinalUnifiedSynchronizedCarriedConsistencyAt.
Check rawDynamicTruthNativeFinalUnifiedCarried_lower_level.
Check rawDynamicTruthNativeFinalUnifiedCarried_upper_level.
Check rawDynamicTruthNativeFinalUnifiedCarried_direct_level.
Check rawDynamicTruthNativeFinalUnifiedCarried_native_link.
Check rawDynamicTruthNativeFinalUnifiedCarried_closure_remainder.
Check rawDynamicTruthNativeFinalUnifiedCarried_consistency.
Check
  raw_dynamicTruthNativeFinalStagedGraphTrace_unified_synchronized_carried_consistency_exists.

Print Assumptions
  raw_dynamicTruthNativeFinalDirectBottomGrowth_of_unified_synchronized_compiled.
Print Assumptions
  raw_dynamicTruthNativeFinalStagedGraphTrace_unified_synchronized_carried_consistency_exists.

End
  PABoundedRawCodedDynamicTruthNativeFinalUnifiedSynchronizedCarriedConsistencyAudit.
