(**
  Assumption audit for the nineteen-witness synchronized-row composition.

  In particular, the two final theorems below must depend only on the
  explicit [deepRoot] derivability premise; opening and closing the finite
  existential packages does not add any logical axiom.
*)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsWitnessComposition.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsWitnessComposition.

Check coqRestrictedPANativeAxiomRowsShiftedBounded_shape.
Check coqRestrictedPANativeAxiomRowsShiftedAdequate_shape.
Check coqRestrictedPANativeAxiomRowsTarget_rename_9_5.
Check coqRestrictedPANativeAxiomRowsTarget_rename_14_5.
Check coqRestrictedPANativeAxiomRowsAxiomTraversalRoot_derives.
Check coqRestrictedPANativeAxiomRowsTarget_total_open_ready.
Check coqRestrictedPANativeAxiomRowsOpenedTargetRoot_derives.
Check coqRestrictedPANativeAxiomRowsTargetWitnessesRoot_derives.
Check coqRestrictedPANativeAxiomRowsAdequacyWitnessesRoot.
Check coqRestrictedPANativeAxiomRowsBoundedWitnessesRoot.
Check coqRestrictedPANativeAxiomRowsAllWitnessesRoot.
Check coqRestrictedPANativeAxiomRowsAllWitnessesRoot_derives.
Check coqRestrictedPANativeAxiomRowsLawTemplate.
Check coqRestrictedPANativeAxiomRowsLawRoot.
Check coqRestrictedPANativeAxiomRowsLawRoot_derives.

Print Assumptions coqRestrictedPANativeAxiomRowsShiftedBounded_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsShiftedAdequate_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsTarget_rename_9_5.
Print Assumptions coqRestrictedPANativeAxiomRowsTarget_rename_14_5.
Print Assumptions coqRestrictedPANativeAxiomRowsAxiomTraversalRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsTarget_total_open_ready.
Print Assumptions coqRestrictedPANativeAxiomRowsOpenedTargetRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsTargetWitnessesRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsAllWitnessesRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsLawRoot_derives.
