From BoundedPAConsistency Require Import
  RawCodedRestrictedPASelectedSigmaBottomSevenCaseReduction.

Module
  PABoundedRawCodedRestrictedPASelectedSigmaBottomSevenCaseReductionAudit.

Import
  PABoundedRawCodedRestrictedPASelectedSigmaBottomSevenCaseReduction.

Check rawCoqRestrictedPASelectedSigmaBottomApplicationCode.
Check rawCoqRestrictedPASelectedSigmaBottomAssumptionContextCode.
Check RawCoqRestrictedPASelectedSigmaBottomExposedRowAt.
Check raw_coqRestrictedPASelectedSigmaBottom_exposed_row_of_native_link.

Check rawDynamicTruthLocalSigmaBranches_right_disjunction.
Check rawDynamicTruthLocalSigmaOr_branch_in_branches.
Check RawCoqRestrictedPASelectedSigmaBottomAppliedBranchesAt.
Check rawCoqRestrictedPASelectedSigmaBottomAppliedBranches.
Check rawCoqRestrictedPASelectedSigmaBottom_or_application_in_branches.
Check RawCoqRestrictedPASelectedSigmaBottomSevenCaseProofSupportAt.
Check raw_coqRestrictedPASelectedSigmaBottom_refutation_of_seven_cases.

Check RawCoqRestrictedPASelectedSigmaBottomSevenCaseProofCompiler.
Check
  raw_coqRestrictedPASelectedSigmaBottomRefutationRootCompiler_of_seven_cases.

Check
  RawDynamicTruthNativeFinalSelectedSigmaBottomSevenCaseProofCompiler.
Check
  raw_dynamicTruthNativeFinalSelectedSigmaBottomRefutationRootCompiler_of_seven_cases.

Print Assumptions
  raw_coqRestrictedPASelectedSigmaBottom_exposed_row_of_native_link.
Print Assumptions
  raw_coqRestrictedPASelectedSigmaBottom_refutation_of_seven_cases.
Print Assumptions
  raw_coqRestrictedPASelectedSigmaBottomRefutationRootCompiler_of_seven_cases.
Print Assumptions
  raw_dynamicTruthNativeFinalSelectedSigmaBottomRefutationRootCompiler_of_seven_cases.

End
  PABoundedRawCodedRestrictedPASelectedSigmaBottomSevenCaseReductionAudit.
