(** Assumption and exact-slot audit for direct right conjunction
    elimination. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectAndEliminationRightCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationRightCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationRightCase.

Check coqRestrictedPADirectAndEliminationRightCaseTemplate.
Check coqRestrictedPADirectAndEliminationRight_case_shape.
Check coqRestrictedPADirectAndEliminationRightResultFormulaTerm.
Check coqRestrictedPADirectAndEliminationRightConclusionEqualityTemplate.
Check coqRestrictedPADirectAndEliminationRightFormulaCodeTemplate.
Check coqRestrictedPADirectAndEliminationRightChildEndpointTemplate.

Check coqRestrictedPADirectAndEliminationRightRecursiveChildLawTemplate.
Check coqRestrictedPADirectAndEliminationRightDynamicTruthLawTemplate.
Check
  coqRestrictedPADirectAndEliminationRight_conclusion_motive_result.
Check RawCoqRestrictedPADirectAndEliminationRightRecursiveChildLawRoot.
Check RawCoqRestrictedPADirectAndEliminationRightDynamicTruthLawRoot.

Check
  coqRestrictedPADirectAndEliminationRightConclusionEqualityRootAt_valid.
Check coqRestrictedPADirectAndEliminationRightFormulaCodeRootAt_valid.
Check coqRestrictedPADirectAndEliminationRightChildEndpointRootAt_valid.
Check
  coqRestrictedPADirectAndEliminationRightConclusionTransportRootAt_valid.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectAndEliminationRightConclusion.
Check raw_coqRestrictedPADirectStrongStepAndEliminationRightCaseRoot.

Print Assumptions
  coqRestrictedPADirectAndEliminationRightConclusionTransportRootAt_valid.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectAndEliminationRightConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepAndEliminationRightCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationRightCaseAudit.
