(** Authoritative audit of the selected guarded rank-zero source boundary. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroGuardedSelectedSourceCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeZeroGuardedSelectedSourceCompilation.

Check RawDynamicTruthNativeZeroGuardedSelectedFixedSourceResources.
Check RawDynamicTruthNativeZeroGuardedFixedSourceCompiler.
Check
  raw_dynamicTruthNativeZeroGuardedSelectedFixedSourceResources_of_compiler.
Check
  raw_dynamicTruthNativeLocalZeroGuardedCollisionFixedResourcesCompilerOnNormalizedResources_of_selected_fixed_sources.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedSelectedFixedSourceSplitGrowingKernelCompilers.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedFixedSourceCompilerSplitGrowingKernelCompilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedSelectedFixedSourceSplitGrowingKernelCompilers_of_fixed_source_compiler.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_selected_fixed_sources.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingSplitGrowingKernelCompilers_of_selected_fixed_sources.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedSelectedFixedSourceSplitGrowingKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedFixedSourceCompilerSplitGrowingKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedSelectedFixedSourceSplitGrowingKernelCompilersInAllModels_of_fixed_source_compilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels_of_selected_fixed_sources.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels_of_fixed_source_compilers.

Print Assumptions
  raw_dynamicTruthNativeZeroGuardedSelectedFixedSourceResources_of_compiler.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGuardedCollisionFixedResourcesCompilerOnNormalizedResources_of_selected_fixed_sources.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedSelectedFixedSourceSplitGrowingKernelCompilers_of_fixed_source_compiler.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_selected_fixed_sources.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingSplitGrowingKernelCompilers_of_selected_fixed_sources.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedSelectedFixedSourceSplitGrowingKernelCompilersInAllModels_of_fixed_source_compilers.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels_of_selected_fixed_sources.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels_of_fixed_source_compilers.
