(** Audit surface for the shared aligned And-E truth compilers. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectAndEliminationAlignedTruthProduction.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationAlignedTruthProductionAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationAlignedTruthProduction.

Check raw_directFormulaStandardTailCompilerAt_of_rerooted_append_concrete_row.

Check CoqRestrictedPADirectAndEliminationProjection.
Check CoqAndEliminationLeftProjection.
Check CoqAndEliminationRightProjection.
Check coqRestrictedPADirectAndEliminationReadyContextFor.
Check coqRestrictedPADirectAndEliminationResultFormulaTermFor.
Check coqRestrictedPADirectAndEliminationFormulaCodeTemplateFor.
Check coqRestrictedPADirectAndEliminationFormulaTruthTemplateFor.
Check coqRestrictedPADirectAndEliminationResultTruthTemplateFor.
Check coqRestrictedPADirectAndEliminationDynamicTruthLawTemplateFor.
Check coqRestrictedPADirectAndEliminationDynamicTruthLawTemplateFor_left.
Check coqRestrictedPADirectAndEliminationDynamicTruthLawTemplateFor_right.

Check
  RawCoqRestrictedPADirectAndEliminationResultTruthStandardTailCompilerFor.
Check
  RawCoqRestrictedPADirectAndEliminationDynamicTruthStandardTailCompilerFor.
Check coqRestrictedPADirectAndElimination_mode_zero_result_rows_stable.
Check coqRestrictedPADirectAndEliminationReadyContextFor_app_witnesses.
Check raw_andElimination_mode_zero_result_source_aligned.
Check
  raw_andEliminationDynamicTruthStandardTailCompilerFor_of_result_truth.
Check
  raw_andEliminationDynamicTruthStandardTailCompilerFor_of_aligned_append_concrete_row.

Check
  RawCoqRestrictedPADirectAndEliminationLeftDynamicTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectAndEliminationRightDynamicTruthStandardTailCompiler.
Check
  raw_andEliminationLeftDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_andEliminationRightDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  RawCoqRestrictedPADirectAndEliminationDynamicTruthStandardTailCompilers.
Check
  raw_andEliminationDynamicTruthStandardTailCompilers_of_aligned_append_concrete_rows.

Check RawCoqRestrictedPADirectAndEliminationDynamicTruthRoots.
Check RawCoqRestrictedPADirectAndEliminationDynamicTruthRootsAtWitnesses.
Check
  RawCoqRestrictedPADirectAndEliminationDynamicTruthRootsStandardTailCompiler.
Check
  raw_andEliminationLeftDynamicTruthLawRoot_surround_witnessed_tail.
Check
  raw_andEliminationRightDynamicTruthLawRoot_surround_witnessed_tail.
Check raw_andEliminationDynamicTruthRootsAtWitnesses_append_stable.
Check
  raw_andEliminationDynamicTruthRootsStandardTailCompiler_of_standalone.
Check
  raw_andEliminationDynamicTruthRootsStandardTailCompiler_of_aligned_append_concrete_rows.

Print Assumptions
  raw_directFormulaStandardTailCompilerAt_of_rerooted_append_concrete_row.
Print Assumptions
  coqRestrictedPADirectAndElimination_mode_zero_result_rows_stable.
Print Assumptions raw_andElimination_mode_zero_result_source_aligned.
Print Assumptions
  raw_andEliminationDynamicTruthStandardTailCompilerFor_of_result_truth.
Print Assumptions
  raw_andEliminationDynamicTruthStandardTailCompilerFor_of_aligned_append_concrete_row.
Print Assumptions
  raw_andEliminationLeftDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_andEliminationRightDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_andEliminationDynamicTruthStandardTailCompilers_of_aligned_append_concrete_rows.
Print Assumptions
  raw_andEliminationLeftDynamicTruthLawRoot_surround_witnessed_tail.
Print Assumptions
  raw_andEliminationRightDynamicTruthLawRoot_surround_witnessed_tail.
Print Assumptions
  raw_andEliminationDynamicTruthRootsAtWitnesses_append_stable.
Print Assumptions
  raw_andEliminationDynamicTruthRootsStandardTailCompiler_of_standalone.
Print Assumptions
  raw_andEliminationDynamicTruthRootsStandardTailCompiler_of_aligned_append_concrete_rows.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationAlignedTruthProductionAudit.
