(** Compatibility umbrella for the localized opened Or-E law proof. *)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapes
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageDisjunctionChildSemanticView
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageLeftBranchSemanticView
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageRightBranchSemanticView
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageIndexedValidity.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageLawValidity.

(** Preserve every historical unqualified name while preventing kernel
    checking of one child view from expanding either neighboring branch. *)
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapes.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageDisjunctionChildSemanticView.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageLeftBranchSemanticView.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageRightBranchSemanticView.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageIndexedValidity.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageLawValidity.
