From BoundedPAConsistency Require Import RawCodedFormulaShiftTotality.

Import PABoundedRawCodedFormulaShiftTotality.

Check raw_codedTermShift_variable_exists.
Check raw_codedTermShift_succ.
Check raw_codedTermShift_add.
Check raw_codedTermShift_mul.
Check RawCodedTermShiftTotalBelow.
Check codedTermShiftTotalBelowTermAt.
Check raw_sat_codedTermShiftTotalBelowTermAt_iff.
Check RawCodedTermShiftTotalWithin.
Check codedTermShiftTotalWithinTermAt.
Check raw_sat_codedTermShiftTotalWithinTermAt_iff.
Check raw_codedTermShiftTotalWithin_all.
Check raw_codedTermShift_exists_of_syntax_realizable.
Check raw_codedFormulaShift_eq_exists_of_term_syntax.
Check raw_codedFormulaShift_bot_exists.
Check RawCodedFormulaShiftCompositional.
Check RawCodedFormulaShiftTotalBelow.
Check codedFormulaShiftTotalBelowTermAt.
Check raw_sat_codedFormulaShiftTotalBelowTermAt_iff.
Check raw_codedFormulaShiftTotalBelow_all.
Check raw_codedFormulaShift_exists_of_atomically_adequate.
Check raw_codedFormulaUnitShift_exists_of_atomically_adequate.

Print Assumptions raw_sat_codedTermShiftTotalBelowTermAt_iff.
Print Assumptions raw_codedTermShiftTotalWithin_all.
Print Assumptions raw_codedTermShift_exists_of_syntax_realizable.
Print Assumptions raw_sat_codedFormulaShiftTotalBelowTermAt_iff.
Print Assumptions raw_codedFormulaShiftTotalBelow_all.
Print Assumptions raw_codedFormulaUnitShift_exists_of_atomically_adequate.
