(** Audit the bottom-free V2 continuation adapter. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyContinuationCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyContinuationCompilation.

Check
  raw_remainingRuleCasesV2Compiler_of_aligned_thirteen_rows_and_five_frontiers.

Print Assumptions
  raw_remainingRuleCasesV2Compiler_of_aligned_thirteen_rows_and_five_frontiers.
