(** Kernel audit for the compiled table-based universal-leaf field proof. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthUniversalLeafProofCompilation.

Module PABoundedRawCodedDynamicTruthUniversalLeafProofCompilationAudit.

Import PABoundedRawCodedDynamicTruthUniversalLeafProofCompilation.

Check rawCoqDynamicTruthLowerPiDirectAtomTemplateCode.
Check rawDirect_coqDynamicTruthLowerPiAtomTemplate.
Check rawDirect_coqDynamicTruthSigmaUniversalLeafTemplate.
Check RawCoqDynamicTruthSigmaDirectTemplateIdentification.
Check rawDirect_coqDynamicTruthSigmaRestrictedProjection_identified.

Check rawCoqDynamicTruthSigmaRestrictedProjectionCertificate.
Check raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedProjection.
Check
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedProjection_identified.

Check coqDynamicTruthSigmaRowEnvironmentArity.
Check coqDynamicTruthSigmaRestrictedUniversalFieldFormula.
Check coqDynamicTruthSigmaRestrictedUniversalFieldProof.
Check coqDynamicTruthSigmaRestrictedUniversalFieldProof_derives.
Check rawTemplateRepeatedAllCode.
Check rawDirectTemplateFormula_repeatedForall.
Check rawCoqDynamicTruthSigmaRestrictedUniversalFieldCode.
Check
  rawDirect_coqDynamicTruthSigmaRestrictedUniversalField_identified.
Check rawCoqDynamicTruthSigmaRestrictedUniversalFieldCertificate.
Check raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedUniversalField.
Check
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedUniversalField_identified.
Check RawCoqDynamicTruthSigmaRestrictedUniversalFieldIdentification.
Check
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedUniversalField_output.

Print Assumptions
  rawDirect_coqDynamicTruthSigmaRestrictedProjection_identified.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedProjection.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedProjection_identified.
Print Assumptions
  coqDynamicTruthSigmaRestrictedUniversalFieldProof_derives.
Print Assumptions rawDirectTemplateFormula_repeatedForall.
Print Assumptions
  rawDirect_coqDynamicTruthSigmaRestrictedUniversalField_identified.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedUniversalField.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedUniversalField_identified.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthSigmaRestrictedUniversalField_output.

End PABoundedRawCodedDynamicTruthUniversalLeafProofCompilationAudit.
