(**
  Compatibility umbrella for the split conjunction-introduction child compiler.

  The proof is deliberately partitioned into five acyclic modules.  Importing
  this historical module re-exports every public identifier, while strict
  verification can check each smaller proof object independently.
*)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildInterfaceSemanticCompilation
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageValidity
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceCompilation
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildCoreExtraction
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildTailCompilation.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildInterfaceCompilation.

Export PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildInterfaceSemanticCompilation.
Export PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageValidity.
Export PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceCompilation.
Export PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildCoreExtraction.
Export PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildTailCompilation.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionChildInterfaceCompilation.
