(** Public-surface and kernel-assumption audit for global successor closure. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthGlobalSuccessorRootClosure.

Module PABoundedRawCodedDynamicTruthGlobalSuccessorRootClosureAudit.

Import PABoundedRawCodedDynamicTruthGlobalSuccessorRootClosure.

Check RawCodedFormulaOperationallyClosedAt.
Check RawCodedFormulaRootClosedAt.
Check rawCodedFormulaRootClosedAt_three_iff.
Check raw_quotedFormula_root_closed_at_scope.
Check raw_fixedFormulaNumeralCode_root_closed_at_scope.

Check rawFormulaShiftBinaryCode_root_closed_at.
Check rawFormulaShiftUnaryCode_root_closed_at.
Check rawFormulaImpCode_root_closed_at.
Check rawFormulaAndCode_root_closed_at.
Check rawFormulaOrCode_root_closed_at.
Check rawFormulaAllCode_root_closed_at.
Check rawFormulaExCode_root_closed_at.
Check rawDynamicTruthFormulaAll5Code_root_closed_at.
Check rawDynamicTruthFormulaEx10Code_root_closed_at.
Check rawDynamicTruthFormulaAnd7Code_root_closed_at.

Check RawDynamicTruthPairedLocalRowsRootClosedAtWrapperDepth.
Check rawDynamicTruthGlobalRowChoiceCode_root_closed.
Check rawDynamicTruthGlobalRowsCode_root_closed.
Check rawDynamicTruthGlobalFormulaCode_root_closed_of_local_rows.
Check dynamicTruthPairedGlobalWrapperAt_root_closed.
Check raw_fixedReplacement_substitution_target_atomically_adequate.
Check raw_dynamicTruthSigmaLower_target_atomically_adequate.
Check raw_dynamicTruthPiLower_target_atomically_adequate.
Check raw_dynamicTruthDomain_target_atomically_adequate.
Check rawDynamicTruthPairedSuccessorRowAt_atomically_adequate.

Check RawDynamicTruthPairedGlobalSuccessorLocalClosure.
Check dynamicTruthPairedGlobalSuccessorAt_root_closed.
Check RawDynamicTruthPairedGlobalRootClosedSuccessorTotal.
Check dynamicTruthPairedGlobalSuccessorGraph_raw_root_closed_total.
Check dynamicTruthPairedGlobalBaseGraph_raw_root_closed_total.

Print Assumptions raw_quotedFormula_root_closed_at_scope.
Print Assumptions rawFormulaShiftBinaryCode_root_closed_at.
Print Assumptions rawFormulaShiftUnaryCode_root_closed_at.
Print Assumptions rawDynamicTruthGlobalFormulaCode_root_closed_of_local_rows.
Print Assumptions dynamicTruthPairedGlobalWrapperAt_root_closed.
Print Assumptions rawDynamicTruthPairedSuccessorRowAt_atomically_adequate.
Print Assumptions dynamicTruthPairedGlobalSuccessorAt_root_closed.
Print Assumptions dynamicTruthPairedGlobalSuccessorGraph_raw_root_closed_total.
Print Assumptions dynamicTruthPairedGlobalBaseGraph_raw_root_closed_total.

End PABoundedRawCodedDynamicTruthGlobalSuccessorRootClosureAudit.
