From BoundedPAConsistency Require Import
  RawCodedFormulaImpChildrenAtomicAdequacyProofCompilation.

Import
  PABoundedRawCodedFormulaImpChildrenAtomicAdequacyProofCompilation.

Check raw_codedFormulaAtomicallyAdequate_imp_children.
Check codedFormulaImpChildrenAtomicAdequacyFormula.
Check raw_sat_codedFormulaImpChildrenAtomicAdequacyFormula_iff.
Check codedFormulaImpChildrenAtomicAdequacyFormula_sentence.
Check codedFormulaImpChildrenAtomicAdequacyFormula_raw_valid.
Check PA_proves_codedFormulaImpChildrenAtomicAdequacyFormula.
Check coqFormulaImpChildrenAtomicAdequacyInstanceTemplate_open.
Check coqFormulaImpChildrenAtomicAdequacyInstanceTemplate_imp2_shape.
Check
  raw_codedPALocalProofOf_formulaImpChildrenAtomicAdequacy_instance_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_formulaImpChildrenAtomicAdequacy_instance_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_formulaImpChildrenAtomicAdequacy_of_roots_on_witnessed_extension_under_prefix.

Print Assumptions raw_codedFormulaAtomicallyAdequate_imp_children.
Print Assumptions codedFormulaImpChildrenAtomicAdequacyFormula_raw_valid.
Print Assumptions PA_proves_codedFormulaImpChildrenAtomicAdequacyFormula.
Print Assumptions
  raw_codedPALocalProofOf_formulaImpChildrenAtomicAdequacy_instance_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_formulaImpChildrenAtomicAdequacy_instance_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_formulaImpChildrenAtomicAdequacy_of_roots_on_witnessed_extension_under_prefix.
