(** Kernel audit for root-closure-preserving paired code orbits. *)

From BoundedPAConsistency Require Import
  RawCodedCarrierIndexedPairedRootClosedCodeOrbitGraph
  RawCodedDynamicTruthPairedGlobalRootClosedFormulaCodeOrbitGraph.

Module PABoundedRawCodedCarrierIndexedPairedRootClosedCodeOrbitGraphAudit.

Import PABoundedRawCodedCarrierIndexedPairedRootClosedCodeOrbitGraph.
Import
  PABoundedRawCodedDynamicTruthPairedGlobalRootClosedFormulaCodeOrbitGraph.

Check RawCarrierIndexedPairedRootClosedCodeOrbitBaseTotal.
Check RawCarrierIndexedPairedRootClosedCodeOrbitSuccessorTotal.
Check RawCarrierIndexedPairedRootClosedCodeOrbitAt.
Check carrierIndexedPairedRootClosedCodeOrbitExistsFormula.
Check raw_sat_carrierIndexedPairedRootClosedCodeOrbitExistsFormula_iff.
Check raw_carrierIndexedPairedRootClosedCodeOrbitExists_zero.
Check raw_carrierIndexedPairedRootClosedCodeOrbitExists_succ.
Check raw_carrierIndexedPairedRootClosedCodeOrbitExists_all.
Check RawCarrierIndexedPairedRootClosedCodeOrbitGraphTotal.
Check raw_carrierIndexedPairedRootClosedCodeOrbitGraph_total.

Check RawDynamicTruthPairedGlobalRootClosedFormulaCodeOrbitAt.
Check dynamicTruthPairedGlobalRootClosedFormulaCodeOrbitExistsFormula.
Check
  raw_sat_dynamicTruthPairedGlobalRootClosedFormulaCodeOrbitExistsFormula_iff.
Check dynamicTruthPairedGlobalOrbitBaseGraph_raw_root_closed_total.
Check RawDynamicTruthPairedGlobalOrbitRootClosedSuccessorTotal.
Check dynamicTruthPairedGlobalRootClosedFormulaCodeOrbitExists_all.
Check dynamicTruthPairedGlobalFormulaCodeOrbitGraph_raw_root_closed_total.

Print Assumptions
  raw_sat_carrierIndexedPairedRootClosedCodeOrbitExistsFormula_iff.
Print Assumptions raw_carrierIndexedPairedRootClosedCodeOrbitExists_all.
Print Assumptions raw_carrierIndexedPairedRootClosedCodeOrbitGraph_total.
Print Assumptions dynamicTruthPairedGlobalOrbitBaseGraph_raw_root_closed_total.
Print Assumptions
  dynamicTruthPairedGlobalRootClosedFormulaCodeOrbitExists_all.
Print Assumptions
  dynamicTruthPairedGlobalFormulaCodeOrbitGraph_raw_root_closed_total.

End PABoundedRawCodedCarrierIndexedPairedRootClosedCodeOrbitGraphAudit.
