(** Audit surface for shared successor append global-root compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSharedSuccessorAppendGlobalRoots.

Import PABoundedRawCodedDynamicTruthSharedSuccessorAppendGlobalRoots.

Check RawDynamicTruthSharedSuccessorAppendGlobalInputsAt.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_input_package.
Check
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_shared_successor_globals_of_append_input_packages.
Check
  raw_dynamicTruthPredecessorGlobalRootsOnWitnessedExtensionFrom_of_shared_successor_append_input_packages.

Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_input_package.
Print Assumptions
  raw_dynamicTruthPredecessorGlobalRootsOnWitnessedExtensionFrom_of_shared_successor_append_input_packages.
