(** Assumption and exact-slot audit for direct right disjunction
    introduction. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectOrIntroductionRightCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionRightCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionRightCase.

Check coqRestrictedPADirectOrIntroductionRightCaseTemplate.
Check coqRestrictedPADirectOrIntroductionRight_case_shape.
Check coqRestrictedPADirectOrIntroductionRightCodeEqualityTemplate.
Check coqRestrictedPADirectOrIntroductionRightFormulaCodeTemplate.
Check coqRestrictedPADirectOrIntroductionRightChildEndpointTemplate.
Check coqRestrictedPADirectOrIntroductionRightFormulaTerm.
Check coqRestrictedPADirectOrIntroductionRightFormulaTruthTemplate.
Check coqRestrictedPADirectOrIntroductionRight_formula_truth_shape.
Check coqRestrictedPADirectOrIntroductionRightResultTruthTemplate.

Check coqRestrictedPADirectOrIntroductionRightRecursiveChildLawTemplate.
Check coqRestrictedPADirectOrIntroductionRightDynamicTruthLawTemplate.
Check RawCoqRestrictedPADirectOrIntroductionRightRecursiveChildLawRoot.
Check RawCoqRestrictedPADirectOrIntroductionRightDynamicTruthLawRoot.

Check coqRestrictedPADirectOrIntroductionRightCodeEqualityRootAt_valid.
Check coqRestrictedPADirectOrIntroductionRightFormulaCodeRootAt_valid.
Check coqRestrictedPADirectOrIntroductionRightChildEndpointRootAt_valid.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectOrIntroductionRightConclusion.
Check raw_coqRestrictedPADirectStrongStepOrIntroductionRightCaseRoot.

Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectOrIntroductionRightConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepOrIntroductionRightCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionRightCaseAudit.
