(** Kernel-facing audit for the concrete restricted-universal local field. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthRestrictedUniversalLocalProofFieldGraph.

Module
  PABoundedRawCodedDynamicTruthRestrictedUniversalLocalProofFieldGraphAudit.

Import
  PABoundedRawCodedDynamicTruthRestrictedUniversalLocalProofFieldGraph.

Check dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph.
Check RawDynamicTruthSigmaRestrictedUniversalLocalProofFieldAt.
Check
  raw_sat_dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_iff.

Check
  RawDynamicTruthSigmaRestrictedUniversalAdequateDirectCompilerTotal.
Check
  RawDynamicTruthSigmaRestrictedUniversalOrbitDirectCompilerTotal.
Check
  rawDynamicTruthSigmaRestrictedUniversalDirectCompilerTotal_implies_adequate.
Check
  rawDynamicTruthSigmaRestrictedUniversalAdequateDirectCompilerTotal_implies_orbit.
Check
  RawDynamicTruthSigmaRestrictedUniversalAdequateTernarySelectorTotal.
Check
  RawDynamicTruthSigmaRestrictedUniversalAdequateTernaryInterchangeTotal.
Check
  RawDynamicTruthSigmaRestrictedUniversalOrbitTernaryInterchangeTotal.
Check
  rawDynamicTruthSigmaRestrictedUniversalAdequateTernarySelectorTotal_of_interchange.
Check
  rawDynamicTruthSigmaRestrictedUniversalDirectCompiler_of_selector.
Check
  rawDynamicTruthSigmaRestrictedUniversalAdequateDirectCompilerTotal_of_ternary_selector.
Check
  rawDynamicTruthSigmaRestrictedUniversalAdequateDirectCompilerTotal_of_interchange.
Check
  rawDynamicTruthSigmaRestrictedUniversalOrbitDirectCompilerTotal_of_interchange.
Check
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_adequate_proof_total.

Check RawDynamicTruthSigmaRestrictedUniversalLocalProofFieldTotal.
Check
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total.
Check
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_orbit_interchange.
Check
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_interchange.
Check
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_direct_compiler.

Print Assumptions
  raw_sat_dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_iff.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalDirectCompilerTotal_implies_adequate.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalAdequateDirectCompilerTotal_implies_orbit.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalAdequateTernarySelectorTotal_of_interchange.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalDirectCompiler_of_selector.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalAdequateDirectCompilerTotal_of_ternary_selector.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalAdequateDirectCompilerTotal_of_interchange.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalOrbitDirectCompilerTotal_of_interchange.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_adequate_proof_total.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_orbit_interchange.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_interchange.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_direct_compiler.

End
  PABoundedRawCodedDynamicTruthRestrictedUniversalLocalProofFieldGraphAudit.
