From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyBridgeContextTransport.

Module PABoundedRawCodedRestrictedPAConsistencyBridgeContextTransportAudit.

Import
  PABoundedRawCodedRestrictedPAConsistencyBridgeContextTransport.

Check raw_codedPALocalProof_contextInclusionWeakening_shared_head.
Check
  raw_codedPALocalProof_coqRestrictedPANativeAxiomContextTruthRowContext_transport.
Check raw_coqRestrictedPAConsistencyBridgeContext_included.
Check
  raw_codedPALocalProof_coqRestrictedPAConsistencyBridgeContext_transport.
Check
  raw_codedPALocalProof_coqRestrictedPAConsistencyBridgeBodyDirectContext_transport.

Print Assumptions
  raw_codedPALocalProof_contextInclusionWeakening_shared_head.
Print Assumptions
  raw_codedPALocalProof_coqRestrictedPANativeAxiomContextTruthRowContext_transport.
Print Assumptions raw_coqRestrictedPAConsistencyBridgeContext_included.
Print Assumptions
  raw_codedPALocalProof_coqRestrictedPAConsistencyBridgeContext_transport.
Print Assumptions
  raw_codedPALocalProof_coqRestrictedPAConsistencyBridgeBodyDirectContext_transport.

End PABoundedRawCodedRestrictedPAConsistencyBridgeContextTransportAudit.
