From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectBodyShell.

Module
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectBodyShellAudit.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectBodyShell.

Check rawPALocalProofAll2Imp3Root.
Check raw_codedPALocalProofOf_all2_imp3_shell.

Check rawCoqRestrictedPANativeAxiomContextWitnessCode.
Check rawCoqRestrictedPANativeAxiomContextBoundedCode.
Check rawCoqRestrictedPANativeAxiomContextAdequacyCode.
Check rawCoqRestrictedPANativeAxiomContextSelectedLeafCode.
Check rawCoqRestrictedPASelectedAxiomContextsTruthDirectCode_shell_view.

Check RawCoqRestrictedPANativeAxiomContextTruthTraversalLeafCompiler.
Check raw_coqRestrictedPANativeAxiomContextTruthBodyRoot_of_traversal_leaf.
Check raw_coqRestrictedPANativeAxiomContextTruthLink_axiom_adequate.
Check RawCoqRestrictedPANativeAxiomContextTruthAdequateBodyRootCompiler.
Check
  raw_coqRestrictedPANativeAxiomContextTruthAdequateBodyRootCompiler_of_leaf.

Check raw_dynamicTruthNativeFinal_bridge_context_all_atomically_adequate.
Check
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthRootCompiler_of_traversal_leaf.

Print Assumptions raw_codedPALocalProofOf_all2_imp3_shell.
Print Assumptions
  raw_coqRestrictedPANativeAxiomContextTruthBodyRoot_of_traversal_leaf.
Print Assumptions
  raw_coqRestrictedPANativeAxiomContextTruthLink_axiom_adequate.
Print Assumptions
  raw_coqRestrictedPANativeAxiomContextTruthAdequateBodyRootCompiler_of_leaf.
Print Assumptions
  raw_dynamicTruthNativeFinal_bridge_context_all_atomically_adequate.
Print Assumptions
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthRootCompiler_of_traversal_leaf.

End
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectBodyShellAudit.
