From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectRuleCasesAfterOrIntroductionLeftTruth.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectRuleCasesAfterOrIntroductionLeftTruth.

Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsAfterOrIntroductionLeftTruth.
Check raw_afterAssumption_of_afterOrIntroductionLeftTruth.
Check RawCoqRestrictedPADirectSelectedOrIntroductionLeftTruthTail.
Check raw_orIntroductionLeftTruthLawRoot_surround_witnessed_tail.
Check
  RawCoqRestrictedPADirectRemainingAfterOrIntroductionLeftTruthStandardTailCompiler.
Check
  raw_remainingAfterAssumptionCompiler_of_selectedOrIntroductionLeftTruth.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeInputs_afterOrIntroductionLeftTruth.

Print Assumptions raw_orIntroductionLeftTruthLawRoot_surround_witnessed_tail.
Print Assumptions
  raw_remainingAfterAssumptionCompiler_of_selectedOrIntroductionLeftTruth.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeInputs_afterOrIntroductionLeftTruth.
