(** Compatibility umbrella for the componentized Or-E child semantics. *)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesCore
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildBelowSatIff
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildRestrictedSatIff
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildEndpointSatIff
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildAdmissibleSatIff.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapes.

(** Preserve the historical unqualified interface.  In downstream files the
    semantic equations are now opaque constants imported from independent
    kernel-checking units. *)
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesCore.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildBelowSatIff.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildRestrictedSatIff.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildEndpointSatIff.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildAdmissibleSatIff.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapes.
