(** Kernel-facing audit of the native master successor obtained from the
    five positive proof totals and compact consistency successor. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeMasterSuccessorFromProofTotals.

Module
  PABoundedRawCodedDynamicTruthNativeMasterSuccessorFromProofTotalsAudit.

Import
  PABoundedRawCodedDynamicTruthNativeMasterSuccessorFromProofTotals.

Check RawSixFieldMasterOrdinaryProofsOf.
Check RawSixFieldMasterOrdinaryProofsCommonContextLiftAt.
Check RawSixFieldMasterOrdinaryProofsCommonContextLift.
Check raw_codedPAProofOf_final_of_sixFieldMaster_common_context.
Check RawDynamicTruthNativePositiveProofTotals.
Check
  RawDynamicTruthNativeSplicedMasterPositiveOrdinaryComponentSuccessor.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveOrdinaryComponentSuccessor_of_proof_totals.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_ordinary_and_common_context_lift.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_proof_totals_and_common_context_lift.
Check RawCodedPAEmptyContextToWitnessedContextTransport.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_local_proof_totals_and_empty_context_transport.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_local_roots_and_empty_context_transport.

Print Assumptions
  raw_codedPAProofOf_final_of_sixFieldMaster_common_context.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveOrdinaryComponentSuccessor_of_proof_totals.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_ordinary_and_common_context_lift.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_proof_totals_and_common_context_lift.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_local_proof_totals_and_empty_context_transport.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_local_roots_and_empty_context_transport.

End
  PABoundedRawCodedDynamicTruthNativeMasterSuccessorFromProofTotalsAudit.
