(** Assumption audit for the native local decision-root reduction. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalDecisionRootCompilation.

Import PABoundedRawCodedDynamicTruthNativeLocalDecisionRootCompilation.

Check rawDynamicTruthNativeLocalAdmissibleDomainOrRoot.
Check RawDynamicTruthNativeLocalDomainCaseDecisionRootsAt.
Check RawDynamicTruthNativeLocalAdmissibleDomainRootAt.
Check rawDynamicTruthNativeLocalDecisionFromCasesRoot.
Check raw_codedPALocalProofOf_dynamicTruthNativeLocalDecision_from_cases.
Check raw_dynamicTruthNativeLocalDecisionRootOn_of_structural_roots.
Check raw_codedPALocalProofOf_dynamicTruthNativeLocalAdmissibleDomainOr.
Check raw_dynamicTruthNativeLocalAdmissibleDomainRootAt_realizable.
Check RawDynamicTruthNativeLocalDomainCaseDecisionRootInterface.
Check RawDynamicTruthNativeLocalAdmissibleDomainRootInterface.
Check raw_dynamicTruthNativeLocalDecisionEvidenceRootInterface_of_cases.
Check RawDynamicTruthNativeLocalDecisionEvidenceRootOnRealizableBases.
Check
  raw_dynamicTruthNativeLocalDecisionEvidenceRoot_on_realizable_of_cases.
Check RawDynamicTruthNativeLocalDecisionEvidenceRootOnWitnessedBases.
Check raw_dynamicTruthNativeLocalDecisionEvidenceRoot_on_witnessed_of_cases.
Check
  RawDynamicTruthNativeLocalDomainCaseDecisionRootInterfaceAtEmptyBase.
Check
  RawDynamicTruthNativeLocalDecisionEvidenceRootInterfaceAtEmptyBase.
Check
  raw_dynamicTruthNativeLocalDecisionEvidenceRoot_at_empty_base_of_cases.
Check raw_dynamicTruthNativeLocalDomainCaseDecisionRoots_at_empty_base.
Check
  raw_dynamicTruthNativeLocalLeafRootCompiler_of_decision_cases_and_linked_empty_base.

(** The structural assembler and the witnessed-tail specialization must not
    acquire any new logical axiom. *)
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeLocalDecision_from_cases.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeLocalAdmissibleDomainOr.
Print Assumptions
  raw_dynamicTruthNativeLocalDecisionEvidenceRoot_on_witnessed_of_cases.
Print Assumptions
  raw_dynamicTruthNativeLocalDecisionEvidenceRoot_at_empty_base_of_cases.
Print Assumptions
  raw_dynamicTruthNativeLocalLeafRootCompiler_of_decision_cases_and_linked_empty_base.
