(** Audit for projection of all seven opened global traversal fields. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthGlobalOpenedFieldProjection.

Import PABoundedRawCodedDynamicTruthGlobalOpenedFieldProjection.

Check coqDynamicTruthGlobalOpenedTraversalBody_and7_shape.
Check coqDynamicTruthGlobalExistentialBodyMany_ten.
Check coqDynamicTruthGlobalExistentialDeepContext_head.
Check raw_codedPALocalProofOf_dynamicTruthGlobal_opened_and7_fields.
Check coqDynamicTruthGlobalOpenedRootRowReplacements.
Check coqDynamicTruthGlobalOpenedRootRowFormula.
Check coqDynamicTruthGlobalOpenedRootRowChoice.
Check coqDynamicTruthGlobalOpenedRootRowFormula_success.
Check coqDynamicTruthGlobalOpenedRootRowFormula_imp2_shape.
Check coqDynamicTruthGlobalOpenedRootRowFormula_bound.
Check coqDynamicTruthGlobalOpenedRootRowFormula_lookup.
Check raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_choice.

Print Assumptions coqDynamicTruthGlobalOpenedTraversalBody_and7_shape.
Print Assumptions coqDynamicTruthGlobalExistentialBodyMany_ten.
Print Assumptions coqDynamicTruthGlobalExistentialDeepContext_head.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthGlobal_opened_and7_fields.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowFormula_success.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowFormula_imp2_shape.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowFormula_bound.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowFormula_lookup.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_choice.
