(** Kernel-facing audit for opaque-tail invariance of the universal code. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessUniversalDirectCodeTailInvariance.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessUniversalDirectCodeTailInvarianceAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessUniversalDirectCodeTailInvariance.

Check RawTemplateFormulaOpaqueNamesBelow.
Check rawStructuralTemplateTermWith_parameter_ext.
Check rawStructuralTemplateTermsWith_parameter_ext.
Check rawStructuralTemplateFormulaWith_opaque_prefix_ext.
Check rawDirectTemplateFormula_opaque_prefix_ext.
Check rawTemplateFormulaOpaqueNamesBelow_embedPA.
Check rawTemplateFormulaOpaqueNamesBelow_closeN.
Check rawTemplateFormulaOpaqueNamesBelow_restrictedTarget.
Check
  coqRestrictedPADerivationSoundnessUniversalTemplate_opaque_names_below_two.
Check
  rawCoqRestrictedPADerivationSoundnessExtendedDirectFormula_below_two_eq_basic.
Check
  raw_coqRestrictedPADerivationSoundnessUniversalDirectCode_extended_eq_basic.
Check
  raw_coqRestrictedPADerivationSoundnessUniversalDirectCode_extended_rows_eq_basic.

Print Assumptions rawStructuralTemplateFormulaWith_opaque_prefix_ext.
Print Assumptions rawDirectTemplateFormula_opaque_prefix_ext.
Print Assumptions
  coqRestrictedPADerivationSoundnessUniversalTemplate_opaque_names_below_two.
Print Assumptions
  rawCoqRestrictedPADerivationSoundnessExtendedDirectFormula_below_two_eq_basic.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessUniversalDirectCode_extended_eq_basic.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessUniversalDirectCode_extended_rows_eq_basic.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessUniversalDirectCodeTailInvarianceAudit.
