(** Assumption audit for the strong-step predecessor global-row handoff. *)

From BoundedPAConsistency Require Import
  RawCodedStrongStepPredecessorGlobalRowEvidenceCompilation.

Import
  PABoundedRawCodedStrongStepPredecessorGlobalRowEvidenceCompilation.

Check
  raw_codedPALocalProof_strongStepPredecessorLogicalRoots_of_restricted_rule_and_global_sources_and_selected_compiler_families_under_prefix.
Check
  raw_codedPALocalProof_strongStepPredecessorLogicalRoots_of_restricted_rule_and_global_sources_under_prefix.
Check
  raw_codedPALocalProof_strongStepPredecessorLogicalRoots_of_restricted_rule_and_growing_global_sources_and_selected_compiler_families.
Check
  raw_codedPALocalProof_strongStepPredecessor_atomic_and_domain_of_restricted_and_rule_roots.
Check
  raw_codedPALocalProof_strongStepPredecessor_atomic_and_domain_of_restricted_and_rule_roots_under_predecessor_state.

Print Assumptions
  raw_codedPALocalProof_strongStepPredecessorLogicalRoots_of_restricted_rule_and_global_sources_and_selected_compiler_families_under_prefix.
Print Assumptions
  raw_codedPALocalProof_strongStepPredecessorLogicalRoots_of_restricted_rule_and_global_sources_under_prefix.
Print Assumptions
  raw_codedPALocalProof_strongStepPredecessorLogicalRoots_of_restricted_rule_and_growing_global_sources_and_selected_compiler_families.
Print Assumptions
  raw_codedPALocalProof_strongStepPredecessor_atomic_and_domain_of_restricted_and_rule_roots.
Print Assumptions
  raw_codedPALocalProof_strongStepPredecessor_atomic_and_domain_of_restricted_and_rule_roots_under_predecessor_state.
