(** Kernel-facing audit for the carrier-level soundness induction shell. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessCarrierInductionShell.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierInductionShellAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierInductionShell.

Check rawStructuralTemplateFormula_shiftAt.

Check coqRestrictedPADerivationSoundnessCarrierInductionSourceTemplate.
Check coqRestrictedPADerivationSoundnessCarrierInductionShiftedTemplate.
Check coqRestrictedPADerivationSoundnessCarrierInductionSuccessorTemplate.
Check coqRestrictedPADerivationSoundnessCarrierInductionZeroTemplate.

Check rawCoqRestrictedPADerivationSoundnessCarrierInductionSourceCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionShiftedCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionSuccessorCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionZeroCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionSourceAllCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionStepImpCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionStepAllCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionPremiseCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierInductionBodyCode.

Check RawCoqRestrictedPADerivationSoundnessClosureRemainder.
Check raw_coqRestrictedPADerivationSoundnessCarrierClosureInductionData.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversal_of_cases.

Print Assumptions rawStructuralTemplateFormula_shiftAt.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierClosureInductionData.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversal_of_cases.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierInductionShellAudit.
