(** Audit surface for the native direct bottom-refutation link. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPABottomTruthNativeDirectRefutationLink.

Module
  PABoundedRawCodedRestrictedPABottomTruthNativeDirectRefutationLinkAudit.

Import
  PABoundedRawCodedRestrictedPABottomTruthNativeDirectRefutationLink.

Check RawCoqRestrictedPANativeConclusionTruthSelectorLinkAt.
Check RawCoqRestrictedPANativeSuccessorConclusionTruthSelectorLinkAt.
Check rawCoqRestrictedPASelectedSigmaBottomRefutationCode.
Check raw_coqRestrictedPABottomTruthRefutationDirectCode_native_view.
Check
  raw_coqRestrictedPANativeDirectTruthInputsWithClosure_bottom_link_exists.
Check RawCoqRestrictedPASelectedSigmaBottomRefutationRootCompiler.
Check
  raw_coqRestrictedPANativeDirectTruthInputsWithClosure_bottom_refutation_of_selected_sigma.
Check RawDynamicTruthNativeFinalBottomTruthNativeSelectorLinkCompiler.
Check
  RawDynamicTruthNativeFinalSelectedSigmaBottomRefutationRootCompiler.
Check
  raw_dynamicTruthNativeFinalBottomTruthDirectRefutationCompiler_of_native_selector.

Print Assumptions
  raw_coqRestrictedPABottomTruthRefutationDirectCode_native_view.
Print Assumptions
  raw_coqRestrictedPANativeDirectTruthInputsWithClosure_bottom_link_exists.
Print Assumptions
  raw_coqRestrictedPANativeDirectTruthInputsWithClosure_bottom_refutation_of_selected_sigma.
Print Assumptions
  raw_dynamicTruthNativeFinalBottomTruthDirectRefutationCompiler_of_native_selector.

End
  PABoundedRawCodedRestrictedPABottomTruthNativeDirectRefutationLinkAudit.
