(** Assumption audit for the two-coordinate carrier-indexed code orbit. *)

From BoundedPAConsistency Require Import
  RawCodedCarrierIndexedPairedCodeOrbitGraph.

Import PABoundedRawCodedCarrierIndexedPairedCodeOrbitGraph.

Check pairedCarrierCodeOrbitPackedBaseGraph.
Check pairedCarrierCodeOrbitPackedSuccessorGraph.
Check carrierIndexedPairedCodeOrbitGraph.
Check RawCarrierIndexedPairedCodeOrbitAt.
Check raw_sat_carrierIndexedPairedCodeOrbitGraph_iff.
Check RawCarrierIndexedPairedCodeOrbitBaseTotal.
Check RawCarrierIndexedPairedCodeOrbitSuccessorTotal.
Check raw_carrierIndexedPairedCodeOrbitAt_zero_of_base.
Check raw_carrierIndexedPairedCodeOrbitAt_succ.
Check raw_carrierIndexedPairedCodeOrbitExists_all.
Check RawCarrierIndexedPairedCodeOrbitGraphTotal.
Check raw_carrierIndexedPairedCodeOrbitGraph_total.
Check raw_carrierIndexedPairedCodeOrbitAt_zero_iff.
Check raw_carrierIndexedPairedCodeOrbitAt_succ_iff.
Check raw_carrierIndexedPairedCodeOrbitGraph_zero_iff.
Check raw_carrierIndexedPairedCodeOrbitGraph_succ_iff.

Print Assumptions raw_sat_carrierIndexedPairedCodeOrbitGraph_iff.
Print Assumptions raw_carrierIndexedPairedCodeOrbitAt_zero_of_base.
Print Assumptions raw_carrierIndexedPairedCodeOrbitAt_succ.
Print Assumptions raw_carrierIndexedPairedCodeOrbitExists_all.
Print Assumptions raw_carrierIndexedPairedCodeOrbitGraph_total.
Print Assumptions raw_carrierIndexedPairedCodeOrbitAt_zero_iff.
Print Assumptions raw_carrierIndexedPairedCodeOrbitAt_succ_iff.
Print Assumptions raw_carrierIndexedPairedCodeOrbitGraph_zero_iff.
Print Assumptions raw_carrierIndexedPairedCodeOrbitGraph_succ_iff.
