(** Exact-interface and assumption audit for append traversal assembly. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendGlobalTraversalAssembly.

Import PABoundedRawCodedFourStateTableAppendGlobalTraversalAssembly.

Check coqFourStateTableAppendWitnessContext_affine.
Check raw_fourStateTableAppendWitnessContext_witnessed_tail_code.
Check coqFourStateTableAppendTraversalBodyTemplate.
Check coqFourStateTableAppendGlobalTraversalWitnesses.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_success.
Check templateAnd7First.
Check templateAnd7Second.
Check templateAnd7Third.
Check templateAnd7Fourth.
Check templateAnd7Fifth.
Check templateAnd7Sixth.
Check templateAnd7Seventh.
Check templateUniversalBodyMany.
Check coqFourStateTableAppendOpenedGlobalRowsTemplate.
Check coqFourStateTableAppendOpenedGlobalRowBodyTemplate.
Check coqFourStateTableAppendOpenedGlobalRowProductionTemplate.
Check coqFourStateTableAppendOpenedGlobalRowsTemplate_success.
Check coqFourStateTableAppendOpenedGlobalRowsTemplate_shape.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_and7_shape.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_field_shapes.
Check coqFourStateTableAppendOpenedGlobalFormulaTemplate_shape.
Check
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_traversal_body.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_rows.

Print Assumptions coqFourStateTableAppendWitnessContext_affine.
Print Assumptions raw_fourStateTableAppendWitnessContext_witnessed_tail_code.
Print Assumptions
  coqFourStateTableAppendOpenedGlobalFormulaTemplate_and7_shape.
Print Assumptions
  coqFourStateTableAppendOpenedGlobalFormulaTemplate_field_shapes.
Print Assumptions coqFourStateTableAppendOpenedGlobalRowsTemplate_success.
Print Assumptions coqFourStateTableAppendOpenedGlobalRowsTemplate_shape.
Print Assumptions coqFourStateTableAppendOpenedGlobalFormulaTemplate_shape.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_traversal_body.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_global_of_append_rows.
