From BoundedPAConsistency Require Import
  RawCodedTemplateLocalProofStandardWitnessTailTransport.

Import PABoundedRawCodedTemplateLocalProofStandardWitnessTailTransport.

Check raw_templateContextCode_app_on_tail_general.
Check raw_templateContextCode_as_on_tail_general.
Check raw_standardPAAxiomWitnessPrefixContextCode_target_included.
Check
  raw_standardPAAxiomWitnessPrefixContextCode_samePrefix_included_general.
Check raw_templateEmbeddedPAAxiomWitnessContext.
Check raw_templateEmbeddedPAAxiomWitnessContext_surrounded_included.
Check raw_codedPALocalProof_standardWitnessTail_surround_under_prefix.

Print Assumptions
  raw_codedPALocalProof_standardWitnessTail_surround_under_prefix.
