From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyGrowingOpenCompiler.

Import PABoundedRawCodedRestrictedPAConsistencyGrowingOpenCompiler.

Check RawRestrictedPAConsistencyGrowingOpenContradictionCompiler.
Check RawRestrictedPAConsistencyGrowingOpenContradictionCompilerInAllModels.
Check raw_restrictedPAConsistencyCertificateSuccessor_of_growingOpenCompiler.
Check
  raw_restrictedPAConsistencyCertificateSuccessorInAllModels_of_growingOpenCompiler.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_growingOpenCompiler.

Print Assumptions
  raw_restrictedPAConsistencyCertificateSuccessor_of_growingOpenCompiler.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_growingOpenCompiler.
