(** Assumption audit for proof-producing successor-bound splitting. *)

From BoundedPAConsistency Require Import
  RawCodedLtSuccCasesProofCompilation.

Import PABoundedRawCodedLtSuccCasesProofCompilation.

Check coqLtSuccCasesInstanceTemplate.
Check coqLtSuccCasesAntecedentTemplate.
Check coqLtSuccCasesResultTemplate.
Check coqLtSuccCasesBelowTemplate.
Check coqLtSuccCasesEqualTemplate.
Check coqLtSuccCasesInstanceTemplate_open.
Check coqLtSuccCasesInstanceTemplate_shape.
Check raw_codedPALocalProofOf_lt_succ_cases_instance_on_witnessed_tail.
Check raw_codedPALocalProofOf_lt_succ_cases_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_lt_succ_cases_on_witnessed_tail_under_prefix.
Check raw_codedPALocalProofOf_lt_succ_cases_eliminate_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_lt_succ_cases_eliminate_on_witnessed_tail_under_prefix.
Check RawCodedPAGrowingTemplateLocalProofAt.
Check raw_codedPAGrowingTemplateLocalProofAt_conclusion_eq.
Check raw_codedPAGrowingTemplateLocalProofAt_cons_of_local_proof.
Check raw_codedPAGrowingTemplateBranchCompiler_cons_of_local.
Check
  raw_codedPALocalProofOf_lt_succ_cases_eliminate_on_growing_witnessed_tail_under_prefix.

Print Assumptions coqLtSuccCasesInstanceTemplate_open.
Print Assumptions coqLtSuccCasesInstanceTemplate_shape.
Print Assumptions
  raw_codedPALocalProofOf_lt_succ_cases_instance_on_witnessed_tail.
Print Assumptions raw_codedPALocalProofOf_lt_succ_cases_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_lt_succ_cases_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_lt_succ_cases_eliminate_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_lt_succ_cases_eliminate_on_witnessed_tail_under_prefix.
Print Assumptions RawCodedPAGrowingTemplateLocalProofAt.
Print Assumptions raw_codedPAGrowingTemplateLocalProofAt_conclusion_eq.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_cons_of_local_proof.
Print Assumptions
  raw_codedPAGrowingTemplateBranchCompiler_cons_of_local.
Print Assumptions
  raw_codedPALocalProofOf_lt_succ_cases_eliminate_on_growing_witnessed_tail_under_prefix.
