(** Kernel-facing audit for native cross-level proof compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeCrossLevelProofCompilation.

Import PABoundedRawCodedDynamicTruthNativeCrossLevelProofCompilation.

Check rawDynamicTruthNativeCrossLevelCoherenceBodyCode.
Check rawDynamicTruthNativeCrossLevelCoherenceFieldCode_as_all3.
Check rawDynamicTruthNativeCrossLevelAdmissibleContext.
Check rawDynamicTruthNativeCrossLevelDomainContext.
Check rawDynamicTruthNativeCrossLevelDirectionalContext.
Check RawDynamicTruthNativeCrossLevelSigmaLocalRootsAt.
Check RawDynamicTruthNativeCrossLevelPiLocalRootsAt.
Check RawDynamicTruthNativeCrossLevelBodyLocalRootAt.
Check raw_dynamicTruthNativeCrossLevelBodyLocalRootAt_of_polarity_roots.
Check rawDynamicTruthNativeCrossLevelClose3Root.
Check rawDynamicTruthNativeCrossLevelProofCertificate.
Check raw_dynamicTruthNativeCrossLevel_empty_witness_context.
Check
  raw_codedPAProofOf_dynamicTruthNativeCrossLevelCoherenceField_of_body_root.
Check
  raw_codedPAProofOf_dynamicTruthNativeCrossLevelCoherenceField_of_polarity_roots.
Check RawDynamicTruthNativeCrossLevelProofTraceAt.
Check RawDynamicTruthNativeCrossLevelLocalRootCompiler.
Check raw_dynamicTruthNativeCrossLevelProofTraceAt_of_transform.
Check
  raw_dynamicTruthNativeCrossLevelCoherenceProofCompiler_of_local_roots.
Check
  dynamicTruthNativeCrossLevelPositiveGraph_raw_proof_total_of_local_roots.

Print Assumptions
  raw_dynamicTruthNativeCrossLevelBodyLocalRootAt_of_polarity_roots.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeCrossLevelCoherenceField_of_body_root.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeCrossLevelCoherenceField_of_polarity_roots.
Print Assumptions raw_dynamicTruthNativeCrossLevelProofTraceAt_of_transform.
Print Assumptions
  raw_dynamicTruthNativeCrossLevelCoherenceProofCompiler_of_local_roots.
Print Assumptions
  dynamicTruthNativeCrossLevelPositiveGraph_raw_proof_total_of_local_roots.
