(** Assumption audit for the finite synchronized-row witness layout. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsWitnessShapes.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsWitnessShapes.

Check coqRestrictedPANativeAxiomRowsFieldTemplate.
Check coqRestrictedPANativeAxiomRowsReadyContext.
Check coqRestrictedPANativeAxiomRowsDeepContext.
Check coqRestrictedPANativeAxiomRowsTargetWitnesses.
Check coqRestrictedPANativeAxiomRowsWitnessContext_shape.
Check coqRestrictedPANativeAxiomRowsBoundedContext_shape.
Check coqRestrictedPANativeAxiomRowsAdequateContext_shape.
Check coqRestrictedPANativeAxiomRowsFinalWitnessBody_shape.
Check coqRestrictedPANativeAxiomRowsFinalBoundedBody_shape.
Check coqRestrictedPANativeAxiomRowsFinalAdequateBody_shape.
Check coqRestrictedPANativeAxiomRowsTarget_open_ready.
Check coqRestrictedPANativeAxiomRowsOpenedTarget_shape.

Print Assumptions coqRestrictedPANativeAxiomRowsWitnessContext_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsBoundedContext_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsAdequateContext_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsFinalWitnessBody_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsFinalBoundedBody_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsFinalAdequateBody_shape.
Print Assumptions coqRestrictedPANativeAxiomRowsTarget_open_ready.
Print Assumptions coqRestrictedPANativeAxiomRowsOpenedTarget_shape.
Print Assumptions coqRestrictedPANativeAxiomRows_final_witness_body_in.
Print Assumptions coqRestrictedPANativeAxiomRows_final_bounded_body_in.
Print Assumptions coqRestrictedPANativeAxiomRows_final_adequate_body_in.
Print Assumptions coqRestrictedPANativeAxiomRows_final_field_in.
Print Assumptions coqRestrictedPANativeAxiomRows_final_transfer_source_in.
