(** Audit the strongest four-coordinate reduced dependency boundary. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionCanonicalV2Boundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionCanonicalV2Boundary.

Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionCanonicalV2KernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevelShiftSubstitution_canonical_v2_kernel_compilers.
Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelShiftSubstitutionCanonicalV2KernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevelShiftSubstitution_canonical_v2_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevelShiftSubstitution_canonical_v2_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevelShiftSubstitution_canonical_v2_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevelShiftSubstitution_canonical_v2_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevelShiftSubstitution_canonical_v2_kernel_compilers.
