(** API and assumption audit for the restricted Pi field transform. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPiExistentialLeafTransformGraph.

Import PABoundedRawCodedDynamicTruthPiExistentialLeafTransformGraph.

Check dynamicTruthPiRestrictedExistentialProjectionCodeTerm.
Check dynamicTruthPiRestrictedExistentialFieldCodeTerm.
Check rawDynamicTruthPiRestrictedExistentialProjectionGraphCode.
Check rawDynamicTruthPiRestrictedExistentialFieldGraphCode.
Check raw_eval_dynamicTruthPiRestrictedExistentialProjectionCodeTerm.
Check raw_eval_dynamicTruthPiRestrictedExistentialFieldCodeTerm.
Check dynamicTruthPiRestrictedExistentialFieldCodeTermAt.
Check raw_sat_dynamicTruthPiRestrictedExistentialFieldCodeTermAt_iff.
Check rawDynamicTruthPiExistentialCode_eq_directTemplateCode.
Check rawDynamicTruthPiRestrictedExistentialFieldGraphCode_eq_compiled.

Check dynamicTruthPiRestrictedExistentialFieldTransformGraph.
Check RawDynamicTruthPiRestrictedExistentialFieldTransformAt.
Check raw_sat_dynamicTruthPiRestrictedExistentialFieldTransformGraph_iff.
Check RawDynamicTruthPiRestrictedExistentialFieldTransformTotal.
Check dynamicTruthPiRestrictedExistentialFieldTransformGraph_raw_total.
Check RawDynamicTruthPiRestrictedExistentialDirectCompilerTotal.
Check dynamicTruthPiRestrictedExistentialFieldTransformGraph_raw_proof_total.

Print Assumptions
  raw_eval_dynamicTruthPiRestrictedExistentialFieldCodeTerm.
Print Assumptions
  raw_sat_dynamicTruthPiRestrictedExistentialFieldTransformGraph_iff.
Print Assumptions
  rawDynamicTruthPiRestrictedExistentialFieldGraphCode_eq_compiled.
Print Assumptions
  dynamicTruthPiRestrictedExistentialFieldTransformGraph_raw_total.
Print Assumptions
  dynamicTruthPiRestrictedExistentialFieldTransformGraph_raw_proof_total.
