(**
  Assumption audit for the carried arithmetic roots of the direct open shell.

  These declarations are intentionally checked from a separate client
  module.  In particular, the three growing constructions must expose no
  semantic truth-to-proof callback: they may only use PA completeness for
  the two fixed, standard arithmetic laws and represented proof transport.
*)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAOpenShellArithmeticCarriedCompilation.

Import
  PABoundedRawCodedRestrictedPAOpenShellArithmeticCarriedCompilation.

Check raw_carrierRestrictedProof_endpoint_context_bounded.
Check PA_proves_coqRestrictedPAOpenEndpointContextBoundedSourceFormula.
Check PA_proves_restrictedPAOpenEndpointContextAtomicAdequacyFormula.
Check coqRestrictedPAOpenShellAdmissibleTemplate_expanded.
Check raw_coqRestrictedPAOpenShellAdmissibilityLawTemplate_valid.
Check PA_proves_coqRestrictedPAOpenShellAdmissibilitySourceFormula.
Check raw_codedPALocalProof_restrictedPAOpenShellAdmissibilityLaw_on_witnessed_base.
Check raw_codedPALocalProof_to_restrictedPABridgeBodyDirectContext.
Check raw_codedPALocalProof_same_restrictedPABridgeBody_witnessedTail_transport.
Check raw_coqRestrictedPAOpenShell_arithmetic_premise_roots.
Check raw_coqRestrictedPAOpenShell_formula_coverage_premise_root.
Check raw_coqRestrictedPAOpenShell_admissible_growing.
Check raw_coqRestrictedPAOpenShell_context_bounded_growing.
Check raw_coqRestrictedPAOpenShell_context_adequate_growing.
Check raw_coqRestrictedPAOpenShell_context_bounds_and_adequacy_growing.

Print Assumptions raw_carrierRestrictedProof_endpoint_context_bounded.
Print Assumptions PA_proves_coqRestrictedPAOpenEndpointContextBoundedSourceFormula.
Print Assumptions PA_proves_restrictedPAOpenEndpointContextAtomicAdequacyFormula.
Print Assumptions coqRestrictedPAOpenShellAdmissibleTemplate_expanded.
Print Assumptions raw_coqRestrictedPAOpenShellAdmissibilityLawTemplate_valid.
Print Assumptions PA_proves_coqRestrictedPAOpenShellAdmissibilitySourceFormula.
Print Assumptions raw_codedPALocalProof_restrictedPAOpenShellAdmissibilityLaw_on_witnessed_base.
Print Assumptions raw_codedPALocalProof_to_restrictedPABridgeBodyDirectContext.
Print Assumptions raw_codedPALocalProof_same_restrictedPABridgeBody_witnessedTail_transport.
Print Assumptions raw_coqRestrictedPAOpenShell_arithmetic_premise_roots.
Print Assumptions raw_coqRestrictedPAOpenShell_formula_coverage_premise_root.
Print Assumptions raw_coqRestrictedPAOpenShell_admissible_growing.
Print Assumptions raw_coqRestrictedPAOpenShell_context_bounded_growing.
Print Assumptions raw_coqRestrictedPAOpenShell_context_adequate_growing.
Print Assumptions raw_coqRestrictedPAOpenShell_context_bounds_and_adequacy_growing.
