(** Audit surface for covered Or-I-left recursive-child compilation. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftRecursiveChildCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftRecursiveChildCompilation.

Check coqRestrictedPADirectOrIntroductionLeftDeepRestrictedTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDeepRestrictedCoreTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDeepAtomicTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDeepHasCoverageTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDeepRuleCoverageTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDeepAdmissibleTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDeepAdmissibleCoreTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDeepCommonCoverageTemplate.
Check
  coqRestrictedPADirectOrIntroductionLeftDeepCommonCoverageBodyTemplate.
Check coqRestrictedPADirectOrIntroductionLeftChildInterfaceResultTemplate.
Check
  coqRestrictedPADirectOrIntroductionLeftChildRestrictedCoreTemplate.

Check coqRestrictedPADirectOrIntroductionLeft_deep_restricted_shape.
Check coqRestrictedPADirectOrIntroductionLeft_deep_admissible_shape.
Check coqRestrictedPADirectOrIntroductionLeft_common_coverage_ex_shape.
Check
  coqRestrictedPADirectOrIntroductionLeft_child_context_truth_agreement.
Check coqRestrictedPADirectOrIntroductionLeft_child_truth_agreement.

Check coqRestrictedPADirectOrIntroductionLeftLawEndpointContext.
Check coqRestrictedPADirectOrIntroductionLeftLawBodyContext.
Check coqRestrictedPADirectOrIntroductionLeftCoverageEigenContext.
Check coqRestrictedPADirectOrIntroductionLeft_ready_restricted_in.
Check coqRestrictedPADirectOrIntroductionLeft_ready_prefix_in.
Check coqRestrictedPADirectOrIntroductionLeft_law_body_restricted_in.
Check coqRestrictedPADirectOrIntroductionLeft_law_body_admissible_in.
Check coqRestrictedPADirectOrIntroductionLeft_law_body_prefix_in.
Check coqRestrictedPADirectOrIntroductionLeft_law_body_case_in.
Check
  coqRestrictedPADirectOrIntroductionLeft_law_body_context_truth_in.
Check coqRestrictedPADirectOrIntroductionLeft_law_body_endpoint_in.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_inherited.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_coverage_body_in.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_restricted_in.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_admissible_in.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_prefix_in.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_case_in.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_context_truth_in.
Check coqRestrictedPADirectOrIntroductionLeft_eigen_endpoint_in.

Check
  coqRestrictedPADirectOrIntroductionLeftOpenedCoverageCompilerLawTemplate.
Check
  RawCoqRestrictedPADirectOrIntroductionLeftOpenedCoverageCompilerLawRoot.
Check
  coqRestrictedPADirectOrIntroductionLeftDynamicRestrictedRerootLawTemplate.
Check
  RawCoqRestrictedPADirectOrIntroductionLeftDynamicRestrictedRerootLawRoot.
Check
  raw_codedPALocalProof_recursiveChildLaw_of_openedCoverageCompiler.

Print Assumptions
  coqRestrictedPADirectOrIntroductionLeft_deep_restricted_shape.
Print Assumptions
  coqRestrictedPADirectOrIntroductionLeft_common_coverage_ex_shape.
Print Assumptions
  coqRestrictedPADirectOrIntroductionLeft_eigen_inherited.
Print Assumptions
  coqRestrictedPADirectOrIntroductionLeft_eigen_restricted_in.
Print Assumptions
  coqRestrictedPADirectOrIntroductionLeft_eigen_context_truth_in.
Print Assumptions
  raw_codedPALocalProof_recursiveChildLaw_of_openedCoverageCompiler.
