From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionWitnessShapes.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionWitnessShapes.

Check coqRestrictedPADirectAssumptionExpandedContextTruthTemplate.
Check coqRestrictedPADirectAssumptionExpandedContextBodyTemplate.
Check coqRestrictedPADirectAssumptionMembershipBodyTemplate.
Check coqRestrictedPADirectAssumptionExpandedContextTruth_shape.
Check coqRestrictedPADirectAssumptionMembership_shape.
Check coqRestrictedPADirectAssumptionShiftedContextTruthTemplate.
Check coqRestrictedPADirectAssumptionShiftedContextBodyTemplate.
Check coqRestrictedPADirectAssumptionShiftedContextTruth_shape.
Check coqRestrictedPADirectAssumptionFinalContextBodyTemplate.
Check coqRestrictedPADirectAssumptionFinalMembershipBodyTemplate.
Check coqRestrictedPADirectAssumptionFinalPointwiseTemplate.
Check coqRestrictedPADirectAssumptionFinalRightMembershipTemplate.
Check coqRestrictedPADirectAssumptionFinalContextBody_shape.
Check coqRestrictedPADirectAssumptionFinalMembershipBody_shape.
Check coqRestrictedPADirectAssumptionFinalRightMembership_shape.

Print Assumptions
  coqRestrictedPADirectAssumptionExpandedContextTruth_shape.
Print Assumptions coqRestrictedPADirectAssumptionMembership_shape.
Print Assumptions coqRestrictedPADirectAssumptionShiftedContextTruth_shape.
Print Assumptions coqRestrictedPADirectAssumptionFinalContextBody_shape.
Print Assumptions coqRestrictedPADirectAssumptionFinalMembershipBody_shape.
Print Assumptions coqRestrictedPADirectAssumptionFinalRightMembership_shape.
