From BoundedPAConsistency Require Import
  RawCodedFormulaTraversalChildAtomicAdequacyProofCompilation.

Import
  PABoundedRawCodedFormulaTraversalChildAtomicAdequacyProofCompilation.

Check codedFormulaTraversalChildAtomicAdequacyFormula.
Check raw_sat_codedFormulaTraversalChildAtomicAdequacyFormula_iff.
Check codedFormulaTraversalChildAtomicAdequacyFormula_raw_valid.
Check codedFormulaTraversalChildAtomicAdequacyFormula_sentence.
Check PA_proves_codedFormulaTraversalChildAtomicAdequacyFormula.
Check coqFormulaTraversalChildAtomicAdequacyInstanceTemplate_open.
Check
  raw_codedPALocalProofOf_formulaTraversalChildAtomicAdequacy_instance_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_formulaTraversalChildAtomicAdequacy_instance_on_witnessed_tail_under_prefix.

Print Assumptions
  codedFormulaTraversalChildAtomicAdequacyFormula_raw_valid.
Print Assumptions
  PA_proves_codedFormulaTraversalChildAtomicAdequacyFormula.
Print Assumptions
  raw_codedPALocalProofOf_formulaTraversalChildAtomicAdequacy_instance_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_formulaTraversalChildAtomicAdequacy_instance_on_witnessed_tail_under_prefix.
