(** Public surface and assumption audit for six-field master introduction. *)

From BoundedPAConsistency Require Import
  RawCodedTruthCertificateMasterIntroduction.

Import PABoundedRawCodedTruthCertificateMasterIntroduction.

Check rawSixFieldMasterIntroductionRoot.
Check raw_codedPALocalProofOf_sixFieldMaster_intro.
Check raw_codedPAProofOf_sixFieldMaster_intro.
Check raw_codedPAProofOf_sixFieldMaster_of_BProv.

Print Assumptions raw_codedPALocalProofOf_sixFieldMaster_intro.
Print Assumptions raw_codedPAProofOf_sixFieldMaster_intro.
Print Assumptions raw_codedPAProofOf_sixFieldMaster_of_BProv.
