From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectTraversalLeaf.

Module
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectTraversalLeafAudit.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectTraversalLeaf.

Check rawCoqRestrictedPANativeAxiomContextTruthRowContext.
Check RawCoqRestrictedPANativeAxiomContextTruthRowProofInputsOn.
Check raw_codedPALocalProofOf_member_assumption.
Check raw_coqRestrictedPANativeAxiomContextTruthRowProofInputs_exists.
Check RawCoqRestrictedPANativeAxiomContextTruthSynchronizedRowsCompiler.
Check
  raw_coqRestrictedPANativeAxiomContextTruthTraversalLeafCompiler_of_synchronized_rows.
Check
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthRootCompiler_of_synchronized_rows.

Print Assumptions raw_codedPALocalProofOf_member_assumption.
Print Assumptions
  raw_coqRestrictedPANativeAxiomContextTruthRowProofInputs_exists.
Print Assumptions
  raw_coqRestrictedPANativeAxiomContextTruthTraversalLeafCompiler_of_synchronized_rows.
Print Assumptions
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthRootCompiler_of_synchronized_rows.

End
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectTraversalLeafAudit.
