(** Public API and assumption audit for native aligned root adequacy. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeAlignedRootAtomicAdequacy.

Import
  PABoundedRawCodedDynamicTruthNativeAlignedRootAtomicAdequacy.

Check raw_dynamicTruthNativeLocalAligned_currentSigmaEvidence_atomically_adequate.
Check raw_dynamicTruthNativeLocalAligned_currentPiEvidence_atomically_adequate.
Check coqDynamicTruthNativeAlignedSigmaEvidenceConclusionTemplate_reroot.
Check coqDynamicTruthNativeAlignedPiEvidenceConclusionTemplate_reroot.
Check raw_dynamicTruthNativeAlignedSigmaEvidenceAtRootTerms_atomically_adequate_of_identification.
Check raw_dynamicTruthNativeAlignedPiEvidenceAtRootTerms_atomically_adequate_of_identification.
Check raw_dynamicTruthNativeAligned_evidenceAtRootTerms_atomically_adequate.
Check raw_dynamicTruthNativeAligned_impIntroduction_piLeft_atomically_adequate.

Print Assumptions
  raw_dynamicTruthNativeLocalAligned_currentSigmaEvidence_atomically_adequate.
Print Assumptions
  raw_dynamicTruthNativeLocalAligned_currentPiEvidence_atomically_adequate.
Print Assumptions
  raw_dynamicTruthNativeAlignedSigmaEvidenceAtRootTerms_atomically_adequate_of_identification.
Print Assumptions
  raw_dynamicTruthNativeAlignedPiEvidenceAtRootTerms_atomically_adequate_of_identification.
Print Assumptions
  raw_dynamicTruthNativeAligned_evidenceAtRootTerms_atomically_adequate.
Print Assumptions
  raw_dynamicTruthNativeAligned_impIntroduction_piLeft_atomically_adequate.
