(** Assumption and exact-slot audit for eigenvariable-sensitive universal
    introduction. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectUniversalIntroductionCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalIntroductionCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalIntroductionCase.

Check coqRestrictedPADirectUniversalIntroductionCaseTemplate.
Check coqRestrictedPADirectUniversalIntroduction_case_shape.
Check coqRestrictedPADirectUniversalIntroductionFormulaCodeTemplate.
Check coqRestrictedPADirectUniversalIntroductionContextShiftTemplate.
Check coqRestrictedPADirectUniversalIntroductionChildEndpointTemplate.
Check coqRestrictedPADirectUniversalIntroductionResultTruthTemplate.

Check
  coqRestrictedPADirectUniversalIntroductionUniversalClosureTemplate.
Check
  coqRestrictedPADirectUniversalIntroductionEigenSemanticLawTemplate.
Check RawCoqRestrictedPADirectUniversalIntroductionSemanticRoots.

Check coqRestrictedPADirectUniversalIntroductionCodeEqualityRootAt_valid.
Check coqRestrictedPADirectUniversalIntroductionFormulaCodeRootAt_valid.
Check coqRestrictedPADirectUniversalIntroductionContextShiftRootAt_valid.
Check coqRestrictedPADirectUniversalIntroductionChildEndpointRootAt_valid.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectUniversalIntroductionConclusion.
Check raw_coqRestrictedPADirectStrongStepUniversalIntroductionCaseRoot.

Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectUniversalIntroductionConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepUniversalIntroductionCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalIntroductionCaseAudit.
