(** Kernel-facing audit for guarded dependency-ordered callback assembly. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeGuardedDependencyOrderedCallbackCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeGuardedDependencyOrderedCallbackCompilation.

Check RawDynamicTruthNativeGuardedDependencyOrderedGrowingKernelCompilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedPositiveCallbacks_of_growing_kernel_compilers.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_guarded_growing_kernel_compilers.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedGrowingKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_guarded_growing_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_dependency_ordered_growing_kernel_compilers.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedSplitGrowingKernelCompilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedGrowingKernelCompilers_of_split.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedSplitGrowingKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedNormalizedCollisionResourceSplitGrowingKernelCompilers.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingSplitGrowingKernelCompilers.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingSplitGrowingKernelCompilers_of_normalized_collision_resources.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_legacy.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingSplitGrowingKernelCompilers_of_legacy_normalized_collision_resources.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedSplitGrowingKernelCompilers_of_normalized_collision_resources.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_normalized_collision_resources.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_dependency_ordered_split_growing_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedPositiveCallbacks_of_growing_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_guarded_growing_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_dependency_ordered_growing_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedGrowingKernelCompilers_of_split.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_dependency_ordered_split_growing_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedSplitGrowingKernelCompilers_of_normalized_collision_resources.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingSplitGrowingKernelCompilers_of_normalized_collision_resources.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_legacy.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingSplitGrowingKernelCompilers_of_legacy_normalized_collision_resources.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_normalized_collision_resources.
