From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaOrOpenedConstructorCodeProjection.

Import
  PABoundedRawCodedDynamicTruthSigmaOrOpenedConstructorCodeProjection.

Check coqDynamicTruthSigmaOrConstructorBranchSourceTemplate_exact.
Check coqDynamicTruthSigmaOrConstructorCodeProjectionProof_derives.
Check
  raw_codedPALocalProofOf_dynamicTruthSigmaOr_constructorCodeExistential_under_modeZeroRowPrefix.
Check coqDynamicTruthSigmaOrOpenedConstructorContextUnderModeZeroAt_success.
Check coqDynamicTruthSigmaOrOpenedConstructorContextUnderModeZeroAt_head.
Check coqDynamicTruthSigmaOrOpenedConstructorCodeRootTemplate_shape.
Check coqDynamicTruthSigmaOrOpenedConstructorCodeRootTemplate_neq_guarded.
Check
  raw_codedPALocalProofOf_dynamicTruthSigmaOr_openedConstructorCode_under_modeZeroRowPrefix.
Check
  raw_dynamicTruthSigmaOr_openedConstructorCodeGrowingCompilerUnderModeZeroRowPrefix.

Print Assumptions coqDynamicTruthSigmaOrConstructorBranchSourceTemplate_exact.
Print Assumptions coqDynamicTruthSigmaOrConstructorCodeProjectionProof_derives.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthSigmaOr_constructorCodeExistential_under_modeZeroRowPrefix.
Print Assumptions
  coqDynamicTruthSigmaOrOpenedConstructorContextUnderModeZeroAt_success.
Print Assumptions
  coqDynamicTruthSigmaOrOpenedConstructorContextUnderModeZeroAt_head.
Print Assumptions
  coqDynamicTruthSigmaOrOpenedConstructorCodeRootTemplate_shape.
Print Assumptions
  coqDynamicTruthSigmaOrOpenedConstructorCodeRootTemplate_neq_guarded.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthSigmaOr_openedConstructorCode_under_modeZeroRowPrefix.
Print Assumptions
  raw_dynamicTruthSigmaOr_openedConstructorCodeGrowingCompilerUnderModeZeroRowPrefix.
