(** Kernel-facing audit for the current-package-linked local callback. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeStagedPositiveSuccessor
  RawCodedDynamicTruthNativeLocalStagedCallbackCompilation.

Module
  PABoundedRawCodedDynamicTruthNativeLocalStagedCallbackCompilationAudit.

Import PABoundedRawCodedDynamicTruthNativeStagedPositiveSuccessor.
Import
  PABoundedRawCodedDynamicTruthNativeLocalStagedCallbackCompilation.

(** A carried proof is packaged with its original witness list and context;
    neither theorem has an empty-context premise. *)
Check raw_codedPAProofOf_dynamicTruthNativeLocal_of_witnessed_root.
Check raw_codedPAProofOf_dynamicTruthNativeLocalFieldRootOn.

(** The exact helper context contains the actual staged current package and
    is produced automatically from it by the forty-helper extension. *)
Check RawDynamicTruthNativeLocalCurrentHelperContextAt.
Check raw_dynamicTruthNativeLocalProofTraceAt_consecutive_alignment.
Check raw_dynamicTruthNativeLocalCurrentHelperContextAt_successor_trace.
Check raw_dynamicTruthNativeLocalCurrentHelperContextAt_exact_cases.
Check RawDynamicTruthNativeLocalAlignedPredecessorAt.
Check rawDynamicTruthNativeLocalAligned_decisionProjection.
Check rawDynamicTruthNativeLocalAligned_exclusiveProjection.
Check raw_dynamicTruthNativeLocalAligned_predecessorRoot_of_bridge.
Check
  raw_dynamicTruthNativeLocalCurrentHelperContextAt_exact_cases_aligned_with_next.
Check raw_dynamicTruthNativeLocalCurrentHelperContextAt_exists.

Goal forall M translation tail level
    currentLocal currentCrossLevel currentShift currentSubstitution
    currentAxiomSoundness currentFinal witnessList baseContext helperRoots,
  RawDynamicTruthNativeLocalCurrentHelperContextAt M translation
    tail level currentLocal currentCrossLevel currentShift
    currentSubstitution currentAxiomSoundness currentFinal
    witnessList baseContext helperRoots ->
  RawDynamicTruthNativeStagedPositiveCurrentAt M tail level
    currentLocal currentCrossLevel currentShift currentSubstitution
    currentAxiomSoundness currentFinal.
Proof.
  intros M translation tail level
    currentLocal currentCrossLevel currentShift currentSubstitution
    currentAxiomSoundness currentFinal witnessList baseContext helperRoots
    [hcurrent _].
  exact hcurrent.
Qed.

(** The only residual is the exact current/trace-linked staged root builder.
    Adequate positive selection and ordinary-certificate construction are
    concrete adapters. *)
Check RawDynamicTruthNativeLocalCurrentStagedRootBuilder.
Check RawDynamicTruthNativeLocalCurrentReducedStagedRootBuilder.
Check RawDynamicTruthNativeLocalDecisionExclusiveProofCompilerAt.
Check
  raw_dynamicTruthNativeLocalDecisionExclusiveProofCompilerAt_of_current_builder.
Check
  raw_dynamicTruthNativeLocalDecisionExclusiveProofCompilerAt_of_reduced_current_builder.
Check raw_dynamicTruthNativeLocalPositiveProof_exists_of_compilerAt.
Check raw_dynamicTruthNativeStagedNextLocalCompiler_of_current_builder.
Check raw_dynamicTruthNativeStagedNextLocalCompiler_of_reduced_current_builder.

Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeLocal_of_witnessed_root.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeLocalFieldRootOn.
Print Assumptions
  raw_dynamicTruthNativeLocalProofTraceAt_consecutive_alignment.
Print Assumptions
  raw_dynamicTruthNativeLocalCurrentHelperContextAt_successor_trace.
Print Assumptions
  raw_dynamicTruthNativeLocalCurrentHelperContextAt_exact_cases.
Print Assumptions
  raw_dynamicTruthNativeLocalCurrentHelperContextAt_exact_cases_aligned_with_next.
Print Assumptions
  raw_dynamicTruthNativeLocalCurrentHelperContextAt_exists.
Print Assumptions
  raw_dynamicTruthNativeLocalDecisionExclusiveProofCompilerAt_of_current_builder.
Print Assumptions
  raw_dynamicTruthNativeLocalDecisionExclusiveProofCompilerAt_of_reduced_current_builder.
Print Assumptions
  raw_dynamicTruthNativeLocalPositiveProof_exists_of_compilerAt.
Print Assumptions
  raw_dynamicTruthNativeStagedNextLocalCompiler_of_current_builder.
Print Assumptions
  raw_dynamicTruthNativeStagedNextLocalCompiler_of_reduced_current_builder.

End
  PABoundedRawCodedDynamicTruthNativeLocalStagedCallbackCompilationAudit.
