(** Audit of the conditional And/And and Or/Or row cells. *)

From FirstOrder Require Import Fol.
From BoundedPAConsistency Require Import
  RawCodedDynamicTruthBooleanBranchExclusivity.

Module PABoundedRawCodedDynamicTruthBooleanBranchExclusivityAudit.

Import PABoundedRawCodedDynamicTruthBooleanBranchExclusivity.

Check dynamicTruthSigmaAndEx8BranchFormula.
Check dynamicTruthPiAndEx8BranchFormula.
Check dynamicTruthSigmaOrEx8BranchFormula.
Check dynamicTruthPiOrEx8BranchFormula.
Check RawDynamicTruthSigmaAndEx8BranchAt.
Check RawDynamicTruthPiAndEx8BranchAt.
Check RawDynamicTruthSigmaOrEx8BranchAt.
Check RawDynamicTruthPiOrEx8BranchAt.
Check raw_sat_dynamicTruthSigmaAndEx8BranchFormula_iff.
Check raw_sat_dynamicTruthPiAndEx8BranchFormula_iff.
Check raw_sat_dynamicTruthSigmaOrEx8BranchFormula_iff.
Check raw_sat_dynamicTruthPiOrEx8BranchFormula_iff.

Check dynamicTruthAndConditionalCellFormula.
Check dynamicTruthOrConditionalCellFormula.
Check dynamicTruthAndConditionalCellFormula_raw_valid.
Check dynamicTruthOrConditionalCellFormula_raw_valid.
Check PA_proves_dynamicTruthAndConditionalCellFormula.
Check PA_proves_dynamicTruthOrConditionalCellFormula.

Check rawDynamicTruthSigmaAndEx8BranchCode.
Check rawDynamicTruthPiAndEx8BranchCode.
Check rawDynamicTruthSigmaOrEx8BranchCode.
Check rawDynamicTruthPiOrEx8BranchCode.
Check rawDynamicTruthAndConditionalCellCode.
Check rawDynamicTruthOrConditionalCellCode.
Check rawDynamicTruthAndConditionalCellCode_eq_quoted.
Check rawDynamicTruthOrConditionalCellCode_eq_quoted.
Check raw_codedPAProofOf_dynamicTruthAndConditionalCell.
Check raw_codedPAProofOf_dynamicTruthOrConditionalCell.
Check raw_codedPALocalProofOf_dynamicTruthAndConditionalCellCollision.
Check raw_codedPALocalProofOf_dynamicTruthOrConditionalCellCollision.

Print Assumptions dynamicTruthAndConditionalCellFormula_raw_valid.
Print Assumptions dynamicTruthOrConditionalCellFormula_raw_valid.
Print Assumptions PA_proves_dynamicTruthAndConditionalCellFormula.
Print Assumptions PA_proves_dynamicTruthOrConditionalCellFormula.
Print Assumptions raw_codedPAProofOf_dynamicTruthAndConditionalCell.
Print Assumptions raw_codedPAProofOf_dynamicTruthOrConditionalCell.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthAndConditionalCellCollision.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthOrConditionalCellCollision.

End PABoundedRawCodedDynamicTruthBooleanBranchExclusivityAudit.
