(** Kernel-facing audit for direct-shell guarded premise retention. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegration.

Module
  PABoundedRawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegrationAudit.

Import
  PABoundedRawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegration.

Check
  raw_codedPAGrowingTemplateLocalProofAt_of_shifted_assumption_under_fixed_prefix.
Check rawCoqRestrictedPADirectStrongStepDeepEndpointTail.
Check RawCoqRestrictedPADirectStrongStepGuardedPremiseRootsAt.
Check raw_coqRestrictedPADirectStrongStep_guardedPremiseRoots.
Check raw_coqTemplateShiftFive_after_renameEight.
Check raw_templateShiftRenamingMany_eq_add.
Check raw_templateShiftRenamingBy_after_shiftMany.
Check raw_templateFormulaRename_cutoff_after_shiftMany.
Check raw_templateContextShiftMany_map.
Check raw_templateContextRename_cutoff_after_shiftMany.
Check rawCoqRestrictedPADirectStrongStepGuardedOuterLiftRenaming.
Check raw_coqRestrictedPADirectStrongStepGuardedOuterLift_atomic_shape.
Check raw_coqRestrictedPADirectStrongStepGuardedOuterLift_boolean_atomic_shape.
Check raw_coqTemplateRenameN_eight_eq_add.
Check raw_templateFormulaRename_outerLift_of_shiftFive.
Check rawCoqRestrictedPADirectStrongStepGuardedLiftedImpDeepPrefix.
Check rawCoqRestrictedPADirectStrongStepGuardedLiftedBooleanDeepPrefix.
Check raw_coqRestrictedPADirectStrongStepGuardedLiftedImpDeepPrefix_split.
Check raw_coqRestrictedPADirectStrongStepGuardedLiftedBooleanDeepPrefix_split.
Check rawCoqRestrictedPADirectStrongStepGuardedEndpointImpFixedPrefix.
Check rawCoqRestrictedPADirectStrongStepGuardedEndpointBooleanFixedPrefix.
Check rawCoqRestrictedPADirectStrongStepGuardedEndpointImpDeepPrefix.
Check rawCoqRestrictedPADirectStrongStepGuardedEndpointBooleanDeepPrefix.
Check
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpDeepPrefix_restricted_member.
Check
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpDeepPrefix_rule_member.
Check
  raw_coqRestrictedPADirectStrongStepGuardedEndpointBooleanDeepPrefix_restricted_member.
Check
  raw_coqRestrictedPADirectStrongStepGuardedEndpointBooleanDeepPrefix_rule_member.
Check RawCoqRestrictedPADirectStrongStepGuardedEndpointPremiseRootsAt.
Check raw_coqRestrictedPADirectStrongStep_guardedEndpointPremiseRoots.
Check raw_coqRestrictedPADirectStrongStepGuardedEndpointPremise_shift13_eq_renamed13.
Check raw_coqRestrictedPADirectStrongStepGuardedOuterLift_atomic_shape_pre.
Check
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpAtomicRoot_of_premise_roots.
Check
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpDomain_eq_endpoint13.
Check
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpAtomicAndDomainRoots_of_premise_roots.

(** The structural shift and membership theorem is closed.  The represented
    assumption compiler and its six-root direct specialization inherit only
    the project's established relational choice principles. *)
Print Assumptions raw_coqTemplateShiftFive_after_renameEight.
Print Assumptions raw_templateFormulaRename_cutoff_after_shiftMany.
Print Assumptions raw_templateContextRename_cutoff_after_shiftMany.
Print Assumptions raw_coqRestrictedPADirectStrongStepGuardedOuterLift_atomic_shape.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepGuardedOuterLift_boolean_atomic_shape.
Print Assumptions raw_coqTemplateRenameN_eight_eq_add.
Print Assumptions raw_templateFormulaRename_outerLift_of_shiftFive.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepGuardedLiftedImpDeepPrefix_split.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepGuardedLiftedBooleanDeepPrefix_split.
Print Assumptions
  raw_coqRestrictedPADirectStrongStep_guardedEndpointPremiseRoots.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpAtomicRoot_of_premise_roots.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpDomain_eq_endpoint13.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepGuardedEndpointImpAtomicAndDomainRoots_of_premise_roots.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_of_shifted_assumption_under_fixed_prefix.
Print Assumptions raw_coqRestrictedPADirectStrongStep_guardedPremiseRoots.

End
  PABoundedRawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegrationAudit.
