From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionNativeClosureProjection.

Check raw_selectedAssumptionTail_of_nativeDirectTruthInputsWithClosureAt.
Check raw_selectedAssumptionTail_of_nativeDirectTruthInputsWithClosureAtFor.

Print Assumptions
  raw_selectedAssumptionTail_of_nativeDirectTruthInputsWithClosureAt.

Print Assumptions
  raw_selectedAssumptionTail_of_nativeDirectTruthInputsWithClosureAtFor.
