(** Assumption audit for successor-bound splitting in an appended row. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendRowLtSuccCases.

Import PABoundedRawCodedFourStateTableAppendRowLtSuccCases.

Check raw_codedPALocalProofOf_templateEqTransport_reverse_head.
Check raw_codedPALocalProofOf_templateEqTransport_reverse_head_parameter.
Check coqFourStateTableAppendEqualityTransportedNewStateLookupTemplate.
Check coqFourStateTableAppendEqualityModeFunctionalityArguments.
Check coqFourStateTableAppendEqualityFormulaFunctionalityArguments.
Check coqFourStateTableAppendEqualityAssignmentCodeFunctionalityArguments.
Check coqFourStateTableAppendEqualityAssignmentStepFunctionalityArguments.
Check coqFourStateTableAppendEqualityRowLookupTemplate.
Check coqFourStateTableAppendEqualityRowLookupTemplate_matches_second.
Check coqFourStateTableAppendModeLookupTemplate_beta_first.
Check coqFourStateTableAppendFormulaLookupTemplate_beta_first.
Check coqFourStateTableAppendAssignmentCodeLookupTemplate_beta_first.
Check coqFourStateTableAppendAssignmentStepLookupTemplate_beta_first.
Check coqBetaLookupFunctionalityFirstLookup_shift5_abstract_open.
Check
  coqFourStateTableAppendEqualityTransportedNewStateLookupTemplate_matches_first.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_branch_lookup_parameter.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_branch_lookup_parameter_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_lookup_functionality_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_four_equalities_on_witnessed_tail_under_prefix.
Check coqFourStateTableAppendEqualityFieldBindings.
Check coqFourStateTableAppendRowModeParameterName.
Check coqFourStateTableAppendRowFormulaParameterName.
Check coqFourStateTableAppendRowAssignmentCodeParameterName.
Check coqFourStateTableAppendRowAssignmentStepParameterName.
Check coqFourStateTableAppendConcreteRowFieldBindings.
Check coqFourStateTableAppendNamedClosedRowProductionTemplate.
Check coqFourStateTableAppendConcreteClosedRowProductionTemplate.
Check
  coqFourStateTableAppendNamedClosedRowProductionTemplate_replace_fields.
Check coqFourStateTableAppendConcreteRowVariables.
Check
  raw_codedPALocalProofOf_four_state_table_append_inherited_row_production.
Check RawFourStateTableAppendInheritedProductionInputsAt.
Check RawFourStateTableAppendInheritedLocalRootsAt.
Check raw_fourStateTableAppendInheritedLocalRootsAt_transport.
Check
  raw_fourStateTableAppendInheritedProductionInputsAt_of_local_roots.
Check
  raw_fourStateTableAppendInheritedProductionInputsAt_of_local_root_package.
Check
  raw_codedPALocalProofOf_four_state_table_append_inherited_row_production_growing_tail.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_growing_tail_under_prefix.
Check RawFourStateTableAppendEqualityProductionInputsAt.
Check raw_fourStateTableAppendEqualityProductionInputsAt_transport.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_production_cases_on_growing_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_production_cases_on_base_included_growing_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_cases_on_growing_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_cases_on_base_included_growing_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_of_inherited_traversal_on_growing_witnessed_tail_under_prefix.
Check
  raw_fourStateTableAppendEqualityProductionInputsAt_on_witnessed_row_context.
Check
  raw_fourStateTableAppendEqualityProductionInputsAt_on_witnessed_row_context_of_local_roots.
Check rawTemplateContextCodeOnTail_app.
Check
  raw_codedPALocalProofOf_universal_introduction_chain_on_self_shift_tail.
Check
  raw_codedPALocalProofOf_universal_introduction_chain_on_witnessed_tail.
Check
  raw_codedPAGrowingTemplateLocalProofAt_universal_introduction_chain.
Check
  raw_codedPALocalProofOf_existential_elimination_chain_on_self_shift_tail.
Check
  raw_codedPALocalProofOf_existential_elimination_chain_on_witnessed_tail.
Check
  raw_codedPAGrowingTemplateLocalProofAt_existential_elimination_chain.
Check
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_row_all5.
Check
  raw_fourStateTableAppendEqualityProductionInputsAt_on_witnessed_row_context_under_prefix_of_local_roots.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_of_inherited_local_roots_on_witnessed_row_context.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_of_inherited_local_roots_on_witnessed_row_context_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_implications_on_witnessed_row_context.
Check raw_templateContextCode_embedPAAxiomWitnesses.
Check raw_fourStateTableAppendRowContext_witnessed_tail_code.
Check raw_fourStateTableAppendRow_combined_witnessed_tail.
Check raw_fourStateTableAppendRowContext_combined_tail_code.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases_eliminate.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_branch_lookup.

Print Assumptions raw_codedPALocalProofOf_templateEqTransport_reverse_head.
Print Assumptions
  raw_codedPALocalProofOf_templateEqTransport_reverse_head_parameter.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_branch_lookup_parameter.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_branch_lookup_parameter_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_lookup_functionality_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_four_equalities_on_witnessed_tail_under_prefix.
Print Assumptions coqFourStateTableAppendEqualityFieldBindings.
Print Assumptions coqFourStateTableAppendConcreteRowFieldBindings.
Print Assumptions
  coqFourStateTableAppendNamedClosedRowProductionTemplate_replace_fields.
Print Assumptions coqFourStateTableAppendConcreteRowVariables.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_inherited_row_production.
Print Assumptions RawFourStateTableAppendInheritedProductionInputsAt.
Print Assumptions RawFourStateTableAppendInheritedLocalRootsAt.
Print Assumptions raw_fourStateTableAppendInheritedLocalRootsAt_transport.
Print Assumptions
  raw_fourStateTableAppendInheritedProductionInputsAt_of_local_roots.
Print Assumptions
  raw_fourStateTableAppendInheritedProductionInputsAt_of_local_root_package.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_inherited_row_production_growing_tail.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_growing_tail_under_prefix.
Print Assumptions RawFourStateTableAppendEqualityProductionInputsAt.
Print Assumptions raw_fourStateTableAppendEqualityProductionInputsAt_transport.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_production_cases_on_growing_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_production_cases_on_base_included_growing_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_cases_on_growing_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_cases_on_base_included_growing_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_of_inherited_traversal_on_growing_witnessed_tail_under_prefix.
Print Assumptions
  raw_fourStateTableAppendEqualityProductionInputsAt_on_witnessed_row_context.
Print Assumptions
  raw_fourStateTableAppendEqualityProductionInputsAt_on_witnessed_row_context_of_local_roots.
Print Assumptions rawTemplateContextCodeOnTail_app.
Print Assumptions
  raw_codedPALocalProofOf_universal_introduction_chain_on_self_shift_tail.
Print Assumptions
  raw_codedPALocalProofOf_universal_introduction_chain_on_witnessed_tail.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_universal_introduction_chain.
Print Assumptions
  raw_codedPALocalProofOf_existential_elimination_chain_on_self_shift_tail.
Print Assumptions
  raw_codedPALocalProofOf_existential_elimination_chain_on_witnessed_tail.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_existential_elimination_chain.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_four_state_table_append_row_all5.
Print Assumptions
  raw_fourStateTableAppendEqualityProductionInputsAt_on_witnessed_row_context_under_prefix_of_local_roots.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_of_inherited_local_roots_on_witnessed_row_context.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_of_inherited_local_roots_on_witnessed_row_context_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_implications_on_witnessed_row_context.
Print Assumptions
  coqFourStateTableAppendEqualityRowLookupTemplate_matches_second.
Print Assumptions coqFourStateTableAppendModeLookupTemplate_beta_first.
Print Assumptions coqFourStateTableAppendFormulaLookupTemplate_beta_first.
Print Assumptions
  coqFourStateTableAppendAssignmentCodeLookupTemplate_beta_first.
Print Assumptions
  coqFourStateTableAppendAssignmentStepLookupTemplate_beta_first.
Print Assumptions
  coqBetaLookupFunctionalityFirstLookup_shift5_abstract_open.
Print Assumptions
  coqFourStateTableAppendEqualityTransportedNewStateLookupTemplate_matches_first.
Print Assumptions raw_templateContextCode_embedPAAxiomWitnesses.
Print Assumptions raw_fourStateTableAppendRowContext_witnessed_tail_code.
Print Assumptions raw_fourStateTableAppendRow_combined_witnessed_tail.
Print Assumptions raw_fourStateTableAppendRowContext_combined_tail_code.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases_eliminate.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_branch_lookup.
