(** Public surface and assumption audit for the synchronized Eq-E source. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageDefinitions
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSource.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageDefinitions.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSource.

Check coqRestrictedPADirectEqualityEliminationEqualityChildInterfaceTemplate.
Check coqRestrictedPADirectEqualityEliminationMotiveChildInterfaceTemplate.
Check coqRestrictedPADirectEqualityEliminationChildInterfacesTemplate.
Check coqRestrictedPADirectEqualityEliminationOpenedCoverageLawTemplate.
Check RawCoqRestrictedPAEqualityEliminationEqualityChildInterface.
Check RawCoqRestrictedPAEqualityEliminationMotiveChildInterface.
Check raw_eqE_equality_child_interface_renamed_sat_iff.
Check raw_eqE_motive_child_interface_renamed_sat_iff.
Check raw_equalityElimination_openedCoverageLaw_valid.
Check coqRestrictedPADirectEqualityEliminationOpenedCoverageSource_reifies.
Check PA_proves_coqRestrictedPADirectEqualityEliminationOpenedCoverageSource.
Check rawDirect_equalityEliminationOpenedCoverageSource_substitution.

Print Assumptions raw_equalityElimination_openedCoverageLaw_valid.
Print Assumptions
  PA_proves_coqRestrictedPADirectEqualityEliminationOpenedCoverageSource.
Print Assumptions
  rawDirect_equalityEliminationOpenedCoverageSource_substitution.
