(** Audit surface for the grown direct universal-soundness bridge. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeFinalGrowingUniversalSoundnessBridgeDirect.

Import
  PABoundedRawCodedDynamicTruthNativeFinalGrowingUniversalSoundnessBridgeDirect.

Check
  RawDynamicTruthNativeFinalSelectedAxiomContextTruthDirectSupportCompiler.
Check RawCoqRestrictedPASelectedAxiomContextTruthDirectResidualSupport.
Check
  raw_coqRestrictedPASelectedAxiomContextTruthDirectSupport_of_residual.
Check
  RawDynamicTruthNativeFinalSelectedAxiomContextTruthDirectResidualSupportCompiler.
Check
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthDirectSupportCompiler_of_residual.
Check
  RawDynamicTruthNativeFinalConsistencyFromUniversalSoundnessDirectCompiler.
Check
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessDirectCompiler_of_open_and_axiom_support.
Check
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessDirectCompiler_of_open_and_residual.

Check RawDynamicTruthNativeFinalGrowingUniversalSoundnessCodeBridgeAt.
Check
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessCodeBridge_of_ordinary.

Check RawDynamicTruthNativeFinalGrowingUniversalSoundnessDirectBridgeAt.
Check
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessDirectBridge_of_ordinary.
Check
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessDirectBridge_of_ordinary_complete_fields.

Print Assumptions
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessDirectCompiler_of_open_and_axiom_support.
Print Assumptions
  raw_coqRestrictedPASelectedAxiomContextTruthDirectSupport_of_residual.
Print Assumptions
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthDirectSupportCompiler_of_residual.
Print Assumptions
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessDirectCompiler_of_open_and_residual.
Print Assumptions
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessCodeBridge_of_ordinary.
Print Assumptions
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessDirectBridge_of_ordinary.
Print Assumptions
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessDirectBridge_of_ordinary_complete_fields.
