From BoundedPAConsistency Require Import
  RawCodedDynamicTruthImpChildrenDomainProofCompilation.

Import
  PABoundedRawCodedDynamicTruthImpChildrenDomainProofCompilation.

Check raw_dynamicTruthSigmaRecordDomain_imp.
Check raw_dynamicTruthPiRecordDomain_imp.
Check raw_dynamicTruthRecordDomain_imp_children.
Check dynamicTruthImpChildrenDomainFormula.
Check raw_sat_dynamicTruthImpChildrenDomainFormula_iff.
Check dynamicTruthImpChildrenDomainFormula_sentence.
Check dynamicTruthImpChildrenDomainFormula_raw_valid.
Check PA_proves_dynamicTruthImpChildrenDomainFormula.
Check coqDynamicTruthImpChildrenDomainInstanceTemplate_open.
Check coqDynamicTruthImpChildrenDomainInstanceTemplate_imp2_shape.
Check
  raw_codedPALocalProofOf_dynamicTruthImpChildrenDomain_instance_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_dynamicTruthImpChildrenDomain_instance_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_dynamicTruthImpChildrenDomain_of_roots_on_witnessed_extension_under_prefix.

Print Assumptions raw_dynamicTruthSigmaRecordDomain_imp.
Print Assumptions raw_dynamicTruthPiRecordDomain_imp.
Print Assumptions raw_dynamicTruthRecordDomain_imp_children.
Print Assumptions dynamicTruthImpChildrenDomainFormula_raw_valid.
Print Assumptions PA_proves_dynamicTruthImpChildrenDomainFormula.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthImpChildrenDomain_instance_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthImpChildrenDomain_of_roots_on_witnessed_extension_under_prefix.
