(** Assumption and exact-slot audit for direct left conjunction
    elimination. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectAndEliminationLeftCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationLeftCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationLeftCase.

Check coqRestrictedPADirectAndEliminationLeftCaseTemplate.
Check coqRestrictedPADirectAndEliminationLeft_case_shape.
Check coqRestrictedPADirectAndEliminationLeftConclusionEqualityTemplate.
Check coqRestrictedPADirectAndEliminationLeftFormulaCodeTemplate.
Check coqRestrictedPADirectAndEliminationLeftChildEndpointTemplate.

Check coqRestrictedPADirectAndEliminationLeftRecursiveChildLawTemplate.
Check coqRestrictedPADirectAndEliminationLeftDynamicTruthLawTemplate.
Check RawCoqRestrictedPADirectAndEliminationLeftRecursiveChildLawRoot.
Check RawCoqRestrictedPADirectAndEliminationLeftDynamicTruthLawRoot.

Check
  coqRestrictedPADirectAndEliminationLeftConclusionEqualityRootAt_valid.
Check coqRestrictedPADirectAndEliminationLeftFormulaCodeRootAt_valid.
Check coqRestrictedPADirectAndEliminationLeftChildEndpointRootAt_valid.
Check
  coqRestrictedPADirectAndEliminationLeftConclusionTransportRootAt_valid.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectAndEliminationLeftConclusion.
Check raw_coqRestrictedPADirectStrongStepAndEliminationLeftCaseRoot.

Print Assumptions
  coqRestrictedPADirectAndEliminationLeftConclusionTransportRootAt_valid.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectAndEliminationLeftConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepAndEliminationLeftCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndEliminationLeftCaseAudit.
