(** Assumption and exact-slot audit for direct left disjunction
    introduction. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftCase.

Check coqRestrictedPADirectOrIntroductionLeftCaseTemplate.
Check coqRestrictedPADirectOrIntroductionLeft_case_shape.
Check coqRestrictedPADirectOrIntroductionLeftFormulaCodeTemplate.
Check coqRestrictedPADirectOrIntroductionLeftChildEndpointTemplate.
Check coqRestrictedPADirectOrIntroductionLeftFormulaTruthTemplate.
Check coqRestrictedPADirectOrIntroductionLeftResultTruthTemplate.

Check coqRestrictedPADirectOrIntroductionLeftRecursiveChildLawTemplate.
Check coqRestrictedPADirectOrIntroductionLeftDynamicTruthLawTemplate.
Check RawCoqRestrictedPADirectOrIntroductionLeftRecursiveChildLawRoot.
Check RawCoqRestrictedPADirectOrIntroductionLeftDynamicTruthLawRoot.

Check coqRestrictedPADirectOrIntroductionLeftCodeEqualityRootAt_valid.
Check coqRestrictedPADirectOrIntroductionLeftFormulaCodeRootAt_valid.
Check coqRestrictedPADirectOrIntroductionLeftChildEndpointRootAt_valid.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectOrIntroductionLeftConclusion.
Check raw_coqRestrictedPADirectStrongStepOrIntroductionLeftCaseRoot.

Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectOrIntroductionLeftConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepOrIntroductionLeftCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftCaseAudit.
