(** Compatibility umbrella for the split Eq-E template-validity proof. *)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageValiditySupport
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageParentData
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageEqualityChildValidity
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageMotiveChildValidity
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageLawAssembly.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceTemplateValidity.

Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageValiditySupport.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageParentData.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageEqualityChildValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageMotiveChildValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageLawAssembly.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceTemplateValidity.
