(** Audit surface for capture-avoiding template-parameter abstraction. *)

From BoundedPAConsistency Require Import
  RawCodedTemplateParameterAbstraction.

Import PABoundedRawCodedTemplateParameterAbstraction.

Check templateTermAbstractParameterAt.
Check templateTermsAbstractParameterAt.
Check templateFormulaAbstractParameterAt.
Check templateFormulaAbstractParameter.

Check templateOpeningSubstAt_after_shift.
Check templateOpeningSubstAt_parameter_at.
Check templateTermAbstractParameterAt_open.
Check templateTermsAbstractParameterAt_open.
Check templateFormulaAbstractParameterAt_open.
Check templateFormulaAbstractParameter_open.
Check templateTermReplaceParameterAt.
Check templateTermsReplaceParameterAt.
Check templateFormulaReplaceParameterAt.
Check templateFormulaReplaceParameter.
Check templateTermAbstractParameterAt_open_as_replace.
Check templateTermsAbstractParameterAt_open_as_replace.
Check templateFormulaAbstractParameterAt_open_as_replace.
Check templateFormulaAbstractParameter_open_as_replace.
Check templateTermAsPATerm.
Check templateFormulaAsPAFormula.
Check templateTermAsPATerm_sound.
Check templateFormulaAsPAFormula_sound.

Print Assumptions templateOpeningSubstAt_after_shift.
Print Assumptions templateTermAbstractParameterAt_open.
Print Assumptions templateFormulaAbstractParameterAt_open.
Print Assumptions templateFormulaAbstractParameter_open.
Print Assumptions templateTermAbstractParameterAt_open_as_replace.
Print Assumptions templateFormulaAbstractParameterAt_open_as_replace.
Print Assumptions templateFormulaAbstractParameter_open_as_replace.
Print Assumptions templateTermAsPATerm_sound.
Print Assumptions templateFormulaAsPAFormula_sound.
