From BoundedPAConsistency Require Import
  RawCodedDynamicTruthGlobalOpenedRowSelection.

Import PABoundedRawCodedDynamicTruthGlobalOpenedRowSelection.

Check coqDynamicTruthGlobalOpenedRootRowChoice_tagged_shape.
Check coqDynamicTruthGlobalOpenedRootRowRightTag_zero.
Check coqDynamicTruthGlobalOpenedRootRowLeftTag_one.
Check coqDynamicTruthGlobalOpenedRootRowLeftPayload_open_sequence.
Check coqDynamicTruthGlobalOpenedRootRowRightPayload_open_sequence.
Check raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_selected.

Print Assumptions coqDynamicTruthGlobalOpenedRootRowChoice_tagged_shape.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowRightTag_zero.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowLeftTag_one.
Print Assumptions
  coqDynamicTruthGlobalOpenedRootRowLeftPayload_open_sequence.
Print Assumptions
  coqDynamicTruthGlobalOpenedRootRowRightPayload_open_sequence.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_selected.
