(** Assumption audit for the fixed dynamic-truth syntax fragments. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthFixedSyntaxFragments.

Import PABoundedRawCodedDynamicTruthFixedSyntaxFragments.

Check dynamicTruthBaseTernaryFormula.
Check RawDynamicTruthBase.
Check raw_sat_dynamicTruthBaseTernaryFormula_iff.
Check DynamicTruthBaseTernaryScoped.
Check dynamicTruthBaseTernaryFormula_scoped.
Check dynamicTruthBaseTernaryFormula_application_scoped.
Check dynamicTruthBaseTernaryApplicationGraph_standard.
Check dynamicTruthBaseClosedFormula.
Check dynamicTruthBaseClosedFormula_sentence.

Check dynamicTruthSigmaRecordDomainTermAt.
Check dynamicTruthPiRecordDomainTermAt.
Check RawDynamicTruthSigmaRecordDomain.
Check RawDynamicTruthPiRecordDomain.
Check raw_sat_dynamicTruthSigmaRecordDomainTermAt_iff.
Check raw_sat_dynamicTruthPiRecordDomainTermAt_iff.

Check dynamicTruthStateTermAt.
Check RawDynamicTruthState.
Check dynamicTruthStateMemberTermAt.
Check RawDynamicTruthStateMember.
Check raw_sat_dynamicTruthStateTermAt_iff.
Check raw_sat_dynamicTruthStateMemberTermAt_iff.

Check dynamicTruthPositiveRecordBranchesTermAt.
Check RawDynamicTruthPositiveRecordBranches.
Check raw_sat_dynamicTruthPositiveRecordBranchesTermAt_iff.

Check dynamicTruthUniversalPrefixTermAt.
Check RawDynamicTruthUniversalPrefix.
Check raw_sat_dynamicTruthUniversalPrefixTermAt_iff.
Check dynamicTruthUniversalLowerApplicationTermAt.
Check RawDynamicTruthUniversalLowerApplication.
Check raw_sat_dynamicTruthUniversalLowerApplicationTermAt_iff.
Check dynamicTruthUniversalLeafTermAt.
Check RawDynamicTruthUniversalLeaf.
Check raw_sat_dynamicTruthUniversalLeafTermAt_iff.

Check dynamicTruthBaseFormulaCodeGraph.
Check dynamicTruthBase_quotedCode_standard.
Check dynamicTruthBaseFormulaCodeGraph_representation.
Check dynamicTruthBaseFormulaCodeGraph_raw_total.
Check dynamicTruthBaseFormulaCodeGraph_dynamic_base_total.
Check dynamicTruthBaseFormulaCodeGraph_zero_iff.

Print Assumptions raw_sat_dynamicTruthBaseTernaryFormula_iff.
Print Assumptions dynamicTruthBaseTernaryFormula_scoped.
Print Assumptions dynamicTruthBaseTernaryApplicationGraph_standard.
Print Assumptions dynamicTruthBaseClosedFormula_sentence.
Print Assumptions raw_sat_dynamicTruthSigmaRecordDomainTermAt_iff.
Print Assumptions raw_sat_dynamicTruthPiRecordDomainTermAt_iff.
Print Assumptions raw_sat_dynamicTruthStateTermAt_iff.
Print Assumptions raw_sat_dynamicTruthStateMemberTermAt_iff.
Print Assumptions raw_sat_dynamicTruthPositiveRecordBranchesTermAt_iff.
Print Assumptions raw_sat_dynamicTruthUniversalPrefixTermAt_iff.
Print Assumptions raw_sat_dynamicTruthUniversalLowerApplicationTermAt_iff.
Print Assumptions raw_sat_dynamicTruthUniversalLeafTermAt_iff.
Print Assumptions dynamicTruthBase_quotedCode_standard.
Print Assumptions dynamicTruthBaseFormulaCodeGraph_representation.
Print Assumptions dynamicTruthBaseFormulaCodeGraph_raw_total.
Print Assumptions dynamicTruthBaseFormulaCodeGraph_dynamic_base_total.
Print Assumptions dynamicTruthBaseFormulaCodeGraph_zero_iff.
