(** Audit for dependency-ordered common-context accumulation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeStagedPrerequisiteAccumulation.

Import PABoundedRawCodedDynamicTruthNativeStagedPrerequisiteAccumulation.

Check
  raw_dynamicTruthNativeCrossLevelStagedPrerequisites_of_current_and_local.
Check raw_dynamicTruthNativeShiftStagedPrerequisites_add_crossLevel.
Check raw_dynamicTruthNativeSubstitutionStagedPrerequisites_add_shift.
Check raw_dynamicTruthNativeAxiomStagedPrerequisites_add_substitution.

Print Assumptions
  raw_dynamicTruthNativeCrossLevelStagedPrerequisites_of_current_and_local.
Print Assumptions
  raw_dynamicTruthNativeShiftStagedPrerequisites_add_crossLevel.
Print Assumptions
  raw_dynamicTruthNativeSubstitutionStagedPrerequisites_add_shift.
Print Assumptions
  raw_dynamicTruthNativeAxiomStagedPrerequisites_add_substitution.
