(** Assumption audit for the paired dynamic-truth formula-code orbit. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPairedFormulaCodeOrbitGraph.

Import PABoundedRawCodedDynamicTruthPairedFormulaCodeOrbitGraph.

Check dynamicTruthPairedFormulaCodeOrbitGraph.
Check RawDynamicTruthPairedFormulaCodeOrbitAt.
Check raw_sat_dynamicTruthPairedFormulaCodeOrbitGraph_iff.
Check raw_dynamicTruthPairedFormulaCodeOrbitAt_zero_iff.
Check raw_dynamicTruthPairedFormulaCodeOrbitAt_succ_iff.
Check raw_sat_dynamicTruthPairedFormulaCodeOrbitGraph_zero_iff.
Check raw_sat_dynamicTruthPairedFormulaCodeOrbitGraph_succ_iff.
Check dynamicTruthPairedFormulaCodeOrbitGraph_adequate_total.
Check dynamicTruthPairedFormulaCodeOrbitGraph_raw_adequate_total.

Print Assumptions raw_sat_dynamicTruthPairedFormulaCodeOrbitGraph_iff.
Print Assumptions raw_dynamicTruthPairedFormulaCodeOrbitAt_zero_iff.
Print Assumptions raw_dynamicTruthPairedFormulaCodeOrbitAt_succ_iff.
Print Assumptions raw_sat_dynamicTruthPairedFormulaCodeOrbitGraph_zero_iff.
Print Assumptions raw_sat_dynamicTruthPairedFormulaCodeOrbitGraph_succ_iff.
Print Assumptions dynamicTruthPairedFormulaCodeOrbitGraph_adequate_total.
Print Assumptions dynamicTruthPairedFormulaCodeOrbitGraph_raw_adequate_total.
