(** Kernel audit for the direct-code strong-prefix finalizer compiler. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerCompilationDirect.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerCompilationDirect.

Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorTermDirectCode.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerVariableTermDirectCode.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorPrefixDirectCode.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorPrefixBodyDirectCode.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerGuardedPredicateDirectCode.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccDirectCode.

Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccDirectCode_quoted.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorPrefixDirectCode_as_all.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerGuardedPredicateDirectCode_as_imp.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_successor_direct_substitution.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_member_direct_substitution.

Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerDirectOpenContext.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerDirectOpenContext_selfShift.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerDirectPremiseRoot.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerDirectSuccessorPrefixRoot.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerDirectGuardedPredicateRoot.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerDirectPredicateRoot.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerDirectRoot.

Check
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizerDirect_of_ltSelfSucc.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerDirect_extendedContext_witnessed.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccDirect.
Check
  RawCoqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccDirectRootCompiler.
Check
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizerDirect_from_exact_arithmetic_leaf.
Check
  RawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerDirectRootCompiler.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerDirectRootCompiler_of_ltSelfSucc.

Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccDirectCode_quoted.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_successor_direct_substitution.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_member_direct_substitution.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerDirectOpenContext_selfShift.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizerDirect_of_ltSelfSucc.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccDirect.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizerDirect_from_exact_arithmetic_leaf.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerDirectRootCompiler_of_ltSelfSucc.
