(** Audit surface for aligned equality-reflexivity truth production. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectEqualityReflexivityAlignedTruthProduction.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityReflexivityAlignedTruthProductionAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityReflexivityAlignedTruthProduction.

Check
  coqRestrictedPADirectEqualityReflexivitySemanticContext_app_witnesses.
Check raw_equalityReflexivity_mode_zero_parent_source_aligned.

Check
  RawCoqRestrictedPADirectEqualityReflexivityConclusionTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectEqualityReflexivityAtomicTruthStandardTailCompiler.

Check raw_equalityReflexivityAtomicTruthLawRoot_of_conclusion_truth.
Check
  raw_equalityReflexivityAtomicTruthStandardTailCompiler_of_conclusion_truth.
Check
  raw_equalityReflexivityConclusionTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_equalityReflexivityAtomicTruthStandardTailCompiler_of_aligned_append_concrete_row.

Print Assumptions
  coqRestrictedPADirectEqualityReflexivitySemanticContext_app_witnesses.
Print Assumptions raw_equalityReflexivity_mode_zero_parent_source_aligned.
Print Assumptions raw_equalityReflexivityAtomicTruthLawRoot_of_conclusion_truth.
Print Assumptions
  raw_equalityReflexivityAtomicTruthStandardTailCompiler_of_conclusion_truth.
Print Assumptions
  raw_equalityReflexivityConclusionTruthStandardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_equalityReflexivityAtomicTruthStandardTailCompiler_of_aligned_append_concrete_row.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityReflexivityAlignedTruthProductionAudit.
