(** Focused assumption audit for the caller-prefix rank-zero relaxation.

    The historical normalized-application and dependency-ordered audit files
    intentionally enumerate hundreds of earlier interfaces.  Keeping the new
    checks here makes this boundary quick to recompile while still exposing
    the complete trusted-axiom footprint of every new public adapter. *)

From BoundedPAConsistency Require Import
  RawCodedPAGrowingTemplateRebase
  RawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification
  RawCodedDynamicTruthNativeZeroCanonicalApplicationNormalizedCompilation
  RawCodedDynamicTruthNativeDependencyOrderedCallbackCompilation.

Import PABoundedRawCodedPAGrowingTemplateRebase.
Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification.
Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalApplicationNormalizedCompilation.
Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCallbackCompilation.

Check raw_codedPALocalProof_templateSuffix.
Check
  raw_dynamicTruthZeroCanonicalGrowingFixedProductionOrRefutationCompilerUnderPrefixAt_app.
Check
  raw_dynamicTruthZeroCanonicalIndependentGrowingFixedProductionOrRefutationCompilersUnderPrefix_app.
Check
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_independent_growing_fixed_productions_or_refutations.
Check
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_state_fixed_productions_or_refutations.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingLogicalRootsUnderCallerPrefix.
Check
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilers_of_legacy.
Check
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilersInAllModels_of_legacy.

Print Assumptions raw_codedPALocalProof_templateSuffix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGrowingFixedProductionOrRefutationCompilerUnderPrefixAt_app.
Print Assumptions
  raw_dynamicTruthZeroCanonicalIndependentGrowingFixedProductionOrRefutationCompilersUnderPrefix_app.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_independent_growing_fixed_productions_or_refutations.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_state_fixed_productions_or_refutations.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingLogicalRootsUnderCallerPrefix.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilers_of_legacy.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilersInAllModels_of_legacy.
