(** Kernel-facing audit for the shared native successor-row identification. *)

From PAFiniteBasisReduction Require Import
  HierarchyReduction CanonicalSelectorPA FiniteBetaCoding.
From BoundedPAConsistency Require Import
  RawCodedTemplateDirectStructuralTranslation
  RawCodedRestrictedPADerivationSoundnessExtendedRowIdentification.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessExtendedRowIdentificationAudit.

Import PAHierarchyReduction.
Import PACanonicalSelectorPA.
Import PAFiniteBetaCoding.
Import PABoundedRawCodedTemplateDirectStructuralTranslation.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessExtendedRowIdentification.

Check rawCoqRestrictedPAExtendedRowsTail.
Check rawCoqRestrictedPAExtendedRowsInputs.
Check rawCoqRestrictedPAExtendedRowsLowerPiPackage.
Check rawCoqRestrictedPAExtendedRowsLowerSigmaPackage.
Check rawCoqRestrictedPAExtendedRows_upper_term.
Check rawCoqRestrictedPAExtendedRows_embed_formula.
Check rawCoqRestrictedPAExtendedRows_sigma_domain_trace.
Check rawCoqRestrictedPAExtendedRows_pi_domain_trace.
Check rawCoqRestrictedPAExtendedRows_lowerPi_atom_code.
Check rawCoqRestrictedPAExtendedRows_lowerSigma_atom_code.
Check rawCoqRestrictedPAExtendedRows_lowerPi_identified.
Check rawCoqRestrictedPAExtendedRows_lowerSigma_identified.
Check rawCoqRestrictedPAExtendedRows_sigma_branches.
Check rawCoqRestrictedPAExtendedRows_pi_branches.
Check rawCoqRestrictedPAExtendedRows_sigma_row.
Check rawCoqRestrictedPAExtendedRows_pi_row.
Check raw_coqRestrictedPAExtendedRows_identify_native.

Print Assumptions rawCoqRestrictedPAExtendedRows_upper_term.
Print Assumptions rawCoqRestrictedPAExtendedRows_sigma_domain_trace.
Print Assumptions rawCoqRestrictedPAExtendedRows_lowerPi_identified.
Print Assumptions rawCoqRestrictedPAExtendedRows_lowerSigma_identified.
Print Assumptions rawCoqRestrictedPAExtendedRows_sigma_row.
Print Assumptions rawCoqRestrictedPAExtendedRows_pi_row.
Print Assumptions raw_coqRestrictedPAExtendedRows_identify_native.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessExtendedRowIdentificationAudit.
