(** Kernel-facing audit for guarded dependency-ordered callback assembly. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeGuardedDependencyOrderedCallbackCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeGuardedDependencyOrderedCallbackCompilation.

Check RawDynamicTruthNativeGuardedDependencyOrderedGrowingKernelCompilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedPositiveCallbacks_of_growing_kernel_compilers.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_guarded_growing_kernel_compilers.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedGrowingKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_guarded_growing_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_dependency_ordered_growing_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedPositiveCallbacks_of_growing_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_guarded_growing_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_guarded_dependency_ordered_growing_kernel_compilers.
