(** Assumption audit for the guarded rank-zero fixed-production boundary. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroGuardedFixedProductionBoundary.

Module
  PABoundedRawCodedDynamicTruthNativeZeroGuardedFixedProductionBoundaryAudit.

Import
  PABoundedRawCodedDynamicTruthNativeZeroGuardedFixedProductionBoundary.

(** The inherited-row path is parametric in the selected direct translation;
    its sole rank-zero premise is the reserved append-bound equality. *)
Check raw_dynamicTruthZeroCanonicalDirect_append_below_parameter_zero.
Check
  raw_dynamicTruthZeroCanonicalDirect_appendInheritedRowResourcesAtRootTermsUnderPrefix_on_standardWitnessTail_of_append_root.
Check
  raw_dynamicTruthZeroCanonicalDirect_guardedAppendInheritedRowResourcesUnderPrefix_on_standardWitnessTail.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedAppendInheritedRowResourcesUnderPrefix_on_standardWitnessTail.

(** The payload endpoints preserve that same translation through fixed-row
    attachment and synchronization of the two independent witness batches. *)
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedAppendRowKernelPayload_on_standardWitnessTail_of_growing_fixed_production.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedAppendRowKernelPayloadPairUnderPrefix_of_independent_growing_fixed_productions_or_refutations.

(** The precise selected-translation residue and its caller-suffix reduction. *)
Check
  RawDynamicTruthZeroCanonicalIdentifiedGuardedFixedDeepIndependentGrowingFixedProductionOrRefutationCompilers.
Check
  RawDynamicTruthZeroCanonicalIdentifiedGuardedDeepIndependentGrowingFixedProductionOrRefutationCompilersForAllCallers.
Check
  raw_dynamicTruthZeroCanonicalDirect_growingFixedProductionOrRefutationCompilerAtRootTermsUnderPrefixAt_app.
Check
  raw_dynamicTruthZeroCanonicalDirect_independentGrowingFixedProductionOrRefutationCompilersAtRootTermsUnderPrefix_app.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedDeepIndependentGrowingFixedProductionOrRefutationCompilersForAllCallers_of_fixed.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedFixedDeepIndependentGrowingFixedProductionOrRefutationCompilers_of_all_callers.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedFixedDeepIndependentGrowingFixedProductionOrRefutationCompilers_iff_all_callers.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedDeepAppendRowKernelPayloadPairForAllCallers.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedDeepAppendRowKernelPayloadPairForAllCallers_of_fixed.
Check
  RawDynamicTruthZeroCanonicalIdentifiedBooleanGuardedFixedDeepIndependentGrowingFixedProductionOrRefutationCompilers.
Check
  RawDynamicTruthZeroCanonicalIdentifiedGuardedCollisionFixedDeepIndependentGrowingFixedProductionOrRefutationCompilers.
Check
  raw_dynamicTruthZeroCanonicalIdentified_booleanGuardedDeepIndependentGrowingFixedProductionOrRefutationCompilersForCaller_of_fixed.
Check
  raw_dynamicTruthZeroCanonicalIdentified_booleanGuardedDeepAppendRowKernelPayloadPairForCaller_of_fixed.
Check
  raw_dynamicTruthZeroCanonicalIdentified_guardedCollisionAppendRowKernelPayloadPairsForCaller_of_fixed.

(** Kernel-computed obstruction to reusing the historical permuted roots by
    definitional conversion at either canonical mode. *)
Check coqDynamicTruthZeroCanonicalPermutedFixedProductionContext.
Check coqDynamicTruthZeroCanonicalGuardedFixedProductionContext.
Check coqDynamicTruthZeroCanonicalGuardedRootRenaming.
Check templateLiftRenamingMany.
Check coqDynamicTruthZeroCanonicalGuardedFixedProductionRenaming.
Check
  coqDynamicTruthZeroCanonicalPermutedFixedProductionContext_rename.
Check
  coqDynamicTruthZeroCanonicalFixedProductionConclusion_rename.
Check
  coqDynamicTruthZeroCanonicalPermutedFixedProductionContext_neq_guarded_zero.
Check
  coqDynamicTruthZeroCanonicalPermutedFixedProductionContext_neq_guarded_one.

Print Assumptions
  raw_dynamicTruthZeroCanonicalDirect_appendInheritedRowResourcesAtRootTermsUnderPrefix_on_standardWitnessTail_of_append_root.
Print Assumptions
  raw_dynamicTruthZeroCanonicalIdentified_guardedAppendRowKernelPayloadPairUnderPrefix_of_independent_growing_fixed_productions_or_refutations.
Print Assumptions
  raw_dynamicTruthZeroCanonicalIdentified_guardedDeepAppendRowKernelPayloadPairForAllCallers_of_fixed.
Print Assumptions
  raw_dynamicTruthZeroCanonicalIdentified_guardedCollisionAppendRowKernelPayloadPairsForCaller_of_fixed.
Print Assumptions
  coqDynamicTruthZeroCanonicalPermutedFixedProductionContext_rename.
Print Assumptions
  coqDynamicTruthZeroCanonicalFixedProductionConclusion_rename.
Print Assumptions
  coqDynamicTruthZeroCanonicalPermutedFixedProductionContext_neq_guarded_zero.
Print Assumptions
  coqDynamicTruthZeroCanonicalPermutedFixedProductionContext_neq_guarded_one.

End
  PABoundedRawCodedDynamicTruthNativeZeroGuardedFixedProductionBoundaryAudit.
