(** Kernel-facing audit for trace-linked native axiom-soundness leaves. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeAxiomSoundnessLeafRootCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeAxiomSoundnessLeafRootCompilation.

Check RawDynamicTruthNativeAxiomSoundnessLinkedRowsAt.
Check
  raw_dynamicTruthNativeAxiomSoundnessProofTraceAt_exposes_linked_rows.
Check raw_dynamicTruthNativeAxiomSoundnessProofTraceAt_of_linked_rows.
Check raw_dynamicTruthNativeAxiomSoundnessProofTraceAt_linked_rows_iff.

Check raw_dynamicTruthNativeAxiomDomain_target_atomically_adequate.
Check raw_dynamicTruthNativeAxiomApplication_target_atomically_adequate.
Check raw_dynamicTruthNativeAxiomAntecedent_atomically_adequate.
Check RawDynamicTruthNativeAxiomSoundnessTraceAdequacyAt.
Check raw_dynamicTruthNativeAxiomSoundnessLinkedRowsAt_adequacy.

Check dynamicTruthNativeAxiomWitnessBodyFormula.
Check rawDynamicTruthNativeAxiomWitnessBodyCode.
Check rawDynamicTruthNativeAxiomRecognitionCode.
Check rawDynamicTruthNativeAxiomAtomicAdequacyCode.
Check rawDynamicTruthNativeAxiomAssignmentDefinedCode.
Check rawDynamicTruthNativeAxiomRecognitionCode_eq_numeral.
Check rawDynamicTruthNativeAxiomSoundnessAntecedentCode_as_components.
Check rawDynamicTruthNativeAxiomContextOn.
Check rawDynamicTruthNativeAxiomDomainContextOn.
Check RawDynamicTruthNativeAxiomAntecedentProjectionRootsOn.
Check raw_dynamicTruthNativeAxiomAntecedentProjectionRootsOn.

Check rawDynamicTruthNativeAxiomShiftedDomainContext.
Check rawDynamicTruthNativeAxiomWitnessContext.
Check RawDynamicTruthNativeAxiomWitnessDomainLeavesOn.
Check RawDynamicTruthNativeAxiomLinkedWitnessLeafRootCompiler.
Check RawDynamicTruthNativeAxiomLinkedWitnessBodyLeafRootCompiler.
Check
  raw_dynamicTruthNativeAxiomLinkedWitnessLeafRootCompiler_of_body_leaf_compiler.
Check RawDynamicTruthNativeAxiomLocalRootOn.
Check raw_dynamicTruthNativeAxiomLocalRootOn_of_witness_domain_leaves.
Check raw_dynamicTruthNativeAxiomLocalRootOn_of_linked_compiler.
Check
  raw_dynamicTruthNativeAxiomLocalRootOn_witnessed_context_of_compiler.

Check
  RawDynamicTruthNativeAxiomLinkedWitnessLeafRootInterfaceAtEmptyBase.
Check
  raw_dynamicTruthNativeAxiomLinkedWitnessLeafRootInterfaceAtEmptyBase_of_compiler.
Check raw_dynamicTruthNativeAxiomLocalRootAt_of_empty_base.
Check
  raw_dynamicTruthNativeAxiomSoundnessLocalRootCompiler_of_linked_empty_base_witness_leaves.
Check
  raw_dynamicTruthNativeAxiomSoundnessLocalRootCompiler_of_linked_witness_leaf_compiler.
Check
  raw_dynamicTruthNativeAxiomSoundnessLocalRootCompiler_of_linked_witness_body_leaves.

Print Assumptions
  raw_dynamicTruthNativeAxiomSoundnessProofTraceAt_linked_rows_iff.
Print Assumptions
  raw_dynamicTruthNativeAxiomSoundnessLinkedRowsAt_adequacy.
Print Assumptions raw_dynamicTruthNativeAxiomAntecedentProjectionRootsOn.
Print Assumptions
  raw_dynamicTruthNativeAxiomLocalRootOn_of_witness_domain_leaves.
Print Assumptions
  raw_dynamicTruthNativeAxiomLinkedWitnessLeafRootCompiler_of_body_leaf_compiler.
Print Assumptions raw_dynamicTruthNativeAxiomLocalRootOn_of_linked_compiler.
Print Assumptions
  raw_dynamicTruthNativeAxiomLocalRootOn_witnessed_context_of_compiler.
Print Assumptions
  raw_dynamicTruthNativeAxiomSoundnessLocalRootCompiler_of_linked_empty_base_witness_leaves.
Print Assumptions
  raw_dynamicTruthNativeAxiomSoundnessLocalRootCompiler_of_linked_witness_leaf_compiler.
Print Assumptions
  raw_dynamicTruthNativeAxiomSoundnessLocalRootCompiler_of_linked_witness_body_leaves.
