From BoundedPAConsistency Require Import
  RawCodedTemplateTernaryApplication.

Import PABoundedRawCodedTemplateTernaryApplication.

Check RawCodedTermSyntax.
Check raw_codedTermShift_target_syntax.
Check RawCodedTernaryApplication.
Check standardTernaryApplication.
Check raw_codedTernaryApplication_standard.
Check standardTernarySubstitution.
Check standardTernaryApplication_eq_subst.
Check raw_codedTernaryApplication_target_atomically_adequate.
Check raw_codedTernaryApplication_exists.
Check RawCodedTernaryApplicationSelector.
Check raw_codedTernaryApplicationSelector_exists.
Check RawCodedTernaryApplicationShiftCommuting.
Check RawCodedTernaryApplicationOpeningCommuting.
Check RawCodedTernaryApplicationCommuting.
Check raw_codedTernaryApplication_unit_shift.
Check raw_codedTernaryApplication_single_opening.
Check RawCodedTernaryPredicateRootClosed.
Check standardFormulaShift_identity_of_scoped.
Check raw_codedFormulaShift_standard_scoped_identity.
Check dynamicTruthGlobalSigmaCode_ternary_application_exists.
Check dynamicTruthGlobalPiCode_ternary_application_exists.

Print Assumptions raw_codedTermShift_target_syntax.
Print Assumptions raw_codedTernaryApplication_standard.
Print Assumptions standardTernaryApplication_eq_subst.
Print Assumptions raw_codedTernaryApplication_target_atomically_adequate.
Print Assumptions raw_codedTernaryApplication_exists.
Print Assumptions raw_codedTernaryApplicationSelector_exists.
Print Assumptions raw_codedTernaryApplication_unit_shift.
Print Assumptions raw_codedTernaryApplication_single_opening.
Print Assumptions raw_codedFormulaShift_standard_scoped_identity.
Print Assumptions dynamicTruthGlobalSigmaCode_ternary_application_exists.
Print Assumptions dynamicTruthGlobalPiCode_ternary_application_exists.
