(** Standalone assumption audit for the concrete term and formula algebra
    used by opaque ternary application. *)

From BoundedPAConsistency Require Import
  RawCodedTermShiftProtection
  RawCodedTermOpeningShiftInterchange
  RawCodedFormulaShiftSubstitutionInterchange
  RawCodedFormulaShiftSubstitutionInterchangeInvariant
  RawCodedFormulaShiftSubstitutionInterchangeInduction
  RawCodedFormulaOperationConcreteLaws.

Import PABoundedRawCodedTermShiftProtection.
Import PABoundedRawCodedTermOpeningShiftInterchange.
Import PABoundedRawCodedFormulaShiftSubstitutionInterchange.
Import PABoundedRawCodedFormulaShiftSubstitutionInterchangeInvariant.
Import PABoundedRawCodedFormulaShiftSubstitutionInterchangeInduction.
Import PABoundedRawCodedFormulaOperationConcreteLaws.

Check raw_shiftedIndex_protection.
Check RawCodedTermShiftProtectionIndexBelow.
Check raw_codedTermShiftProtectionIndexBelow_all.
Check raw_codedTermShift_protection_endpoint.
Check raw_codedTermShift_protection.
Check raw_codedTermShift_protect_one.
Check raw_codedTermShift_protect_two.

Check raw_codedTermOpening_shift_variable_interchange.
Check RawCodedTermOpeningShiftInterchangeIndexBelow.
Check raw_codedTermOpeningShiftInterchangeIndexBelow_all.
Check raw_codedTermOpening_shift_interchange.

Check raw_codedFormulaShift_substitutionAtom_interchange.
Check RawCodedFormulaShiftSubstitutionInterchangeIndexBelow.
Check raw_codedFormulaShiftSubstitutionInterchangeIndexBelow_succ.
Check raw_codedFormulaShiftSubstitutionInterchangeIndexBelow_all.
Check raw_codedFormulaShift_substitution_interchange_at.
Check raw_codedFormulaShiftAtom_singleSubstitutionInterchange.
Check raw_codedFormulaShiftAtom_protectiveShiftStable.
Check raw_codedFormulaShiftAtom_concrete_laws.

Print Assumptions raw_codedTermShiftProtectionIndexBelow_all.
Print Assumptions raw_codedTermShift_protection.
Print Assumptions raw_codedTermShift_protect_two.
Print Assumptions raw_codedTermOpeningShiftInterchangeIndexBelow_all.
Print Assumptions raw_codedTermOpening_shift_interchange.
Print Assumptions raw_codedFormulaShift_substitutionAtom_interchange.
Print Assumptions raw_codedFormulaShiftSubstitutionInterchangeIndexBelow_succ.
Print Assumptions raw_codedFormulaShiftSubstitutionInterchangeIndexBelow_all.
Print Assumptions raw_codedFormulaShift_substitution_interchange_at.
Print Assumptions raw_codedFormulaShiftAtom_singleSubstitutionInterchange.
Print Assumptions raw_codedFormulaShiftAtom_protectiveShiftStable.
Print Assumptions raw_codedFormulaShiftAtom_concrete_laws.
