(** Assumption audit for exact strong-step endpoint atomic adequacy. *)

From BoundedPAConsistency Require Import
  RawCodedStrongStepProofEndpointAtomicAdequacyProofCompilation.

Import
  PABoundedRawCodedStrongStepProofEndpointAtomicAdequacyProofCompilation.

Check strongStepProofEndpointAtomicAdequacyFormula.
Check raw_sat_strongStepProofEndpointAtomicAdequacyFormula_iff.
Check strongStepProofEndpointAtomicAdequacyFormula_raw_valid.
Check PA_proves_strongStepProofEndpointAtomicAdequacyFormula.
Check coqStrongStepProofEndpointAtomicAdequacyLawTemplate_imp2_shape.
Check coqStrongStepProofEndpointAtomicAdequacyAtomicPremise_view.
Check coqStrongStepProofEndpointAtomicAdequacyRulePremise_view.
Check coqStrongStepProofEndpointAtomicAdequacyConclusion_view.
Check
  raw_codedPALocalProof_strongStepProofEndpointAtomicAdequacyLaw_on_witnessed_base.
Check
  raw_codedPALocalProof_strongStepProofEndpointAtomicAdequacy_of_roots_on_witnessed_extension.

Print Assumptions strongStepProofEndpointAtomicAdequacyFormula_raw_valid.
Print Assumptions PA_proves_strongStepProofEndpointAtomicAdequacyFormula.
Print Assumptions
  raw_codedPALocalProof_strongStepProofEndpointAtomicAdequacyLaw_on_witnessed_base.
Print Assumptions
  raw_codedPALocalProof_strongStepProofEndpointAtomicAdequacy_of_roots_on_witnessed_extension.
