(** Public API and assumption audit for arbitrary-root aligned decisions. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeAlignedArbitraryRootReadyDecision.

Import
  PABoundedRawCodedDynamicTruthNativeAlignedArbitraryRootReadyDecision.

Check raw_codedPALocalProofOf_openedEvidenceDecision_of_elimination_chain.
Check raw_codedPALocalProofOf_openedEvidenceDecision_on_standard_witness_extension_under_prefix.
Check coqDynamicTruthNativeAlignedDecisionBodyTemplate.
Check coqDynamicTruthNativeAlignedDecisionBodyTemplate_scoped_three.
Check raw_dynamicTruthNativeAlignedDecision_domains_identified.
Check raw_dynamicTruthNativeAlignedDecisionBody_identified.
Check raw_dynamicTruthNativeAlignedDecisionSource_identified.
Check coqDynamicTruthNativeAlignedImpIntroductionDecisionOpening_shape.
Check raw_dynamicTruthNativeAligned_impIntroduction_evidence_cross_identified.
Check raw_dynamicTruthNativeAligned_impIntroduction_readyEvidenceDecision_of_atomic_and_domain_roots.

Print Assumptions
  raw_codedPALocalProofOf_openedEvidenceDecision_of_elimination_chain.
Print Assumptions
  raw_codedPALocalProofOf_openedEvidenceDecision_on_standard_witness_extension_under_prefix.
Print Assumptions raw_dynamicTruthNativeAlignedDecision_domains_identified.
Print Assumptions raw_dynamicTruthNativeAlignedDecisionBody_identified.
Print Assumptions raw_dynamicTruthNativeAlignedDecisionSource_identified.
Print Assumptions
  raw_dynamicTruthNativeAligned_impIntroduction_evidence_cross_identified.
Print Assumptions
  raw_dynamicTruthNativeAligned_impIntroduction_readyEvidenceDecision_of_atomic_and_domain_roots.
