(** Authoritative API and assumption audit for the call-site substitution
    compiler reduction. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeSubstitutionCurrentPackageCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeSubstitutionCurrentPackageCompilation.

Check RawDynamicTruthNativeSubstitutionCurrentPackageProofCompiler.
Check
  raw_dynamicTruthNativeSubstitutionCurrentPackageProofCompiler_of_body_implication.
Check
  raw_dynamicTruthNativeStagedNextSubstitutionCompiler_of_currentPackageProofCompiler.
Check
  raw_dynamicTruthNativeStagedNextSubstitutionCompiler_of_body_implication_via_currentPackage.

Print Assumptions
  raw_dynamicTruthNativeSubstitutionCurrentPackageProofCompiler_of_body_implication.
Print Assumptions
  raw_dynamicTruthNativeStagedNextSubstitutionCompiler_of_currentPackageProofCompiler.
Print Assumptions
  raw_dynamicTruthNativeStagedNextSubstitutionCompiler_of_body_implication_via_currentPackage.
