From BoundedPAConsistency Require Import
  RawCodedDynamicTruthLocalFieldProjectionCompilation.

Import PABoundedRawCodedDynamicTruthLocalFieldProjectionCompilation.

Check rawDynamicTruthLocalDecisionProjectionRoot.
Check rawDynamicTruthLocalExclusiveProjectionRoot.
Check raw_codedPALocalProofOf_dynamicTruthLocalDecisionProjection.
Check raw_codedPALocalProofOf_dynamicTruthLocalExclusiveProjection.
Check RawDynamicTruthLocalDecisionExclusiveProjectedRootsAt.
Check raw_dynamicTruthLocalDecisionExclusiveProjectedRootsAt_of_local.
Check raw_codedPALocalProofOf_dynamicTruthLocalDecisionInstance.
Check raw_codedPALocalProofOf_dynamicTruthLocalExclusiveInstance.
Check
  raw_codedPALocalProofOf_dynamicTruthLocalEvidenceDecision_of_elimination_chain.
Check
  raw_codedPALocalProofOf_dynamicTruthLocalDecisionInstance_of_native_trace.
Check
  raw_codedPALocalProofOf_dynamicTruthLocalExclusiveInstance_of_native_trace.
Check
  raw_codedPALocalProofOf_dynamicTruthLocalEvidenceDecision_of_native_trace.

Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalDecisionProjection.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalExclusiveProjection.
Print Assumptions
  raw_dynamicTruthLocalDecisionExclusiveProjectedRootsAt_of_local.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalDecisionInstance.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalExclusiveInstance.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalEvidenceDecision_of_elimination_chain.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalDecisionInstance_of_native_trace.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalExclusiveInstance_of_native_trace.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthLocalEvidenceDecision_of_native_trace.
