(** Assumption audit for guarded native collision-matrix compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalGuardedMatrixCompilation.

Module
  PABoundedRawCodedDynamicTruthNativeLocalGuardedMatrixCompilationAudit.

Import
  PABoundedRawCodedDynamicTruthNativeLocalGuardedMatrixCompilation.

Check rawDynamicTruthGuardedImpCollisionFixedPAHelpers.
Check rawDynamicTruthReadyAndGuardedMixedQFPAHelpers.
Check rawDynamicTruthReadyAndGuardedMixedQFPAHelpers_length.
Check raw_fixedPAHelperBatchLocalProofs_app_prefix_firstn.
Check raw_dynamicTruthNativeLocal_helper_roots_of_42_helpers.
Check raw_dynamicTruthLocalRootAt_on_exclusive_context.
Check RawDynamicTruthNativeLocalGuardedExclusiveMatrixResourcesAt.
Check
  raw_dynamicTruthNativeLocalGuardedExclusiveMatrixResourcesAt_of_42_helpers.
Check raw_dynamicTruthNativeLocalExclusiveRootOn_of_rows_and_guarded_matrix.

Print Assumptions raw_fixedPAHelperBatchLocalProofs_app_prefix_firstn.
Print Assumptions raw_dynamicTruthNativeLocal_helper_roots_of_42_helpers.
Print Assumptions raw_dynamicTruthLocalRootAt_on_exclusive_context.
Print Assumptions
  raw_dynamicTruthNativeLocalGuardedExclusiveMatrixResourcesAt_of_42_helpers.
Print Assumptions
  raw_dynamicTruthNativeLocalExclusiveRootOn_of_rows_and_guarded_matrix.

End
  PABoundedRawCodedDynamicTruthNativeLocalGuardedMatrixCompilationAudit.
