(** Assumption audit for exact canonical rank-zero global applications. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroCanonicalTraceExactification.

Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalTraceExactification.

Check dynamicTruthZeroInputGlobalSigmaFormula_scoped.
Check dynamicTruthZeroInputGlobalPiFormula_scoped.
Check raw_dynamicTruthZeroInputGlobalSigma_root_closed.
Check raw_dynamicTruthZeroInputGlobalPi_root_closed.
Check dynamicTruthZeroInputGlobalSigmaApplicationFormula.
Check dynamicTruthZeroInputGlobalPiApplicationFormula.
Check dynamicTruthZeroInputGlobalSigmaApplicationFormula_scoped.
Check dynamicTruthZeroInputGlobalPiApplicationFormula_scoped.
Check raw_dynamicTruthZeroInputGlobalSigma_application_standard.
Check raw_dynamicTruthZeroInputGlobalPi_application_standard.
Check raw_dynamicTruthZeroInputGlobal_applications_exact.
Check raw_dynamicTruthZeroInputGlobalSigmaApplication_atomically_adequate.
Check raw_dynamicTruthZeroInputGlobalPiApplication_atomically_adequate.
Check dynamicTruthZeroSigmaSuccessorRow_native_shape.
Check dynamicTruthZeroPiSuccessorRow_native_shape.
Check dynamicTruthZeroLowerSigmaApplication.
Check dynamicTruthZeroLowerPiApplication.
Check dynamicTruthZeroLowerSigmaApplication_row_eq.
Check dynamicTruthZeroLowerPiApplication_row_eq.
Check dynamicTruthZeroClosedSuccessorRowFormula.
Check dynamicTruthZeroClosedSuccessorRow_native_shape.
Check raw_sat_dynamicTruthZeroLowerSigmaApplication_native_iff.
Check raw_sat_dynamicTruthZeroLowerPiApplication_native_iff.
Check raw_sat_dynamicTruthZeroClosedSuccessorRowFormula_native_iff.
Check dynamicTruthZeroGlobalTraversalBody_native_shape.
Check raw_sat_dynamicTruthZeroInputGlobalSigmaFormula_native_iff.
Check raw_sat_dynamicTruthZeroInputGlobalPiFormula_native_iff.
Check
  raw_sat_dynamicTruthZeroInputGlobalSigmaApplicationFormula_native_iff.
Check raw_sat_dynamicTruthZeroInputGlobalPiApplicationFormula_native_iff.
Check dynamicTruthZeroInputGlobalSigmaApplicationNativeForwardFormula.
Check dynamicTruthZeroInputGlobalPiApplicationNativeForwardFormula.
Check
  dynamicTruthZeroInputGlobalSigmaApplicationNativeForwardFormula_raw_valid.
Check dynamicTruthZeroInputGlobalPiApplicationNativeForwardFormula_raw_valid.
Check
  PA_proves_dynamicTruthZeroInputGlobalSigmaApplicationNativeForwardFormula.
Check PA_proves_dynamicTruthZeroInputGlobalPiApplicationNativeForwardFormula.
Check dynamicTruthZeroInputGlobalSigmaApplicationNativeBackwardFormula.
Check dynamicTruthZeroInputGlobalPiApplicationNativeBackwardFormula.
Check
  dynamicTruthZeroInputGlobalSigmaApplicationNativeBackwardFormula_raw_valid.
Check dynamicTruthZeroInputGlobalPiApplicationNativeBackwardFormula_raw_valid.
Check
  PA_proves_dynamicTruthZeroInputGlobalSigmaApplicationNativeBackwardFormula.
Check PA_proves_dynamicTruthZeroInputGlobalPiApplicationNativeBackwardFormula.

Print Assumptions dynamicTruthZeroInputGlobalSigmaFormula_scoped.
Print Assumptions dynamicTruthZeroInputGlobalPiFormula_scoped.
Print Assumptions raw_dynamicTruthZeroInputGlobalSigma_root_closed.
Print Assumptions raw_dynamicTruthZeroInputGlobalPi_root_closed.
Print Assumptions dynamicTruthZeroInputGlobalSigmaApplicationFormula_scoped.
Print Assumptions dynamicTruthZeroInputGlobalPiApplicationFormula_scoped.
Print Assumptions raw_dynamicTruthZeroInputGlobalSigma_application_standard.
Print Assumptions raw_dynamicTruthZeroInputGlobalPi_application_standard.
Print Assumptions raw_dynamicTruthZeroInputGlobal_applications_exact.
Print Assumptions
  raw_dynamicTruthZeroInputGlobalSigmaApplication_atomically_adequate.
Print Assumptions
  raw_dynamicTruthZeroInputGlobalPiApplication_atomically_adequate.
Print Assumptions dynamicTruthZeroSigmaSuccessorRow_native_shape.
Print Assumptions dynamicTruthZeroPiSuccessorRow_native_shape.
Print Assumptions dynamicTruthZeroLowerSigmaApplication_row_eq.
Print Assumptions dynamicTruthZeroLowerPiApplication_row_eq.
Print Assumptions dynamicTruthZeroClosedSuccessorRow_native_shape.
Print Assumptions raw_sat_dynamicTruthZeroLowerSigmaApplication_native_iff.
Print Assumptions raw_sat_dynamicTruthZeroLowerPiApplication_native_iff.
Print Assumptions
  raw_sat_dynamicTruthZeroClosedSuccessorRowFormula_native_iff.
Print Assumptions dynamicTruthZeroGlobalTraversalBody_native_shape.
Print Assumptions raw_sat_dynamicTruthZeroInputGlobalSigmaFormula_native_iff.
Print Assumptions raw_sat_dynamicTruthZeroInputGlobalPiFormula_native_iff.
Print Assumptions
  raw_sat_dynamicTruthZeroInputGlobalSigmaApplicationFormula_native_iff.
Print Assumptions
  raw_sat_dynamicTruthZeroInputGlobalPiApplicationFormula_native_iff.
Print Assumptions
  dynamicTruthZeroInputGlobalSigmaApplicationNativeForwardFormula_raw_valid.
Print Assumptions
  dynamicTruthZeroInputGlobalPiApplicationNativeForwardFormula_raw_valid.
Print Assumptions
  PA_proves_dynamicTruthZeroInputGlobalSigmaApplicationNativeForwardFormula.
Print Assumptions
  PA_proves_dynamicTruthZeroInputGlobalPiApplicationNativeForwardFormula.
Print Assumptions
  dynamicTruthZeroInputGlobalSigmaApplicationNativeBackwardFormula_raw_valid.
Print Assumptions
  dynamicTruthZeroInputGlobalPiApplicationNativeBackwardFormula_raw_valid.
Print Assumptions
  PA_proves_dynamicTruthZeroInputGlobalSigmaApplicationNativeBackwardFormula.
Print Assumptions
  PA_proves_dynamicTruthZeroInputGlobalPiApplicationNativeBackwardFormula.
