(** Authoritative API and assumption audit for the dependency-ordered
    call-site substitution reduction. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionBoundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionBoundary.

Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionTraceProofKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionTraceProofKernelCompilers_of_trace_proof.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageSubstitution_trace_proof_kernel_compilers.
Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionTraceProofKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionTraceProofKernelCompilersInAllModels_of_trace_proof.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageSubstitution_trace_proof_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageSubstitution_trace_proof_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionTraceProofKernelCompilers_of_trace_proof.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageSubstitution_trace_proof_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageSubstitutionTraceProofKernelCompilersInAllModels_of_trace_proof.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageSubstitution_trace_proof_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageSubstitution_trace_proof_kernel_compilers.
