(** Kernel-facing audit for native successor-row append normalization. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSuccessorRowsAppendNormalization.

Import PABoundedRawCodedDynamicTruthSuccessorRowsAppendNormalization.

Check coqDynamicTruthSharedSigmaSuccessorRowTemplate.
Check coqDynamicTruthSharedPiSuccessorRowTemplate.
Check coqDynamicTruthSharedSigmaSuccessorRowTemplate_scoped_13.
Check coqDynamicTruthSharedPiSuccessorRowTemplate_scoped_13.
Check coqDynamicTruthSharedSigmaSuccessorRowTemplate_append_fields_inert.
Check coqDynamicTruthSharedPiSuccessorRowTemplate_append_fields_inert.
Check coqDynamicTruthSharedSuccessorRows_append_production.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_row.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_code_equivalent_row_prefix.
Check coqDynamicTruthAppendRowBoundParameterName.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_and_inherited_row_roots.

Print Assumptions coqDynamicTruthSharedSigmaSuccessorRowTemplate_scoped_13.
Print Assumptions coqDynamicTruthSharedPiSuccessorRowTemplate_scoped_13.
Print Assumptions
  coqDynamicTruthSharedSigmaSuccessorRowTemplate_append_fields_inert.
Print Assumptions
  coqDynamicTruthSharedPiSuccessorRowTemplate_append_fields_inert.
Print Assumptions coqDynamicTruthSharedSuccessorRows_append_production.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_row.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_code_equivalent_row_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_successor_global_of_append_and_inherited_row_roots.
