(** Focused assumption audit for the caller-prefix rank-zero relaxation.

    The historical normalized-application and dependency-ordered audit files
    intentionally enumerate hundreds of earlier interfaces.  Keeping the new
    checks here makes this boundary quick to recompile while still exposing
    the complete trusted-axiom footprint of every new public adapter. *)

From BoundedPAConsistency Require Import
  RawCodedPAGrowingTemplateRebase
  RawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification
  RawCodedDynamicTruthNativeZeroCanonicalApplicationNormalizedCompilation
  RawCodedDynamicTruthNativeDependencyOrderedCallbackCompilation.

Import PABoundedRawCodedPAGrowingTemplateRebase.
Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification.
Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalApplicationNormalizedCompilation.
Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCallbackCompilation.

Check raw_codedPALocalProof_templateSuffix.
Check raw_codedPAGrowingTemplateLocalProofAt_suffix.
Check
  raw_dynamicTruthZeroCanonicalGrowingFixedProductionOrRefutationCompilerUnderPrefixAt_app.
Check
  raw_dynamicTruthZeroCanonicalIndependentGrowingFixedProductionOrRefutationCompilersUnderPrefix_app.
Check
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_independent_growing_fixed_productions_or_refutations.
Check
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_state_fixed_productions_or_refutations.
Check
  RawDynamicTruthNativeLocalZeroGrowingPredecessorRootCompilerUnderCallerPrefixOnCanonicalNormalizedResources.
Check
  raw_dynamicTruthNativeLocalZeroGrowingPredecessorRootCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_shifted_logical_roots.
Check
  raw_dynamicTruthNativeLocalZeroCanonicalEndpointResourcesCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_independent_growing_restricted_rule_roots.
Check
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_independent_growing_restricted_rule_roots_and_payload_pair.
Check
  raw_dynamicTruthNativeLocalZeroGrowingPredecessorRootCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_independent_growing_restricted_rule_roots_and_shifted_payload_pair.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingPredecessorRootUnderCallerPrefixInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingLogicalRootsUnderCallerPrefix.
Check
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingPredecessorRootUnderCallerPrefix.
Check
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingPredecessorRootUnderCallerPrefixInAllModels_of_local.
Check
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilers_of_legacy.
Check
  raw_dynamicTruthNativeDependencyOrderedLegacyLogicalZeroGrowingPredecessorRootUnderCallerPrefix.
Check
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilersInAllModels_of_legacy.

Print Assumptions raw_codedPALocalProof_templateSuffix.
Print Assumptions raw_codedPAGrowingTemplateLocalProofAt_suffix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGrowingFixedProductionOrRefutationCompilerUnderPrefixAt_app.
Print Assumptions
  raw_dynamicTruthZeroCanonicalIndependentGrowingFixedProductionOrRefutationCompilersUnderPrefix_app.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_independent_growing_fixed_productions_or_refutations.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_template_assumptions_and_state_fixed_productions_or_refutations.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingPredecessorRootCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_shifted_logical_roots.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroCanonicalEndpointResourcesCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_independent_growing_restricted_rule_roots.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_independent_growing_restricted_rule_roots_and_payload_pair.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingPredecessorRootCompilerUnderCallerPrefixOnCanonicalNormalizedResources_of_independent_growing_restricted_rule_roots_and_shifted_payload_pair.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingLogicalRootsUnderCallerPrefix.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingPredecessorRootUnderCallerPrefix.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingLogicalZeroGrowingPredecessorRootUnderCallerPrefixInAllModels_of_local.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilers_of_legacy.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedLegacyLogicalZeroGrowingPredecessorRootUnderCallerPrefix.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroGrowingFixedProductionOrRefutationProofResourceStrongStepKernelCompilersInAllModels_of_legacy.
