From BoundedPAConsistency Require Import
  RawCodedTemplateTripleUniversalOpening.

Import PABoundedRawCodedTemplateTripleUniversalOpening.

Check TemplateTermScoped.
Check TemplateTermsScoped.
Check TemplateFormulaScoped.
Check template_three_opening_substitutions_variable.
Check template_three_opening_substitutions_term.
Check template_three_opening_substitutions_formula.
Check templateUniversalOpenMany_all3_variables.
Check raw_template_all3_variables_elimination_chain.

Print Assumptions templateUniversalOpenMany_all3_variables.
Print Assumptions raw_template_all3_variables_elimination_chain.
