(** Assumption and interface audit for the consolidated direct rule cases. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectRuleCases.

Module PABoundedRawCodedRestrictedPADerivationSoundnessDirectRuleCasesAudit.

Import PABoundedRawCodedRestrictedPADerivationSoundnessDirectRuleCases.

(** The package exposes only the semantic residuals already advertised by
    the seventeen constructor modules. *)
Check RawCoqRestrictedPADirectRuleCaseSemanticRoots.
Check rawCoqRestrictedPADirectRuleCases_assumption.
Check rawCoqRestrictedPADirectRuleCases_impIntroductionRecursive.
Check rawCoqRestrictedPADirectRuleCases_impIntroductionTruth.
Check rawCoqRestrictedPADirectRuleCases_impElimination.
Check rawCoqRestrictedPADirectRuleCases_bottomElimination.
Check rawCoqRestrictedPADirectRuleCases_excludedMiddle.
Check rawCoqRestrictedPADirectRuleCases_andIntroduction.
Check rawCoqRestrictedPADirectRuleCases_andEliminationLeftRecursive.
Check rawCoqRestrictedPADirectRuleCases_andEliminationLeftTruth.
Check rawCoqRestrictedPADirectRuleCases_andEliminationRightRecursive.
Check rawCoqRestrictedPADirectRuleCases_andEliminationRightTruth.
Check rawCoqRestrictedPADirectRuleCases_orIntroductionLeftRecursive.
Check rawCoqRestrictedPADirectRuleCases_orIntroductionLeftTruth.
Check rawCoqRestrictedPADirectRuleCases_orIntroductionRightRecursive.
Check rawCoqRestrictedPADirectRuleCases_orIntroductionRightTruth.
Check rawCoqRestrictedPADirectRuleCases_orElimination.
Check rawCoqRestrictedPADirectRuleCases_universalIntroduction.
Check rawCoqRestrictedPADirectRuleCases_universalEliminationRecursive.
Check rawCoqRestrictedPADirectRuleCases_universalEliminationTruth.
Check rawCoqRestrictedPADirectRuleCases_existentialIntroduction.
Check rawCoqRestrictedPADirectRuleCases_existentialElimination.
Check rawCoqRestrictedPADirectRuleCases_equalityReflexivity.
Check rawCoqRestrictedPADirectRuleCases_equalityElimination.

(** The first theorem is precisely the seventeen-way dispatcher.  The
    second is its application to the independent exact strong-step shell. *)
Check
  raw_coqRestrictedPADirectStrongStepRuleCaseImplicationRoots_of_semantic_roots.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectStrongStep_of_rule_case_semantic_roots.

Print Assumptions
  raw_coqRestrictedPADirectStrongStepRuleCaseImplicationRoots_of_semantic_roots.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectStrongStep_of_rule_case_semantic_roots.

End PABoundedRawCodedRestrictedPADerivationSoundnessDirectRuleCasesAudit.
