(** Assumption audit for the closed six-source synchronized-row law. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsGrowingLaw.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsGrowingLaw.

Check coqRestrictedPANativeAxiomRowsGrowingReadyContext.
Check coqRestrictedPANativeAxiomRowsGrowingDeep_context.
Check coqRestrictedPANativeAxiomRowsGrowingAxiomTraversalRoot_derives.
Check coqRestrictedPANativeAxiomRowsGrowingOpenedTargetRoot_derives.
Check coqRestrictedPANativeAxiomRowsGrowingTargetRoot_derives.
Check coqRestrictedPANativeAxiomRowsGrowingAllWitnessesRoot_derives.
Check coqRestrictedPANativeAxiomRowsGrowingLawTemplate.
Check coqRestrictedPANativeAxiomRowsGrowingLawRoot_derives.

Print Assumptions coqRestrictedPANativeAxiomRowsGrowingDeep_context.
Print Assumptions
  coqRestrictedPANativeAxiomRowsGrowingAxiomTraversalRoot_derives.
Print Assumptions
  coqRestrictedPANativeAxiomRowsGrowingOpenedTargetRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsGrowingTargetRoot_derives.
Print Assumptions
  coqRestrictedPANativeAxiomRowsGrowingAllWitnessesRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsGrowingLawRoot_derives.
