(** Audit of the dependency boundary after discharging target refutation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedUniversalSoundnessBridgeBoundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedUniversalSoundnessBridgeBoundary.

Check RawDynamicTruthNativeFinalUniversalSoundnessBridgeCompiler.
Check
  raw_dynamicTruthNativeFinalUniversalSoundnessCompositionCompiler_of_bridge.

Check
  RawDynamicTruthNativeDependencyOrderedUniversalSoundnessBridgeKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedUniversalSoundnessKernelCompilers_of_bridge.
Check
  raw_dynamicTruthNativeDependencyOrderedKernelCompilers_of_universal_soundness_bridge.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_universal_soundness_bridge.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_universal_soundness_bridge.

Check
  RawDynamicTruthNativeDependencyOrderedUniversalSoundnessBridgeKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedUniversalSoundnessKernelCompilersInAllModels_of_bridge.
Check
  raw_dynamicTruthNativeDependencyOrderedKernelCompilersInAllModels_of_universal_soundness_bridge.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_universal_soundness_bridge.

Print Assumptions
  raw_dynamicTruthNativeFinalUniversalSoundnessCompositionCompiler_of_bridge.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedUniversalSoundnessKernelCompilers_of_bridge.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedKernelCompilers_of_universal_soundness_bridge.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_universal_soundness_bridge.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_universal_soundness_bridge.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_universal_soundness_bridge.
