(** Assumption audit for the guarded native zero/successor collision split. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalGuardedCollisionCaseSplit.

Import
  PABoundedRawCodedDynamicTruthNativeLocalGuardedCollisionCaseSplit.

Check
  RawDynamicTruthNativeLocalZeroGrowingGuardedCollisionRootsCompilerOnCurrentGuardedHelperContext.
Check
  RawDynamicTruthNativeLocalAlignedGrowingGuardedCollisionRootsCompilerOnWitnessedBase.
Check
  RawDynamicTruthNativeLocalZeroGuardedCollisionProofResourcesCompilerOnNormalizedResources.
Check
  raw_dynamicTruthNativeLocalZeroGrowingGuardedCollisionRootsCompilerOnCurrentGuardedHelperContext_of_normalized_proof_resources.
Check
  raw_dynamicTruthNativeLocalCurrentGrowingGuardedCollisionRootsBuilder_of_zero_and_witnessed_aligned.
Check
  raw_dynamicTruthNativeLocalCurrentGrowingGuardedCollisionRootsBuilder_of_zero_normalized_proof_resources_and_witnessed_aligned.

Print Assumptions
  raw_dynamicTruthNativeLocalCurrentGrowingGuardedCollisionRootsBuilder_of_zero_and_witnessed_aligned.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingGuardedCollisionRootsCompilerOnCurrentGuardedHelperContext_of_normalized_proof_resources.
Print Assumptions
  raw_dynamicTruthNativeLocalCurrentGrowingGuardedCollisionRootsBuilder_of_zero_normalized_proof_resources_and_witnessed_aligned.
