From BoundedPAConsistency Require Import
  RawCodedDynamicTruthDeepClosedDomainProjectionFields.

Module PABoundedRawCodedDynamicTruthDeepClosedDomainProjectionFieldsAudit.

Import PABoundedRawCodedDynamicTruthDeepClosedDomainProjectionFields.

Check
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total_of_deep_closed_orbit.
Check
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total_of_deep_closed_orbit.
Check dynamicTruthDeepClosedDomainProjectionFields_raw_proof_total.
Check
  dynamicTruthDeepClosedDomainProjectionFields_raw_proof_total_of_local_closure.
Check
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total_unconditional.
Check
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total_unconditional.
Check
  dynamicTruthDeepClosedDomainProjectionFields_raw_proof_total_unconditional.

Print Assumptions
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total_of_deep_closed_orbit.
Print Assumptions
  dynamicTruthPiDomainProjectionPositiveFieldGraph_raw_proof_total_of_deep_closed_orbit.
Print Assumptions
  dynamicTruthDeepClosedDomainProjectionFields_raw_proof_total_of_local_closure.
Print Assumptions
  dynamicTruthDeepClosedDomainProjectionFields_raw_proof_total_unconditional.

End PABoundedRawCodedDynamicTruthDeepClosedDomainProjectionFieldsAudit.
