From BoundedPAConsistency Require Import
  RawCodedTruthCertificateMasterInduction.

Import PABoundedRawCodedTruthCertificateMasterInduction.

Check RawSixFieldMasterDirectPackageAt.
Check sixFieldMasterDirectPackageFormula.
Check raw_sat_sixFieldMasterDirectPackageFormula_iff.
Check RawSixFieldMasterGraphDecomposition.
Check RawSixFieldMasterPackageBase.
Check RawSixFieldMasterPackageSuccessor.
Check RawSixFieldMasterInductionCallbacksInAllModels.
Check raw_sixFieldMasterDirectPackages_all.
Check raw_sixFieldMasterDirectPackage_to_compactSelector.
Check raw_compactSelectorPackages_all_of_sixFieldMaster.
Check
  compactUniformRestrictedPAConsistencyProvabilityFormula_raw_valid_of_sixFieldMaster.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_sixFieldMaster.

Print Assumptions raw_sat_sixFieldMasterDirectPackageFormula_iff.
Print Assumptions raw_sixFieldMasterDirectPackages_all.
Print Assumptions raw_sixFieldMasterDirectPackage_to_compactSelector.
Print Assumptions raw_compactSelectorPackages_all_of_sixFieldMaster.
Print Assumptions
  compactUniformRestrictedPAConsistencyProvabilityFormula_raw_valid_of_sixFieldMaster.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_sixFieldMaster.
