(** Audit surface for the represented same-context unary child compiler. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessSameContextUnaryChildInterfaceOpenedCoverageSource
  RawCodedRestrictedPADerivationSoundnessSameContextUnaryChildInterfaceOpenedCoverageCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessSameContextUnaryChildInterfaceOpenedCoverageSource.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessSameContextUnaryChildInterfaceOpenedCoverageCompilation.

Check CoqRestrictedPASameContextUnaryRule.
Check coqRestrictedPASameContextUnaryOpenedCoverageLawTemplate.
Check raw_sameContextUnary_openedCoverageLaw_valid.
Check PA_proves_coqRestrictedPASameContextUnaryOpenedCoverageSource.
Check rawDirect_sameContextUnaryOpenedCoverageSource_substitution.

Check coqRestrictedPASameContextUnaryReadyContext.
Check coqRestrictedPASameContextUnaryCoverageEigenContext.
Check coqRestrictedPASameContextUnaryReadyContext_app_witnesses.
Check coqRestrictedPASameContextUnaryCoverageEigenContext_app_witnesses.
Check raw_sameContextUnaryCoverageEigenContext_witnessed_code.

Check RawCoqRestrictedPASameContextUnaryOpenedCoverageCompilerLawRoot.
Check raw_sameContextUnaryChildInterfaceRoot_of_openedCoverageCompiler.
Check
  raw_codedPALocalProof_sameContextUnaryOpenedCoverageLaw_on_witnessed_base.
Check RawCoqRestrictedPADirectSelectedSameContextUnaryChildInterfaceTail.
Check raw_selectedSameContextUnaryChildInterfaceTail.
Check raw_sameContextUnaryChildInterface_standardTailCompiler.

Check raw_andEliminationLeftChildInterface_standardTailCompiler.
Check raw_andEliminationRightChildInterface_standardTailCompiler.
Check raw_orIntroductionRightChildInterface_standardTailCompiler.

Print Assumptions raw_sameContextUnary_openedCoverageLaw_valid.
Print Assumptions PA_proves_coqRestrictedPASameContextUnaryOpenedCoverageSource.
Print Assumptions
  rawDirect_sameContextUnaryOpenedCoverageSource_substitution.
Print Assumptions
  raw_sameContextUnaryChildInterfaceRoot_of_openedCoverageCompiler.
Print Assumptions
  raw_codedPALocalProof_sameContextUnaryOpenedCoverageLaw_on_witnessed_base.
Print Assumptions raw_selectedSameContextUnaryChildInterfaceTail.
Print Assumptions raw_sameContextUnaryChildInterface_standardTailCompiler.
Print Assumptions
  raw_andEliminationLeftChildInterface_standardTailCompiler.
Print Assumptions
  raw_andEliminationRightChildInterface_standardTailCompiler.
Print Assumptions
  raw_orIntroductionRightChildInterface_standardTailCompiler.
