(** Assumption audit for the paired rank-zero dynamic-truth code graph. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPairedBaseFormulaCodeGraph.

Import PABoundedRawCodedDynamicTruthPairedBaseFormulaCodeGraph.

Check dynamicTruthPiBaseTernaryFormula.
Check RawDynamicTruthPiBase.
Check raw_sat_dynamicTruthPiBaseTernaryFormula_iff.
Check dynamicTruthPiBaseTernaryFormula_scoped.
Check dynamicTruthPiBaseTernaryApplicationGraph_standard.
Check dynamicTruthPairedBaseFormulaCodeGraph.
Check RawDynamicTruthPairedBaseFormulaCodeAt.
Check dynamicTruthPairedBaseFormulaCodeGraph_numeral_representation.
Check dynamicTruthPairedBaseFormulaCodeGraph_representation.
Check dynamicTruthPairedBaseFormulaCodeGraph_raw_total.
Check dynamicTruthPairedBaseFormulaCodeGraph_paired_orbit_base_total.
Check dynamicTruthPairedBaseFormulaCodeGraph_quoted.

Print Assumptions raw_sat_dynamicTruthPiBaseTernaryFormula_iff.
Print Assumptions dynamicTruthPiBaseTernaryFormula_scoped.
Print Assumptions dynamicTruthPiBaseTernaryApplicationGraph_standard.
Print Assumptions dynamicTruthPairedBaseFormulaCodeGraph_numeral_representation.
Print Assumptions dynamicTruthPairedBaseFormulaCodeGraph_representation.
Print Assumptions dynamicTruthPairedBaseFormulaCodeGraph_raw_total.
Print Assumptions
  dynamicTruthPairedBaseFormulaCodeGraph_paired_orbit_base_total.
Print Assumptions dynamicTruthPairedBaseFormulaCodeGraph_quoted.
