From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroBooleanGuardedBranchCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeZeroBooleanGuardedBranchCompilation.

Check raw_dynamicTruthBooleanGuardedParentBranchRoots_transport.
Check
  raw_dynamicTruthBooleanGuardedBranchRoots_of_parent_and_evidence_on_witnessed_extension.
Check
  raw_dynamicTruthBooleanGuardedBranchRoots_on_witnessed_extension_of_parent_and_canonical_append_kernel_payload_pair.
Check
  raw_dynamicTruthBooleanGuardedBranchRoots_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pair.
Check
  raw_dynamicTruthBooleanGuardedDiagonalPair_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pair.
Check RawDynamicTruthLocalBooleanDiagonalPairRootsUnderTemplatePrefixAt.
Check
  raw_dynamicTruthLocalBooleanDiagonalPairRootsUnderTemplatePrefixAt_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pairs.

Print Assumptions raw_dynamicTruthBooleanGuardedParentBranchRoots_transport.
Print Assumptions
  raw_dynamicTruthBooleanGuardedBranchRoots_of_parent_and_evidence_on_witnessed_extension.
Print Assumptions
  raw_dynamicTruthBooleanGuardedBranchRoots_on_witnessed_extension_of_parent_and_canonical_append_kernel_payload_pair.
Print Assumptions
  raw_dynamicTruthBooleanGuardedBranchRoots_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pair.
Print Assumptions
  raw_dynamicTruthBooleanGuardedDiagonalPair_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pair.
Print Assumptions
  raw_dynamicTruthLocalBooleanDiagonalPairRootsUnderTemplatePrefixAt_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pairs.
