(** Assumption audit for canonical append-source identification. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification.

Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification.

Check dynamicTruthZeroCanonicalSigmaRowFormula.
Check dynamicTruthZeroCanonicalPiRowFormula.
Check coqFourStateTableAppendPermutedTemplateGlobalSource_zero_sigma.
Check coqFourStateTableAppendPermutedTemplateGlobalSource_zero_pi.
Check rawTemplateFormula_zeroCanonicalPermutedGlobalSource_sigma.
Check rawTemplateFormula_zeroCanonicalPermutedGlobalSource_pi.
Check
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_pair.
Check RawDynamicTruthZeroCanonicalPermutedAppendInputsAt.
Check RawDynamicTruthZeroCanonicalPermutedAppendInputsUnderPrefixAt.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofPairAt_dynamic_truth_zero_canonical_permuted_globals_of_inputs_under_prefix.
Check
  raw_dynamicTruthZeroCanonicalApplicationPair_of_permuted_append_inputs_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs.
Check
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_zero_canonical_permuted_globals_of_inputs.
Check
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_inputs.

Print Assumptions
  coqFourStateTableAppendPermutedTemplateGlobalSource_zero_sigma.
Print Assumptions
  coqFourStateTableAppendPermutedTemplateGlobalSource_zero_pi.
Print Assumptions rawTemplateFormula_zeroCanonicalPermutedGlobalSource_sigma.
Print Assumptions rawTemplateFormula_zeroCanonicalPermutedGlobalSource_pi.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_pair.
Print Assumptions RawDynamicTruthZeroCanonicalPermutedAppendInputsAt.
Print Assumptions RawDynamicTruthZeroCanonicalPermutedAppendInputsUnderPrefixAt.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofPairAt_dynamic_truth_zero_canonical_permuted_globals_of_inputs_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationPair_of_permuted_append_inputs_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_zero_canonical_permuted_globals_of_inputs.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_inputs.
