(** Assumption audit for concrete substitution/opening algebra. *)

From BoundedPAConsistency Require Import
  RawCodedFormulaSubstitutionAtomSourceSyntax
  RawCodedTermShiftAmountComposition
  RawCodedTermOpeningProtection
  RawCodedTermOpeningOpeningInterchangeInduction
  RawCodedTermOpeningUnitShiftCancellation
  RawCodedTermOpeningLiftCancellation
  RawCodedFormulaSubstitutionAtomProtective
  RawCodedFormulaSubstitutionAtomInterchange
  RawCodedFormulaSubstitutionAtomSubstitutionInterchangeInvariant
  RawCodedFormulaSubstitutionAtomSubstitutionInterchangeInduction
  RawCodedFormulaSubstitutionAtomConcreteLaws.

Import PABoundedRawCodedFormulaSubstitutionAtomSourceSyntax.
Import PABoundedRawCodedTermShiftAmountComposition.
Import PABoundedRawCodedTermOpeningProtection.
Import PABoundedRawCodedTermOpeningOpeningInterchangeInduction.
Import PABoundedRawCodedTermOpeningUnitShiftCancellation.
Import PABoundedRawCodedTermOpeningLiftCancellation.
Import PABoundedRawCodedFormulaSubstitutionAtomProtective.
Import PABoundedRawCodedFormulaSubstitutionAtomInterchange.
Import PABoundedRawCodedFormulaSubstitutionAtomSubstitutionInterchangeInvariant.
Import PABoundedRawCodedFormulaSubstitutionAtomSubstitutionInterchangeInduction.
Import PABoundedRawCodedFormulaSubstitutionAtomConcreteLaws.

Check raw_codedFormulaSubstitutionAtom_source_syntax.
Check raw_codedTermShift_amount_composition.
Check raw_codedTermOpening_protection.
Check raw_codedTermOpening_opening_interchange_with_cancellation.
Check raw_codedTermOpening_zero_after_unit_shift.
Check raw_codedTermOpening_lift_cancellation.
Check raw_codedFormulaSubstitutionAtom_protectiveShiftStable.
Check raw_codedFormulaSubstitutionAtom_substitutionAtom_interchange.
Check raw_codedFormulaSubstitutionAtomSubstitutionInterchangeIndexBelow_succ.
Check raw_codedFormulaSubstitutionAtomSubstitutionInterchangeIndexBelow_all.
Check raw_codedFormulaSubstitutionAtom_substitution_interchange_at.
Check raw_codedFormulaSubstitutionAtom_singleSubstitutionInterchange.
Check raw_codedFormulaSubstitutionAtom_concreteLawsOnSyntax.
Check raw_codedFormulaSubstitutionAtom_sourceSyntaxLaw.

Print Assumptions raw_codedFormulaSubstitutionAtom_source_syntax.
Print Assumptions raw_codedTermShift_amount_composition.
Print Assumptions raw_codedTermOpening_protection.
Print Assumptions raw_codedTermOpening_opening_interchange_with_cancellation.
Print Assumptions raw_codedTermOpening_zero_after_unit_shift.
Print Assumptions raw_codedTermOpening_lift_cancellation.
Print Assumptions raw_codedFormulaSubstitutionAtom_protectiveShiftStable.
Print Assumptions raw_codedFormulaSubstitutionAtom_substitutionAtom_interchange.
Print Assumptions
  raw_codedFormulaSubstitutionAtomSubstitutionInterchangeIndexBelow_succ.
Print Assumptions
  raw_codedFormulaSubstitutionAtomSubstitutionInterchangeIndexBelow_all.
Print Assumptions
  raw_codedFormulaSubstitutionAtom_substitution_interchange_at.
Print Assumptions
  raw_codedFormulaSubstitutionAtom_singleSubstitutionInterchange.
Print Assumptions raw_codedFormulaSubstitutionAtom_concreteLawsOnSyntax.
Print Assumptions raw_codedFormulaSubstitutionAtom_sourceSyntaxLaw.
