From BoundedPAConsistency Require Import
  RawCodedFormulaBoundAllCarrierBoundary.

Import PABoundedRawCodedFormulaBoundAllCarrierBoundary.

Check raw_formulaShift_eq_row_of_source.
Check raw_codedFormulaShift_source_atomically_adequate.
Check rawDirectTemplateFormula_atomically_adequate.
Check RawCodedFormulaBoundAtomicallyAdequateTotal.
Check coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyTemplate.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirectCode_view.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirectCode_atomically_adequate.
Check
  raw_coqRestrictedPADerivationSoundnessStrongPrefixDirectClosureRemainder_exists_of_bound_totality.

Print Assumptions raw_codedFormulaShift_source_atomically_adequate.
Print Assumptions rawDirectTemplateFormula_atomically_adequate.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixBodyDirectCode_atomically_adequate.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessStrongPrefixDirectClosureRemainder_exists_of_bound_totality.
