(** Kernel-facing audit for the positive substitution carrier syntax. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeSubstitutionCarrier.

Module PABoundedRawCodedDynamicTruthNativeSubstitutionCarrierAudit.

Import PABoundedRawCodedDynamicTruthNativeSubstitutionCarrier.

Check dynamicTruthNativeSubstitutionAll7.
Check dynamicTruthNativeSubstitutionSourceAdmissibleFormula.
Check dynamicTruthNativeSubstitutionCertificateTransportFormula.
Check dynamicTruthNativeSubstitutionStepCarrierFormula.
Check dynamicTruthNativeSubstitutionFieldCarrierFormula.
Check dynamicTruthNativeSubstitutionStepCarrierFormula_fixedLevel.
Check dynamicTruthNativeSubstitutionFieldCarrierFormula_fixedLevel.

Check dynamicTruthNativeSubstitutionFieldCodeTerm.
Check rawDynamicTruthNativeSubstitutionFieldCode.
Check raw_eval_dynamicTruthNativeSubstitutionFieldCodeTerm.
Check raw_sat_dynamicTruthNativeSubstitutionFieldCodeTermAt_iff.
Check rawDynamicTruthNativeSubstitutionFieldCode_quoted.
Check
  rawDynamicTruthNativeSubstitutionFieldCode_quoted_successor_level.

Check dynamicTruthNativeSubstitutionFixedLevelFieldFormula.
Check dynamicTruthNativeSubstitutionFixedLevelFieldFormula_closeN.
Check PA_proves_dynamicTruthNativeSubstitutionFixedLevelFieldFormula.
Check raw_dynamicTruthNativeSubstitutionFixedLevelField_quoted_proof.
Check rawDynamicTruthNativeSubstitutionFieldCode_standard_proof.

Print Assumptions
  dynamicTruthNativeSubstitutionStepCarrierFormula_fixedLevel.
Print Assumptions
  dynamicTruthNativeSubstitutionFieldCarrierFormula_fixedLevel.
Print Assumptions raw_eval_dynamicTruthNativeSubstitutionFieldCodeTerm.
Print Assumptions raw_sat_dynamicTruthNativeSubstitutionFieldCodeTermAt_iff.
Print Assumptions rawDynamicTruthNativeSubstitutionFieldCode_quoted.
Print Assumptions
  rawDynamicTruthNativeSubstitutionFieldCode_quoted_successor_level.
Print Assumptions
  PA_proves_dynamicTruthNativeSubstitutionFixedLevelFieldFormula.
Print Assumptions
  raw_dynamicTruthNativeSubstitutionFixedLevelField_quoted_proof.
Print Assumptions rawDynamicTruthNativeSubstitutionFieldCode_standard_proof.

End PABoundedRawCodedDynamicTruthNativeSubstitutionCarrierAudit.
