(** Kernel audit for the exact consistency-from-soundness middle seam. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyFromUniversalSoundness.

Import PABoundedRawCodedRestrictedPAConsistencyFromUniversalSoundness.

Check coqRestrictedPASoundnessLowerLevelParameterName.
Check coqRestrictedPASoundnessUpperLevelParameterName.
Check coqRestrictedPAContextTruthPredicateName.
Check coqRestrictedPAConclusionTruthPredicateName.

Check coqRestrictedPADerivationSoundnessRestrictedProofCoreTemplate.
Check coqRestrictedPADerivationSoundnessProofWideCertificatesTemplate.
Check coqRestrictedPADerivationSoundnessRestrictedProofTemplate.
Check coqRestrictedPADerivationSoundnessEndpointTemplate.
Check coqRestrictedPADerivationSoundnessAdmissibleCoreTemplate.
Check coqRestrictedPADerivationSoundnessCommonCoverageTemplate.
Check coqRestrictedPADerivationSoundnessAdmissibleTemplate.
Check coqRestrictedPADerivationSoundnessContextTruthTemplate.
Check coqRestrictedPADerivationSoundnessConclusionTruthTemplate.
Check coqRestrictedPAAxiomContextsTruthTemplate.
Check coqRestrictedPABottomTruthRefutationTemplate.
Check coqRestrictedPADerivationSoundnessPredicateTemplate.
Check coqRestrictedPADerivationSoundnessUniversalTemplate.
Check coqRestrictedPAConsistencyFromUniversalSoundnessTargetTemplate.
Check coqRestrictedPAConsistencyFromUniversalSoundnessBridgeTemplate.

Check rawCoqRestrictedPADerivationSoundnessPredicateCode.
Check rawCoqRestrictedPADerivationSoundnessUniversalCode.
Check rawCoqRestrictedPAAxiomContextsTruthCode.
Check raw_coqRestrictedPAAxiomContextsTruthCode_structural.
Check rawCoqRestrictedPABottomTruthRefutationCode.
Check raw_coqRestrictedPABottomTruthRefutationCode_structural.
Check rawCoqRestrictedPAConsistencyFromSoundnessTargetCode.
Check rawCoqRestrictedPAConsistencyFromSoundnessBridgeCode.
Check raw_coqRestrictedPADerivationSoundnessUniversalCode_view.
Check raw_coqRestrictedPAConsistencyFromSoundnessTargetCode_exact.
Check raw_coqRestrictedPAConsistencyFromSoundnessBridgeCode_view.

Check rawCoqRestrictedPAConsistencyBridgeContextCode.
Check rawCoqRestrictedPAConsistencyBridgeBodyContextCode.
Check RawCoqRestrictedPASelectedAxiomContextTruthSupport.
Check rawCoqRestrictedPAAxiomContextsTruthRoot.
Check raw_coqRestrictedPAAxiomContextsTruth_of_selected_support.
Check RawCoqRestrictedPAConsistencyFromUniversalSoundnessOpenCompiler.
Check rawCoqRestrictedPAConsistencyFromSoundnessBridgeRoot.
Check raw_coqRestrictedPAConsistencyFromSoundnessBridge_of_open.
Check RawDynamicTruthNativeFinalSelectedAxiomContextTruthSupportCompiler.
Check RawDynamicTruthNativeFinalConsistencyFromUniversalSoundnessCompiler.
Check
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessCompiler_of_open_and_axiom_support.

Print Assumptions
  raw_coqRestrictedPADerivationSoundnessUniversalCode_view.
Print Assumptions
  raw_coqRestrictedPAConsistencyFromSoundnessTargetCode_exact.
Print Assumptions
  raw_coqRestrictedPAConsistencyFromSoundnessBridgeCode_view.
Print Assumptions
  raw_coqRestrictedPAAxiomContextsTruthCode_structural.
Print Assumptions
  raw_coqRestrictedPABottomTruthRefutationCode_structural.
Print Assumptions
  raw_coqRestrictedPAAxiomContextsTruth_of_selected_support.
Print Assumptions
  raw_coqRestrictedPAConsistencyFromSoundnessBridge_of_open.
Print Assumptions
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessCompiler_of_open_and_axiom_support.
