(** Audit surface for the split growing predecessor callback. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalGrowingPredecessorStagedCallbackCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeLocalGrowingPredecessorStagedCallbackCompilation.

Check RawDynamicTruthNativeLocalReducedCurrentKernelTailInputsAt.
Check RawDynamicTruthNativeLocalReducedStagedRootsWithoutPredecessorAt.
Check raw_dynamicTruthNativeLocalReducedStagedRootsAt_of_predecessor_and_tail.
Check RawDynamicTruthNativeLocalCurrentGrowingPredecessorRootBuilder.
Check RawDynamicTruthNativeLocalZeroPredecessorRootCompiler.
Check RawDynamicTruthNativeLocalAlignedGrowingLogicalRootsCompiler.
Check
  raw_dynamicTruthNativeLocalCurrentGrowingPredecessorRootBuilder_of_zero_and_aligned_logical_roots.
Check
  RawDynamicTruthNativeLocalCurrentGrowingReducedStagedRemainderBuilder.
Check
  raw_dynamicTruthNativeLocalCurrentGrowingReducedStagedRootBuilder_of_predecessor_and_remainder.

Print Assumptions
  raw_dynamicTruthNativeLocalReducedStagedRootsAt_of_predecessor_and_tail.
Print Assumptions
  raw_dynamicTruthNativeLocalCurrentGrowingPredecessorRootBuilder_of_zero_and_aligned_logical_roots.
Print Assumptions
  raw_dynamicTruthNativeLocalCurrentGrowingReducedStagedRootBuilder_of_predecessor_and_remainder.
