From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionPointwiseMembership.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionPointwiseMembership.

Check coqRestrictedPADirectAssumptionFinalNativeTruthTemplate.
Check coqRestrictedPADirectAssumptionMembershipIndexContext.
Check templateRawDerives_impE.
Check coqRestrictedPADirectAssumptionPointwiseMembershipRoot.
Check coqRestrictedPADirectAssumptionFinalNativeTruth_shift.
Check coqRestrictedPADirectAssumption_shifted_pointwise_in.
Check coqRestrictedPADirectAssumptionPointwiseMembershipRoot_derives.

Print Assumptions templateRawDerives_impE.
Print Assumptions coqRestrictedPADirectAssumptionFinalNativeTruth_shift.
Print Assumptions
  coqRestrictedPADirectAssumptionPointwiseMembershipRoot_derives.
