From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessOrIntroductionLeftNativeClosureContinuation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessOrIntroductionLeftNativeClosureContinuation.

Check RawCoqRestrictedPADirectV2LiteralRows.
Check
  raw_remainingRuleCasesV2Compiler_of_literalRows_and_threeImpFrontiers_of_nativeClosureAtFor_of_dynamicLawAtEmpty.

Print Assumptions
  raw_remainingRuleCasesV2Compiler_of_literalRows_and_threeImpFrontiers_of_nativeClosureAtFor_of_dynamicLawAtEmpty.
