From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaSuccessorRowGraph.

Import PABoundedRawCodedDynamicTruthSigmaSuccessorRowGraph.

Set Printing Width 100.

Check dynamicTruthCoqLowerApplicationTermAt.
Check RawDynamicTruthCoqLowerApplication.
Check raw_sat_dynamicTruthCoqLowerApplicationTermAt_iff.
Check standardDynamicTruthCoqLowerApplication_eq_rename.
Check raw_dynamicTruthCoqLowerApplication_standard_rename.

Check dynamicTruthSigmaRowDomainTemplate.
Check dynamicTruthSigmaRowInstantiatedDomain.
Check dynamicTruthSigmaSuccessorRowFormula.
Check dynamicTruthSigmaSuccessorRowCodeTerm.
Check rawDynamicTruthSigmaSuccessorRowCode.
Check raw_eval_dynamicTruthSigmaSuccessorRowCodeTerm.
Check rawDynamicTruthSigmaSuccessorRowCode_quoted.
Check raw_dynamicTruthSigmaRowInstantiatedDomain_standard.

Check dynamicTruthSigmaSuccessorRowGraph.
Check RawDynamicTruthSigmaSuccessorRowAt.
Check raw_sat_dynamicTruthSigmaSuccessorRowGraph_iff.
Check raw_dynamicTruthSigmaSuccessorRow_standard.

Check RawDynamicTruthSigmaDomainStepTotal.
Check RawDynamicTruthCoqLowerApplicationTotal.
Check dynamicTruthSigmaSuccessorRowGraph_raw_total.

Print Assumptions raw_sat_dynamicTruthCoqLowerApplicationTermAt_iff.
Print Assumptions standardDynamicTruthCoqLowerApplication_eq_rename.
Print Assumptions raw_dynamicTruthCoqLowerApplication_standard_rename.
Print Assumptions raw_eval_dynamicTruthSigmaSuccessorRowCodeTerm.
Print Assumptions rawDynamicTruthSigmaSuccessorRowCode_quoted.
Print Assumptions raw_sat_dynamicTruthSigmaSuccessorRowGraph_iff.
Print Assumptions raw_dynamicTruthSigmaSuccessorRow_standard.
Print Assumptions dynamicTruthSigmaSuccessorRowGraph_raw_total.
