(** Assumption audit for universal represented assignment-definedness. *)

From BoundedPAConsistency Require Import
  RawCodedAssignmentUniversalDefinednessProofCompilation.

Import
  PABoundedRawCodedAssignmentUniversalDefinednessProofCompilation.

Check codedAssignmentUniversalDefinednessFormula.
Check PA_proves_codedAssignmentUniversalDefinednessFormula.
Check
  raw_codedPALocalProofOf_assignmentUniversalDefinedness_instance_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_assignmentUniversalDefinedness_four_instances_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_assignmentUniversalDefinedness_instance_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_assignmentDefinedThrough_local_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_assignmentDefinedThrough_local_numeral_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_assignmentDefinedThrough_local_numeral_on_witnessed_tail_under_prefix.
Check coqAssignmentUniversalDefinednessInstanceTemplate_predecessor_child.
Check
  raw_codedPALocalProofOf_assignmentDefinedThrough_predecessor_child_numeral_on_witnessed_tail_under_prefix.

Print Assumptions PA_proves_codedAssignmentUniversalDefinednessFormula.
Print Assumptions
  raw_codedPALocalProofOf_assignmentUniversalDefinedness_four_instances_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_assignmentDefinedThrough_local_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_assignmentDefinedThrough_local_numeral_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_assignmentDefinedThrough_local_numeral_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_assignmentDefinedThrough_predecessor_child_numeral_on_witnessed_tail_under_prefix.
