(** Strict assumption audit for the growing-tail same-context unary compiler. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessSameContextUnaryRecursiveChildStandardTailCompilation.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessSameContextUnaryRecursiveChildStandardTailCompilationAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessSameContextUnaryRecursiveChildStandardTailCompilation.

Check
  RawCoqRestrictedPASameContextUnaryChildInterfaceStandardTailCompilerAt.
Check
  RawCoqRestrictedPASameContextUnaryRecursiveChildLawStandardTailCompilerAt.
Check
  raw_sameContextUnary_recursiveChildLawStandardTailCompiler_of_interface.
Check
  raw_sameContextUnary_recursiveChildLawRootAtWitnesses_append_stable.

Check
  coqRestrictedPADirectSameContextUnary_andEliminationLeft_readyContext_app_witnesses.
Check
  coqRestrictedPADirectSameContextUnary_andEliminationRight_readyContext_app_witnesses.
Check
  coqRestrictedPADirectSameContextUnary_orIntroductionRight_readyContext_app_witnesses.

Check
  RawCoqRestrictedPADirectAndEliminationLeftChildInterfaceStandardTailCompiler.
Check
  RawCoqRestrictedPADirectAndEliminationRightChildInterfaceStandardTailCompiler.
Check
  RawCoqRestrictedPADirectOrIntroductionRightChildInterfaceStandardTailCompiler.
Check
  RawCoqRestrictedPADirectSameContextUnaryRecursiveStandardTailCompiler.
Check raw_sameContextUnaryRecursiveStandardTailCompiler_of_interfaces.

Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsAfterAndIntroductionExceptSameContextUnaryRecursive.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionExceptSameContextUnaryRecursiveStandardTailCompiler.
Check raw_afterAndIntroduction_of_sameContextUnaryRecursive_and_remainder.
Check
  raw_remainingAfterAndIntroductionCompiler_of_sameContextUnaryInterfaces.

Print Assumptions
  raw_sameContextUnary_recursiveChildLawStandardTailCompiler_of_interface.
Print Assumptions
  raw_sameContextUnaryRecursiveStandardTailCompiler_of_interfaces.
Print Assumptions
  raw_remainingAfterAndIntroductionCompiler_of_sameContextUnaryInterfaces.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessSameContextUnaryRecursiveChildStandardTailCompilationAudit.
