From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaOrGuardedCanonicalCodeRootAssumptionCompilation.

Import
  PABoundedRawCodedDynamicTruthSigmaOrGuardedCanonicalCodeRootAssumptionCompilation.

Check coqDynamicTruthSigmaOrGuardedCanonicalCodeRootTemplate_shape.
Check coqDynamicTruthSigmaOrGuardedCanonicalModeZeroRowPrefix_affine.
Check raw_codedPAStandardWitnessGrowingTemplateFormulaCompilerAt_of_member.
Check
  raw_dynamicTruthSigmaOrGuardedCanonical_codeRootGrowingCompilerUnderPrefixAt_of_member.
Check
  raw_dynamicTruthSigmaOrGuardedCanonical_codeRootGrowingOrRefutationCompilerUnderPrefixAt_of_member.
Check
  raw_dynamicTruthSigmaOrGuardedCanonical_independentGrowingThreeRootOrRefutationCompilersUnderPrefixAt_of_code_member.

Print Assumptions
  coqDynamicTruthSigmaOrGuardedCanonicalCodeRootTemplate_shape.
Print Assumptions
  coqDynamicTruthSigmaOrGuardedCanonicalModeZeroRowPrefix_affine.
Print Assumptions
  raw_codedPAStandardWitnessGrowingTemplateFormulaCompilerAt_of_member.
Print Assumptions
  raw_dynamicTruthSigmaOrGuardedCanonical_codeRootGrowingCompilerUnderPrefixAt_of_member.
Print Assumptions
  raw_dynamicTruthSigmaOrGuardedCanonical_codeRootGrowingOrRefutationCompilerUnderPrefixAt_of_member.
Print Assumptions
  raw_dynamicTruthSigmaOrGuardedCanonical_independentGrowingThreeRootOrRefutationCompilersUnderPrefixAt_of_code_member.
