(** Assumption audit for guarded canonical-append integration. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroGuardedCanonicalAppendIntegration.

Import
  PABoundedRawCodedDynamicTruthNativeZeroGuardedCanonicalAppendIntegration.

Check coqFourStateTableAppendAtGuardedRootTerms_zero_sigma.
Check coqFourStateTableAppendAtGuardedRootTerms_zero_pi.
Check rawTemplateFormula_zeroCanonicalGuardedGlobalSource_sigma.
Check rawTemplateFormula_zeroCanonicalGuardedGlobalSource_pi.
Check
  raw_dynamicTruthZeroCanonicalGuardedGlobalApplicationRoots_on_witnessed_extension_of_kernel_payload_pair.
Check
  raw_dynamicTruthImpGuardedEvidenceRoots_on_witnessed_extension_of_canonical_append_kernel_payload_pair.
Check
  raw_dynamicTruthImpGuardedBranchRoots_on_witnessed_extension_of_parent_and_canonical_append_kernel_payload_pair.

Print Assumptions coqFourStateTableAppendAtGuardedRootTerms_zero_sigma.
Print Assumptions coqFourStateTableAppendAtGuardedRootTerms_zero_pi.
Print Assumptions rawTemplateFormula_zeroCanonicalGuardedGlobalSource_sigma.
Print Assumptions rawTemplateFormula_zeroCanonicalGuardedGlobalSource_pi.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGuardedGlobalApplicationRoots_on_witnessed_extension_of_kernel_payload_pair.
Print Assumptions
  raw_dynamicTruthImpGuardedEvidenceRoots_on_witnessed_extension_of_canonical_append_kernel_payload_pair.
Print Assumptions
  raw_dynamicTruthImpGuardedBranchRoots_on_witnessed_extension_of_parent_and_canonical_append_kernel_payload_pair.
