(** Audit for the predecessor assignment-admissibility component. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPredecessorAdmissibilityAssignmentCompilation.

Import
  PABoundedRawCodedDynamicTruthPredecessorAdmissibilityAssignmentCompilation.

Check raw_dynamicTruthPredecessorStateTemplateContext_atomically_adequate.
Check
  raw_dynamicTruthPredecessorStateTemplateContext_app_atomically_adequate.
Check
  raw_dynamicTruthPredecessorLocalAssignmentRoot_on_witnessed_extension_under_prefix.
Check
  raw_dynamicTruthPredecessorLocalAssignmentRoot_on_witnessed_extension.
Check
  raw_dynamicTruthPredecessorLocalAdmissibility_on_witnessed_extension_under_prefix_of_atomic_and_domain.
Check
  raw_dynamicTruthPredecessorLocalAdmissibility_on_witnessed_extension_of_atomic_and_domain.

Print Assumptions
  raw_dynamicTruthPredecessorStateTemplateContext_atomically_adequate.
Print Assumptions
  raw_dynamicTruthPredecessorStateTemplateContext_app_atomically_adequate.
Print Assumptions
  raw_dynamicTruthPredecessorLocalAssignmentRoot_on_witnessed_extension_under_prefix.
Print Assumptions
  raw_dynamicTruthPredecessorLocalAssignmentRoot_on_witnessed_extension.
Print Assumptions
  raw_dynamicTruthPredecessorLocalAdmissibility_on_witnessed_extension_under_prefix_of_atomic_and_domain.
Print Assumptions
  raw_dynamicTruthPredecessorLocalAdmissibility_on_witnessed_extension_of_atomic_and_domain.
