(** Kernel-facing audit for the full Sigma-row domain projection. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaDomainProjectionProofCompilation.

Import
  PABoundedRawCodedDynamicTruthSigmaDomainProjectionProofCompilation.

Check coqDynamicTruthSigmaDomainProjectionFormula.
Check coqDynamicTruthSigmaDomainProjectionProof.
Check coqDynamicTruthSigmaDomainProjectionProof_derives.
Check coqDynamicTruthSigmaDomainProjectionFieldFormula.
Check coqDynamicTruthSigmaDomainProjectionFieldProof.
Check coqDynamicTruthSigmaDomainProjectionFieldProof_derives.

Check rawCoqDynamicTruthSigmaDomainProjectionCode.
Check rawDynamicTruthSigmaDomainProjectionCode.
Check rawCoqDynamicTruthSigmaDomainProjectionFieldCode.
Check rawDynamicTruthSigmaDomainProjectionFieldCode.
Check rawDirect_coqDynamicTruthSigmaSuccessorRowTemplate_identified.
Check rawDirect_coqDynamicTruthSigmaDomainProjection_identified.
Check rawDirect_coqDynamicTruthSigmaDomainProjectionField_identified.
Check rawCoqDynamicTruthSigmaSuccessorRowTemplateCode_eq_native.
Check rawCoqDynamicTruthSigmaDomainProjectionCode_eq_native.
Check rawCoqDynamicTruthSigmaDomainProjectionFieldCode_eq_native.

Check rawCoqDynamicTruthSigmaDomainProjectionFieldCertificate.
Check raw_codedPAProofOf_coqDynamicTruthSigmaDomainProjectionField.
Check
  raw_codedPAProofOf_dynamicTruthSigmaDomainProjectionField_identified.

Print Assumptions coqDynamicTruthSigmaDomainProjectionProof_derives.
Print Assumptions coqDynamicTruthSigmaDomainProjectionFieldProof_derives.
Print Assumptions
  rawDirect_coqDynamicTruthSigmaSuccessorRowTemplate_identified.
Print Assumptions
  rawCoqDynamicTruthSigmaDomainProjectionCode_eq_native.
Print Assumptions
  rawCoqDynamicTruthSigmaDomainProjectionFieldCode_eq_native.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthSigmaDomainProjectionField.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthSigmaDomainProjectionField_identified.
