From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendPermutedTemplateGlobalTraversalAssembly.

Import
  PABoundedRawCodedFourStateTableAppendPermutedTemplateGlobalTraversalAssembly.

Check coqFourStateTableAppendPermutedTemplateGlobalSource.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula_success.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalRows.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula_shape.
Check coqFourStateTableAppendOpenedPermutedSharedGlobalRows_eq.
Check
  raw_codedPAGrowingTemplateLocalProofAt_opened_template_global_rows_of_concrete_row_at_root_terms.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_template_global_of_append_rows.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_row.

Print Assumptions
  coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula_shape.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_template_global_of_append_rows.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_row.
