(** Kernel-facing audit for direct-shell guarded premise retention. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegration.

Module
  PABoundedRawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegrationAudit.

Import
  PABoundedRawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegration.

Check
  raw_codedPAGrowingTemplateLocalProofAt_of_shifted_assumption_under_fixed_prefix.
Check rawCoqRestrictedPADirectStrongStepDeepEndpointTail.
Check RawCoqRestrictedPADirectStrongStepGuardedPremiseRootsAt.
Check raw_coqRestrictedPADirectStrongStep_guardedPremiseRoots.
Check raw_coqTemplateShiftFive_after_renameEight.
Check raw_templateShiftRenamingMany_eq_add.
Check raw_templateShiftRenamingBy_after_shiftMany.
Check raw_templateFormulaRename_cutoff_after_shiftMany.
Check raw_templateContextShiftMany_map.
Check raw_templateContextRename_cutoff_after_shiftMany.
Check rawCoqRestrictedPADirectStrongStepGuardedOuterLiftRenaming.
Check raw_coqRestrictedPADirectStrongStepGuardedOuterLift_atomic_shape.
Check raw_coqRestrictedPADirectStrongStepGuardedOuterLift_boolean_atomic_shape.

(** The structural shift and membership theorem is closed.  The represented
    assumption compiler and its six-root direct specialization inherit only
    the project's established relational choice principles. *)
Print Assumptions raw_coqTemplateShiftFive_after_renameEight.
Print Assumptions raw_templateFormulaRename_cutoff_after_shiftMany.
Print Assumptions raw_templateContextRename_cutoff_after_shiftMany.
Print Assumptions raw_coqRestrictedPADirectStrongStepGuardedOuterLift_atomic_shape.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepGuardedOuterLift_boolean_atomic_shape.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_of_shifted_assumption_under_fixed_prefix.
Print Assumptions raw_coqRestrictedPADirectStrongStep_guardedPremiseRoots.

End
  PABoundedRawCodedDynamicTruthNativeDirectStrongStepGuardedPremiseIntegrationAudit.
