From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionFiveFieldChildOnlyRemainderIntegration.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionFiveFieldChildOnlyRemainderIntegration.

Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsAfterAndIntroductionFiveFieldChildOnlyRemainder.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionFiveFieldChildOnlyAtWitnesses.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionFiveFieldChildOnlyStandardTailCompiler.
Check
  raw_sevenFieldChildOnlyRemainder_of_quantifierUnaryChildren_and_fiveFieldRemainder.
Check
  raw_remainingAfterAndIntroductionSevenFieldChildOnlyStandardTailCompiler_of_fiveFieldRemainder.

Print Assumptions
  raw_sevenFieldChildOnlyRemainder_of_quantifierUnaryChildren_and_fiveFieldRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionSevenFieldChildOnlyStandardTailCompiler_of_fiveFieldRemainder.
