(** Kernel audit for the arbitrary-carrier strong-prefix induction shell. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixInductionShell.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixInductionShell.

Check coqRestrictedPADerivationSoundnessCarrierPredicateTemplate.
Check coqRestrictedPADerivationSoundnessCarrierStrongPrefixTemplate.
Check coqRestrictedPADerivationSoundnessCarrierStrongStepTemplate.
Check coqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerTemplate.

Check rawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixSuccessorCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixZeroCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixStepAllCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongStepCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixAllCode.
Check rawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerCode.

Check
  RawCoqRestrictedPADerivationSoundnessStrongPrefixClosureRemainder.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixClosureInductionData.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessStrongPrefixAll_of_cases.
Check
  RawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixCaseRootCompiler.
Check
  RawCoqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerRootCompiler.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversal_of_strongPrefix_cases_and_finalizer.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversal_of_strongPrefix_compilers.

Print Assumptions raw_coqCarrierStrongPrefix_templateFormula_shiftAt.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixClosureInductionData.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessStrongPrefixAll_of_cases.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversal_of_strongPrefix_cases_and_finalizer.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversal_of_strongPrefix_compilers.
