(** Assumption audit for synchronized strong-step endpoint evidence. *)

From BoundedPAConsistency Require Import
  RawCodedStrongStepProofEndpointEvidenceCompilation.

Import PABoundedRawCodedStrongStepProofEndpointEvidenceCompilation.

Check coqStrongStepEndpointEvidence_rule_premises_agree.
Check coqRestrictedPADerivationSoundnessRestrictedProofTemplate_view.
Check coqStrongStepSigmaDomainTemplate_open.
Check coqStrongStepPiDomainTemplate_open.
Check raw_strongStepEndpointAtomicAdequacyConclusion_code.
Check raw_strongStepEndpointQuantifierBoundedConclusion_code.
Check raw_codedPALocalProof_twoPremiseLaw_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProof_strongStepProofEndpointQuantifierBounded_of_roots_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProof_strongStepProofEndpointAtomicAdequacy_of_roots_on_witnessed_tail_under_prefix.
Check raw_codedPALocalProof_strongStepEndpointEvidence_of_roots.
Check
  raw_codedPALocalProof_strongStepEndpointEvidence_of_roots_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProof_strongStepEndpointEvidence_of_restricted_and_rule_roots.
Check
  raw_codedPALocalProof_strongStepEndpointEvidence_of_restricted_and_rule_roots_on_witnessed_tail_under_prefix.

Print Assumptions coqStrongStepEndpointEvidence_rule_premises_agree.
Print Assumptions
  coqRestrictedPADerivationSoundnessRestrictedProofTemplate_view.
Print Assumptions coqStrongStepSigmaDomainTemplate_open.
Print Assumptions coqStrongStepPiDomainTemplate_open.
Print Assumptions raw_strongStepEndpointAtomicAdequacyConclusion_code.
Print Assumptions raw_strongStepEndpointQuantifierBoundedConclusion_code.
Print Assumptions
  raw_codedPALocalProof_twoPremiseLaw_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProof_strongStepProofEndpointQuantifierBounded_of_roots_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProof_strongStepProofEndpointAtomicAdequacy_of_roots_on_witnessed_tail_under_prefix.
Print Assumptions raw_codedPALocalProof_strongStepEndpointEvidence_of_roots.
Print Assumptions
  raw_codedPALocalProof_strongStepEndpointEvidence_of_roots_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProof_strongStepEndpointEvidence_of_restricted_and_rule_roots.
Print Assumptions
  raw_codedPALocalProof_strongStepEndpointEvidence_of_restricted_and_rule_roots_on_witnessed_tail_under_prefix.
