(**
  Kernel-facing audit for native substitution proof compilation.

  The interface checks distinguish the concrete propositional/universal
  shell from the four same-context implication roots still supplied by the
  carrier-indexed structural compiler.
*)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeSubstitutionProofCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeSubstitutionProofCompilation.

Check rawDynamicTruthNativeSubstitutionAntecedentCode.
Check rawDynamicTruthNativeSubstitutionTransportCode.
Check rawDynamicTruthNativeSubstitutionBodyCode.
Check rawDynamicTruthNativeSubstitutionRepeatedAllCode.
Check rawDynamicTruthNativeSubstitutionFieldCode_as_all7_body.
Check rawDynamicTruthNativeSubstitutionCommonContext.

Check RawDynamicTruthNativeSubstitutionSigmaLocalRootsAt.
Check RawDynamicTruthNativeSubstitutionPiLocalRootsAt.
Check RawDynamicTruthNativeSubstitutionBodyLocalRootAt.
Check rawDynamicTruthNativeSubstitutionIffRoot.
Check rawDynamicTruthNativeSubstitutionTransportRoot.
Check rawDynamicTruthNativeSubstitutionBodyRoot.
Check raw_dynamicTruthNativeSubstitutionBodyLocalRootAt_of_polarity_roots.

Check rawDynamicTruthNativeSubstitutionCloseRoot.
Check raw_codedPALocalProofOf_dynamicTruthNativeSubstitutionClose.
Check rawDynamicTruthNativeSubstitutionProofCertificate.
Check raw_dynamicTruthNativeSubstitution_empty_witness_context.
Check raw_codedPAProofOf_dynamicTruthNativeSubstitutionField_of_body_root.
Check
  raw_codedPAProofOf_dynamicTruthNativeSubstitutionField_of_polarity_roots.

Check RawDynamicTruthNativeSubstitutionProofTraceAt.
Check RawDynamicTruthNativeSubstitutionLocalRootCompiler.
Check raw_dynamicTruthNativeSubstitutionProofTraceAt_of_transform.
Check raw_dynamicTruthNativeSubstitutionProofCompiler_of_local_roots.
Check
  dynamicTruthNativeSubstitutionPositiveGraph_raw_proof_total_of_local_roots.

Print Assumptions
  raw_dynamicTruthNativeSubstitutionBodyLocalRootAt_of_polarity_roots.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeSubstitutionClose.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeSubstitutionField_of_body_root.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeSubstitutionField_of_polarity_roots.
Print Assumptions
  raw_dynamicTruthNativeSubstitutionProofTraceAt_of_transform.
Print Assumptions
  raw_dynamicTruthNativeSubstitutionProofCompiler_of_local_roots.
Print Assumptions
  dynamicTruthNativeSubstitutionPositiveGraph_raw_proof_total_of_local_roots.
