(** Assumptions audit for predecessor-free guarded collision assembly. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalGuardedReducedStagedCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeLocalGuardedReducedStagedCompilation.

Check DynamicTruthImpDiagonalCell.
Check RawDynamicTruthLocalCollisionPairFamilyWithoutImpAt.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_witnessed_inclusion.
Check raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_of_family.
Check raw_dynamicTruthLocalCollisionPairFamily_of_without_imp_and_pairs.
Check raw_dynamicTruthLocalCollisionPairFamily_of_without_imp_and_guarded.
Check raw_dynamicTruthNativeLocal_guarded_cell_roots_of_42_helpers.
Check raw_dynamicTruthNativeLocalFieldRootOn_of_base_pair_family.
Check RawDynamicTruthNativeLocalGuardedReducedStagedRootsAt.
Check
  raw_dynamicTruthNativeLocalFieldRootOn_of_guarded_reduced_staged_roots_and_42_helpers.

Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_witnessed_inclusion.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_of_family.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamily_of_without_imp_and_pairs.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamily_of_without_imp_and_guarded.
Print Assumptions
  raw_dynamicTruthNativeLocal_guarded_cell_roots_of_42_helpers.
Print Assumptions raw_dynamicTruthNativeLocalFieldRootOn_of_base_pair_family.
Print Assumptions
  raw_dynamicTruthNativeLocalFieldRootOn_of_guarded_reduced_staged_roots_and_42_helpers.
