(** Kernel audit for direct growing strong-prefix case/finalizer integration. *)
From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixGrowingIntegrationDirect.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixGrowingIntegrationDirect.

Check
  RawCoqRestrictedPADerivationSoundnessCarrierGrowingFinalizationPackageOfDirect.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixAllDirect_selfShift.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixAllDirect_cons_binderReady.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierGrowingFinalizationPackageDirect_of_growing_case_package.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_growing_case_and_finalizer.

Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixAllDirect_selfShift.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierGrowingFinalizationPackageDirect_of_growing_case_package.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_growing_case_and_finalizer.
