(** Audit surface for the refined direct-consistency integration. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeFinalRefinedDirectConsistencyIntegration.

Import
  PABoundedRawCodedDynamicTruthNativeFinalRefinedDirectConsistencyIntegration.

Check
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessDirectCompiler_of_refined_resources.
Check
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessDirectBridge_of_witnessed_rule_cases_and_refined_resources.
Check
  raw_dynamicTruthNativeFinalGrowingStagedNextFinalProof_of_witnessed_rule_cases_and_refined_resources.

Print Assumptions
  raw_dynamicTruthNativeFinalConsistencyFromUniversalSoundnessDirectCompiler_of_refined_resources.
Print Assumptions
  raw_dynamicTruthNativeFinalGrowingUniversalSoundnessDirectBridge_of_witnessed_rule_cases_and_refined_resources.
Print Assumptions
  raw_dynamicTruthNativeFinalGrowingStagedNextFinalProof_of_witnessed_rule_cases_and_refined_resources.
