(** Audit surface for opened Or-I-left proof-code integration. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftOpenedCoverageCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftOpenedCoverageCompilation.

Check raw_codedPALocalProof_openedCoverageLaw_on_witnessed_base.
Check raw_openedCoverageCompilerLawRoot_on_selected_witnessed_tail.
Check
  raw_orIntroductionLeft_recursiveChildLawRoot_on_selected_witnessed_tail.
Check coqRestrictedPADirectOrIntroductionLeftReadyContext_app_witnesses.
Check raw_standardPAAxiomWitnessPrefixContextCode_realizable.
Check
  raw_standardPAAxiomWitnessPrefixContextCode_samePrefix_included.
Check raw_directEmbeddedPAAxiomWitnessContext.
Check raw_directEmbeddedPAAxiomWitnessContext_suffix_included.
Check raw_orIntroductionLeft_recursiveChildLawRoot_append_witnessed_tail.

Print Assumptions
  raw_codedPALocalProof_openedCoverageLaw_on_witnessed_base.
Print Assumptions
  raw_openedCoverageCompilerLawRoot_on_selected_witnessed_tail.
Print Assumptions
  raw_orIntroductionLeft_recursiveChildLawRoot_on_selected_witnessed_tail.
Print Assumptions
  coqRestrictedPADirectOrIntroductionLeftReadyContext_app_witnesses.
Print Assumptions
  raw_directEmbeddedPAAxiomWitnessContext_suffix_included.
Print Assumptions
  raw_orIntroductionLeft_recursiveChildLawRoot_append_witnessed_tail.
