(** Assumption audit for the individual Sigma/Pi formula-code graphs. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPolarityFormulaCodeGraphs.

Import PABoundedRawCodedDynamicTruthPolarityFormulaCodeGraphs.

Check dynamicTruthSigmaFormulaCodeProjectionRenaming.
Check raw_sat_dynamicTruthSigmaFormulaCodeProjectionRenamed_iff.
Check dynamicTruthSigmaFormulaCodeGraph.
Check RawDynamicTruthSigmaFormulaCodeAt.
Check raw_sat_dynamicTruthSigmaFormulaCodeGraph_iff.
Check dynamicTruthPiFormulaCodeGraph.
Check RawDynamicTruthPiFormulaCodeAt.
Check raw_sat_dynamicTruthPiFormulaCodeGraph_iff.
Check raw_dynamicTruthSigmaFormulaCodeAt_zero_iff.
Check raw_dynamicTruthPiFormulaCodeAt_zero_iff.
Check raw_dynamicTruthSigmaFormulaCodeAt_succ_iff.
Check raw_dynamicTruthPiFormulaCodeAt_succ_iff.
Check raw_sat_dynamicTruthSigmaFormulaCodeGraph_zero_iff.
Check raw_sat_dynamicTruthPiFormulaCodeGraph_zero_iff.
Check dynamicTruthSigmaFormulaCodeGraph_adequate_total.
Check dynamicTruthPiFormulaCodeGraph_adequate_total.
Check dynamicTruthSigmaFormulaCodeGraph_raw_adequate_total.
Check dynamicTruthPiFormulaCodeGraph_raw_adequate_total.

Print Assumptions raw_sat_dynamicTruthSigmaFormulaCodeProjectionRenamed_iff.
Print Assumptions raw_sat_dynamicTruthSigmaFormulaCodeGraph_iff.
Print Assumptions raw_sat_dynamicTruthPiFormulaCodeGraph_iff.
Print Assumptions raw_dynamicTruthSigmaFormulaCodeAt_zero_iff.
Print Assumptions raw_dynamicTruthPiFormulaCodeAt_zero_iff.
Print Assumptions raw_dynamicTruthSigmaFormulaCodeAt_succ_iff.
Print Assumptions raw_dynamicTruthPiFormulaCodeAt_succ_iff.
Print Assumptions dynamicTruthSigmaFormulaCodeGraph_adequate_total.
Print Assumptions dynamicTruthPiFormulaCodeGraph_adequate_total.
Print Assumptions dynamicTruthSigmaFormulaCodeGraph_raw_adequate_total.
Print Assumptions dynamicTruthPiFormulaCodeGraph_raw_adequate_total.
