(** Assumption audit for represented restricted-proof endpoint boundedness. *)

From BoundedPAConsistency Require Import
  RawCodedProofEndpointQuantifierBoundedProofCompilation.

Import PABoundedRawCodedProofEndpointQuantifierBoundedProofCompilation.

Check coqProofEndpointQuantifierBoundedLawTemplate.
Check coqProofEndpointQuantifierBoundedLawTemplate_imp2_shape.
Check raw_coqProofEndpointQuantifierBoundedLawTemplate_valid.
Check coqProofEndpointQuantifierBoundedSourceFormula.
Check coqProofEndpointQuantifierBoundedSource_open.
Check raw_coqProofEndpointQuantifierBoundedSourceFormula_valid.
Check PA_proves_coqProofEndpointQuantifierBoundedSourceFormula.
Check rawDirect_proofEndpointQuantifierBoundedSource_substitution.
Check raw_codedPALocalProof_proofEndpointQuantifierBoundedLaw_on_witnessed_base.
Check
  raw_codedPALocalProof_proofEndpointQuantifierBounded_of_roots_on_witnessed_extension.
Check coqStrongStepProofEndpointQuantifierBoundedLawTemplate.
Check coqStrongStepProofEndpointQuantifierBoundedLawTemplate_imp2_shape.
Check coqStrongStepProofEndpointQuantifierBoundedRestrictedPremise_view.
Check coqStrongStepProofEndpointQuantifierBoundedEndpointPremise_view.
Check coqStrongStepProofEndpointQuantifierBoundedConclusion_view.
Check raw_proofRuleValid_endpoint.
Check raw_coqStrongStepProofEndpointQuantifierBoundedLawTemplate_valid.
Check coqStrongStepProofEndpointQuantifierBoundedSourceFormula.
Check coqStrongStepProofEndpointQuantifierBoundedSource_open.
Check raw_coqStrongStepProofEndpointQuantifierBoundedSourceFormula_valid.
Check PA_proves_coqStrongStepProofEndpointQuantifierBoundedSourceFormula.

Print Assumptions raw_coqProofEndpointQuantifierBoundedLawTemplate_valid.
Print Assumptions PA_proves_coqProofEndpointQuantifierBoundedSourceFormula.
Print Assumptions rawDirect_proofEndpointQuantifierBoundedSource_substitution.
Print Assumptions
  raw_codedPALocalProof_proofEndpointQuantifierBoundedLaw_on_witnessed_base.
Print Assumptions
  raw_codedPALocalProof_proofEndpointQuantifierBounded_of_roots_on_witnessed_extension.
Print Assumptions
  raw_proofRuleValid_endpoint.
Print Assumptions
  raw_coqStrongStepProofEndpointQuantifierBoundedLawTemplate_valid.
Print Assumptions
  PA_proves_coqStrongStepProofEndpointQuantifierBoundedSourceFormula.
