From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyRemainderCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyRemainderCompilation.

Check RawCoqRestrictedPADirectThreeFieldEqualityEliminationChildrenAtWitnesses.
Check
  RawCoqRestrictedPADirectThreeFieldEqualityEliminationChildrenStandardTailCompiler.
Check
  raw_threeFieldChildOnlyRemainder_of_orElimination_existentialElimination_equalityChildren.
Check
  raw_threeFieldChildOnlyRemainderAtWitnesses_of_orElimination_existentialElimination_equalityChildren.
Check
  raw_remainingAfterAndIntroductionThreeFieldChildOnlyStandardTailCompiler_of_orElimination_existentialElimination_equalityChildren.
Check
  raw_remainingAfterAndIntroductionThreeFieldChildOnlyStandardTailCompiler_of_aligned_orElimination_existentialElimination_rows_and_equalityChildren.
