(** Assumption audit for the canonical-application direct-evidence bridge. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroCanonicalApplicationDirectEvidence.

Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalApplicationDirectEvidence.

Check RawDynamicTruthZeroCanonicalApplicationRootsAt.
Check
  raw_dynamicTruthZeroCanonicalApplicationRootsAt_of_growing_global_roots.
Check raw_dynamicTruthZeroDirectEvidenceRoots_of_canonicalApplicationRoots.
Check raw_dynamicTruthZeroCanonicalApplicationRoots_of_directEvidenceRoots.
Check
  raw_dynamicTruthZeroDirectEvidenceRoots_of_canonicalApplicationRoots_bottom.
Check
  raw_dynamicTruthZeroCanonicalApplicationRoots_of_directEvidenceRoots_bottom.

Print Assumptions RawDynamicTruthZeroCanonicalApplicationRootsAt.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationRootsAt_of_growing_global_roots.
Print Assumptions
  raw_dynamicTruthZeroDirectEvidenceRoots_of_canonicalApplicationRoots.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationRoots_of_directEvidenceRoots.
Print Assumptions
  raw_dynamicTruthZeroDirectEvidenceRoots_of_canonicalApplicationRoots_bottom.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationRoots_of_directEvidenceRoots_bottom.
