From BoundedPAConsistency Require Import
  RawCodedStandardClosedFormulaCodeGraph.

Import PABoundedRawCodedStandardClosedFormulaCodeGraph.

Check standardClosedFormulaCodeGraph.
Check RawStandardClosedFormulaCodeAt.
Check standardClosedFormulaCodeGraph_numeral_representation.
Check standardClosedFormulaCodeGraph_representation.
Check standardClosedFormulaCodeGraph_raw_total.
Check standardClosedFormulaCodeGraph_dynamic_base_total.
Check standardClosedFormulaCodeGraph_zero_iff.
Check standardClosedFormulaCodeGraph_zero.
Check raw_standardClosedFormulaCodeGraph_proof_of_BProv.

Print Assumptions standardClosedFormulaCodeGraph_numeral_representation.
Print Assumptions standardClosedFormulaCodeGraph_representation.
Print Assumptions standardClosedFormulaCodeGraph_raw_total.
Print Assumptions standardClosedFormulaCodeGraph_dynamic_base_total.
Print Assumptions standardClosedFormulaCodeGraph_zero_iff.
Print Assumptions standardClosedFormulaCodeGraph_zero.
Print Assumptions raw_standardClosedFormulaCodeGraph_proof_of_BProv.
