(** Kernel-facing audit for reusable adjoined-context proof transport. *)

From BoundedPAConsistency Require Import
  RawCodedPALocalProofAdjoinedContextTransport.

Import PABoundedRawCodedPALocalProofAdjoinedContextTransport.

Check raw_contextListIncluded_same_induction_extension.
Check raw_codedPALocalProof_same_induction_extension_weakening.
Check raw_contextBinderReady_prepend_target_of_formulaShift.
Check raw_codedPALocalProof_prepend_context_of_formulaShift.
Check raw_codedPALocalProof_prepend_closed_context.
Check raw_codedPALocalProof_same_prepend_weakening_between_witnessed_tails.
Check
  raw_codedPALocalProof_same_induction_extension_then_prepend_closed_context.

Print Assumptions raw_contextListIncluded_same_induction_extension.
Print Assumptions raw_codedPALocalProof_same_induction_extension_weakening.
Print Assumptions raw_contextBinderReady_prepend_target_of_formulaShift.
Print Assumptions raw_codedPALocalProof_prepend_context_of_formulaShift.
Print Assumptions raw_codedPALocalProof_prepend_closed_context.
Print Assumptions
  raw_codedPALocalProof_same_prepend_weakening_between_witnessed_tails.
Print Assumptions
  raw_codedPALocalProof_same_induction_extension_then_prepend_closed_context.
