(** Assumption audit for guarded rank-zero predecessor compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroGuardedPredecessorCompilation.

Module
  PABoundedRawCodedDynamicTruthNativeZeroGuardedPredecessorCompilationAudit.

Import
  PABoundedRawCodedDynamicTruthNativeZeroGuardedPredecessorCompilation.

Check coqDynamicTruthImpGuardedParentAtomicTemplate_eq_endpoint_shift5.
Check coqDynamicTruthImpGuardedParentDomainTemplate_view.
Check
  coqStrongStepProofEndpointQuantifierBoundedConclusion_shift5_view.
Check raw_coqDynamicTruthImpGuardedParentDomain_eq_endpoint_shift5.
Check RawDynamicTruthImpGuardedBranchRootsAt.
Check
  raw_dynamicTruthImpGuardedPredecessorRoot_on_witnessed_extension_of_branch_roots.
Check raw_dynamicTruthImpGuardedBranchSource_of_zero_normalized.
Check
  raw_dynamicTruthImpGuardedBranchSource_exists_of_zero_normalized.
Check
  RawDynamicTruthNativeLocalZeroGrowingGuardedBranchRootsCompilerOnNormalizedResources.
Check
  RawDynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnNormalizedResources.
Check
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnNormalizedResources_of_branch_roots.

Print Assumptions
  raw_coqDynamicTruthImpGuardedParentDomain_eq_endpoint_shift5.
Print Assumptions
  raw_dynamicTruthImpGuardedPredecessorRoot_on_witnessed_extension_of_branch_roots.
Print Assumptions raw_dynamicTruthImpGuardedBranchSource_of_zero_normalized.
Print Assumptions
  raw_dynamicTruthImpGuardedBranchSource_exists_of_zero_normalized.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingGuardedPredecessorRootCompilerOnNormalizedResources_of_branch_roots.

End
  PABoundedRawCodedDynamicTruthNativeZeroGuardedPredecessorCompilationAudit.
