(** Audit the translation-free six-coordinate call-site boundary. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2Boundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2Boundary.

Check
  RawDynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2KernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2KernelCompilers_of_reduced_local_boundary.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_all_currentPackages_canonical_v2_kernel_compilers.
Check
  RawDynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2KernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2KernelCompilersInAllModels_of_reduced_local_boundary.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_all_currentPackages_canonical_v2_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_all_currentPackages_canonical_v2_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2KernelCompilers_of_reduced_local_boundary.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_all_currentPackages_canonical_v2_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedAllCurrentPackagesCanonicalV2KernelCompilersInAllModels_of_reduced_local_boundary.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_all_currentPackages_canonical_v2_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_all_currentPackages_canonical_v2_kernel_compilers.
