(** Kernel-facing audit for native successor-row append normalization. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSuccessorRowsAppendNormalization.

Import PABoundedRawCodedDynamicTruthSuccessorRowsAppendNormalization.

Check coqDynamicTruthSharedSigmaSuccessorRowTemplate.
Check coqDynamicTruthSharedPiSuccessorRowTemplate.
Check coqDynamicTruthSharedSigmaSuccessorRowTemplate_scoped_13.
Check coqDynamicTruthSharedPiSuccessorRowTemplate_scoped_13.
Check coqDynamicTruthSharedSigmaSuccessorRowTemplate_append_fields_inert.
Check coqDynamicTruthSharedPiSuccessorRowTemplate_append_fields_inert.
Check coqDynamicTruthSharedSuccessorRows_append_production.

Print Assumptions coqDynamicTruthSharedSigmaSuccessorRowTemplate_scoped_13.
Print Assumptions coqDynamicTruthSharedPiSuccessorRowTemplate_scoped_13.
Print Assumptions
  coqDynamicTruthSharedSigmaSuccessorRowTemplate_append_fields_inert.
Print Assumptions
  coqDynamicTruthSharedPiSuccessorRowTemplate_append_fields_inert.
Print Assumptions coqDynamicTruthSharedSuccessorRows_append_production.
