(** Assumption audit for canonical append-source identification. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification.

Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalAppendSourceIdentification.

Check dynamicTruthZeroCanonicalSigmaRowFormula.
Check dynamicTruthZeroCanonicalPiRowFormula.
Check coqFourStateTableAppendZeroCanonicalFixedProduction_native.
Check rawTemplateFormula_zeroCanonicalFixedProduction_native.
Check coqFourStateTableAppendPermutedTemplateGlobalSource_zero_sigma.
Check coqFourStateTableAppendPermutedTemplateGlobalSource_zero_pi.
Check rawTemplateFormula_zeroCanonicalPermutedGlobalSource_sigma.
Check rawTemplateFormula_zeroCanonicalPermutedGlobalSource_pi.
Check
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_pair.
Check RawDynamicTruthZeroCanonicalPermutedAppendInputsAt.
Check RawDynamicTruthZeroCanonicalPermutedAppendInputsUnderPrefixAt.
Check coqFourStateTableAppendOpenedPermutedZeroCanonicalRows_eq.
Check coqFourStateTableAppendZeroCanonicalRowProduction_eq.
Check
  RawDynamicTruthZeroCanonicalPermutedAppendRowImplicationInputsUnderPrefixAt.
Check
  RawDynamicTruthZeroCanonicalPermutedAppendLiteralRowImplicationInputsUnderPrefixAt.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRowImplicationInputsUnderPrefixAt_of_literal.
Check
  RawDynamicTruthZeroCanonicalPermutedAppendRowKernelInputsUnderPrefixAt.
Check coqDynamicTruthZeroCanonicalVacuousOldLookupTemplate.
Check coqDynamicTruthZeroCanonicalVacuousInheritedRowBodyTemplate.
Check coqDynamicTruthZeroCanonicalVacuousInheritedBoundRowBodyTemplate.
Check coqDynamicTruthZeroCanonicalVacuousInheritedTraversalTemplate.
Check
  coqDynamicTruthZeroCanonicalVacuousInheritedTraversalTemplate_open.
Check coqNoLtZeroAntecedentTemplate_append_below_zero.
Check
  RawDynamicTruthZeroCanonicalPermutedAppendInheritedRowResourcesUnderPrefixAt.
Check
  RawDynamicTruthZeroCanonicalGrowingFixedProductionCompilerUnderPrefixAt.
Check
  RawDynamicTruthZeroCanonicalGrowingFixedProductionOrRefutationCompilerUnderPrefixAt.
Check
  raw_dynamicTruthZeroCanonicalGrowingFixedProductionCompilerUnderPrefixAt_of_production_or_refutation.
Check
  RawDynamicTruthZeroCanonicalIndependentGrowingFixedProductionOrRefutationCompilersUnderPrefix.
Check
  RawDynamicTruthZeroCanonicalIndependentGrowingFixedProductionCompilersUnderPrefix.
Check
  raw_dynamicTruthZeroCanonicalIndependentGrowingFixedProductionCompilersUnderPrefix_of_production_or_refutation.
Check
  RawDynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadUnderPrefixAt.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayload_on_standardWitnessTail_of_inherited_and_growing_fixed_production.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRoot_on_standardWitnessTail.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadUnderPrefixAt_standardWitnessTail_surround.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelInputsUnderPrefixAt_of_payload.
Check
  raw_dynamicTruthZeroCanonicalSigmaPermutedAppendRowKernelInputsUnderPrefixAt_of_payload.
Check
  raw_dynamicTruthZeroCanonicalPiPermutedAppendRowKernelInputsUnderPrefixAt_of_payload.
Check
  RawDynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadPairUnderPrefix.
Check
  RawDynamicTruthZeroCanonicalIndependentPermutedAppendRowKernelPayloadsUnderPrefix.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadPairUnderPrefix_of_independent_witnesses.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadPairUnderPrefix_of_independent_payloads.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendRowImplicationInputsUnderPrefixAt_of_kernel.
Check
  raw_dynamicTruthZeroCanonicalPermutedAppendInputsUnderPrefixAt_of_row_implication_inputs.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_kernel_payload_under_prefix.
Check
  raw_dynamicTruthZeroCanonicalSigmaApplication_of_permuted_append_kernel_payload_under_prefix.
Check
  raw_dynamicTruthZeroCanonicalPiApplication_of_permuted_append_kernel_payload_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofPairAt_dynamic_truth_zero_canonical_permuted_globals_of_inputs_under_prefix.
Check
  raw_dynamicTruthZeroCanonicalApplicationPair_of_permuted_append_inputs_under_prefix.
Check
  raw_dynamicTruthZeroCanonicalStateApplicationPair_of_permuted_append_inputs.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs.
Check
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_zero_canonical_permuted_globals_of_inputs.
Check
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_inputs.

Print Assumptions
  coqFourStateTableAppendPermutedTemplateGlobalSource_zero_sigma.
Print Assumptions
  coqFourStateTableAppendPermutedTemplateGlobalSource_zero_pi.
Print Assumptions rawTemplateFormula_zeroCanonicalPermutedGlobalSource_sigma.
Print Assumptions rawTemplateFormula_zeroCanonicalPermutedGlobalSource_pi.
Print Assumptions
  coqFourStateTableAppendZeroCanonicalFixedProduction_native.
Print Assumptions
  rawTemplateFormula_zeroCanonicalFixedProduction_native.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_pair.
Print Assumptions RawDynamicTruthZeroCanonicalPermutedAppendInputsAt.
Print Assumptions RawDynamicTruthZeroCanonicalPermutedAppendInputsUnderPrefixAt.
Print Assumptions coqFourStateTableAppendOpenedPermutedZeroCanonicalRows_eq.
Print Assumptions coqFourStateTableAppendZeroCanonicalRowProduction_eq.
Print Assumptions
  RawDynamicTruthZeroCanonicalPermutedAppendRowImplicationInputsUnderPrefixAt.
Print Assumptions
  RawDynamicTruthZeroCanonicalPermutedAppendLiteralRowImplicationInputsUnderPrefixAt.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRowImplicationInputsUnderPrefixAt_of_literal.
Print Assumptions
  RawDynamicTruthZeroCanonicalPermutedAppendRowKernelInputsUnderPrefixAt.
Print Assumptions
  coqDynamicTruthZeroCanonicalVacuousInheritedTraversalTemplate_open.
Print Assumptions coqNoLtZeroAntecedentTemplate_append_below_zero.
Print Assumptions
  RawDynamicTruthZeroCanonicalPermutedAppendInheritedRowResourcesUnderPrefixAt.
Print Assumptions
  RawDynamicTruthZeroCanonicalGrowingFixedProductionCompilerUnderPrefixAt.
Print Assumptions
  RawDynamicTruthZeroCanonicalGrowingFixedProductionOrRefutationCompilerUnderPrefixAt.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGrowingFixedProductionCompilerUnderPrefixAt_of_production_or_refutation.
Print Assumptions
  RawDynamicTruthZeroCanonicalIndependentGrowingFixedProductionOrRefutationCompilersUnderPrefix.
Print Assumptions
  RawDynamicTruthZeroCanonicalIndependentGrowingFixedProductionCompilersUnderPrefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalIndependentGrowingFixedProductionCompilersUnderPrefix_of_production_or_refutation.
Print Assumptions
  RawDynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadUnderPrefixAt.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayload_on_standardWitnessTail_of_inherited_and_growing_fixed_production.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRoot_on_standardWitnessTail.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadUnderPrefixAt_standardWitnessTail_surround.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelInputsUnderPrefixAt_of_payload.
Print Assumptions
  raw_dynamicTruthZeroCanonicalSigmaPermutedAppendRowKernelInputsUnderPrefixAt_of_payload.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPiPermutedAppendRowKernelInputsUnderPrefixAt_of_payload.
Print Assumptions
  RawDynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadPairUnderPrefix.
Print Assumptions
  RawDynamicTruthZeroCanonicalIndependentPermutedAppendRowKernelPayloadsUnderPrefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadPairUnderPrefix_of_independent_witnesses.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRowKernelPayloadPairUnderPrefix_of_independent_payloads.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendRowImplicationInputsUnderPrefixAt_of_kernel.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPermutedAppendInputsUnderPrefixAt_of_row_implication_inputs.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_kernel_payload_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalSigmaApplication_of_permuted_append_kernel_payload_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalPiApplication_of_permuted_append_kernel_payload_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofPairAt_dynamic_truth_zero_canonical_permuted_globals_of_inputs_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationPair_of_permuted_append_inputs_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalStateApplicationPair_of_permuted_append_inputs.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_zero_canonical_permuted_global_of_inputs.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_zero_canonical_permuted_globals_of_inputs.
Print Assumptions
  raw_dynamicTruthZeroCanonicalGlobalApplicationRoots_of_permuted_append_inputs.
