(** Kernel audit for the full Sigma-row domain-projection transform. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaDomainProjectionTransformGraph.

Module
  PABoundedRawCodedDynamicTruthSigmaDomainProjectionTransformGraphAudit.

Import
  PABoundedRawCodedDynamicTruthSigmaDomainProjectionTransformGraph.

Check dynamicTruthSigmaDomainProjectionFormulaAllCodeTerm.
Check dynamicTruthSigmaDomainProjectionRepeatedAllCodeTerm.
Check dynamicTruthSigmaDomainProjectionCodeTerm.
Check dynamicTruthSigmaDomainProjectionFieldCodeTerm.
Check raw_eval_dynamicTruthSigmaDomainProjectionCodeTerm.
Check raw_eval_dynamicTruthSigmaDomainProjectionFieldCodeTerm.
Check raw_sat_dynamicTruthSigmaDomainProjectionFieldCodeTermAt_iff.

Check dynamicTruthSigmaDomainProjectionFieldTransformGraph.
Check RawDynamicTruthSigmaDomainProjectionFieldTransformAt.
Check raw_sat_dynamicTruthSigmaDomainProjectionFieldTransformGraph_iff.
Check RawDynamicTruthSigmaDomainProjectionFieldTransformTotal.
Check dynamicTruthSigmaDomainProjectionFieldTransformGraph_raw_total.

Check RawDynamicTruthSigmaDomainProjectionDirectCompilerTotal.
Check
  dynamicTruthSigmaDomainProjectionFieldTransformGraph_raw_proof_total.

Check dynamicTruthSigmaDomainProjectionPositiveFieldGraph.
Check RawDynamicTruthSigmaDomainProjectionPositiveFieldAt.
Check raw_sat_dynamicTruthSigmaDomainProjectionPositiveFieldGraph_iff.
Check RawDynamicTruthSigmaDomainProjectionPositiveFieldTotal.
Check
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total.
Check RawDynamicTruthSigmaDomainProjectionOrbitDirectCompilerTotal.
Check
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_adequate_proof_total.
Check
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total_of_orbit_direct_compiler.
Check
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total_of_orbit_interchange.

Print Assumptions
  raw_sat_dynamicTruthSigmaDomainProjectionFieldCodeTermAt_iff.
Print Assumptions
  raw_sat_dynamicTruthSigmaDomainProjectionFieldTransformGraph_iff.
Print Assumptions
  dynamicTruthSigmaDomainProjectionFieldTransformGraph_raw_total.
Print Assumptions
  dynamicTruthSigmaDomainProjectionFieldTransformGraph_raw_proof_total.
Print Assumptions
  raw_sat_dynamicTruthSigmaDomainProjectionPositiveFieldGraph_iff.
Print Assumptions
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total.
Print Assumptions
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_adequate_proof_total.
Print Assumptions
  dynamicTruthSigmaDomainProjectionPositiveFieldGraph_raw_proof_total_of_orbit_interchange.

End
  PABoundedRawCodedDynamicTruthSigmaDomainProjectionTransformGraphAudit.
