(** Kernel-facing audit for native formula-shift proof compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeShiftProofCompilation.

Import PABoundedRawCodedDynamicTruthNativeShiftProofCompilation.

Check rawDynamicTruthNativeShiftAntecedentCode.
Check rawDynamicTruthNativeShiftBodyCode.
Check rawDynamicTruthNativeShiftFieldCode_as_all8.
Check rawDynamicTruthNativeShiftCommonContext.
Check RawDynamicTruthNativeShiftSigmaLocalRootsAt.
Check RawDynamicTruthNativeShiftPiLocalRootsAt.
Check RawDynamicTruthNativeShiftBodyLocalRootAt.
Check raw_dynamicTruthNativeShiftBodyLocalRootAt_of_same_context_roots.
Check rawDynamicTruthNativeShiftCloseNCode.
Check rawDynamicTruthNativeShiftCloseNRoot.
Check rawDynamicTruthNativeShiftCloseNCode_eight.
Check raw_dynamicTruthNativeShiftCloseNRoot_ruleCoverage.
Check raw_dynamicTruthNativeShiftCloseNRoot_endpoint.
Check rawDynamicTruthNativeShiftProofCertificate.
Check raw_dynamicTruthNativeShift_empty_witness_context.
Check raw_codedPAProofOf_dynamicTruthNativeShiftField_of_body_root.
Check
  raw_codedPAProofOf_dynamicTruthNativeShiftField_of_same_context_roots.
Check RawDynamicTruthNativeShiftProofTraceAt.
Check RawDynamicTruthNativeShiftLocalRootCompiler.
Check raw_dynamicTruthNativeShiftProofTraceAt_of_transform.
Check raw_dynamicTruthNativeShiftProofCompiler_of_local_roots.
Check dynamicTruthNativeShiftPositiveGraph_raw_proof_total_of_local_roots.

Print Assumptions
  raw_dynamicTruthNativeShiftBodyLocalRootAt_of_same_context_roots.
Print Assumptions raw_dynamicTruthNativeShiftCloseNRoot_ruleCoverage.
Print Assumptions raw_dynamicTruthNativeShiftCloseNRoot_endpoint.
Print Assumptions raw_codedPAProofOf_dynamicTruthNativeShiftField_of_body_root.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeShiftField_of_same_context_roots.
Print Assumptions raw_dynamicTruthNativeShiftProofTraceAt_of_transform.
Print Assumptions raw_dynamicTruthNativeShiftProofCompiler_of_local_roots.
Print Assumptions
  dynamicTruthNativeShiftPositiveGraph_raw_proof_total_of_local_roots.
