(** Audit surface for the aligned existential-introduction and
    equality-elimination K-only truth compilers. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectExistentialIntroductionEqualityEliminationAlignedTruthProduction.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialIntroductionEqualityEliminationAlignedTruthProductionAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialIntroductionEqualityEliminationAlignedTruthProduction.

Check coqRestrictedPADirectExistentialIntroductionReadyContext_app_witnesses.
Check coqRestrictedPADirectEqualityEliminationReadyContext_app_witnesses.
Check raw_existentialIntroduction_mode_zero_parent_source_aligned.
Check raw_equalityElimination_mode_zero_parent_source_aligned.

Check RawCoqRestrictedPADirectExistentialIntroductionDynamicTruthLawRoot.
Check RawCoqRestrictedPADirectEqualityEliminationDynamicTruthLawRoot.
Check
  RawCoqRestrictedPADirectExistentialIntroductionResultTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectExistentialIntroductionDynamicTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectEqualityEliminationResultTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectEqualityEliminationDynamicTruthStandardTailCompiler.
Check
  raw_existentialIntroductionDynamicTruthStandardTailCompiler_of_result_truth.
Check raw_equalityEliminationDynamicTruthStandardTailCompiler_of_result_truth.
Check
  raw_existentialIntroductionResultTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_existentialIntroductionDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_equalityEliminationResultTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_equalityEliminationDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.

Check
  RawCoqRestrictedPADirectExistentialIntroductionEqualityEliminationKOnlyRoots.
Check
  RawCoqRestrictedPADirectExistentialIntroductionEqualityEliminationKOnlyRootsAtWitnesses.
Check
  RawCoqRestrictedPADirectExistentialIntroductionEqualityEliminationKOnlyRootsStandardTailCompiler.
Check
  raw_existentialIntroductionDynamicTruthLawRoot_surround_witnessed_tail.
Check
  raw_equalityEliminationDynamicTruthLawRoot_surround_witnessed_tail.
Check
  raw_existentialIntroductionEqualityEliminationKOnlyRootsAtWitnesses_append_stable.
Check
  raw_existentialIntroductionEqualityEliminationKOnlyRootsStandardTailCompiler_of_standalone.
Check
  raw_existentialIntroductionEqualityEliminationKOnlyRootsStandardTailCompiler_of_aligned_append_concrete_rows.

Print Assumptions
  coqRestrictedPADirectExistentialIntroductionReadyContext_app_witnesses.
Print Assumptions
  coqRestrictedPADirectEqualityEliminationReadyContext_app_witnesses.
Print Assumptions raw_existentialIntroduction_mode_zero_parent_source_aligned.
Print Assumptions raw_equalityElimination_mode_zero_parent_source_aligned.
Print Assumptions
  raw_existentialIntroductionDynamicTruthStandardTailCompiler_of_result_truth.
Print Assumptions
  raw_equalityEliminationDynamicTruthStandardTailCompiler_of_result_truth.
Print Assumptions
  raw_existentialIntroductionDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_equalityEliminationDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_existentialIntroductionDynamicTruthLawRoot_surround_witnessed_tail.
Print Assumptions
  raw_equalityEliminationDynamicTruthLawRoot_surround_witnessed_tail.
Print Assumptions
  raw_existentialIntroductionEqualityEliminationKOnlyRootsAtWitnesses_append_stable.
Print Assumptions
  raw_existentialIntroductionEqualityEliminationKOnlyRootsStandardTailCompiler_of_standalone.
Print Assumptions
  raw_existentialIntroductionEqualityEliminationKOnlyRootsStandardTailCompiler_of_aligned_append_concrete_rows.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialIntroductionEqualityEliminationAlignedTruthProductionAudit.
