From BoundedPAConsistency Require Import
  RawCodedDynamicTruthGlobalOpenedRowSelection.

Import PABoundedRawCodedDynamicTruthGlobalOpenedRowSelection.

Check coqDynamicTruthGlobalOpenedRootRowChoice_tagged_shape.
Check coqDynamicTruthGlobalOpenedRootRowRightTag_zero.
Check coqDynamicTruthGlobalOpenedRootRowLeftTag_one.
Check coqDynamicTruthGlobalOpenedRootRowLeftPayload_open_sequence.
Check coqDynamicTruthGlobalOpenedRootRowRightPayload_open_sequence.
Check embedPAFormula_paFormulaOpenSequenceUnderBinders.
Check coqDynamicTruthGlobalOpenedRootRowLeftPayload_embedPA.
Check coqDynamicTruthGlobalOpenedRootRowRightPayload_embedPA.
Check embedPAFormula_paFormulaShiftMany.
Check coqDynamicTruthGlobalOpenedRootRowSelectedPayload_embedPA.
Check
  raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_selected_under_prefix.
Check raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_selected.

Print Assumptions coqDynamicTruthGlobalOpenedRootRowChoice_tagged_shape.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowRightTag_zero.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowLeftTag_one.
Print Assumptions
  coqDynamicTruthGlobalOpenedRootRowLeftPayload_open_sequence.
Print Assumptions
  coqDynamicTruthGlobalOpenedRootRowRightPayload_open_sequence.
Print Assumptions embedPAFormula_paFormulaOpenSequenceUnderBinders.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowLeftPayload_embedPA.
Print Assumptions coqDynamicTruthGlobalOpenedRootRowRightPayload_embedPA.
Print Assumptions embedPAFormula_paFormulaShiftMany.
Print Assumptions
  coqDynamicTruthGlobalOpenedRootRowSelectedPayload_embedPA.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_selected_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthGlobal_opened_root_row_selected.
