(** Assumption audit for the cons-extension transplant factorisation. *)

From BoundedPAConsistency Require Import
  RawCodedPALocalProofConsTransplant.

Import PABoundedRawCodedPALocalProofConsTransplant.

Check RawCodedPALocalProofConsTransplant.
Check RawCodedPALocalProofConsTransplantInAllModels.
Check raw_restrictedPADynamicSoundnessTargetContext_cons_view.
Check RawRestrictedPADynamicSoundnessBaseProof.
Check RawRestrictedPADynamicSoundnessBaseProofInAllModels.
Check raw_restrictedPADynamicSoundnessProducer_of_baseProof_and_transplant.
Check
  raw_restrictedPADynamicSoundnessProducerInAllModels_of_baseProof_and_transplant.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_baseProof_and_transplant.
Check raw_codedPALocalProofOf_consTransplant_assumptionLeaf.
Check raw_codedPALocalProofOf_consTransplant_of_member.

Print Assumptions raw_restrictedPADynamicSoundnessTargetContext_cons_view.
Print Assumptions
  raw_restrictedPADynamicSoundnessProducer_of_baseProof_and_transplant.
Print Assumptions raw_codedPALocalProofOf_consTransplant_assumptionLeaf.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_baseProof_and_transplant.
