(** Compatibility umbrella for the physically split opened Ex-E source. *)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageDefinitions
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceTemplateValidity
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceReification
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceEmbedding
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceProvability
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceSubstitution.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSource.

(** Preserve the historical unqualified API while each proof family remains
    behind its own independently kernel-checkable compilation boundary. *)
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageDefinitions.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceTemplateValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceReification.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceEmbedding.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceProvability.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceSubstitution.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSource.
