(** Public surface and assumption audit for the uniform target boundary. *)

From BoundedPAConsistency Require Import RawCodedPAUniformProvability.

Import PABoundedRawCodedPAUniformProvability.

Check restrictedPAConsistencyFormulaCode.
Check restrictedPAConsistencyFormulaCodeGraph.
Check restrictedPAConsistencyFormulaCodeGraph_standard_of_computable.
Check RawRestrictedPAConsistencyProvabilityCompiler.
Check RawRestrictedPAConsistencyProvabilityCompilerInAllModels.
Check uniformRestrictedPAConsistencyProvabilityBodyFormula.
Check uniformRestrictedPAConsistencyProvabilityFormula.
Check uniformRestrictedPAConsistencyProvabilityFormula_sentence.
Check raw_sat_uniformRestrictedPAConsistencyProvabilityBodyFormula_iff.
Check uniformRestrictedPAConsistencyProvabilityFormula_raw_valid_of_compiler.
Check PA_BProv_uniformRestrictedPAConsistencyProvabilityFormula_of_compiler.
Check raw_restrictedPAConsistencyProvabilityCompiler_of_BProv.
Check PA_BProv_uniformRestrictedPAConsistencyProvabilityFormula_iff_compiler.
Check PA_BProv_each_standard_restrictedPAConsistencyProvability.

Print Assumptions
  restrictedPAConsistencyFormulaCodeGraph_standard_of_computable.
Print Assumptions
  raw_sat_uniformRestrictedPAConsistencyProvabilityBodyFormula_iff.
Print Assumptions
  PA_BProv_uniformRestrictedPAConsistencyProvabilityFormula_of_compiler.
Print Assumptions
  raw_restrictedPAConsistencyProvabilityCompiler_of_BProv.
Print Assumptions
  PA_BProv_uniformRestrictedPAConsistencyProvabilityFormula_iff_compiler.
Print Assumptions
  PA_BProv_each_standard_restrictedPAConsistencyProvability.
