(**
  Assumption audit for the ordinary global Sigma/Pi formula-code graphs.

  In particular, the final two checks audit the unconditional nonstandard
  totality obtained from the concrete paired global orbit.
*)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthGlobalPolarityFormulaCodeGraphs.

Import PABoundedRawCodedDynamicTruthGlobalPolarityFormulaCodeGraphs.

Check dynamicTruthGlobalSigmaFormulaCodeProjectionRenaming.
Check raw_sat_dynamicTruthGlobalSigmaFormulaCodeProjectionRenamed_iff.
Check dynamicTruthGlobalSigmaFormulaCodeGraph.
Check RawDynamicTruthGlobalSigmaFormulaCodeAt.
Check raw_sat_dynamicTruthGlobalSigmaFormulaCodeGraph_iff.
Check dynamicTruthGlobalPiFormulaCodeGraph.
Check RawDynamicTruthGlobalPiFormulaCodeAt.
Check raw_sat_dynamicTruthGlobalPiFormulaCodeGraph_iff.

Check raw_dynamicTruthGlobalSigmaFormulaCodeAt_zero_iff.
Check raw_dynamicTruthGlobalPiFormulaCodeAt_zero_iff.
Check raw_sat_dynamicTruthGlobalSigmaFormulaCodeGraph_zero_iff.
Check raw_sat_dynamicTruthGlobalPiFormulaCodeGraph_zero_iff.

Check raw_dynamicTruthGlobalSigmaFormulaCodeAt_succ_iff.
Check raw_dynamicTruthGlobalPiFormulaCodeAt_succ_iff.
Check raw_sat_dynamicTruthGlobalSigmaFormulaCodeGraph_succ_iff.
Check raw_sat_dynamicTruthGlobalPiFormulaCodeGraph_succ_iff.

Check dynamicTruthGlobalSigmaFormulaCodeGraph_adequate_total.
Check dynamicTruthGlobalPiFormulaCodeGraph_adequate_total.
Check dynamicTruthGlobalSigmaFormulaCodeGraph_raw_adequate_total.
Check dynamicTruthGlobalPiFormulaCodeGraph_raw_adequate_total.

Print Assumptions
  raw_sat_dynamicTruthGlobalSigmaFormulaCodeProjectionRenamed_iff.
Print Assumptions raw_sat_dynamicTruthGlobalSigmaFormulaCodeGraph_iff.
Print Assumptions raw_sat_dynamicTruthGlobalPiFormulaCodeGraph_iff.

Print Assumptions raw_dynamicTruthGlobalSigmaFormulaCodeAt_zero_iff.
Print Assumptions raw_dynamicTruthGlobalPiFormulaCodeAt_zero_iff.
Print Assumptions raw_sat_dynamicTruthGlobalSigmaFormulaCodeGraph_zero_iff.
Print Assumptions raw_sat_dynamicTruthGlobalPiFormulaCodeGraph_zero_iff.
Print Assumptions raw_dynamicTruthGlobalSigmaFormulaCodeAt_succ_iff.
Print Assumptions raw_dynamicTruthGlobalPiFormulaCodeAt_succ_iff.
Print Assumptions raw_sat_dynamicTruthGlobalSigmaFormulaCodeGraph_succ_iff.
Print Assumptions raw_sat_dynamicTruthGlobalPiFormulaCodeGraph_succ_iff.

Print Assumptions dynamicTruthGlobalSigmaFormulaCodeGraph_adequate_total.
Print Assumptions dynamicTruthGlobalPiFormulaCodeGraph_adequate_total.
Print Assumptions
  dynamicTruthGlobalSigmaFormulaCodeGraph_raw_adequate_total.
Print Assumptions dynamicTruthGlobalPiFormulaCodeGraph_raw_adequate_total.
