(** Assumption audit for finite universal-elimination chains. *)

From BoundedPAConsistency Require Import
  RawCodedPALocalProofUniversalEliminationChain.

Import PABoundedRawCodedPALocalProofUniversalEliminationChain.

Check RawCodedUniversalEliminationChain.
Check raw_codedUniversalEliminationChain_all3_of_diagonal.
Check RCUENil.
Check RCUECons.
Check templateUniversalOpenMany.
Check templateUniversalOpenManyOrBot.
Check templateUniversalOpenManyOrBot_of_success.
Check raw_templateUniversalOpenMany_elimination_chain.
Check raw_codedPALocalProofOf_universal_elimination_chain.
Check raw_codedPALocalProofOf_templateUniversalOpenMany.
Check raw_codedPALocalProofOf_templateUniversalOpenMany_impE2.
Check raw_codedPALocalProofOf_templateUniversalOpenMany_list.
Check
  raw_codedTemplatePALocalProofOf_of_BProv_then_universal_chain_on_witnessed_tail.
Check
  raw_codedTemplatePALocalProofOf_of_BProv_open_many_on_witnessed_tail.
Check
  raw_codedTemplatePALocalProofOf_of_BProv_open_many_list_on_witnessed_tail.

Print Assumptions raw_templateUniversalOpenMany_elimination_chain.
Print Assumptions templateUniversalOpenManyOrBot_of_success.
Print Assumptions raw_codedPALocalProofOf_universal_elimination_chain.
Print Assumptions raw_codedUniversalEliminationChain_all3_of_diagonal.
Print Assumptions raw_codedPALocalProofOf_templateUniversalOpenMany.
Print Assumptions
  raw_codedPALocalProofOf_templateUniversalOpenMany_impE2.
Print Assumptions raw_codedPALocalProofOf_templateUniversalOpenMany_list.
Print Assumptions
  raw_codedTemplatePALocalProofOf_of_BProv_then_universal_chain_on_witnessed_tail.
Print Assumptions
  raw_codedTemplatePALocalProofOf_of_BProv_open_many_on_witnessed_tail.
Print Assumptions
  raw_codedTemplatePALocalProofOf_of_BProv_open_many_list_on_witnessed_tail.
