(** Assumption and API audit for the deeply closed global code orbit. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitGraph.

Import
  PABoundedRawCodedDynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitGraph.

Check RawDynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitAt.
Check dynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitExistsFormula.
Check
  raw_sat_dynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitExistsFormula_iff.

Check rawDynamicTruthGlobalSigmaBaseCode_deep_closed.
Check rawDynamicTruthGlobalPiBaseCode_deep_closed.
Check dynamicTruthPairedGlobalBaseAt_deep_closed.
Check dynamicTruthPairedGlobalOrbitBaseGraph_raw_deep_closed_total.

Check RawDynamicTruthPairedGlobalOrbitDeepClosedSuccessorTotal.
Check
  dynamicTruthPairedGlobalOrbitDeepClosedSuccessorTotal_of_local_closure.
Check dynamicTruthPairedGlobalSuccessorGraph_preserves_deep_closure.
Check dynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitExists_all.
Check dynamicTruthPairedGlobalFormulaCodeOrbitGraph_raw_deep_closed_total.

Print Assumptions
  raw_sat_dynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitExistsFormula_iff.
Print Assumptions rawDynamicTruthGlobalSigmaBaseCode_deep_closed.
Print Assumptions rawDynamicTruthGlobalPiBaseCode_deep_closed.
Print Assumptions dynamicTruthPairedGlobalOrbitBaseGraph_raw_deep_closed_total.
Print Assumptions
  dynamicTruthPairedGlobalOrbitDeepClosedSuccessorTotal_of_local_closure.
Print Assumptions dynamicTruthPairedGlobalSuccessorGraph_preserves_deep_closure.
Print Assumptions dynamicTruthPairedGlobalDeepClosedFormulaCodeOrbitExists_all.
Print Assumptions
  dynamicTruthPairedGlobalFormulaCodeOrbitGraph_raw_deep_closed_total.
