From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessOrIntroductionLeftNativeLawTransport.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessOrIntroductionLeftNativeLawTransport.

Check rawCoqRestrictedPADirectOrIntroductionLeftNativeTruthLawCode.
Check raw_coqRestrictedPADirectOrIntroductionLeftNativeTruthLaw_code.
Check RawCoqRestrictedPADirectOrIntroductionLeftNativeTruthLawRoot.
Check raw_publicOrIntroductionLeftTruthLawRoot_of_native.
Check raw_nativeOrIntroductionLeftTruthLawRoot_of_dynamic_reroot.
Check RawCoqRestrictedPADirectSelectedNativeOrIntroductionLeftTruthTail.
Check raw_selectedPublicOrIntroductionLeftTruthTail_of_native.
Check raw_selectedNativeOrIntroductionLeftTruthTail_of_dynamic_reroot.
Check RawCoqRestrictedPADirectDynamicTruthLawRootAtEmpty.
Check raw_selectedNativeOrIntroductionLeftTruthTail_of_dynamic_reroot_at_empty.
Check RawCoqRestrictedPADirectDynamicTruthLawCompiler.
Check
  RawCoqRestrictedPADirectLinkedNativeOrIntroductionLeftTruthCompiler.
Check
  raw_selectedPublicOrIntroductionLeftTruthTail_of_nativeDirectTruthInputsWithClosureAt.
Check
  raw_selectedPublicOrIntroductionLeftTruthTail_of_nativeDirectTruthInputsWithClosureAt_of_dynamic_reroot.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeDirectTruthInputsWithClosureAt_of_dynamic_reroot.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeDirectTruthInputsWithClosureAt_of_dynamic_reroot_at_empty.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_linkedNativeOrIntroductionLeftTruth.

Print Assumptions
  raw_coqRestrictedPADirectOrIntroductionLeftNativeTruthLaw_code.
Print Assumptions raw_publicOrIntroductionLeftTruthLawRoot_of_native.
Print Assumptions raw_nativeOrIntroductionLeftTruthLawRoot_of_dynamic_reroot.
Print Assumptions raw_selectedPublicOrIntroductionLeftTruthTail_of_native.
Print Assumptions raw_selectedNativeOrIntroductionLeftTruthTail_of_dynamic_reroot.
Print Assumptions RawCoqRestrictedPADirectDynamicTruthLawRootAtEmpty.
Print Assumptions raw_selectedNativeOrIntroductionLeftTruthTail_of_dynamic_reroot_at_empty.
Print Assumptions RawCoqRestrictedPADirectDynamicTruthLawCompiler.
Print Assumptions
  raw_selectedPublicOrIntroductionLeftTruthTail_of_nativeDirectTruthInputsWithClosureAt.
Print Assumptions
  raw_selectedPublicOrIntroductionLeftTruthTail_of_nativeDirectTruthInputsWithClosureAt_of_dynamic_reroot.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeDirectTruthInputsWithClosureAt_of_dynamic_reroot.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeDirectTruthInputsWithClosureAt_of_dynamic_reroot_at_empty.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_linkedNativeOrIntroductionLeftTruth.
