(** Authoritative API and assumptions audit for the dependency-ordered
    call-site cross-level reduction. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelBoundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelBoundary.

Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilers_of_trace_proof.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevel_trace_proof_kernel_compilers.
Check
  RawDynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilersInAllModels_of_trace_proof.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevel_trace_proof_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevel_trace_proof_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilers_of_trace_proof.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_currentPackageCrossLevel_trace_proof_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCurrentPackageCrossLevelTraceProofKernelCompilersInAllModels_of_trace_proof.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_currentPackageCrossLevel_trace_proof_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_currentPackageCrossLevel_trace_proof_kernel_compilers.
