From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeGlobalEvidencePermutation.

Import
  PABoundedRawCodedDynamicTruthNativeGlobalEvidencePermutation.

Check templateReverseFirstThreeRenaming.
Check coqDynamicTruthSharedSigmaGlobalTernaryApplication_reverse.
Check coqDynamicTruthSharedPiGlobalTernaryApplication_reverse.
Check raw_coqDynamicTruthSharedSigmaGlobalTernaryApplication_reverse_trace.
Check raw_coqDynamicTruthSharedPiGlobalTernaryApplication_reverse_trace.

Print Assumptions
  coqDynamicTruthSharedSigmaGlobalTernaryApplication_reverse.
Print Assumptions
  coqDynamicTruthSharedPiGlobalTernaryApplication_reverse.
Print Assumptions
  raw_coqDynamicTruthSharedSigmaGlobalTernaryApplication_reverse_trace.
Print Assumptions
  raw_coqDynamicTruthSharedPiGlobalTernaryApplication_reverse_trace.
