(** Audit for ten-witness global elimination over predecessor state. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPredecessorGlobalExistentialElimination.

Import
  PABoundedRawCodedDynamicTruthPredecessorGlobalExistentialElimination.

Check coqDynamicTruthPredecessorStateTemplateContext.
Check coqDynamicTruthGlobalRowsTemplate.
Check coqDynamicTruthGlobalTraversalBodyTemplate.
Check coqDynamicTruthGlobalExistentialSource.
Check coqDynamicTruthGlobalRowsTemplate_embed.
Check coqDynamicTruthGlobalExistentialSource_embed.
Check rawTemplateFormula_dynamicTruthGlobalExistentialSource.
Check rawTemplateFormula_dynamicTruthGlobalSources_of_wrapper.
Check coqDynamicTruthGlobalExistentialDeepContext.
Check coqDynamicTruthGlobalExistentialDeepContextUnderPrefix.
Check coqDynamicTruthGlobalExistentialDeepContext_success.
Check coqDynamicTruthGlobalExistentialDeepContextUnderPrefix_success.
Check raw_dynamicTruthPredecessorStateTemplateContextCode.
Check raw_dynamicTruthPredecessorStateTemplateContext_app_code.
Check
  raw_codedPALocalProofOf_dynamicTruthGlobal_existential_elimination_on_predecessor_state_context_under_prefix.
Check
  raw_codedPALocalProofOf_dynamicTruthGlobal_existential_elimination_on_predecessor_state_context.

Print Assumptions coqDynamicTruthGlobalExistentialDeepContext_success.
Print Assumptions
  coqDynamicTruthGlobalExistentialDeepContextUnderPrefix_success.
Print Assumptions raw_dynamicTruthPredecessorStateTemplateContextCode.
Print Assumptions raw_dynamicTruthPredecessorStateTemplateContext_app_code.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthGlobal_existential_elimination_on_predecessor_state_context_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthGlobal_existential_elimination_on_predecessor_state_context.
Print Assumptions coqDynamicTruthGlobalRowsTemplate_embed.
Print Assumptions coqDynamicTruthGlobalExistentialSource_embed.
Print Assumptions rawTemplateFormula_dynamicTruthGlobalExistentialSource.
Print Assumptions rawTemplateFormula_dynamicTruthGlobalSources_of_wrapper.
