(** Audit surface for shared-template-prefix witnessed-tail transport. *)

From BoundedPAConsistency Require Import
  RawCodedTemplateLocalProofWitnessedTailTransport.

Import PABoundedRawCodedTemplateLocalProofWitnessedTailTransport.

Check RawCodedTemplatePrefixAtomicallyAdequate.
Check raw_codedPALocalProof_templatePrefix.
Check raw_codedPALocalProof_templatePrefix_list.
Check raw_codedPALocalProof_templatePrefix_indexed.
Check raw_templateContextCodeOnTail_included.
Check raw_templateContextCodeOnTail_binderReady.
Check raw_codedPALocalProof_sameTemplatePrefix_transport.
Check raw_codedPALocalProof_sameTemplatePrefix_witnessedTail_transport.
Check
  raw_codedPALocalProof_sameTemplatePrefix_witnessedTail_transport_list.
Check
  raw_codedPALocalProof_sameTemplatePrefix_witnessedTail_transport_indexed.

Print Assumptions raw_templateContextCodeOnTail_included.
Print Assumptions raw_codedPALocalProof_templatePrefix.
Print Assumptions raw_codedPALocalProof_templatePrefix_list.
Print Assumptions raw_codedPALocalProof_templatePrefix_indexed.
Print Assumptions raw_templateContextCodeOnTail_binderReady.
Print Assumptions raw_codedPALocalProof_sameTemplatePrefix_transport.
Print Assumptions
  raw_codedPALocalProof_sameTemplatePrefix_witnessedTail_transport.
Print Assumptions
  raw_codedPALocalProof_sameTemplatePrefix_witnessedTail_transport_list.
Print Assumptions
  raw_codedPALocalProof_sameTemplatePrefix_witnessedTail_transport_indexed.
