(** Assumptions audit for guarded Boolean direct-child admissibility. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthBooleanDirectChildAdmissibilityProofCompilation.

Import
  PABoundedRawCodedDynamicTruthBooleanDirectChildAdmissibilityProofCompilation.

Check raw_codedFormulaAtomicallyAdequate_and_children.
Check raw_codedFormulaAtomicallyAdequate_or_children.
Check raw_codedFormulaAtomicallyAdequate_boolean_children.
Check raw_dynamicTruthSigmaRecordDomain_and_or_from_view.
Check raw_dynamicTruthPiRecordDomain_and_or_from_view.
Check raw_dynamicTruthRecordDomain_boolean_children.
Check raw_dynamicTruthBooleanDirectChild_admissibility_core.
Check PA_proves_dynamicTruthBooleanDirectChildAdmissibilityCoreFormula.
Check
  coqDynamicTruthBooleanDirectChildAtomicPremiseTemplate_eq_imp.
Check
  coqDynamicTruthBooleanDirectChildDomainPremiseTemplate_eq_imp.
Check coqDynamicTruthBooleanGuardedChildAdmissibleTemplate_eq_imp.
Check
  raw_codedPALocalProofOf_dynamicTruthBooleanDirectChildAdmissibilityCore_of_roots_on_witnessed_extension_under_prefix.
Check
  raw_codedPALocalProofOf_dynamicTruthBooleanGuardedChildAdmissible_of_parent_roots_on_witnessed_extension_under_prefix.

Print Assumptions raw_codedFormulaAtomicallyAdequate_boolean_children.
Print Assumptions raw_dynamicTruthRecordDomain_boolean_children.
Print Assumptions
  PA_proves_dynamicTruthBooleanDirectChildAdmissibilityCoreFormula.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthBooleanDirectChildAdmissibilityCore_of_roots_on_witnessed_extension_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthBooleanGuardedChildAdmissible_of_parent_roots_on_witnessed_extension_under_prefix.
