(** Assumption audit for opening-after-shift syntax stability. *)

From BoundedPAConsistency Require Import
  RawCodedTermOpeningAfterShiftSyntaxStability.

Import PABoundedRawCodedTermOpeningAfterShiftSyntaxStability.

Check RawTermOpeningAfterShiftSupportDesired.
Check termOpeningAfterShiftSupportDesiredTermAt.
Check raw_sat_termOpeningAfterShiftSupportDesiredTermAt_iff.
Check RawTermOpeningAfterShiftSupportPrefix.
Check termOpeningAfterShiftSupportPrefixTermAt.
Check raw_sat_termOpeningAfterShiftSupportPrefixTermAt_iff.
Check RawTermOpeningAfterShiftSupportPrefixRealizable.
Check termOpeningAfterShiftSupportPrefixRealizableTermAt.
Check raw_sat_termOpeningAfterShiftSupportPrefixRealizableTermAt_iff.
Check raw_termOpeningAfterShiftSupportPrefix_exists.
Check raw_termSyntaxStep_support_mono.
Check raw_termOpening_code_lt_enclosing.
Check raw_codedTermOpeningTrace_target_syntax_realizable_after_shift.
Check raw_codedTermOpeningAfterShiftSyntaxStable_of_PA.
Check raw_codedFormulaSingleSubstitution_three_exists_total.

Print Assumptions raw_termOpeningAfterShiftSupportPrefix_exists.
Print Assumptions raw_codedTermOpeningTrace_target_syntax_realizable_after_shift.
Print Assumptions raw_codedTermOpeningAfterShiftSyntaxStable_of_PA.
Print Assumptions raw_codedFormulaSingleSubstitution_three_exists_total.
