(** Strict audit for the same-context-unary-free aligned post-And-I endpoint. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlySameContextUnaryIntegration.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlySameContextUnaryIntegrationAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlySameContextUnaryIntegration.

Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_six_rows_and_sevenFieldChildOnlyRemainder.

Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_six_rows_and_sevenFieldChildOnlyRemainder.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlySameContextUnaryIntegrationAudit.
