From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroPredecessorLogicalRootsCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeZeroPredecessorLogicalRootsCompilation.

Check raw_dynamicTruthZeroLocalDecisionExclusiveFieldCode.
Check RawDynamicTruthZeroGrowingLogicalRootsCompilerOnWitnessedBase.
Check dynamicTruthZeroLogicalRootsLawFormula.
Check raw_dynamicTruthZeroLocalAdmissibleCode.
Check
  raw_dynamicTruthZeroGrowingLogicalRootsCompilerOnWitnessedBase_of_PA_law.
Check raw_dynamicTruthNativeLocalProofTraceAt_zero_global_predecessor.
Check
  RawDynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerOnCanonicalGlobalStep.
Check
  RawDynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerOnWitnessedBase.
Check
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerOnWitnessedBase_of_fixed_logical_roots.
Check
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerOnWitnessedBase_of_canonical_global_step.
Check
  raw_dynamicTruthNativeLocalZeroPredecessorRootCompiler_of_growing_logical_roots.

Print Assumptions raw_dynamicTruthZeroLocalDecisionExclusiveFieldCode.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerOnWitnessedBase_of_fixed_logical_roots.
Print Assumptions
  raw_dynamicTruthZeroGrowingLogicalRootsCompilerOnWitnessedBase_of_PA_law.
Print Assumptions
  raw_dynamicTruthNativeLocalProofTraceAt_zero_global_predecessor.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroGrowingLogicalRootsCompilerOnWitnessedBase_of_canonical_global_step.
Print Assumptions
  raw_dynamicTruthNativeLocalZeroPredecessorRootCompiler_of_growing_logical_roots.
