(** Assumption and exact-slot audit for the direct implication-introduction
    constructor case. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectImpIntroductionCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectImpIntroductionCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectImpIntroductionCase.

Check coqRestrictedPADirectImpIntroductionCaseTemplate.
Check coqRestrictedPADirectImpIntroduction_case_shape.
Check coqRestrictedPADirectImpIntroductionFormulaCodeTemplate.
Check coqRestrictedPADirectImpIntroductionChildEndpointTemplate.
Check coqRestrictedPADirectImpIntroductionAntecedentTruthTemplate.
Check coqRestrictedPADirectImpIntroductionConsequentTruthTemplate.

Check coqRestrictedPADirectImpIntroductionRecursiveChildLawTemplate.
Check coqRestrictedPADirectImpIntroductionDynamicTruthLawTemplate.
Check RawCoqRestrictedPADirectImpIntroductionRecursiveChildLawRoot.
Check RawCoqRestrictedPADirectImpIntroductionDynamicTruthLawRoot.

Check coqRestrictedPADirectImpIntroductionFormulaCodeRootAt_valid.
Check coqRestrictedPADirectImpIntroductionChildEndpointRootAt_valid.
Check raw_codedPALocalProofOf_coqRestrictedPADirectImpIntroductionConclusion.
Check raw_coqRestrictedPADirectStrongStepImpIntroductionCaseRoot.

Print Assumptions
  coqRestrictedPADirectImpIntroductionFormulaCodeRootAt_valid.
Print Assumptions
  coqRestrictedPADirectImpIntroductionChildEndpointRootAt_valid.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectImpIntroductionConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepImpIntroductionCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectImpIntroductionCaseAudit.
