From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionContextTruthExpansion.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionContextTruthExpansion.

Check coqRestrictedPADynamicContextSigmaLeafTemplate.
Check coqRestrictedPADynamicContextPointwiseTemplate.
Check coqRestrictedPADynamicContextPredicateBodyTemplate.
Check coqRestrictedPADynamicContextPredicateTemplate.
Check raw_coqRestrictedPADynamicContextPredicateTemplate_code.
Check raw_coqRestrictedPADynamicContextPredicateTemplate_output.
Check raw_coqRestrictedPADynamicContextPredicateTemplate_native_output.
Check raw_coqRestrictedPAContextTruthLeaf_expansion.

Print Assumptions raw_coqRestrictedPADynamicContextPredicateTemplate_code.
Print Assumptions raw_coqRestrictedPADynamicContextPredicateTemplate_output.
Print Assumptions
  raw_coqRestrictedPADynamicContextPredicateTemplate_native_output.
Print Assumptions raw_coqRestrictedPAContextTruthLeaf_expansion.
