(** Assumption audit for the paired global dynamic-truth formula-code orbit. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPairedGlobalFormulaCodeOrbitGraph.

Import PABoundedRawCodedDynamicTruthPairedGlobalFormulaCodeOrbitGraph.

Check dynamicTruthPairedGlobalFormulaCodeOrbitGraph.
Check RawDynamicTruthPairedGlobalFormulaCodeOrbitAt.
Check RawDynamicTruthPairedGlobalFormulaCodeAdequateOrbitAt.
Check raw_sat_dynamicTruthPairedGlobalFormulaCodeOrbitGraph_iff.
Check raw_dynamicTruthPairedGlobalFormulaCodeAdequateOrbitAt_iff.
Check raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_zero_iff.
Check raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_succ_iff.
Check raw_sat_dynamicTruthPairedGlobalFormulaCodeOrbitGraph_zero_iff.
Check raw_sat_dynamicTruthPairedGlobalFormulaCodeOrbitGraph_succ_iff.
Check dynamicTruthPairedGlobalFormulaCodeOrbitGraph_adequate_total.
Check dynamicTruthPairedGlobalFormulaCodeOrbitGraph_raw_adequate_total.

Print Assumptions raw_sat_dynamicTruthPairedGlobalFormulaCodeOrbitGraph_iff.
Print Assumptions
  raw_dynamicTruthPairedGlobalFormulaCodeAdequateOrbitAt_iff.
Print Assumptions raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_zero_iff.
Print Assumptions raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_succ_iff.
Print Assumptions
  raw_sat_dynamicTruthPairedGlobalFormulaCodeOrbitGraph_zero_iff.
Print Assumptions
  raw_sat_dynamicTruthPairedGlobalFormulaCodeOrbitGraph_succ_iff.
Print Assumptions
  dynamicTruthPairedGlobalFormulaCodeOrbitGraph_adequate_total.
Print Assumptions
  dynamicTruthPairedGlobalFormulaCodeOrbitGraph_raw_adequate_total.
