(** Assumption audit for arbitrary-code formula substitution totality. *)

From BoundedPAConsistency Require Import
  RawCodedFormulaSingleSubstitutionTotality.

Import PABoundedRawCodedFormulaSingleSubstitutionTotality.

Check RawCodedTermOpeningTotal.
Check raw_codedFormulaSubstitutionAtom_exists.
Check raw_codedFormulaSubstitution_binary_composition.
Check raw_codedFormulaSubstitution_unary_composition.
Check RawCodedFormulaSingleSubstitutionTotalBelow.
Check codedFormulaSingleSubstitutionTotalBelowTermAt.
Check raw_sat_codedFormulaSingleSubstitutionTotalBelowTermAt_iff.
Check raw_codedFormulaSingleSubstitutionTotalBelow_succ.
Check raw_codedFormulaSingleSubstitutionTotalBelow_all.
Check raw_codedFormulaSubstitutionAt_exists_of_atomically_adequate.
Check raw_codedFormulaSingleSubstitution_exists_of_atomically_adequate.

Print Assumptions raw_codedFormulaSubstitution_binary_composition.
Print Assumptions raw_codedFormulaSubstitution_unary_composition.
Print Assumptions raw_codedFormulaSingleSubstitutionTotalBelow_succ.
Print Assumptions raw_codedFormulaSingleSubstitutionTotalBelow_all.
Print Assumptions raw_codedFormulaSingleSubstitution_exists_of_atomically_adequate.
