(** Public API and assumption audit for the restricted Pi row compiler. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPiExistentialLeafProofCompilation.

Import PABoundedRawCodedDynamicTruthPiExistentialLeafProofCompilation.

Check rawCoqDynamicTruthPiRestrictedProjectionCertificate.
Check raw_codedPAProofOf_coqDynamicTruthPiRestrictedProjection.
Check raw_codedPAProofOf_coqDynamicTruthPiRestrictedProjection_identified.

Check coqDynamicTruthPiRowEnvironmentArity.
Check coqDynamicTruthPiRestrictedExistentialFieldFormula.
Check coqDynamicTruthPiRestrictedExistentialFieldProof.
Check coqDynamicTruthPiRestrictedExistentialFieldProof_derives.
Check rawCoqDynamicTruthPiRestrictedExistentialFieldCode.
Check rawDirect_coqDynamicTruthPiRestrictedExistentialField_identified.
Check rawCoqDynamicTruthPiRestrictedExistentialFieldCertificate.
Check raw_codedPAProofOf_coqDynamicTruthPiRestrictedExistentialField.
Check raw_codedPAProofOf_coqDynamicTruthPiRestrictedExistentialField_identified.

Check RawCoqDynamicTruthPiRestrictedExistentialFieldIdentification.
Check rawCoqDynamicTruthPiRestrictedExistentialField_template.
Check rawCoqDynamicTruthPiRestrictedExistentialField_output.
Check raw_codedPAProofOf_coqDynamicTruthPiRestrictedExistentialField_output.

Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthPiRestrictedProjection.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthPiRestrictedProjection_identified.
Print Assumptions
  coqDynamicTruthPiRestrictedExistentialFieldProof_derives.
Print Assumptions
  rawDirect_coqDynamicTruthPiRestrictedExistentialField_identified.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthPiRestrictedExistentialField.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthPiRestrictedExistentialField_identified.
Print Assumptions
  raw_codedPAProofOf_coqDynamicTruthPiRestrictedExistentialField_output.
