(** Audit surface for the fixed-level derivation-code soundness predicate. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessPredicate.

Import PABoundedRawCodedRestrictedPADerivationSoundnessPredicate.

Check restrictedPADerivationSoundnessPredicateTermAt.
Check RawRestrictedPADerivationSoundnessAt.
Check raw_sat_restrictedPADerivationSoundnessPredicateTermAt_iff.

Check restrictedPADerivationSoundnessPrefixTermAt.
Check RawRestrictedPADerivationSoundnessPrefix.
Check raw_sat_restrictedPADerivationSoundnessPrefixTermAt_iff.
Check raw_restrictedPADerivationSoundnessPrefix_iff_sigmaSoundBelow.

Check restrictedPADerivationSoundnessStrongStepFormula.
Check RawRestrictedPADerivationSoundnessStrongStep.
Check raw_sat_restrictedPADerivationSoundnessStrongStepFormula_iff.
Check raw_restrictedPADerivationSoundnessStrongStep_of_rule_sound.
Check rawRestrictedPADerivationSoundnessPredicateCode.
Check rawRestrictedPADerivationSoundnessPrefixCode.
Check rawRestrictedPADerivationSoundnessStrongStepCode.

Check RestrictedPADerivationSoundnessPrefixScoped.
Check raw_codedRestrictedPADerivationSoundnessInductionBody_diagonal.
Check raw_codedRestrictedPADerivationSoundnessClosureInductionData.

Print Assumptions
  raw_sat_restrictedPADerivationSoundnessPredicateTermAt_iff.
Print Assumptions
  raw_sat_restrictedPADerivationSoundnessPrefixTermAt_iff.
Print Assumptions
  raw_restrictedPADerivationSoundnessPrefix_iff_sigmaSoundBelow.
Print Assumptions
  raw_sat_restrictedPADerivationSoundnessStrongStepFormula_iff.
Print Assumptions
  raw_restrictedPADerivationSoundnessStrongStep_of_rule_sound.
Print Assumptions
  raw_codedRestrictedPADerivationSoundnessInductionBody_diagonal.
Print Assumptions
  raw_codedRestrictedPADerivationSoundnessClosureInductionData.
