(** Kernel-facing audit for the five native positive local-proof totals. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativePositiveLocalProofTotals.

Import PABoundedRawCodedDynamicTruthNativePositiveLocalProofTotals.

Check RawDynamicTruthNativePositiveGraphLocalProofTotal.
Check RawDynamicTruthNativeLocalPositiveLocalProofTotal.
Check RawDynamicTruthNativeCrossLevelPositiveLocalProofTotal.
Check RawDynamicTruthNativeShiftPositiveLocalProofTotal.
Check RawDynamicTruthNativeSubstitutionPositiveLocalProofTotal.
Check RawDynamicTruthNativeAxiomSoundnessPositiveLocalProofTotal.
Check RawDynamicTruthNativePositiveLocalProofTotals.
Check raw_dynamicTruthNativePositive_adequateOrbit_of_graph.
Check
  raw_codedPALocalProofOf_dynamicTruthNativeCrossLevelField_of_body_root.
Check raw_codedPALocalProofOf_dynamicTruthNativeShiftField_of_body_root.
Check
  raw_codedPALocalProofOf_dynamicTruthNativeSubstitutionField_of_body_root.
Check
  raw_codedPALocalProofOf_dynamicTruthNativeAxiomSoundnessField_of_local_root.
Check dynamicTruthNativeLocalPositiveGraph_raw_local_proof_total_of_leaves.
Check
  dynamicTruthNativeCrossLevelPositiveGraph_raw_local_proof_total_of_local_roots.
Check
  dynamicTruthNativeShiftPositiveGraph_raw_local_proof_total_of_local_roots.
Check
  dynamicTruthNativeSubstitutionPositiveGraph_raw_local_proof_total_of_local_roots.
Check
  dynamicTruthNativeAxiomSoundnessPositiveGraph_raw_local_proof_total_of_local_roots.
Check dynamicTruthNativePositiveLocalProofTotals_of_local_roots.

Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeCrossLevelField_of_body_root.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeShiftField_of_body_root.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeSubstitutionField_of_body_root.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeAxiomSoundnessField_of_local_root.
Print Assumptions
  dynamicTruthNativeLocalPositiveGraph_raw_local_proof_total_of_leaves.
Print Assumptions
  dynamicTruthNativeCrossLevelPositiveGraph_raw_local_proof_total_of_local_roots.
Print Assumptions
  dynamicTruthNativeShiftPositiveGraph_raw_local_proof_total_of_local_roots.
Print Assumptions
  dynamicTruthNativeSubstitutionPositiveGraph_raw_local_proof_total_of_local_roots.
Print Assumptions
  dynamicTruthNativeAxiomSoundnessPositiveGraph_raw_local_proof_total_of_local_roots.
Print Assumptions dynamicTruthNativePositiveLocalProofTotals_of_local_roots.
