(** Compatibility umbrella for independently checked Or-E child shapes. *)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesDefinitions
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildInterfaceShape
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildBelowShape
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildRestrictedShape
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildEndpointShape
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildAdmissibleShape.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesCore.

(** Preserve the Core import used by all semantic iff leaves while making
    every potentially expensive reflexive shape proof opaque to its peers. *)
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesDefinitions.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildInterfaceShape.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildBelowShape.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildRestrictedShape.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildEndpointShape.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageChildAdmissibleShape.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesCore.
