From BoundedPAConsistency Require Import
  RawCodedDynamicTruthDeepClosedRestrictedLocalProofFields.

Import
  PABoundedRawCodedDynamicTruthDeepClosedRestrictedLocalProofFields.

Check RawCodedTernaryPredicateDeepClosedOpeningInterchangeTotal.
Check
  raw_codedTernaryPredicateDeepClosedOpeningInterchangeTotal_of_PA.
Check dynamicTruthPairedGlobalDeepClosedOrbit_interchange_exists.
Check
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_deep_closed_orbit.
Check
  dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total_of_deep_closed_orbit.
Check dynamicTruthDeepClosedRestrictedLocalProofFields_raw_proof_total.
Check
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_local_closure.
Check
  dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total_of_local_closure.
Check
  dynamicTruthDeepClosedRestrictedLocalProofFields_raw_proof_total_of_local_closure.

Print Assumptions
  dynamicTruthPairedGlobalDeepClosedOrbit_interchange_exists.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_deep_closed_orbit.
Print Assumptions
  dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total_of_deep_closed_orbit.
Print Assumptions
  dynamicTruthDeepClosedRestrictedLocalProofFields_raw_proof_total.
Print Assumptions
  raw_codedTernaryPredicateDeepClosedOpeningInterchangeTotal_of_PA.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalLocalProofFieldGraph_raw_proof_total_of_local_closure.
Print Assumptions
  dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total_of_local_closure.
Print Assumptions
  dynamicTruthDeepClosedRestrictedLocalProofFields_raw_proof_total_of_local_closure.
