(** Assumption and API audit for the paired deep-closed orbit graph. *)

From BoundedPAConsistency Require Import
  RawCodedCarrierIndexedPairedDeepClosedCodeOrbitGraph.

Import PABoundedRawCodedCarrierIndexedPairedDeepClosedCodeOrbitGraph.

Check RawCarrierIndexedPairedDeepClosedCodeOrbitBaseTotal.
Check RawCarrierIndexedPairedDeepClosedCodeOrbitSuccessorTotal.
Check RawCarrierIndexedPairedDeepClosedCodeOrbitAt.
Check carrierIndexedPairedDeepClosedCodeOrbitExistsFormula.
Check raw_sat_carrierIndexedPairedDeepClosedCodeOrbitExistsFormula_iff.
Check raw_carrierIndexedPairedDeepClosedCodeOrbitExists_zero.
Check raw_carrierIndexedPairedDeepClosedCodeOrbitExists_succ.
Check raw_carrierIndexedPairedDeepClosedCodeOrbitExists_all.
Check RawCarrierIndexedPairedDeepClosedCodeOrbitGraphTotal.
Check raw_carrierIndexedPairedDeepClosedCodeOrbitGraph_total.

Print Assumptions
  raw_sat_carrierIndexedPairedDeepClosedCodeOrbitExistsFormula_iff.
Print Assumptions raw_carrierIndexedPairedDeepClosedCodeOrbitExists_zero.
Print Assumptions raw_carrierIndexedPairedDeepClosedCodeOrbitExists_succ.
Print Assumptions raw_carrierIndexedPairedDeepClosedCodeOrbitExists_all.
Print Assumptions raw_carrierIndexedPairedDeepClosedCodeOrbitGraph_total.
