(** Compatibility umbrella for the physically split opened Or-E source. *)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageLawValidity
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceReification
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceEmbedding
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceProvability
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceSubstitution.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSource.

(** Preserve the historical unqualified API while each substantial proof
    family remains behind its own independently kernel-checkable boundary. *)
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageLawValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceReification.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceEmbedding.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceProvability.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSourceSubstitution.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSource.
