(** Strict audit surface for the three-field child-only post-And-I boundary. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyRemainderIntegration.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyRemainderIntegrationAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyRemainderIntegration.

Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsAfterAndIntroductionThreeFieldChildOnlyRemainder.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionThreeFieldChildOnlyAtWitnesses.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionThreeFieldChildOnlyStandardTailCompiler.

Check
  raw_fiveFieldChildOnlyRemainder_of_andEliminationTruthRoots_and_threeFieldRemainder.
Check
  raw_fiveFieldChildOnlyRemainderAtWitnesses_of_andEliminationTruthRoots_and_threeFieldRemainder.
Check
  raw_remainingAfterAndIntroductionFiveFieldChildOnlyStandardTailCompiler_of_andEliminationTruthRoots_and_threeFieldRemainder.
Check
  raw_remainingAfterAndIntroductionFiveFieldChildOnlyStandardTailCompiler_of_aligned_andElimination_rows_and_threeFieldRemainder.

Print Assumptions
  raw_fiveFieldChildOnlyRemainder_of_andEliminationTruthRoots_and_threeFieldRemainder.
Print Assumptions
  raw_fiveFieldChildOnlyRemainderAtWitnesses_of_andEliminationTruthRoots_and_threeFieldRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionFiveFieldChildOnlyStandardTailCompiler_of_andEliminationTruthRoots_and_threeFieldRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionFiveFieldChildOnlyStandardTailCompiler_of_aligned_andElimination_rows_and_threeFieldRemainder.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionThreeFieldChildOnlyRemainderIntegrationAudit.
