(** Kernel-facing audit for binder-principal projection compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthBinderPrincipalProjectionCompilation.

Import PABoundedRawCodedDynamicTruthBinderPrincipalProjectionCompilation.

(** Shared transparent logical template. *)
Check binderPrincipalProjectionTemplateFormula.
Check binderPrincipalProjectionTemplateProof.
Check binderPrincipalProjectionTemplateProof_derives.
Check rawBinderPrincipalProjectionTemplateRoot.
Check raw_codedPALocalProofOf_binderPrincipalProjectionTemplate.

(** Lower-independent structural instances. *)
Check formulaAndRightOrBottom.
Check dynamicTruthSigmaFixedPrincipalRemainder.
Check dynamicTruthPiFixedPrincipalRemainder.
Check dynamicTruthSigmaFixedPrincipal_split.
Check dynamicTruthPiFixedPrincipal_split.
Check dynamicTruthSigmaFixedPrincipalProjectionTemplateFormula.
Check dynamicTruthPiFixedPrincipalProjectionTemplateFormula.
Check rawBinderProjectionZeroNumeralParameters.
Check rawBinderProjectionBottomStructuralInputs.
Check rawStructural_sigmaFixedPrincipalProjection_identified.
Check rawStructural_piFixedPrincipalProjection_identified.
Check raw_codedPALocalProofOf_sigmaFixedPrincipalProjection.
Check raw_codedPALocalProofOf_piFixedPrincipalProjection.

(** Native Sigma-All and Pi-Ex instances. *)
Check dynamicTruthSigmaAllPrincipalProjectionTemplateFormula.
Check dynamicTruthPiExPrincipalProjectionTemplateFormula.
Check rawBinderProjectionDirectTemplateFormula_embedPA.
Check rawSigmaAllPrincipalProjectionRoot.
Check rawPiExPrincipalProjectionRoot.
Check rawDirect_sigmaAllPrincipalProjection_identified.
Check rawDirect_piExPrincipalProjection_identified.
Check raw_codedPALocalProofOf_sigmaAllPrincipalProjection.
Check raw_codedPALocalProofOf_piExPrincipalProjection.

(** Exact common-context adapters and increasingly concrete resource
    boundaries. *)
Check
  raw_dynamicTruthBinderPrincipalProjectionInterface_of_lower_identification.
Check raw_dynamicTruthBinderPrincipalProjectionInterface_of_direct.
Check raw_dynamicTruthBinderPrincipalProjectionInterface_of_native_traces.
Check raw_dynamicTruthBinderPrincipalProjectionInterface_of_deepClosed.

Print Assumptions binderPrincipalProjectionTemplateProof_derives.
Print Assumptions raw_codedPALocalProofOf_binderPrincipalProjectionTemplate.
Print Assumptions rawStructural_sigmaFixedPrincipalProjection_identified.
Print Assumptions rawStructural_piFixedPrincipalProjection_identified.
Print Assumptions raw_codedPALocalProofOf_sigmaFixedPrincipalProjection.
Print Assumptions raw_codedPALocalProofOf_piFixedPrincipalProjection.
Print Assumptions rawDirect_sigmaAllPrincipalProjection_identified.
Print Assumptions rawDirect_piExPrincipalProjection_identified.
Print Assumptions raw_codedPALocalProofOf_sigmaAllPrincipalProjection.
Print Assumptions raw_codedPALocalProofOf_piExPrincipalProjection.
Print Assumptions
  raw_dynamicTruthBinderPrincipalProjectionInterface_of_lower_identification.
Print Assumptions raw_dynamicTruthBinderPrincipalProjectionInterface_of_direct.
Print Assumptions
  raw_dynamicTruthBinderPrincipalProjectionInterface_of_native_traces.
Print Assumptions
  raw_dynamicTruthBinderPrincipalProjectionInterface_of_deepClosed.
