(** Kernel-facing audit for carrier-parametric binder off-diagonal cells. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthBinderOffDiagonalExclusivity.

Import PABoundedRawCodedDynamicTruthBinderOffDiagonalExclusivity.

Check DynamicTruthBinderOffDiagonalCell.
Check DTBODSigmaAllPiImp.
Check DTBODSigmaAllPiAnd.
Check DTBODSigmaAllPiOr.
Check DTBODSigmaAllPiEx.
Check DTBODSigmaImpFalseLeftPiEx.
Check DTBODSigmaImpTrueRightPiEx.
Check DTBODSigmaAndPiEx.
Check DTBODSigmaOrPiEx.
Check dynamicTruthBinderOffDiagonalSigmaBranch.
Check dynamicTruthBinderOffDiagonalPiBranch.
Check dynamicTruthBinderOffDiagonalCells.
Check dynamicTruthBinderOffDiagonalCells_length.
Check dynamicTruthBinderOffDiagonalCells_complete.
Check dynamicTruthBinderOffDiagonal_branches_disjoint.
Check dynamicTruthBinderOffDiagonal_touches_binder.

Check rawDynamicTruthSigmaCarrierConstructorEx8BranchCode.
Check rawDynamicTruthPiCarrierConstructorEx8BranchCode.
Check rawDynamicTruthBinderOffDiagonalSigmaBranchCode.
Check rawDynamicTruthBinderOffDiagonalPiBranchCode.
Check rawDynamicTruthSigmaCarrierAllBranchCode_literal.
Check rawDynamicTruthPiCarrierExBranchCode_literal.
Check rawDynamicTruthSigmaCarrierConstructorEx8BranchCode_adequate.
Check rawDynamicTruthPiCarrierConstructorEx8BranchCode_adequate.
Check rawDynamicTruthBinderOffDiagonalSigmaBranchCode_adequate.
Check rawDynamicTruthBinderOffDiagonalPiBranchCode_adequate.

Check dynamicTruthSigmaPrincipalBody.
Check dynamicTruthPiPrincipalBody.
Check dynamicTruthSigmaPrincipalEx8Formula.
Check dynamicTruthPiPrincipalEx8Formula.
Check raw_sat_dynamicTruthSigmaPrincipalEx8Formula_principal.
Check raw_sat_dynamicTruthPiPrincipalEx8Formula_principal.
Check dynamicTruthBinderPrincipalCollisionFormula.
Check dynamicTruthBinderPrincipalCollisionFormula_raw_valid.
Check PA_proves_dynamicTruthBinderPrincipalCollisionFormula.
Check rawDynamicTruthBinderSigmaPrincipalCode.
Check rawDynamicTruthBinderPiPrincipalCode.
Check rawDynamicTruthBinderPrincipalCollisionCode.
Check rawDynamicTruthBinderPrincipalCollisionCode_eq_quoted.
Check raw_codedPAProofOf_dynamicTruthBinderPrincipalCollision.

Check RawDynamicTruthBinderPrincipalProjectionInterfaceAt.
Check RawDynamicTruthBinderPrincipalCollisionAvailableAt.
Check RawDynamicTruthBinderOffDiagonalProofInputsAt.
Check rawDynamicTruthBinderOffDiagonalPairCollisionCode.
Check raw_codedPALocalProofOf_dynamicTruthBinderOffDiagonalPairCollision.
Check raw_dynamicTruthBinderOffDiagonal_matrix_pair.
Check raw_dynamicTruthBinderOffDiagonal_singleton_pair_family.

Print Assumptions dynamicTruthBinderOffDiagonal_branches_disjoint.
Print Assumptions rawDynamicTruthSigmaCarrierConstructorEx8BranchCode_adequate.
Print Assumptions rawDynamicTruthPiCarrierConstructorEx8BranchCode_adequate.
Print Assumptions raw_sat_dynamicTruthSigmaPrincipalEx8Formula_principal.
Print Assumptions raw_sat_dynamicTruthPiPrincipalEx8Formula_principal.
Print Assumptions dynamicTruthBinderPrincipalCollisionFormula_raw_valid.
Print Assumptions PA_proves_dynamicTruthBinderPrincipalCollisionFormula.
Print Assumptions raw_codedPAProofOf_dynamicTruthBinderPrincipalCollision.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthBinderOffDiagonalPairCollision.
Print Assumptions raw_dynamicTruthBinderOffDiagonal_matrix_pair.
Print Assumptions raw_dynamicTruthBinderOffDiagonal_singleton_pair_family.
