From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeFinalTargetRefutationCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeFinalTargetRefutationCompilation.

Check RestrictedTargetFormulaContextDiagonalScoped.
Check raw_codedRestrictedTargetFormulaContext_diagonal_scoped.
Check raw_restrictedPAConsistencyClosedPrefix_singleSubstitution.
Check raw_codedPALocalProofOf_restrictedPAConsistency_closeN_eliminate.
Check raw_restrictedPAProofAssumption_candidateThree_substitution.
Check raw_restrictedPAConsistencyCandidateImplication_substitution.
Check rawDynamicTruthNativeFinalTargetRefutationRoot.
Check RawDynamicTruthNativeFinalTargetRefutationRootCompiler.
Check raw_dynamicTruthNativeFinalTargetRefutationRootCompiler.

Print Assumptions
  raw_codedRestrictedTargetFormulaContext_diagonal_scoped.
Print Assumptions
  raw_codedPALocalProofOf_restrictedPAConsistency_closeN_eliminate.
Print Assumptions
  raw_restrictedPAProofAssumption_candidateThree_substitution.
Print Assumptions
  raw_dynamicTruthNativeFinalTargetRefutationRootCompiler.
