From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessNativeAfterAssumptionCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessNativeAfterAssumptionCompilation.

Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeInputs_afterAssumption.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeTrace_afterAssumption.

Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeInputs_afterAssumption.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_nativeTrace_afterAssumption.
