From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessOrIntroductionLeftNativeLawTransport.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessOrIntroductionLeftNativeLawTransport.

Check rawCoqRestrictedPADirectOrIntroductionLeftNativeTruthLawCode.
Check raw_coqRestrictedPADirectOrIntroductionLeftNativeTruthLaw_code.
Check RawCoqRestrictedPADirectOrIntroductionLeftNativeTruthLawRoot.
Check raw_publicOrIntroductionLeftTruthLawRoot_of_native.
Check RawCoqRestrictedPADirectSelectedNativeOrIntroductionLeftTruthTail.
Check raw_selectedPublicOrIntroductionLeftTruthTail_of_native.
Check
  RawCoqRestrictedPADirectLinkedNativeOrIntroductionLeftTruthCompiler.
Check
  raw_selectedPublicOrIntroductionLeftTruthTail_of_nativeDirectTruthInputsWithClosureAt.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_linkedNativeOrIntroductionLeftTruth.

Print Assumptions
  raw_coqRestrictedPADirectOrIntroductionLeftNativeTruthLaw_code.
Print Assumptions raw_publicOrIntroductionLeftTruthLawRoot_of_native.
Print Assumptions raw_selectedPublicOrIntroductionLeftTruthTail_of_native.
Print Assumptions
  raw_selectedPublicOrIntroductionLeftTruthTail_of_nativeDirectTruthInputsWithClosureAt.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessUniversalDirect_of_linkedNativeOrIntroductionLeftTruth.
