(** Assumption audit for paired output-first graph composition. *)

From BoundedPAConsistency Require Import
  RawCodedOutputFirstPairedFormulaGraphComposition.

Import PABoundedRawCodedOutputFirstPairedFormulaGraphComposition.

Check outputFirstPairedFormulaGraphCompositionEnvironment.
Check outputFirstPairedFormulaGraphCompositionSourceRenaming.
Check outputFirstPairedFormulaGraphCompositionTransformRenaming.
Check raw_sat_outputFirstPairedFormulaGraphCompositionSourceRenamed_iff.
Check raw_sat_outputFirstPairedFormulaGraphCompositionTransformRenamed_iff.
Check outputFirstPairedFormulaGraphComposition.
Check RawOutputFirstPairedFormulaGraphCompositionAt.
Check raw_sat_outputFirstPairedFormulaGraphComposition_iff.
Check RawOutputFirstPairedFormulaSourceTotal.
Check RawOutputFirstPairedFormulaTransformProofTotal.
Check outputFirstPairedFormulaGraphComposition_raw_proof_total.

Print Assumptions
  raw_sat_outputFirstPairedFormulaGraphCompositionSourceRenamed_iff.
Print Assumptions
  raw_sat_outputFirstPairedFormulaGraphCompositionTransformRenamed_iff.
Print Assumptions raw_sat_outputFirstPairedFormulaGraphComposition_iff.
Print Assumptions
  outputFirstPairedFormulaGraphComposition_raw_proof_total.
