(** Assumption and exact-slot audit for direct disjunction elimination. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationCase.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationCaseAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationCase.

Check coqRestrictedPADirectOrEliminationCaseTemplate.
Check coqRestrictedPADirectOrElimination_case_shape.
Check coqRestrictedPADirectOrEliminationResultFormulaTerm.
Check coqRestrictedPADirectOrEliminationConclusionEqualityTemplate.
Check coqRestrictedPADirectOrEliminationFormulaCodeTemplate.
Check coqRestrictedPADirectOrEliminationDisjunctionEndpointTemplate.
Check coqRestrictedPADirectOrEliminationLeftEndpointTemplate.
Check coqRestrictedPADirectOrEliminationRightEndpointTemplate.

Check coqRestrictedPADirectOrEliminationDisjunctionChildLawTemplate.
Check coqRestrictedPADirectOrEliminationLeftChildLawTemplate.
Check coqRestrictedPADirectOrEliminationRightChildLawTemplate.
Check coqRestrictedPADirectOrEliminationDynamicTruthLawTemplate.
Check
  coqRestrictedPADirectOrElimination_conclusion_motive_result.
Check RawCoqRestrictedPADirectOrEliminationSemanticRoots.

Check coqRestrictedPADirectOrEliminationCodeEqualityRootAt_valid.
Check
  coqRestrictedPADirectOrEliminationConclusionEqualityRootAt_valid.
Check coqRestrictedPADirectOrEliminationFormulaCodeRootAt_valid.
Check
  coqRestrictedPADirectOrEliminationDisjunctionEndpointRootAt_valid.
Check coqRestrictedPADirectOrEliminationLeftEndpointRootAt_valid.
Check coqRestrictedPADirectOrEliminationRightEndpointRootAt_valid.
Check
  coqRestrictedPADirectOrEliminationConclusionTransportRootAt_valid.
Check
  raw_codedPALocalProofOf_coqRestrictedPADirectOrEliminationConclusion.
Check raw_coqRestrictedPADirectStrongStepOrEliminationCaseRoot.

Print Assumptions
  coqRestrictedPADirectOrEliminationConclusionTransportRootAt_valid.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectOrEliminationConclusion.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepOrEliminationCaseRoot.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationCaseAudit.
