From BoundedPAConsistency Require Import
  RawCodedRestrictedPATemplateTernaryApplicationCompilation.

Import
  PABoundedRawCodedRestrictedPATemplateTernaryApplicationCompilation.

Check coqRestrictedPATemplateTernaryFirstLifted.
Check coqRestrictedPATemplateTernarySecondLifted.
Check coqRestrictedPATemplateTernaryFirstResult.
Check coqRestrictedPATemplateTernarySecondResult.
Check coqRestrictedPATemplateTernaryApplication.
Check raw_coqRestrictedPATemplateTernary_first_shift.
Check raw_coqRestrictedPATemplateTernary_second_shift.
Check raw_coqRestrictedPATemplateTernaryApplication_trace.
Check raw_codedTemplateTernaryApplication_trace_of_protected_shifts.
Check raw_coqRestrictedPAExtendedTemplateTernaryApplication_trace.
Check raw_coqRestrictedPAExtendedTemplateTernaryApplication_output.
Check raw_coqRestrictedPATemplateTernaryApplication_output.

Print Assumptions raw_coqRestrictedPATemplateTernary_first_shift.
Print Assumptions raw_coqRestrictedPATemplateTernary_second_shift.
Print Assumptions raw_coqRestrictedPATemplateTernaryApplication_trace.
Print Assumptions
  raw_codedTemplateTernaryApplication_trace_of_protected_shifts.
Print Assumptions
  raw_coqRestrictedPAExtendedTemplateTernaryApplication_trace.
Print Assumptions
  raw_coqRestrictedPAExtendedTemplateTernaryApplication_output.
Print Assumptions raw_coqRestrictedPATemplateTernaryApplication_output.
