From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionWitnessShapes.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionWitnessShapes.

Check coqRestrictedPADirectAssumptionExpandedContextTruthTemplate.
Check coqRestrictedPADirectAssumptionExpandedContextBodyTemplate.
Check coqRestrictedPADirectAssumptionMembershipBodyTemplate.
Check coqRestrictedPADirectAssumptionExpandedContextTruth_shape.
Check coqRestrictedPADirectAssumptionMembership_shape.
Check coqRestrictedPADirectAssumptionShiftedContextTruthTemplate.
Check coqRestrictedPADirectAssumptionShiftedContextBodyTemplate.
Check coqRestrictedPADirectAssumptionShiftedContextTruth_shape.
Check coqRestrictedPADirectAssumptionFinalContextBodyTemplate.
Check coqRestrictedPADirectAssumptionFinalMembershipBodyTemplate.
Check coqRestrictedPADirectAssumptionFinalPointwiseTemplate.
Check coqRestrictedPADirectAssumptionFinalRightMembershipTemplate.
Check coqRestrictedPADirectAssumptionFinalContextBody_shape.
Check coqRestrictedPADirectAssumptionFinalMembershipBody_shape.
Check coqRestrictedPADirectAssumptionFinalRightMembership_shape.
Check coqRestrictedPADirectAssumptionFinalLeftMembershipTemplate.
Check coqRestrictedPADirectAssumptionFinalMembershipIndexBodyTemplate.
Check coqRestrictedPADirectAssumptionFinalLiveIndexTemplate.
Check coqRestrictedPADirectAssumptionFinalHeadLookupTemplate.
Check coqRestrictedPADirectAssumptionFinalLeftMembership_shape.
Check coqRestrictedPADirectAssumptionNativeWitnessFormulaTruthTemplate.
Check coqRestrictedPADirectAssumptionFinalPointwiseAfterIndexTemplate.
Check coqRestrictedPADirectAssumptionFinalPointwiseAfterLiveTemplate.
Check coqRestrictedPADirectAssumptionFinalPointwiseAfterFormulaTemplate.
Check coqRestrictedPADirectAssumptionFinalPointwiseTruthTemplate.
Check coqRestrictedPADirectAssumptionFinalPointwiseAfterIndex_shape.
Check coqRestrictedPADirectAssumptionFinalPointwiseAfterLive_shape.
Check coqRestrictedPADirectAssumptionFinalPointwiseAfterFormula_shape.
Check coqRestrictedPADirectAssumptionFinalPointwiseTruth_shape.

Print Assumptions
  coqRestrictedPADirectAssumptionExpandedContextTruth_shape.
Print Assumptions coqRestrictedPADirectAssumptionMembership_shape.
Print Assumptions coqRestrictedPADirectAssumptionShiftedContextTruth_shape.
Print Assumptions coqRestrictedPADirectAssumptionFinalContextBody_shape.
Print Assumptions coqRestrictedPADirectAssumptionFinalMembershipBody_shape.
Print Assumptions coqRestrictedPADirectAssumptionFinalRightMembership_shape.
Print Assumptions coqRestrictedPADirectAssumptionFinalLeftMembership_shape.
Print Assumptions
  coqRestrictedPADirectAssumptionFinalPointwiseAfterIndex_shape.
Print Assumptions
  coqRestrictedPADirectAssumptionFinalPointwiseAfterLive_shape.
Print Assumptions
  coqRestrictedPADirectAssumptionFinalPointwiseAfterFormula_shape.
Print Assumptions
  coqRestrictedPADirectAssumptionFinalPointwiseTruth_shape.
