(** Assumption audit for the simultaneous four-table PA append source. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendSource.

Import PABoundedRawCodedFourStateTableAppendSource.

Check codedFourStateTableAppendFormula.
Check codedAssignmentAppendAtTermAt.
Check RawCodedAssignmentAppendAt.
Check raw_sat_codedAssignmentAppendAtTermAt_iff.
Check RawFourStateTableAppendProperty.
Check raw_sat_codedFourStateTableAppendFormula_iff.
Check codedFourStateTableAppendFormula_sentence.
Check codedFourStateTableAppendFormula_raw_valid.
Check PA_proves_codedFourStateTableAppendFormula.

Print Assumptions raw_sat_codedFourStateTableAppendFormula_iff.
Print Assumptions raw_sat_codedAssignmentAppendAtTermAt_iff.
Print Assumptions codedFourStateTableAppendFormula_sentence.
Print Assumptions codedFourStateTableAppendFormula_raw_valid.
Print Assumptions PA_proves_codedFourStateTableAppendFormula.
