(** Audit surface for the child-only seven-field post-And-I remainder. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlyRemainderIntegration.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlyRemainderIntegrationAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlyRemainderIntegration.

Check
  RawCoqRestrictedPADirectExistentialIntroductionChildInterfaceLawRoot.
Check RawCoqRestrictedPADirectEqualityEliminationChildInterfaceRoots.
Check
  raw_existentialIntroductionSemanticRoots_of_childInterface_and_dynamicTruth.
Check
  raw_equalityEliminationSemanticRoots_of_childInterfaces_and_dynamicTruth.

Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsAfterAndIntroductionSevenFieldChildOnlyRemainder.
Check
  rawCoqRestrictedPADirectAfterAndISevenChildOnly_andEliminationLeftTruth.
Check
  rawCoqRestrictedPADirectAfterAndISevenChildOnly_andEliminationRightTruth.
Check rawCoqRestrictedPADirectAfterAndISevenChildOnly_orElimination.
Check
  rawCoqRestrictedPADirectAfterAndISevenChildOnly_universalEliminationRecursive.
Check
  rawCoqRestrictedPADirectAfterAndISevenChildOnly_existentialIntroductionChild.
Check
  rawCoqRestrictedPADirectAfterAndISevenChildOnly_existentialElimination.
Check
  rawCoqRestrictedPADirectAfterAndISevenChildOnly_equalityEliminationChildren.

Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionSevenFieldAtWitnesses.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionSevenFieldChildOnlyAtWitnesses.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionSevenFieldChildOnlyStandardTailCompiler.
Check
  raw_sevenFieldRemainder_of_existentialIntroductionEqualityEliminationKOnly_and_childOnlyRemainder.
Check
  raw_sevenFieldRemainderAtWitnesses_of_existentialIntroductionEqualityEliminationKOnly_and_childOnlyRemainder.
Check
  raw_remainingAfterAndIntroductionSevenFieldStandardTailCompiler_of_existentialIntroductionEqualityEliminationKOnly_and_childOnlyRemainder.
Check
  raw_remainingAfterAndIntroductionSevenFieldStandardTailCompiler_of_aligned_existentialIntroduction_equalityElimination_rows_and_childOnlyRemainder.
Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_six_rows_interfaces_and_sevenFieldChildOnlyRemainder.

Print Assumptions
  raw_existentialIntroductionSemanticRoots_of_childInterface_and_dynamicTruth.
Print Assumptions
  raw_equalityEliminationSemanticRoots_of_childInterfaces_and_dynamicTruth.
Print Assumptions
  raw_sevenFieldRemainder_of_existentialIntroductionEqualityEliminationKOnly_and_childOnlyRemainder.
Print Assumptions
  raw_sevenFieldRemainderAtWitnesses_of_existentialIntroductionEqualityEliminationKOnly_and_childOnlyRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionSevenFieldStandardTailCompiler_of_existentialIntroductionEqualityEliminationKOnly_and_childOnlyRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionSevenFieldStandardTailCompiler_of_aligned_existentialIntroduction_equalityElimination_rows_and_childOnlyRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_six_rows_interfaces_and_sevenFieldChildOnlyRemainder.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldChildOnlyRemainderIntegrationAudit.
