From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectBottomAdmissibilityAwareCompletion.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectBottomAdmissibilityAwareCompletion.

Check coqRestrictedPADirectBottomAdmissibilityAwareCompletionTemplate.
Check coqRestrictedPADirectBottomAdmissibilityAwareCompletionRoot_valid.
Check RawCoqRestrictedPADirectBottomCurrentSourceIdentification.
Check
  RawCoqRestrictedPADirectBottomAdmissibilityAwareRemainingStandardTailCompiler.
Check
  RawCoqRestrictedPADirectBottomAdmissibilityAwareCaseStandardTailCompiler.
Check
  raw_bottomAdmissibilityAwareRemaining_standardTail_of_current_source_identification.
Check
  raw_bottomAdmissibilityAwareCase_standardTail_of_current_source_identification.
Check raw_bottomCurrentSourceIdentification_of_aligned_structural_inputs.
Check raw_bottomAdmissibilityAwareRemaining_standardTail_of_aligned.
Check raw_bottomAdmissibilityAwareCase_standardTail_of_aligned.
Check
  raw_coqRestrictedPADirectStrongStepBottomAdmissibilityAwareCaseRoot_standardTail.

Print Assumptions
  coqRestrictedPADirectBottomAdmissibilityAwareCompletionRoot_valid.
Print Assumptions
  raw_bottomAdmissibilityAwareRemaining_standardTail_of_current_source_identification.
Print Assumptions
  raw_bottomAdmissibilityAwareCase_standardTail_of_current_source_identification.
Print Assumptions
  raw_bottomCurrentSourceIdentification_of_aligned_structural_inputs.
Print Assumptions raw_bottomAdmissibilityAwareRemaining_standardTail_of_aligned.
Print Assumptions raw_bottomAdmissibilityAwareCase_standardTail_of_aligned.
Print Assumptions
  raw_coqRestrictedPADirectStrongStepBottomAdmissibilityAwareCaseRoot_standardTail.
