(** Kernel audit for the restricted universal-row output-first transform. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthUniversalLeafTransformGraph.

Module PABoundedRawCodedDynamicTruthUniversalLeafTransformGraphAudit.

Import PABoundedRawCodedDynamicTruthUniversalLeafTransformGraph.

Check restrictedUniversalFormulaAllCodeTerm.
Check restrictedUniversalRepeatedAllCodeTerm.
Check dynamicTruthSigmaRestrictedUniversalProjectionCodeTerm.
Check dynamicTruthSigmaRestrictedUniversalFieldCodeTerm.
Check rawDynamicTruthSigmaRestrictedUniversalProjectionGraphCode.
Check rawDynamicTruthSigmaRestrictedUniversalFieldGraphCode.
Check raw_eval_dynamicTruthSigmaRestrictedUniversalFieldCodeTerm.
Check raw_sat_dynamicTruthSigmaRestrictedUniversalFieldCodeTermAt_iff.
Check rawDynamicTruthSigmaUniversalCode_eq_directTemplateCode.
Check rawDynamicTruthSigmaRestrictedUniversalFieldGraphCode_eq_compiled.

Check dynamicTruthSigmaRestrictedUniversalFieldTransformGraph.
Check RawDynamicTruthSigmaRestrictedUniversalFieldTransformAt.
Check raw_sat_dynamicTruthSigmaRestrictedUniversalFieldTransformGraph_iff.
Check RawDynamicTruthSigmaRestrictedUniversalFieldTransformTotal.
Check dynamicTruthSigmaRestrictedUniversalFieldTransformGraph_raw_total.

Check RawDynamicTruthSigmaRestrictedUniversalDirectCompilerTotal.
Check
  dynamicTruthSigmaRestrictedUniversalFieldTransformGraph_raw_proof_total.

Print Assumptions
  raw_sat_dynamicTruthSigmaRestrictedUniversalFieldCodeTermAt_iff.
Print Assumptions
  rawDynamicTruthSigmaRestrictedUniversalFieldGraphCode_eq_compiled.
Print Assumptions
  raw_sat_dynamicTruthSigmaRestrictedUniversalFieldTransformGraph_iff.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalFieldTransformGraph_raw_total.
Print Assumptions
  dynamicTruthSigmaRestrictedUniversalFieldTransformGraph_raw_proof_total.

End PABoundedRawCodedDynamicTruthUniversalLeafTransformGraphAudit.
