(** Kernel audit for the table-based universal-leaf source template. *)

From Stdlib Require Import List.
From BoundedPAConsistency Require Import
  RawCodedTemplateSyntax
  RawCodedDynamicTruthUniversalLeafSourceTemplate.

Import ListNotations.

Module PABoundedRawCodedDynamicTruthUniversalLeafSourceTemplateAudit.

Import PABoundedRawCodedTemplateSyntax.
Import PABoundedRawCodedDynamicTruthUniversalLeafSourceTemplate.

Check coqDynamicTruthLowerLevelParameterName.
Check coqDynamicTruthUpperLevelParameterName.
Check coqDynamicTruthLowerPiPredicateName.
Check coqDynamicTruthLowerPiAtomTemplate.
Check coqDynamicTruthLowerPiAtomTemplateAt.
Check coqDynamicTruthSigmaDomainLeafTemplate.
Check coqDynamicTruthSigmaQfLeafTemplate.
Check coqDynamicTruthSigmaImpFalseLeftLeafTemplate.
Check coqDynamicTruthSigmaImpTrueRightLeafTemplate.
Check coqDynamicTruthSigmaAndLeafTemplate.
Check coqDynamicTruthSigmaOrLeafTemplate.
Check coqDynamicTruthSigmaExLeafTemplate.
Check coqDynamicTruthSigmaUniversalLeafTemplate.
Check coqDynamicTruthSigmaRowTemplateLeaves.
Check coqDynamicTruthSigmaBranchesTemplate.
Check coqDynamicTruthSigmaSuccessorRowTemplate.
Check coqDynamicTruthSigmaNoBinderCounterexampleTemplateAt.
Check coqDynamicTruthSigmaUniversalLeafTemplateAt.
Check coqDynamicTruthSigmaBranchesTemplateAt.
Check coqDynamicTruthSigmaSuccessorRowTemplateAt.
Check coqDynamicTruthSigmaSuccessorRowTemplateAt_default.

Check rawStructuralTemplateTerm_embedPA.
Check rawStructuralTemplateFormula_embedPA.
Check rawStructural_coqDynamicTruthLowerPiAtomTemplate.
Check rawStructural_coqDynamicTruthSigmaUniversalLeafTemplate.
Check rawStructural_coqDynamicTruthSigmaBranchesTemplate.
Check rawStructural_coqDynamicTruthSigmaSuccessorRowTemplate.
Check rawCoqDynamicTruthLowerPiAtomTemplateCodeAt.
Check rawCoqDynamicTruthLowerPiAtomTemplateCodeAt_default.
Check rawStructural_coqDynamicTruthLowerPiAtomTemplateAt.
Check rawStructural_coqDynamicTruthSigmaBranchesTemplateAt.
Check rawStructural_coqDynamicTruthSigmaSuccessorRowTemplateAt.
Check RawCoqDynamicTruthSigmaTemplateIdentification.
Check rawStructural_coqDynamicTruthSigmaSuccessorRowTemplate_identified.

Check coqDynamicTruthSigmaRestrictedUniversalProjectionFormula.
Check coqDynamicTruthSigmaRestrictedUniversalProjectionProof.
Check coqDynamicTruthSigmaRestrictedUniversalProjectionProof_derives.
Check rawStructural_coqDynamicTruthSigmaRestrictedProjection_identified.
Check coqDynamicTruthSigmaClosedRestrictedProjectionProof_derives.

Check coqDynamicTruthSigmaEightLeafConjunctionCandidate.
Check coqDynamicTruthSigma_conjunction_body_not_actual_row_body.
Check coqDynamicTruthSigma_five_witness_source_not_table_row.
Check coqDynamicTruthSigma_generic_candidate_not_successor_row.

Print Assumptions rawStructuralTemplateFormula_embedPA.
Print Assumptions rawStructural_coqDynamicTruthSigmaUniversalLeafTemplate.
Print Assumptions rawStructural_coqDynamicTruthSigmaSuccessorRowTemplate.
Print Assumptions
  rawStructural_coqDynamicTruthSigmaSuccessorRowTemplateAt.
Print Assumptions coqDynamicTruthSigmaSuccessorRowTemplateAt_default.
Print Assumptions
  rawStructural_coqDynamicTruthSigmaSuccessorRowTemplate_identified.
Print Assumptions
  coqDynamicTruthSigmaRestrictedUniversalProjectionProof_derives.
Print Assumptions
  rawStructural_coqDynamicTruthSigmaRestrictedProjection_identified.
Print Assumptions
  coqDynamicTruthSigmaClosedRestrictedProjectionProof_derives.
Print Assumptions
  coqDynamicTruthSigma_conjunction_body_not_actual_row_body.
Print Assumptions
  coqDynamicTruthSigma_five_witness_source_not_table_row.
Print Assumptions
  coqDynamicTruthSigma_generic_candidate_not_successor_row.

End PABoundedRawCodedDynamicTruthUniversalLeafSourceTemplateAudit.
