From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPredecessorDirectEvidenceLogicalRoots.

Import
  PABoundedRawCodedDynamicTruthPredecessorDirectEvidenceLogicalRoots.

Check
  raw_dynamicTruthPredecessorStateLogicalRootsAt_of_direct_evidence_under_prefix_atomic_and_domain.
Check
  raw_dynamicTruthImpPredecessorStateExclusivityRoot_of_instantiated_evidence_under_template_prefix.
Check
  raw_dynamicTruthPredecessorEvidenceDecision_of_projected_decision_under_prefix_atomic_and_domain.
Check
  raw_dynamicTruthPredecessorStateLogicalRootsAt_of_direct_evidence_atomic_and_domain.
Check
  raw_dynamicTruthPredecessorStateLogicalRootsAt_of_direct_global_roots_on_witnessed_extension_atomic_and_domain.

Print Assumptions
  raw_dynamicTruthPredecessorStateLogicalRootsAt_of_direct_evidence_under_prefix_atomic_and_domain.
Print Assumptions
  raw_dynamicTruthImpPredecessorStateExclusivityRoot_of_instantiated_evidence_under_template_prefix.
Print Assumptions
  raw_dynamicTruthPredecessorEvidenceDecision_of_projected_decision_under_prefix_atomic_and_domain.
Print Assumptions
  raw_dynamicTruthPredecessorStateLogicalRootsAt_of_direct_evidence_atomic_and_domain.
Print Assumptions
  raw_dynamicTruthPredecessorStateLogicalRootsAt_of_direct_global_roots_on_witnessed_extension_atomic_and_domain.
