(** Kernel-facing audit for the direct consistency open integration. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyFromUniversalSoundnessDirectOpenIntegration.

Module
  PABoundedRawCodedRestrictedPAConsistencyFromUniversalSoundnessDirectOpenIntegrationAudit.

Import
  PABoundedRawCodedRestrictedPAConsistencyFromUniversalSoundnessDirectOpenIntegration.

Check coqRestrictedPAOpenShell_soundness_open_many.
Check coqRestrictedPAOpenShell_context_truth_open_many.
Check coqRestrictedPAOpenShell_universal_shift_identity.
Check coqRestrictedPAOpenShell_restricted_proof_shape.
Check coqRestrictedPAOpenShell_endpoint_field_shape.

Check raw_coqRestrictedPAOpenShell_restricted_proof_code.
Check raw_coqRestrictedPAOpenShell_endpoint_code.
Check raw_coqRestrictedPAOpenShell_witnessed_context_code.
Check RawCoqRestrictedPAOpenShellArithmeticResidual.
Check raw_coqRestrictedPAConsistencyBridgeContext_realizable.
Check raw_coqRestrictedPAOpenShell_projected_roots.
Check raw_coqRestrictedPAOpenShell_prepend_universal.
Check raw_coqRestrictedPAOpenShell_roots_of_support_and_arithmetic.
Check raw_coqRestrictedPAOpenShell_bottom_same_context.
Check
  raw_coqRestrictedPAConsistencyFromUniversalSoundnessDirect_child_of_arithmetic.
Check
  RawCoqRestrictedPAConsistencyFromUniversalSoundnessDirectArithmeticCompiler.
Check
  raw_coqRestrictedPAConsistencyFromUniversalSoundnessDirectOpenCompiler_of_arithmetic.

Print Assumptions raw_coqRestrictedPAOpenShell_restricted_proof_code.
Print Assumptions raw_coqRestrictedPAOpenShell_projected_roots.
Print Assumptions raw_coqRestrictedPAOpenShell_bottom_same_context.
Print Assumptions
  raw_coqRestrictedPAConsistencyFromUniversalSoundnessDirect_child_of_arithmetic.
Print Assumptions
  raw_coqRestrictedPAConsistencyFromUniversalSoundnessDirectOpenCompiler_of_arithmetic.

End
  PABoundedRawCodedRestrictedPAConsistencyFromUniversalSoundnessDirectOpenIntegrationAudit.
