(** Audit of the dependency bundle with the final three roots exposed. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedUniversalSoundnessBoundary.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedUniversalSoundnessBoundary.

Check
  RawDynamicTruthNativeDependencyOrderedUniversalSoundnessKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedKernelCompilers_of_universal_soundness.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_universal_soundness.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_universal_soundness.

Check
  RawDynamicTruthNativeDependencyOrderedUniversalSoundnessKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedKernelCompilersInAllModels_of_universal_soundness.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_universal_soundness.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedKernelCompilers_of_universal_soundness.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_universal_soundness.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_universal_soundness.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_universal_soundness.
