(** Assumption audit for the synchronized-row pointwise proof. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsPointwise.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectSynchronizedRowsPointwise.

Check coqRestrictedPANativeAxiomRowsPointwiseDeepContext.
Check coqRestrictedPANativeAxiomRowsPointwise_shape.
Check coqRestrictedPANativeAxiomRowsPointwiseAxiomMembershipRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseAdequateMembershipRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseBoundedMembershipRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseAtomicRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseDomainRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseWitnessLookupExistsRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseRecognitionRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseDefinedRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseLeafRoot_derives.
Check coqRestrictedPANativeAxiomRowsPointwiseRoot_derives.

Print Assumptions coqRestrictedPANativeAxiomRowsPointwise_shape.
Print Assumptions
  coqRestrictedPANativeAxiomRowsPointwiseAxiomMembershipRoot_derives.
Print Assumptions
  coqRestrictedPANativeAxiomRowsPointwiseAdequateMembershipRoot_derives.
Print Assumptions
  coqRestrictedPANativeAxiomRowsPointwiseBoundedMembershipRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsPointwiseAtomicRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsPointwiseDomainRoot_derives.
Print Assumptions
  coqRestrictedPANativeAxiomRowsPointwiseWitnessLookupExistsRoot_derives.
Print Assumptions
  coqRestrictedPANativeAxiomRowsPointwiseRecognitionRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsPointwiseDefinedRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsPointwiseLeafRoot_derives.
Print Assumptions coqRestrictedPANativeAxiomRowsPointwiseRoot_derives.
