(** Assumption audit for successor-bound splitting in an appended row. *)

From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendRowLtSuccCases.

Import PABoundedRawCodedFourStateTableAppendRowLtSuccCases.

Check raw_codedPALocalProofOf_templateEqTransport_reverse_head.
Check raw_codedPALocalProofOf_templateEqTransport_reverse_head_parameter.
Check coqFourStateTableAppendEqualityTransportedNewStateLookupTemplate.
Check coqFourStateTableAppendEqualityModeFunctionalityArguments.
Check coqFourStateTableAppendEqualityFormulaFunctionalityArguments.
Check coqFourStateTableAppendEqualityAssignmentCodeFunctionalityArguments.
Check coqFourStateTableAppendEqualityAssignmentStepFunctionalityArguments.
Check coqFourStateTableAppendEqualityRowLookupTemplate.
Check coqFourStateTableAppendEqualityRowLookupTemplate_matches_second.
Check coqFourStateTableAppendModeLookupTemplate_beta_first.
Check coqFourStateTableAppendFormulaLookupTemplate_beta_first.
Check coqFourStateTableAppendAssignmentCodeLookupTemplate_beta_first.
Check coqFourStateTableAppendAssignmentStepLookupTemplate_beta_first.
Check coqBetaLookupFunctionalityFirstLookup_shift5_abstract_open.
Check
  coqFourStateTableAppendEqualityTransportedNewStateLookupTemplate_matches_first.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_branch_lookup_parameter.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_lookup_functionality_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_four_equalities_on_witnessed_tail_under_prefix.
Check coqFourStateTableAppendEqualityFieldBindings.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_growing_tail_under_prefix.
Check raw_templateContextCode_embedPAAxiomWitnesses.
Check raw_fourStateTableAppendRowContext_witnessed_tail_code.
Check raw_fourStateTableAppendRow_combined_witnessed_tail.
Check raw_fourStateTableAppendRowContext_combined_tail_code.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases_eliminate.
Check
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_branch_lookup.

Print Assumptions raw_codedPALocalProofOf_templateEqTransport_reverse_head.
Print Assumptions
  raw_codedPALocalProofOf_templateEqTransport_reverse_head_parameter.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_branch_lookup_parameter.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_lookup_functionality_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_four_equalities_on_witnessed_tail_under_prefix.
Print Assumptions coqFourStateTableAppendEqualityFieldBindings.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_equality_transport_result_growing_tail_under_prefix.
Print Assumptions
  coqFourStateTableAppendEqualityRowLookupTemplate_matches_second.
Print Assumptions coqFourStateTableAppendModeLookupTemplate_beta_first.
Print Assumptions coqFourStateTableAppendFormulaLookupTemplate_beta_first.
Print Assumptions
  coqFourStateTableAppendAssignmentCodeLookupTemplate_beta_first.
Print Assumptions
  coqFourStateTableAppendAssignmentStepLookupTemplate_beta_first.
Print Assumptions
  coqBetaLookupFunctionalityFirstLookup_shift5_abstract_open.
Print Assumptions
  coqFourStateTableAppendEqualityTransportedNewStateLookupTemplate_matches_first.
Print Assumptions raw_templateContextCode_embedPAAxiomWitnesses.
Print Assumptions raw_fourStateTableAppendRowContext_witnessed_tail_code.
Print Assumptions raw_fourStateTableAppendRow_combined_witnessed_tail.
Print Assumptions raw_fourStateTableAppendRowContext_combined_tail_code.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_lt_succ_cases_eliminate.
Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_row_predecessor_branch_lookup.
