(** Kernel-facing audit for the positive assumption-retaining append cut. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativePositiveAssumptionRetainingPermutedAppendCompilation.

Import
  PABoundedRawCodedDynamicTruthNativePositiveAssumptionRetainingPermutedAppendCompilation.

Check
  RawDynamicTruthNativeAlignedStrongStepPermutedAppendInputResourcesCompilerWithPA.
Check
  raw_dynamicTruthNativeAlignedStrongStepPermutedAppendInputResourcesCompilerWithPA_of_proof_resources.
Check
  RawDynamicTruthNativeLocalAlignedGrowingLogicalRootsCompilerUnderCallerPrefixOnWitnessedBaseWithDirectInputs.
Check
  raw_dynamicTruthNativeLocalAlignedGrowingLogicalRootsCompilerUnderCallerPrefixOnWitnessedBaseWithDirectInputs_of_permuted_append_input_resources.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroPositivePermutedAppendInputResourceStrongStepKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroPositivePermutedAppendInputResourceStrongStepKernelCompilers_of_proof_resources.
Check
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingPositiveLogicalRootsUnderCallerPrefix_of_permuted_append_input_resources.
Check
  RawDynamicTruthNativeAlignedLogicalRootsToGuardedCollisionContinuationUnderCallerPrefix.
Check
  raw_dynamicTruthNativeLocalAlignedGrowingGuardedCollisionRootsCompilerUnderCallerPrefixOnWitnessedBase_of_positive_permuted_append_inputs_and_logical_continuation.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingPositivePermutedAppendInputResourceSplitGrowingKernelCompilers.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_positive_permuted_append_inputs.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroPositivePermutedAppendInputResourceStrongStepKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroPositivePermutedAppendInputResourceStrongStepKernelCompilersInAllModels_of_proof_resources.
Check
  RawDynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingPositivePermutedAppendInputResourceSplitGrowingKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels_of_positive_permuted_append_inputs.

Print Assumptions
  raw_dynamicTruthNativeAlignedStrongStepPermutedAppendInputResourcesCompilerWithPA_of_proof_resources.
Print Assumptions
  raw_dynamicTruthNativeLocalAlignedGrowingLogicalRootsCompilerUnderCallerPrefixOnWitnessedBaseWithDirectInputs_of_permuted_append_input_resources.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroPositivePermutedAppendInputResourceStrongStepKernelCompilers_of_proof_resources.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedAssumptionRetainingPositiveLogicalRootsUnderCallerPrefix_of_permuted_append_input_resources.
Print Assumptions
  raw_dynamicTruthNativeLocalAlignedGrowingGuardedCollisionRootsCompilerUnderCallerPrefixOnWitnessedBase_of_positive_permuted_append_inputs_and_logical_continuation.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilers_of_positive_permuted_append_inputs.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedCanonicalAssumptionRetainingLogicalZeroPositivePermutedAppendInputResourceStrongStepKernelCompilersInAllModels_of_proof_resources.
Print Assumptions
  raw_dynamicTruthNativeGuardedDependencyOrderedAssumptionRetainingNormalizedCollisionResourceSplitGrowingKernelCompilersInAllModels_of_positive_permuted_append_inputs.
