(** PA embedding and parameter-opening laws for the fixed source body. *)

From PAHF Require Import PAHF.
From BoundedPAConsistency Require Import
  RawCodedTemplateSyntax
  RawCodedTemplateParameterAbstraction
  RawCodedRestrictedPAConsistencyFromUniversalSoundness
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageValidity
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceDefinitions
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceReification.

Module PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceEmbedding.

Import PABoundedRawCodedTemplateSyntax.
Import PABoundedRawCodedTemplateParameterAbstraction.
Import PABoundedRawCodedRestrictedPAConsistencyFromUniversalSoundness.
Import PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageValidity.
Import PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceDefinitions.
Import PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceReification.

Theorem coqRestrictedPADirectAndIntroductionOpenedCoverageSource_embed :
  embedPAFormula
    coqRestrictedPADirectAndIntroductionOpenedCoverageSourceBodyFormula =
  coqRestrictedPADirectAndIntroductionOpenedCoverageSourceBodyTemplate.
Proof.
  apply templateFormulaAsPAFormula_sound.
  exact coqRestrictedPADirectAndIntroductionOpenedCoverageSource_reifies.
Qed.

Theorem coqRestrictedPADirectAndIntroductionOpenedCoverageSource_open :
  templateFormulaOpen coqRestrictedPASoundnessLowerLevelTerm
    (embedPAFormula
      coqRestrictedPADirectAndIntroductionOpenedCoverageSourceBodyFormula) =
  coqRestrictedPADirectAndIntroductionOpenedCoverageCompilerLawTemplate.
Proof.
  rewrite coqRestrictedPADirectAndIntroductionOpenedCoverageSource_embed.
  apply templateFormulaAbstractParameter_open.
Qed.

End PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageSourceEmbedding.
