(** Assumption audit for represented canonical-application proof transport. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroCanonicalApplicationProofTransport.

Import
  PABoundedRawCodedDynamicTruthNativeZeroCanonicalApplicationProofTransport.

Check rawQuotedFormulaCode_imp.
Check raw_codedPALocalProofOf_target_of_PA_implication_under_prefix.
Check raw_codedPALocalProofOf_pair_of_PA_implications_under_prefix.
Check
  raw_dynamicTruthZeroNativeEvidenceRoots_of_canonicalApplicationRoots_under_prefix.
Check
  raw_dynamicTruthZeroCanonicalApplicationRoots_of_nativeEvidenceRoots_under_prefix.
Check
  raw_dynamicTruthZeroCanonicalApplicationDecision_of_nativeEvidenceDecision_under_prefix.
Check raw_dynamicTruthZeroNativeEvidenceRoots_of_canonicalApplicationRoots.
Check raw_dynamicTruthZeroCanonicalApplicationRoots_of_nativeEvidenceRoots.

Print Assumptions rawQuotedFormulaCode_imp.
Print Assumptions
  raw_codedPALocalProofOf_target_of_PA_implication_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_pair_of_PA_implications_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroNativeEvidenceRoots_of_canonicalApplicationRoots_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationRoots_of_nativeEvidenceRoots_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationDecision_of_nativeEvidenceDecision_under_prefix.
Print Assumptions
  raw_dynamicTruthZeroNativeEvidenceRoots_of_canonicalApplicationRoots.
Print Assumptions
  raw_dynamicTruthZeroCanonicalApplicationRoots_of_nativeEvidenceRoots.
