(** Compatibility umbrella for the physically split opened Eq-E source. *)

From BoundedPAConsistency Require Export
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageDefinitions
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceTemplateValidity
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceReification
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceEmbedding
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceProvability
  RawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceSubstitution.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSource.

(** Preserve the unqualified API while each substantial proof family remains
    behind an independently kernel-checkable compilation boundary. *)
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageDefinitions.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceTemplateValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceReification.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceEmbedding.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceProvability.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSourceSubstitution.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectEqualityEliminationOpenedCoverageSource.
