(** Audit surface for context-safe native successor-row projections. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalRowProjectionCompilation.

Import PABoundedRawCodedDynamicTruthNativeLocalRowProjectionCompilation.

Check raw_dynamicTruthNativeLocalSigma_orbit_interchange.
Check raw_dynamicTruthNativeLocalPi_orbit_interchange.
Check
  raw_dynamicTruthNativeLocalExactRows_branch_projection_inputs_on_witnessed_base.
Check rawDynamicTruthSigmaSuccessorRowDomainProjectionImpRoot.
Check rawDynamicTruthPiSuccessorRowDomainProjectionImpRoot.
Check
  raw_codedPALocalProofOf_dynamicTruthSigmaSuccessorRowDomainProjectionImp.
Check raw_codedPALocalProofOf_dynamicTruthPiSuccessorRowDomainProjectionImp.
Check
  raw_dynamicTruthNativeLocalExactRows_lower_direct_traces_on_witnessed_base.
Check
  raw_dynamicTruthNativeLocalExactRows_binder_projections_on_witnessed_base.
Check RawDynamicTruthNativeLocalProjectedRowRootsAt.
Check raw_dynamicTruthNativeLocalProjectedRowRootsAt_of_exact_rows.
Check raw_dynamicTruthLocalPairFamily_adequateCons.
Check RawDynamicTruthNativeLocalReducedCurrentKernelInputsAt.
Check RawDynamicTruthNativeLocalReducedStagedRootsAt.
Check
  raw_dynamicTruthNativeLocalFieldRootOn_of_reduced_staged_roots_and_40_helpers.

Print Assumptions raw_dynamicTruthNativeLocalSigma_orbit_interchange.
Print Assumptions raw_dynamicTruthNativeLocalPi_orbit_interchange.
Print Assumptions
  raw_dynamicTruthNativeLocalExactRows_branch_projection_inputs_on_witnessed_base.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthSigmaSuccessorRowDomainProjectionImp.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthPiSuccessorRowDomainProjectionImp.
Print Assumptions
  raw_dynamicTruthNativeLocalExactRows_lower_direct_traces_on_witnessed_base.
Print Assumptions
  raw_dynamicTruthNativeLocalExactRows_binder_projections_on_witnessed_base.
Print Assumptions
  raw_dynamicTruthNativeLocalProjectedRowRootsAt_of_exact_rows.
Print Assumptions raw_dynamicTruthLocalPairFamily_adequateCons.
Print Assumptions
  raw_dynamicTruthNativeLocalFieldRootOn_of_reduced_staged_roots_and_40_helpers.
