(** Assumption audit for the synchronized guarded collision package. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeZeroGuardedCollisionCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeZeroGuardedCollisionCompilation.

Check RawDynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt.
Check
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_merge_boolean_and_imp.
Check
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pairs.
Check
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_on_witnessed_extension_of_zero_normalized_independently_growing_renamed_premise_roots_and_guarded_collision_fixed_productions_or_refutations.
Check
  raw_dynamicTruthLocalGuardedCollisionRootsAt_on_witnessed_extension_of_zero_normalized_restricted_rule_roots_and_canonical_append_kernel_payload_pairs.
Check
  raw_dynamicTruthLocalGuardedCollisionRootsAt_on_witnessed_extension_of_zero_normalized_restricted_rule_roots_and_guarded_collision_fixed_productions_or_refutations.
Check
  raw_dynamicTruthLocalGuardedCollisionRootsAt_on_witnessed_extension_of_zero_normalized_independently_growing_restricted_rule_roots_and_guarded_collision_fixed_productions_or_refutations.

Print Assumptions
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_merge_boolean_and_imp.
Print Assumptions
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_on_witnessed_extension_of_zero_normalized_and_canonical_append_kernel_payload_pairs.
Print Assumptions
  raw_dynamicTruthLocalGuardedCollisionRootsUnderTemplatePrefixAt_on_witnessed_extension_of_zero_normalized_independently_growing_renamed_premise_roots_and_guarded_collision_fixed_productions_or_refutations.
Print Assumptions
  raw_dynamicTruthLocalGuardedCollisionRootsAt_on_witnessed_extension_of_zero_normalized_restricted_rule_roots_and_canonical_append_kernel_payload_pairs.
Print Assumptions
  raw_dynamicTruthLocalGuardedCollisionRootsAt_on_witnessed_extension_of_zero_normalized_restricted_rule_roots_and_guarded_collision_fixed_productions_or_refutations.
Print Assumptions
  raw_dynamicTruthLocalGuardedCollisionRootsAt_on_witnessed_extension_of_zero_normalized_independently_growing_restricted_rule_roots_and_guarded_collision_fixed_productions_or_refutations.
