(** Public-surface and assumption audit for Sigma/Or append integration. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaOrFixedProductionAppendIntegration.

Module
  PABoundedRawCodedDynamicTruthSigmaOrFixedProductionAppendIntegrationAudit.

Import
  PABoundedRawCodedDynamicTruthSigmaOrFixedProductionAppendIntegration.

Check coqDynamicTruthSigmaOrFixedProductionContextOnTailAt.
Check coqDynamicTruthSigmaOrFixedProductionProofOnTailAt.
Check coqDynamicTruthSigmaOrFixedProductionProofOnTailAt_derives.
Check coqDynamicTruthSigmaOrFixedProductionCurriedFormulaAt.
Check coqDynamicTruthSigmaOrFixedProductionCurriedProofAt.
Check coqDynamicTruthSigmaOrFixedProductionCurriedProofAt_derives.
Check
  raw_codedPALocalProofOf_dynamic_truth_sigma_or_fixed_production_of_four_roots.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_sigma_global_of_append_inherited_and_sigma_or_roots.
Check
  raw_dynamicTruthZeroCanonicalFixedProductionRootAtRootTermsUnderPrefix_of_sigma_or_roots_and_code_identification.

Print Assumptions
  coqDynamicTruthSigmaOrFixedProductionProofOnTailAt_derives.
Print Assumptions
  coqDynamicTruthSigmaOrFixedProductionCurriedProofAt_derives.
Print Assumptions
  raw_codedPALocalProofOf_dynamic_truth_sigma_or_fixed_production_of_four_roots.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_shared_sigma_global_of_append_inherited_and_sigma_or_roots.
Print Assumptions
  raw_dynamicTruthZeroCanonicalFixedProductionRootAtRootTermsUnderPrefix_of_sigma_or_roots_and_code_identification.

End
  PABoundedRawCodedDynamicTruthSigmaOrFixedProductionAppendIntegrationAudit.
