From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionPointwiseMembership.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionPointwiseMembership.

Check coqRestrictedPADirectAssumptionFinalNativeTruthTemplate.
Check coqRestrictedPADirectAssumptionMembershipIndexContext.
Check templateRawDerives_impE.
Check coqRestrictedPADirectAssumptionPointwiseMembershipFromRoots.
Check coqRestrictedPADirectAssumptionPointwiseMembershipFromRoot.
Check coqRestrictedPADirectAssumptionPointwiseMembershipRoot.
Check coqRestrictedPADirectAssumptionFinalNativeTruth_shift.
Check coqRestrictedPADirectAssumption_shifted_pointwise_in.
Check coqRestrictedPADirectAssumptionPointwiseMembershipFromRoots_derives.
Check coqRestrictedPADirectAssumptionPointwiseMembershipFromRoot_derives.
Check coqRestrictedPADirectAssumptionPointwiseMembershipRoot_derives.

Print Assumptions templateRawDerives_impE.
Print Assumptions coqRestrictedPADirectAssumptionFinalNativeTruth_shift.
Print Assumptions
  coqRestrictedPADirectAssumptionPointwiseMembershipFromRoots_derives.
Print Assumptions
  coqRestrictedPADirectAssumptionPointwiseMembershipFromRoot_derives.
Print Assumptions
  coqRestrictedPADirectAssumptionPointwiseMembershipRoot_derives.
