(** Kernel-facing audit for arbitrary-context finite derived cases. *)

From BoundedPAConsistency Require Import
  RawCodedPALocalProofFiniteDisjunctionDerivedCases.

Module PABoundedRawCodedPALocalProofFiniteDisjunctionDerivedCasesAudit.

Import PABoundedRawCodedPALocalProofFiniteDisjunctionDerivedCases.

Check RawCodedPALocalFiniteDisjunctionCaseFamily.
Check RawFiniteDisjunctionConsTransplantAdequate.
Check RawFiniteDisjunctionDerivedCaseResources.
Check raw_finiteDisjunctionDerivedCaseResources_tail.

Check raw_codedPALocalProofOf_finiteDisjunctionDerivedCases.
Check raw_codedPALocalProofOf_emptyDisjunctionDerivedCase.
Check raw_codedPALocalProofOf_singletonDisjunctionDerivedCase.
Check raw_codedPALocalProofOf_rightDisjunctionSixDerivedCases.
Check raw_codedPALocalProofOf_rightDisjunctionSevenDerivedCases.

Print Assumptions raw_finiteDisjunctionDerivedCaseResources_tail.
Print Assumptions raw_codedPALocalProofOf_finiteDisjunctionDerivedCases.
Print Assumptions raw_codedPALocalProofOf_emptyDisjunctionDerivedCase.
Print Assumptions raw_codedPALocalProofOf_singletonDisjunctionDerivedCase.
Print Assumptions raw_codedPALocalProofOf_rightDisjunctionSixDerivedCases.
Print Assumptions raw_codedPALocalProofOf_rightDisjunctionSevenDerivedCases.

End PABoundedRawCodedPALocalProofFiniteDisjunctionDerivedCasesAudit.
