(** Strict assumption audit for the exact four-root Ex-E compiler. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationSemanticRootsCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationSemanticRootsCompilation.

Check raw_existentialEliminationPairedChildInterface_standardTailCompiler.
Check raw_existentialEliminationChildLawRoots_standardTailCompiler.
Check
  coqRestrictedPADirectExistentialElimination_mode_one_binder_rows_stable.
Check
  coqRestrictedPADirectExistentialElimination_mode_zero_result_rows_stable.
Check
  raw_rootModeGlobalSourceStandardTailCompilerAt_of_append_concrete_row.
Check
  raw_existentialEliminationBinderContextTruthLaw_standardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_existentialEliminationDynamicTruthLaw_standardTailCompiler_of_aligned_append_concrete_row.
Check raw_existentialEliminationSemanticRootsAtWitnesses_append_stable.
Check
  raw_existentialEliminationSemanticRoots_standardTailCompiler_of_aligned_append_concrete_rows.

Print Assumptions
  raw_existentialEliminationPairedChildInterface_standardTailCompiler.
Print Assumptions raw_existentialEliminationChildLawRoots_standardTailCompiler.
Print Assumptions
  coqRestrictedPADirectExistentialElimination_mode_one_binder_rows_stable.
Print Assumptions
  coqRestrictedPADirectExistentialElimination_mode_zero_result_rows_stable.
Print Assumptions
  raw_rootModeGlobalSourceStandardTailCompilerAt_of_append_concrete_row.
Print Assumptions
  raw_existentialEliminationBinderContextTruthLaw_standardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_existentialEliminationDynamicTruthLaw_standardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_existentialEliminationSemanticRootsAtWitnesses_append_stable.
Print Assumptions
  raw_existentialEliminationSemanticRoots_standardTailCompiler_of_aligned_append_concrete_rows.
