From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSharedSuccessorPermutedAppendGlobalRoots.

Import
  PABoundedRawCodedDynamicTruthSharedSuccessorPermutedAppendGlobalRoots.

Check RawDynamicTruthSharedSuccessorPermutedAppendGlobalInputsAt.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_input_package.
Check
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_permuted_shared_successor_globals_of_append_input_packages.
Check
  raw_dynamicTruthPredecessorPermutedGlobalRootsOnWitnessedExtensionFrom_of_shared_successor_append_input_packages.

Print Assumptions
  raw_codedPAGrowingTemplateLocalProofPairAtEmpty_dynamic_truth_permuted_shared_successor_globals_of_append_input_packages.
Print Assumptions
  raw_dynamicTruthPredecessorPermutedGlobalRootsOnWitnessedExtensionFrom_of_shared_successor_append_input_packages.
