(**
  Kernel-facing surface and assumption audit for the native positive
  single-substitution graph.

  The audit separates three facts which are easy to conflate:

  - the orbit/transform graph has exact, law-free semantics and is
    relationally total on adequate formula codes;
  - every externally fixed standard predecessor is aligned with the
    represented PA proof supplied by the carrier module;
  - proof production at an arbitrary (possibly nonstandard) carrier index
    remains exactly the explicit compiler premise printed below.
*)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeSubstitutionCarrier
  RawCodedDynamicTruthNativeSubstitutionPositiveGraph.

Module PABoundedRawCodedDynamicTruthNativeSubstitutionPositiveGraphAudit.

Import PABoundedRawCodedDynamicTruthNativeSubstitutionCarrier.
Import PABoundedRawCodedDynamicTruthNativeSubstitutionPositiveGraph.

(** Exact seven-variable carrier and its standard-level proof alignment. *)
Check dynamicTruthNativeSubstitutionStepCarrierFormula.
Check dynamicTruthNativeSubstitutionFieldCarrierFormula.
Check dynamicTruthNativeSubstitutionStepCarrierFormula_fixedLevel.
Check dynamicTruthNativeSubstitutionFixedLevelFieldFormula.
Check dynamicTruthNativeSubstitutionFieldCarrierFormula_fixedLevel.
Check dynamicTruthNativeSubstitutionFieldCodeTerm.
Check rawDynamicTruthNativeSubstitutionFieldCode.
Check raw_eval_dynamicTruthNativeSubstitutionFieldCodeTerm.
Check raw_sat_dynamicTruthNativeSubstitutionFieldCodeTermAt_iff.
Check rawDynamicTruthNativeSubstitutionFieldCode_quoted.
Check rawDynamicTruthNativeSubstitutionFieldCode_quoted_successor_level.
Check dynamicTruthNativeSubstitutionFixedLevelFieldFormula_closeN.
Check PA_proves_dynamicTruthNativeSubstitutionFixedLevelFieldFormula.
Check raw_dynamicTruthNativeSubstitutionFixedLevelField_quoted_proof.
Check rawDynamicTruthNativeSubstitutionFieldCode_standard_proof.
Check rawDynamicTruthNativeSubstitutionPositiveFieldCode_standard_alignment.
Check rawDynamicTruthNativeSubstitutionPositiveFieldCode_standard_proof.

(** The six literal replacement terms expose the de Bruijn layout. *)
Check dynamicTruthNativeSubstitutionSourceFirstReplacement.
Check dynamicTruthNativeSubstitutionSourceSecondReplacement.
Check dynamicTruthNativeSubstitutionSourceThirdReplacement.
Check dynamicTruthNativeSubstitutionTargetFirstReplacement.
Check dynamicTruthNativeSubstitutionTargetSecondReplacement.
Check dynamicTruthNativeSubstitutionTargetThirdReplacement.
Check dynamicTruthNativeSubstitutionApplicationTermAt.
Check RawDynamicTruthNativeSubstitutionApplication.
Check raw_sat_dynamicTruthNativeSubstitutionApplicationTermAt_iff.
Check raw_dynamicTruthNativeSubstitutionApplication_exists_adequate.

(** Genuine current-level orbit and exact native transform. *)
Check dynamicTruthNativeSubstitutionInputOrbitGraph.
Check RawDynamicTruthNativeSubstitutionInputOrbitAt.
Check raw_sat_dynamicTruthNativeSubstitutionInputOrbitGraph_iff.
Check raw_sat_dynamicTruthNativeSubstitutionInputOrbitGraph_standard_iff.
Check dynamicTruthNativeSubstitutionFieldTransformGraph.
Check RawDynamicTruthNativeSubstitutionFieldTransformAt.
Check raw_sat_dynamicTruthNativeSubstitutionFieldTransformGraph_iff.
Check rawDynamicTruthNativeSubstitutionFieldCode_atomically_adequate.
Check RawDynamicTruthNativeSubstitutionFieldTransformTotalOnAdequate.
Check dynamicTruthNativeSubstitutionFieldTransformGraph_raw_total_on_adequate.

(** Output-first composition and the one remaining proof-production seam. *)
Check dynamicTruthNativeSubstitutionPositiveGraph.
Check RawDynamicTruthNativeSubstitutionPositiveAt.
Check raw_sat_dynamicTruthNativeSubstitutionPositiveGraph_iff.
Check RawDynamicTruthNativeSubstitutionPositiveAdequateTotal.
Check dynamicTruthNativeSubstitutionPositiveGraph_raw_adequate_total.
Check RawDynamicTruthNativeSubstitutionPositiveTotal.
Check dynamicTruthNativeSubstitutionPositiveGraph_raw_total.
Check RawDynamicTruthNativeSubstitutionProofCompiler.
Check RawDynamicTruthNativeSubstitutionPositiveProofTotal.
Check dynamicTruthNativeSubstitutionPositiveGraph_raw_proof_total_of_compiler.

Print Assumptions dynamicTruthNativeSubstitutionFieldCarrierFormula_fixedLevel.
Print Assumptions rawDynamicTruthNativeSubstitutionFieldCode_quoted_successor_level.
Print Assumptions PA_proves_dynamicTruthNativeSubstitutionFixedLevelFieldFormula.
Print Assumptions rawDynamicTruthNativeSubstitutionFieldCode_standard_proof.
Print Assumptions
  rawDynamicTruthNativeSubstitutionPositiveFieldCode_standard_alignment.
Print Assumptions
  rawDynamicTruthNativeSubstitutionPositiveFieldCode_standard_proof.
Print Assumptions raw_sat_dynamicTruthNativeSubstitutionApplicationTermAt_iff.
Print Assumptions raw_sat_dynamicTruthNativeSubstitutionInputOrbitGraph_iff.
Print Assumptions raw_sat_dynamicTruthNativeSubstitutionFieldTransformGraph_iff.
Print Assumptions rawDynamicTruthNativeSubstitutionFieldCode_atomically_adequate.
Print Assumptions
  dynamicTruthNativeSubstitutionFieldTransformGraph_raw_total_on_adequate.
Print Assumptions raw_sat_dynamicTruthNativeSubstitutionPositiveGraph_iff.
Print Assumptions dynamicTruthNativeSubstitutionPositiveGraph_raw_adequate_total.
Print Assumptions dynamicTruthNativeSubstitutionPositiveGraph_raw_total.
Print Assumptions
  dynamicTruthNativeSubstitutionPositiveGraph_raw_proof_total_of_compiler.

End PABoundedRawCodedDynamicTruthNativeSubstitutionPositiveGraphAudit.
