(** Audit surface for synchronized post-And-I aligned truth integration. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionAlignedTruthIntegration.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionAlignedTruthIntegrationAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionAlignedTruthIntegration.

Check RawCoqRestrictedPADirectOrIntroductionRightTruthAtWitnesses.
Check RawCoqRestrictedPADirectEqualityReflexivityTruthAtWitnesses.
Check RawCoqRestrictedPADirectRemainingAfterAndIntroductionAtWitnesses.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionTwoTruthHolesStandardTailCompiler.

Check raw_orIntroductionRightTruthAtWitnesses_append_stable.
Check raw_equalityReflexivityTruthAtWitnesses_append_stable.
Check raw_postAndIntroductionTruthPairStandardTailCompiler.
Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_two_truth_compilers_and_continuation.
Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_orIntroductionRight_equalityReflexivity_and_continuation.

Print Assumptions raw_orIntroductionRightTruthAtWitnesses_append_stable.
Print Assumptions raw_equalityReflexivityTruthAtWitnesses_append_stable.
Print Assumptions raw_postAndIntroductionTruthPairStandardTailCompiler.
Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_two_truth_compilers_and_continuation.
Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_orIntroductionRight_equalityReflexivity_and_continuation.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionAlignedTruthIntegrationAudit.
