(** Kernel-facing audit for common-context finite disjunction matrices. *)

From BoundedPAConsistency Require Import
  RawCodedPALocalProofFiniteDisjunctionMatrix.

Module PABoundedRawCodedPALocalProofFiniteDisjunctionMatrixAudit.

Import PABoundedRawCodedPALocalProofFiniteDisjunctionMatrix.

Check RawCodedPALocalFiniteDisjunctionPairFamily.
Check RawFiniteDisjunctionMatrixLeftResources.
Check RawFiniteDisjunctionMatrixResources.
Check raw_finiteDisjunctionConsTransplantAdequate_nontrivial_member.
Check raw_finiteDisjunctionMatrixLeftResources_context_realizable.
Check raw_finiteDisjunctionMatrixLeftResources_member_adequate.
Check raw_finiteDisjunctionMatrixLeftResources_derived.
Check raw_finiteDisjunctionDerivedCaseResources_cons_context.

Check raw_codedPALocalProofOf_finiteDisjunctionMatrix_nonempty.
Check raw_codedPALocalProofOf_finiteDisjunctionMatrix.
Check raw_codedPALocalProofOf_finiteDisjunctionMatrix_left_empty.
Check raw_codedPALocalProofOf_finiteDisjunctionMatrix_right_empty.
Check raw_codedPALocalProofOf_finiteDisjunctionMatrix_singletons.
Check raw_codedPALocalProofOf_rightDisjunctionSevenBySixMatrix.

Print Assumptions
  raw_finiteDisjunctionConsTransplantAdequate_nontrivial_member.
Print Assumptions
  raw_finiteDisjunctionDerivedCaseResources_cons_context.
Print Assumptions raw_codedPALocalProofOf_finiteDisjunctionMatrix_nonempty.
Print Assumptions raw_codedPALocalProofOf_finiteDisjunctionMatrix.
Print Assumptions
  raw_codedPALocalProofOf_finiteDisjunctionMatrix_singletons.
Print Assumptions
  raw_codedPALocalProofOf_rightDisjunctionSevenBySixMatrix.

End PABoundedRawCodedPALocalProofFiniteDisjunctionMatrixAudit.
