(** Assumption and API audit for deep closure through the global wrapper. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthGlobalSuccessorDeepClosure.

Import PABoundedRawCodedDynamicTruthGlobalSuccessorDeepClosure.

Check RawCodedFormulaDeepOperationallyClosedFrom.
Check RawCodedFormulaDeepClosedFrom.
Check rawCodedFormulaDeepClosedFrom_three_iff.
Check raw_quotedFormula_deep_closed_from_scope.
Check raw_fixedFormulaNumeralCode_deep_closed_from_scope.

Check rawFormulaShiftBinaryCode_deep_closed_from.
Check rawFormulaShiftUnaryCode_deep_closed_from.
Check rawFormulaImpCode_deep_closed_from.
Check rawFormulaAndCode_deep_closed_from.
Check rawFormulaOrCode_deep_closed_from.
Check rawFormulaAllCode_deep_closed_from.
Check rawFormulaExCode_deep_closed_from.
Check rawDynamicTruthFormulaAll5Code_deep_closed_from.
Check rawDynamicTruthFormulaEx10Code_deep_closed_from.
Check rawDynamicTruthFormulaAnd7Code_deep_closed_from.

Check RawDynamicTruthPairedLocalRowsDeepClosedAtWrapperDepth.
Check rawDynamicTruthGlobalRowChoiceCode_deep_closed.
Check rawDynamicTruthGlobalRowsCode_deep_closed.
Check rawDynamicTruthGlobalFormulaCode_deep_closed_of_local_rows.
Check dynamicTruthPairedGlobalWrapperAt_deep_closed.

Check RawDynamicTruthPairedGlobalSuccessorLocalDeepClosure.
Check dynamicTruthPairedGlobalSuccessorAt_deep_closed.
Check RawDynamicTruthPairedGlobalDeepClosedSuccessorTotal.
Check dynamicTruthPairedGlobalSuccessorGraph_raw_deep_closed_total.

Print Assumptions raw_quotedFormula_deep_closed_from_scope.
Print Assumptions rawFormulaShiftBinaryCode_deep_closed_from.
Print Assumptions rawFormulaShiftUnaryCode_deep_closed_from.
Print Assumptions rawDynamicTruthGlobalFormulaCode_deep_closed_of_local_rows.
Print Assumptions dynamicTruthPairedGlobalWrapperAt_deep_closed.
Print Assumptions dynamicTruthPairedGlobalSuccessorAt_deep_closed.
Print Assumptions
  dynamicTruthPairedGlobalSuccessorGraph_raw_deep_closed_total.
