From BoundedPAConsistency Require Import
  RawCodedPALocalProofContextInsertInduction.

Import PABoundedRawCodedPALocalProofContextInsertInduction.

Check RawCodedPALocalProofContextInsertAt.
Check codedPALocalProofContextInsertAtTermAt.
Check raw_sat_codedPALocalProofContextInsertAtTermAt_iff.
Check RawCodedPALocalProofContextInsertBelow.
Check codedPALocalProofContextInsertBelowTermAt.
Check raw_sat_codedPALocalProofContextInsertBelowTermAt_iff.
Check raw_codedPALocalProof_contextInsert_assumption.
Check RawCodedPALocalProofContextInsertRootStep.
Check raw_codedPALocalProofContextInsertBelow_all.
Check raw_codedPALocalProofContextInsertAt_all.
Check raw_codedPALocalProof_adequateConsTransplant_of_contextInsertRootStep.

Print Assumptions raw_codedPALocalProofContextInsertBelow_all.
Print Assumptions raw_codedPALocalProofContextInsertAt_all.
Print Assumptions
  raw_codedPALocalProof_adequateConsTransplant_of_contextInsertRootStep.
