(** API and assumption audit for the paired-orbit Pi local field. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthRestrictedExistentialLocalProofFieldGraph.

Import PABoundedRawCodedDynamicTruthRestrictedExistentialLocalProofFieldGraph.

Check dynamicTruthPiRestrictedExistentialLocalProofFieldGraph.
Check RawDynamicTruthPiRestrictedExistentialLocalProofFieldAt.
Check raw_sat_dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_iff.
Check RawDynamicTruthPiRestrictedExistentialOrbitDirectCompilerTotal.
Check RawDynamicTruthPiRestrictedExistentialOrbitTernaryInterchangeTotal.
Check rawDynamicTruthPiRestrictedExistentialOrbitDirectCompilerTotal_of_interchange.
Check dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_adequate_proof_total.
Check RawDynamicTruthPiRestrictedExistentialLocalProofFieldTotal.
Check dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total.
Check dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total_of_orbit_interchange.

Print Assumptions
  raw_sat_dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_iff.
Print Assumptions
  rawDynamicTruthPiRestrictedExistentialOrbitDirectCompilerTotal_of_interchange.
Print Assumptions
  dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_adequate_proof_total.
Print Assumptions
  dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total.
Print Assumptions
  dynamicTruthPiRestrictedExistentialLocalProofFieldGraph_raw_proof_total_of_orbit_interchange.
