(** Strict assumption audit for the arithmetic Ex-E child source. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageReificationCaseCertificate
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageReificationExistentialChildCertificate
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageReificationBodyChildCertificate
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceTemplateValidityChildShapes
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceTemplateValidityExistentialChildView
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceTemplateValidityBodyChildView
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceTemplateValidityOpenedLaw
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceTemplateValidity
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceReification
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceEmbedding
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceProvability
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSourceSubstitution
  RawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSource.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageReificationCaseCertificate.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageReificationExistentialChildCertificate.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageReificationBodyChildCertificate.
Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectExistentialEliminationOpenedCoverageSource.

Check coqRestrictedPADirectExistentialEliminationOpenedCase_reifies.
Check coqRestrictedPADirectExistentialEliminationOpenedExistentialChild_reifies.
Check coqRestrictedPADirectExistentialEliminationOpenedBodyChild_reifies.
Check raw_existentialElimination_openedCoverageLaw_valid.
Check PA_proves_coqRestrictedPADirectExistentialEliminationOpenedCoverageSource.
Check rawDirect_existentialEliminationOpenedCoverageSource_substitution.

Print Assumptions raw_existentialElimination_openedCoverageLaw_valid.
Print Assumptions
  coqRestrictedPADirectExistentialEliminationOpenedCase_reifies.
Print Assumptions
  coqRestrictedPADirectExistentialEliminationOpenedExistentialChild_reifies.
Print Assumptions
  coqRestrictedPADirectExistentialEliminationOpenedBodyChild_reifies.
Print Assumptions
  PA_proves_coqRestrictedPADirectExistentialEliminationOpenedCoverageSource.
Print Assumptions
  rawDirect_existentialEliminationOpenedCoverageSource_substitution.
