(** Audit surface for the exact seven-field post-And-I continuation. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldRemainderIntegration.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldRemainderIntegrationAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldRemainderIntegration.

(** The residual boundary itself contains exactly seven rule-level fields. *)
Check
  RawCoqRestrictedPADirectRuleCaseSemanticRootsAfterAndIntroductionSevenFieldRemainder.
Check rawCoqRestrictedPADirectAfterAndISeven_andEliminationLeftTruth.
Check rawCoqRestrictedPADirectAfterAndISeven_andEliminationRightTruth.
Check rawCoqRestrictedPADirectAfterAndISeven_orElimination.
Check
  rawCoqRestrictedPADirectAfterAndISeven_universalEliminationRecursive.
Check rawCoqRestrictedPADirectAfterAndISeven_existentialIntroduction.
Check rawCoqRestrictedPADirectAfterAndISeven_existentialElimination.
Check rawCoqRestrictedPADirectAfterAndISeven_equalityElimination.
Check
  RawCoqRestrictedPADirectRemainingAfterAndIntroductionSevenFieldStandardTailCompiler.

(** Complementary compiled bundle and its affine synchronization. *)
Check RawCoqRestrictedPADirectUniversalKOnlyAtWitnesses.
Check RawCoqRestrictedPADirectPostAndIResolvedSevenAtWitnesses.
Check RawCoqRestrictedPADirectPostAndIResolvedSevenStandardTailCompiler.
Check raw_sameContextUnaryRecursiveRootsAtWitnesses_append_stable.
Check raw_universalKOnlyAtWitnesses_append_stable.
Check raw_postAndIResolvedSevenAtWitnesses_append_stable.
Check raw_postAndIResolvedSevenStandardTailCompiler_of_compilers.

(** Pointwise and growing-tail assemblers, including the aligned endpoint. *)
Check raw_afterAndIntroduction_of_resolvedSeven_and_sevenFieldRemainder.
Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_compilers_and_sevenFieldRemainder.
Check
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_four_rows_interfaces_and_sevenFieldRemainder.

Print Assumptions
  raw_sameContextUnaryRecursiveRootsAtWitnesses_append_stable.
Print Assumptions raw_universalKOnlyAtWitnesses_append_stable.
Print Assumptions raw_postAndIResolvedSevenAtWitnesses_append_stable.
Print Assumptions raw_postAndIResolvedSevenStandardTailCompiler_of_compilers.
Print Assumptions
  raw_afterAndIntroduction_of_resolvedSeven_and_sevenFieldRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_compilers_and_sevenFieldRemainder.
Print Assumptions
  raw_remainingAfterAndIntroductionStandardTailCompiler_of_aligned_four_rows_interfaces_and_sevenFieldRemainder.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectPostAndIntroductionSevenFieldRemainderIntegrationAudit.
