(** Assumption and API audit for Pi direct structural identification. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPiTemplateDirectInputs.

Import PABoundedRawCodedDynamicTruthPiTemplateDirectInputs.

Check coqDynamicTruthPiLowerLevelParameterName_eq_shared.
Check coqDynamicTruthPiUpperLevelParameterName_eq_shared.
Check coqDynamicTruthLowerSigmaPredicateName_eq_shared.
Check coqDynamicTruthPiLowerLevelTerm_eq_shared.
Check coqDynamicTruthPiUpperLevelTerm_eq_shared.

Check rawCoqDynamicTruthPiTemplateDirectStructuralInputs.
Check raw_dynamicTruthPiRowDomainTemplate_quoted_code.
Check rawCoqDynamicTruthLowerSigmaDirectAtomTemplateCode.
Check rawDirect_coqDynamicTruthLowerSigmaAtomTemplate.
Check RawCoqDynamicTruthPiDirectTemplateIdentification.
Check rawCoqDynamicTruthPiDirect_domain_identified.
Check rawCoqDynamicTruthPiDirect_lowerApplication_identified.

Check rawDirect_coqDynamicTruthPiExistentialLeafTemplate.
Check rawDirect_coqDynamicTruthPiBranchesTemplate.
Check rawDirect_coqDynamicTruthPiSuccessorRowTemplate.
Check rawDirect_coqDynamicTruthPiSuccessorRowTemplate_identified.
Check rawDirect_coqDynamicTruthPiSuccessorRowTemplate_identifies_native.
Check rawDirect_coqDynamicTruthPiRestrictedProjection_identified.

Check raw_dynamicTruthPiCoqLowerApplication_functional.
Check rawCoqDynamicTruthPiDomainLeaf_opening_trace.
Check rawCoqDynamicTruthPiDomainLeaf_identifies_native_domain.
Check rawCoqDynamicTruthLowerSigmaAtomDirect_code.
Check rawCoqDynamicTruthLowerSigmaAtom_selector_trace.
Check RawCoqDynamicTruthPiLowerApplicationCompatibility.
Check rawCoqDynamicTruthPiLowerApplicationCompatibility_holds.
Check rawCoqDynamicTruthPiLowerApplication_selector_unique.
Check rawCoqDynamicTruthLowerSigmaAtom_identifies_native_application.
Check rawCoqDynamicTruthLowerSigmaAtom_native_application.
Check rawCoqDynamicTruthPiDirectTemplateIdentification_of_native.
Check raw_coqDynamicTruthPiDirectTemplateIdentification_exists.

Print Assumptions raw_dynamicTruthPiRowDomainTemplate_quoted_code.
Print Assumptions rawDirect_coqDynamicTruthPiRestrictedProjection_identified.
Print Assumptions raw_dynamicTruthPiCoqLowerApplication_functional.
Print Assumptions rawCoqDynamicTruthPiDomainLeaf_opening_trace.
Print Assumptions rawCoqDynamicTruthLowerSigmaAtom_selector_trace.
Print Assumptions rawCoqDynamicTruthPiLowerApplicationCompatibility_holds.
Print Assumptions
  rawCoqDynamicTruthLowerSigmaAtom_identifies_native_application.
Print Assumptions rawCoqDynamicTruthPiDirectTemplateIdentification_of_native.
Print Assumptions raw_coqDynamicTruthPiDirectTemplateIdentification_exists.
