(** Assumption audit for paired-global successor/orbit functionality. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPairedGlobalOrbitFunctionality.

Import PABoundedRawCodedDynamicTruthPairedGlobalOrbitFunctionality.

Check raw_dynamicTruthSigmaSuccessorRowAt_functional.
Check raw_dynamicTruthPiSuccessorRowAt_functional.
Check raw_dynamicTruthPairedSuccessorRowAt_functional.
Check raw_dynamicTruthPairedGlobalSuccessorAt_functional.
Check raw_sat_dynamicTruthPairedGlobalSuccessorGraph_functional.
Check raw_sat_dynamicTruthPairedGlobalOrbitFunctionalFormula_iff.
Check raw_dynamicTruthPairedGlobalFormulaCodeOrbitFunctionalAt_all.
Check raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_functional.
Check raw_sat_dynamicTruthPairedGlobalFormulaCodeOrbitGraph_functional.
Check raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_adequate.
Check raw_dynamicTruthPairedGlobalFormulaCodeAdequateOrbitAt_functional.
Check RawDynamicTruthNativeFivePositiveOrbitCoherentAt.
Check raw_dynamicTruthNativeFivePositiveAt_orbit_coherent.
Check raw_dynamicTruthNativeFivePositiveGraphs_orbit_coherent.

Print Assumptions raw_dynamicTruthPairedGlobalSuccessorAt_functional.
Print Assumptions
  raw_dynamicTruthPairedGlobalFormulaCodeOrbitFunctionalAt_all.
Print Assumptions
  raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_functional.
Print Assumptions
  raw_dynamicTruthPairedGlobalFormulaCodeOrbitAt_adequate.
Print Assumptions raw_dynamicTruthNativeFivePositiveAt_orbit_coherent.
Print Assumptions raw_dynamicTruthNativeFivePositiveGraphs_orbit_coherent.
