(** Audit the exact seventeen-constructor direct soundness frontier. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectRuleDispatchFrontier.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectRuleDispatchFrontierAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectRuleDispatchFrontier.

Check RawCoqRestrictedPAProofRuleCase.
Check rawCoqRuleAssumption.
Check rawCoqRuleImpIntroduction.
Check rawCoqRuleImpElimination.
Check rawCoqRuleBottomElimination.
Check rawCoqRuleExcludedMiddle.
Check rawCoqRuleAndIntroduction.
Check rawCoqRuleAndEliminationLeft.
Check rawCoqRuleAndEliminationRight.
Check rawCoqRuleOrIntroductionLeft.
Check rawCoqRuleOrIntroductionRight.
Check rawCoqRuleOrElimination.
Check rawCoqRuleAllIntroduction.
Check rawCoqRuleAllElimination.
Check rawCoqRuleExIntroduction.
Check rawCoqRuleExElimination.
Check rawCoqRuleEqualityReflexivity.
Check rawCoqRuleEqualityElimination.

Check rawCoqRestrictedPAProofRuleCases.
Check rawCoqRestrictedPAProofRuleCaseFormula.
Check rawCoqRestrictedPAProofRuleCaseTemplate.
Check rawCoqRestrictedPAProofRuleCaseTemplates.
Check raw_coqRestrictedPAProofRuleCaseTemplates_exact.
Check rawCoqRestrictedPADirectEndpointWitnessEqualityTemplate.
Check rawCoqRestrictedPADirectEndpointRuleCaseTemplates.
Check rawCoqRestrictedPADirectEndpointWitnessBodyTemplate.
Check rawCoqTemplateEx8.
Check raw_coqRestrictedPADerivationSoundnessEndpointTemplate_rule_shape.
Check raw_coqTemplateRuleDisjunction_finite_code.
Check raw_finiteRightDisjunctionCode_atomically_adequate_of_forall.
Check raw_finiteDisjunctionConsTransplantAdequate_of_forall.
Check raw_finiteDisjunctionDerivedCaseResources_of_forall.
Check RawCoqRestrictedPADirectRuleCaseImplicationRoots.
Check raw_coqRestrictedPAProofRuleCases_complete.
Check raw_codedPALocalProofOf_coqRestrictedPADirectRuleDispatch.
Check raw_coqRestrictedPADirectRuleCaseCodes_atomically_adequate.
Check raw_codedPALocalProofOf_coqRestrictedPADirectRuleDispatch_exact.
Check RawCoqRestrictedPADirectEndpointRuleCaseImplicationRoots.
Check raw_codedPALocalProofOf_coqRestrictedPADirectEndpointRuleDispatch.
Check rawCoqRestrictedPADirectEndpointDeepContext.
Check rawCoqRestrictedPADirectEndpointDeepTail.
Check raw_coqRestrictedPADirectEndpointDeepContext_shape.
Check raw_coqTemplateExN_eight.
Check RawCoqRestrictedPADirectDeepEndpointRuleCaseImplicationRoots.
Check raw_codedPALocalProofOf_coqRestrictedPADirectEndpointFromRuleCases.

Print Assumptions raw_coqRestrictedPAProofRuleCaseTemplates_exact.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessEndpointTemplate_rule_shape.
Print Assumptions raw_coqTemplateRuleDisjunction_finite_code.
Print Assumptions raw_coqRestrictedPAProofRuleCases_complete.
Print Assumptions raw_codedPALocalProofOf_coqRestrictedPADirectRuleDispatch.
Print Assumptions
  raw_coqRestrictedPADirectRuleCaseCodes_atomically_adequate.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectRuleDispatch_exact.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectEndpointRuleDispatch.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADirectEndpointFromRuleCases.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectRuleDispatchFrontierAudit.
