From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeAlignedRootApplicationIdentification.

Import
  PABoundedRawCodedDynamicTruthNativeAlignedRootApplicationIdentification.

Check coqDirectTemplateTernaryApplication_reverse_reroot.
Check coqDynamicTruthSharedSigmaGlobalSource_scoped_three.
Check coqDynamicTruthSharedPiGlobalSource_scoped_three.
Check coqDynamicTruthNativeAlignedSigmaEvidencePredicateTemplate.
Check coqDynamicTruthNativeAlignedPiEvidencePredicateTemplate.
Check coqDynamicTruthNativeAlignedSigmaEvidenceAtRootTerms.
Check coqDynamicTruthNativeAlignedPiEvidenceAtRootTerms.
Check coqDynamicTruthNativeAlignedSigmaEvidenceConclusionTemplate_reverse.
Check coqDynamicTruthNativeAlignedPiEvidenceConclusionTemplate_reverse.
Check raw_dynamicTruthNativeAligned_global_evidence_reroot.
Check raw_dynamicTruthNativeAligned_impIntroduction_applications.

Print Assumptions coqDirectTemplateTernaryApplication_reverse_reroot.
Print Assumptions coqDynamicTruthSharedSigmaGlobalSource_scoped_three.
Print Assumptions coqDynamicTruthSharedPiGlobalSource_scoped_three.
Print Assumptions raw_dynamicTruthNativeAligned_global_evidence_reroot.
Print Assumptions raw_dynamicTruthNativeAligned_impIntroduction_applications.
