From BoundedPAConsistency Require Import
  RawCodedDynamicTruthSigmaOrOpenedConstructorCodeProjection
  RawCodedDynamicTruthSigmaOrCorrelatedConstructorConsumer.

Import
  PABoundedRawCodedDynamicTruthSigmaOrOpenedConstructorCodeProjection.
Import
  PABoundedRawCodedDynamicTruthSigmaOrCorrelatedConstructorConsumer.

Check coqDynamicTruthSigmaOrCorrelatedConstructorBodyTemplate.
Check coqDynamicTruthSigmaOrCorrelatedConstructorSourceTemplate.
Check coqDynamicTruthSigmaOrCorrelatedConstructorSourceTemplate_exact.
Check coqDynamicTruthSigmaOrCorrelatedConstructorBody_code_shape.
Check coqDynamicTruthSigmaOrOpenedConstructorCodeRootTemplate_shape.
Check coqDynamicTruthSigmaOrOpenedConstructorCodeRootTemplate_neq_guarded.

Check coqDynamicTruthSharedSigmaSuccessorRowTemplate_ex8_shape.
Check coqDynamicTruthSigmaOr_open_fresh_after_rename8_ex8.
Check coqDynamicTruthSigmaOrHonestConstructor_opened_renamed_row.
Check coqDynamicTruthSigmaOrCorrelatedConstructorDeepContextOn.
Check coqDynamicTruthSigmaOrCorrelatedConstructorDeepContextOn_head.

Check coqDynamicTruthSigmaOrCorrelatedRowBodyProof_derives.
Check coqDynamicTruthSigmaOrCorrelatedRenamedRowProof_derives.
Check coqDynamicTruthSigmaOrCorrelatedConstructorRowProofOn_derives.
Check coqDynamicTruthSigmaOrCorrelatedConstructorRowConsumerProof_derives.
Check
  raw_codedPALocalProofOf_dynamicTruthSigmaOr_correlatedConstructorRow_of_root.

Print Assumptions
  coqDynamicTruthSigmaOrCorrelatedConstructorBody_code_shape.
Print Assumptions
  coqDynamicTruthSigmaOr_open_fresh_after_rename8_ex8.
Print Assumptions
  coqDynamicTruthSigmaOrHonestConstructor_opened_renamed_row.
Print Assumptions
  coqDynamicTruthSigmaOrCorrelatedConstructorRowProofOn_derives.
Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthSigmaOr_correlatedConstructorRow_of_root.
