(** Kernel-facing audit of dependency-ordered native successor assembly. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeStagedPositiveSuccessor.

Module PABoundedRawCodedDynamicTruthNativeStagedPositiveSuccessorAudit.

Import PABoundedRawCodedDynamicTruthNativeStagedPositiveSuccessor.

Check RawDynamicTruthNativeStagedPositiveCurrentAt.
Check RawDynamicTruthNativePositiveFieldOrdinaryProofAt.
Check RawDynamicTruthNativeStagedNextLocalProofAt.
Check RawDynamicTruthNativeStagedNextCrossLevelProofAt.
Check RawDynamicTruthNativeStagedNextShiftProofAt.
Check RawDynamicTruthNativeStagedNextSubstitutionProofAt.
Check RawDynamicTruthNativeStagedNextAxiomSoundnessProofAt.
Check RawDynamicTruthNativeStagedNextFinalProofAt.

Check RawDynamicTruthNativeStagedNextLocalCompiler.
Check RawDynamicTruthNativeStagedNextCrossLevelCompiler.
Check RawDynamicTruthNativeStagedNextShiftCompiler.
Check RawDynamicTruthNativeStagedNextSubstitutionCompiler.
Check RawDynamicTruthNativeStagedNextAxiomSoundnessCompiler.
Check RawDynamicTruthNativeStagedNextFinalCompiler.
Check RawDynamicTruthNativeDependencyOrderedPositiveCallbacks.
Check RawDynamicTruthNativeStagedPositiveOrdinarySuccessor.
Check
  raw_dynamicTruthNativeStagedPositiveOrdinarySuccessor_of_callbacks.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_staged_ordinary.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_dependency_ordered_callbacks.
Check
  RawDynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels_of_dependency_ordered_callbacks.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_callbacks.

Print Assumptions
  raw_dynamicTruthNativeStagedPositiveOrdinarySuccessor_of_callbacks.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_staged_ordinary.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_dependency_ordered_callbacks.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessorInAllModels_of_dependency_ordered_callbacks.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_callbacks.

End PABoundedRawCodedDynamicTruthNativeStagedPositiveSuccessorAudit.
