(** Public surface and assumption audit for aligned And-I continuation use. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionAlignedContinuationIntegration.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionAlignedContinuationIntegrationAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionAlignedContinuationIntegration.

Check raw_remainingAfterBottomEliminationCompiler_of_alignedAndIntroduction.
Check
  raw_remainingAfterBottomEliminationCompiler_of_alignedAndIntroduction_and_excludedMiddle.
Check
  raw_remainingRuleCasesV2Compiler_of_selected_prefix_bottom_and_alignedAndIntroduction.
Check
  raw_remainingRuleCasesV2Compiler_of_fixedRowSplit_bottom_and_alignedAndIntroduction.
Check
  raw_remainingRuleCasesV2Compiler_of_fixedRowSplit_bottom_and_alignedAndIntroduction_excludedMiddle.

Print Assumptions
  raw_remainingAfterBottomEliminationCompiler_of_alignedAndIntroduction.
Print Assumptions
  raw_remainingAfterBottomEliminationCompiler_of_alignedAndIntroduction_and_excludedMiddle.
Print Assumptions
  raw_remainingRuleCasesV2Compiler_of_selected_prefix_bottom_and_alignedAndIntroduction.
Print Assumptions
  raw_remainingRuleCasesV2Compiler_of_fixedRowSplit_bottom_and_alignedAndIntroduction.
Print Assumptions
  raw_remainingRuleCasesV2Compiler_of_fixedRowSplit_bottom_and_alignedAndIntroduction_excludedMiddle.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionAlignedContinuationIntegrationAudit.
