From BoundedPAConsistency Require Import
  RawCodedCarrierIndexedCodeOrbitGraph.

Import PABoundedRawCodedCarrierIndexedCodeOrbitGraph.

Check carrierCodeOrbitBaseRenaming.
Check carrierCodeOrbitSuccessorRenaming.
Check RawCarrierIndexedCodeOrbitRows.
Check RawCarrierIndexedCodeOrbitTrace.
Check RawCarrierIndexedCodeOrbitAt.
Check carrierIndexedCodeOrbitGraph.
Check raw_sat_carrierIndexedCodeOrbitGraph_iff.
Check RawCarrierIndexedCodeOrbitBaseTotal.
Check RawCarrierIndexedCodeOrbitSuccessorTotal.
Check raw_carrierIndexedCodeOrbitAt_zero_of_base.
Check raw_carrierIndexedCodeOrbitAt_succ.
Check raw_carrierIndexedCodeOrbitExists_all.
Check RawCarrierIndexedCodeOrbitGraphTotal.
Check raw_carrierIndexedCodeOrbitGraph_total.
Check raw_carrierIndexedCodeOrbitAt_zero_iff.
Check raw_carrierIndexedCodeOrbitAt_succ_iff.
Check raw_carrierIndexedCodeOrbitGraph_zero_iff.
Check raw_carrierIndexedCodeOrbitGraph_succ_iff.

Print Assumptions raw_sat_carrierIndexedCodeOrbitGraph_iff.
Print Assumptions raw_carrierIndexedCodeOrbitAt_zero_of_base.
Print Assumptions raw_carrierIndexedCodeOrbitAt_succ.
Print Assumptions raw_carrierIndexedCodeOrbitExists_all.
Print Assumptions raw_carrierIndexedCodeOrbitGraph_total.
Print Assumptions raw_carrierIndexedCodeOrbitAt_zero_iff.
Print Assumptions raw_carrierIndexedCodeOrbitAt_succ_iff.
Print Assumptions raw_carrierIndexedCodeOrbitGraph_zero_iff.
Print Assumptions raw_carrierIndexedCodeOrbitGraph_succ_iff.
