(** Audit surface for carrier-parametric restricted-proof rerooting. *)

From BoundedPAConsistency Require Import
  RawCodedCarrierRestrictedProofReroot.

Import PABoundedRawCodedCarrierRestrictedProofReroot.

Check RawCarrierRestrictedProofNodeAt.
Check RawCarrierRestrictedProofTraversalAt.
Check RawCarrierRestrictedProofCertificateAt.
Check RawCarrierRestrictedProofAt.
Check RawCarrierFormulaQuantifierBounded.
Check RawCarrierContextAllBounded.
Check RawCarrierRestrictedProofNode.
Check raw_restrictedTargetFormulaQuantifierBoundedContextSat_iff.
Check raw_restrictedTargetContextAllBoundedContextSat_iff.
Check raw_restrictedTargetProofNodeContextSat_iff.
Check raw_carrierRestrictedProofNodeAt_iff.
Check raw_carrierRestrictedProofNodeAt_tail_ext.
Check raw_carrierRestrictedProofTraversalAt_tail_ext.
Check raw_carrierRestrictedProofCertificateAt_tail_ext.
Check raw_carrierRestrictedProofAt_tail_ext.
Check raw_carrierRestrictedProofNodeAt_syntax.
Check raw_carrierRestrictedProofContextSat_iff.
Check raw_carrierRestrictedProof_endpoint_formula_bounded.
Check raw_carrierRestrictedProofTraversalAt_weaken.
Check raw_carrierRestrictedProofAt_orI_left_child.
Check raw_carrierRestrictedProofAt_orI_left_child_between.
Check raw_restrictedTargetProofContextSat_orI_left_child.
Check raw_restrictedTargetProofContextSat_orI_left_child_between.

Print Assumptions raw_restrictedTargetProofNodeContextSat_iff.
Print Assumptions raw_carrierRestrictedProofAt_tail_ext.
Print Assumptions raw_carrierRestrictedProofContextSat_iff.
Print Assumptions raw_carrierRestrictedProof_endpoint_formula_bounded.
Print Assumptions raw_carrierRestrictedProofTraversalAt_weaken.
Print Assumptions raw_carrierRestrictedProofAt_orI_left_child.
Print Assumptions raw_carrierRestrictedProofAt_orI_left_child_between.
Print Assumptions raw_restrictedTargetProofContextSat_orI_left_child.
Print Assumptions raw_restrictedTargetProofContextSat_orI_left_child_between.
