(** Audit surface for the direct consistency-from-soundness bridge. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAConsistencyFromUniversalSoundnessDirect.

Import
  PABoundedRawCodedRestrictedPAConsistencyFromUniversalSoundnessDirect.

Check rawCoqRestrictedPAAxiomContextsTruthDirectCode.
Check rawCoqRestrictedPABottomTruthRefutationDirectCode.
Check rawCoqRestrictedPAConsistencyFromSoundnessTargetDirectCode.
Check rawCoqRestrictedPAConsistencyFromSoundnessBridgeDirectCode.
Check raw_coqRestrictedPAConsistencyFromSoundnessTargetDirectCode_exact.
Check raw_coqRestrictedPAConsistencyFromSoundnessBridgeDirectCode_view.

Check rawCoqRestrictedPAConsistencyBridgeBodyDirectContextCode.
Check RawCoqRestrictedPASelectedAxiomContextTruthDirectSupport.
Check rawCoqRestrictedPAAxiomContextsTruthDirectRoot.
Check raw_coqRestrictedPAAxiomContextsTruthDirect_of_selected_support.

Check RawCoqRestrictedPAConsistencyFromUniversalSoundnessDirectOpenCompiler.
Check rawCoqRestrictedPAConsistencyFromSoundnessBridgeDirectRoot.
Check raw_coqRestrictedPAConsistencyFromSoundnessBridgeDirect_of_open.

Print Assumptions
  raw_coqRestrictedPAConsistencyFromSoundnessTargetDirectCode_exact.
Print Assumptions
  raw_coqRestrictedPAConsistencyFromSoundnessBridgeDirectCode_view.
Print Assumptions
  raw_coqRestrictedPAAxiomContextsTruthDirect_of_selected_support.
Print Assumptions
  raw_coqRestrictedPAConsistencyFromSoundnessBridgeDirect_of_open.
