From BoundedPAConsistency Require Import
  RawCodedRestrictedPADirectImpIntroductionPositiveBodyAppendProduction.

Import
  PABoundedRawCodedRestrictedPADirectImpIntroductionPositiveBodyAppendProduction.

Check
  raw_fourStateTableAppendEqualityProductionInputsAt_on_witnessed_tail_under_prefix_of_local_roots.
Check
  raw_codedPALocalProofOf_four_state_table_append_equality_fixed_lookup_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_four_state_table_append_traversal_body_on_witnessed_tail_under_prefix.
Check coqRestrictedPADirectImpIntroduction_shared_rows_at_root_terms_eq.
Check
  raw_codedPALocalProofOf_dynamic_truth_shared_global_at_root_terms_of_append_and_concrete_row_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_implications_on_standard_prefix.

Check coqRestrictedPADirectImpIntroductionAppendWitness7.
Check coqRestrictedPADirectImpIntroductionAppendWitness0.
Check
  RawCoqRestrictedPADirectImpIntroductionSigmaImpAppendRootsCompilerAt.
Check
  raw_restrictedPADirectImpIntroductionPositiveBodyCompilerAt_of_sigma_imp_append_roots.
Check
  RawCoqRestrictedPADirectImpIntroductionPositiveBodyAppendRootCompilers.
Check
  raw_restrictedPADirectImpIntroductionPositiveBodyCompilers_of_literal_append_roots.

Print Assumptions
  raw_codedPALocalProofOf_four_state_table_append_concrete_closed_row_implications_on_standard_prefix.
Print Assumptions
  coqRestrictedPADirectImpIntroduction_shared_rows_at_root_terms_eq.
Print Assumptions
  raw_codedPALocalProofOf_dynamic_truth_shared_global_at_root_terms_of_append_and_concrete_row_on_witnessed_tail.
Print Assumptions
  raw_restrictedPADirectImpIntroductionPositiveBodyCompilerAt_of_sigma_imp_append_roots.
Print Assumptions
  raw_restrictedPADirectImpIntroductionPositiveBodyCompilers_of_literal_append_roots.
