(** Assumption audit for atomically adequate paired successor rows. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPairedSuccessorAdequacy.

Import PABoundedRawCodedDynamicTruthPairedSuccessorAdequacy.

Check raw_codedTermZeroShift_identity_of_syntax_realizable.
Check raw_codedFormula_zeroShift_identity.
Check raw_formulaImpCode_atomically_adequate.
Check raw_formulaAndCode_atomically_adequate.
Check raw_formulaOrCode_atomically_adequate.
Check raw_formulaAllCode_atomically_adequate.
Check raw_formulaExCode_atomically_adequate.

Check raw_numeralTermCode_syntax_realizable_zero.
Check raw_dynamicTruthSigmaDomain_exists_adequate.
Check raw_dynamicTruthPiDomain_exists_adequate.
Check raw_dynamicTruthSigmaLower_exists_adequate.
Check raw_dynamicTruthPiLower_exists_adequate.

Check rawDynamicTruthSigmaSuccessorRowCode_atomically_adequate.
Check rawDynamicTruthPiSuccessorRowCode_atomically_adequate.
Check dynamicTruthPairedSuccessorRowGraph_raw_adequate_total.

Print Assumptions raw_codedTermZeroShift_identity_of_syntax_realizable.
Print Assumptions raw_codedFormula_zeroShift_identity.
Print Assumptions raw_dynamicTruthSigmaDomain_exists_adequate.
Print Assumptions raw_dynamicTruthSigmaLower_exists_adequate.
Print Assumptions rawDynamicTruthSigmaSuccessorRowCode_atomically_adequate.
Print Assumptions rawDynamicTruthPiSuccessorRowCode_atomically_adequate.
Print Assumptions dynamicTruthPairedSuccessorRowGraph_raw_adequate_total.
