(** Shared imports for independently checked Or-E shape equations. *)

From Stdlib Require Import List Lia.
From FirstOrder Require Import Fol.
From PAHF Require Import PAHF.
From PAListCoding Require Import Representability ListFormulas.
From PAFiniteBasisReduction Require Import
  HierarchyReduction CanonicalSelector CanonicalSelectorPA FiniteBetaCoding.
From BoundedPAConsistency Require Import
  RawModelCompleteness
  RawCodedAssignment
  RawCodedSyntaxConstructors
  RawCodedFormulaOperations
  RawCodedProofConstructors
  RawCodedProofDescent
  RawCodedProofEndpoints
  RawCodedProofRules
  RawCodedProofAtomicAdequacy
  RawCodedProofFormulaCoverage
  RawCodedProofRuleCoverage
  RawCodedRestrictedPAProof
  RawCodedFixedLevelTruthTotality
  RawCodedRestrictedPAConsistencyFormulaCode
  RawCodedTemplateSyntax
  RawCodedTemplateSemantics
  RawCodedTemplatePAEmbedding
  RawCodedTemplateEmbeddedUniversalValidity
  RawCodedTemplateStructuralTranslation
  RawCodedTemplateStructuralPAAgreement
  RawCodedTemplateParameterAbstraction
  RawCodedTemplateDirectStructuralTranslation
  RawCodedRestrictedTargetTemplateContext
  RawCodedRestrictedTargetTemplateSemantics
  RawCodedCarrierRestrictedProofReroot
  RawCodedRestrictedPAConsistencyFromUniversalSoundness
  RawCodedRestrictedPADerivationSoundnessDirectAssumptionCase
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionCase
  RawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftRecursiveChildCompilation
  RawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftDynamicRerootValidity
  RawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftOpenedCoverageValidity
  RawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageValidity
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageDefinitions
  RawCodedRestrictedPADerivationSoundnessRecursiveChildInterface
  RawCodedRestrictedPADerivationSoundnessRecursiveChildEndpointContextInterface
  RawCodedRestrictedPADerivationSoundnessSameContextUnaryChildInterfaceOpenedCoverageSource
  RawCodedProofOrEConstructor
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationCase
  RawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesDefinitions.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageShapeSupport.

(** Each shape certificate imports this one compatibility module.  Keeping
    the broad semantic environment here avoids repeating a fragile list of
    implementation modules in every one-theorem file. *)
Export PA.
Export PAListRepresentability.
Export PAListFormulas.
Export PAHierarchyReduction.
Export PACanonicalSelector.
Export PACanonicalSelectorPA.
Export PAFiniteBetaCoding.
Export PABoundedRawModelCompleteness.
Export PABoundedRawCodedAssignment.
Export PABoundedRawCodedSyntaxConstructors.
Export PABoundedRawCodedFormulaOperations.
Export PABoundedRawCodedProofConstructors.
Export PABoundedRawCodedProofDescent.
Export PABoundedRawCodedProofEndpoints.
Export PABoundedRawCodedProofRules.
Export PABoundedRawCodedProofAtomicAdequacy.
Export PABoundedRawCodedProofFormulaCoverage.
Export PABoundedRawCodedProofRuleCoverage.
Export PABoundedRawCodedRestrictedPAProof.
Export PABoundedRawCodedFixedLevelTruthTotality.
Export PABoundedRawCodedRestrictedPAConsistencyFormulaCode.
Export PABoundedRawCodedTemplateSyntax.
Export PABoundedRawCodedTemplateSemantics.
Export PABoundedRawCodedTemplatePAEmbedding.
Export PABoundedRawCodedTemplateEmbeddedUniversalValidity.
Export PABoundedRawCodedTemplateStructuralTranslation.
Export PABoundedRawCodedTemplateStructuralPAAgreement.
Export PABoundedRawCodedTemplateParameterAbstraction.
Export PABoundedRawCodedTemplateDirectStructuralTranslation.
Export PABoundedRawCodedRestrictedTargetTemplateContext.
Export PABoundedRawCodedRestrictedTargetTemplateSemantics.
Export PABoundedRawCodedCarrierRestrictedProofReroot.
Export PABoundedRawCodedRestrictedPAConsistencyFromUniversalSoundness.
Export PABoundedRawCodedRestrictedPADerivationSoundnessDirectAssumptionCase.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionCase.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftRecursiveChildCompilation.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftDynamicRerootValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrIntroductionLeftOpenedCoverageValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectAndIntroductionOpenedCoverageValidity.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageDefinitions.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessRecursiveChildInterface.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessRecursiveChildEndpointContextInterface.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessSameContextUnaryChildInterfaceOpenedCoverageSource.
Export PABoundedRawCodedProofOrEConstructor.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationCase.
Export
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageSharedShapesDefinitions.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectOrEliminationOpenedCoverageShapeSupport.
