(** Audit for the trace-linked native global-evidence proof boundary. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeGlobalEvidenceRootCompilation.

Import PABoundedRawCodedDynamicTruthNativeGlobalEvidenceRootCompilation.

Check RawDynamicTruthNativeTraceRowParametersAt.
Check raw_dynamicTruthNativeLocalProofTraceAt_exposes_linked_rows.
Check RawDynamicTruthNativeGlobalEvidenceLinkedRowRootInterface.
Check RawDynamicTruthNativeGlobalEvidenceLinkedRowRootCompiler.
Check
  raw_dynamicTruthNativeGlobalEvidenceLinkedRowRootInterface_of_compiler.
Check
  raw_dynamicTruthNativeGlobalEvidenceLinkedRowRoots_of_unlinked_interface.

Check RawDynamicTruthNativeLocalLinkedMatrixResourceCompiler.
Check
  raw_dynamicTruthNativeLocalExclusiveRootOn_of_linked_interfaces.
Check raw_dynamicTruthNativeLocalLeafRootsOn_of_linked_interfaces.
Check
  RawDynamicTruthNativeGlobalEvidenceLinkedRowRootInterfaceAtEmptyBase.
Check raw_dynamicTruthNativeGlobalEvidenceLinkedRowRoots_at_empty_base.
Check
  RawDynamicTruthNativeLocalLinkedEmptyBaseMatrixResourceCompiler.
Check raw_dynamicTruthNativeLocalLinkedMatrixResources_at_empty_base.
Check
  raw_dynamicTruthNativeLocalLeafRootCompiler_of_linked_empty_base_interfaces.
Check raw_dynamicTruthNativeLocalLeafRootCompiler_of_linked_interfaces.

Print Assumptions
  raw_dynamicTruthNativeLocalProofTraceAt_exposes_linked_rows.
Print Assumptions
  raw_dynamicTruthNativeGlobalEvidenceLinkedRowRoots_of_unlinked_interface.
Print Assumptions
  raw_dynamicTruthNativeLocalExclusiveRootOn_of_linked_interfaces.
Print Assumptions raw_dynamicTruthNativeLocalLeafRootsOn_of_linked_interfaces.
Print Assumptions
  raw_dynamicTruthNativeLocalLeafRootCompiler_of_linked_empty_base_interfaces.
Print Assumptions
  raw_dynamicTruthNativeLocalLeafRootCompiler_of_linked_interfaces.
