(** Assumptions audit for predecessor-free non-implication pair production. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalGuardedNonImpPairCompilation.

Import
  PABoundedRawCodedDynamicTruthNativeLocalGuardedNonImpPairCompilation.

Check DynamicTruthBooleanDiagonalCell.
Check DynamicTruthConditionalDiagonalCell.
Check RawDynamicTruthLocalCollisionPairFamilyWithoutConditionalAt.
Check RawDynamicTruthLocalBooleanDiagonalPairRootsAt.
Check RawDynamicTruthNativeLocalNonConditionalResidualInputsAt.
Check RawDynamicTruthLocalNonConditionalCollisionInputsAt.
Check
  raw_dynamicTruthLocalNonConditionalCollisionInputsAt_of_40_helpers.
Check raw_dynamicTruthLocal_sigmaExPiEx_pair_of_nonconditional_inputs.
Check raw_dynamicTruthLocal_sigmaAllPiAll_pair_of_nonconditional_inputs.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutConditionalAt_of_inputs.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutConditionalAt_witnessed_inclusion.
Check
  raw_dynamicTruthLocalBooleanDiagonalPairRootsAt_witnessed_inclusion.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_of_without_conditional_and_boolean.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutConditionalAt_of_without_imp.
Check raw_dynamicTruthLocalBooleanDiagonalPairRootsAt_of_without_imp.
Check raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_iff_split.
Check RawDynamicTruthNativeLocalNonConditionalReducedKernelInputsAt.
Check
  raw_dynamicTruthNativeLocalNonConditionalResidualInputsAt_of_exact_rows_on_witnessed_base.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_of_40_helpers_and_nonconditional_residual.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_of_42_helpers_and_nonconditional_residual.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutConditionalAt_of_42_helpers_on_exact_rows.
Check
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_of_42_helpers_on_exact_rows_and_boolean.

Print Assumptions
  raw_dynamicTruthLocalNonConditionalCollisionInputsAt_of_40_helpers.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamilyWithoutConditionalAt_of_inputs.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamilyWithoutConditionalAt_witnessed_inclusion.
Print Assumptions
  raw_dynamicTruthLocalBooleanDiagonalPairRootsAt_witnessed_inclusion.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_iff_split.
Print Assumptions
  raw_dynamicTruthNativeLocalNonConditionalResidualInputsAt_of_exact_rows_on_witnessed_base.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamilyWithoutConditionalAt_of_42_helpers_on_exact_rows.
Print Assumptions
  raw_dynamicTruthLocalCollisionPairFamilyWithoutImpAt_of_42_helpers_on_exact_rows_and_boolean.
