(** Kernel-facing audit for the literal Imp-I ready child arithmetic roots. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADirectImpIntroductionReadyChildAtomicDomainCompilation.

Import
  PABoundedRawCodedRestrictedPADirectImpIntroductionReadyChildAtomicDomainCompilation.

Check coqRestrictedPADirectImpIntroductionReadyPrefix.
Check coqRestrictedPADirectImpIntroductionReadyDeepAdmissible_shape.
Check coqRestrictedPADirectImpIntroductionReadyChildShape_view.
Check coqRestrictedPADirectImpIntroductionReadyChildGuard_view.
Check coqRestrictedPADirectImpIntroductionReadyChildAtomic_view.
Check coqRestrictedPADirectImpIntroductionReadyChildDomain_view.
Check coqRestrictedPADirectImpIntroductionReadyChildCoreConclusion_shape.
Check coqRestrictedPADirectImpIntroductionReady_deepAdmissible_member.
Check coqRestrictedPADirectImpIntroductionReady_case_member.
Check coqRestrictedPADirectImpIntroductionReadyParentAtomicRoot_valid.
Check coqRestrictedPADirectImpIntroductionReadyParentDomainRoot_valid.
Check coqRestrictedPADirectImpIntroductionReadyChildShapeRoot_valid.
Check coqRestrictedPADirectImpIntroductionReadyChildGuardRoot_valid.
Check
  raw_restrictedPADirectImpIntroductionReadyPrefix_atomically_adequate.
Check
  raw_restrictedPADirectImpIntroduction_readyChild_atomic_and_domain_on_standard_witness_extension.

Print Assumptions
  coqRestrictedPADirectImpIntroductionReadyDeepAdmissible_shape.
Print Assumptions
  coqRestrictedPADirectImpIntroductionReadyChildShapeRoot_valid.
Print Assumptions
  coqRestrictedPADirectImpIntroductionReadyChildGuardRoot_valid.
Print Assumptions
  raw_restrictedPADirectImpIntroduction_readyChild_atomic_and_domain_on_standard_witness_extension.
