From BoundedPAConsistency Require Import
  RawCodedFourStateTableAppendPermutedTemplateGlobalTraversalAssembly.

Import
  PABoundedRawCodedFourStateTableAppendPermutedTemplateGlobalTraversalAssembly.

Check templateOpeningSubstitution.
Check templateUniversalOpenMany_all_many_normal_form.
Check templateExistentialOpenMany_ex_many_normal_form.
Check coqFourStateTableAppendRootTermsSubstitution.
Check coqFourStateTableAppendTemplateGlobalSourceAtRootTerms.
Check coqFourStateTableAppendTemplateGlobalSourceAtRootTerms_reverse.
Check coqFourStateTableAppendOpenedTemplateGlobalFormulaAtRootTerms.
Check coqFourStateTableAppendOpenedTemplateGlobalFormulaAtRootTerms_success.
Check coqFourStateTableAppendOpenedTemplateGlobalRowsAtRootTerms.
Check coqFourStateTableAppendOpenedTemplateGlobalFormulaAtRootTerms_and7_shape.
Check templateTermSubst_eq_rename_of_pointwise.
Check betaLookupVariableRenaming.
Check templateFormulaSubst_codedAssignmentLookup_variables_ext.
Check coqFourStateTableAppendOpenedTemplateGlobalFormulaAtRootTerms_field_shapes.
Check coqFourStateTableAppendOpenedTemplateGlobalFormulaAtRootTerms_shape.
Check coqFourStateTableAppendPermutedTemplateGlobalSource.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula_success.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalRows.
Check coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula_shape.
Check coqFourStateTableAppendOpenedPermutedSharedGlobalRows_eq.
Check
  raw_codedPAGrowingTemplateLocalProofAt_opened_template_global_rows_of_concrete_row_at_root_terms_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_opened_template_global_rows_of_concrete_row_at_root_terms.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_template_global_at_root_terms_of_append_rows_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_template_global_of_append_rows_under_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_template_global_of_append_rows.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_row.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_code_equivalent_row_prefix.
Check
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_and_inherited_row_roots.

Print Assumptions
  templateExistentialOpenMany_ex_many_normal_form.
Print Assumptions
  templateFormulaSubst_codedAssignmentLookup_variables_ext.
Print Assumptions
  coqFourStateTableAppendOpenedTemplateGlobalFormulaAtRootTerms_field_shapes.
Print Assumptions
  coqFourStateTableAppendOpenedTemplateGlobalFormulaAtRootTerms_shape.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_template_global_at_root_terms_of_append_rows_under_prefix.
Print Assumptions
  coqFourStateTableAppendOpenedPermutedTemplateGlobalFormula_shape.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_opened_template_global_rows_of_concrete_row_at_root_terms_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_template_global_of_append_rows_under_prefix.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_template_global_of_append_rows.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_row.
Print Assumptions
  raw_codedPAGrowingTemplateLocalProofAt_dynamic_truth_permuted_shared_successor_global_of_append_and_inherited_row_roots.
