From BoundedPAConsistency Require Import
  RawCodedPALocalProofContextInsertComplete.

Import PABoundedRawCodedPALocalProofContextInsertComplete.

Check raw_adequateUnitFormulaShiftExists_of_compositional.
Check raw_contextInsertUnitShiftSquare_all.
Check raw_codedPALocalProof_contextInsertRootStep_of_compositional.
Check raw_codedPALocalProofContextInsertAt_all_of_compositional.
Check raw_codedPALocalProof_adequateConsTransplant_of_compositional.

Print Assumptions raw_adequateUnitFormulaShiftExists_of_compositional.
Print Assumptions raw_contextInsertUnitShiftSquare_all.
Print Assumptions
  raw_codedPALocalProof_contextInsertRootStep_of_compositional.
Print Assumptions
  raw_codedPALocalProofContextInsertAt_all_of_compositional.
Print Assumptions
  raw_codedPALocalProof_adequateConsTransplant_of_compositional.
