(** Kernel-facing audit of the exact dependency-ordered callback bundle. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeDependencyOrderedCallbackCompilation.

Module
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCallbackCompilationAudit.

Import
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCallbackCompilation.

(** The bundle retains the concrete translation agreement and all six
    explicit arithmetic seams, including the final dynamic-soundness one. *)
Check RawDynamicTruthNativeDependencyOrderedKernelCompilers.
Check RawDynamicTruthNativeDependencyOrderedGrowingKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedSplitPredecessorKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedGrowingProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedAppendProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedPermutedAppendProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedDirectPermutedAppendProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalPermutedAppendProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedDirectLogicalZeroPermutedAppendProofResourceStrongStepKernelCompilers.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalLogicalZeroPermutedAppendProofResourceStrongStepKernelCompilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPermutedAppendProofResourceStrongStepKernelCompilers_of_direct.
Check
  raw_dynamicTruthNativeDependencyOrderedDirectPermutedAppendProofResourceStrongStepKernelCompilers_of_logical_zero.
Check
  raw_dynamicTruthNativeDependencyOrderedStrongStepKernelCompilers_of_proof_resources.
Check
  raw_dynamicTruthNativeDependencyOrderedGrowingProofResourceStrongStepKernelCompilers_of_append_proof_resources.
Check
  raw_dynamicTruthNativeDependencyOrderedGrowingKernelCompilers_of_permuted_append_proof_resources.
Check
  raw_dynamicTruthNativeDependencyOrderedGrowingKernelCompilers_of_fixed.
Check
  raw_dynamicTruthNativeDependencyOrderedGrowingKernelCompilers_of_split_predecessor.
Check
  raw_dynamicTruthNativeDependencyOrderedGrowingKernelCompilers_of_strong_step.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_growing_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_split_predecessor_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_append_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_kernel_compilers.

(** The all-model wrapper is conditional on a per-model translation and
    kernel bundle; the final theorem is therefore not an unconditional
    consistency-provability theorem. *)
Check RawDynamicTruthNativeDependencyOrderedKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedGrowingKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedSplitPredecessorKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedStrongStepKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedProofResourceStrongStepKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedAppendProofResourceStrongStepKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedPermutedAppendProofResourceStrongStepKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedDirectPermutedAppendProofResourceStrongStepKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalPermutedAppendProofResourceStrongStepKernelCompilersInAllModels.
Check
  RawDynamicTruthNativeDependencyOrderedCanonicalLogicalZeroPermutedAppendProofResourceStrongStepKernelCompilersInAllModels.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_growing_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_split_predecessor_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_append_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_direct_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_canonical_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_canonical_logical_zero_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_growing_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_split_predecessor_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_strong_step_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_proof_resource_strong_step_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_append_proof_resource_strong_step_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_direct_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_canonical_permuted_append_proof_resource_strong_step_kernel_compilers.
Check
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_canonical_logical_zero_permuted_append_proof_resource_strong_step_kernel_compilers.

Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedGrowingKernelCompilers_of_fixed.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_growing_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedGrowingKernelCompilers_of_split_predecessor.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_split_predecessor_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedGrowingKernelCompilers_of_strong_step.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_strong_step_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_append_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacks_of_permuted_append_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPermutedAppendProofResourceStrongStepKernelCompilers_of_direct.
Print Assumptions
  raw_dynamicTruthNativeSplicedMasterPositiveComponentSuccessor_of_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedPositiveCallbacksInAllModels_of_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_growing_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_split_predecessor_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_strong_step_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_append_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_permuted_append_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_direct_permuted_append_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_canonical_permuted_append_proof_resource_strong_step_kernel_compilers.
Print Assumptions
  raw_dynamicTruthNativeDependencyOrderedDirectPermutedAppendProofResourceStrongStepKernelCompilers_of_logical_zero.
Print Assumptions
  PA_BProv_compactUniformRestrictedPAConsistencyProvabilityFormula_of_dependency_ordered_canonical_logical_zero_permuted_append_proof_resource_strong_step_kernel_compilers.

End
  PABoundedRawCodedDynamicTruthNativeDependencyOrderedCallbackCompilationAudit.
