(** Surface and assumption audit for the paired global truth shell. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthPairedGlobalSuccessorGraph.

Import PABoundedRawCodedDynamicTruthPairedGlobalSuccessorGraph.

Check dynamicTruthGlobalRowEnvironment_first_thirteen.
Check DynamicTruthGlobalLocalRowScoped.
Check dynamicTruthGlobalRowsFormula_scoped.
Check dynamicTruthGlobalFormula_scoped.

Check dynamicTruthGlobalFormula.
Check dynamicTruthGlobalFormulaCodeTerm.
Check rawDynamicTruthGlobalFormulaCode.
Check raw_eval_dynamicTruthGlobalFormulaCodeTerm.
Check rawDynamicTruthGlobalFormulaCode_quoted.
Check rawDynamicTruthGlobalFormulaCode_atomically_adequate.

Check dynamicTruthPairedGlobalWrapperGraph.
Check RawDynamicTruthPairedGlobalWrapperAt.
Check raw_sat_dynamicTruthPairedGlobalWrapperGraph_iff.
Check dynamicTruthPairedGlobalWrapperGraph_adequacy.

Check dynamicTruthPairedGlobalSuccessorGraph.
Check RawDynamicTruthPairedGlobalSuccessorAt.
Check raw_sat_dynamicTruthPairedGlobalSuccessorGraph_iff.
Check dynamicTruthPairedGlobalSuccessorGraph_raw_adequate_total.

Check dynamicTruthPairedGlobalBaseGraph.
Check RawDynamicTruthPairedGlobalBaseAt.
Check raw_sat_dynamicTruthPairedGlobalBaseGraph_iff.
Check dynamicTruthPairedGlobalBaseGraph_raw_adequate_total.
Check rawDynamicTruthGlobalSigmaBaseCode_quoted.
Check rawDynamicTruthGlobalPiBaseCode_quoted.
Check dynamicTruthPairedGlobalBaseGraph_quoted_representation.
Check dynamicTruthPairedGlobalBaseGraph_quoted.

Check dynamicTruthGlobalRowsFormula_zero_eq.
Check dynamicTruthGlobalTraversalBodyFormula_zero_eq.
Check raw_sat_dynamicTruthGlobalZeroFormula_iff.
Check raw_sat_dynamicTruthGlobalSigmaBaseFormula_native_iff.
Check raw_sat_dynamicTruthGlobalPiBaseFormula_native_iff.

Print Assumptions dynamicTruthGlobalRowEnvironment_first_thirteen.
Print Assumptions dynamicTruthGlobalFormula_scoped.
Print Assumptions rawDynamicTruthGlobalFormulaCode_quoted.
Print Assumptions raw_sat_dynamicTruthPairedGlobalWrapperGraph_iff.
Print Assumptions rawDynamicTruthGlobalFormulaCode_atomically_adequate.
Print Assumptions raw_sat_dynamicTruthPairedGlobalSuccessorGraph_iff.
Print Assumptions dynamicTruthPairedGlobalSuccessorGraph_raw_adequate_total.
Print Assumptions raw_sat_dynamicTruthPairedGlobalBaseGraph_iff.
Print Assumptions dynamicTruthPairedGlobalBaseGraph_raw_adequate_total.
Print Assumptions dynamicTruthPairedGlobalBaseGraph_quoted_representation.
Print Assumptions raw_sat_dynamicTruthGlobalSigmaBaseFormula_native_iff.
Print Assumptions raw_sat_dynamicTruthGlobalPiBaseFormula_native_iff.
