(** Assumption audit for represented beta-lookup functionality compilation. *)

From BoundedPAConsistency Require Import
  RawCodedBetaLookupFunctionalityProofCompilation.

Import PABoundedRawCodedBetaLookupFunctionalityProofCompilation.

Check coqBetaLookupFunctionalityInstanceTemplate.
Check coqBetaLookupFunctionalityFirstLookupTemplate.
Check coqBetaLookupFunctionalitySecondLookupTemplate.
Check coqBetaLookupFunctionalityEqualityTemplate.
Check coqBetaLookupFunctionalityInstanceTemplate_open.
Check CoqBetaLookupFunctionalityArguments.
Check coqBetaLookupFunctionalityReplacementList.
Check coqBetaLookupFunctionalityInstanceOf.
Check coqBetaLookupFunctionalityFirstLookupOf.
Check coqBetaLookupFunctionalitySecondLookupOf.
Check coqBetaLookupFunctionalityEqualityOf.
Check coqBetaLookupFunctionalityInstanceOf_open.
Check coqBetaLookupFunctionalityInstanceOf_shape.
Check coqBetaLookupFunctionalityInstanceTemplate_shape.
Check
  raw_codedPALocalProofOf_beta_lookup_functionality_instance_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_beta_lookup_functionality_instances_on_witnessed_tail.
Check
  raw_codedPALocalProofOf_beta_lookup_functionality_instances_apply.
Check
  raw_codedPALocalProofOf_beta_lookup_functionality_instances_on_witnessed_tail_under_prefix.
Check TemplateAnd4MatchesBetaFunctionalitySide.
Check
  raw_codedPALocalProofOf_beta_lookup_functionality_and4_on_witnessed_tail_under_prefix.
Check
  raw_codedPALocalProofOf_beta_lookup_functionality_on_witnessed_tail_under_prefix.

Print Assumptions coqBetaLookupFunctionalityInstanceTemplate_open.
Print Assumptions coqBetaLookupFunctionalityInstanceOf_open.
Print Assumptions coqBetaLookupFunctionalityInstanceOf_shape.
Print Assumptions coqBetaLookupFunctionalityInstanceTemplate_shape.
Print Assumptions
  raw_codedPALocalProofOf_beta_lookup_functionality_instance_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_beta_lookup_functionality_instances_on_witnessed_tail.
Print Assumptions
  raw_codedPALocalProofOf_beta_lookup_functionality_instances_apply.
Print Assumptions
  raw_codedPALocalProofOf_beta_lookup_functionality_instances_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_beta_lookup_functionality_and4_on_witnessed_tail_under_prefix.
Print Assumptions
  raw_codedPALocalProofOf_beta_lookup_functionality_on_witnessed_tail_under_prefix.
