(** Audit surface for the aligned K-only universal-rule compilers. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessDirectUniversalRulesAlignedTruthProduction.

Module
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalRulesAlignedTruthProductionAudit.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalRulesAlignedTruthProduction.

(** Generic affine-context and growing-witness infrastructure. *)
Check RawCoqRestrictedPADirectStandardWitnessTailCompiler.
Check RawCoqRestrictedPADirectReadyContextStandardWitnessAffine.
Check RawCoqRestrictedPADirectFormulaLocalProofAt.
Check RawCoqRestrictedPADirectFormulaStandardTailCompilerAt.
Check raw_directReadyFormulaRoot_surround_witnessed_tail.
Check raw_standardWitnessTailCompiler_pair.
Check
  raw_directFormulaStandardTailCompilerAt_of_parent_append_concrete_row.
Check raw_directImpChainStandardTailCompilerAt_of_consequence.

(** Exact rule contexts and their aligned parent-source equations. *)
Check coqRestrictedPADirectUniversalIntroductionReadyContext_app_witnesses.
Check coqRestrictedPADirectUniversalEliminationReadyContext_app_witnesses.
Check raw_universalIntroduction_mode_zero_parent_source_aligned.
Check raw_universalElimination_mode_zero_parent_source_aligned.

(** Standalone consequence and law compilers. *)
Check
  RawCoqRestrictedPADirectUniversalIntroductionResultTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectUniversalIntroductionEigenStandardTailCompiler.
Check
  RawCoqRestrictedPADirectUniversalEliminationResultTruthStandardTailCompiler.
Check
  RawCoqRestrictedPADirectUniversalEliminationDynamicTruthStandardTailCompiler.
Check raw_universalIntroductionEigenStandardTailCompiler_of_result_truth.
Check
  raw_universalEliminationDynamicTruthStandardTailCompiler_of_result_truth.
Check
  raw_universalIntroductionResultTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_universalIntroductionEigenStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_universalEliminationResultTruthStandardTailCompiler_of_aligned_append_concrete_row.
Check
  raw_universalEliminationDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.

(** Synchronized pair consumed by later post-And-I continuation assembly. *)
Check RawCoqRestrictedPADirectUniversalKOnlySemanticRoots.
Check
  RawCoqRestrictedPADirectUniversalKOnlySemanticRootsStandardTailCompiler.
Check
  raw_universalIntroductionEigenSemanticRoots_surround_witnessed_tail.
Check
  raw_universalKOnlySemanticRootsStandardTailCompiler_of_standalone.
Check
  raw_universalKOnlySemanticRootsStandardTailCompiler_of_aligned_append_concrete_rows.

Print Assumptions raw_directReadyFormulaRoot_surround_witnessed_tail.
Print Assumptions raw_standardWitnessTailCompiler_pair.
Print Assumptions
  raw_directFormulaStandardTailCompilerAt_of_parent_append_concrete_row.
Print Assumptions raw_directImpChainStandardTailCompilerAt_of_consequence.
Print Assumptions
  coqRestrictedPADirectUniversalIntroductionReadyContext_app_witnesses.
Print Assumptions
  coqRestrictedPADirectUniversalEliminationReadyContext_app_witnesses.
Print Assumptions raw_universalIntroduction_mode_zero_parent_source_aligned.
Print Assumptions raw_universalElimination_mode_zero_parent_source_aligned.
Print Assumptions
  raw_universalIntroductionEigenStandardTailCompiler_of_result_truth.
Print Assumptions
  raw_universalEliminationDynamicTruthStandardTailCompiler_of_result_truth.
Print Assumptions
  raw_universalIntroductionEigenStandardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_universalEliminationDynamicTruthStandardTailCompiler_of_aligned_append_concrete_row.
Print Assumptions
  raw_universalIntroductionEigenSemanticRoots_surround_witnessed_tail.
Print Assumptions
  raw_universalKOnlySemanticRootsStandardTailCompiler_of_standalone.
Print Assumptions
  raw_universalKOnlySemanticRootsStandardTailCompiler_of_aligned_append_concrete_rows.

End
  PABoundedRawCodedRestrictedPADerivationSoundnessDirectUniversalRulesAlignedTruthProductionAudit.
