(** Kernel-facing audit for native local-field proof compilation. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeLocalProofCompilation.

Module PABoundedRawCodedDynamicTruthNativeLocalProofCompilationAudit.

Import PABoundedRawCodedDynamicTruthNativeLocalProofCompilation.

Check rawDynamicTruthNativeLocalAdmissibleContext.
Check rawDynamicTruthNativeLocalExclusiveSigmaContext.
Check rawDynamicTruthNativeLocalExclusivePiContext.
Check RawDynamicTruthNativeLocalDecisionLeafRootAt.
Check RawDynamicTruthNativeLocalExclusiveLeafRootAt.
Check RawDynamicTruthNativeLocalLeafRootsAt.
Check rawDynamicTruthNativeLocalClose3Root.
Check raw_codedPALocalProofOf_dynamicTruthNativeLocal_close3.
Check RawDynamicTruthNativeLocalFieldLocalRootAt.
Check raw_dynamicTruthNativeLocalFieldLocalRootAt_of_leaf_roots.
Check rawDynamicTruthNativeLocalProofCertificate.
Check raw_dynamicTruthNativeLocal_empty_witness_context.
Check raw_codedPAProofOf_dynamicTruthNativeLocalField_of_local_root.
Check raw_codedPAProofOf_dynamicTruthNativeLocalField_of_leaf_roots.
Check RawDynamicTruthNativeLocalProofTraceAt.
Check RawDynamicTruthNativeLocalLeafRootCompiler.
Check raw_dynamicTruthNativeLocalProofTraceAt_of_transform.
Check raw_dynamicTruthNativeLocalDecisionExclusiveProofCompiler_of_leaves.
Check dynamicTruthNativeLocalPositiveGraph_raw_proof_total_of_leaves.

Print Assumptions
  raw_codedPALocalProofOf_dynamicTruthNativeLocal_close3.
Print Assumptions
  raw_dynamicTruthNativeLocalFieldLocalRootAt_of_leaf_roots.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeLocalField_of_local_root.
Print Assumptions
  raw_codedPAProofOf_dynamicTruthNativeLocalField_of_leaf_roots.
Print Assumptions raw_dynamicTruthNativeLocalProofTraceAt_of_transform.
Print Assumptions
  raw_dynamicTruthNativeLocalDecisionExclusiveProofCompiler_of_leaves.
Print Assumptions
  dynamicTruthNativeLocalPositiveGraph_raw_proof_total_of_leaves.

End PABoundedRawCodedDynamicTruthNativeLocalProofCompilationAudit.
