(** Kernel audit for checked strong-prefix finalizer compilation. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerCompilation.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerCompilation.

Check
  coqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorPrefixTemplate.
Check
  coqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorPrefixBodyTemplate.
Check
  coqRestrictedPADerivationSoundnessCarrierFinalizerGuardedPredicateTemplate.
Check
  coqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccTemplate.

Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorPrefixCode.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerGuardedPredicateCode.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccCode.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccCode_quoted.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_successor_substitution.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_member_substitution.

Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerOpenContext.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerOpenContext_selfShift.
Check rawCoqRestrictedPADerivationSoundnessCarrierFinalizerPremiseRoot.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerSuccessorPrefixRoot.
Check
  rawCoqRestrictedPADerivationSoundnessCarrierFinalizerGuardedPredicateRoot.
Check rawCoqRestrictedPADerivationSoundnessCarrierFinalizerPredicateRoot.
Check rawCoqRestrictedPADerivationSoundnessCarrierFinalizerRoot.

Check
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizer_of_ltSelfSucc.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_extendedContext_witnessed.
Check
  coqRestrictedPADerivationSoundnessCarrierFinalizer_ltSelfSucc_bprov.
Check
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizer_ltSelfSucc.
Check
  RawCoqRestrictedPADerivationSoundnessCarrierFinalizerLtSelfSuccRootCompiler.
Check
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizer_from_exact_arithmetic_leaf.
Check
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerRootCompiler_of_ltSelfSucc.

Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_successor_substitution.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizer_prefix_member_substitution.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierFinalizerOpenContext_selfShift.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizer_of_ltSelfSucc.
Print Assumptions
  raw_codedPAProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizer_ltSelfSucc.
Print Assumptions
  raw_codedPALocalProofOf_coqRestrictedPADerivationSoundnessCarrierFinalizer_from_exact_arithmetic_leaf.
Print Assumptions
  raw_coqRestrictedPADerivationSoundnessCarrierStrongPrefixFinalizerRootCompiler_of_ltSelfSucc.
