(** Audit surface for the native axiom/context-truth coherence link. *)

From BoundedPAConsistency Require Import
  RawCodedRestrictedPAAxiomContextTruthNativeDirectCoherenceLink.

Module
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectCoherenceLinkAudit.

Import
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectCoherenceLink.

Check RawCoqRestrictedPANativeContextTruthSelectorLinkAt.
Check RawCoqRestrictedPANativeAxiomContextTruthLinkAt.
Check
  raw_coqRestrictedPANativeAxiomContextTruthLink_exists_of_trace_and_inputs.
Check
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_context_native_link_exists.
Check rawCoqRestrictedPASelectedAxiomContextsTruthDirectCode.
Check raw_coqRestrictedPAAxiomContextsTruthDirectCode_native_view.
Check RawCoqRestrictedPANativeAxiomContextTruthBodyRootCompiler.
Check RawCoqRestrictedPANativeAxiomContextTruthRootCompiler.
Check raw_coqRestrictedPANativeAxiomContextTruthRootCompiler_of_body.
Check
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_context_coherence_exists.
Check
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_context_coherence_exists_of_body.
Check RawDynamicTruthNativeFinalAxiomContextTruthNativeLinkCompiler.
Check RawDynamicTruthNativeFinalSelectedAxiomContextTruthRootCompiler.
Check
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthRootCompiler_of_native_body.
Check
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthDirectCoherenceCompiler_of_native_link.
Check
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthDirectCoherenceCompiler_of_native_body.

Print Assumptions
  raw_coqRestrictedPANativeAxiomContextTruthLink_exists_of_trace_and_inputs.
Print Assumptions
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_context_native_link_exists.
Print Assumptions
  raw_coqRestrictedPAAxiomContextsTruthDirectCode_native_view.
Print Assumptions
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_context_coherence_exists.
Print Assumptions
  raw_dynamicTruthNativeFinalStagedGraphTrace_axiom_context_coherence_exists_of_body.
Print Assumptions
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthDirectCoherenceCompiler_of_native_link.
Print Assumptions
  raw_dynamicTruthNativeFinalSelectedAxiomContextTruthDirectCoherenceCompiler_of_native_body.

End
  PABoundedRawCodedRestrictedPAAxiomContextTruthNativeDirectCoherenceLinkAudit.
