(** Surface and assumption audit for the standard-carrier cross-level bridge. *)

From BoundedPAConsistency Require Import
  RawCodedDynamicTruthNativeCrossLevelStandardProofBridge.

Module PABoundedRawCodedDynamicTruthNativeCrossLevelStandardProofBridgeAudit.

Import PABoundedRawCodedDynamicTruthNativeCrossLevelStandardProofBridge.

Check rawDynamicTruthNativeCrossLevelStandardFieldCode.
Check raw_dynamicTruthNativeCrossLevelStandardFieldCode_eq_quoted_fixedLevel_coherence.
Check RawDynamicTruthNativeCrossLevelStandardFieldProofCompiler.
Check raw_dynamicTruthNativeCrossLevelStandardFieldProofCompiler_of_PA.
Check RawDynamicTruthNativeCrossLevelStandardCanonicalOutputAt.
Check RawDynamicTruthNativeCrossLevelStandardCanonicalOutputProofCompiler.
Check
  raw_dynamicTruthNativeCrossLevelStandardCanonicalOutputProofCompiler_of_PA.
Check RawDynamicTruthNativeCrossLevelStandardCoherenceProofCompiler.
Check raw_dynamicTruthNativeCrossLevelStandardCoherenceProofCompiler_of_PA.
Check RawDynamicTruthNativeCrossLevelStandardCarrierTraceAt.
Check raw_dynamicTruthNativeCrossLevelStandardCarrierTraceAt_proof_of_PA.

Print Assumptions
  raw_dynamicTruthNativeCrossLevelStandardFieldProofCompiler_of_PA.
Print Assumptions
  raw_dynamicTruthNativeCrossLevelStandardCanonicalOutputProofCompiler_of_PA.
Print Assumptions
  raw_dynamicTruthNativeCrossLevelStandardCoherenceProofCompiler_of_PA.
Print Assumptions
  raw_dynamicTruthNativeCrossLevelStandardCarrierTraceAt_proof_of_PA.

End PABoundedRawCodedDynamicTruthNativeCrossLevelStandardProofBridgeAudit.
