From BoundedPAConsistency Require Import
  RawCodedRestrictedPADerivationSoundnessAssumptionFinalWitnessComposition.

Import
  PABoundedRawCodedRestrictedPADerivationSoundnessAssumptionFinalWitnessComposition.

Check coqRestrictedPADirectAssumptionTransferInstanceRoot.
Check coqRestrictedPADirectAssumptionShiftedFinalContextBody_shape.
Check coqRestrictedPADirectAssumption_shifted_context_body_in.
Check coqRestrictedPADirectAssumptionTransferredMembershipRoot.
Check coqRestrictedPADirectAssumptionFinalWitnessRoot.
Check coqRestrictedPADirectAssumptionFinalWitnessRoot_derives.

Print Assumptions coqRestrictedPADirectAssumptionFinalWitnessRoot_derives.
Print Assumptions
  coqRestrictedPADirectAssumptionShiftedFinalContextBody_shape.
