import PolynomialFormulas

/-! Kernel-assumption audit for the solver theorems and the Abel--Ruffini obstruction. -/

open LeanProofs.PolynomialFormulas

#check solveLinear_correct
#check solveQuadratic_correct
#check cardano_formula
#check solveCubic_correct
#check ferrari_parameters_of_resolvent
#check solveQuartic_correct
#check solveCubic_exhaustive
#check solveQuartic_exhaustive
#check cubic_eq_zero_iff
#check quartic_eq_zero_iff
#check RadicalExpression.eval_mem_solvableByRad
#check RadicalExpression.nonempty_iff_mem_solvableByRad
#check hasCompleteRadicalSolution_sound
#check hasCompleteRadicalSolution_iff
#check abelRuffiniQuintic_irreducible
#check abelRuffiniQuintic_root_not_solvableByRad
#check abelRuffiniQuintic_not_completelySolvableByRadicals
#check paddedAbelRuffiniPolynomial_natDegree
#check paddedAbelRuffiniPolynomial_not_completelySolvableByRadicals
#check exists_incomplete_radical_polynomial_of_degree
#check no_universal_complete_radical_solution
#check no_universal_radical_formula_of_degree_gt_four
#check no_universal_complete_solvability_by_radicals
#check QuinticRadicalComputability.encodedCriterion_primrec
#check QuinticRadicalComputability.computablePred_of_primrec_criterion
#check QuinticRadicalComputability.has_partrec_code
#check QuinticRadicalComputability.has_turing_code
#check QuinticRadicalComputability.has_turing_machine
#check QuinticRadicalComputability.has_turing_machine_of_primrec_criterion
#check QuinticRadicalComputability.encodedCriterion_accepts_iff
#check QuinticRadicalComputability.has_verified_turing_machine_of_primrec_criterion
#check ComputableDummitCoefficients.dummitTable
#check ComputableDummitCoefficients.explicitDummitCoefficients
#check ComputableDummitCoefficients.normalized_table_certificate
#check ComputableDummitCoefficients.dummitTable_eval_elementaryTuple
#check ComputableDummitCoefficients.listRootCoefficient_eq_scalarResolvent_coeff
#check ComputableDummitCoefficients.toMvPolynomial_dummitTable_eq_elementaryResolventCoefficient
#check ComputableDummitCoefficients.explicitDummitCoefficients_eq_dummitCoefficients
#check ComputableDummitCoefficients.explicitDummitCoefficients_apply_primrec
#check ComputableDummitCoefficients.explicitDummitCoefficients_primrec
#check ComputableDummitCoefficients.explicitDummitCoefficients_six
#check QuinticRadicalDecision.dummitCriterion_correct
#check QuinticRadicalDecision.quinticRadicalDecision_primrec
#check QuinticRadicalDecision.quinticRadicalDecision_correct
#check QuinticRadicalDecision.allRootsRadical_computablePred
#check QuinticRadicalDecision.has_verified_quinticRadicalDecision_turingMachine
#check SelmerAbelRuffini.iSup_inertia_eq_top
#synth NumberField (SelmerAbelRuffini.splittingField 5)
#check SelmerAbelRuffini.pQ_gal_not_solvable
#check SelmerAbelRuffini.pQ_rootSet_complex_card
#check SelmerAbelRuffini.every_complex_root_not_solvableByRad
#check SelmerAbelRuffini.every_complex_root_has_no_radical_expression
#check SelmerAbelRuffini.selmer_all_complex_roots
#check SelmerAbelRuffini.every_degree_gt_four_has_rational_polynomial_with_no_radical_root
#check GenericAbelRuffini.p_natDegree
#check GenericAbelRuffini.p_rootSet_card
#check GenericAbelRuffini.galEquivPerm
#check GenericAbelRuffini.every_root_not_solvableByRad
#check GenericAbelRuffini.generic_unsolvable_polynomial
#check GenericAbelRuffini.every_degree_gt_four_has_polynomial_with_no_radical_root

#print axioms solveLinear_correct
#print axioms solveQuadratic_correct
#print axioms cardano_formula
#print axioms solveCubic_correct
#print axioms ferrari_parameters_of_resolvent
#print axioms solveQuartic_correct
#print axioms solveCubic_exhaustive
#print axioms solveQuartic_exhaustive
#print axioms cubic_eq_zero_iff
#print axioms quartic_eq_zero_iff
#print axioms RadicalExpression.eval_mem_solvableByRad
#print axioms RadicalExpression.nonempty_iff_mem_solvableByRad
#print axioms hasCompleteRadicalSolution_sound
#print axioms hasCompleteRadicalSolution_iff
#print axioms abelRuffiniQuintic_irreducible
#print axioms abelRuffiniQuintic_root_not_solvableByRad
#print axioms abelRuffiniQuintic_not_completelySolvableByRadicals
#print axioms paddedAbelRuffiniPolynomial_natDegree
#print axioms paddedAbelRuffiniPolynomial_not_completelySolvableByRadicals
#print axioms exists_incomplete_radical_polynomial_of_degree
#print axioms no_universal_complete_radical_solution
#print axioms no_universal_radical_formula_of_degree_gt_four
#print axioms no_universal_complete_solvability_by_radicals
#print axioms QuinticRadicalComputability.encodedCriterion_primrec
#print axioms QuinticRadicalComputability.computablePred_of_primrec_criterion
#print axioms QuinticRadicalComputability.has_partrec_code
#print axioms QuinticRadicalComputability.has_turing_code
#print axioms QuinticRadicalComputability.has_turing_machine
#print axioms QuinticRadicalComputability.has_turing_machine_of_primrec_criterion
#print axioms QuinticRadicalComputability.encodedCriterion_accepts_iff
#print axioms QuinticRadicalComputability.has_verified_turing_machine_of_primrec_criterion
#print axioms ComputableDummitCoefficients.normalized_table_certificate
#print axioms ComputableDummitCoefficients.dummitTable_eval_elementaryTuple
#print axioms ComputableDummitCoefficients.listRootCoefficient_eq_scalarResolvent_coeff
#print axioms ComputableDummitCoefficients.toMvPolynomial_dummitTable_eq_elementaryResolventCoefficient
#print axioms ComputableDummitCoefficients.explicitDummitCoefficients_eq_dummitCoefficients
#print axioms ComputableDummitCoefficients.explicitDummitCoefficients_primrec
#print axioms QuinticRadicalDecision.dummitCriterion_correct
#print axioms QuinticRadicalDecision.quinticRadicalDecision_primrec
#print axioms QuinticRadicalDecision.quinticRadicalDecision_correct
#print axioms QuinticRadicalDecision.allRootsRadical_computablePred
#print axioms QuinticRadicalDecision.has_verified_quinticRadicalDecision_turingMachine
#print axioms SelmerAbelRuffini.iSup_inertia_eq_top
#print axioms SelmerAbelRuffini.pQ_gal_not_solvable
#print axioms SelmerAbelRuffini.pQ_rootSet_complex_card
#print axioms SelmerAbelRuffini.every_complex_root_not_solvableByRad
#print axioms SelmerAbelRuffini.every_complex_root_has_no_radical_expression
#print axioms SelmerAbelRuffini.selmer_all_complex_roots
#print axioms SelmerAbelRuffini.every_degree_gt_four_has_rational_polynomial_with_no_radical_root
#print axioms GenericAbelRuffini.p_natDegree
#print axioms GenericAbelRuffini.p_rootSet_card
#print axioms GenericAbelRuffini.galEquivPerm
#print axioms GenericAbelRuffini.every_root_not_solvableByRad
#print axioms GenericAbelRuffini.generic_unsolvable_polynomial
#print axioms GenericAbelRuffini.every_degree_gt_four_has_polynomial_with_no_radical_root
