import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2Data

import PolynomialFormulas.ComputableDummitKernelCertificateFlattenBucketsAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix2FlattenChunk7Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term125_state7_normalize_radix2flatten_certificate :
    SparsePolynomial.flattenBuckets table0Term125State7NormalizeRadix2BucketsNormal = table0Term125State7NormalizeRadix2Normal := by
  change SparsePolynomial.flattenBuckets (table0Term125State7NormalizeRadix2FlattenChunk0BucketsNormal ++ (table0Term125State7NormalizeRadix2FlattenChunk1BucketsNormal ++ (table0Term125State7NormalizeRadix2FlattenChunk2BucketsNormal ++ (table0Term125State7NormalizeRadix2FlattenChunk3BucketsNormal ++ (table0Term125State7NormalizeRadix2FlattenChunk4BucketsNormal ++ (table0Term125State7NormalizeRadix2FlattenChunk5BucketsNormal ++ (table0Term125State7NormalizeRadix2FlattenChunk6BucketsNormal ++ table0Term125State7NormalizeRadix2FlattenChunk7BucketsNormal))))))) =
    (table0Term125State7NormalizeRadix2FlattenChunk0Normal ++ (table0Term125State7NormalizeRadix2FlattenChunk1Normal ++ (table0Term125State7NormalizeRadix2FlattenChunk2Normal ++ (table0Term125State7NormalizeRadix2FlattenChunk3Normal ++ (table0Term125State7NormalizeRadix2FlattenChunk4Normal ++ (table0Term125State7NormalizeRadix2FlattenChunk5Normal ++ (table0Term125State7NormalizeRadix2FlattenChunk6Normal ++ table0Term125State7NormalizeRadix2FlattenChunk7Normal)))))))
  rw [flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, table0_term125_state7_normalize_radix2_flatten_chunk0_certificate, table0_term125_state7_normalize_radix2_flatten_chunk1_certificate, table0_term125_state7_normalize_radix2_flatten_chunk2_certificate, table0_term125_state7_normalize_radix2_flatten_chunk3_certificate, table0_term125_state7_normalize_radix2_flatten_chunk4_certificate, table0_term125_state7_normalize_radix2_flatten_chunk5_certificate, table0_term125_state7_normalize_radix2_flatten_chunk6_certificate, table0_term125_state7_normalize_radix2_flatten_chunk7_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
