import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term72State9NormalizeRadix0BucketsNormal : List SparsePolynomial :=
  (table0Term72State9NormalizeRadix0FlattenChunk0BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk1BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk2BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk3BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk4BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk5BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk6BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk7BucketsNormal ++ (table0Term72State9NormalizeRadix0FlattenChunk8BucketsNormal ++ table0Term72State9NormalizeRadix0FlattenChunk9BucketsNormal)))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
