import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawLeftSplitCertificate

import PolynomialFormulas.ComputableDummitKernelCertificateRawMulAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk9Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk10Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk11Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk12Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk13Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk14Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk15Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk16Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk17Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk18Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk19Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk20Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk21Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk22Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk23Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk24Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk25Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk26Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk27Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk28Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk29Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk30Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk31Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk32Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk33Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk34Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk35Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk36Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term87_state9_normalize_raw_certificate :
    SparsePolynomial.rawMul table0Term87State8Normal (elementaryPolynomials 3) = table0Term87State9NormalizeRawNormal := by
  rw [table0_term87_state9_normalize_rawleftsplit_certificate]
  change SparsePolynomial.rawMul (table0Term87State9NormalizeRawLeftChunk0Normal ++ (table0Term87State9NormalizeRawLeftChunk1Normal ++ (table0Term87State9NormalizeRawLeftChunk2Normal ++ (table0Term87State9NormalizeRawLeftChunk3Normal ++ (table0Term87State9NormalizeRawLeftChunk4Normal ++ (table0Term87State9NormalizeRawLeftChunk5Normal ++ (table0Term87State9NormalizeRawLeftChunk6Normal ++ (table0Term87State9NormalizeRawLeftChunk7Normal ++ (table0Term87State9NormalizeRawLeftChunk8Normal ++ (table0Term87State9NormalizeRawLeftChunk9Normal ++ (table0Term87State9NormalizeRawLeftChunk10Normal ++ (table0Term87State9NormalizeRawLeftChunk11Normal ++ (table0Term87State9NormalizeRawLeftChunk12Normal ++ (table0Term87State9NormalizeRawLeftChunk13Normal ++ (table0Term87State9NormalizeRawLeftChunk14Normal ++ (table0Term87State9NormalizeRawLeftChunk15Normal ++ (table0Term87State9NormalizeRawLeftChunk16Normal ++ (table0Term87State9NormalizeRawLeftChunk17Normal ++ (table0Term87State9NormalizeRawLeftChunk18Normal ++ (table0Term87State9NormalizeRawLeftChunk19Normal ++ (table0Term87State9NormalizeRawLeftChunk20Normal ++ (table0Term87State9NormalizeRawLeftChunk21Normal ++ (table0Term87State9NormalizeRawLeftChunk22Normal ++ (table0Term87State9NormalizeRawLeftChunk23Normal ++ (table0Term87State9NormalizeRawLeftChunk24Normal ++ (table0Term87State9NormalizeRawLeftChunk25Normal ++ (table0Term87State9NormalizeRawLeftChunk26Normal ++ (table0Term87State9NormalizeRawLeftChunk27Normal ++ (table0Term87State9NormalizeRawLeftChunk28Normal ++ (table0Term87State9NormalizeRawLeftChunk29Normal ++ (table0Term87State9NormalizeRawLeftChunk30Normal ++ (table0Term87State9NormalizeRawLeftChunk31Normal ++ (table0Term87State9NormalizeRawLeftChunk32Normal ++ (table0Term87State9NormalizeRawLeftChunk33Normal ++ (table0Term87State9NormalizeRawLeftChunk34Normal ++ (table0Term87State9NormalizeRawLeftChunk35Normal ++ table0Term87State9NormalizeRawLeftChunk36Normal)))))))))))))))))))))))))))))))))))) (elementaryPolynomials 3) = (table0Term87State9NormalizeRawChunk0Normal ++ (table0Term87State9NormalizeRawChunk1Normal ++ (table0Term87State9NormalizeRawChunk2Normal ++ (table0Term87State9NormalizeRawChunk3Normal ++ (table0Term87State9NormalizeRawChunk4Normal ++ (table0Term87State9NormalizeRawChunk5Normal ++ (table0Term87State9NormalizeRawChunk6Normal ++ (table0Term87State9NormalizeRawChunk7Normal ++ (table0Term87State9NormalizeRawChunk8Normal ++ (table0Term87State9NormalizeRawChunk9Normal ++ (table0Term87State9NormalizeRawChunk10Normal ++ (table0Term87State9NormalizeRawChunk11Normal ++ (table0Term87State9NormalizeRawChunk12Normal ++ (table0Term87State9NormalizeRawChunk13Normal ++ (table0Term87State9NormalizeRawChunk14Normal ++ (table0Term87State9NormalizeRawChunk15Normal ++ (table0Term87State9NormalizeRawChunk16Normal ++ (table0Term87State9NormalizeRawChunk17Normal ++ (table0Term87State9NormalizeRawChunk18Normal ++ (table0Term87State9NormalizeRawChunk19Normal ++ (table0Term87State9NormalizeRawChunk20Normal ++ (table0Term87State9NormalizeRawChunk21Normal ++ (table0Term87State9NormalizeRawChunk22Normal ++ (table0Term87State9NormalizeRawChunk23Normal ++ (table0Term87State9NormalizeRawChunk24Normal ++ (table0Term87State9NormalizeRawChunk25Normal ++ (table0Term87State9NormalizeRawChunk26Normal ++ (table0Term87State9NormalizeRawChunk27Normal ++ (table0Term87State9NormalizeRawChunk28Normal ++ (table0Term87State9NormalizeRawChunk29Normal ++ (table0Term87State9NormalizeRawChunk30Normal ++ (table0Term87State9NormalizeRawChunk31Normal ++ (table0Term87State9NormalizeRawChunk32Normal ++ (table0Term87State9NormalizeRawChunk33Normal ++ (table0Term87State9NormalizeRawChunk34Normal ++ (table0Term87State9NormalizeRawChunk35Normal ++ table0Term87State9NormalizeRawChunk36Normal))))))))))))))))))))))))))))))))))))
  rw [rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, table0_term87_state9_normalize_raw_chunk0_certificate, table0_term87_state9_normalize_raw_chunk1_certificate, table0_term87_state9_normalize_raw_chunk2_certificate, table0_term87_state9_normalize_raw_chunk3_certificate, table0_term87_state9_normalize_raw_chunk4_certificate, table0_term87_state9_normalize_raw_chunk5_certificate, table0_term87_state9_normalize_raw_chunk6_certificate, table0_term87_state9_normalize_raw_chunk7_certificate, table0_term87_state9_normalize_raw_chunk8_certificate, table0_term87_state9_normalize_raw_chunk9_certificate, table0_term87_state9_normalize_raw_chunk10_certificate, table0_term87_state9_normalize_raw_chunk11_certificate, table0_term87_state9_normalize_raw_chunk12_certificate, table0_term87_state9_normalize_raw_chunk13_certificate, table0_term87_state9_normalize_raw_chunk14_certificate, table0_term87_state9_normalize_raw_chunk15_certificate, table0_term87_state9_normalize_raw_chunk16_certificate, table0_term87_state9_normalize_raw_chunk17_certificate, table0_term87_state9_normalize_raw_chunk18_certificate, table0_term87_state9_normalize_raw_chunk19_certificate, table0_term87_state9_normalize_raw_chunk20_certificate, table0_term87_state9_normalize_raw_chunk21_certificate, table0_term87_state9_normalize_raw_chunk22_certificate, table0_term87_state9_normalize_raw_chunk23_certificate, table0_term87_state9_normalize_raw_chunk24_certificate, table0_term87_state9_normalize_raw_chunk25_certificate, table0_term87_state9_normalize_raw_chunk26_certificate, table0_term87_state9_normalize_raw_chunk27_certificate, table0_term87_state9_normalize_raw_chunk28_certificate, table0_term87_state9_normalize_raw_chunk29_certificate, table0_term87_state9_normalize_raw_chunk30_certificate, table0_term87_state9_normalize_raw_chunk31_certificate, table0_term87_state9_normalize_raw_chunk32_certificate, table0_term87_state9_normalize_raw_chunk33_certificate, table0_term87_state9_normalize_raw_chunk34_certificate, table0_term87_state9_normalize_raw_chunk35_certificate, table0_term87_state9_normalize_raw_chunk36_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
