import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRadix0BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRadix1Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state9_normalize_radix0bucketize_certificate :
    SparsePolynomial.bucketize (fun t ↦ t.powers.p0) table0Term87State9NormalizeRadix1Normal = table0Term87State9NormalizeRadix0BucketsNormal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
