import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRadix0FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state9_normalize_radix0_flatten_chunk9_certificate :
    SparsePolynomial.flattenBuckets table0Term87State9NormalizeRadix0FlattenChunk9BucketsNormal = table0Term87State9NormalizeRadix0FlattenChunk9Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
