import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term131State7NormalizeRadix2Normal : SparsePolynomial :=
  (table0Term131State7NormalizeRadix2FlattenChunk0Normal ++ (table0Term131State7NormalizeRadix2FlattenChunk1Normal ++ (table0Term131State7NormalizeRadix2FlattenChunk2Normal ++ (table0Term131State7NormalizeRadix2FlattenChunk3Normal ++ (table0Term131State7NormalizeRadix2FlattenChunk4Normal ++ (table0Term131State7NormalizeRadix2FlattenChunk5Normal ++ (table0Term131State7NormalizeRadix2FlattenChunk6Normal ++ table0Term131State7NormalizeRadix2FlattenChunk7Normal)))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
