import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State8NormalizeRawLeftChunk17Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State8NormalizeRawChunk17Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term86_state8_normalize_raw_chunk17_certificate :
    SparsePolynomial.rawMul table0Term86State8NormalizeRawLeftChunk17Normal (elementaryPolynomials 2) = table0Term86State8NormalizeRawChunk17Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
