import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State7NormalizeRadix3FlattenChunk1Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term110_state7_normalize_radix3_flatten_chunk1_certificate :
    SparsePolynomial.flattenBuckets table0Term110State7NormalizeRadix3FlattenChunk1BucketsNormal = table0Term110State7NormalizeRadix3FlattenChunk1Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
