import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term120State2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term120State1Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term120_state2_certificate :
    SparsePolynomial.mul table0Term120State1Normal (elementaryPolynomials 1) = table0Term120State2Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
