import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term86_state9_certificate :
    SparsePolynomial.mul table0Term86State8Normal (elementaryPolynomials 4) = table0Term86Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
