import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRawLeftChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRawChunk6Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term125_state7_normalize_raw_chunk6_certificate :
    SparsePolynomial.rawMul table0Term125State7NormalizeRawLeftChunk6Normal (elementaryPolynomials 2) = table0Term125State7NormalizeRawChunk6Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
