import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term109_certificate :
    SparseTerm.substitute ⟨-4, ⟨0, 6, 0, 3, 0⟩⟩ elementaryPolynomials = table0Term109Normal := by
  change SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.const (-4)) (elementaryPolynomials 1)) (elementaryPolynomials 1)) (elementaryPolynomials 1)) (elementaryPolynomials 1)) (elementaryPolynomials 1)) (elementaryPolynomials 1)) (elementaryPolynomials 3)) (elementaryPolynomials 3)) (elementaryPolynomials 3) = table0Term109Normal
  rw [table0_term109_state0_certificate, table0_term109_state1_certificate, table0_term109_state2_certificate, table0_term109_state3_certificate, table0_term109_state4_certificate, table0_term109_state5_certificate, table0_term109_state6_certificate, table0_term109_state7_certificate, table0_term109_state8_certificate, table0_term109_state9_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
