import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix1FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term111State7NormalizeRadix1Normal : SparsePolynomial :=
  (table0Term111State7NormalizeRadix1FlattenChunk0Normal ++ (table0Term111State7NormalizeRadix1FlattenChunk1Normal ++ (table0Term111State7NormalizeRadix1FlattenChunk2Normal ++ (table0Term111State7NormalizeRadix1FlattenChunk3Normal ++ (table0Term111State7NormalizeRadix1FlattenChunk4Normal ++ (table0Term111State7NormalizeRadix1FlattenChunk5Normal ++ (table0Term111State7NormalizeRadix1FlattenChunk6Normal ++ table0Term111State7NormalizeRadix1FlattenChunk7Normal)))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
