import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3Data

import PolynomialFormulas.ComputableDummitKernelCertificateFlattenBucketsAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk8Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term109_state8_normalize_radix3flatten_certificate :
    SparsePolynomial.flattenBuckets table0Term109State8NormalizeRadix3BucketsNormal = table0Term109State8NormalizeRadix3Normal := by
  change SparsePolynomial.flattenBuckets (table0Term109State8NormalizeRadix3FlattenChunk0BucketsNormal ++ (table0Term109State8NormalizeRadix3FlattenChunk1BucketsNormal ++ (table0Term109State8NormalizeRadix3FlattenChunk2BucketsNormal ++ (table0Term109State8NormalizeRadix3FlattenChunk3BucketsNormal ++ (table0Term109State8NormalizeRadix3FlattenChunk4BucketsNormal ++ (table0Term109State8NormalizeRadix3FlattenChunk5BucketsNormal ++ (table0Term109State8NormalizeRadix3FlattenChunk6BucketsNormal ++ (table0Term109State8NormalizeRadix3FlattenChunk7BucketsNormal ++ table0Term109State8NormalizeRadix3FlattenChunk8BucketsNormal)))))))) =
    (table0Term109State8NormalizeRadix3FlattenChunk0Normal ++ (table0Term109State8NormalizeRadix3FlattenChunk1Normal ++ (table0Term109State8NormalizeRadix3FlattenChunk2Normal ++ (table0Term109State8NormalizeRadix3FlattenChunk3Normal ++ (table0Term109State8NormalizeRadix3FlattenChunk4Normal ++ (table0Term109State8NormalizeRadix3FlattenChunk5Normal ++ (table0Term109State8NormalizeRadix3FlattenChunk6Normal ++ (table0Term109State8NormalizeRadix3FlattenChunk7Normal ++ table0Term109State8NormalizeRadix3FlattenChunk8Normal))))))))
  rw [flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, table0_term109_state8_normalize_radix3_flatten_chunk0_certificate, table0_term109_state8_normalize_radix3_flatten_chunk1_certificate, table0_term109_state8_normalize_radix3_flatten_chunk2_certificate, table0_term109_state8_normalize_radix3_flatten_chunk3_certificate, table0_term109_state8_normalize_radix3_flatten_chunk4_certificate, table0_term109_state8_normalize_radix3_flatten_chunk5_certificate, table0_term109_state8_normalize_radix3_flatten_chunk6_certificate, table0_term109_state8_normalize_radix3_flatten_chunk7_certificate, table0_term109_state8_normalize_radix3_flatten_chunk8_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
