import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term71State8NormalizeRadix3BucketsNormal : List SparsePolynomial :=
  (table0Term71State8NormalizeRadix3FlattenChunk0BucketsNormal ++ (table0Term71State8NormalizeRadix3FlattenChunk1BucketsNormal ++ (table0Term71State8NormalizeRadix3FlattenChunk2BucketsNormal ++ (table0Term71State8NormalizeRadix3FlattenChunk3BucketsNormal ++ (table0Term71State8NormalizeRadix3FlattenChunk4BucketsNormal ++ (table0Term71State8NormalizeRadix3FlattenChunk5BucketsNormal ++ (table0Term71State8NormalizeRadix3FlattenChunk6BucketsNormal ++ (table0Term71State8NormalizeRadix3FlattenChunk7BucketsNormal ++ table0Term71State8NormalizeRadix3FlattenChunk8BucketsNormal))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
