import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRawLeftChunk15Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRawChunk15Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term110_state8_normalize_raw_chunk15_certificate :
    SparsePolynomial.rawMul table0Term110State8NormalizeRawLeftChunk15Normal (elementaryPolynomials 2) = table0Term110State8NormalizeRawChunk15Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
