import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRadix3BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRadix4Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term90_state9_normalize_radix3bucketize_certificate :
    SparsePolynomial.bucketize (fun t ↦ t.powers.p3) table0Term90State9NormalizeRadix4Normal = table0Term90State9NormalizeRadix3BucketsNormal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
