import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix1FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term72_state7_normalize_radix1_flatten_chunk7_certificate :
    SparsePolynomial.flattenBuckets table0Term72State7NormalizeRadix1FlattenChunk7BucketsNormal = table0Term72State7NormalizeRadix1FlattenChunk7Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
