import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term51State2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term51State1Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term51_state2_certificate :
    SparsePolynomial.mul table0Term51State1Normal (elementaryPolynomials 0) = table0Term51State2Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
