import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawLeftSplitCertificate

import PolynomialFormulas.ComputableDummitKernelCertificateRawMulAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk9Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk10Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk11Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk12Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term86_state7_normalize_raw_certificate :
    SparsePolynomial.rawMul table0Term86State6Normal (elementaryPolynomials 2) = table0Term86State7NormalizeRawNormal := by
  rw [table0_term86_state7_normalize_rawleftsplit_certificate]
  change SparsePolynomial.rawMul (table0Term86State7NormalizeRawLeftChunk0Normal ++ (table0Term86State7NormalizeRawLeftChunk1Normal ++ (table0Term86State7NormalizeRawLeftChunk2Normal ++ (table0Term86State7NormalizeRawLeftChunk3Normal ++ (table0Term86State7NormalizeRawLeftChunk4Normal ++ (table0Term86State7NormalizeRawLeftChunk5Normal ++ (table0Term86State7NormalizeRawLeftChunk6Normal ++ (table0Term86State7NormalizeRawLeftChunk7Normal ++ (table0Term86State7NormalizeRawLeftChunk8Normal ++ (table0Term86State7NormalizeRawLeftChunk9Normal ++ (table0Term86State7NormalizeRawLeftChunk10Normal ++ (table0Term86State7NormalizeRawLeftChunk11Normal ++ table0Term86State7NormalizeRawLeftChunk12Normal)))))))))))) (elementaryPolynomials 2) = (table0Term86State7NormalizeRawChunk0Normal ++ (table0Term86State7NormalizeRawChunk1Normal ++ (table0Term86State7NormalizeRawChunk2Normal ++ (table0Term86State7NormalizeRawChunk3Normal ++ (table0Term86State7NormalizeRawChunk4Normal ++ (table0Term86State7NormalizeRawChunk5Normal ++ (table0Term86State7NormalizeRawChunk6Normal ++ (table0Term86State7NormalizeRawChunk7Normal ++ (table0Term86State7NormalizeRawChunk8Normal ++ (table0Term86State7NormalizeRawChunk9Normal ++ (table0Term86State7NormalizeRawChunk10Normal ++ (table0Term86State7NormalizeRawChunk11Normal ++ table0Term86State7NormalizeRawChunk12Normal))))))))))))
  rw [rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, table0_term86_state7_normalize_raw_chunk0_certificate, table0_term86_state7_normalize_raw_chunk1_certificate, table0_term86_state7_normalize_raw_chunk2_certificate, table0_term86_state7_normalize_raw_chunk3_certificate, table0_term86_state7_normalize_raw_chunk4_certificate, table0_term86_state7_normalize_raw_chunk5_certificate, table0_term86_state7_normalize_raw_chunk6_certificate, table0_term86_state7_normalize_raw_chunk7_certificate, table0_term86_state7_normalize_raw_chunk8_certificate, table0_term86_state7_normalize_raw_chunk9_certificate, table0_term86_state7_normalize_raw_chunk10_certificate, table0_term86_state7_normalize_raw_chunk11_certificate, table0_term86_state7_normalize_raw_chunk12_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
