import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRadix0FlattenChunk1Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state9_normalize_radix0_flatten_chunk1_certificate :
    SparsePolynomial.flattenBuckets table0Term87State9NormalizeRadix0FlattenChunk1BucketsNormal = table0Term87State9NormalizeRadix0FlattenChunk1Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
