import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term72_certificate :
    SparseTerm.substitute ⟨5, ⟨2, 1, 4, 2, 0⟩⟩ elementaryPolynomials = table0Term72Normal := by
  change SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.const (5)) (elementaryPolynomials 0)) (elementaryPolynomials 0)) (elementaryPolynomials 1)) (elementaryPolynomials 2)) (elementaryPolynomials 2)) (elementaryPolynomials 2)) (elementaryPolynomials 2)) (elementaryPolynomials 3)) (elementaryPolynomials 3) = table0Term72Normal
  rw [table0_term72_state0_certificate, table0_term72_state1_certificate, table0_term72_state2_certificate, table0_term72_state3_certificate, table0_term72_state4_certificate, table0_term72_state5_certificate, table0_term72_state6_certificate, table0_term72_state7_certificate, table0_term72_state8_certificate, table0_term72_state9_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
