import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawLeftSplitCertificate

import PolynomialFormulas.ComputableDummitKernelCertificateRawMulAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk9Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk10Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk11Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk12Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk13Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term111_state7_normalize_raw_certificate :
    SparsePolynomial.rawMul table0Term111State6Normal (elementaryPolynomials 2) = table0Term111State7NormalizeRawNormal := by
  rw [table0_term111_state7_normalize_rawleftsplit_certificate]
  change SparsePolynomial.rawMul (table0Term111State7NormalizeRawLeftChunk0Normal ++ (table0Term111State7NormalizeRawLeftChunk1Normal ++ (table0Term111State7NormalizeRawLeftChunk2Normal ++ (table0Term111State7NormalizeRawLeftChunk3Normal ++ (table0Term111State7NormalizeRawLeftChunk4Normal ++ (table0Term111State7NormalizeRawLeftChunk5Normal ++ (table0Term111State7NormalizeRawLeftChunk6Normal ++ (table0Term111State7NormalizeRawLeftChunk7Normal ++ (table0Term111State7NormalizeRawLeftChunk8Normal ++ (table0Term111State7NormalizeRawLeftChunk9Normal ++ (table0Term111State7NormalizeRawLeftChunk10Normal ++ (table0Term111State7NormalizeRawLeftChunk11Normal ++ (table0Term111State7NormalizeRawLeftChunk12Normal ++ table0Term111State7NormalizeRawLeftChunk13Normal))))))))))))) (elementaryPolynomials 2) = (table0Term111State7NormalizeRawChunk0Normal ++ (table0Term111State7NormalizeRawChunk1Normal ++ (table0Term111State7NormalizeRawChunk2Normal ++ (table0Term111State7NormalizeRawChunk3Normal ++ (table0Term111State7NormalizeRawChunk4Normal ++ (table0Term111State7NormalizeRawChunk5Normal ++ (table0Term111State7NormalizeRawChunk6Normal ++ (table0Term111State7NormalizeRawChunk7Normal ++ (table0Term111State7NormalizeRawChunk8Normal ++ (table0Term111State7NormalizeRawChunk9Normal ++ (table0Term111State7NormalizeRawChunk10Normal ++ (table0Term111State7NormalizeRawChunk11Normal ++ (table0Term111State7NormalizeRawChunk12Normal ++ table0Term111State7NormalizeRawChunk13Normal)))))))))))))
  rw [rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, table0_term111_state7_normalize_raw_chunk0_certificate, table0_term111_state7_normalize_raw_chunk1_certificate, table0_term111_state7_normalize_raw_chunk2_certificate, table0_term111_state7_normalize_raw_chunk3_certificate, table0_term111_state7_normalize_raw_chunk4_certificate, table0_term111_state7_normalize_raw_chunk5_certificate, table0_term111_state7_normalize_raw_chunk6_certificate, table0_term111_state7_normalize_raw_chunk7_certificate, table0_term111_state7_normalize_raw_chunk8_certificate, table0_term111_state7_normalize_raw_chunk9_certificate, table0_term111_state7_normalize_raw_chunk10_certificate, table0_term111_state7_normalize_raw_chunk11_certificate, table0_term111_state7_normalize_raw_chunk12_certificate, table0_term111_state7_normalize_raw_chunk13_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
