import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term86_state1_certificate :
    SparsePolynomial.mul table0Term86State0Normal (elementaryPolynomials 0) = table0Term86State1Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
