import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRawLeftChunk22Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRawChunk22Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state8_normalize_raw_chunk22_certificate :
    SparsePolynomial.rawMul table0Term87State8NormalizeRawLeftChunk22Normal (elementaryPolynomials 3) = table0Term87State8NormalizeRawChunk22Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
