import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term51State6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term51State5Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term51_state6_certificate :
    SparsePolynomial.mul table0Term51State5Normal (elementaryPolynomials 2) = table0Term51State6Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
