import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix2FlattenChunk6Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term90_state7_normalize_radix2_flatten_chunk6_certificate :
    SparsePolynomial.flattenBuckets table0Term90State7NormalizeRadix2FlattenChunk6BucketsNormal = table0Term90State7NormalizeRadix2FlattenChunk6Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
