import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRadix4FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term72State7NormalizeRadix4BucketsNormal : List SparsePolynomial :=
  (table0Term72State7NormalizeRadix4FlattenChunk0BucketsNormal ++ (table0Term72State7NormalizeRadix4FlattenChunk1BucketsNormal ++ (table0Term72State7NormalizeRadix4FlattenChunk2BucketsNormal ++ (table0Term72State7NormalizeRadix4FlattenChunk3BucketsNormal ++ (table0Term72State7NormalizeRadix4FlattenChunk4BucketsNormal ++ (table0Term72State7NormalizeRadix4FlattenChunk5BucketsNormal ++ (table0Term72State7NormalizeRadix4FlattenChunk6BucketsNormal ++ table0Term72State7NormalizeRadix4FlattenChunk7BucketsNormal)))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
