import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2Data

import PolynomialFormulas.ComputableDummitKernelCertificateFlattenBucketsAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix2FlattenChunk9Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term72_state9_normalize_radix2flatten_certificate :
    SparsePolynomial.flattenBuckets table0Term72State9NormalizeRadix2BucketsNormal = table0Term72State9NormalizeRadix2Normal := by
  change SparsePolynomial.flattenBuckets (table0Term72State9NormalizeRadix2FlattenChunk0BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk1BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk2BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk3BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk4BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk5BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk6BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk7BucketsNormal ++ (table0Term72State9NormalizeRadix2FlattenChunk8BucketsNormal ++ table0Term72State9NormalizeRadix2FlattenChunk9BucketsNormal))))))))) =
    (table0Term72State9NormalizeRadix2FlattenChunk0Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk1Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk2Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk3Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk4Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk5Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk6Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk7Normal ++ (table0Term72State9NormalizeRadix2FlattenChunk8Normal ++ table0Term72State9NormalizeRadix2FlattenChunk9Normal)))))))))
  rw [flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, table0_term72_state9_normalize_radix2_flatten_chunk0_certificate, table0_term72_state9_normalize_radix2_flatten_chunk1_certificate, table0_term72_state9_normalize_radix2_flatten_chunk2_certificate, table0_term72_state9_normalize_radix2_flatten_chunk3_certificate, table0_term72_state9_normalize_radix2_flatten_chunk4_certificate, table0_term72_state9_normalize_radix2_flatten_chunk5_certificate, table0_term72_state9_normalize_radix2_flatten_chunk6_certificate, table0_term72_state9_normalize_radix2_flatten_chunk7_certificate, table0_term72_state9_normalize_radix2_flatten_chunk8_certificate, table0_term72_state9_normalize_radix2_flatten_chunk9_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
