import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix4BucketizeCertificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix4FlattenCertificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term125_state8_normalize_radix4_certificate :
    SparsePolynomial.radixPass (fun t ↦ t.powers.p4) table0Term125State8NormalizeRawNormal = table0Term125State8NormalizeRadix4Normal := by
  change SparsePolynomial.flattenBuckets
    (SparsePolynomial.bucketize (fun t ↦ t.powers.p4) table0Term125State8NormalizeRawNormal) = _
  rw [table0_term125_state8_normalize_radix4bucketize_certificate, table0_term125_state8_normalize_radix4flatten_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
