import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawLeftChunk36Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9NormalizeRawChunk36Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state9_normalize_raw_chunk36_certificate :
    SparsePolynomial.rawMul table0Term87State9NormalizeRawLeftChunk36Normal (elementaryPolynomials 3) = table0Term87State9NormalizeRawChunk36Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
