import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRawLeftChunk22Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRawChunk22Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term72_state9_normalize_raw_chunk22_certificate :
    SparsePolynomial.rawMul table0Term72State9NormalizeRawLeftChunk22Normal (elementaryPolynomials 3) = table0Term72State9NormalizeRawChunk22Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
