import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRawLeftChunk12Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRawChunk12Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term85_state8_normalize_raw_chunk12_certificate :
    SparsePolynomial.rawMul table0Term85State8NormalizeRawLeftChunk12Normal (elementaryPolynomials 3) = table0Term85State8NormalizeRawChunk12Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
