import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRadix3FlattenChunk0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term90_state9_normalize_radix3_flatten_chunk0_certificate :
    SparsePolynomial.flattenBuckets table0Term90State9NormalizeRadix3FlattenChunk0BucketsNormal = table0Term90State9NormalizeRadix3FlattenChunk0Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
