import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State3Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state4_certificate :
    SparsePolynomial.mul table0Term87State3Normal (elementaryPolynomials 1) = table0Term87State4Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
