import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRadix4FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term90_state9_normalize_radix4_flatten_chunk7_certificate :
    SparsePolynomial.flattenBuckets table0Term90State9NormalizeRadix4FlattenChunk7BucketsNormal = table0Term90State9NormalizeRadix4FlattenChunk7Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
