import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk30Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawChunk30Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term111_state9_normalize_raw_chunk30_certificate :
    SparsePolynomial.rawMul table0Term111State9NormalizeRawLeftChunk30Normal (elementaryPolynomials 3) = table0Term111State9NormalizeRawChunk30Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
