import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term111_state1_certificate :
    SparsePolynomial.mul table0Term111State0Normal (elementaryPolynomials 1) = table0Term111State1Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
