import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix3FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term85State9NormalizeRadix3BucketsNormal : List SparsePolynomial :=
  (table0Term85State9NormalizeRadix3FlattenChunk0BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk1BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk2BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk3BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk4BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk5BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk6BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk7BucketsNormal ++ (table0Term85State9NormalizeRadix3FlattenChunk8BucketsNormal ++ table0Term85State9NormalizeRadix3FlattenChunk9BucketsNormal)))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
