import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State7NormalizeRadix0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term71_state7_normalize_combine_certificate :
    SparsePolynomial.combine table0Term71State7NormalizeRadix0Normal = table0Term71State7Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
