import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State9Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term87_certificate :
    SparseTerm.substitute ⟨-15, ⟨1, 3, 3, 2, 0⟩⟩ elementaryPolynomials = table0Term87Normal := by
  change SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.mul (SparsePolynomial.const (-15)) (elementaryPolynomials 0)) (elementaryPolynomials 1)) (elementaryPolynomials 1)) (elementaryPolynomials 1)) (elementaryPolynomials 2)) (elementaryPolynomials 2)) (elementaryPolynomials 2)) (elementaryPolynomials 3)) (elementaryPolynomials 3) = table0Term87Normal
  rw [table0_term87_state0_certificate, table0_term87_state1_certificate, table0_term87_state2_certificate, table0_term87_state3_certificate, table0_term87_state4_certificate, table0_term87_state5_certificate, table0_term87_state6_certificate, table0_term87_state7_certificate, table0_term87_state8_certificate, table0_term87_state9_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
