import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term109State9NormalizeRadix0Normal : SparsePolynomial :=
  (table0Term109State9NormalizeRadix0FlattenChunk0Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk1Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk2Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk3Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk4Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk5Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk6Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk7Normal ++ (table0Term109State9NormalizeRadix0FlattenChunk8Normal ++ table0Term109State9NormalizeRadix0FlattenChunk9Normal)))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
