import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawLeftChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRawChunk3Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term111_state7_normalize_raw_chunk3_certificate :
    SparsePolynomial.rawMul table0Term111State7NormalizeRawLeftChunk3Normal (elementaryPolynomials 2) = table0Term111State7NormalizeRawChunk3Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
