import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix4FlattenChunk4Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term109_state9_normalize_radix4_flatten_chunk4_certificate :
    SparsePolynomial.flattenBuckets table0Term109State9NormalizeRadix4FlattenChunk4BucketsNormal = table0Term109State9NormalizeRadix4FlattenChunk4Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
