import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk9Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk10Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk11Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk12Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk13Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk14Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk15Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk16Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk17Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk18Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk19Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk20Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk21Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk22Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk23Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk24Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk25Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk26Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk27Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk28Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk29Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk30Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk31Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk32Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk33Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk34Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk35Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk36Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk37Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State9NormalizeRawChunk38Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term90State9NormalizeRawNormal : SparsePolynomial :=
  (table0Term90State9NormalizeRawChunk0Normal ++ (table0Term90State9NormalizeRawChunk1Normal ++ (table0Term90State9NormalizeRawChunk2Normal ++ (table0Term90State9NormalizeRawChunk3Normal ++ (table0Term90State9NormalizeRawChunk4Normal ++ (table0Term90State9NormalizeRawChunk5Normal ++ (table0Term90State9NormalizeRawChunk6Normal ++ (table0Term90State9NormalizeRawChunk7Normal ++ (table0Term90State9NormalizeRawChunk8Normal ++ (table0Term90State9NormalizeRawChunk9Normal ++ (table0Term90State9NormalizeRawChunk10Normal ++ (table0Term90State9NormalizeRawChunk11Normal ++ (table0Term90State9NormalizeRawChunk12Normal ++ (table0Term90State9NormalizeRawChunk13Normal ++ (table0Term90State9NormalizeRawChunk14Normal ++ (table0Term90State9NormalizeRawChunk15Normal ++ (table0Term90State9NormalizeRawChunk16Normal ++ (table0Term90State9NormalizeRawChunk17Normal ++ (table0Term90State9NormalizeRawChunk18Normal ++ (table0Term90State9NormalizeRawChunk19Normal ++ (table0Term90State9NormalizeRawChunk20Normal ++ (table0Term90State9NormalizeRawChunk21Normal ++ (table0Term90State9NormalizeRawChunk22Normal ++ (table0Term90State9NormalizeRawChunk23Normal ++ (table0Term90State9NormalizeRawChunk24Normal ++ (table0Term90State9NormalizeRawChunk25Normal ++ (table0Term90State9NormalizeRawChunk26Normal ++ (table0Term90State9NormalizeRawChunk27Normal ++ (table0Term90State9NormalizeRawChunk28Normal ++ (table0Term90State9NormalizeRawChunk29Normal ++ (table0Term90State9NormalizeRawChunk30Normal ++ (table0Term90State9NormalizeRawChunk31Normal ++ (table0Term90State9NormalizeRawChunk32Normal ++ (table0Term90State9NormalizeRawChunk33Normal ++ (table0Term90State9NormalizeRawChunk34Normal ++ (table0Term90State9NormalizeRawChunk35Normal ++ (table0Term90State9NormalizeRawChunk36Normal ++ (table0Term90State9NormalizeRawChunk37Normal ++ table0Term90State9NormalizeRawChunk38Normal))))))))))))))))))))))))))))))))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
