import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term90State7NormalizeRadix3BucketsNormal : List SparsePolynomial :=
  (table0Term90State7NormalizeRadix3FlattenChunk0BucketsNormal ++ (table0Term90State7NormalizeRadix3FlattenChunk1BucketsNormal ++ (table0Term90State7NormalizeRadix3FlattenChunk2BucketsNormal ++ (table0Term90State7NormalizeRadix3FlattenChunk3BucketsNormal ++ (table0Term90State7NormalizeRadix3FlattenChunk4BucketsNormal ++ (table0Term90State7NormalizeRadix3FlattenChunk5BucketsNormal ++ (table0Term90State7NormalizeRadix3FlattenChunk6BucketsNormal ++ table0Term90State7NormalizeRadix3FlattenChunk7BucketsNormal)))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
