import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix0FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term109_state8_normalize_radix0_flatten_chunk8_certificate :
    SparsePolynomial.flattenBuckets table0Term109State8NormalizeRadix0FlattenChunk8BucketsNormal = table0Term109State8NormalizeRadix0FlattenChunk8Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
