import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1Data

import PolynomialFormulas.ComputableDummitKernelCertificateFlattenBucketsAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk7Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term125_state7_normalize_radix1flatten_certificate :
    SparsePolynomial.flattenBuckets table0Term125State7NormalizeRadix1BucketsNormal = table0Term125State7NormalizeRadix1Normal := by
  change SparsePolynomial.flattenBuckets (table0Term125State7NormalizeRadix1FlattenChunk0BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk1BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk2BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk3BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk4BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk5BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk6BucketsNormal ++ table0Term125State7NormalizeRadix1FlattenChunk7BucketsNormal))))))) =
    (table0Term125State7NormalizeRadix1FlattenChunk0Normal ++ (table0Term125State7NormalizeRadix1FlattenChunk1Normal ++ (table0Term125State7NormalizeRadix1FlattenChunk2Normal ++ (table0Term125State7NormalizeRadix1FlattenChunk3Normal ++ (table0Term125State7NormalizeRadix1FlattenChunk4Normal ++ (table0Term125State7NormalizeRadix1FlattenChunk5Normal ++ (table0Term125State7NormalizeRadix1FlattenChunk6Normal ++ table0Term125State7NormalizeRadix1FlattenChunk7Normal)))))))
  rw [flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, table0_term125_state7_normalize_radix1_flatten_chunk0_certificate, table0_term125_state7_normalize_radix1_flatten_chunk1_certificate, table0_term125_state7_normalize_radix1_flatten_chunk2_certificate, table0_term125_state7_normalize_radix1_flatten_chunk3_certificate, table0_term125_state7_normalize_radix1_flatten_chunk4_certificate, table0_term125_state7_normalize_radix1_flatten_chunk5_certificate, table0_term125_state7_normalize_radix1_flatten_chunk6_certificate, table0_term125_state7_normalize_radix1_flatten_chunk7_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
