import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4Data

import PolynomialFormulas.ComputableDummitKernelCertificateFlattenBucketsAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix4FlattenChunk8Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term87_state8_normalize_radix4flatten_certificate :
    SparsePolynomial.flattenBuckets table0Term87State8NormalizeRadix4BucketsNormal = table0Term87State8NormalizeRadix4Normal := by
  change SparsePolynomial.flattenBuckets (table0Term87State8NormalizeRadix4FlattenChunk0BucketsNormal ++ (table0Term87State8NormalizeRadix4FlattenChunk1BucketsNormal ++ (table0Term87State8NormalizeRadix4FlattenChunk2BucketsNormal ++ (table0Term87State8NormalizeRadix4FlattenChunk3BucketsNormal ++ (table0Term87State8NormalizeRadix4FlattenChunk4BucketsNormal ++ (table0Term87State8NormalizeRadix4FlattenChunk5BucketsNormal ++ (table0Term87State8NormalizeRadix4FlattenChunk6BucketsNormal ++ (table0Term87State8NormalizeRadix4FlattenChunk7BucketsNormal ++ table0Term87State8NormalizeRadix4FlattenChunk8BucketsNormal)))))))) =
    (table0Term87State8NormalizeRadix4FlattenChunk0Normal ++ (table0Term87State8NormalizeRadix4FlattenChunk1Normal ++ (table0Term87State8NormalizeRadix4FlattenChunk2Normal ++ (table0Term87State8NormalizeRadix4FlattenChunk3Normal ++ (table0Term87State8NormalizeRadix4FlattenChunk4Normal ++ (table0Term87State8NormalizeRadix4FlattenChunk5Normal ++ (table0Term87State8NormalizeRadix4FlattenChunk6Normal ++ (table0Term87State8NormalizeRadix4FlattenChunk7Normal ++ table0Term87State8NormalizeRadix4FlattenChunk8Normal))))))))
  rw [flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, table0_term87_state8_normalize_radix4_flatten_chunk0_certificate, table0_term87_state8_normalize_radix4_flatten_chunk1_certificate, table0_term87_state8_normalize_radix4_flatten_chunk2_certificate, table0_term87_state8_normalize_radix4_flatten_chunk3_certificate, table0_term87_state8_normalize_radix4_flatten_chunk4_certificate, table0_term87_state8_normalize_radix4_flatten_chunk5_certificate, table0_term87_state8_normalize_radix4_flatten_chunk6_certificate, table0_term87_state8_normalize_radix4_flatten_chunk7_certificate, table0_term87_state8_normalize_radix4_flatten_chunk8_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
