import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRadix0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term72_state9_normalize_combine_certificate :
    SparsePolynomial.combine table0Term72State9NormalizeRadix0Normal = table0Term72Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
