import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State8NormalizeRadix0FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term125State8NormalizeRadix0BucketsNormal : List SparsePolynomial :=
  (table0Term125State8NormalizeRadix0FlattenChunk0BucketsNormal ++ (table0Term125State8NormalizeRadix0FlattenChunk1BucketsNormal ++ (table0Term125State8NormalizeRadix0FlattenChunk2BucketsNormal ++ (table0Term125State8NormalizeRadix0FlattenChunk3BucketsNormal ++ (table0Term125State8NormalizeRadix0FlattenChunk4BucketsNormal ++ (table0Term125State8NormalizeRadix0FlattenChunk5BucketsNormal ++ (table0Term125State8NormalizeRadix0FlattenChunk6BucketsNormal ++ (table0Term125State8NormalizeRadix0FlattenChunk7BucketsNormal ++ table0Term125State8NormalizeRadix0FlattenChunk8BucketsNormal))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
