import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk9Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk10Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk11Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term131State7NormalizeRawNormal : SparsePolynomial :=
  (table0Term131State7NormalizeRawChunk0Normal ++ (table0Term131State7NormalizeRawChunk1Normal ++ (table0Term131State7NormalizeRawChunk2Normal ++ (table0Term131State7NormalizeRawChunk3Normal ++ (table0Term131State7NormalizeRawChunk4Normal ++ (table0Term131State7NormalizeRawChunk5Normal ++ (table0Term131State7NormalizeRawChunk6Normal ++ (table0Term131State7NormalizeRawChunk7Normal ++ (table0Term131State7NormalizeRawChunk8Normal ++ (table0Term131State7NormalizeRawChunk9Normal ++ (table0Term131State7NormalizeRawChunk10Normal ++ table0Term131State7NormalizeRawChunk11Normal)))))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
