import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State4Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state5_certificate :
    SparsePolynomial.mul table0Term87State4Normal (elementaryPolynomials 2) = table0Term87State5Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
