import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk4Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term131_state8_normalize_raw_chunk4_certificate :
    SparsePolynomial.rawMul table0Term131State8NormalizeRawLeftChunk4Normal (elementaryPolynomials 2) = table0Term131State8NormalizeRawChunk4Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
