import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRadix1FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term85State8NormalizeRadix1Normal : SparsePolynomial :=
  (table0Term85State8NormalizeRadix1FlattenChunk0Normal ++ (table0Term85State8NormalizeRadix1FlattenChunk1Normal ++ (table0Term85State8NormalizeRadix1FlattenChunk2Normal ++ (table0Term85State8NormalizeRadix1FlattenChunk3Normal ++ (table0Term85State8NormalizeRadix1FlattenChunk4Normal ++ (table0Term85State8NormalizeRadix1FlattenChunk5Normal ++ (table0Term85State8NormalizeRadix1FlattenChunk6Normal ++ (table0Term85State8NormalizeRadix1FlattenChunk7Normal ++ table0Term85State8NormalizeRadix1FlattenChunk8Normal))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
