import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix1BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix2Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term111_state9_normalize_radix1bucketize_certificate :
    SparsePolynomial.bucketize (fun t ↦ t.powers.p1) table0Term111State9NormalizeRadix2Normal = table0Term111State9NormalizeRadix1BucketsNormal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
