import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State7NormalizeRadix3FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term90State7NormalizeRadix3Normal : SparsePolynomial :=
  (table0Term90State7NormalizeRadix3FlattenChunk0Normal ++ (table0Term90State7NormalizeRadix3FlattenChunk1Normal ++ (table0Term90State7NormalizeRadix3FlattenChunk2Normal ++ (table0Term90State7NormalizeRadix3FlattenChunk3Normal ++ (table0Term90State7NormalizeRadix3FlattenChunk4Normal ++ (table0Term90State7NormalizeRadix3FlattenChunk5Normal ++ (table0Term90State7NormalizeRadix3FlattenChunk6Normal ++ table0Term90State7NormalizeRadix3FlattenChunk7Normal)))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
