import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State6Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term109_state7_certificate :
    SparsePolynomial.mul table0Term109State6Normal (elementaryPolynomials 3) = table0Term109State7Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
