import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix1FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term109State9NormalizeRadix1BucketsNormal : List SparsePolynomial :=
  (table0Term109State9NormalizeRadix1FlattenChunk0BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk1BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk2BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk3BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk4BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk5BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk6BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk7BucketsNormal ++ (table0Term109State9NormalizeRadix1FlattenChunk8BucketsNormal ++ table0Term109State9NormalizeRadix1FlattenChunk9BucketsNormal)))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
