import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0Data

import PolynomialFormulas.ComputableDummitKernelCertificateFlattenBucketsAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix0FlattenChunk9Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term85_state9_normalize_radix0flatten_certificate :
    SparsePolynomial.flattenBuckets table0Term85State9NormalizeRadix0BucketsNormal = table0Term85State9NormalizeRadix0Normal := by
  change SparsePolynomial.flattenBuckets (table0Term85State9NormalizeRadix0FlattenChunk0BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk1BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk2BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk3BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk4BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk5BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk6BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk7BucketsNormal ++ (table0Term85State9NormalizeRadix0FlattenChunk8BucketsNormal ++ table0Term85State9NormalizeRadix0FlattenChunk9BucketsNormal))))))))) =
    (table0Term85State9NormalizeRadix0FlattenChunk0Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk1Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk2Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk3Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk4Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk5Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk6Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk7Normal ++ (table0Term85State9NormalizeRadix0FlattenChunk8Normal ++ table0Term85State9NormalizeRadix0FlattenChunk9Normal)))))))))
  rw [flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, table0_term85_state9_normalize_radix0_flatten_chunk0_certificate, table0_term85_state9_normalize_radix0_flatten_chunk1_certificate, table0_term85_state9_normalize_radix0_flatten_chunk2_certificate, table0_term85_state9_normalize_radix0_flatten_chunk3_certificate, table0_term85_state9_normalize_radix0_flatten_chunk4_certificate, table0_term85_state9_normalize_radix0_flatten_chunk5_certificate, table0_term85_state9_normalize_radix0_flatten_chunk6_certificate, table0_term85_state9_normalize_radix0_flatten_chunk7_certificate, table0_term85_state9_normalize_radix0_flatten_chunk8_certificate, table0_term85_state9_normalize_radix0_flatten_chunk9_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
