import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State7NormalizeRadix0FlattenChunk5Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term111_state7_normalize_radix0_flatten_chunk5_certificate :
    SparsePolynomial.flattenBuckets table0Term111State7NormalizeRadix0FlattenChunk5BucketsNormal = table0Term111State7NormalizeRadix0FlattenChunk5Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
