import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term131State8NormalizeRadix2BucketsNormal : List SparsePolynomial :=
  (table0Term131State8NormalizeRadix2FlattenChunk0BucketsNormal ++ (table0Term131State8NormalizeRadix2FlattenChunk1BucketsNormal ++ (table0Term131State8NormalizeRadix2FlattenChunk2BucketsNormal ++ (table0Term131State8NormalizeRadix2FlattenChunk3BucketsNormal ++ (table0Term131State8NormalizeRadix2FlattenChunk4BucketsNormal ++ (table0Term131State8NormalizeRadix2FlattenChunk5BucketsNormal ++ (table0Term131State8NormalizeRadix2FlattenChunk6BucketsNormal ++ (table0Term131State8NormalizeRadix2FlattenChunk7BucketsNormal ++ table0Term131State8NormalizeRadix2FlattenChunk8BucketsNormal))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
