import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0Data

import PolynomialFormulas.ComputableDummitKernelCertificateFlattenBucketsAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRadix0FlattenChunk8Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term90_state8_normalize_radix0flatten_certificate :
    SparsePolynomial.flattenBuckets table0Term90State8NormalizeRadix0BucketsNormal = table0Term90State8NormalizeRadix0Normal := by
  change SparsePolynomial.flattenBuckets (table0Term90State8NormalizeRadix0FlattenChunk0BucketsNormal ++ (table0Term90State8NormalizeRadix0FlattenChunk1BucketsNormal ++ (table0Term90State8NormalizeRadix0FlattenChunk2BucketsNormal ++ (table0Term90State8NormalizeRadix0FlattenChunk3BucketsNormal ++ (table0Term90State8NormalizeRadix0FlattenChunk4BucketsNormal ++ (table0Term90State8NormalizeRadix0FlattenChunk5BucketsNormal ++ (table0Term90State8NormalizeRadix0FlattenChunk6BucketsNormal ++ (table0Term90State8NormalizeRadix0FlattenChunk7BucketsNormal ++ table0Term90State8NormalizeRadix0FlattenChunk8BucketsNormal)))))))) =
    (table0Term90State8NormalizeRadix0FlattenChunk0Normal ++ (table0Term90State8NormalizeRadix0FlattenChunk1Normal ++ (table0Term90State8NormalizeRadix0FlattenChunk2Normal ++ (table0Term90State8NormalizeRadix0FlattenChunk3Normal ++ (table0Term90State8NormalizeRadix0FlattenChunk4Normal ++ (table0Term90State8NormalizeRadix0FlattenChunk5Normal ++ (table0Term90State8NormalizeRadix0FlattenChunk6Normal ++ (table0Term90State8NormalizeRadix0FlattenChunk7Normal ++ table0Term90State8NormalizeRadix0FlattenChunk8Normal))))))))
  rw [flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, flattenBuckets_append_certificate, table0_term90_state8_normalize_radix0_flatten_chunk0_certificate, table0_term90_state8_normalize_radix0_flatten_chunk1_certificate, table0_term90_state8_normalize_radix0_flatten_chunk2_certificate, table0_term90_state8_normalize_radix0_flatten_chunk3_certificate, table0_term90_state8_normalize_radix0_flatten_chunk4_certificate, table0_term90_state8_normalize_radix0_flatten_chunk5_certificate, table0_term90_state8_normalize_radix0_flatten_chunk6_certificate, table0_term90_state8_normalize_radix0_flatten_chunk7_certificate, table0_term90_state8_normalize_radix0_flatten_chunk8_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
