import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk9Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk10Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk11Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk12Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk13Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk14Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk15Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk16Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk17Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk18Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk19Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftChunk20Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term131_state8_normalize_rawleftsplit_certificate :
    table0Term131State7Normal = (table0Term131State8NormalizeRawLeftChunk0Normal ++ (table0Term131State8NormalizeRawLeftChunk1Normal ++ (table0Term131State8NormalizeRawLeftChunk2Normal ++ (table0Term131State8NormalizeRawLeftChunk3Normal ++ (table0Term131State8NormalizeRawLeftChunk4Normal ++ (table0Term131State8NormalizeRawLeftChunk5Normal ++ (table0Term131State8NormalizeRawLeftChunk6Normal ++ (table0Term131State8NormalizeRawLeftChunk7Normal ++ (table0Term131State8NormalizeRawLeftChunk8Normal ++ (table0Term131State8NormalizeRawLeftChunk9Normal ++ (table0Term131State8NormalizeRawLeftChunk10Normal ++ (table0Term131State8NormalizeRawLeftChunk11Normal ++ (table0Term131State8NormalizeRawLeftChunk12Normal ++ (table0Term131State8NormalizeRawLeftChunk13Normal ++ (table0Term131State8NormalizeRawLeftChunk14Normal ++ (table0Term131State8NormalizeRawLeftChunk15Normal ++ (table0Term131State8NormalizeRawLeftChunk16Normal ++ (table0Term131State8NormalizeRawLeftChunk17Normal ++ (table0Term131State8NormalizeRawLeftChunk18Normal ++ (table0Term131State8NormalizeRawLeftChunk19Normal ++ table0Term131State8NormalizeRawLeftChunk20Normal)))))))))))))))))))) := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
