import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk9Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk10Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk11Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk12Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk13Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk14Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk15Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk16Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk17Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk18Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk19Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk20Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk21Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk22Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk23Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk24Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk25Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk26Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk27Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk28Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk29Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk30Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk31Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk32Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk33Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk34Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk35Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk36Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk37Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk38Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term111_state9_normalize_rawleftsplit_certificate :
    table0Term111State8Normal = (table0Term111State9NormalizeRawLeftChunk0Normal ++ (table0Term111State9NormalizeRawLeftChunk1Normal ++ (table0Term111State9NormalizeRawLeftChunk2Normal ++ (table0Term111State9NormalizeRawLeftChunk3Normal ++ (table0Term111State9NormalizeRawLeftChunk4Normal ++ (table0Term111State9NormalizeRawLeftChunk5Normal ++ (table0Term111State9NormalizeRawLeftChunk6Normal ++ (table0Term111State9NormalizeRawLeftChunk7Normal ++ (table0Term111State9NormalizeRawLeftChunk8Normal ++ (table0Term111State9NormalizeRawLeftChunk9Normal ++ (table0Term111State9NormalizeRawLeftChunk10Normal ++ (table0Term111State9NormalizeRawLeftChunk11Normal ++ (table0Term111State9NormalizeRawLeftChunk12Normal ++ (table0Term111State9NormalizeRawLeftChunk13Normal ++ (table0Term111State9NormalizeRawLeftChunk14Normal ++ (table0Term111State9NormalizeRawLeftChunk15Normal ++ (table0Term111State9NormalizeRawLeftChunk16Normal ++ (table0Term111State9NormalizeRawLeftChunk17Normal ++ (table0Term111State9NormalizeRawLeftChunk18Normal ++ (table0Term111State9NormalizeRawLeftChunk19Normal ++ (table0Term111State9NormalizeRawLeftChunk20Normal ++ (table0Term111State9NormalizeRawLeftChunk21Normal ++ (table0Term111State9NormalizeRawLeftChunk22Normal ++ (table0Term111State9NormalizeRawLeftChunk23Normal ++ (table0Term111State9NormalizeRawLeftChunk24Normal ++ (table0Term111State9NormalizeRawLeftChunk25Normal ++ (table0Term111State9NormalizeRawLeftChunk26Normal ++ (table0Term111State9NormalizeRawLeftChunk27Normal ++ (table0Term111State9NormalizeRawLeftChunk28Normal ++ (table0Term111State9NormalizeRawLeftChunk29Normal ++ (table0Term111State9NormalizeRawLeftChunk30Normal ++ (table0Term111State9NormalizeRawLeftChunk31Normal ++ (table0Term111State9NormalizeRawLeftChunk32Normal ++ (table0Term111State9NormalizeRawLeftChunk33Normal ++ (table0Term111State9NormalizeRawLeftChunk34Normal ++ (table0Term111State9NormalizeRawLeftChunk35Normal ++ (table0Term111State9NormalizeRawLeftChunk36Normal ++ (table0Term111State9NormalizeRawLeftChunk37Normal ++ table0Term111State9NormalizeRawLeftChunk38Normal)))))))))))))))))))))))))))))))))))))) := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
