import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawLeftSplitCertificate

import PolynomialFormulas.ComputableDummitKernelCertificateRawMulAppend

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk5Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk6Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk7Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk8Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk9Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk10Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk11Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk12Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk13Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk14Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk15Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk16Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk17Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk18Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk19Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk20Certificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term131_state8_normalize_raw_certificate :
    SparsePolynomial.rawMul table0Term131State7Normal (elementaryPolynomials 2) = table0Term131State8NormalizeRawNormal := by
  rw [table0_term131_state8_normalize_rawleftsplit_certificate]
  change SparsePolynomial.rawMul (table0Term131State8NormalizeRawLeftChunk0Normal ++ (table0Term131State8NormalizeRawLeftChunk1Normal ++ (table0Term131State8NormalizeRawLeftChunk2Normal ++ (table0Term131State8NormalizeRawLeftChunk3Normal ++ (table0Term131State8NormalizeRawLeftChunk4Normal ++ (table0Term131State8NormalizeRawLeftChunk5Normal ++ (table0Term131State8NormalizeRawLeftChunk6Normal ++ (table0Term131State8NormalizeRawLeftChunk7Normal ++ (table0Term131State8NormalizeRawLeftChunk8Normal ++ (table0Term131State8NormalizeRawLeftChunk9Normal ++ (table0Term131State8NormalizeRawLeftChunk10Normal ++ (table0Term131State8NormalizeRawLeftChunk11Normal ++ (table0Term131State8NormalizeRawLeftChunk12Normal ++ (table0Term131State8NormalizeRawLeftChunk13Normal ++ (table0Term131State8NormalizeRawLeftChunk14Normal ++ (table0Term131State8NormalizeRawLeftChunk15Normal ++ (table0Term131State8NormalizeRawLeftChunk16Normal ++ (table0Term131State8NormalizeRawLeftChunk17Normal ++ (table0Term131State8NormalizeRawLeftChunk18Normal ++ (table0Term131State8NormalizeRawLeftChunk19Normal ++ table0Term131State8NormalizeRawLeftChunk20Normal)))))))))))))))))))) (elementaryPolynomials 2) = (table0Term131State8NormalizeRawChunk0Normal ++ (table0Term131State8NormalizeRawChunk1Normal ++ (table0Term131State8NormalizeRawChunk2Normal ++ (table0Term131State8NormalizeRawChunk3Normal ++ (table0Term131State8NormalizeRawChunk4Normal ++ (table0Term131State8NormalizeRawChunk5Normal ++ (table0Term131State8NormalizeRawChunk6Normal ++ (table0Term131State8NormalizeRawChunk7Normal ++ (table0Term131State8NormalizeRawChunk8Normal ++ (table0Term131State8NormalizeRawChunk9Normal ++ (table0Term131State8NormalizeRawChunk10Normal ++ (table0Term131State8NormalizeRawChunk11Normal ++ (table0Term131State8NormalizeRawChunk12Normal ++ (table0Term131State8NormalizeRawChunk13Normal ++ (table0Term131State8NormalizeRawChunk14Normal ++ (table0Term131State8NormalizeRawChunk15Normal ++ (table0Term131State8NormalizeRawChunk16Normal ++ (table0Term131State8NormalizeRawChunk17Normal ++ (table0Term131State8NormalizeRawChunk18Normal ++ (table0Term131State8NormalizeRawChunk19Normal ++ table0Term131State8NormalizeRawChunk20Normal))))))))))))))))))))
  rw [rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, rawMul_append_certificate, table0_term131_state8_normalize_raw_chunk0_certificate, table0_term131_state8_normalize_raw_chunk1_certificate, table0_term131_state8_normalize_raw_chunk2_certificate, table0_term131_state8_normalize_raw_chunk3_certificate, table0_term131_state8_normalize_raw_chunk4_certificate, table0_term131_state8_normalize_raw_chunk5_certificate, table0_term131_state8_normalize_raw_chunk6_certificate, table0_term131_state8_normalize_raw_chunk7_certificate, table0_term131_state8_normalize_raw_chunk8_certificate, table0_term131_state8_normalize_raw_chunk9_certificate, table0_term131_state8_normalize_raw_chunk10_certificate, table0_term131_state8_normalize_raw_chunk11_certificate, table0_term131_state8_normalize_raw_chunk12_certificate, table0_term131_state8_normalize_raw_chunk13_certificate, table0_term131_state8_normalize_raw_chunk14_certificate, table0_term131_state8_normalize_raw_chunk15_certificate, table0_term131_state8_normalize_raw_chunk16_certificate, table0_term131_state8_normalize_raw_chunk17_certificate, table0_term131_state8_normalize_raw_chunk18_certificate, table0_term131_state8_normalize_raw_chunk19_certificate, table0_term131_state8_normalize_raw_chunk20_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
