import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRawLeftChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRawChunk2Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term85_state9_normalize_raw_chunk2_certificate :
    SparsePolynomial.rawMul table0Term85State9NormalizeRawLeftChunk2Normal (elementaryPolynomials 3) = table0Term85State9NormalizeRawChunk2Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
