import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawLeftChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term86State7NormalizeRawChunk0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term86_state7_normalize_raw_chunk0_certificate :
    SparsePolynomial.rawMul table0Term86State7NormalizeRawLeftChunk0Normal (elementaryPolynomials 2) = table0Term86State7NormalizeRawChunk0Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
