import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix2FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term109State9NormalizeRadix2Normal : SparsePolynomial :=
  (table0Term109State9NormalizeRadix2FlattenChunk0Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk1Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk2Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk3Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk4Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk5Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk6Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk7Normal ++ (table0Term109State9NormalizeRadix2FlattenChunk8Normal ++ table0Term109State9NormalizeRadix2FlattenChunk9Normal)))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
