import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk9Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk10Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State7NormalizeRawLeftChunk11Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term72_state7_normalize_rawleftsplit_certificate :
    table0Term72State6Normal = (table0Term72State7NormalizeRawLeftChunk0Normal ++ (table0Term72State7NormalizeRawLeftChunk1Normal ++ (table0Term72State7NormalizeRawLeftChunk2Normal ++ (table0Term72State7NormalizeRawLeftChunk3Normal ++ (table0Term72State7NormalizeRawLeftChunk4Normal ++ (table0Term72State7NormalizeRawLeftChunk5Normal ++ (table0Term72State7NormalizeRawLeftChunk6Normal ++ (table0Term72State7NormalizeRawLeftChunk7Normal ++ (table0Term72State7NormalizeRawLeftChunk8Normal ++ (table0Term72State7NormalizeRawLeftChunk9Normal ++ (table0Term72State7NormalizeRawLeftChunk10Normal ++ table0Term72State7NormalizeRawLeftChunk11Normal))))))))))) := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
