import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term110State8NormalizeRadix4FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term110State8NormalizeRadix4Normal : SparsePolynomial :=
  (table0Term110State8NormalizeRadix4FlattenChunk0Normal ++ (table0Term110State8NormalizeRadix4FlattenChunk1Normal ++ (table0Term110State8NormalizeRadix4FlattenChunk2Normal ++ (table0Term110State8NormalizeRadix4FlattenChunk3Normal ++ (table0Term110State8NormalizeRadix4FlattenChunk4Normal ++ (table0Term110State8NormalizeRadix4FlattenChunk5Normal ++ (table0Term110State8NormalizeRadix4FlattenChunk6Normal ++ (table0Term110State8NormalizeRadix4FlattenChunk7Normal ++ table0Term110State8NormalizeRadix4FlattenChunk8Normal))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
