import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRawLeftChunk21Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State8NormalizeRawChunk21Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term85_state8_normalize_raw_chunk21_certificate :
    SparsePolynomial.rawMul table0Term85State8NormalizeRawLeftChunk21Normal (elementaryPolynomials 3) = table0Term85State8NormalizeRawChunk21Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
