import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix4FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term131_state8_normalize_radix4_flatten_chunk8_certificate :
    SparsePolynomial.flattenBuckets table0Term131State8NormalizeRadix4FlattenChunk8BucketsNormal = table0Term131State8NormalizeRadix4FlattenChunk8Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
