import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term71State8NormalizeRadix3FlattenChunk8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term71State8NormalizeRadix3Normal : SparsePolynomial :=
  (table0Term71State8NormalizeRadix3FlattenChunk0Normal ++ (table0Term71State8NormalizeRadix3FlattenChunk1Normal ++ (table0Term71State8NormalizeRadix3FlattenChunk2Normal ++ (table0Term71State8NormalizeRadix3FlattenChunk3Normal ++ (table0Term71State8NormalizeRadix3FlattenChunk4Normal ++ (table0Term71State8NormalizeRadix3FlattenChunk5Normal ++ (table0Term71State8NormalizeRadix3FlattenChunk6Normal ++ (table0Term71State8NormalizeRadix3FlattenChunk7Normal ++ table0Term71State8NormalizeRadix3FlattenChunk8Normal))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
