import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State9NormalizeRadix0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term109_state9_normalize_combine_certificate :
    SparsePolynomial.combine table0Term109State9NormalizeRadix0Normal = table0Term109Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
