import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRawLeftChunk16Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRawChunk16Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term72_state9_normalize_raw_chunk16_certificate :
    SparsePolynomial.rawMul table0Term72State9NormalizeRawLeftChunk16Normal (elementaryPolynomials 3) = table0Term72State9NormalizeRawChunk16Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
