import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term109State8NormalizeRadix3FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term109_state8_normalize_radix3_flatten_chunk7_certificate :
    SparsePolynomial.flattenBuckets table0Term109State8NormalizeRadix3FlattenChunk7BucketsNormal = table0Term109State8NormalizeRadix3FlattenChunk7Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
