import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term125State7NormalizeRadix1FlattenChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term125State7NormalizeRadix1BucketsNormal : List SparsePolynomial :=
  (table0Term125State7NormalizeRadix1FlattenChunk0BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk1BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk2BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk3BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk4BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk5BucketsNormal ++ (table0Term125State7NormalizeRadix1FlattenChunk6BucketsNormal ++ table0Term125State7NormalizeRadix1FlattenChunk7BucketsNormal)))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
