import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix1BucketsData

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRadix2Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term131_state7_normalize_radix1bucketize_certificate :
    SparsePolynomial.bucketize (fun t ↦ t.powers.p1) table0Term131State7NormalizeRadix2Normal = table0Term131State7NormalizeRadix1BucketsNormal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
