import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawCertificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix4Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix3Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix2Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix1Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix0Certificate

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeCombineCertificate

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

theorem table0_term131_state8_certificate :
    SparsePolynomial.mul table0Term131State7Normal (elementaryPolynomials 2) = table0Term131Normal := by
  change SparsePolynomial.combine (SparsePolynomial.radixPass (fun t ↦ t.powers.p0) (SparsePolynomial.radixPass (fun t ↦ t.powers.p1) (SparsePolynomial.radixPass (fun t ↦ t.powers.p2) (SparsePolynomial.radixPass (fun t ↦ t.powers.p3) (SparsePolynomial.radixPass (fun t ↦ t.powers.p4) (SparsePolynomial.rawMul table0Term131State7Normal (elementaryPolynomials 2))))))) = table0Term131Normal
  rw [table0_term131_state8_normalize_raw_certificate, table0_term131_state8_normalize_radix4_certificate, table0_term131_state8_normalize_radix3_certificate, table0_term131_state8_normalize_radix2_certificate, table0_term131_state8_normalize_radix1_certificate, table0_term131_state8_normalize_radix0_certificate, table0_term131_state8_normalize_combine_certificate]

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
