import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix2FlattenChunk0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term85_state9_normalize_radix2_flatten_chunk0_certificate :
    SparsePolynomial.flattenBuckets table0Term85State9NormalizeRadix2FlattenChunk0BucketsNormal = table0Term85State9NormalizeRadix2FlattenChunk0Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
