import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawLeftChunk21Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRawChunk21Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term111_state9_normalize_raw_chunk21_certificate :
    SparsePolynomial.rawMul table0Term111State9NormalizeRawLeftChunk21Normal (elementaryPolynomials 3) = table0Term111State9NormalizeRawChunk21Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
