import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term111State9NormalizeRadix3FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term111State9NormalizeRadix3Normal : SparsePolynomial :=
  (table0Term111State9NormalizeRadix3FlattenChunk0Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk1Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk2Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk3Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk4Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk5Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk6Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk7Normal ++ (table0Term111State9NormalizeRadix3FlattenChunk8Normal ++ table0Term111State9NormalizeRadix3FlattenChunk9Normal)))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
