import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRawLeftChunk32Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term72State9NormalizeRawChunk32Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term72_state9_normalize_raw_chunk32_certificate :
    SparsePolynomial.rawMul table0Term72State9NormalizeRawLeftChunk32Normal (elementaryPolynomials 3) = table0Term72State9NormalizeRawChunk32Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
