import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk9Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk10Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk11Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk12Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk13Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk14Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk15Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk16Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk17Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk18Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk19Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRawChunk20Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term131State8NormalizeRawNormal : SparsePolynomial :=
  (table0Term131State8NormalizeRawChunk0Normal ++ (table0Term131State8NormalizeRawChunk1Normal ++ (table0Term131State8NormalizeRawChunk2Normal ++ (table0Term131State8NormalizeRawChunk3Normal ++ (table0Term131State8NormalizeRawChunk4Normal ++ (table0Term131State8NormalizeRawChunk5Normal ++ (table0Term131State8NormalizeRawChunk6Normal ++ (table0Term131State8NormalizeRawChunk7Normal ++ (table0Term131State8NormalizeRawChunk8Normal ++ (table0Term131State8NormalizeRawChunk9Normal ++ (table0Term131State8NormalizeRawChunk10Normal ++ (table0Term131State8NormalizeRawChunk11Normal ++ (table0Term131State8NormalizeRawChunk12Normal ++ (table0Term131State8NormalizeRawChunk13Normal ++ (table0Term131State8NormalizeRawChunk14Normal ++ (table0Term131State8NormalizeRawChunk15Normal ++ (table0Term131State8NormalizeRawChunk16Normal ++ (table0Term131State8NormalizeRawChunk17Normal ++ (table0Term131State8NormalizeRawChunk18Normal ++ (table0Term131State8NormalizeRawChunk19Normal ++ table0Term131State8NormalizeRawChunk20Normal))))))))))))))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
