import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term51Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term51State8Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term51_state9_certificate :
    SparsePolynomial.mul table0Term51State8Normal (elementaryPolynomials 4) = table0Term51Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
