import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State8NormalizeRadix0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term131_state8_normalize_combine_certificate :
    SparsePolynomial.combine table0Term131State8NormalizeRadix0Normal = table0Term131Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
