import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk0Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk1Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk2Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk3Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk4Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk5Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk6Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term85State9NormalizeRadix4FlattenChunk9Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

def table0Term85State9NormalizeRadix4BucketsNormal : List SparsePolynomial :=
  (table0Term85State9NormalizeRadix4FlattenChunk0BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk1BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk2BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk3BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk4BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk5BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk6BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk7BucketsNormal ++ (table0Term85State9NormalizeRadix4FlattenChunk8BucketsNormal ++ table0Term85State9NormalizeRadix4FlattenChunk9BucketsNormal)))))))))

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
