import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term87State8NormalizeRadix0Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term87_state8_normalize_combine_certificate :
    SparsePolynomial.combine table0Term87State8NormalizeRadix0Normal = table0Term87State8Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
