import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawLeftChunk7Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term131State7NormalizeRawChunk7Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term131_state7_normalize_raw_chunk7_certificate :
    SparsePolynomial.rawMul table0Term131State7NormalizeRawLeftChunk7Normal (elementaryPolynomials 2) = table0Term131State7NormalizeRawChunk7Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
