import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRawLeftChunk19Data

import PolynomialFormulas.ComputableDummitKernelCertificateTable0Term90State8NormalizeRawChunk19Data

namespace LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate

open LeanProofs.PolynomialFormulas.ComputableDummitCoefficients

set_option maxRecDepth 1000000

set_option maxHeartbeats 20000000

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 20000000 in
theorem table0_term90_state8_normalize_raw_chunk19_certificate :
    SparsePolynomial.rawMul table0Term90State8NormalizeRawLeftChunk19Normal (elementaryPolynomials 2) = table0Term90State8NormalizeRawChunk19Normal := by
  decide

end LeanProofs.PolynomialFormulas.ComputableDummitCoefficients.KernelCertificate
