import PolynomialFormulas.LazardQuinticSectionFiveCombinedAction

/-!
# Kernel audit for Lazard's corrected Section 5 combined action

This focused audit keeps the corrected Section 5 proof independently
checkable without importing the much larger, still evolving Lazard audit
surface.
-/

open LeanProofs.PolynomialFormulas

#check LazardQuintic.FifthRootOfUnity.primitive_cases
#check LazardQuintic.sectionFiveFourierS_s0_eq_zero_of_centered
#check LazardQuintic.sectionFiveCyclicS_permute_fiveCycle
#check LazardQuintic.sectionFive_x0_recover_from_s1_cyclicS
#check LazardQuintic.sectionFive_phi_psi_commute
#check LazardQuintic.sectionFive_phi_T_eq_neg_printedU
#check LazardQuintic.sectionFive_phi_printedU_eq_T
#check LazardQuintic.rootFourierOrbit_phiPsi_fixed
#check LazardQuintic.sectionFiveFourierS_phiPsi_fixed
#check LazardQuintic.sectionFiveCyclicS_phiPsi_fixed
#check LazardQuintic.rootQuadraticTriple_phiPsi_fixed
#check LazardQuintic.rootFourierFifthOrbit_phiPsi_fixed
#check LazardQuintic.omegaSquared_independent_of_phi_invariant
#check LazardQuintic.primitiveFifthRoot_independent_of_squared
#check LazardQuintic.rootPrintedSectionFiveForwardSource_eq_phiIterates
#check LazardQuintic.rootFormulaConventionProjectionValues_eq_printed_I1_I2_I3_neg_I4
#check LazardQuintic.rootFormulaConventionProjectionValues_phi_fixed
#check LazardQuintic.rootFormulaConventionProjectionValues_phiPsi_fixed
#check LazardQuintic.rootFormulaConventionProjectionValues_squared
#check LazardQuintic.rootFormulaConventionProjectionValues_primitiveRoot_independent

#print axioms LazardQuintic.FifthRootOfUnity.primitive_cases
#print axioms LazardQuintic.sectionFiveFourierS_s0_eq_zero_of_centered
#print axioms LazardQuintic.sectionFiveCyclicS_permute_fiveCycle
#print axioms LazardQuintic.sectionFive_x0_recover_from_s1_cyclicS
#print axioms LazardQuintic.sectionFive_phi_psi_commute
#print axioms LazardQuintic.sectionFive_phi_T_eq_neg_printedU
#print axioms LazardQuintic.sectionFive_phi_printedU_eq_T
#print axioms LazardQuintic.rootFourierOrbit_phiPsi_fixed
#print axioms LazardQuintic.sectionFiveFourierS_phiPsi_fixed
#print axioms LazardQuintic.sectionFiveCyclicS_phiPsi_fixed
#print axioms LazardQuintic.rootQuadraticTriple_phiPsi_fixed
#print axioms LazardQuintic.rootFourierFifthOrbit_phiPsi_fixed
#print axioms LazardQuintic.omegaSquared_independent_of_phi_invariant
#print axioms LazardQuintic.primitiveFifthRoot_independent_of_squared
#print axioms LazardQuintic.rootPrintedSectionFiveForwardSource_eq_phiIterates
#print axioms LazardQuintic.rootFormulaConventionProjectionValues_eq_printed_I1_I2_I3_neg_I4
#print axioms LazardQuintic.rootFormulaConventionProjectionValues_phi_fixed
#print axioms LazardQuintic.rootFormulaConventionProjectionValues_phiPsi_fixed
#print axioms LazardQuintic.rootFormulaConventionProjectionValues_squared
#print axioms LazardQuintic.rootFormulaConventionProjectionValues_primitiveRoot_independent
