"""Regenerate a machine-readable catalogue from exact formulas, never by fitting."""
from pathlib import Path
import json
import sympy as sp
from mellin_exact import compact,jet,moment,central,low

root=Path(__file__).resolve().parents[1]
rows=[]
def add(kind,params,formula,label):
    rows.append({'id':f'BMH-{len(rows)+1:04d}','kind':kind,**params,
       'formula_sympy':str(formula),'formula_latex':sp.latex(formula),
       'proof_label':label,'status':'analytic identity; symbolic formula generated by exact arithmetic'})
for W in range(2,13):
    for m in range(1,W//2+1):
        n=W-m
        add('unit_scale_resonance',{'m':m,'n':n,'h':0,'a':0,'N':1},low(compact(m,n)),'bmh:thm:compact')
for W in range(2,7):
    for m in range(1,W//2+1):
        n=W-m
        for h in [1,2]:
            add('logarithmic_resonance',{'m':m,'n':n,'h':h,'a':0,'N':1},low(jet(m,n,h)),'bmh:thm:jets')
        add('negative_resonance',{'m':m,'n':n,'h':0,'a':-1,'N':1},low(jet(m,n,0,True)),'bmh:cor:negative')
for N in range(2,5):
    for a in range(-1,N):
        for m,n in [(1,1),(2,1),(2,2),(3,1),(3,2)]:
            add('integer_kernel',{'m':m,'n':n,'h':0,'a':a,'N':N},low(moment(N,a,m,n)),'bmh:thm:kernel')
for W in range(2,9):
    for m in range(1,W//2+1):
        n=W-m;h=1 if W%2==0 else 0
        add('central_parity',{'m':m,'n':n,'h':h,'a':'1/2','N':1},central(m,n,h),'bmh:thm:central')
record={'conventions':{'Z(A,B)':'sum over integers n>m>=1 of 1/(n**A*m**B)',
 'zeta(s)':'ordinary Riemann zeta','orders':'positive integers',
 'LHS':'d^h/da^h integral_0^infinity x^(a-1) Li_m(-x) Li_n(-x)/(1+x)^N dx'},
 'number_of_identities':len(rows),'identities':rows}
(root/'data/formula_table.json').write_text(json.dumps(record,indent=2)+'\n')
print('Exported',len(rows),'exact formula records')
