#!/usr/bin/env python3
"""Generate the full 93-instruction certificate and 22 equality tests."""
from pathlib import Path

import round34_1980_factored_mask_certificate as certificate
from round24_26_1980_schedule_tables import generate


if __name__ == "__main__":
    generate(certificate, 93, "93")
    output = (Path(__file__).resolve().parent.parent / "1980"
              / "jones1980_theorem5_93_schedule.tex")
    text = output.read_text(encoding="utf-8")
    text = text.replace("Generated by round24_26_1980_schedule_tables.py",
                        "Generated by round34_1980_schedule_table.py")
    output.write_text(text, encoding="utf-8", newline="\n")
