#!/usr/bin/env python3
"""Generate all 90 primitive instructions and 22 free equality tests."""
from pathlib import Path

import round37_1980_binary_product_certificate as certificate
from round24_26_1980_schedule_tables import generate


if __name__ == '__main__':
    generate(certificate, 90, '90')
    output = (Path(__file__).resolve().parent.parent / '1980'
              / 'jones1980_theorem5_90_schedule.tex')
    text = output.read_text(encoding='utf-8')
    text = text.replace('Generated by round24_26_1980_schedule_tables.py',
                        'Generated by round37_1980_schedule_table.py')
    assert text.count('The twenty-two free equality tests are') == 1
    assert len(certificate.EQUALITIES) == 22
    output.write_text(text, encoding='utf-8', newline='\n')
