#!/usr/bin/env python3
"""Generate the frozen 105-instruction appendix, with exponent L=2^32."""
from pathlib import Path

import round16_1980_index_multiple_certificate as certificate


def tex(value):
    if isinstance(value, int):
        return r"2^{32}" if value == certificate.L else str(value)
    return r"\mathit{" + value.replace("_", r"\_") + "}"


def main():
    receipt = certificate.verify_certificate()
    assert receipt["operations"] == len(certificate.SCHEDULE) == 105
    rows = []
    for number, (target, operation, left, right) in enumerate(certificate.SCHEDULE, 1):
        symbol = {"+": "+", "-": "-", "*": r"\cdot"}[operation]
        assignment = f"{tex(target)} = {tex(left)} {symbol} {tex(right)}"
        check = (f"{tex(target)} + {tex(right)} = {tex(left)}" if operation == "-"
                 else f"{tex(left)} {symbol} {tex(right)} = {tex(target)}")
        rows.append(f"{number} & ${assignment}$ & ${check}$ " + r"\\")
    header = r"""% Generated by round16_1980_schedule_table.py; do not edit.
\begin{longtable}{@{}rll@{}}
\toprule
No. & Assignment & Addition/multiplication check\\
\midrule
\endfirsthead
\toprule
No. & Assignment & Addition/multiplication check\\
\midrule
\endhead
\bottomrule
\endfoot
"""
    equalities = [f"{tex(left)}={tex(right)}" for left, right in certificate.EQUALITIES]
    equality_rows = [r",\quad ".join(equalities[start:start + 3])
                     for start in range(0, len(equalities), 3)]
    ending = ("\n" + r"\end{longtable}" + "\n\n"
              + "The twenty-two free equality tests are\n"
              + r"\[\begin{array}{@{}l@{}}" + "\n"
              + (r",\\" + "\n").join(equality_rows) + "\n"
              + r"\end{array}\]" + "\n")
    output = Path(__file__).resolve().parent.parent / "1980" / "jones1980_theorem5_105_schedule.tex"
    output.write_text(header + "\n".join(rows) + ending, encoding="utf-8", newline="\n")
    print(f"Generated {len(rows)} instructions and {len(equalities)} equality tests: {output.name}")


if __name__ == "__main__":
    main()
