import Surreal.HahnSeries.NeumannWords

/-!
# Recovering rare entries from first-error masses

This file proves `meas:lem:recover` in
`docs/surreal/hahn-valued-measures-and-probability/article.tex`, together with the two
displayed identities `meas:eq:survival` and `meas:eq:recover` of its proof.

Rare entries `p_{n,j}` are indexed by the sigma type `Σ n, J n`, with finitely many
indices `j : J n` at each level `n`. Put `q_n = ∑_j p_{n,j}`, the survival product
`∏_{k<n} (1 - q_k)`, the first-error masses `h_{n,j} = p_{n,j} ∏_{k<n} (1 - q_k)`, and
`H_{<n} = ∑_{k<n} ∑_j h_{k,j}`. Levels are indexed from `0` rather than `1`, so the
products and sums over `k < n` run over `Finset.range n`; this is a harmless reindexing.

The following are proved.

* `survival_eq` is `meas:eq:survival`: `∏_{k<n} (1 - q_k) = 1 - H_{<n}`, a purely algebraic
  identity with no hypothesis.
* `eq_firstError_mul_hsum_powers` and `hsum_firstError_smul_powers` are `meas:eq:recover` in
  its strong-sum form `p_{n,j} = ∑ˢ_m h_{n,j} H_{<n}^m`, and `eq_firstError_mul_inv` is its
  form `p_{n,j} = h_{n,j} (1 - H_{<n})⁻¹` over a coefficient field.
* `stronglySummable_iff_firstError` is `meas:lem:recover`: if every `p_{n,j}` has positive
  order (zero allowed), then `(p_{n,j})` is strongly summable if and only if `(h_{n,j})` is.
* `stronglySummable_firstError_mul_pow`: when every `p_{n,j}` has positive order and
  `(h_{n,j})` (equivalently `(p_{n,j})`) is strongly summable, the double family
  `(h_{n,j} H_{<n}^m)_{(n,j),m}` is strongly summable. This is the assertion of the source
  proof that `meas:eq:recover` is strongly summable simultaneously for all `(n,j)`, with no
  uniform bound on `n` or `m`.
* `StronglySummable` and `stronglySummable_iff` restate `meas:def:summability` as membership
  in a Mathlib `SummableFamily`.

The source works with real coefficients and an ordered abelian exponent group. Everything
except the inverse form of `meas:eq:recover` is proved here for any commutative coefficient
ring and any linearly ordered cancellative commutative exponent monoid.

The proof does not expand the finite products into labelled words. Instead, a family `f`
is strongly summable as soon as the support of each `f i` lies in the support of `a i` plus
the additive monoid generated by the supports of a strongly summable positive-order family
`a`; at a fixed exponent, the finite antidiagonals of Neumann's lemma leave finitely many
possible leading exponents and hence finitely many indices. Both directions of
`meas:lem:recover` reduce to this bound, since the survival products and the geometric
series `∑ˢ_m H_{<n}^m` have supports in the generated monoid.
-/

namespace Surreal.FirstError

open _root_.HahnSeries Surreal.HahnSeries
open scoped Pointwise

noncomputable section

section Summable

variable {Γ R : Type*} [PartialOrder Γ] [AddCommMonoid R]

/-- `meas:def:summability`: a family of Hahn series is strongly summable if it is the family
of members of a Mathlib `SummableFamily`. -/
def StronglySummable {ι : Type*} (f : ι → R⟦Γ⟧) : Prop :=
  ∃ s : SummableFamily Γ R ι, ∀ i, s i = f i

/-- The two clauses of `meas:def:summability`: the union of the supports is partially well
ordered (equivalently, well ordered when `Γ` is linearly ordered), and each exponent lies in
the supports of only finitely many members. -/
theorem stronglySummable_iff {ι : Type*} (f : ι → R⟦Γ⟧) :
    StronglySummable f ↔
      (⋃ i, (f i).support).IsPWO ∧ ∀ g : Γ, {i | (f i).coeff g ≠ 0}.Finite := by
  constructor
  · rintro ⟨s, hs⟩
    have hf : f = fun i => s i := funext fun i => (hs i).symm
    subst hf
    exact ⟨s.isPWO_iUnion_support, s.finite_co_support⟩
  · rintro ⟨hpwo, hfin⟩
    exact ⟨⟨f, hpwo, hfin⟩, fun _ => rfl⟩

end Summable

section Support

variable {Γ R : Type*} [AddCommMonoid Γ] [LinearOrder Γ] [IsOrderedCancelAddMonoid Γ]
  [CommRing R]

omit [IsOrderedCancelAddMonoid Γ] in
/-- A Hahn series whose support is positive has positive order. -/
theorem orderTop_pos_of_forall_support {x : R⟦Γ⟧} (h : ∀ g ∈ x.support, 0 < g) :
    0 < x.orderTop := by
  by_cases hx : x = 0
  · simp [hx]
  rw [← order_eq_orderTop_of_ne_zero hx]
  exact WithTop.coe_lt_coe.mpr (h _ fun h0 => hx (coeff_order_eq_zero.mp h0))

omit [IsOrderedCancelAddMonoid Γ] in
/-- A Hahn series of positive order has positive support. -/
theorem pos_of_mem_support {x : R⟦Γ⟧} (h : 0 < x.orderTop) {g : Γ} (hg : g ∈ x.support) :
    0 < g :=
  WithTop.coe_lt_coe.mp (h.trans_le (orderTop_le_of_coeff_ne_zero ((mem_support _ _).mp hg)))

omit [IsOrderedCancelAddMonoid Γ] in
/-- A finite sum of positive-order Hahn series has positive order. -/
theorem orderTop_sum_pos {ι : Type*} (s : Finset ι) (f : ι → R⟦Γ⟧)
    (h : ∀ i ∈ s, 0 < (f i).orderTop) : 0 < (∑ i ∈ s, f i).orderTop :=
  Finset.sum_induction f (fun x => 0 < x.orderTop)
    (fun _ _ ha hb => (lt_min ha hb).trans_le min_orderTop_le_orderTop_add) (by simp) h

omit [CommRing R] in
/-- The additive monoid generated by positive elements consists of nonnegative elements. -/
theorem nonneg_of_mem_closure {S : Set Γ} (hS : ∀ g ∈ S, 0 < g) {g : Γ}
    (hg : g ∈ AddSubmonoid.closure S) : 0 ≤ g := by
  induction hg using AddSubmonoid.closure_induction with
  | mem x hx => exact (hS x hx).le
  | zero => exact le_rfl
  | add x y _ _ hx hy => exact add_nonneg hx hy

omit [IsOrderedCancelAddMonoid Γ] in
/-- Each member's support lies in the monoid generated by all the supports. -/
theorem support_subset_closure {I : Type*} (a : I → R⟦Γ⟧) (i : I) :
    (a i).support ⊆ AddSubmonoid.closure (⋃ i, (a i).support) :=
  (Set.subset_iUnion (fun i => (a i).support) i).trans AddSubmonoid.subset_closure

/-- The Hahn series whose supports lie in a fixed additive submonoid form a subring. -/
def supportSubring (C : AddSubmonoid Γ) : Subring R⟦Γ⟧ where
  carrier := {x | x.support ⊆ C}
  mul_mem' {x y} hx hy g hg := by
    obtain ⟨a, ha, b, hb, rfl⟩ := support_mul_subset hg
    exact C.add_mem (hx ha) (hy hb)
  one_mem' g hg := by
    have hg' : (1 : R⟦Γ⟧).coeff g ≠ 0 := hg
    rw [coeff_one] at hg'
    split_ifs at hg' with h
    · exact h ▸ C.zero_mem
    · exact absurd rfl hg'
  add_mem' {x y} hx hy := (support_add_subset x y).trans (Set.union_subset hx hy)
  zero_mem' := by
    change (0 : R⟦Γ⟧).support ⊆ C
    simp
  neg_mem' {x} hx := by
    change (-x).support ⊆ C
    rwa [support_neg]

/-- Membership in `supportSubring`: the support lies in the submonoid. -/
theorem mem_supportSubring {C : AddSubmonoid Γ} {x : R⟦Γ⟧} :
    x ∈ supportSubring C ↔ x.support ⊆ C := Iff.rfl

/-- The domination criterion behind `meas:lem:recover`. Let `a` be a strongly summable
family of positive order, grouped by a map `π` into the index set of `a`. If the support of
each `f k` lies in the support of `a (π k)` plus the monoid generated by the supports of `a`,
and every fibre of `π` contributes finitely many members at each exponent, then `f` is
strongly summable. -/
theorem stronglySummable_of_support_subset_fibre {I K : Type*} {a : I → R⟦Γ⟧}
    (ha : StronglySummable a) (hpos : ∀ i, 0 < (a i).orderTop) (π : K → I) (f : K → R⟦Γ⟧)
    (hf : ∀ k, (f k).support ⊆
      (a (π k)).support + (AddSubmonoid.closure (⋃ i, (a i).support) : Set Γ))
    (hfib : ∀ i γ, {k | π k = i ∧ (f k).coeff γ ≠ 0}.Finite) : StronglySummable f := by
  classical
  obtain ⟨s, hs⟩ := ha
  have hsa : a = fun i => s i := funext fun i => (hs i).symm
  subst hsa
  have hS := s.isPWO_iUnion_support
  have hSpos : ∀ g ∈ ⋃ i, (s i).support, 0 < g := fun g hg => by
    obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hg
    exact pos_of_mem_support (hpos i) hi
  have hC := isPWO_closure_of_pos hS hSpos
  refine ⟨⟨f, ?_, fun γ => ?_⟩, fun _ => rfl⟩
  · refine hC.mono (Set.iUnion_subset fun k g hg => ?_)
    obtain ⟨x, hx, y, hy, rfl⟩ := hf k hg
    exact AddSubmonoid.add_mem _
      (AddSubmonoid.subset_closure (Set.mem_iUnion.mpr ⟨π k, hx⟩)) hy
  · refine ((Finset.antidiagonal hS hC γ).finite_toSet.biUnion fun xy _ =>
      (s.finite_co_support xy.1).biUnion fun i _ => hfib i γ).subset fun k hk => ?_
    obtain ⟨x, hx, y, hy, hxy⟩ := hf k ((mem_support _ _).mpr hk)
    refine Set.mem_biUnion (x := (x, y)) ?_
      (Set.mem_biUnion (x := π k) ((mem_support _ _).mp hx) ⟨rfl, hk⟩)
    rw [Finset.mem_coe, Finset.mem_antidiagonal]
    exact ⟨Set.mem_iUnion.mpr ⟨π k, hx⟩, hy, hxy⟩

/-- The domination criterion with one member of `f` for each member of `a`. -/
theorem stronglySummable_of_support_subset {I : Type*} {a : I → R⟦Γ⟧}
    (ha : StronglySummable a) (hpos : ∀ i, 0 < (a i).orderTop) (f : I → R⟦Γ⟧)
    (hf : ∀ i, (f i).support ⊆
      (a i).support + (AddSubmonoid.closure (⋃ i, (a i).support) : Set Γ)) :
    StronglySummable f :=
  stronglySummable_of_support_subset_fibre ha hpos id f hf fun i _ =>
    (Set.finite_singleton i).subset fun _ hk => hk.1

end Support

section FirstError

variable {Γ R : Type*} [AddCommMonoid Γ] [LinearOrder Γ] [IsOrderedCancelAddMonoid Γ]
  [CommRing R] {J : ℕ → Type*} [∀ n, Fintype (J n)] (p : (Σ n, J n) → R⟦Γ⟧)

/-- The row sum `q_n = ∑_j p_{n,j}` of `meas:eq:first-error`. -/
def rowSum (n : ℕ) : R⟦Γ⟧ :=
  ∑ j, p ⟨n, j⟩

/-- The survival product `∏_{k<n} u_k = ∏_{k<n} (1 - q_k)` of `meas:eq:first-error`. -/
def survival (n : ℕ) : R⟦Γ⟧ :=
  ∏ k ∈ Finset.range n, (1 - rowSum p k)

/-- The first-error mass `h_{n,j} = p_{n,j} ∏_{k<n} u_k` of `meas:eq:first-error`. -/
def firstError (i : Σ n, J n) : R⟦Γ⟧ :=
  p i * survival p i.1

/-- The accumulated first-error mass `H_{<n} = ∑_{k<n} ∑_j h_{k,j}` of
`meas:eq:survival`. -/
def firstErrorMass (n : ℕ) : R⟦Γ⟧ :=
  ∑ k ∈ Finset.range n, ∑ j, firstError p ⟨k, j⟩

/-- `meas:eq:survival`: finite telescoping gives `∏_{k<n} u_k = 1 - H_{<n}`. -/
theorem survival_eq (n : ℕ) : survival p n = 1 - firstErrorMass p n := by
  induction n with
  | zero => simp [survival, firstErrorMass]
  | succ n ih =>
    have hrow : survival p n * rowSum p n = ∑ j, firstError p ⟨n, j⟩ := by
      rw [rowSum, Finset.mul_sum]
      exact Finset.sum_congr rfl fun j _ => mul_comm _ _
    have hmass : firstErrorMass p (n + 1) = firstErrorMass p n + ∑ j, firstError p ⟨n, j⟩ :=
      Finset.sum_range_succ _ _
    rw [survival, Finset.prod_range_succ, ← survival, mul_sub, mul_one, hrow, ih, hmass]
    ring

/-- Survival products have support in the monoid generated by the supports of the entries. -/
theorem survival_mem (n : ℕ) :
    survival p n ∈ supportSubring (AddSubmonoid.closure (⋃ i, (p i).support)) :=
  prod_mem fun k _ => sub_mem (one_mem _)
    (sum_mem fun j _ => support_subset_closure p ⟨k, j⟩)

/-- Accumulated first-error masses have support in the monoid generated by the supports of
the first-error masses. -/
theorem firstErrorMass_mem (n : ℕ) :
    firstErrorMass p n ∈
      supportSubring (AddSubmonoid.closure (⋃ i, (firstError p i).support)) :=
  sum_mem fun k _ => sum_mem fun j _ => support_subset_closure (firstError p) ⟨k, j⟩

variable {p}

/-- First-error masses of positive-order entries have positive order. -/
theorem orderTop_firstError_pos (hp : ∀ i, 0 < (p i).orderTop) (i : Σ n, J n) :
    0 < (firstError p i).orderTop := by
  refine orderTop_pos_of_forall_support fun g hg => ?_
  obtain ⟨x, hx, y, hy, rfl⟩ := support_mul_subset hg
  refine add_pos_of_pos_of_nonneg (pos_of_mem_support (hp i) hx) ?_
  refine nonneg_of_mem_closure (fun g hg => ?_) (survival_mem p i.1 hy)
  obtain ⟨k, hk⟩ := Set.mem_iUnion.mp hg
  exact pos_of_mem_support (hp k) hk

/-- The accumulated mass `H_{<n}` has positive order, as used for `meas:eq:recover`. -/
theorem orderTop_firstErrorMass_pos (hp : ∀ i, 0 < (p i).orderTop) (n : ℕ) :
    0 < (firstErrorMass p n).orderTop :=
  orderTop_sum_pos _ _ fun _ _ => orderTop_sum_pos _ _ fun _ _ => orderTop_firstError_pos hp _

/-- `meas:eq:recover`: `p_{n,j} = h_{n,j} ∑ˢ_m H_{<n}^m`, where the geometric series is the
strong sum of the powers of the positive-order series `H_{<n}`. -/
theorem eq_firstError_mul_hsum_powers (hp : ∀ i, 0 < (p i).orderTop) (i : Σ n, J n) :
    p i = firstError p i * (SummableFamily.powers (firstErrorMass p i.1)).hsum := by
  calc p i = p i * ((1 - firstErrorMass p i.1) *
        (SummableFamily.powers (firstErrorMass p i.1)).hsum) := by
        rw [SummableFamily.one_sub_self_mul_hsum_powers (orderTop_firstErrorMass_pos hp _),
          mul_one]
    _ = firstError p i * (SummableFamily.powers (firstErrorMass p i.1)).hsum := by
        rw [firstError, survival_eq, mul_assoc]

/-- The members `h_{n,j} H_{<n}^m` of the strong sum in `meas:eq:recover`. -/
theorem firstError_smul_powers_apply (hp : ∀ i, 0 < (p i).orderTop) (i : Σ n, J n) (m : ℕ) :
    (firstError p i • SummableFamily.powers (firstErrorMass p i.1)) m =
      firstError p i * firstErrorMass p i.1 ^ m := by
  rw [SummableFamily.smul_apply, of_symm_smul_of_eq_mul,
    SummableFamily.powers_of_orderTop_pos (orderTop_firstErrorMass_pos hp _)]

/-- `meas:eq:recover` as a strong sum: `p_{n,j} = ∑ˢ_m h_{n,j} H_{<n}^m`. -/
theorem hsum_firstError_smul_powers (hp : ∀ i, 0 < (p i).orderTop) (i : Σ n, J n) :
    (firstError p i • SummableFamily.powers (firstErrorMass p i.1)).hsum = p i := by
  rw [SummableFamily.hsum_smul, ← eq_firstError_mul_hsum_powers hp i]

/-- `meas:lem:recover`: for entries of positive order (zero allowed), with finitely many
entries at each level, `(p_{n,j})` is strongly summable if and only if the family of
first-error masses `(h_{n,j})` is. -/
theorem stronglySummable_iff_firstError (hp : ∀ i, 0 < (p i).orderTop) :
    StronglySummable p ↔ StronglySummable (firstError p) := by
  constructor
  · intro hs
    exact stronglySummable_of_support_subset hs hp _ fun i =>
      support_mul_subset.trans (Set.add_subset_add subset_rfl (survival_mem p i.1))
  · intro hs
    refine stronglySummable_of_support_subset hs (orderTop_firstError_pos hp) _ fun i => ?_
    rw [eq_firstError_mul_hsum_powers hp i]
    refine support_mul_subset.trans (Set.add_subset_add subset_rfl ?_)
    refine SummableFamily.support_hsum_subset.trans (Set.iUnion_subset fun m => ?_)
    rw [SummableFamily.powers_of_orderTop_pos (orderTop_firstErrorMass_pos hp _)]
    exact pow_mem (firstErrorMass_mem p i.1) m

/-- The proof of `meas:lem:recover`: when the first-error masses are strongly summable, the
double family `(h_{n,j} H_{<n}^m)_{(n,j),m}` of all terms of `meas:eq:recover` is strongly
summable, with no uniform bound on the level `n` or the power `m`. -/
theorem stronglySummable_firstError_mul_pow (hp : ∀ i, 0 < (p i).orderTop)
    (hs : StronglySummable (firstError p)) :
    StronglySummable fun x : (Σ n, J n) × ℕ =>
      firstError p x.1 * firstErrorMass p x.1.1 ^ x.2 := by
  refine stronglySummable_of_support_subset_fibre hs (orderTop_firstError_pos hp) Prod.fst _
    (fun x => support_mul_subset.trans (Set.add_subset_add subset_rfl
      (pow_mem (firstErrorMass_mem p x.1.1) x.2))) fun i γ => ?_
  have hfin :=
    (firstError p i • SummableFamily.powers (firstErrorMass p i.1)).finite_co_support γ
  refine (hfin.image fun m => (i, m)).subset ?_
  rintro ⟨i', m⟩ ⟨rfl, hk⟩
  refine ⟨m, ?_, rfl⟩
  change ((firstError p i' • SummableFamily.powers (firstErrorMass p i'.1)) m).coeff γ ≠ 0
  rwa [firstError_smul_powers_apply hp]

end FirstError

section Field

variable {Γ R : Type*} [AddCommGroup Γ] [LinearOrder Γ] [IsOrderedAddMonoid Γ] [Field R]
  {J : ℕ → Type*} [∀ n, Fintype (J n)] {p : (Σ n, J n) → R⟦Γ⟧}

/-- `meas:eq:recover`: over a coefficient field, `p_{n,j} = h_{n,j} (1 - H_{<n})⁻¹`. -/
theorem eq_firstError_mul_inv (hp : ∀ i, 0 < (p i).orderTop) (i : Σ n, J n) :
    p i = firstError p i * (1 - firstErrorMass p i.1)⁻¹ := by
  rw [inv_eq_of_mul_eq_one_right
    (SummableFamily.one_sub_self_mul_hsum_powers (orderTop_firstErrorMass_pos hp i.1))]
  exact eq_firstError_mul_hsum_powers hp i

end Field

end

end Surreal.FirstError
