import Surreal.HahnSeries.NeumannWords
import Surreal.HahnSeries.Regroup

/-!
# Infinite positive-order products and ratio families

This file proves `prop:products` in
`docs/surreal/hahn-valued-measures-and-probability/article.tex`.

For a strongly summable family `q` of positive-order Hahn series, the products
over all finite subsets of indices form a strongly summable family; this is the
finite-subset subfamily of `lem:labeled`. Its strong sum with alternating signs
is the infinite product `U = ∏ (1 - q_n)` of equation (13). Every nonempty
subset contributes a positive-order term, so `U - 1` has positive order and `U`
is a unit.

For a strongly summable positive-order family `a`, grouped into rows by any map
`g`, with row sums `q_n`, the ratios `a_i/(1 - q_{g(i)})` form a strongly
summable family, and in particular so do `q_n/(1 - q_n)`, as in equation (14).
The source's rows have finitely many entries; here the rows may be arbitrary
strongly summable subfamilies. The proof bounds supports by the additive monoid
generated by the positive support set and uses its finite antidiagonals, so no
limiting argument is involved.
-/

namespace Surreal.HahnSeries

open _root_.HahnSeries

noncomputable section

variable {Γ R I N : Type*} [AddCommGroup Γ] [LinearOrder Γ] [IsOrderedAddMonoid Γ] [Field R]

theorem orderTop_pos_of_support_pos {x : R⟦Γ⟧} (h : ∀ g ∈ x.support, 0 < g) :
    0 < x.orderTop := by
  by_cases hx : x = 0
  · simp [hx]
  rw [← order_eq_orderTop_of_ne_zero hx]
  exact WithTop.coe_lt_coe.mpr (h _ fun h0 => hx (coeff_order_eq_zero.mp h0))

omit [IsOrderedAddMonoid Γ] in
theorem support_pos_of_orderTop_pos {x : R⟦Γ⟧} (h : 0 < x.orderTop) :
    ∀ g ∈ x.support, 0 < g := fun _ hg =>
  WithTop.coe_lt_coe.mp (h.trans_le (orderTop_le_of_coeff_ne_zero ((mem_support _ _).mp hg)))

theorem finset_toList_injective : Function.Injective (Finset.toList : Finset I → List I) := by
  classical
  intro F G h
  rw [← Finset.toList_toFinset F, h, Finset.toList_toFinset]

/-- Products over finite subsets of a strongly summable positive-order family. -/
def finsetProductFamily (s : SummableFamily Γ R I) (hpos : ∀ i, 0 < (s i).orderTop) :
    SummableFamily Γ R (Finset I) where
  toFun F := ∏ i ∈ F, s i
  isPWO_iUnion_support' := by
    refine (labeledWordFamily s hpos).isPWO_iUnion_support.mono (Set.iUnion_subset fun F => ?_)
    intro g hg
    refine Set.mem_iUnion.mpr ⟨F.toList, ?_⟩
    rwa [labeledWordFamily_apply, Finset.prod_map_toList]
  finite_co_support' γ := by
    refine (((labeledWordFamily s hpos).finite_co_support γ).preimage
      finset_toList_injective.injOn).subset fun F hF => ?_
    change (labeledWordFamily s hpos F.toList).coeff γ ≠ 0
    rw [labeledWordFamily_apply, Finset.prod_map_toList]
    exact hF

@[simp]
theorem finsetProductFamily_apply (s : SummableFamily Γ R I) (hpos : ∀ i, 0 < (s i).orderTop)
    (F : Finset I) : finsetProductFamily s hpos F = ∏ i ∈ F, s i := rfl

theorem orderTop_prod_pos (a : I → R⟦Γ⟧) (hpos : ∀ i, 0 < (a i).orderTop) {F : Finset I}
    (hF : F.Nonempty) : 0 < (∏ i ∈ F, a i).orderTop := by
  classical
  induction F using Finset.induction_on with
  | empty => exact absurd hF Finset.not_nonempty_empty
  | insert i F hi ih =>
    rw [Finset.prod_insert hi, orderTop_mul]
    by_cases hF' : F.Nonempty
    · exact add_pos_of_pos_of_nonneg (hpos i) (ih hF').le
    · rw [Finset.not_nonempty_iff_eq_empty.mp hF', Finset.prod_empty, orderTop_one, add_zero]
      exact hpos i

/-- The finite-subset products sum to `1` plus a positive-order series. -/
theorem orderTop_hsum_finsetProductFamily_sub_one_pos (s : SummableFamily Γ R I)
    (hpos : ∀ i, 0 < (s i).orderTop) :
    0 < ((finsetProductFamily s hpos).hsum - 1).orderTop := by
  classical
  have hcoeff : ∀ g : Γ, g ≤ 0 → ((finsetProductFamily s hpos).hsum - 1).coeff g = 0 := by
    intro g hg
    rw [coeff_sub, SummableFamily.coeff_hsum, finsum_eq_single _ ∅]
    · simp
    · intro F hF
      exact coeff_eq_zero_of_lt_orderTop (lt_of_le_of_lt (WithTop.coe_le_coe.mpr hg)
        (orderTop_prod_pos s hpos (Finset.nonempty_iff_ne_empty.mpr hF)))
  refine orderTop_pos_of_support_pos fun g hg => ?_
  by_contra h
  exact (mem_support _ _).mp hg (hcoeff g (not_lt.mp h))

/-- Equation (13): the infinite product `U = ∏ (1 - q_n)`, defined as the strong
sum over finite subsets of `(-1)^{|F|} ∏_{n ∈ F} q_n`. -/
def oneSubProduct (q : SummableFamily Γ R I) (hpos : ∀ i, 0 < (q i).orderTop) : R⟦Γ⟧ :=
  (finsetProductFamily (-q) fun i => by simpa [orderTop_neg] using hpos i).hsum

theorem oneSubProduct_term (q : SummableFamily Γ R I) (F : Finset I) :
    ∏ i ∈ F, (-q) i = (-1) ^ F.card * ∏ i ∈ F, q i := by
  simp only [SummableFamily.neg_apply, Finset.prod_neg]

/-- `prop:products`: `U ∈ 1 + 𝔪`. -/
theorem orderTop_oneSubProduct_sub_one_pos (q : SummableFamily Γ R I)
    (hpos : ∀ i, 0 < (q i).orderTop) : 0 < (oneSubProduct q hpos - 1).orderTop :=
  orderTop_hsum_finsetProductFamily_sub_one_pos _ _

/-- `prop:products`: `U` is a unit. -/
theorem isUnit_oneSubProduct (q : SummableFamily Γ R I) (hpos : ∀ i, 0 < (q i).orderTop) :
    IsUnit (oneSubProduct q hpos) :=
  isUnit_of_orderTop_pos (orderTop_oneSubProduct_sub_one_pos q hpos)

/-- The geometric inverse has support in the monoid generated by the ratio. -/
theorem support_inv_one_sub_subset {q : R⟦Γ⟧} (hq : 0 < q.orderTop) :
    ((1 - q)⁻¹).support ⊆ AddSubmonoid.closure q.support := by
  rw [inv_eq_of_mul_eq_one_right (SummableFamily.one_sub_self_mul_hsum_powers hq)]
  refine SummableFamily.support_hsum_subset.trans (Set.iUnion_subset fun n => ?_)
  rw [SummableFamily.powers_of_orderTop_pos hq]
  exact SummableFamily.support_pow_subset_closure q n

variable (a : SummableFamily Γ R I) (hpos : ∀ i, 0 < (a i).orderTop) (g : I → N)

omit [IsOrderedAddMonoid Γ] in
include hpos in
/-- The common positive support of the family. -/
theorem support_pos_iUnion : ∀ γ ∈ ⋃ i, (a i).support, 0 < γ := by
  intro γ hγ
  obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hγ
  exact support_pos_of_orderTop_pos (hpos i) γ hi

omit [AddCommGroup Γ] [IsOrderedAddMonoid Γ] in
theorem support_regroup_subset (n : N) : (regroup a g n).support ⊆ ⋃ i, (a i).support := by
  refine SummableFamily.support_hsum_subset.trans (Set.iUnion_subset fun i => ?_)
  exact Set.subset_iUnion (fun i => (a i).support) i.val

include hpos in
theorem orderTop_regroup_pos (n : N) : 0 < (regroup a g n).orderTop :=
  orderTop_pos_of_support_pos fun γ hγ =>
    support_pos_iUnion a hpos γ (support_regroup_subset a g n hγ)

include hpos in
theorem support_ratio_subset (i : I) :
    (a i * (1 - regroup a g (g i))⁻¹).support ⊆ AddSubmonoid.closure (⋃ i, (a i).support) := by
  intro γ hγ
  obtain ⟨x, hx, y, hy, rfl⟩ := support_mul_subset hγ
  refine AddSubmonoid.add_mem _ (AddSubmonoid.subset_closure (Set.mem_iUnion.mpr ⟨i, hx⟩)) ?_
  have hy' := support_inv_one_sub_subset (orderTop_regroup_pos a hpos g (g i)) hy
  exact AddSubmonoid.closure_mono (support_regroup_subset a g (g i)) hy'

/-- Equation (14): the ratios `a_i/(1 - q_{g(i)})`, with row sums `q_n`, form a
strongly summable family. -/
def ratioFamily : SummableFamily Γ R I where
  toFun i := a i * (1 - regroup a g (g i))⁻¹
  isPWO_iUnion_support' :=
    (isPWO_closure_of_pos a.isPWO_iUnion_support (support_pos_iUnion a hpos)).mono
      (Set.iUnion_subset fun i => support_ratio_subset a hpos g i)
  finite_co_support' γ := by
    classical
    have hS := a.isPWO_iUnion_support
    have hC := isPWO_closure_of_pos hS (support_pos_iUnion a hpos)
    refine ((Finset.antidiagonal hS hC γ).finite_toSet.biUnion fun p _ =>
      a.finite_co_support p.1).subset fun i hi => ?_
    obtain ⟨x, hx, y, hy, hxy⟩ := support_mul_subset ((mem_support _ _).mpr hi)
    have hy' := AddSubmonoid.closure_mono (support_regroup_subset a g (g i))
      (support_inv_one_sub_subset (orderTop_regroup_pos a hpos g (g i)) hy)
    refine Set.mem_biUnion (x := (x, y)) ?_ ((mem_support _ _).mp hx)
    rw [Finset.mem_coe, Finset.mem_antidiagonal]
    exact ⟨Set.mem_iUnion.mpr ⟨i, hx⟩, hy', hxy⟩

@[simp]
theorem ratioFamily_apply (i : I) :
    ratioFamily a hpos g i = a i * (1 - regroup a g (g i))⁻¹ := rfl

omit [AddCommGroup Γ] [IsOrderedAddMonoid Γ] in
theorem regroup_id_apply (n : I) : regroup a id n = a n := by
  ext γ
  rw [regroup_apply, coeff_hsum_fiber, Finsupp.mapDomain_id]
  rfl

/-- Equation (14): `q_n/(1 - q_n)` is strongly summable for a strongly summable
positive-order family `q`. -/
theorem ratioFamily_id_apply (n : I) : ratioFamily a hpos id n = a n * (1 - a n)⁻¹ := by
  rw [ratioFamily_apply, regroup_id_apply, id]

end

end Surreal.HahnSeries
