import Surreal.HahnSeries.Evaluation
import Surreal.HahnSeries.Regroup
import Mathlib.RingTheory.MvPowerSeries.Basic
import Mathlib.Data.Fintype.Option
import Mathlib.Algebra.BigOperators.Finsupp.Basic

/-!
# Strong multivariate Hahn evaluation

This supplies finite-variable strong evaluation and its algebra homomorphism
laws in `a:cor:complexsub` in the analysis article. For finitely many positive-order
Hahn inputs, all substituted monomials form a strongly summable family.
The proof takes finite products of Mathlib's summable families of powers;
their multiplication theorem carries both the well-ordering and finite
coefficient-fiber conditions. Arbitrary formal coefficients then act by
termwise scalar multiplication. Regrouping this jointly summable family proves
the product law. Evaluation preserves the constant coefficient and has support
in the additive monoid generated by the input supports; zero-constant formal
series evaluate to positive order.

Zero inputs are allowed, since their order is infinity. The exponent group
need not be Archimedean. No native fine-topological convergence or actual
surreal strong-evaluation map is assumed.
-/

namespace Surreal.HahnSeries

open _root_.HahnSeries

noncomputable section

variable {Γ R σ α : Type*} [AddCommMonoid Γ] [LinearOrder Γ]
  [IsOrderedCancelAddMonoid Γ] [CommRing R]

/-- Finite products of jointly summable families remain jointly summable,
with the full Cartesian product of their index sets. -/
theorem summable_finite_products (σ : Type*) [Fintype σ]
    (s : σ → SummableFamily Γ R α) :
    ∃ t : SummableFamily Γ R (σ → α), ∀ d, t d = ∏ i, s i (d i) := by
  classical
  revert s
  refine Fintype.induction_empty_option
    (P := fun β _ => ∀ s : β → SummableFamily Γ R α,
      ∃ t : SummableFamily Γ R (β → α), ∀ d, t d = ∏ i, s i (d i)) ?_ ?_ ?_ σ
  · intro β δ _ e ih s
    letI : Fintype β := Fintype.ofEquiv δ e.symm
    obtain ⟨t, ht⟩ := ih (fun b => s (e b))
    refine ⟨SummableFamily.Equiv (Equiv.arrowCongr e (Equiv.refl α)) t, ?_⟩
    intro d
    change t (fun b => d (e b)) = _
    rw [ht]
    exact e.prod_comp (fun i => s i (d i))
  · intro s
    refine ⟨SummableFamily.const (PEmpty → α) 1, ?_⟩
    intro d
    simp
  · intro β _ ih s
    obtain ⟨t, ht⟩ := ih (fun b => s (some b))
    refine ⟨SummableFamily.Equiv Equiv.piOptionEquivProd.symm ((s none).mul t), ?_⟩
    intro d
    change s none (d none) * t (fun b => d (some b)) = _
    rw [ht, Fintype.prod_option]

variable [Fintype σ]

private def finiteProductFamily (s : σ → SummableFamily Γ R α) :
    SummableFamily Γ R (σ → α) := Classical.choose (summable_finite_products σ s)

private theorem finiteProductFamily_apply (s : σ → SummableFamily Γ R α) (d : σ → α) :
    finiteProductFamily s d = ∏ i, s i (d i) :=
  Classical.choose_spec (summable_finite_products σ s) d

/-- The genuinely summable family of all multivariate substituted powers. -/
def mvPowerFamily (x : σ → R⟦Γ⟧) (_hx : ∀ i, 0 < (x i).orderTop) :
    SummableFamily Γ R (σ →₀ ℕ) :=
  SummableFamily.Equiv Finsupp.equivFunOnFinite.symm
    (finiteProductFamily (fun i => SummableFamily.powers (x i)))

@[simp] theorem mvPowerFamily_apply (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (d : σ →₀ ℕ) : mvPowerFamily x hx d = ∏ i, x i ^ d i := by
  classical
  change finiteProductFamily (fun i => SummableFamily.powers (x i)) (fun i => d i) = _
  rw [finiteProductFamily_apply]
  exact Finset.prod_congr rfl fun i _ => SummableFamily.powers_of_orderTop_pos (hx i) (d i)

/-- The actual substituted monomials for an arbitrary formal power series. -/
def mvEvaluationFamily (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (F : MvPowerSeries σ R) : SummableFamily Γ R (σ →₀ ℕ) :=
  SummableFamily.smulFamily (fun d => MvPowerSeries.coeff d F) (mvPowerFamily x hx)

@[simp] theorem mvEvaluationFamily_apply (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (F : MvPowerSeries σ R) (d : σ →₀ ℕ) :
    mvEvaluationFamily x hx F d = (MvPowerSeries.coeff d F) • ∏ i, x i ^ d i := by
  rw [mvEvaluationFamily, SummableFamily.smulFamily_toFun, mvPowerFamily_apply]

/-- Summability of the coefficient-times-monomial formula, with no separate
summability hypothesis on the formal series. -/
theorem summable_mv_coeff_mul_powers (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (F : MvPowerSeries σ R) :
    ∃ s : SummableFamily Γ R (σ →₀ ℕ),
      ∀ d, s d = single 0 (MvPowerSeries.coeff d F) * ∏ i, x i ^ d i := by
  refine ⟨mvEvaluationFamily x hx F, fun d => ?_⟩
  rw [mvEvaluationFamily_apply, single_zero_mul_eq_smul]

/-- At every Hahn exponent only finitely many multivariate monomials contribute. -/
theorem finite_mv_coeff_support (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (F : MvPowerSeries σ R) (g : Γ) :
    {d : σ →₀ ℕ | (single 0 (MvPowerSeries.coeff d F) * ∏ i, x i ^ d i).coeff g ≠ 0}.Finite := by
  simpa only [mvEvaluationFamily_apply, single_zero_mul_eq_smul,
    Function.HasFiniteSupport, Function.support] using
    (mvEvaluationFamily x hx F).finite_co_support g

/-- The union of all contributing supports is partially well ordered. -/
theorem isPWO_mv_support (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (F : MvPowerSeries σ R) :
    (⋃ d : σ →₀ ℕ, (single 0 (MvPowerSeries.coeff d F) * ∏ i, x i ^ d i).support).IsPWO := by
  simpa only [mvEvaluationFamily_apply, single_zero_mul_eq_smul] using
    (mvEvaluationFamily x hx F).isPWO_iUnion_support

omit [AddCommMonoid Γ] [IsOrderedCancelAddMonoid Γ] [Fintype σ] in
open scoped Classical in
private theorem regroup_add_apply
    (s : SummableFamily Γ R ((σ →₀ ℕ) × (σ →₀ ℕ))) (d : σ →₀ ℕ) :
    regroup s (fun p => p.1 + p.2) d = ∑ p ∈ _root_.Finset.HasAntidiagonal.antidiagonal d, s p := by
  classical
  ext g
  rw [regroup_apply, SummableFamily.coeff_hsum]
  simp only [restrict_apply, HahnSeries.coeff_sum]
  trans ∑ᶠ p, if p.1 + p.2 = d then (s p).coeff g else 0
  · convert (finsum_subtype_eq_finsum_cond (f := fun p => (s p).coeff g)
      (fun p => p.1 + p.2 = d)) using 1
    · rfl
    · simp only [finsum_eq_if]
  calc
    (∑ᶠ p, if p.1 + p.2 = d then (s p).coeff g else 0) =
        ∑ p ∈ _root_.Finset.HasAntidiagonal.antidiagonal d, if p.1 + p.2 = d then (s p).coeff g else 0 := by
      apply finsum_eq_sum_of_support_subset
      intro p hp
      by_cases h : p.1 + p.2 = d
      · exact Finset.HasAntidiagonal.mem_antidiagonal.mpr h
      · simp [Function.mem_support, h] at hp
    _ = ∑ p ∈ _root_.Finset.HasAntidiagonal.antidiagonal d, (s p).coeff g := by
      apply Finset.sum_congr rfl
      intro p hp
      rw [if_pos (Finset.HasAntidiagonal.mem_antidiagonal.mp hp)]

theorem mvEvaluationFamily_add (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (F G : MvPowerSeries σ R) :
    mvEvaluationFamily x hx (F + G) = mvEvaluationFamily x hx F + mvEvaluationFamily x hx G := by
  ext1 d
  simp [mvEvaluationFamily_apply, add_smul]

theorem mvEvaluationFamily_zero (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop) :
    mvEvaluationFamily x hx (0 : MvPowerSeries σ R) = 0 := by
  ext1 d
  simp

/-- The multivariate Cauchy product is regrouping of an already jointly
summable product family. No separate convergence assumption is introduced. -/
theorem mvEvaluationFamily_mul (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (F G : MvPowerSeries σ R) :
    mvEvaluationFamily x hx (F * G) =
      regroup ((mvEvaluationFamily x hx F).mul (mvEvaluationFamily x hx G))
        (fun p => p.1 + p.2) := by
  classical
  ext1 d
  rw [regroup_add_apply, mvEvaluationFamily_apply, MvPowerSeries.coeff_mul, Finset.sum_smul]
  apply Finset.sum_congr rfl
  rintro ⟨a, b⟩ hp
  have hab : a + b = d := Finset.HasAntidiagonal.mem_antidiagonal.mp hp
  rw [SummableFamily.mul_toFun, mvEvaluationFamily_apply, mvEvaluationFamily_apply,
    smul_mul_smul_comm]
  congr 1
  rw [← Finset.prod_mul_distrib]
  apply Finset.prod_congr rfl
  intro i _
  rw [← pow_add, ← Finsupp.add_apply, hab]

open scoped Classical in
theorem mvEvaluationFamily_monomial (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (d : σ →₀ ℕ) (r : R) :
    mvEvaluationFamily x hx (MvPowerSeries.monomial d r) =
      SummableFamily.single d (r • ∏ i, x i ^ d i) := by
  classical
  ext1 e
  by_cases h : e = d
  · subst e
    simp [SummableFamily.single_toFun]
  · simp [SummableFamily.single_toFun, MvPowerSeries.coeff_monomial, h]

theorem hsum_mvEvaluationFamily_monomial (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (d : σ →₀ ℕ) (r : R) :
    (mvEvaluationFamily x hx (MvPowerSeries.monomial d r)).hsum = r • ∏ i, x i ^ d i := by
  classical
  rw [mvEvaluationFamily_monomial, SummableFamily.hsum_single]

/-- Strong finite-variable Hahn evaluation as an actual algebra homomorphism.
Its domain explicitly requires positive order for every substituted variable. -/
def mvEvaluate (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop) :
    MvPowerSeries σ R →ₐ[R] R⟦Γ⟧ where
  toFun F := (mvEvaluationFamily x hx F).hsum
  map_zero' := by rw [mvEvaluationFamily_zero, SummableFamily.hsum_zero]
  map_one' := by
    rw [← MvPowerSeries.monomial_zero_one, hsum_mvEvaluationFamily_monomial]
    simp
  map_add' F G := by rw [mvEvaluationFamily_add, SummableFamily.hsum_add]
  map_mul' F G := by rw [mvEvaluationFamily_mul, hsum_regroup, SummableFamily.hsum_mul]
  commutes' r := by
    change (mvEvaluationFamily x hx (MvPowerSeries.C r)).hsum = algebraMap R R⟦Γ⟧ r
    rw [← MvPowerSeries.monomial_zero_eq_C_apply, hsum_mvEvaluationFamily_monomial]
    simp [Algebra.algebraMap_eq_smul_one]

theorem mvEvaluate_apply (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (F : MvPowerSeries σ R) : mvEvaluate x hx F = (mvEvaluationFamily x hx F).hsum := rfl

/-- Evaluation coefficients are genuine finite Hahn sums of the intended monomials. -/
theorem coeff_mvEvaluate (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (F : MvPowerSeries σ R) (g : Γ) :
    (mvEvaluate x hx F).coeff g =
      ∑ᶠ d, (single 0 (MvPowerSeries.coeff d F) * ∏ i, x i ^ d i).coeff g := by
  simp only [mvEvaluate_apply, SummableFamily.coeff_hsum, mvEvaluationFamily_apply,
    single_zero_mul_eq_smul]

@[simp] theorem mvEvaluate_monomial (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (d : σ →₀ ℕ) (r : R) :
    mvEvaluate x hx (MvPowerSeries.monomial d r) = r • ∏ i, x i ^ d i :=
  hsum_mvEvaluationFamily_monomial x hx d r

@[simp] theorem mvEvaluate_C (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop) (r : R) :
    mvEvaluate x hx (MvPowerSeries.C r) = single 0 r := by
  rw [← MvPowerSeries.monomial_zero_eq_C_apply, mvEvaluate_monomial]
  simp [← single_zero_mul_eq_smul]

@[simp] theorem mvEvaluate_X (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop) (i : σ) :
    mvEvaluate x hx (MvPowerSeries.X i) = x i := by
  classical
  simp [MvPowerSeries.X, Finsupp.single_apply]

omit [Fintype σ] in
private theorem sum_orderTop_le_orderTop_prod (s : Finset σ) (f : σ → R⟦Γ⟧) :
    ∑ i ∈ s, (f i).orderTop ≤ (∏ i ∈ s, f i).orderTop := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    simpa only [Finset.sum_empty, Finset.prod_empty, zero_smul, pow_zero] using
      (orderTop_nsmul_le_orderTop_pow (x := (0 : R⟦Γ⟧)) (n := 0))
  | @insert i s hi ih =>
    simp only [Finset.sum_insert hi]
    simp only [Finset.prod_insert hi]
    exact (add_le_add (le_refl (f i).orderTop) ih).trans
      (orderTop_add_le_mul (x := f i) (y := ∏ j ∈ s, f j))

/-- The usual weighted lower bound for every substituted monomial, including
zero inputs and coefficient rings with zero divisors. -/
theorem sum_nsmul_orderTop_le_mvPower (x : σ → R⟦Γ⟧) (d : σ →₀ ℕ) :
    ∑ i, d i • (x i).orderTop ≤ (∏ i, x i ^ d i).orderTop := by
  classical
  exact (Finset.sum_le_sum fun i _ => orderTop_nsmul_le_orderTop_pow).trans
    (sum_orderTop_le_orderTop_prod Finset.univ (fun i => x i ^ d i))

theorem orderTop_mvPower_nonneg (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (d : σ →₀ ℕ) : 0 ≤ (∏ i, x i ^ d i).orderTop :=
  (Finset.sum_nonneg fun i _ => nsmul_nonneg (hx i).le (d i)).trans
    (sum_nsmul_orderTop_le_mvPower x d)

/-- Every nonconstant substituted monomial has strictly positive order. -/
theorem orderTop_mvPower_pos (x : σ → R⟦Γ⟧) (hx : ∀ i, 0 < (x i).orderTop)
    (d : σ →₀ ℕ) (hd : d ≠ 0) : 0 < (∏ i, x i ^ d i).orderTop := by
  classical
  have hex : ∃ i, d i ≠ 0 := by
    by_contra! h
    exact hd (Finsupp.ext h)
  obtain ⟨i, hi⟩ := hex
  refine lt_of_lt_of_le ?_ (sum_nsmul_orderTop_le_mvPower x d)
  exact ((nsmul_pos_iff hi).mpr (hx i)).trans_le
    (Finset.single_le_sum (fun j _ => nsmul_nonneg (hx j).le (d j)) (Finset.mem_univ i))

/-- Evaluation preserves the constant coefficient without a growth restriction
on the formal coefficients. -/
@[simp] theorem coeff_zero_mvEvaluate (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (F : MvPowerSeries σ R) :
    (mvEvaluate x hx F).coeff 0 = MvPowerSeries.constantCoeff F := by
  classical
  rw [coeff_mvEvaluate, finsum_eq_single _ (0 : σ →₀ ℕ)]
  · simp [MvPowerSeries.coeff_zero_eq_constantCoeff_apply]
  · intro d hd
    rw [single_zero_mul_eq_smul, coeff_smul,
      coeff_eq_zero_of_lt_orderTop (orderTop_mvPower_pos x hx d hd), smul_zero]

/-- Multivariate evaluation takes values in the nonnegative-order subring. -/
theorem orderTop_mvEvaluate_nonneg (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (F : MvPowerSeries σ R) :
    0 ≤ (mvEvaluate x hx F).orderTop := by
  apply le_orderTop_iff_forall.mpr
  intro g hg
  rw [coeff_mvEvaluate]
  apply finsum_eq_zero_of_forall_eq_zero
  intro d
  rw [single_zero_mul_eq_smul, coeff_smul,
    coeff_eq_zero_of_lt_orderTop (hg.trans_le (orderTop_mvPower_nonneg x hx d)), smul_zero]

/-- A zero-constant formal series evaluates to positive order, giving the
admissibility needed for further substitution and infinitesimal corrections. -/
theorem orderTop_mvEvaluate_pos_of_constantCoeff_zero (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (F : MvPowerSeries σ R)
    (hF : MvPowerSeries.constantCoeff F = 0) : 0 < (mvEvaluate x hx F).orderTop := by
  have hc : (mvEvaluate x hx F).coeff 0 = 0 := (coeff_zero_mvEvaluate x hx F).trans hF
  exact lt_of_le_of_ne (orderTop_mvEvaluate_nonneg x hx F)
    (orderTop_ne_of_coeff_eq_zero hc).symm

omit [IsOrderedCancelAddMonoid Γ] in
private theorem support_one_subset_addSubmonoid (S : AddSubmonoid Γ) :
    (1 : R⟦Γ⟧).support ⊆ S := by
  intro g hg
  have : g = 0 := Set.mem_singleton_iff.mp (support_single_subset hg)
  subst g
  exact S.zero_mem

private theorem support_mul_subset_addSubmonoid (S : AddSubmonoid Γ)
    {a b : R⟦Γ⟧} (ha : a.support ⊆ S) (hb : b.support ⊆ S) :
    (a * b).support ⊆ S := by
  intro g hg
  obtain ⟨u, hu, v, hv, rfl⟩ := support_mul_subset hg
  exact S.add_mem (ha hu) (hb hv)

private theorem support_pow_subset_addSubmonoid (S : AddSubmonoid Γ)
    {a : R⟦Γ⟧} (ha : a.support ⊆ S) (n : ℕ) : (a ^ n).support ⊆ S := by
  induction n with
  | zero => simpa only [pow_zero] using support_one_subset_addSubmonoid (R := R) S
  | succ n ih =>
    rw [pow_succ]
    exact support_mul_subset_addSubmonoid S ih ha

/-- Every substituted monomial stays within any additive submonoid containing
the input supports. -/
theorem support_mvPower_subset_addSubmonoid (x : σ → R⟦Γ⟧) (d : σ →₀ ℕ)
    (S : AddSubmonoid Γ) (hx : ∀ i, (x i).support ⊆ S) :
    (∏ i, x i ^ d i).support ⊆ S := by
  classical
  exact Finset.prod_induction (fun i => x i ^ d i) (fun a => a.support ⊆ S)
    (fun _ _ => support_mul_subset_addSubmonoid S)
    (support_one_subset_addSubmonoid S)
    (fun i _ => support_pow_subset_addSubmonoid S (hx i) (d i))

/-- Strong evaluation stays within every additive submonoid containing the
supports of the substituted variables. -/
theorem support_mvEvaluate_subset_addSubmonoid (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (F : MvPowerSeries σ R)
    (S : AddSubmonoid Γ) (hS : ∀ i, (x i).support ⊆ S) :
    (mvEvaluate x hx F).support ⊆ S := by
  intro g hg
  obtain ⟨d, hd⟩ := Set.mem_iUnion.mp (SummableFamily.support_hsum_subset hg)
  rw [mvEvaluationFamily_apply] at hd
  exact support_mvPower_subset_addSubmonoid x d S hS (support_smul_subset _ _ hd)

/-- The evaluation support is contained in the additive monoid generated by
the union of the input supports. This controls the supports of corrections
obtained by evaluating universal formal factor lifts. -/
theorem support_mvEvaluate_subset_closure (x : σ → R⟦Γ⟧)
    (hx : ∀ i, 0 < (x i).orderTop) (F : MvPowerSeries σ R) :
    (mvEvaluate x hx F).support ⊆ AddSubmonoid.closure (⋃ i, (x i).support) := by
  apply support_mvEvaluate_subset_addSubmonoid x hx F
  intro i g hg
  exact AddSubmonoid.subset_closure (Set.mem_iUnion.mpr ⟨i, hg⟩)

end

end Surreal.HahnSeries
