import Mathlib.RingTheory.HahnSeries.Summable

/-!
# Noncommutative Neumann inverses and the inverse-smooth criterion

This file formalizes two results of
`docs/surcomplex/infinite-dimensional-hahn-spectral-theory/article.tex`.

`ihs:lem:neumann` (support-certified Neumann inverse) is proved over an arbitrary, possibly
noncommutative, ring `R` and a linearly ordered cancellative commutative additive monoid `Γ`
of exponents.
Mathlib's `SummableFamily.powers` and `isUnit_of_orderTop_pos` require a commutative
coefficient ring, so the strong summability of the powers of a positive-order series is
reproved without commutativity (`pow_finite_co_support_of_semiring`, `ringPowers`). For
`E` with `0 < E.orderTop` (that is, `v(E) > 0`, the case `E = 0` included), the family
`((-E) ^ n)` is strongly summable (`neumannFamily`), its sum is a two-sided inverse of
`1 + E`, and that inverse is supported in the additive monoid generated by `supp E`
(`neumann`). In the spirit of `ihs:rem:telescope`, the left and right identities use only
associativity. The remark's finite partial-sum identity
`(I + E) ∑_{n ≤ N} (-E)^n = I + (-1)^N E^(N+1)` is not formalized; instead the left
identity is the shift identity `H = 1 + x * H` for `H = ∑ x ^ n`, and the right one
follows because left and right multiplication by `x` give the same shifted family of
powers (`hsum_mulRight`).

`ihs:hh:thm:smooth` (all inverse moments are necessary and sufficient) is proved for an
injective linear endomorphism `S` of an arbitrary module `V` over a semiring `k`, with
exponents in a partially ordered abelian group `Γ`. The space `V((t^Γ))` is
`HahnModule Γ k V`, `S` acts coefficientwise and `s = t^η` acts through the module structure
over `k((t^Γ))` (`shiftResolvent`). For `η > 0` and constant data `f`, the equation
`(S - sI) y = f` has a solution if and only if `f ∈ Ran S^(n+1)` for every `n`
(`exists_shiftResolvent_eq_const_iff`, equation `ihs:hh:eq:inversesmooth`; the literal
intersection `⋂_{m ≥ 1} Ran S^m` is matched by `mem_iInf_range_pow_iff`). The operator
`S - sI` is injective (`shiftResolvent_injective`), so the solution is unique, and it is the
strong sum `∑ s^n S^(-n-1) f` of `ihs:hh:eq:smoothsolution` for any choice of the preimages
`u n` with `S^(n+1) (u n) = f`, which are themselves unique
(`eq_hsum_of_shiftResolvent_eq_const`, `inverseSmoothFamily_apply_eq_smul`, `inverseSmooth`).
The proof of necessity does not partition into cosets of `ℤη`: the least support point
outside `{n • η}` would be annihilated by `S`. It does not use `ihs:hh:thm:defect`.

The analytic example `ihs:hh:ex:smoothD` on `ℓ²` is not formalized here.
-/

namespace Surreal.InfiniteSpectral

open _root_.HahnSeries

noncomputable section

section RightMultiplication

variable {Γ R α : Type*} [AddCommMonoid Γ] [PartialOrder Γ] [IsOrderedCancelAddMonoid Γ]
  [Semiring R]

/-- Right multiplication of a strongly summable family by a fixed Hahn series. -/
def mulRight (s : SummableFamily Γ R α) (y : R⟦Γ⟧) : SummableFamily Γ R α :=
  SummableFamily.Equiv (_root_.Equiv.prodPUnit.{0} α) (s.mul (SummableFamily.const Unit y))

@[simp]
theorem mulRight_apply (s : SummableFamily Γ R α) (y : R⟦Γ⟧) (a : α) :
    mulRight s y a = s a * y :=
  rfl

/-- Strong sums commute with right multiplication, without commutativity of `R`. -/
theorem hsum_mulRight (s : SummableFamily Γ R α) (y : R⟦Γ⟧) :
    (mulRight s y).hsum = s.hsum * y := by
  rw [mulRight, SummableFamily.hsum_equiv, SummableFamily.hsum_mul,
    SummableFamily.hsum_unique (SummableFamily.const Unit y)]
  rfl

end RightMultiplication

section Powers

variable {Γ R : Type*} [AddCommMonoid Γ] [LinearOrder Γ] [IsOrderedCancelAddMonoid Γ]
  [Semiring R]

open Finset in
/-- Mathlib's `SummableFamily.pow_finite_co_support` without commutativity of the
coefficients: at a fixed exponent only finitely many powers of a positive-order series
have a nonzero coefficient. -/
theorem pow_finite_co_support_of_semiring {x : R⟦Γ⟧} (hx : 0 < x.orderTop) (g : Γ) :
    {n : ℕ | (x ^ n).coeff g ≠ 0}.Finite := by
  have hpwo : Set.IsPWO (⋃ n, support (x ^ n)) :=
    SummableFamily.isPWO_iUnion_support_powers (zero_le_orderTop_iff.mp hx.le)
  by_cases h0 : x = 0
  · subst h0
    exact (Set.finite_singleton 0).subset (SummableFamily.co_support_zero g)
  by_cases hg : g ∈ ⋃ n : ℕ, {g | (x ^ n).coeff g ≠ 0}
  swap
  · exact Set.finite_empty.subset fun n hn => hg (Set.mem_iUnion.2 ⟨n, hn⟩)
  apply hpwo.isWF.induction hg
  intro y _ hy
  refine ((((antidiagonal x.isPWO_support hpwo y).finite_toSet.biUnion
    fun ij hij => hy ij.snd (mem_antidiagonal.1 (mem_coe.1 hij)).2.1 ?_).image Nat.succ).union
      (Set.finite_singleton 0)).subset ?_
  · obtain ⟨hi, _, rfl⟩ := mem_antidiagonal.1 (mem_coe.1 hij)
    exact lt_add_of_pos_left ij.2 <| lt_of_lt_of_le ((zero_lt_orderTop_iff h0).mp hx) <|
      order_le_of_coeff_ne_zero <| Function.mem_support.mp hi
  · rintro (_ | n) hn
    · exact Set.mem_union_right _ (Set.mem_singleton 0)
    · rw [Set.mem_setOf_eq, pow_succ] at hn
      obtain ⟨i, hi, j, hj, rfl⟩ := support_mul_subset hn
      refine Set.mem_union_left _ ⟨n, Set.mem_iUnion.2 ⟨⟨j, i⟩, Set.mem_iUnion.2 ⟨?_, hi⟩⟩, rfl⟩
      simp only [mem_coe, mem_antidiagonal, mem_support, ne_eq, Set.mem_iUnion]
      exact ⟨hj, ⟨n, hi⟩, add_comm j i⟩

/-- The strongly summable family of powers of a positive-order Hahn series, over a possibly
noncommutative semiring. -/
def ringPowers (x : R⟦Γ⟧) (hx : 0 < x.orderTop) : SummableFamily Γ R ℕ where
  toFun n := x ^ n
  isPWO_iUnion_support' :=
    SummableFamily.isPWO_iUnion_support_powers (zero_le_orderTop_iff.mp hx.le)
  finite_co_support' := pow_finite_co_support_of_semiring hx

@[simp]
theorem ringPowers_apply (x : R⟦Γ⟧) (hx : 0 < x.orderTop) (n : ℕ) :
    ringPowers x hx n = x ^ n :=
  rfl

/-- The powers split as the zeroth power plus the left shift by `x`. -/
theorem ringPowers_eq_single_add (x : R⟦Γ⟧) (hx : 0 < x.orderTop) :
    ringPowers x hx = SummableFamily.ofFinsupp (Finsupp.single 0 1) +
      (x • ringPowers x hx).embDomain ⟨Nat.succ, Nat.succ_injective⟩ := by
  refine SummableFamily.ext fun n => ?_
  rcases n with _ | n
  · rw [SummableFamily.add_apply, SummableFamily.embDomain_notin_range]
    · simp
    · rintro ⟨m, hm⟩
      exact Nat.succ_ne_zero m hm
  · have h : (x • ringPowers x hx).embDomain ⟨Nat.succ, Nat.succ_injective⟩ (n + 1) =
        x * x ^ n :=
      SummableFamily.embDomain_image _ _
    rw [SummableFamily.add_apply, h, ringPowers_apply, pow_succ']
    simp

/-- The telescoping identity `H = 1 + x * H` for `H = ∑ x ^ n`. -/
theorem hsum_ringPowers_eq_one_add_mul (x : R⟦Γ⟧) (hx : 0 < x.orderTop) :
    (ringPowers x hx).hsum = 1 + x * (ringPowers x hx).hsum := by
  conv_lhs => rw [ringPowers_eq_single_add x hx]
  rw [SummableFamily.hsum_add, SummableFamily.hsum_embDomain, SummableFamily.hsum_smul,
    SummableFamily.hsum_ofFinsupp]
  simp

/-- Left and right multiplication by `x` agree on the strong sum of its powers. -/
theorem mul_hsum_ringPowers_comm (x : R⟦Γ⟧) (hx : 0 < x.orderTop) :
    x * (ringPowers x hx).hsum = (ringPowers x hx).hsum * x := by
  rw [← SummableFamily.hsum_smul, ← hsum_mulRight]
  congr 1
  refine SummableFamily.ext fun n => ?_
  rw [mulRight_apply, SummableFamily.smul_apply, ringPowers_apply]
  exact (Commute.self_pow x n).eq

end Powers

section Neumann

variable {Γ R : Type*} [AddCommMonoid Γ] [LinearOrder Γ] [IsOrderedCancelAddMonoid Γ]
  [Ring R]

theorem one_sub_mul_hsum_ringPowers (x : R⟦Γ⟧) (hx : 0 < x.orderTop) :
    (1 - x) * (ringPowers x hx).hsum = 1 := by
  rw [sub_mul, one_mul, sub_eq_iff_eq_add, ← hsum_ringPowers_eq_one_add_mul]

theorem hsum_ringPowers_mul_one_sub (x : R⟦Γ⟧) (hx : 0 < x.orderTop) :
    (ringPowers x hx).hsum * (1 - x) = 1 := by
  rw [mul_sub, mul_one, ← mul_hsum_ringPowers_comm, sub_eq_iff_eq_add,
    ← hsum_ringPowers_eq_one_add_mul]

omit [IsOrderedCancelAddMonoid Γ] in
theorem neg_orderTop_pos {E : R⟦Γ⟧} (hE : 0 < E.orderTop) : 0 < (-E).orderTop := by
  rwa [orderTop_neg]

/-- `ihs:lem:neumann`: the strongly summable Neumann family `((-E) ^ n)`. -/
def neumannFamily (E : R⟦Γ⟧) (hE : 0 < E.orderTop) : SummableFamily Γ R ℕ :=
  ringPowers (-E) (neg_orderTop_pos hE)

@[simp]
theorem neumannFamily_apply (E : R⟦Γ⟧) (hE : 0 < E.orderTop) (n : ℕ) :
    neumannFamily E hE n = (-E) ^ n :=
  rfl

/-- `ihs:lem:neumann`, left inverse: `(1 + E) * ∑ (-E) ^ n = 1`. -/
theorem one_add_mul_hsum_neumannFamily (E : R⟦Γ⟧) (hE : 0 < E.orderTop) :
    (1 + E) * (neumannFamily E hE).hsum = 1 := by
  rw [← sub_neg_eq_add]
  exact one_sub_mul_hsum_ringPowers _ _

/-- `ihs:lem:neumann`, right inverse: `(∑ (-E) ^ n) * (1 + E) = 1`. -/
theorem hsum_neumannFamily_mul_one_add (E : R⟦Γ⟧) (hE : 0 < E.orderTop) :
    (neumannFamily E hE).hsum * (1 + E) = 1 := by
  rw [← sub_neg_eq_add]
  exact hsum_ringPowers_mul_one_sub _ _

/-- `ihs:lem:neumann`, support certificate: the Neumann inverse is supported in the
additive monoid `(supp E)*` generated by the support of `E`. -/
theorem support_hsum_neumannFamily_subset (E : R⟦Γ⟧) (hE : 0 < E.orderTop) :
    (neumannFamily E hE).hsum.support ⊆ AddSubmonoid.closure E.support := by
  refine SummableFamily.support_hsum_subset.trans (Set.iUnion_subset fun n => ?_)
  rw [neumannFamily_apply, ← support_neg (x := E)]
  exact SummableFamily.support_pow_subset_closure (-E) n

/-- `ihs:lem:neumann`: a Hahn series `1 + E` with `v(E) > 0` is a unit, over any ring. -/
theorem isUnit_one_add_of_orderTop_pos {E : R⟦Γ⟧} (hE : 0 < E.orderTop) : IsUnit (1 + E) :=
  ⟨⟨1 + E, (neumannFamily E hE).hsum, one_add_mul_hsum_neumannFamily E hE,
    hsum_neumannFamily_mul_one_add E hE⟩, rfl⟩

/-- `ihs:eq:neumann`: the inverse of `1 + E` is the strong sum `∑ (-E) ^ n`. -/
theorem inv_one_add_eq_hsum_neumannFamily {E : R⟦Γ⟧} (hE : 0 < E.orderTop) :
    (((isUnit_one_add_of_orderTop_pos hE).unit⁻¹ : (R⟦Γ⟧)ˣ) : R⟦Γ⟧) =
      (neumannFamily E hE).hsum :=
  Units.inv_eq_of_mul_eq_one_right (one_add_mul_hsum_neumannFamily E hE)

/-- `ihs:lem:neumann`: for `E` with `v(E) > 0` over a possibly noncommutative ring, the
powers `(-E) ^ n` form a strongly summable family whose sum is a two-sided inverse of
`1 + E`, supported in the additive monoid generated by `supp E`. -/
theorem neumann (E : R⟦Γ⟧) (hE : 0 < E.orderTop) :
    ∃ s : SummableFamily Γ R ℕ, (∀ n, s n = (-E) ^ n) ∧ (1 + E) * s.hsum = 1 ∧
      s.hsum * (1 + E) = 1 ∧ s.hsum.support ⊆ AddSubmonoid.closure E.support :=
  ⟨neumannFamily E hE, neumannFamily_apply E hE, one_add_mul_hsum_neumannFamily E hE,
    hsum_neumannFamily_mul_one_add E hE, support_hsum_neumannFamily_subset E hE⟩

end Neumann

section InverseSmooth

variable {Γ k V : Type*} [AddCommGroup Γ] [PartialOrder Γ] [IsOrderedAddMonoid Γ]
  [Semiring k] [AddCommGroup V] [Module k V]

/-- The coefficients of `t^b r • x` in a Hahn module over a group of exponents. -/
theorem coeff_single_smul_hahnModule (b : Γ) (r : k) (x : HahnModule Γ k V) (γ : Γ) :
    ((HahnModule.of k).symm (single b r • x)).coeff γ =
      r • ((HahnModule.of k).symm x).coeff (γ - b) := by
  have h := HahnModule.coeff_single_smul_vadd (r := r) (x := x) (a := γ - b) (b := b)
  rwa [vadd_eq_add, add_sub_cancel] at h

/-- The operator `S - sI` on `V((t^Γ))` of `ihs:hh:eq:constres`, with `S` acting
coefficientwise and `s = t^η` acting through the module structure over `k((t^Γ))`. -/
def shiftResolvent (S : Module.End k V) (η : Γ) (y : HahnModule Γ k V) : HahnModule Γ k V :=
  HahnModule.of k (((HahnModule.of k).symm y).map S) - single η (1 : k) • y

theorem coeff_shiftResolvent (S : Module.End k V) (η : Γ) (y : HahnModule Γ k V) (γ : Γ) :
    ((HahnModule.of k).symm (shiftResolvent S η y)).coeff γ =
      S (((HahnModule.of k).symm y).coeff γ) - ((HahnModule.of k).symm y).coeff (γ - η) := by
  rw [shiftResolvent, HahnModule.of_symm_sub, coeff_sub, coeff_single_smul_hahnModule, one_smul,
    Equiv.symm_apply_apply, map_coeff]

theorem shiftResolvent_sub (S : Module.End k V) (η : Γ) (y₁ y₂ : HahnModule Γ k V) :
    shiftResolvent S η (y₁ - y₂) = shiftResolvent S η y₁ - shiftResolvent S η y₂ := by
  refine HahnModule.ext _ _ (funext fun γ => ?_)
  simp only [HahnModule.of_symm_sub, coeff_sub, coeff_shiftResolvent, map_sub]
  abel

/-- A series satisfying the homogeneous recursion `S y_γ = y_(γ-η)` away from `0` is
supported in `{n • η : n ∈ ℕ}`: the least support point outside that set would be
annihilated by the injective map `S`. -/
theorem support_subset_range_nsmul {S : Module.End k V} (hS : Function.Injective S) {η : Γ}
    (hη : 0 < η) {Y : HahnSeries Γ V} (hY : ∀ γ ≠ 0, S (Y.coeff γ) = Y.coeff (γ - η)) :
    Y.support ⊆ Set.range fun n : ℕ => n • η := by
  intro γ hγ
  refine Y.isWF_support.induction hγ fun γ hγ ih => ?_
  by_cases h0 : γ = 0
  · exact ⟨0, by simp only [h0, zero_nsmul]⟩
  have hne : γ - η ∈ Y.support := by
    rw [mem_support, ← hY γ h0]
    intro h
    exact hγ (hS (h.trans (map_zero S).symm))
  obtain ⟨n, hn⟩ := ih (γ - η) hne (sub_lt_self γ hη)
  exact ⟨n + 1, by dsimp only at hn ⊢; rw [succ_nsmul, hn, sub_add_cancel]⟩

theorem neg_notMem_range_nsmul {η : Γ} (hη : 0 < η) :
    -η ∉ Set.range fun n : ℕ => n • η := by
  rintro ⟨n, hn⟩
  have h : (0 : Γ) ≤ -η := hn ▸ nsmul_nonneg hη.le n
  exact (lt_irrefl (0 : Γ)) (h.trans_lt (neg_lt_zero.mpr hη))

omit [PartialOrder Γ] [IsOrderedAddMonoid Γ] in
theorem sub_notMem_range_nsmul {η γ : Γ} (hγ : γ ∉ Set.range fun n : ℕ => n • η) :
    γ - η ∉ Set.range fun n : ℕ => n • η := by
  rintro ⟨n, hn⟩
  exact hγ ⟨n + 1, by dsimp only at hn ⊢; rw [succ_nsmul, hn, sub_add_cancel]⟩

/-- The coefficient recursion of a solution of `(S - sI) y = f` for constant `f`: the
support lies in `{n • η}` and `S^(n+1) y_(nη) = f` for every `n`. -/
theorem shiftResolvent_eq_const_coeff {S : Module.End k V} (hS : Function.Injective S) {η : Γ}
    (hη : 0 < η) {f : V} {y : HahnModule Γ k V}
    (hy : shiftResolvent S η y = HahnModule.of k (single 0 f)) :
    (∀ n : ℕ, (S ^ (n + 1)) (((HahnModule.of k).symm y).coeff (n • η)) = f) ∧
      ((HahnModule.of k).symm y).support ⊆ Set.range fun n : ℕ => n • η := by
  set Y := (HahnModule.of k).symm y with hYdef
  have hc : ∀ γ, S (Y.coeff γ) - Y.coeff (γ - η) = (single 0 f).coeff γ := by
    intro γ
    rw [← coeff_shiftResolvent, hy, Equiv.symm_apply_apply]
  have hrec : ∀ γ ≠ 0, S (Y.coeff γ) = Y.coeff (γ - η) := by
    intro γ hγ
    have h := hc γ
    rwa [coeff_single_of_ne hγ, sub_eq_zero] at h
  have hsupp := support_subset_range_nsmul hS hη hrec
  refine ⟨fun n => ?_, hsupp⟩
  induction n with
  | zero =>
    have h := hc 0
    have hneg : Y.coeff (0 - η) = 0 := by
      rw [zero_sub]
      by_contra h'
      exact neg_notMem_range_nsmul hη (hsupp h')
    rwa [hneg, sub_zero, coeff_single_same, ← zero_nsmul η] at h
  | succ n ih =>
    have hpos : (n + 1) • η ≠ 0 := (nsmul_pos hη n.succ_ne_zero).ne'
    rw [pow_succ, Module.End.mul_apply, hrec _ hpos, succ_nsmul, add_sub_cancel_right]
    exact ih

/-- The family `n ↦ t^(nη) u_n`. When `u n` is the preimage of `f` under `S^(n+1)`, this is
the family `s^n S^(-n-1) f` of `ihs:hh:eq:smoothsolution`. -/
def inverseSmoothFamily {η : Γ} (hη : 0 < η) (u : ℕ → V) : SummableFamily Γ V ℕ where
  toFun n := single (n • η) (u n)
  isPWO_iUnion_support' := by
    refine ((Set.isPWO_of_wellQuasiOrderedLE (Set.univ : Set ℕ)).image_of_monotone
      (nsmul_left_strictMono hη).monotone).mono (Set.iUnion_subset fun n => ?_)
    refine support_single_subset.trans ?_
    rintro _ rfl
    exact ⟨n, Set.mem_univ n, rfl⟩
  finite_co_support' g := by
    refine Set.Subsingleton.finite fun m hm n hn => ?_
    have hm' : g = m • η := by
      by_contra h
      exact hm (coeff_single_of_ne h)
    have hn' : g = n • η := by
      by_contra h
      exact hn (coeff_single_of_ne h)
    exact (nsmul_left_strictMono hη).injective (hm'.symm.trans hn')

@[simp]
theorem inverseSmoothFamily_apply {η : Γ} (hη : 0 < η) (u : ℕ → V) (n : ℕ) :
    inverseSmoothFamily hη u n = single (n • η) (u n) :=
  rfl

/-- Each term of `inverseSmoothFamily` is `s^n` applied to the constant `u n`. -/
theorem inverseSmoothFamily_apply_eq_smul {η : Γ} (hη : 0 < η) (u : ℕ → V) (n : ℕ) :
    inverseSmoothFamily hη u n =
      (HahnModule.of k).symm (single η (1 : k) ^ n • HahnModule.of k (single 0 (u n))) := by
  ext γ
  rw [single_pow, one_pow, coeff_single_smul_hahnModule, one_smul, Equiv.symm_apply_apply,
    inverseSmoothFamily_apply, coeff_single, coeff_single, sub_eq_zero]

theorem coeff_hsum_inverseSmoothFamily_nsmul {η : Γ} (hη : 0 < η) (u : ℕ → V) (n : ℕ) :
    (inverseSmoothFamily hη u).hsum.coeff (n • η) = u n := by
  rw [SummableFamily.coeff_hsum, finsum_eq_single _ n]
  · exact coeff_single_same _ _
  · intro m hm
    exact coeff_single_of_ne fun h => hm ((nsmul_left_strictMono hη).injective h).symm

theorem coeff_hsum_inverseSmoothFamily_of_notMem {η : Γ} (hη : 0 < η) (u : ℕ → V) {γ : Γ}
    (hγ : γ ∉ Set.range fun n : ℕ => n • η) : (inverseSmoothFamily hη u).hsum.coeff γ = 0 := by
  rw [SummableFamily.coeff_hsum]
  exact finsum_eq_zero_of_forall_eq_zero fun n => coeff_single_of_ne fun h => hγ ⟨n, h.symm⟩

/-- `ihs:hh:thm:smooth`, sufficiency: if `S^(n+1) (u n) = f` for all `n`, then
`∑ s^n u_n` solves `(S - sI) y = f`. -/
theorem shiftResolvent_hsum_inverseSmoothFamily {S : Module.End k V}
    (hS : Function.Injective S) {η : Γ} (hη : 0 < η) {f : V} {u : ℕ → V}
    (hu : ∀ n, (S ^ (n + 1)) (u n) = f) :
    shiftResolvent S η (HahnModule.of k (inverseSmoothFamily hη u).hsum) =
      HahnModule.of k (single 0 f) := by
  have hstep : ∀ n, S (u (n + 1)) = u n := by
    intro n
    apply Module.End.iterate_injective hS (n + 1)
    rw [← Module.End.mul_apply, ← pow_succ, hu, hu]
  have hzero : S (u 0) = f := by simpa using hu 0
  refine HahnModule.ext _ _ (funext fun γ => ?_)
  rw [coeff_shiftResolvent, Equiv.symm_apply_apply, Equiv.symm_apply_apply]
  by_cases hγ : γ ∈ Set.range fun n : ℕ => n • η
  · obtain ⟨n, rfl⟩ := hγ
    dsimp only
    rcases n with _ | n
    · rw [coeff_hsum_inverseSmoothFamily_nsmul, zero_nsmul, zero_sub,
        coeff_hsum_inverseSmoothFamily_of_notMem hη u (neg_notMem_range_nsmul hη), sub_zero,
        coeff_single_same, hzero]
    · have hpos : (n + 1) • η ≠ 0 := (nsmul_pos hη n.succ_ne_zero).ne'
      rw [coeff_hsum_inverseSmoothFamily_nsmul, coeff_single_of_ne hpos, succ_nsmul,
        add_sub_cancel_right, coeff_hsum_inverseSmoothFamily_nsmul, hstep, sub_self]
  · have h0 : γ ≠ 0 := fun h => hγ ⟨0, by simp only [h, zero_nsmul]⟩
    rw [coeff_hsum_inverseSmoothFamily_of_notMem hη u hγ,
      coeff_hsum_inverseSmoothFamily_of_notMem hη u (sub_notMem_range_nsmul hγ), map_zero,
      sub_zero, coeff_single_of_ne h0]

/-- `ihs:hh:thm:smooth`, uniqueness: for injective `S` and `η > 0`, the operator `S - sI` is
injective on `V((t^Γ))`. -/
theorem shiftResolvent_injective {S : Module.End k V} (hS : Function.Injective S) {η : Γ}
    (hη : 0 < η) : Function.Injective (shiftResolvent S η) := by
  intro y₁ y₂ h
  have h0 : shiftResolvent S η (y₁ - y₂) = HahnModule.of k (single 0 0) := by
    rw [shiftResolvent_sub, h, sub_self, single_eq_zero, HahnModule.of_zero]
  obtain ⟨hpow, hsupp⟩ := shiftResolvent_eq_const_coeff hS hη h0
  rw [← sub_eq_zero]
  refine HahnModule.ext _ _ (funext fun γ => ?_)
  rw [HahnModule.of_symm_zero, coeff_zero]
  by_contra hne
  obtain ⟨n, rfl⟩ := hsupp hne
  exact hne (Module.End.iterate_injective hS (n + 1) ((hpow n).trans (map_zero _).symm))

omit [AddCommGroup Γ] [PartialOrder Γ] [IsOrderedAddMonoid Γ] in
/-- The intersection `⋂_{m ≥ 1} Ran S^m` of `ihs:hh:eq:inversesmooth`, indexed by `n + 1`. -/
theorem mem_iInf_range_pow_iff (S : Module.End k V) (f : V) :
    f ∈ ⨅ (m : ℕ) (_ : 1 ≤ m), LinearMap.range (S ^ m) ↔
      ∀ n : ℕ, f ∈ LinearMap.range (S ^ (n + 1)) := by
  simp only [Submodule.mem_iInf]
  refine ⟨fun h n => h (n + 1) (Nat.le_add_left 1 n), fun h m hm => ?_⟩
  obtain ⟨n, rfl⟩ := Nat.exists_eq_add_of_le' hm
  exact h n

/-- `ihs:hh:thm:smooth`, `ihs:hh:eq:inversesmooth`: for injective `S` and `s = t^η` with
`η > 0`, the equation `(S - sI) y = f` with constant data `f` has a solution in `V((t^Γ))`
if and only if `f` lies in `Ran S^(n+1)` for every `n`, that is, in `⋂_{m ≥ 1} Ran S^m`. -/
theorem exists_shiftResolvent_eq_const_iff {S : Module.End k V} (hS : Function.Injective S)
    {η : Γ} (hη : 0 < η) (f : V) :
    (∃ y, shiftResolvent S η y = HahnModule.of k (single 0 f)) ↔
      ∀ n : ℕ, f ∈ LinearMap.range (S ^ (n + 1)) := by
  constructor
  · rintro ⟨y, hy⟩ n
    exact ⟨_, (shiftResolvent_eq_const_coeff hS hη hy).1 n⟩
  · intro hf
    choose u hu using fun n => LinearMap.mem_range.mp (hf n)
    exact ⟨_, shiftResolvent_hsum_inverseSmoothFamily hS hη hu⟩

/-- `ihs:hh:thm:smooth`, `ihs:hh:eq:smoothsolution`: any solution of `(S - sI) y = f` is the
strong sum `∑ s^n S^(-n-1) f`, where `S^(-n-1) f` is any, hence the unique, preimage of `f`
under `S^(n+1)`. -/
theorem eq_hsum_of_shiftResolvent_eq_const {S : Module.End k V} (hS : Function.Injective S)
    {η : Γ} (hη : 0 < η) {f : V} {y : HahnModule Γ k V}
    (hy : shiftResolvent S η y = HahnModule.of k (single 0 f)) {u : ℕ → V}
    (hu : ∀ n, (S ^ (n + 1)) (u n) = f) :
    y = HahnModule.of k (inverseSmoothFamily hη u).hsum :=
  shiftResolvent_injective hS hη (hy.trans (shiftResolvent_hsum_inverseSmoothFamily hS hη hu).symm)

/-- `ihs:hh:thm:smooth`, packaged: for injective `S`, `η > 0` and
`f ∈ ⋂_{m ≥ 1} Ran S^m`, the preimages `S^(-n-1) f` exist and are unique, and a series `y`
solves `(S - sI) y = f` exactly when `y = ∑ s^n S^(-n-1) f`. -/
theorem inverseSmooth {S : Module.End k V} (hS : Function.Injective S) {η : Γ} (hη : 0 < η)
    {f : V} (hf : ∀ n : ℕ, f ∈ LinearMap.range (S ^ (n + 1))) :
    (∀ n : ℕ, ∃! v : V, (S ^ (n + 1)) v = f) ∧
      ∃ u : ℕ → V, (∀ n, (S ^ (n + 1)) (u n) = f) ∧
        ∀ y, shiftResolvent S η y = HahnModule.of k (single 0 f) ↔
          y = HahnModule.of k (inverseSmoothFamily hη u).hsum := by
  choose u hu using fun n => LinearMap.mem_range.mp (hf n)
  refine ⟨fun n => ⟨u n, hu n, fun v hv =>
    Module.End.iterate_injective hS (n + 1) (hv.trans (hu n).symm)⟩, u, hu, fun y => ⟨?_, ?_⟩⟩
  · exact fun hy => eq_hsum_of_shiftResolvent_eq_const hS hη hy hu
  · rintro rfl
    exact shiftResolvent_hsum_inverseSmoothFamily hS hη hu

end InverseSmooth

end

end Surreal.InfiniteSpectral
