import Mathlib.Data.Int.Interval
import Mathlib.Data.Int.LeastGreatest
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.LinearCombination
import Surreal.HahnSeries.InfiniteProducts

/-!
# The exact domain of the bilateral theta series

This file proves `tate:thm:theta` in
`docs/surcomplex/hahn-tate-uniformization/article.tex`, together with the finite
normalization lemma `tate:lem:normalize` and the definitions `tate:def:domain`
(`tate:eq:H`, `tate:eq:U`) on which it rests.

Let `Γ` be an arbitrary linearly ordered abelian group (no divisibility, rank or
countability hypothesis) and `k` an arbitrary field; the report works over `k = ℂ`
and remarks that the argument is coefficient-free. For `q ∈ k⟦Γ⟧` with
`α = v(q) > 0` (such `q` is nonzero, `ne_zero_of_order_pos`, since Mathlib sets
`order 0 = 0`), the admissible group `H_α` consists of the `γ` with
`-Nα ≤ γ ≤ Nα` for some natural `N`; it is the smallest convex subgroup containing
`α` (`admissibleGroup`, `self_mem_admissibleGroup`, `admissibleGroup_convex`,
`admissibleGroup_le`). The admissible domain `U_q` is `v⁻¹(H_α) ⊆ K^×`.

* `tate:lem:normalize`: for `α > 0`, `β ∈ H_α` iff some integer `m` has
  `0 ≤ β + mα < α`; such `m` is unique; outside `H_α` either `β > Nα` for all `N`
  or `β < -Nα` for all `N`.
* `tate:thm:theta`, domain clause: for `u ≠ 0` the bilateral family
  `((-1)^n q^{n(n-1)/2} u^n)_{n ∈ ℤ}` is strongly summable (a `SummableFamily`)
  if and only if `u ∈ U_q`, i.e. `v(u) ∈ H_α` (`thetaSummable_iff`).
* `tate:eq:theta-functional`: on that domain `Θ_q(qu) = -u⁻¹ Θ_q(u)`
  (`theta_mul_left`), and `qu` again lies in the domain.

The proof follows the report. The leading exponent of the `n`th summand is
`b_n = n(n-1)/2 α + nβ` (`tate:eq:bn`); each summand is `±t^{b_n}` times an order-zero
series whose support lies in the monoid `M` generated by the supports of the
normalized units of `q` and `u`, negative powers included. For necessity, the
exponents `b_n` are actual support points, and outside `H_α` they strictly decrease
along `n → -∞` or `n → +∞`, contradicting well-ordering; no cancellation between
summands is assumed away. For sufficiency, the sublevel sets `{n | b_n ≤ γ}` are
finite for every `γ ∈ H_α` (not for arbitrary `γ`), which makes `{b_n}` partially
well ordered with finite fibres, and the finite antidiagonals of `{b_n}` and `M`
give finite co-support. The sum `Θ_q(u)` is defined as the strong sum when it
exists; it depends only on the family of summands. Off the summability predicate
`theta` is `0` by convention, and at `u = 0` (outside the source's domain `K^×`) the
Lean family degenerates to the single term `1`, so `theta q 0 = 1` (`theta_zero_right`).

Of `tate:thm:main`, and of its form `tate:node:thm:main` over a field of characteristic
zero (the statements here hold over any field `k`), only the theta-summability clause
is proved here, for `u ∈ K^×` (`thetaSummable_iff_mem_admissibleDomain`); the
normal-form clause of `tate:node:thm:main` is covered only at the level of valuations,
by `tate:lem:normalize` (`mem_admissibleGroup_iff_existsUnique`). The coordinate
families `X_q`, `Y_q` (`tate:thm:coordinates`), the group homomorphism `Φ_q`, its
kernel and surjectivity, and the product formula `tate:prop:theta-product` remain
pending.
-/

namespace Surreal.Tate

open _root_.HahnSeries
open scoped Pointwise

noncomputable section

variable {Γ k : Type*} [AddCommGroup Γ] [LinearOrder Γ] [IsOrderedAddMonoid Γ]

section Admissible

/-- `tate:def:domain`, equation `tate:eq:H`: the admissible group
`H_α = {γ | -Nα ≤ γ ≤ Nα for some N ∈ ℕ}`. The definition makes sense for every `α`
(for `α ≤ 0` it is `{0}`); the source only uses `α > 0`. -/
def admissibleGroup (α : Γ) : AddSubgroup Γ where
  carrier := {γ | ∃ N : ℕ, -(N • α) ≤ γ ∧ γ ≤ N • α}
  zero_mem' := ⟨0, by simp⟩
  add_mem' := by
    rintro a b ⟨M, hM1, hM2⟩ ⟨N, hN1, hN2⟩
    refine ⟨M + N, ?_, ?_⟩
    · rw [add_nsmul, neg_add]
      exact add_le_add hM1 hN1
    · rw [add_nsmul]
      exact add_le_add hM2 hN2
  neg_mem' := by
    rintro a ⟨N, h1, h2⟩
    exact ⟨N, neg_le_neg h2, by simpa using neg_le_neg h1⟩

theorem mem_admissibleGroup {α γ : Γ} :
    γ ∈ admissibleGroup α ↔ ∃ N : ℕ, -(N • α) ≤ γ ∧ γ ≤ N • α :=
  Iff.rfl

theorem self_mem_admissibleGroup {α : Γ} (hα : 0 ≤ α) : α ∈ admissibleGroup α :=
  ⟨1, by rw [one_nsmul]; exact (neg_nonpos.mpr hα).trans hα, by rw [one_nsmul]⟩

/-- `tate:def:domain`: `H_α` is convex. -/
theorem admissibleGroup_convex {α a b c : Γ} (hα : 0 ≤ α) (ha : a ∈ admissibleGroup α)
    (hb : b ∈ admissibleGroup α) (hac : a ≤ c) (hcb : c ≤ b) : c ∈ admissibleGroup α := by
  obtain ⟨M, hM, -⟩ := ha
  obtain ⟨N, -, hN⟩ := hb
  refine ⟨M + N, ?_, ?_⟩
  · refine le_trans ?_ (hM.trans hac)
    exact neg_le_neg (nsmul_le_nsmul_left hα (Nat.le_add_right M N))
  · exact (hcb.trans hN).trans (nsmul_le_nsmul_left hα (Nat.le_add_left N M))

/-- `tate:def:domain`: `H_α` is contained in every convex subgroup containing `α`. -/
theorem admissibleGroup_le {α : Γ} {G : AddSubgroup Γ} (hαG : α ∈ G)
    (hG : ∀ a b c : Γ, a ∈ G → b ∈ G → a ≤ c → c ≤ b → c ∈ G) : admissibleGroup α ≤ G := by
  rintro γ ⟨N, h1, h2⟩
  exact hG _ _ γ (G.neg_mem (G.nsmul_mem hαG N)) (G.nsmul_mem hαG N) h1 h2

theorem normalize_not_lt {α β : Γ} (hα : 0 < α) {m m' : ℤ} (h1 : 0 ≤ β + m • α)
    (h2' : β + m' • α < α) : ¬m < m' := by
  intro hlt
  have h : (m + 1) • α ≤ m' • α := zsmul_le_zsmul_left hα.le (by omega)
  rw [add_zsmul, one_zsmul] at h
  refine (lt_irrefl α) (lt_of_le_of_lt ?_ h2')
  calc α = 0 + α := (zero_add α).symm
    _ ≤ (β + m • α) + α := by gcongr
    _ = β + (m • α + α) := add_assoc _ _ _
    _ ≤ β + m' • α := by gcongr

/-- `tate:lem:normalize`, (i) ⇔ (ii): `β ∈ H_α` iff `0 ≤ β + mα < α` for some integer
`m`. -/
theorem mem_admissibleGroup_iff_exists {α β : Γ} (hα : 0 < α) :
    β ∈ admissibleGroup α ↔ ∃ m : ℤ, 0 ≤ β + m • α ∧ β + m • α < α := by
  constructor
  · rintro ⟨N, h1, h2⟩
    obtain ⟨z, hz, hmax⟩ := Int.exists_greatest_of_bdd (P := fun z : ℤ => z • α ≤ β)
      ⟨N, fun z hz => (zsmul_le_zsmul_iff_left hα).mp
        (hz.trans (by rw [natCast_zsmul]; exact h2))⟩
      ⟨-N, by rw [neg_zsmul, natCast_zsmul]; exact h1⟩
    refine ⟨-z, ?_, ?_⟩
    · rw [neg_zsmul, ← sub_eq_add_neg, sub_nonneg]
      exact hz
    · rw [neg_zsmul, ← sub_eq_add_neg, sub_lt_iff_lt_add]
      by_contra hle
      have h := hmax (z + 1) (by
        rw [add_zsmul, one_zsmul, add_comm]
        exact not_lt.mp hle)
      omega
  · rintro ⟨m, h1, h2⟩
    have hαH := self_mem_admissibleGroup hα.le
    have hr : β + m • α ∈ admissibleGroup α :=
      ⟨1, by rw [one_nsmul]; exact (neg_nonpos.mpr hα.le).trans h1, by rw [one_nsmul]; exact h2.le⟩
    simpa using sub_mem hr (zsmul_mem hαH m)

/-- `tate:lem:normalize`: the normalizing integer is unique. -/
theorem mem_admissibleGroup_iff_existsUnique {α β : Γ} (hα : 0 < α) :
    β ∈ admissibleGroup α ↔ ∃! m : ℤ, 0 ≤ β + m • α ∧ β + m • α < α := by
  rw [mem_admissibleGroup_iff_exists hα]
  refine ⟨fun ⟨m, hm⟩ => ⟨m, hm, fun m' hm' => ?_⟩, fun h => h.exists⟩
  exact le_antisymm (not_lt.mp (normalize_not_lt hα hm.1 hm'.2))
    (not_lt.mp (normalize_not_lt hα hm'.1 hm.2))

/-- `tate:lem:normalize`: outside `H_α`, either `β > Nα` for every `N` or `β < -Nα` for
every `N`. -/
theorem forall_lt_or_forall_lt_of_not_mem {α β : Γ} (hα : 0 ≤ α)
    (h : β ∉ admissibleGroup α) : (∀ N : ℕ, N • α < β) ∨ ∀ N : ℕ, β < -(N • α) := by
  by_contra hne
  push Not at hne
  obtain ⟨⟨M, hM⟩, ⟨N, hN⟩⟩ := hne
  refine h ⟨M + N, ?_, ?_⟩
  · exact (neg_le_neg (nsmul_le_nsmul_left hα (Nat.le_add_left N M))).trans hN
  · exact hM.trans (nsmul_le_nsmul_left hα (Nat.le_add_right M N))

end Admissible

section Exponents

/-- The triangular exponent `n(n-1)/2` of `tate:eq:theta`. -/
def triangle (n : ℤ) : ℤ := n * (n - 1) / 2

theorem two_mul_triangle (n : ℤ) : 2 * triangle n = n * (n - 1) :=
  Int.mul_ediv_cancel' (Int.even_mul_pred_self n).two_dvd

theorem triangle_add_one (n : ℤ) : triangle (n + 1) = triangle n + n := by
  have h1 := two_mul_triangle n
  have h2 := two_mul_triangle (n + 1)
  linarith

/-- `tate:eq:bn`: the leading exponent `b_n = n(n-1)/2 α + nβ` of the `n`th summand. -/
def leadExp (α β : Γ) (n : ℤ) : Γ := triangle n • α + n • β

omit [LinearOrder Γ] [IsOrderedAddMonoid Γ] in
theorem leadExp_add_one (α β : Γ) (n : ℤ) :
    leadExp α β (n + 1) = leadExp α β n + (n • α + β) := by
  rw [leadExp, leadExp, triangle_add_one, add_zsmul, add_zsmul, one_zsmul]
  abel

theorem leadExp_mem {α β : Γ} (hα : 0 ≤ α) (hβ : β ∈ admissibleGroup α) (n : ℤ) :
    leadExp α β n ∈ admissibleGroup α :=
  add_mem (zsmul_mem (self_mem_admissibleGroup hα) _) (zsmul_mem hβ _)

theorem sub_abs_mul_zsmul_le_leadExp {α β : Γ} {N : ℕ} (h1 : -(N • α) ≤ β) (h2 : β ≤ N • α)
    (n : ℤ) : (triangle n - |n| * N) • α ≤ leadExp α β n := by
  rw [leadExp, sub_eq_add_neg, add_zsmul]
  gcongr
  rw [← natCast_zsmul] at h1 h2
  rcases le_or_gt 0 n with hn | hn
  · rw [abs_of_nonneg hn]
    calc (-(n * N)) • α = n • -((N : ℤ) • α) := by rw [smul_neg, smul_smul, neg_zsmul]
      _ ≤ n • β := zsmul_le_zsmul_right hn h1
  · rw [abs_of_neg hn]
    calc (-(-n * N)) • α = (-n) • -((N : ℤ) • α) := by rw [smul_neg, smul_smul, neg_zsmul]
      _ ≤ (-n) • -β := zsmul_le_zsmul_right (by omega) (neg_le_neg h2)
      _ = n • β := by rw [smul_neg, neg_zsmul, neg_neg]

theorem abs_le_of_triangle_sub_le {n N G : ℤ} (hN : 0 ≤ N) (hG : 0 ≤ G)
    (h : triangle n - |n| * N ≤ G) : |n| ≤ 2 * (N + G) + 1 := by
  have ht := two_mul_triangle n
  rcases le_or_gt 0 n with hn | hn
  · rw [abs_of_nonneg hn] at h ⊢
    by_contra hbig
    push Not at hbig
    nlinarith [mul_nonneg hn (by omega : (0 : ℤ) ≤ n - 2 * (N + G) - 2),
      mul_nonneg (by omega : (0 : ℤ) ≤ n - 1) (by omega : (0 : ℤ) ≤ 2 * G + 1)]
  · rw [abs_of_neg hn] at h ⊢
    by_contra hbig
    push Not at hbig
    nlinarith [mul_nonneg (by omega : (0 : ℤ) ≤ -n) (by omega : (0 : ℤ) ≤ -n - 2 * (N + G) - 1),
      mul_nonneg (by omega : (0 : ℤ) ≤ -n - 1) (by omega : (0 : ℤ) ≤ 2 * G + 1)]

/-- Local finiteness of the leading exponents: below any `γ ∈ H_α` lie only finitely many
`b_n`. (Sublevel sets at exponents above `H_α` are infinite.) -/
theorem finite_setOf_leadExp_le {α β γ : Γ} (hα : 0 < α) (hβ : β ∈ admissibleGroup α)
    (hγ : γ ∈ admissibleGroup α) : {n : ℤ | leadExp α β n ≤ γ}.Finite := by
  obtain ⟨N, hN1, hN2⟩ := hβ
  obtain ⟨G, -, hG⟩ := hγ
  refine (Set.finite_Icc (-(2 * ((N : ℤ) + G) + 1)) (2 * ((N : ℤ) + G) + 1)).subset
    fun n hn => ?_
  have h1 := (sub_abs_mul_zsmul_le_leadExp hN1 hN2 n).trans
    ((show leadExp α β n ≤ γ from hn).trans hG)
  rw [← natCast_zsmul, zsmul_le_zsmul_iff_left hα] at h1
  exact abs_le.mp (abs_le_of_triangle_sub_le (Int.natCast_nonneg N) (Int.natCast_nonneg G) h1)

theorem isPWO_range_leadExp {α β : Γ} (hα : 0 < α) (hβ : β ∈ admissibleGroup α) :
    (Set.range (leadExp α β)).IsPWO := by
  rw [Set.IsPWO, Set.partiallyWellOrderedOn_iff_exists_lt]
  intro f hf
  by_cases h : ∃ j, 0 < j ∧ f 0 ≤ f j
  · obtain ⟨j, hj, hle⟩ := h
    exact ⟨0, j, hj, hle⟩
  push Not at h
  obtain ⟨n0, hn0⟩ := hf 0
  have hfin : (leadExp α β '' {n | leadExp α β n ≤ f 0}).Finite :=
    (finite_setOf_leadExp_le hα hβ (hn0 ▸ leadExp_mem hα.le hβ n0)).image _
  obtain ⟨i, j, hij, hle⟩ := Set.PartiallyWellOrderedOn.exists_lt hfin.isPWO
    (f := fun i => f (i + 1)) fun i => by
      obtain ⟨n, hn⟩ := hf (i + 1)
      refine ⟨n, ?_, hn⟩
      rw [Set.mem_setOf_eq, hn]
      exact (h (i + 1) (Nat.succ_pos i)).le
  exact ⟨i + 1, j + 1, by omega, hle⟩

theorem finite_leadExp_fiber {α β : Γ} (hα : 0 < α) (hβ : β ∈ admissibleGroup α) (x : Γ) :
    {n : ℤ | leadExp α β n = x}.Finite := by
  by_cases hx : x ∈ admissibleGroup α
  · exact (finite_setOf_leadExp_le hα hβ hx).subset fun n hn => le_of_eq hn
  · refine Set.finite_empty.subset fun n (hn : leadExp α β n = x) => ?_
    exact hx (hn ▸ leadExp_mem hα.le hβ n)

end Exponents

section Normalization

variable [Field k]

/-- The normalized series `t^{-v(x)} x`; for `x ≠ 0` it has order zero. -/
def unitPart (x : k⟦Γ⟧) : k⟦Γ⟧ := single (-x.order) (1 : k) * x

theorem single_order_mul_unitPart (x : k⟦Γ⟧) : single x.order (1 : k) * unitPart x = x := by
  rw [unitPart, ← mul_assoc, single_mul_single, add_neg_cancel, mul_one, single_zero_one,
    one_mul]

theorem orderTop_unitPart {x : k⟦Γ⟧} (hx : x ≠ 0) : (unitPart x).orderTop = 0 := by
  rw [unitPart, orderTop_mul, orderTop_single one_ne_zero, ← order_eq_orderTop_of_ne_zero hx,
    ← WithTop.coe_add, neg_add_cancel, WithTop.coe_zero]

theorem single_one_zpow (g : Γ) (n : ℤ) : single g (1 : k) ^ n = single (n • g) 1 := by
  obtain ⟨m, rfl | rfl⟩ := n.eq_nat_or_neg
  · rw [zpow_natCast, single_pow, one_pow, natCast_zsmul]
  · rw [zpow_neg, zpow_natCast, single_pow, one_pow, inv_single, inv_one, neg_zsmul,
      natCast_zsmul]

theorem zpow_eq_single_mul (x : k⟦Γ⟧) (n : ℤ) :
    x ^ n = single (n • x.order) (1 : k) * unitPart x ^ n := by
  conv_lhs => rw [← single_order_mul_unitPart x]
  rw [mul_zpow, single_one_zpow]

theorem orderTop_inv_eq_zero {y : k⟦Γ⟧} (hy : y.orderTop = 0) : y⁻¹.orderTop = 0 := by
  have hy0 : y ≠ 0 := by
    rintro rfl
    simp at hy
  have h := congrArg orderTop (mul_inv_cancel₀ hy0)
  rwa [orderTop_mul, orderTop_one, hy, zero_add] at h

theorem orderTop_pow_eq_zero {y : k⟦Γ⟧} (hy : y.orderTop = 0) (n : ℕ) :
    (y ^ n).orderTop = 0 := by
  induction n with
  | zero => rw [pow_zero, orderTop_one]
  | succ n ih => rw [pow_succ, orderTop_mul, ih, hy, add_zero]

theorem orderTop_zpow_eq_zero {y : k⟦Γ⟧} (hy : y.orderTop = 0) (n : ℤ) :
    (y ^ n).orderTop = 0 := by
  obtain ⟨m, rfl | rfl⟩ := n.eq_nat_or_neg
  · rw [zpow_natCast]
    exact orderTop_pow_eq_zero hy m
  · rw [zpow_neg, zpow_natCast]
    exact orderTop_inv_eq_zero (orderTop_pow_eq_zero hy m)

theorem support_C_mul_subset (a : k) (z : k⟦Γ⟧) : (C a * z).support ⊆ z.support := by
  intro g hg
  rw [mem_support, C_mul_eq_smul, coeff_smul, smul_eq_mul] at hg
  exact (mem_support _ _).mpr (right_ne_zero_of_mul hg)

/-- Inverses of order-zero series: the support stays in the generated monoid
(`tate:lem:neumann`, applied to `(1 - ε)⁻¹`). -/
theorem support_inv_subset_closure {y : k⟦Γ⟧} (hy : y.orderTop = 0) :
    y⁻¹.support ⊆ AddSubmonoid.closure y.support := by
  have hc : y.coeff 0 ≠ 0 := coeff_orderTop_ne (by rw [hy]; rfl)
  set w := C (y.coeff 0)⁻¹ * y with hw
  have hyw : y = C (y.coeff 0) * w := by
    rw [hw, ← mul_assoc, ← map_mul, mul_inv_cancel₀ hc, map_one, one_mul]
  have hcoeff : ∀ g, (1 - w).coeff g = (1 : k⟦Γ⟧).coeff g - (y.coeff 0)⁻¹ * y.coeff g := by
    intro g
    rw [coeff_sub, hw, C_mul_eq_smul, coeff_smul, smul_eq_mul]
  have hpos : 0 < (1 - w).orderTop := by
    refine Surreal.HahnSeries.orderTop_pos_of_support_pos fun g hg => ?_
    by_contra hle
    push Not at hle
    apply (mem_support _ _).mp hg
    rw [hcoeff]
    rcases hle.lt_or_eq with hlt | rfl
    · have h1 : y.coeff g = 0 :=
        coeff_eq_zero_of_lt_orderTop (by rw [hy]; exact WithTop.coe_lt_coe.mpr hlt)
      rw [coeff_one, if_neg hlt.ne, h1, mul_zero, sub_zero]
    · rw [coeff_one, if_pos rfl, inv_mul_cancel₀ hc, sub_self]
  have hsub : (1 - w).support ⊆ AddSubmonoid.closure y.support := by
    intro g hg
    rcases eq_or_ne g 0 with rfl | hg0
    · exact AddSubmonoid.zero_mem _
    · apply AddSubmonoid.subset_closure
      rw [mem_support] at hg ⊢
      intro h0
      apply hg
      rw [hcoeff, coeff_one, if_neg hg0, h0, mul_zero, sub_zero]
  have hyinv : y⁻¹ = C (y.coeff 0)⁻¹ * (1 - (1 - w))⁻¹ := by
    rw [sub_sub_cancel]
    conv_lhs => rw [hyw]
    rw [mul_inv, map_inv₀]
  rw [hyinv]
  refine (support_C_mul_subset _ _).trans ?_
  refine (Surreal.HahnSeries.support_inv_one_sub_subset hpos).trans ?_
  exact SetLike.coe_subset_coe.mpr (AddSubmonoid.closure_le.mpr hsub)

theorem support_zpow_subset_closure {y : k⟦Γ⟧} (hy : y.orderTop = 0) (n : ℤ) :
    (y ^ n).support ⊆ AddSubmonoid.closure y.support := by
  obtain ⟨m, rfl | rfl⟩ := n.eq_nat_or_neg
  · rw [zpow_natCast]
    exact SummableFamily.support_pow_subset_closure y m
  · rw [zpow_neg, zpow_natCast]
    refine (support_inv_subset_closure (orderTop_pow_eq_zero hy m)).trans ?_
    exact SetLike.coe_subset_coe.mpr
      (AddSubmonoid.closure_le.mpr (SummableFamily.support_pow_subset_closure y m))

omit [IsOrderedAddMonoid Γ] in
theorem nonneg_of_mem_support {y : k⟦Γ⟧} (hy : y.orderTop = 0) {g : Γ} (hg : g ∈ y.support) :
    0 ≤ g := by
  have h := orderTop_le_of_coeff_ne_zero ((mem_support _ _).mp hg)
  rw [hy] at h
  exact WithTop.coe_le_coe.mp h

end Normalization

section Theta

variable [Field k] {q u : k⟦Γ⟧}

omit [IsOrderedAddMonoid Γ] in
/-- A series of positive order is nonzero, because Mathlib sets `order 0 = 0`; so the
hypothesis `0 < v(q)` already contains the source's `q ∈ K^×`. -/
theorem ne_zero_of_order_pos (hq : 0 < q.order) : q ≠ 0 := by
  rintro rfl
  simp at hq

/-- `tate:def:domain`, equation `tate:eq:U`: the admissible multiplicative domain
`U_q = v⁻¹(H_α) ⊆ K^×`. -/
def admissibleDomain (q : k⟦Γ⟧) : Set k⟦Γ⟧ :=
  {u | u ≠ 0 ∧ u.order ∈ admissibleGroup q.order}

/-- The `n`th summand `(-1)^n q^{n(n-1)/2} u^n` of the bilateral family `tate:eq:theta`. -/
def thetaTerm (q u : k⟦Γ⟧) (n : ℤ) : k⟦Γ⟧ := (-1) ^ n * q ^ triangle n * u ^ n

/-- Strong summability of the bilateral theta family `tate:eq:theta`. -/
def ThetaSummable (q u : k⟦Γ⟧) : Prop := ∃ s : SummableFamily Γ k ℤ, ⇑s = thetaTerm q u

/-- The order-zero factor of the `n`th theta summand. -/
def thetaUnit (q u : k⟦Γ⟧) (n : ℤ) : k⟦Γ⟧ := unitPart q ^ triangle n * unitPart u ^ n

/-- The monoid `M` generated by the supports of the normalized units of `q` and `u`. -/
def supportMonoid (q u : k⟦Γ⟧) : AddSubmonoid Γ :=
  AddSubmonoid.closure ((unitPart q).support ∪ (unitPart u).support)

theorem thetaTerm_eq (q u : k⟦Γ⟧) (n : ℤ) :
    thetaTerm q u n =
      (-1) ^ n * (single (leadExp q.order u.order n) (1 : k) * thetaUnit q u n) := by
  have h : single (triangle n • q.order + n • u.order) (1 : k) =
      single (triangle n • q.order) (1 : k) * single (n • u.order) 1 := by
    rw [single_mul_single, mul_one]
  rw [thetaTerm, zpow_eq_single_mul q, zpow_eq_single_mul u, leadExp, thetaUnit, h]
  ring

theorem orderTop_thetaUnit (hq : q ≠ 0) (hu : u ≠ 0) (n : ℤ) :
    (thetaUnit q u n).orderTop = 0 := by
  rw [thetaUnit, orderTop_mul, orderTop_zpow_eq_zero (orderTop_unitPart hq),
    orderTop_zpow_eq_zero (orderTop_unitPart hu), add_zero]

theorem support_thetaUnit_subset (hq : q ≠ 0) (hu : u ≠ 0) (n : ℤ) :
    (thetaUnit q u n).support ⊆ supportMonoid q u := by
  intro g hg
  obtain ⟨a, ha, b, hb, rfl⟩ := support_mul_subset hg
  refine AddSubmonoid.add_mem _ ?_ ?_
  · exact AddSubmonoid.closure_mono Set.subset_union_left
      (support_zpow_subset_closure (orderTop_unitPart hq) _ ha)
  · exact AddSubmonoid.closure_mono Set.subset_union_right
      (support_zpow_subset_closure (orderTop_unitPart hu) _ hb)

theorem isPWO_supportMonoid (hq : q ≠ 0) (hu : u ≠ 0) :
    (supportMonoid q u : Set Γ).IsPWO := by
  refine Set.IsPWO.addSubmonoid_closure ?_
    ((unitPart q).isPWO_support.union (unitPart u).isPWO_support)
  rintro g (hg | hg)
  · exact nonneg_of_mem_support (orderTop_unitPart hq) hg
  · exact nonneg_of_mem_support (orderTop_unitPart hu) hg

theorem support_thetaTerm (q u : k⟦Γ⟧) (n : ℤ) :
    (thetaTerm q u n).support =
      (single (leadExp q.order u.order n) (1 : k) * thetaUnit q u n).support := by
  rw [thetaTerm_eq, neg_one_zpow_eq_ite]
  split_ifs
  · rw [one_mul]
  · rw [neg_one_mul, support_neg]

/-- The leading exponent `b_n` of `tate:eq:bn` is an actual support point of the `n`th
summand. -/
theorem leadExp_mem_support_thetaTerm (hq : q ≠ 0) (hu : u ≠ 0) (n : ℤ) :
    leadExp q.order u.order n ∈ (thetaTerm q u n).support := by
  rw [support_thetaTerm, mem_support]
  have h := coeff_single_mul_add (r := (1 : k)) (x := thetaUnit q u n) (a := 0)
    (b := leadExp q.order u.order n)
  rw [zero_add] at h
  rw [h, one_mul]
  exact coeff_orderTop_ne (by rw [orderTop_thetaUnit hq hu]; rfl)

/-- Every support point of the `n`th summand lies in `b_n + M`. -/
theorem exists_of_mem_support_thetaTerm (hq : q ≠ 0) (hu : u ≠ 0) {n : ℤ} {γ : Γ}
    (hγ : γ ∈ (thetaTerm q u n).support) :
    ∃ m ∈ supportMonoid q u, leadExp q.order u.order n + m = γ := by
  rw [support_thetaTerm] at hγ
  obtain ⟨a, ha, b, hb, rfl⟩ := support_mul_subset hγ
  refine ⟨b, support_thetaUnit_subset hq hu n hb, ?_⟩
  rw [Set.mem_singleton_iff.mp (support_single_subset ha)]

/-- Sufficiency in `tate:thm:theta`: for `v(u) ∈ H_α` the theta summands form a strongly
summable family. -/
def thetaFamily (hq : 0 < q.order) (hu : u ≠ 0)
    (hdom : u.order ∈ admissibleGroup q.order) : SummableFamily Γ k ℤ where
  toFun := thetaTerm q u
  isPWO_iUnion_support' := by
    have hq0 := ne_zero_of_order_pos hq
    refine ((isPWO_range_leadExp hq hdom).add (isPWO_supportMonoid hq0 hu)).mono ?_
    refine Set.iUnion_subset fun n γ hγ => ?_
    obtain ⟨m, hm, rfl⟩ := exists_of_mem_support_thetaTerm hq0 hu hγ
    exact Set.add_mem_add ⟨n, rfl⟩ hm
  finite_co_support' γ := by
    have hq0 := ne_zero_of_order_pos hq
    have hfin := Set.AddAntidiagonal.finite_of_isPWO (isPWO_range_leadExp hq hdom)
      (isPWO_supportMonoid hq0 hu) γ
    refine (hfin.biUnion fun p _ => finite_leadExp_fiber hq hdom p.1).subset fun n hn => ?_
    obtain ⟨m, hm, hγ⟩ := exists_of_mem_support_thetaTerm hq0 hu ((mem_support _ _).mpr hn)
    exact Set.mem_biUnion (x := (leadExp q.order u.order n, m)) ⟨⟨n, rfl⟩, hm, hγ⟩
      (show leadExp q.order u.order n = leadExp q.order u.order n from rfl)

@[simp]
theorem thetaFamily_apply (hq : 0 < q.order) (hu : u ≠ 0)
    (hdom : u.order ∈ admissibleGroup q.order) (n : ℤ) :
    thetaFamily hq hu hdom n = thetaTerm q u n :=
  rfl

/-- Necessity in `tate:thm:theta`: outside `H_α` the leading exponents strictly decrease
along one tail, so the union of supports is not well ordered. -/
theorem mem_admissibleGroup_of_thetaSummable (hq : 0 < q.order) (hu : u ≠ 0)
    (h : ThetaSummable q u) : u.order ∈ admissibleGroup q.order := by
  have hq0 := ne_zero_of_order_pos hq
  obtain ⟨s, hs⟩ := h
  by_contra hnot
  set α := q.order
  set β := u.order
  have hmem : ∀ n, leadExp α β n ∈ ⋃ i, (s i).support := fun n =>
    Set.mem_iUnion.mpr ⟨n, by rw [hs]; exact leadExp_mem_support_thetaTerm hq0 hu n⟩
  have key : ∀ f : ℕ → ℤ, (∀ j, leadExp α β (f (j + 1)) < leadExp α β (f j)) → False := by
    intro f hf
    obtain ⟨i, j, hij, hle⟩ := Set.PartiallyWellOrderedOn.exists_lt s.isPWO_iUnion_support
      (f := fun j => leadExp α β (f j)) fun j => hmem (f j)
    have hanti : StrictAnti fun j => leadExp α β (f j) := strictAnti_nat_of_succ_lt hf
    exact (hanti hij).not_ge hle
  rcases forall_lt_or_forall_lt_of_not_mem hq.le hnot with hA | hB
  · refine key (fun j => -(j : ℤ)) fun j => ?_
    have e : -((j + 1 : ℕ) : ℤ) + 1 = -(j : ℤ) := by push_cast; ring
    show leadExp α β (-((j + 1 : ℕ) : ℤ)) < leadExp α β (-(j : ℤ))
    rw [← e, leadExp_add_one]
    refine lt_add_of_pos_right _ ?_
    rw [neg_zsmul, natCast_zsmul, neg_add_eq_sub, sub_pos]
    exact hA (j + 1)
  · refine key (fun j => (j : ℤ)) fun j => ?_
    show leadExp α β ((j + 1 : ℕ) : ℤ) < leadExp α β (j : ℤ)
    rw [Nat.cast_add, Nat.cast_one, leadExp_add_one]
    refine add_lt_of_neg_right _ ?_
    rw [natCast_zsmul]
    have := hB j
    rw [lt_neg_iff_add_neg'] at this
    exact this

/-- `tate:thm:theta`, domain clause: for `v(q) = α > 0` and `u ≠ 0`, the bilateral family
`(-1)^n q^{n(n-1)/2} u^n` is strongly summable iff `v(u) ∈ H_α`. -/
theorem thetaSummable_iff (hq : 0 < q.order) (hu : u ≠ 0) :
    ThetaSummable q u ↔ u.order ∈ admissibleGroup q.order :=
  ⟨mem_admissibleGroup_of_thetaSummable hq hu,
    fun hdom => ⟨thetaFamily hq hu hdom, rfl⟩⟩

/-- `tate:thm:theta`, domain clause, which is also the theta-summability clause of
`tate:thm:main` and of `tate:node:thm:main` (over any field `k`): for `v(q) > 0` and
`u ∈ K^×` the family is strongly summable exactly when `u ∈ U_q`. -/
theorem thetaSummable_iff_mem_admissibleDomain (hq : 0 < q.order)
    (hu : u ≠ 0) : ThetaSummable q u ↔ u ∈ admissibleDomain q := by
  rw [thetaSummable_iff hq hu, admissibleDomain, Set.mem_setOf_eq, and_iff_right hu]

open Classical in
/-- The strong sum `Θ_q(u)` of `tate:eq:theta` when the family is strongly summable
(`ThetaSummable q u`), and `0` by convention otherwise; for `v(q) > 0` and `u ≠ 0` this
means `0` off `U_q`. At `u = 0`, outside the source's domain `K^×`, the Lean family
degenerates to the single term `1` (as `0 ^ n = 0` for `n ≠ 0`), so `theta q 0 = 1`
(`theta_zero_right`). -/
def theta (q u : k⟦Γ⟧) : k⟦Γ⟧ :=
  if h : ThetaSummable q u then h.choose.hsum else 0

/-- `Θ_q(u)` is the strong sum of any summable family with the theta summands. -/
theorem theta_eq_hsum {s : SummableFamily Γ k ℤ} (hs : ⇑s = thetaTerm q u) :
    theta q u = s.hsum := by
  have h : ThetaSummable q u := ⟨s, hs⟩
  rw [theta, dif_pos h, SummableFamily.coe_injective (h.choose_spec.trans hs.symm)]

/-- A convention outside the source's domain `K^×`: at `u = 0` the Lean theta family is the
single term `1` at `n = 0` (because `0 ^ n = 0` for every `n ≠ 0`, negative `n` included,
as `0⁻¹ = 0`), so `theta q 0 = 1`. -/
theorem theta_zero_right (q : k⟦Γ⟧) : theta q 0 = 1 := by
  have hs : ⇑(SummableFamily.ofFinsupp (Finsupp.single (0 : ℤ) (1 : k⟦Γ⟧))) =
      thetaTerm q 0 := by
    rw [SummableFamily.coe_ofFinsupp]
    funext n
    rcases eq_or_ne n 0 with rfl | hn
    · simp [thetaTerm, triangle]
    · simp [thetaTerm, hn, zero_zpow n hn]
  rw [theta_eq_hsum hs, SummableFamily.hsum_ofFinsupp, Finsupp.sum_single_index rfl, id]

theorem coeff_theta (h : ThetaSummable q u) (g : Γ) :
    (theta q u).coeff g = ∑ᶠ n, (thetaTerm q u n).coeff g := by
  obtain ⟨s, hs⟩ := h
  rw [theta_eq_hsum hs, SummableFamily.coeff_hsum, hs]

theorem thetaTerm_mul_left (hq : q ≠ 0) (hu : u ≠ 0) (n : ℤ) :
    thetaTerm q (q * u) n = -u⁻¹ * thetaTerm q u (n + 1) := by
  have h1 : u⁻¹ * u = 1 := inv_mul_cancel₀ hu
  rw [thetaTerm, thetaTerm, mul_zpow, triangle_add_one, zpow_add₀ hq, zpow_add₀ hu,
    zpow_add₀ (neg_ne_zero.mpr one_ne_zero), zpow_one, zpow_one]
  linear_combination (-(-1) ^ n * q ^ triangle n * q ^ n * u ^ n) * h1

/-- For `v(q) > 0` the admissible domain is stable under multiplication by `q`, so both
sides of `tate:eq:theta-functional` (`tate:thm:theta`) are strong sums. -/
theorem mul_left_mem_admissibleDomain (hq : 0 < q.order)
    (hu : u ∈ admissibleDomain q) : q * u ∈ admissibleDomain q := by
  have hq0 := ne_zero_of_order_pos hq
  refine ⟨mul_ne_zero hq0 hu.1, ?_⟩
  rw [order_mul hq0 hu.1]
  exact add_mem (self_mem_admissibleGroup hq.le) hu.2

/-- `tate:thm:theta`, equation `tate:eq:theta-functional`: on the admissible domain,
`Θ_q(qu) = -u⁻¹ Θ_q(u)`. -/
theorem theta_mul_left (hq : 0 < q.order) (hu : u ∈ admissibleDomain q) :
    theta q (q * u) = -u⁻¹ * theta q u := by
  have hq0 := ne_zero_of_order_pos hq
  obtain ⟨hu0, hdom⟩ := hu
  set s := thetaFamily hq hu0 hdom
  have hshift : ⇑((-u⁻¹) • SummableFamily.Equiv (Equiv.addRight (1 : ℤ)).symm s) =
      thetaTerm q (q * u) := by
    funext n
    rw [SummableFamily.smul_apply, HahnSeries.of_symm_smul_of_eq_mul,
      SummableFamily.Equiv_toFun, Equiv.symm_symm, Equiv.coe_addRight, thetaFamily_apply,
      thetaTerm_mul_left hq0 hu0]
  rw [theta_eq_hsum hshift, SummableFamily.hsum_smul, SummableFamily.hsum_equiv,
    theta_eq_hsum (s := s) rfl]

end Theta

end

end Surreal.Tate
