import Surreal.Foundations.OmnificIntegers
import Surreal.Algebra.CoefficientPullbackDivisibility
import Mathlib.Data.ZMod.QuotientRing
import Mathlib.NumberTheory.Padics.PadicVal.Basic

/-!
# Ordinary divisibility and residue rings of actual omnific integers

The ordinary-modulus theorem `odg:thm:finitequotients`, including
`odg:eq:nOz` and `odg:eq:divkernel`. Nonzero ordinary moduli see only the
integer constant coefficient. The kernel intersections and exact prime-power
divisibility bounds are expressed on the actual omnific ring.
-/

universe u
namespace Surreal.Foundations.SignSequence

noncomputable section

/-- Divisibility by a nonzero ordinary integer is detected exactly by the constant term. -/
theorem omnific_int_dvd_iff (n : ℤ) (hn : n ≠ 0) (x : OmnificInteger.{u}) :
    omnificIntCast n ∣ x ↔ n ∣ omnificConstantCoeff x :=
  CoefficientPullback.sectionMap_dvd_iff constantCoeff (Int.castRingHom ℝ)
    Int.cast_injective realConstants constantCoeff_realConstants n
    (by change (n : ℝ) ≠ 0; exact_mod_cast hn) x

/-- Every purely infinite omnific integer is divisible by every nonzero ordinary integer. -/
theorem omnific_int_dvd_of_purelyInfinite (n : ℤ) (hn : n ≠ 0) (x : OmnificInteger.{u})
    (hx : x ∈ omnificPurelyInfiniteIdeal) : omnificIntCast n ∣ x := by
  rw [omnific_int_dvd_iff n hn]
  change omnificConstantCoeff x = 0 at hx
  rw [hx]
  exact dvd_zero n

/-- The equation `n Oz = Pi + n Z`, as an exact membership criterion. -/
theorem omnific_int_dvd_iff_purelyInfinite_add (n : ℤ) (hn : n ≠ 0)
    (x : OmnificInteger.{u}) :
    omnificIntCast n ∣ x ↔ ∃ j ∈ omnificPurelyInfiniteIdeal, ∃ m : ℤ,
      x = j + omnificIntCast (n * m) := by
  rw [omnific_int_dvd_iff n hn]
  constructor
  · rintro ⟨m, hm⟩
    obtain ⟨j, hj, hx⟩ := omnific_constant_decomposition x
    exact ⟨j, hj, m, by rw [hx, hm]; exact _root_.add_comm _ _⟩
  · rintro ⟨j, hj, m, rfl⟩
    change omnificConstantCoeff j = 0 at hj
    exact ⟨m, by rw [map_add, hj, omnificConstantCoeff_intCast, _root_.zero_add]⟩

/-- Reduction of the actual constant term modulo an ordinary integer. -/
def omnificResidue (n : ℤ) :
    OmnificInteger.{u} →+* ℤ ⧸ Ideal.span ({n} : Set ℤ) :=
  (Ideal.Quotient.mk (Ideal.span {n})).comp omnificConstantCoeff

/-- Every ordinary residue class is represented by an omnific integer constant. -/
theorem omnificResidue_surjective (n : ℤ) : Function.Surjective (omnificResidue.{u} n) :=
  Ideal.Quotient.mk_surjective.comp omnificConstantCoeff_surjective

/-- The kernel of reduction is the principal ideal generated by the actual integer constant. -/
theorem ker_omnificResidue (n : ℤ) (hn : n ≠ 0) :
    RingHom.ker (omnificResidue.{u} n) = Ideal.span {omnificIntCast n} := by
  ext x
  change Ideal.Quotient.mk (Ideal.span {n}) (omnificConstantCoeff x) = 0 ↔ _
  rw [Ideal.Quotient.eq_zero_iff_mem, Ideal.mem_span_singleton, Ideal.mem_span_singleton,
    omnific_int_dvd_iff n hn]

/-- Quotienting the actual omnific ring by a nonzero ordinary modulus gives the ordinary quotient. -/
def omnificQuotientIntEquiv (n : ℤ) (hn : n ≠ 0) :
    OmnificInteger.{u} ⧸ Ideal.span {omnificIntCast n} ≃+* ℤ ⧸ Ideal.span ({n} : Set ℤ) :=
  (Ideal.quotEquivOfEq (ker_omnificResidue n hn).symm).trans
    ((omnificResidue n).quotientKerEquivOfSurjective (omnificResidue_surjective n))

/-- The quotient equivalence sends a class to its constant coefficient modulo `n`. -/
@[simp] theorem omnificQuotientIntEquiv_mk (n : ℤ) (hn : n ≠ 0) (x : OmnificInteger.{u}) :
    omnificQuotientIntEquiv n hn (Ideal.Quotient.mk _ x) =
      Ideal.Quotient.mk (Ideal.span {n}) (omnificConstantCoeff x) := by
  simp only [omnificQuotientIntEquiv, RingEquiv.trans_apply, Ideal.quotEquivOfEq_mk,
    RingHom.quotientKerEquivOfSurjective_apply_mk]
  rfl

/-- The same quotient is the finite cyclic residue ring with modulus the absolute value of `n`. -/
def omnificQuotientZModEquiv (n : ℤ) (hn : n ≠ 0) :
    OmnificInteger.{u} ⧸ Ideal.span {omnificIntCast n} ≃+* ZMod n.natAbs :=
  (omnificQuotientIntEquiv n hn).trans (Int.quotientSpanEquivZMod n)

/-- Exact prime-power divisibility, including the zero-constant case. -/
theorem omnific_prime_pow_dvd_iff (p : ℕ) [hp : Fact p.Prime] (k : ℕ)
    (x : OmnificInteger.{u}) :
    omnificIntCast (p : ℤ) ^ k ∣ x ↔
      omnificConstantCoeff x = 0 ∨ k ≤ padicValInt p (omnificConstantCoeff x) := by
  rw [← map_pow, omnific_int_dvd_iff _ (pow_ne_zero _ (by exact_mod_cast hp.out.ne_zero))]
  exact padicValInt_dvd_iff k _

/-- For nonzero constant term the greatest prime-power divisor exponent is its ordinary p-adic order. -/
theorem omnific_prime_pow_dvd_iff_le (p : ℕ) [Fact p.Prime] (x : OmnificInteger.{u})
    (hx : omnificConstantCoeff x ≠ 0) (k : ℕ) :
    omnificIntCast (p : ℤ) ^ k ∣ x ↔ k ≤ padicValInt p (omnificConstantCoeff x) := by
  rw [omnific_prime_pow_dvd_iff, or_iff_right hx]

/-- The common kernel of all positive powers of one ordinary prime is the purely infinite ideal. -/
theorem omnific_dvd_all_prime_powers_iff (p : ℕ) [Fact p.Prime] (x : OmnificInteger.{u}) :
    (∀ k : ℕ, 0 < k → omnificIntCast (p : ℤ) ^ k ∣ x) ↔
      x ∈ omnificPurelyInfiniteIdeal := by
  change _ ↔ omnificConstantCoeff x = 0
  constructor
  · intro h
    by_contra hx
    have hb := (omnific_prime_pow_dvd_iff_le p x hx _).mp
      (h (padicValInt p (omnificConstantCoeff x) + 1) (Nat.succ_pos _))
    omega
  · intro hx k _
    exact (omnific_prime_pow_dvd_iff p k x).mpr (Or.inl hx)

/-- Divisibility by every positive ordinary integer characterizes the purely infinite ideal. -/
theorem omnific_dvd_all_pos_int_iff (x : OmnificInteger.{u}) :
    (∀ n : ℕ, 0 < n → omnificIntCast (n : ℤ) ∣ x) ↔
      x ∈ omnificPurelyInfiniteIdeal := by
  constructor
  · intro h
    apply (omnific_dvd_all_prime_powers_iff 2 x).mp
    intro k _
    simpa only [Int.natCast_pow, map_pow] using h (2 ^ k) (pow_pos (by decide) k)
  · intro hx n hn
    exact omnific_int_dvd_of_purelyInfinite n (by exact_mod_cast hn.ne') x hx

/-- Literal ideal intersection over all positive ordinary integer moduli. -/
theorem iInf_omnific_int_multiples :
    (⨅ n : {n : ℕ // 0 < n}, Ideal.span {omnificIntCast (n.val : ℤ)}) =
      omnificPurelyInfiniteIdeal.{u} := by
  ext x
  simp only [Ideal.mem_iInf, Ideal.mem_span_singleton, Subtype.forall]
  exact omnific_dvd_all_pos_int_iff x

/-- Literal ideal intersection over the positive powers of an ordinary prime. -/
theorem iInf_omnific_prime_pow_multiples (p : ℕ) [Fact p.Prime] :
    (⨅ k : {k : ℕ // 0 < k}, Ideal.span {omnificIntCast (p : ℤ) ^ k.val}) =
      omnificPurelyInfiniteIdeal.{u} := by
  ext x
  simp only [Ideal.mem_iInf, Ideal.mem_span_singleton, Subtype.forall]
  exact omnific_dvd_all_prime_powers_iff p x

end
end Surreal.Foundations.SignSequence
