#!/usr/bin/env python3
"""Exact tools for prescribed additive-relation minima (standard library only).

All public functions use zero-based set coordinates: A[0]=0, A[1]=1.
Radices may be unordered: the successive minima are twice their sorted list.
The exact short-relation subgroup is generated by carries whose radix <= H.
"""
from __future__ import annotations
from itertools import product
from math import comb, prod
from typing import Iterable, Iterator, Sequence


def validate(radices: Sequence[int], *, ordered: bool = False) -> tuple[int, ...]:
    q = tuple(radices)
    if any(type(x) is not int or x < 2 for x in q):
        raise ValueError('Every radix must be an integer at least 2.')
    if ordered and tuple(sorted(q)) != q:
        raise ValueError('The radices must be sorted when ordered=True.')
    return q


def construct(radices: Sequence[int]) -> tuple[int, ...]:
    q = validate(radices)
    a = [0, 1]
    for x in q:
        a.append(a[-1] * x)
    return tuple(a)


def carry_basis(radices: Sequence[int]) -> tuple[tuple[int, ...], ...]:
    q = validate(radices)
    rows = []
    for j, x in enumerate(q, start=1):
        row = [0] * (len(q) + 2)
        row[0], row[j], row[j + 1] = x - 1, -x, 1
        rows.append(tuple(row))
    return tuple(rows)


def degree(c: Sequence[int]) -> int:
    if sum(c) != 0:
        raise ValueError('Relation degree is defined here only for zero-sum vectors.')
    return sum(max(x, 0) for x in c)


def coordinates(radices: Sequence[int], c: Sequence[int]) -> tuple[int, ...]:
    a = construct(radices)
    if len(c) != len(a) or any(type(x) is not int for x in c):
        raise ValueError('Expected an integer vector of length len(radices)+2.')
    if sum(c) or sum(x*y for x, y in zip(c, a)):
        raise ValueError('The input vector is not in the coefficient lattice.')
    v = carry_basis(radices)
    remainder = list(c)
    coeff = [0] * len(v)
    for j in range(len(v) - 1, -1, -1):
        coeff[j] = remainder[j + 2]
        remainder = [x - coeff[j]*y for x, y in zip(remainder, v[j])]
    if any(remainder):
        raise AssertionError('Triangular elimination left a nonzero remainder.')
    return tuple(coeff)


def normal_digits(radices: Sequence[int], n: int) -> tuple[tuple[int, ...], int]:
    q = validate(radices)
    if type(n) is not int or n < 0:
        raise ValueError('n must be a nonnegative integer.')
    digits = []
    for x in q:
        n, digit = divmod(n, x)
        digits.append(digit)
    return tuple(digits), n


def min_summands(radices: Sequence[int], n: int) -> int:
    digits, top = normal_digits(radices, n)
    return sum(digits) + top


def canonical_representation(radices: Sequence[int], h: int, n: int) -> tuple[int, ...] | None:
    if type(h) is not int or h < 0:
        raise ValueError('h must be a nonnegative integer.')
    digits, top = normal_digits(radices, n)
    cost = sum(digits) + top
    if cost > h:
        return None
    return (h-cost, *digits, top)


def numerator(radices: Sequence[int]) -> tuple[int, ...]:
    """Multiply digit polynomials by exact sliding-window convolution."""
    p = [1]
    for q in validate(radices):
        result = []
        window = 0
        for i in range(len(p) + q - 1):
            if i < len(p):
                window += p[i]
            if 0 <= i - q < len(p):
                window -= p[i - q]
            result.append(window)
        p = result
    return tuple(p)


def sumset_size(radices: Sequence[int], h: int) -> int:
    if type(h) is not int or h < 0:
        raise ValueError('h must be a nonnegative integer.')
    return sum(c * (h-i+1) for i, c in enumerate(numerator(radices)) if i <= h)


def binomial_size(radices: Sequence[int], h: int) -> int:
    q = validate(radices)
    if type(h) is not int or h < 0:
        raise ValueError('h must be a nonnegative integer.')
    r = len(q)
    result = 0
    for selected in product((0, 1), repeat=r):
        shift = sum(x*flag for x, flag in zip(q, selected))
        if h >= shift:
            result += (-1)**sum(selected) * comb(h-shift+r+1, r+1)
    return result


def eventual_size(radices: Sequence[int], h: int) -> int:
    """Evaluate the affine polynomial (not the sumset size before its onset)."""
    if type(h) is not int:
        raise ValueError('h must be an integer.')
    q = validate(radices)
    p, d = prod(q), sum(x-1 for x in q)
    return p*(h+1) - p*d//2


def compositions(total: int, parts: int) -> Iterator[tuple[int, ...]]:
    if total < 0 or parts < 1:
        raise ValueError('total must be nonnegative and parts positive.')
    if parts == 1:
        yield (total,)
    else:
        for first in range(total + 1):
            for tail in compositions(total-first, parts-1):
                yield (first, *tail)


def relation_generators_at(a: Sequence[int], h: int) -> tuple[list[tuple[int, ...]], int, int]:
    """Independently enumerate all h-multisets, grouping by their integer sum.

    Differences to one representative per sum span exactly the vectors of
    relation degree <=h: pad both positive/negative parts by zeros. This does
    not call the construction's predicted basis or any formula for its ranks.
    Returns (generators, number of multisets, number of distinct sums).
    """
    if not a or a[0] != 0:
        raise ValueError('The set must contain 0 as its first coordinate.')
    buckets: dict[int, tuple[int, ...]] = {}
    rows: list[tuple[int, ...]] = []
    count = 0
    for c in compositions(h, len(a)):
        count += 1
        n = sum(x*y for x, y in zip(c, a))
        if n not in buckets:
            buckets[n] = c
        else:
            rows.append(tuple(x-y for x, y in zip(c, buckets[n])))
    return rows, count, len(buckets)


def exact_rank(rows: Iterable[Sequence[int]]) -> int:
    """Fraction-free Gaussian row reduction, with gcd normalization."""
    from math import gcd
    pivots: dict[int, list[int]] = {}
    for raw in rows:
        row = list(raw)
        for pivot, basis in sorted(pivots.items()):
            if row[pivot]:
                factor, denom = row[pivot], basis[pivot]
                row = [denom*x-factor*y for x, y in zip(row, basis)]
                g = 0
                for x in row:
                    g = gcd(g, x)
                if g > 1:
                    row = [x//g for x in row]
        if any(row):
            pivot = next(i for i, x in enumerate(row) if x)
            if row[pivot] < 0:
                row = [-x for x in row]
            pivots[pivot] = row
    return len(pivots)


def short_vectors(radices: Sequence[int], h: int) -> tuple[tuple[int, ...], ...]:
    """Enumerate the degree <=h ball using the proved carry-coordinate bounds.

    This is an exact enumerator, but is not used as independent evidence for
    the coefficient bound. verify.py cross-checks it against multiset pairs.
    """
    q = validate(radices)
    if type(h) is not int or h < 0:
        raise ValueError('h must be a nonnegative integer.')
    basis = carry_basis(q)
    result = []
    for z in product(*(range(-(h//x), h//x+1) for x in q)):
        c = tuple(sum(zj*v[i] for zj,v in zip(z,basis)) for i in range(len(q)+2))
        if degree(c) <= h:
            result.append(c)
    return tuple(result)
