import Mathlib.NumberTheory.PellMatiyasevic

/-!
# Pell sequences shared by the six articles

The articles write `ψ_a(n)` and `χ_a(n)` for the solutions of `x² - (a²-1) y² = 1`
generated by `χ_a(0)=1, χ_a(1)=a, χ_a(n+2)=2a χ_a(n+1)-χ_a(n)` and
`ψ_a(0)=0, ψ_a(1)=1, ψ_a(n+2)=2a ψ_a(n+1)-ψ_a(n)`.  These are Mathlib's `Pell.xn` and
`Pell.yn` (for `1 < a`).  This file records the elementary properties that the
1976, 1978 and 1982 papers quote without proof.
-/

namespace Diophantine

open Pell

variable {a : ℕ} (a1 : 1 < a)

/-- `ψ_a(n)` (second Pell coordinate). -/
abbrev ψ (n : ℕ) : ℕ := yn a1 n

/-- `χ_a(n)` (first Pell coordinate). -/
abbrev χ (n : ℕ) : ℕ := xn a1 n

theorem ψ_two : ψ a1 2 = 2 * a := by
  simp [ψ, yn_succ]; ring

/-- Lemma 2.1 of JSWW 1976 (= Lemma 2.19 of Jones 1982), upper half:
`ψ_a(n+1) ≤ (2a)^n`. -/
theorem ψ_succ_le_pow (n : ℕ) : ψ a1 (n + 1) ≤ (2 * a) ^ n := by
  have key : ∀ n, ψ a1 (n + 1) ≤ (2 * a) ^ n ∧ ψ a1 (n + 2) ≤ (2 * a) ^ (n + 1) := by
    intro n
    induction n with
    | zero => exact ⟨by simp [ψ], by rw [ψ_two]; simp⟩
    | succ n ih =>
      refine ⟨ih.2, ?_⟩
      have h : yn a1 (n + 3) + yn a1 (n + 1) = 2 * a * yn a1 (n + 2) := yn_succ_succ a1 (n + 1)
      have : yn a1 (n + 3) ≤ 2 * a * yn a1 (n + 2) := by omega
      calc ψ a1 (n + 3) ≤ 2 * a * yn a1 (n + 2) := this
        _ ≤ 2 * a * (2 * a) ^ (n + 1) := Nat.mul_le_mul_left _ ih.2
        _ = (2 * a) ^ (n + 2) := by ring
  exact (key n).1

/-- Lemma 2.1 of JSWW 1976, lower half: `(2a-1)^n ≤ ψ_a(n+1)`. -/
theorem pow_le_ψ_succ (n : ℕ) : (2 * a - 1) ^ n ≤ ψ a1 (n + 1) := by
  have key : ∀ n, (2 * a - 1) ^ n ≤ ψ a1 (n + 1) ∧ (2 * a - 1) ^ (n + 1) ≤ ψ a1 (n + 2) := by
    intro n
    induction n with
    | zero => exact ⟨by simp [ψ], by rw [ψ_two]; simp⟩
    | succ n ih =>
      refine ⟨ih.2, ?_⟩
      have h : yn a1 (n + 3) + yn a1 (n + 1) = 2 * a * yn a1 (n + 2) := yn_succ_succ a1 (n + 1)
      have mono : yn a1 (n + 1) ≤ yn a1 (n + 2) := (strictMono_y a1).monotone (by omega)
      have step : (2 * a - 1) * yn a1 (n + 2) ≤ yn a1 (n + 3) := by
        have h1 : 1 ≤ a := a1.le
        have : (2 * a - 1) * yn a1 (n + 2) + yn a1 (n + 2) = 2 * a * yn a1 (n + 2) := by
          have : 2 * a - 1 + 1 = 2 * a := by omega
          calc (2 * a - 1) * yn a1 (n + 2) + yn a1 (n + 2) = (2 * a - 1 + 1) * yn a1 (n + 2) := by ring
            _ = 2 * a * yn a1 (n + 2) := by rw [this]
        omega
      calc (2 * a - 1) ^ (n + 2) = (2 * a - 1) * (2 * a - 1) ^ (n + 1) := by ring
        _ ≤ (2 * a - 1) * yn a1 (n + 2) := Nat.mul_le_mul_left _ ih.2
        _ ≤ ψ a1 (n + 3) := step
  exact (key n).1

/-- Lemma 2.2 of JSWW 1976 (= Lemma 2.20 of Jones 1982): `ψ_a(n) ≡ n (mod a-1)`.
This is Mathlib's `Pell.yn_modEq_a_sub_one`. -/
theorem ψ_modEq (n : ℕ) : ψ a1 n ≡ n [MOD a - 1] := yn_modEq_a_sub_one a1 n

/-- The Pell equation itself, `χ_a(n)² = (a²-1) ψ_a(n)² + 1`, in additive form. -/
theorem χ_sq (n : ℕ) : χ a1 n * χ a1 n = (a * a - 1) * ψ a1 n * ψ a1 n + 1 := by
  show xn a1 n * xn a1 n = (a * a - 1) * yn a1 n * yn a1 n + 1
  have h : xn a1 n * xn a1 n - (a * a - 1) * yn a1 n * yn a1 n = 1 := pell_eq a1 n
  have : (a * a - 1) * yn a1 n * yn a1 n < xn a1 n * xn a1 n := Nat.sub_ne_zero_iff_lt.1 (by omega)
  omega

/-- `χ_a(n) > (a-1) ψ_a(n)`, from the Pell equation. -/
theorem χ_gt (n : ℕ) : (a - 1) * ψ a1 n < χ a1 n := by
  have h := χ_sq a1 n
  have h1 : (a - 1) * (a - 1) ≤ a * a - 1 := by
    have : 1 ≤ a := a1.le
    have : (a - 1) * (a - 1) + 1 ≤ a * a := by
      have ha : a = (a - 1) + 1 := by omega
      calc (a - 1) * (a - 1) + 1 ≤ (a - 1) * (a - 1) + 2 * (a - 1) + 1 := by omega
        _ = ((a - 1) + 1) * ((a - 1) + 1) := by ring
        _ = a * a := by rw [← ha]
    omega
  have : ((a - 1) * ψ a1 n) * ((a - 1) * ψ a1 n) < χ a1 n * χ a1 n := by
    calc ((a - 1) * ψ a1 n) * ((a - 1) * ψ a1 n) = ((a - 1) * (a - 1)) * ψ a1 n * ψ a1 n := by ring
      _ ≤ (a * a - 1) * ψ a1 n * ψ a1 n := by gcongr
      _ < (a * a - 1) * ψ a1 n * ψ a1 n + 1 := Nat.lt_succ_self _
      _ = χ a1 n * χ a1 n := h.symm
  exact Nat.mul_self_lt_mul_self_iff.1 this

/-- Lemma 2.4 of JSWW 1976, congruence part: for `0 < p ≤ a`,
`χ_a(n) ≡ p^n + ψ_a(n)(a-p)  (mod 2ap - p² - 1)`.  From Mathlib's `Pell.x_sub_y_dvd_pow`. -/
theorem χ_modEq_pow {p : ℕ} (hp : 0 < p) (hpa : p ≤ a) (n : ℕ) :
    χ a1 n ≡ p ^ n + ψ a1 n * (a - p) [MOD 2 * a * p - p * p - 1] := by
  have hmod : p * p + 1 ≤ 2 * a * p := by nlinarith
  have hdvd := x_sub_y_dvd_pow a1 p n
  rw [Nat.ModEq.comm, Nat.modEq_iff_dvd]
  have hcast : ((2 * a * p - p * p - 1 : ℕ) : ℤ) = 2 * a * p - p * p - 1 := by
    have : p * p ≤ 2 * a * p - 1 := by omega
    push_cast [Nat.sub_sub, Nat.cast_sub hmod]
    ring
  rw [hcast]
  have hsub : ((a - p : ℕ) : ℤ) = (a : ℤ) - p := Nat.cast_sub hpa
  have : ((χ a1 n : ℕ) : ℤ) - ((p ^ n + ψ a1 n * (a - p) : ℕ) : ℤ) =
      -(yz a1 n * (a - p) + ↑(p ^ n) - xz a1 n) := by
    simp only [χ, ψ, xz, yz]
    push_cast [hsub]
    ring
  rw [this]
  exact (dvd_neg).2 hdvd

/-- Lemma 2.4 of JSWW 1976, inequality part: when `0 < p` and `p^n < a`,
`p^n + ψ_a(n)(a-p) ≤ χ_a(n)`. -/
theorem pow_add_ψ_le_χ {p n : ℕ} (hp : 0 < p) (hpn : p ^ n < a) :
    p ^ n + ψ a1 n * (a - p) ≤ χ a1 n := by
  rcases n with _ | n
  · simp [χ, ψ]
  have hpa : p ≤ a := (Nat.le_self_pow (Nat.succ_ne_zero n) p).trans hpn.le
  rcases n with _ | n
  · simp [χ, ψ]; omega
  show p ^ (n + 2) + ψ a1 (n + 2) * (a - p) ≤ χ a1 (n + 2)
  have hpn : p ^ (n + 2) < a := hpn
  -- n+2 ≥ 2: use χ > (a-1) ψ and ψ(p-1) ≥ p^(n+2)
  have hχ := χ_gt a1 (n + 2)
  rcases Nat.lt_or_ge p 2 with hp1 | hp2
  · -- p = 1
    have : p = 1 := by omega
    subst this
    simp only [one_pow]
    have : ψ a1 (n + 2) * (a - 1) = (a - 1) * ψ a1 (n + 2) := by ring
    omega
  · -- p ≥ 2: (2a-1)^(n+1) ≤ ψ(n+2) and (2a-1)^(n+1) (p-1) ≥ p^(n+2)
    have hψ := pow_le_ψ_succ a1 (n + 1)
    have hpow : p ^ (n + 2) ≤ (2 * a - 1) ^ (n + 1) * (p - 1) := by
      have hp_le : p ≤ p ^ (n + 2) := Nat.le_self_pow (by omega) p
      have h2p : 2 * p ≤ 2 * a - 1 := by omega
      calc p ^ (n + 2) = p ^ (n + 1) * p := by ring
        _ ≤ (2 * p) ^ (n + 1) * (p - 1) := by
          have hp' : p ≤ 2 ^ (n + 1) * (p - 1) := by
            have h2 : 2 ≤ 2 ^ (n + 1) := by
              calc 2 = 2 ^ 1 := by norm_num
                _ ≤ 2 ^ (n + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
            obtain ⟨q, hq⟩ : ∃ q, p = q + 2 := ⟨p - 2, by omega⟩
            rw [hq, show q + 2 - 1 = q + 1 by omega]
            nlinarith
          calc p ^ (n + 1) * p ≤ p ^ (n + 1) * (2 ^ (n + 1) * (p - 1)) := Nat.mul_le_mul_left _ hp'
            _ = (2 * p) ^ (n + 1) * (p - 1) := by rw [mul_pow]; ring
        _ ≤ (2 * a - 1) ^ (n + 1) * (p - 1) := by gcongr
    have hsplit : (a - 1) * ψ a1 (n + 2) = ψ a1 (n + 2) * (a - p) + ψ a1 (n + 2) * (p - 1) := by
      have : a - 1 = (a - p) + (p - 1) := by omega
      rw [this]; ring
    have : p ^ (n + 2) ≤ ψ a1 (n + 2) * (p - 1) := by
      calc p ^ (n + 2) ≤ (2 * a - 1) ^ (n + 1) * (p - 1) := hpow
        _ ≤ ψ a1 (n + 2) * (p - 1) := Nat.mul_le_mul_right _ hψ
    omega

end Diophantine
