#!/usr/bin/env python3
"""Offline, nondestructive deterministic artifact build (standard library only)."""
import argparse
from fractions import Fraction
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from exact import radial_coefficients, coefficient_transfer, partition_counts, nonnegative_cli
from inverse import inverse_polynomials, records


def fraction_tex(q):
    if q.denominator == 1:
        return str(q.numerator)
    sign = '-' if q < 0 else ''
    return sign+r'\frac{'+str(abs(q.numerator))+'}{'+str(q.denominator)+'}'


def field_tex(q):
    parts = []
    if q.a:
        parts.append(fraction_tex(q.a))
    if q.b:
        coefficient = '' if abs(q.b) == 1 else fraction_tex(abs(q.b))
        term = coefficient+r'\sqrt{5}'
        if parts:
            parts.append((' - ' if q.b < 0 else ' + ')+term)
        else:
            parts.append(('-' if q.b < 0 else '')+term)
    return ''.join(parts) or '0'


def inverse_tex(poly):
    result = ''
    for powers, coefficient in sorted(poly.items(), reverse=True):
        factors = []
        if powers[0]:
            factors.append('w' if powers[0] == 1 else 'w^{'+str(powers[0])+'}')
        for j, power in enumerate(powers[1:], 1):
            if power:
                factors.append(r'\alpha_{'+str(j)+'}'+('' if power == 1 else '^{'+str(power)+'}'))
        magnitude = abs(coefficient)
        body = ('' if factors and magnitude == 1 else fraction_tex(magnitude))+''.join(factors)
        result += (' - ' if coefficient < 0 else (' + ' if result else ''))+body
    return result or '0'


def write_new(path, data):
    with path.open('x', encoding='utf-8') as handle:
        handle.write(data)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', required=True, type=Path, help='new or empty output directory')
    parser.add_argument('--order', default=4, type=nonnegative_cli)
    parser.add_argument('--max-n', default=10000, type=nonnegative_cli)
    args = parser.parse_args()
    source = Path(__file__).resolve().parent
    output = args.out.resolve()
    if output == source or source in output.parents:
        parser.error('output must be outside the source directory')
    if output.exists() and (not output.is_dir() or any(output.iterdir())):
        parser.error('output must be a new or empty directory; nothing is overwritten')
    commands = [[sys.executable, '-B', str(source/'selftest.py')],
                [sys.executable, '-B', '-O', str(source/'selftest.py')]]
    tests = [subprocess.run(cmd, check=True, capture_output=True, text=True).stdout for cmd in commands]
    if tests[0] != tests[1]:
        raise RuntimeError('normal and -O test outputs differ')
    cs = radial_coefficients(args.order)
    ds = coefficient_transfer(cs)
    ps = inverse_polynomials(args.order)
    counts = partition_counts(args.max_n)
    selected = sorted({n for n in (0,1,2,3,4,5,6,7,8,9,10,20,25,50,100,200,400,1000,2000,5000,10000,args.max_n) if n <= args.max_n})
    payload = {'schema': 1, 'radial_order': args.order,
               'field_basis': ['1', 'sqrt(5)'], 'A': 'pi^2/30',
               'radial': [{'j': j, **c.record()} for j,c in enumerate(cs)],
               'coefficient_polynomials_in_sqrt_A': [
                   {'r': r, 'terms': {str(k): v.record() for k,v in sorted(poly.items())}}
                   for r, poly in enumerate(ds)],
               'inverse_variables': ['w']+['alpha_'+str(j) for j in range(1,args.order+1)],
               'inverse_polynomials': records(ps),
               'counts_max_n': args.max_n,
               'selected_exact_counts': [{'n': n, 'a_n': str(counts[n])} for n in selected],
               'count_data_origin': 'exact integer finite-product DP; no external data file'}
    output.mkdir(parents=True, exist_ok=True)
    write_new(output/'exact_tables.json', json.dumps(payload, indent=2, sort_keys=True)+'\n')
    write_new(output/'radial_coefficients.tex', '% Generated by code/build.py; exact rational arithmetic.\n'+
        '\\begin{align*}\n'+' \\\\\n'.join('c_{'+str(j)+'} &= '+field_tex(c) for j,c in enumerate(cs))+
        '\n\\end{align*}\n')
    write_new(output/'inverse_polynomials.tex', '% Generated formal inverse polynomials.\n'+
        '\\begin{align*}\n'+' \\\\\n'.join('P_{'+str(j)+'}(w) &= '+inverse_tex(p) for j,p in enumerate(ps,1))+
        '\n\\end{align*}\n')
    write_new(output/'exact_counts.tex', '% Exact finite-product counts.\n\\begin{tabular}{r r}\n$n$ & $a(n)$ \\\\\n\\hline\n'+
        '\n'.join(str(n)+' & '+str(counts[n])+r' \\' for n in selected)+
        '\n\\end{tabular}\n')
    write_new(output/'selftest.txt', 'normal: '+tests[0]+'python -O: '+tests[1]+'normal and -O outputs are byte-identical\n')
    manifests = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(output.iterdir()) if p.is_file()}
    write_new(output/'SHA256SUMS.json', json.dumps(manifests, indent=2, sort_keys=True)+'\n')
    print('Built exact tables and verified tests in '+str(args.out))


if __name__ == '__main__':
    main()
