import BoundedPAConsistency.Basic
import BoundedPAConsistency.CodedHierarchy
import BoundedPAConsistency.FixedLevelPAAxioms
import BoundedPAConsistency.FixedLevelTruthTarski
import BoundedPAConsistency.Internal
import BoundedPAConsistency.ModelCodedInductionAxiomAudit
import BoundedPAConsistency.ModelFormulaInduction
import BoundedPAConsistency.OrientedHierarchy
import BoundedPAConsistency.PrimitiveRecursiveTruthCertificateAudit
import BoundedPAConsistency.QuantifierFreeTarski
import BoundedPAConsistency.QuantifierFreeTransport
import BoundedPAConsistency.QuantifierFreeSoundness
import BoundedPAConsistency.QuantifierFreeTruth
import BoundedPAConsistency.QuantifierFreePAAxioms
import BoundedPAConsistency.RestrictedConsistency
import BoundedPAConsistency.TermEvaluationTransport
import BoundedPAConsistency.TruthCertificateProofCompilerAudit
import BoundedPAConsistency.UniformInternalProvability
import BoundedPAConsistency.UniformInternalProvabilityTheorem
import BoundedPAConsistency.UniformProofPackage

/-!
# Kernel audit for bounded PA consistency, phase one

The checks below keep the public metatheoretic surface visible and ask Lean to
report the assumptions of the key hierarchy, erasure, cofinality, collapse,
and standard-model consistency theorems.
-/

open LeanProofs.BoundedPAConsistency

#check sigmaRank
#check piRank
#check quantifierGroups
#check hierarchyRanks_rename
#check hierarchyRanks_subst
#check quantifierGroups_mixed_branches
#check ProvTree
#check eraseProvTree
#check provTree_complete
#check proofOccurrenceRank
#check ProofAllBounded
#check RestrictedProv
#check RestrictedBProv
#check restrictedProv_erase
#check restrictedBProv_erase
#check restrictedProv_cofinal
#check restrictedBProv_cofinal
#check conclusionRestrictedProv_bot_iff
#check conclusionRestrictedBProv_bot_iff
#check restrictedPA_consistent_standard
#check LeanProofs.BoundedPAConsistency.Internal.inductionAtHierarchy
#check LeanProofs.BoundedPAConsistency.Internal.inductionInPeanoModel
#check LeanProofs.BoundedPAConsistency.ModelCodedInductionAxiom.indBody_mem_peano_of_shift_fixed
#check LeanProofs.BoundedPAConsistency.ModelCodedInductionAxiom.paInductionProofOfShiftFixed
#check LeanProofs.BoundedPAConsistency.ModelCodedInductionAxiom.paInductionOfShiftFixed
#check LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.TruthCertificateFields
#check LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.TruthCertificateStep.compile
#check LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.PAInductionKernel.compile
#check LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.PAInductiveTruthCertificateStep.compile_isPAProof
#check LeanProofs.BoundedPAConsistency.PrimitiveRecursiveTruthCertificate.PrimitiveRecursivePackage
#check LeanProofs.BoundedPAConsistency.PrimitiveRecursiveTruthCertificate.primitiveRecursivePackage_definable
#check LeanProofs.BoundedPAConsistency.PrimitiveRecursiveTruthCertificate.paRestrictedConsistencyProofSelectorIn_of_typedPrimitiveRecursivePackage
#check LeanProofs.BoundedPAConsistency.ModelFormulaInduction.uformula_inductionInPeanoModel
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValues
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue.defined
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValues.defined
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_bvar_zero_seqCons
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_add
#check LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_mul
#check LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termShift_of_isFreeTail
#check LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termSubst_of_isSubstitutionBound
#check LeanProofs.BoundedPAConsistency.TermEvaluationTransport.exists_isSubstitutionEnvironment
#check LeanProofs.BoundedPAConsistency.TermEvaluationTransport.exists_isFreeTail
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.quantifierGroupsCode
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.QuantifierBoundedCode
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_neg
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_shift
#check LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_subst
#check LeanProofs.BoundedPAConsistency.OrientedHierarchy.IsSigmaCode
#check LeanProofs.BoundedPAConsistency.OrientedHierarchy.IsPiCode
#check LeanProofs.BoundedPAConsistency.OrientedHierarchy.quantifierBoundedCode_iff_sigma_or_pi
#check LeanProofs.BoundedPAConsistency.OrientedHierarchy.rankCode_balanced
#check LeanProofs.BoundedPAConsistency.OrientedHierarchy.QuantifierBoundedCode.toSigmaSucc
#check LeanProofs.BoundedPAConsistency.OrientedHierarchy.isSigmaCode_neg_iff
#check LeanProofs.BoundedPAConsistency.OrientedHierarchy.isPiCode_neg_iff
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTruth.qfValue
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTruth.qfValue_isBit
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.quantifierGroupsCode_eq_zero_iff
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_and_iff
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_eq_atom_iff
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTransport.qfValue_neg
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTransport.qfValue_shift_of_isFreeTail
#check LeanProofs.BoundedPAConsistency.QuantifierFreeTransport.qfValue_subst_of_isSubstitutionBound
#check LeanProofs.BoundedPAConsistency.QuantifierFreeSoundness.restrictedDerivation_qf_sound
#check LeanProofs.BoundedPAConsistency.QuantifierFreeSoundness.restrictedConsistent_zero_of_qf_axioms
#check LeanProofs.BoundedPAConsistency.QuantifierFreePAAxioms.qfTrue_of_mem_pa_delta1Class
#check LeanProofs.BoundedPAConsistency.QuantifierFreePAAxioms.restrictedConsistent_pa_zero
#check LeanProofs.BoundedPAConsistency.QuantifierFreePAAxioms.pa_proves_restrictedConsistency_zero
#check LeanProofs.BoundedPAConsistency.FixedLevelPAAxioms.pa_proves_restrictedConsistency
#check LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.sigmaTrue_and_iff
#check LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.piTrue_all_iff
#check LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.sigmaTrue_succ_all_iff
#check LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.piTrue_succ_exs_iff
#check LeanProofs.BoundedPAConsistency.RestrictedDerivation
#check LeanProofs.BoundedPAConsistency.RestrictedProof
#check LeanProofs.BoundedPAConsistency.RestrictedConsistent
#check LeanProofs.BoundedPAConsistency.paRestrictedConsistencySentence
#check LeanProofs.BoundedPAConsistency.eval_paRestrictedConsistencySentence_iff
#check LeanProofs.BoundedPAConsistency.UniformInternalProvability.paUniformRestrictedConsistencyProvabilitySentence
#check LeanProofs.BoundedPAConsistency.UniformInternalProvability.eval_paRestrictedConsistencyTemplate_instance_iff
#check LeanProofs.BoundedPAConsistency.UniformInternalProvability.pa_proves_paRestrictedConsistencyTemplate_instance
#check LeanProofs.BoundedPAConsistency.UniformInternalProvability.provable_paRestrictedConsistency_standard_point
#check LeanProofs.BoundedPAConsistency.UniformInternalProvability.pa_proves_uniformRestrictedConsistencyProvability_iff_selectorInAllModels
#check LeanProofs.BoundedPAConsistency.UniformProofPackage.HasPARestrictedConsistencyProofPackage
#check LeanProofs.BoundedPAConsistency.UniformProofPackage.hasPARestrictedConsistencyProofPackage_definable
#check LeanProofs.BoundedPAConsistency.UniformProofPackage.paRestrictedConsistencyProofSelectorIn_of_package

#print axioms hierarchyRanks_rename
#print axioms hierarchyRanks_subst
#print axioms provTree_complete
#print axioms restrictedBProv_erase
#print axioms restrictedBProv_cofinal
#print axioms conclusionRestrictedBProv_bot_iff
#print axioms restrictedPA_consistent_standard
#print axioms LeanProofs.BoundedPAConsistency.Internal.inductionAtHierarchy
#print axioms LeanProofs.BoundedPAConsistency.Internal.inductionInPeanoModel
#print axioms LeanProofs.BoundedPAConsistency.ModelCodedInductionAxiom.indBody_mem_peano_of_shift_fixed
#print axioms LeanProofs.BoundedPAConsistency.ModelCodedInductionAxiom.paInductionProofOfShiftFixed
#print axioms LeanProofs.BoundedPAConsistency.ModelCodedInductionAxiom.paInductionOfShiftFixed
#print axioms LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.TruthCertificateFields.intro
#print axioms LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.TruthCertificateStep.compile
#print axioms LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.PAInductionKernel.compile
#print axioms LeanProofs.BoundedPAConsistency.TruthCertificateProofCompiler.PAInductiveTruthCertificateStep.compile_isPAProof
#print axioms LeanProofs.BoundedPAConsistency.PrimitiveRecursiveTruthCertificate.primitiveRecursivePackage_definable
#print axioms LeanProofs.BoundedPAConsistency.PrimitiveRecursiveTruthCertificate.paRestrictedConsistencyProofSelectorIn_of_typedPrimitiveRecursivePackage
#print axioms LeanProofs.BoundedPAConsistency.ModelFormulaInduction.uformula_inductionInPeanoModel
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue.defined
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValues.defined
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_bvar_zero_seqCons
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_add
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluation.termValue_mul
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termShift_of_isFreeTail
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluationTransport.termValue_termSubst_of_isSubstitutionBound
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluationTransport.exists_isSubstitutionEnvironment
#print axioms LeanProofs.BoundedPAConsistency.TermEvaluationTransport.exists_isFreeTail
#print axioms LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_neg
#print axioms LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_shift
#print axioms LeanProofs.BoundedPAConsistency.CodedHierarchy.rankPair_subst
#print axioms LeanProofs.BoundedPAConsistency.OrientedHierarchy.quantifierBoundedCode_iff_sigma_or_pi
#print axioms LeanProofs.BoundedPAConsistency.OrientedHierarchy.rankCode_balanced
#print axioms LeanProofs.BoundedPAConsistency.OrientedHierarchy.QuantifierBoundedCode.toSigmaSucc
#print axioms LeanProofs.BoundedPAConsistency.OrientedHierarchy.isSigmaCode_neg_iff
#print axioms LeanProofs.BoundedPAConsistency.OrientedHierarchy.isPiCode_neg_iff
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTruth.qfValue_isBit
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.quantifierGroupsCode_eq_zero_iff
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_and_iff
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTarski.qfTrue_eq_atom_iff
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTransport.qfValue_neg
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTransport.qfValue_shift_of_isFreeTail
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeTransport.qfValue_subst_of_isSubstitutionBound
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeSoundness.restrictedDerivation_qf_sound
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreeSoundness.restrictedConsistent_zero_of_qf_axioms
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreePAAxioms.qfTrue_of_mem_pa_delta1Class
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreePAAxioms.restrictedConsistent_pa_zero
#print axioms LeanProofs.BoundedPAConsistency.QuantifierFreePAAxioms.pa_proves_restrictedConsistency_zero
#print axioms LeanProofs.BoundedPAConsistency.FixedLevelPAAxioms.pa_proves_restrictedConsistency
#print axioms LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.sigmaTrue_and_iff
#print axioms LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.piTrue_all_iff
#print axioms LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.sigmaTrue_succ_all_iff
#print axioms LeanProofs.BoundedPAConsistency.FixedLevelTruthTarski.piTrue_succ_exs_iff
#print axioms LeanProofs.BoundedPAConsistency.RestrictedDerivation.defined
#print axioms LeanProofs.BoundedPAConsistency.RestrictedProof.defined
#print axioms LeanProofs.BoundedPAConsistency.eval_paRestrictedConsistencySentence_iff
#print axioms LeanProofs.BoundedPAConsistency.UniformInternalProvability.eval_paRestrictedConsistencyTemplate_instance_iff
#print axioms LeanProofs.BoundedPAConsistency.UniformInternalProvability.pa_proves_paRestrictedConsistencyTemplate_instance
#print axioms LeanProofs.BoundedPAConsistency.UniformInternalProvability.provable_paRestrictedConsistency_standard_point
#print axioms LeanProofs.BoundedPAConsistency.UniformInternalProvability.pa_proves_uniformRestrictedConsistencyProvability_iff_selectorInAllModels
#print axioms LeanProofs.BoundedPAConsistency.UniformProofPackage.hasPARestrictedConsistencyProofPackage_definable
#print axioms LeanProofs.BoundedPAConsistency.UniformProofPackage.paRestrictedConsistencyProofSelectorIn_of_package

/-! ## The uniform object theorem

The model-internal selector is constructed, so the literal sentence
`PA ⊢ ∀ n, Prov_PA(⌜Con_n(PA)⌝)` is an unconditional theorem.  Its axiom
listing is the trust boundary of the whole development. -/

#check @LeanProofs.BoundedPAConsistency.UniformInternalProvabilityTheorem.paRestrictedConsistencyProofSelectorIn_compiled
#check LeanProofs.BoundedPAConsistency.UniformInternalProvabilityTheorem.paRestrictedConsistencyProofSelectorInAllModels_compiled
#check LeanProofs.BoundedPAConsistency.UniformInternalProvabilityTheorem.pa_proves_uniformRestrictedConsistencyProvability

#print axioms LeanProofs.BoundedPAConsistency.UniformInternalProvabilityTheorem.paRestrictedConsistencyProofSelectorInAllModels_compiled
#print axioms LeanProofs.BoundedPAConsistency.UniformInternalProvabilityTheorem.pa_proves_uniformRestrictedConsistencyProvability
