#!/usr/bin/env python3
"""Create the author-facing TeX fragment from checked JSON, no recomputation."""
import json
from pathlib import Path
import mpmath as mp
P=Path(__file__).resolve().parent
r=json.loads((P/'verification_results.json').read_text())
mp.mp.dps=80

def num(s,d=13):
    out=mp.nstr(mp.mpf(s),d,min_fixed=-4,max_fixed=5)
    if 'e' in out:
        a,b=out.split('e');return a+r'\times10^{'+str(int(b))+'}'
    return out

out=[r'''% Generated by render_validation_tables.py from verification_results.json.
% Numerical observations only; not an interval certificate.
Independent code uses the integer triangle through $n=1000$, with prefix sums
in each row, and rational formal division of the stated generating function
through $n=250$. All coefficients agree exactly. The freshly retrieved OEIS
b-file contains indices $1\le n\le200$; all 200 counts agree exactly.
The script uses explicit exception-based checks, not Python \texttt{assert}
statements. The source manifest records retrieval and SHA-256 hashes.

For $r_n=b_n-kh^n$, direct subtraction requires precision growing linearly
with $n$. The table uses a scaled positive Laplace integral and compares it
against exact counts with sufficiently increased working precision. The
reported discrepancies are numerical observations, not certified errors.
The first row uses the normalization $b_0=1/2$.
\begin{center}
\begin{tabular}{rrr}
\toprule
$n$ & $r_n$ from positive integral & Relative discrepancy \\
\midrule''']
for row in r['spectral_moments']:
    if row['n'] in [0,1,4,100,1000]:
        out.append(str(row['n'])+' & $'+num(row['residual'])+'$ & $'+num(row['relative_difference_integral_vs_exact'],3)+r'$ \\')
out.append(r'''\bottomrule
\end{tabular}
\end{center}
The total continuous mass is numerically
$0.316177736956408984232149966021$, agreeing with $1-2k$.
Independent direct $t$-quadratures check the first few moments; 65- and
90-digit scaled quadratures agree to over 55 relative digits in the
reported precision-stability tests. These are consistency checks only.

Let $R_n=2(n+1)\log^2(n+1)r_n$, and let $P_K$ be the logarithmic polynomial
inside the square brackets truncated after $L^{-K}$. The following values
are empirical evaluations of the exact positive integral and those
polynomials. A fixed-order asymptotic expansion does not promise monotone
improvement as more terms are added at modest $n$.
\begin{center}
\begin{tabular}{rrrr}
\toprule
$n$ & $R_n$ & $P_3$ & $P_6$ \\
\midrule''')
for row in r['inverse_log_expansion']:
    n=int(row['n'])
    if n in [1000,10**6,10**12,10**24,10**96]:
        ns=str(n) if n==1000 else '$10^{'+str(len(row['n'])-1)+'}$'
        out.append(ns+' & $'+num(row['normalized_2Nlog2N_residual'],12)+'$ & $'+num(row['truncations'][3]['approx_normalized'],12)+'$ & $'+num(row['truncations'][6]['approx_normalized'],12)+r'$ \\')
out.append(r'''\bottomrule
\end{tabular}
\end{center}
The derived coefficients $C_{0,0},\ldots,C_{0,4}$ and $C_{1,0},C_{1,1}$
were checked by exact symbolic algebra. The supplemental JSON also records
$C_{j,k}$ for $0\le j\le2$, $0\le k\le6$ and mixed-sector tests.

For the exact Gamma envelope $F(x)=k\Gamma(x+2)h^x$, the numerical inverse
shifts below are positive. Every index $1\le n\le200$ passed the finite
check $0<F^{-1}(a_n)-n<1/2$. The all-index statement follows from the
analytical bound in the text, not from this finite check.
\begin{center}
\begin{tabular}{rr}
\toprule
$n$ & $F^{-1}(a_n)-n$ \\
\midrule''')
for row in r['rounding']['selected_rows']:
    if row['n'] in [1,4,10,100]:
        out.append(str(row['n'])+' & $'+num(row['envelope_inverse_minus_n'],15)+r'$ \\')
out.append(r'''\bottomrule
\end{tabular}
\end{center}
Forward rounding is a different operation and already fails at $n=4$:
$F(4)=151.378352788239\ldots$, while $a_4=152$. Thus rounding $F(4)$ to
its nearest integer gives 151. The forward absolute discrepancy subsequently
grows, despite the exponentially small relative discrepancy.

For the natural interpolation, direct high-precision solution about selected
exact envelope inverses $X_*=5,10,25,50,100$ validates the signs and scale of
the first two inverse sectors. At $X_*=100$ the inverse shift is approximately
$-1.0551771299966891351\times10^{-18}$; including the second sector reduces
the observed relative error from $2.25\times10^{-18}$ to
$6.44\times10^{-36}$. These diagnostics use 138 working decimal digits.

A cautionary test at $n=500$ illustrates why fixed precision is unsuitable:
50-digit subtraction gives approximately $-4.02\times10^{21}$ instead of the
positive residual $2.4464646945801111\times10^{-5}$. No negative residual,
secondary exponent, or inverse correction should be inferred from such a
cancellation-dominated computation.
''')
(P/'validation_summary.tex').write_text('\n'.join(out)+'\n')
print(P/'validation_summary.tex')
