import GowersSzemeredi.Proofs16SpanSumCounting
import GowersSzemeredi.Proofs05ModularApproximation
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-! A dissociation bound gives small generators chosen from the original
set, with coefficients restricted to -1, 0, 1. The rank bound depends
quadratically on the original rank and logarithmically on its cutoff. -/
set_option autoImplicit false
noncomputable section
namespace LeanProofs.GowersSzemeredi
open Classical

def spanGeneratorBound (k R : Nat) : Nat :=
  ⌈16 * (k : Real)^2 + 4 * k * Real.log (2 * (R : Real) + 1)⌉₊

/-- An elementary explicit solution of the subset-sum counting inequality. -/
theorem subsetSum_count_rank_bound (d k R : Nat)
    (hcount : 2 ^ d ≤ (2 * (d * R) + 1) ^ k) :
    d ≤ spanGeneratorBound k R := by
  by_cases hd : d = 0
  · simp [hd]
  have hdpos : (0 : Real) < d := by exact_mod_cast Nat.pos_of_ne_zero hd
  have hd1 : (1 : Real) ≤ d := by exact_mod_cast Nat.one_le_iff_ne_zero.mpr hd
  have hpow : (2 : Real)^d ≤ (2 * ((d : Real) * R) + 1)^k := by exact_mod_cast hcount
  have hlog := Real.log_le_log (by positivity) hpow
  rw [Real.log_pow, Real.log_pow] at hlog
  have hbox : 2 * ((d : Real) * R) + 1 ≤ (d : Real) * (2 * (R : Real) + 1) := by nlinarith
  have hlogbox := Real.log_le_log (by positivity) hbox
  rw [Real.log_mul (by positivity) (by positivity)] at hlogbox
  have hlogsqrt : Real.log (d : Real) ≤ 2 * Real.sqrt d := by
    have h := Real.log_le_rpow_div hdpos.le (by norm_num : (0 : Real) < 1 / 2)
    rw [← Real.sqrt_eq_rpow] at h
    linarith
  have hlog2 : (1 / 2 : Real) ≤ Real.log 2 := by have := Real.log_two_gt_d9; linarith
  have hscaled := mul_le_mul_of_nonneg_left hlogbox (Nat.cast_nonneg k : (0 : Real) ≤ k)
  have hsqrt := Real.sq_sqrt hdpos.le
  have hyoung := sq_nonneg (Real.sqrt (d : Real) / 2 - 2 * k)
  have hdlog : (d : Real) / 2 ≤ k * (2 * Real.sqrt d + Real.log (2 * (R : Real) + 1)) := by
    nlinarith [mul_le_mul_of_nonneg_left hlogsqrt (Nat.cast_nonneg k : (0 : Real) ≤ k)]
  have hbound : (d : Real) ≤ 16 * (k : Real)^2 + 4 * k * Real.log (2 * (R : Real) + 1) := by
    nlinarith only [hdlog, hsqrt, hyoung]
  unfold spanGeneratorBound
  exact_mod_cast hbound.trans (Nat.le_ceil _)

/-- Mathlib's signed additive span lies in the unit-coefficient span. -/
theorem addSpan_subset_boundedFrequencySpan_one {N : Nat} [NeZero N]
    (D : Finset (ZMod N)) :
    D.addSpan ⊆ boundedFrequencySpan (fun k : D => (k : ZMod N)) 1 := by
  intro x hx
  obtain ⟨e, he, heq⟩ := Finset.mem_addSpan.mp hx
  apply (mem_boundedFrequencySpan_iff D 1 x).mpr
  refine ⟨fun k => (e k : ZMod N), fun k hk => ?_, ?_⟩
  · have h := recurrence_centeredAbs_intCast_le (N := N) (e k)
    rcases he k with hneg | hz | hpos
    · simpa [hneg] using h
    · simpa [hz] using h.trans (by norm_num [hz])
    · simpa [hpos] using h
  · simpa only [zsmul_eq_mul] using heq.symm

/-- Every subset of a bounded frequency span is generated by a small
subset of itself, with no coefficient larger than one in absolute value. -/
theorem boundedSpan_small_generators {N : Nat} [NeZero N]
    (K B : Finset (ZMod N)) (R : Nat)
    (hB : B ⊆ boundedFrequencySpan (fun k : K => (k : ZMod N)) R) :
    ∃ D : Finset (ZMod N), D ⊆ B ∧ D.card ≤ spanGeneratorBound K.card R ∧
      B ⊆ boundedFrequencySpan (fun k : D => (k : ZMod N)) 1 := by
  obtain ⟨D, hDB, hD, hspan⟩ := Finset.exists_subset_addSpan_card_le_of_forall_addDissociated
    (s := B) (d := spanGeneratorBound K.card R) (fun E hEB hdiss =>
      subsetSum_count_rank_bound E.card K.card R (dissociated_boundedSpan_count K E R (hEB.trans hB) hdiss))
  exact ⟨D, hDB, hD, hspan.trans (addSpan_subset_boundedFrequencySpan_one D)⟩

end LeanProofs.GowersSzemeredi
